я решил lesson1.task1
Kotlin-Polytech/KotlinAsFirst2016 pull request #100
Opened 2016-09-22 09:12 UTC by NanXiang1998116

2016-09-22 11:06 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +        {
Открывающая фигурная скобка должна быть после `: Double` на одной строчке с ним:

```
fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double {
    // Function source code
}
```

Intellij IDEA может автоматически отформатировать ваш код. Используйте Ctrl+Alt+L.

2016-09-22 11:07 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    (number/100)%10
Значение этого выражения -- `(number/100)%10` -- будет рассчитано, но никак не будет использовано. Вероятно, вы хотели использовать его в операторе `return`? Тогда так и надо написать: `return ...` и далее это выражение.

2016-09-22 11:08 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return number
Таким образом, результат функции будет всегда равен её параметру, что неверно. Видно на результатах работы бота.

2016-09-22 11:09 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    val x1=(initial*(1+0.01*percent))*(1+0.01*percent)*(1+0.01*percent)
Вы можете использовать функцию `Math.pow(x, 3.0)` для возведения в куб (вместо `x` следует поставить требуемое выражение).

2016-09-22 11:11 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    val x3=(sec/3600)/180.0* PI
Следует использовать вещественную константу: `3600.0`. Результат операции `sec / 3600` всегда будет целым числом, так как `sec` и `3600` -- целые. Например, для 35 секунд вы получите результат 0 после округления.

2016-09-22 11:12 UTC, mglukhikh commented
В основном всё сделано правильно. Про имеющиеся ошибки и неточности я написал вам в комментариях выше. Пожалуйста, поправьте их.

2016-09-22 11:14 UTC, mglukhikh commented
Не забывайте пользоваться тестовыми функциями в обучающем проекте. Обе ваши фактические ошибки видны и на них. Как их запускать, смотрите здесь: https://github.com/Kotlin-Polytech/KotlinAsFirst2016/blob/master/tutorial/chapter01.adoc#Упражнения.

2016-09-22 11:14 UTC, mglukhikh commented
Если вам удобнее общаться по-английски -- напишите мне об этом.

2016-09-22 11:15 UTC, NanXiang1998116 commented
Спасибо вам большое!Я поправлю ошибки потом.

четверг, 22 сентября 2016 г. пользователь Mikhail Glukhikh написал:

> В основном всё сделано правильно. Про имеющиеся ошибки и неточности я
> написал вам в комментариях выше. Пожалуйста, поправьте их.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/100#issuecomment-248873327>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA-E25PjfWHQtUIlArY8XiUWqbPD5yfks5qsmKjgaJpZM4KDrTj>
> .
>

2016-09-22 11:18 UTC, NanXiang1998116 commented
Мне удобно общаться по-русски,спасибо вам!

четверг, 22 сентября 2016 г. пользователь Mikhail Glukhikh написал:

> Если вам удобнее общаться по-английски -- напишите мне об этом.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/100#issuecomment-248873799>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA-E3I147QQba6Px7ifrBjxYPmBREoyks5qsmMagaJpZM4KDrTj>
> .
>

2016-09-22 15:27 UTC, NanXiang1998116 commented
Спасибо вам большое!Я поправлю.

четверг, 22 сентября 2016 г. пользователь Mikhail Glukhikh написал:

> В основном всё сделано правильно. Про имеющиеся ошибки и неточности я
> написал вам в комментариях выше. Пожалуйста, поправьте их.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/100#issuecomment-248873327>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA-E25PjfWHQtUIlArY8XiUWqbPD5yfks5qsmKjgaJpZM4KDrTj>
> .
>

2016-09-22 17:04 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    val x3 = (sec / 3600) / 180 * PI
Ещё раз повторяю: нужно делить на 3600.0, чтобы получить вещественный результат. Иначе произойдёт округление до целого, и вы получите 0

2016-10-03 16:33 UTC, mglukhikh requested changes
Ваш код не компилируется -- смотрите замечания. Впредь, пожалуйста, проверяйте ваши исправления на тестах в учебном проекте перед отправкой нам. Кроме этого, не забудьте исправить прежние замечания.

2016-10-03 16:33 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    }
Функция должна знать, что ей делать, если ни одно из ваших условий не выполнено -- в конце тоже должен стоять `return`. Поскольку он отсутствует, происходит ошибка компиляции. Кроме этого, фигурную скобку следует сдвинуть на 4 пробела назад.

2016-10-03 16:33 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +import lesson6.task2.kingMoveNumber
Удалите два последних импорта, вам они ни к чему

2016-10-03 16:33 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +
Это решение кажется неверным. Увидим точно, когда вы исправите ошибку компиляции

2016-10-03 18:59 UTC, NanXiang1998116 commented
Здравствуйте.Перед тем,как я отправил мою работу,я уже проверил на
тестах.Там не показалось ошибки.Я не понимаю почему.В прошлый раз у меня
тоже такая же ситуация.

понедельник, 3 октября 2016 г. пользователь Mikhail Glukhikh написал:

> *@mglukhikh* requested changes on this pull request.
>
> Ваш код не компилируется -- смотрите замечания. Впредь, пожалуйста,
> проверяйте ваши исправления на тестах в учебном проекте перед отправкой
> нам. Кроме этого, не забудьте исправить прежние замечания.
> ------------------------------
>
> In src/lesson2/task1/IfElse.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/100#pullrequestreview-2556300>
> :
>
> > +        if ((b - a) > (d - c)) {
> +            if (c > b && b > d) return (b - c)
> +            if (c < a && d > b) return (d - c)
> +            if (c > a && a > d) return (d - a)
> +        }
> +        if ((b - a) == (d - c)) {
> +            if (c > b || c == b) return -1
> +            if (b > c && c > a) return (b - c)
> +            if (a == c) return (b - a)
> +            if (d > a && a > c) return (d - a)
> +        }
> +    }
> +    if (a == b && c == d) return -1
> +    if (a == b && c != d) return -1
> +    if (c == d && a != b) return -1
> +    }
>
> Функция должна знать, что ей делать, если ни одно из ваших условий не
> выполнено -- в конце тоже должен стоять return. Поскольку он отсутствует,
> происходит ошибка компиляции. Кроме этого, фигурную скобку следует сдвинуть
> на 4 пробела назад.
> ------------------------------
>
> In src/lesson2/task1/IfElse.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/100#pullrequestreview-2556300>
> :
>
> >  package lesson2.task1
>
>  import lesson1.task1.discriminant
> +import lesson4.task1.abs
> +import lesson6.task2.kingMoveNumber
>
> Удалите два последних импорта, вам они ни к чему
> ------------------------------
>
> In src/lesson2/task1/IfElse.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/100#pullrequestreview-2556300>
> :
>
> > @@ -56,7 +76,16 @@ fun timeForHalfWay(t1: Double, v1: Double,
>   */
>  fun whichRookThreatens(kingX: Int, kingY: Int,
>                         rookX1: Int, rookY1: Int,
> -                       rookX2: Int, rookY2: Int): Int = TODO()
> +                       rookX2: Int, rookY2: Int): Int {
> +    if ((rookX1 - kingX == 1) && (rookY1 == kingY) && (rookX2 - kingX >= 1) && (rookY2 - kingY >= 1)) return 1
> +    if ((rookX2 - kingX == 1) && (rookY2 == kingY) && (rookX1 - kingX >= 1) && (rookY1 - kingY >= 1)) return 2
> +    if ((rookY1 - kingY == 1) && (rookX1 == kingX) && (rookX2 - kingX >= 1) && (rookY2 - kingY >= 1)) return 1
> +    if ((rookY2 - kingY == 1) && (rookX2 == kingX) && (rookX1 - kingX >= 1) && (rookY1 - kingY >= 1)) return 2
> +    if ((rookX1 - kingX >= 1) && (rookY1 - kingY >= 1) && (rookX2 - kingX >= 1) && (rookY2 - kingY >= 1)) return 0
> +    else return 3
> +
>
> Это решение кажется неверным. Увидим точно, когда вы исправите ошибку
> компиляции
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/100#pullrequestreview-2556300>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA-E1TxgYGXJYjWsc5DtEzqkJfvjpENks5qwS5OgaJpZM4KDrTj>
> .
>

2016-10-03 19:50 UTC, mglukhikh commented
Повторяю ещё раз. Строчка 143 файла `IfElse.kt`.

Функция должна знать, что ей делать, если ни одно из ваших условий не выполнено -- в конце тоже должен стоять return. Поскольку он отсутствует, происходит ошибка компиляции. Кроме этого, фигурную скобку следует сдвинуть на 4 пробела назад.

Если вы не исправите это замечание, программа компилироваться не будет.

2016-10-15 19:34 UTC, mglukhikh commented
recheck all

2016-10-15 19:46 UTC, mglukhikh reviewed
По первым двум урокам всё верно, за исключением задачи `ageDescription`. Попробуйте поправить её решение (если вам для этого не хватает знаний русского языка, можем закрыть на это глаза). Третий урок посмотрю чуть позже.

2016-10-15 19:46 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        else if((rookX1 != kingX && rookY1 != kingY) && (rookX2 != kingX && rookY2 != kingY)) return 0
Решение верное, но оба `else if` следует сдвинуть на 4 пробела назад -- они должны быть на одном уровне с верхним `if`. Кроме этого, решение можно улучшить, если создать логические переменные "угроза от 1-й ладьи" и "угроза от 2-й ладьи" и в условиях использовать уже их -- получится короче, проверьте.

2016-10-15 19:46 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (c >= a && b <= d && b >= c) return (b - c)
Да, с этим решением я согласен

2016-10-15 19:46 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +
Бот справедливо выдаёт для этой задачи ошибки для `age = 1` и `age = 21`. Должно быть "1 год", "21 год". Кроме этого, сравнение на неравенство -- это `!=`, а `!==` это сравнение на неравенство ссылок и используется очень редко (эту тему мы обсуждали на лекции на прошлой неделе). Старайтесь использовать `!=`.

2016-10-15 19:58 UTC, mglukhikh commented
recheck all

2016-10-15 20:14 UTC, mglukhikh commented
По третьему уроку -- пожалуйста, запустите тесты, которые имеются для него в обучающем проекте. Убедитесь, что они проходят нормально. Если тесты выдают ошибки или зацикливаются -- посмотрите внимательно свои решения задач из этого урока.

2016-10-27 12:27 UTC, mglukhikh commented
recheck all

2016-10-27 12:29 UTC, mglukhikh commented
recheck all

2016-10-27 12:30 UTC, mglukhikh commented
recheck all

2016-10-28 07:39 UTC, mglukhikh requested changes
Довольно много ошибок в решениях, есть также замечания по стилю. Главное, что нужно сделать -- найти и исправить все имеющиеся бесконечные циклы -- с ними бот не может нормально проверить ваши решения. Убедитесь, что для всех уроков с 1-го по 4-й проходят тесты в учебном проекте. Если они запускаются и не останавливаются -- это означает, что где-то есть бесконечный цикл. Затем исправьте замечания. 4-й урок потом посмотрю ещё раз.

2016-10-28 07:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +
Эта задача по-прежнему решена ошибочно

2016-10-28 07:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        else if((rookX1 != kingX && rookY1 != kingY) && (rookX2 != kingX && rookY2 != kingY)) return 0
Сдвиньте оба else if на 4 пробела назад, пожалуйста (Shift-TAB в IDEA). Кроме этого, вы по нескольку раз проверяете одни и те же условия. Введите вспомогательные переменные "угроза от 1-й ладьи", "угроза от 2-й ладьи", чтобы этого избежать.

2016-10-28 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Это решение неверное. Одно из возможных решений -- уменьшать `n` в 10 раз до тех пор, пока не получите 0, и считать, сколько раз удалось поделить на 10

2016-10-28 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Этот цикл может быть бесконечным. Задачу можно решить перебором всех возможных делителей, начиная с 2.

2016-10-28 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Подобные циклы гораздо более понятным образом записываются через `for`, например: `for (x in n-1 downTo 1) { ... }`.

2016-10-28 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +}
Здесь и в `lcm` вы используете расчёт наибольшего общего делителя (gcd, greatest common divisor). Вынесите его в отдельную функцию. Кроме этого, `if (x) return true else return false` эквивалентно `return x`

2016-10-28 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Это решение неверное, цикл может быть бесконечным. Попробуйте определить, существует ли целое число между корнем из m и корнем из n.

2016-10-28 07:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +
Бессмысленные пустые строки здесь и далее не украшают код

2016-10-28 07:39 UTC, mglukhikh commented
Новых задач пока делать не нужно -- очень много ошибок в старых.

2016-11-02 09:22 UTC, mglukhikh requested changes
Тесты работают, и это прекрасно. Осталось исправить замечания по стилю

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +
Уберите лишние пустые строки, здесь в них нет особенного смысла

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +
И здесь тоже

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +
И здесь тоже

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +
И здесь тоже

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +
И здесь тоже ненужные пустые строки

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +
И здесь тоже

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    k--
Такой трюк с `k--` и `k++` выглядит довольно уродливо, в нём нет особой необходимости. Вы можете написать цикл `for` по `k` и перебрать возможные делители

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +
Много ненужных пустых строк

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        else x--
Дополнительная переменная `x` здесь не нужна, достаточно использовать `k`

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +}
Повторно! Здесь и в lcm вы используете расчёт наибольшего общего делителя (gcd, greatest common divisor). Вынесите его в отдельную функцию. Кроме этого, `if (x) return true else return false` эквивалентно `return x`

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +
Много ненужных пустых строк

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var k = 0.0
Действительно ли необходимо начинать перебор с 0?

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        x = (list.sum()) / (list.size * 1.0)
Умножение на 1.0 здесь не нужно, так как `list.sum()` -- уже вещественное число. Кроме этого, не нужна переменная `x`: можно сразу написать `return list.sum() / list.size`

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        x = (list.sum()) / (list.size * 1.0)
Не нужно умножение на 1.0

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +
Много ненужных пустых строк

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +
Много ненужных пустых строк

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        t++
Здесь лучше написать `else t++` и убрать `t--` двумя строчками выше

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +
Много ненужных пустых строк

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Не нужно здесь дублировать функцию `factorize`, просто вызовите её.

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val N = mutableListOf<Int>()
Неудачное имя

2016-11-02 09:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Переворачивание списка можно выполнить с помощью `list.reversed()`.

2016-11-04 19:01 UTC, mglukhikh commented
Часть замечаний вы исправили, но не все. Закончите исправления, пожалуйста. Все замечания вы можете посмотреть на вкладке Files Changed.

2016-11-07 16:29 UTC, mglukhikh commented
Подсказка. Чему равен наибольший общий делитель двух взаимно простых чисел? (это к isCoPrime). Также, пожалуйста, исправьте сломавшиеся тесты (см. отчёт бота)

2016-11-10 10:58 UTC, mglukhikh approved these changes

2016-11-10 10:59 UTC, mglukhikh commented
Спасибо. Первые четыре урока приняты.

2016-11-10 10:59 UTC, closed without merging