Решение задач урок 1,2
Kotlin-Polytech/KotlinAsFirst2016 pull request #101
Opened 2016-09-22 09:31 UTC by buithuynhung

2016-09-22 10:42 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +
Просьба не делать изменений, не относящихся к сути решаемой задачи, так как они усложняют объединение изменений нескольких разработчиков вместе

2016-09-22 10:43 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +   val dlina_metr=sagenes*48*4.445*0.01+arshins*16*4.445*0.01+vershoks*4.445*0.01
* Именовать переменные транслитом --- **очень плохой** стиль программирования
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`
* Выражение можно упростить с использованием правил арифметики

2016-09-22 10:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double =(grad*3.14/180+min*3.14/(180*60)+sec*3.14/(180*3600))
Число PI имеет несколько больше значащих цифр после запятой, чем `3.14`. Используйте `Math.PI`.

2016-09-22 10:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val dlina_otreska= sqrt(sqr(x2-x1)+sqr(y2-y1))
См. замечания к `lengthInMeters`

2016-09-22 10:47 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val minutes= hoursArrive*60+minutesArrive-(hoursDepart*60+minutesDepart)
См. замечания к `lengthInMeters`

2016-09-22 10:48 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val money1=percent*initial*0.01
Данную формулу можно записать проще

2016-09-22 10:48 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val number= (number-(number/10)*10)*100+(number/10-(number/100)*10)*10+(number/100)
См. замечания к `lengthInMeters`

2016-09-22 10:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +   else return "199 лет"
Простите, что это такое?

2016-09-22 10:50 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val s=t1*v1+t2*v2+t3*v3
Повторно используемые выражения лучше вынести в отдельные переменные

2016-09-22 10:50 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val number1=(sqr(b)+sqr(c)-sqr(a))/(2*b*c)
Переменным лучше давать говорящие имена

2016-09-22 10:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((number1>0.0&&number1<1.0) && (number2>0.0 && number2<1.0) && (number3>0.0 && number3<1.0)) return 0
Логику можно упростить, если считать косинус только наибольшего угла

2016-09-22 10:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if(b<c || a>d) return -1
Данное выражение лучше оформить как `when`

2016-09-22 10:51 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if(sum1==sum2)return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-22 10:51 UTC, ice-phoenix requested changes

2016-09-22 11:24 UTC, mglukhikh commented
Автору: пожалуйста, напишите здесь ваше полное имя и номер группы. Нам необходимо знать, кто вы.

To the author: please write here your full name and the student group number.

2016-09-22 17:56 UTC, buithuynhung commented
Буй Тхюи Ньунг в группе 13531/1)

2016-09-22 19:42 UTC, buithuynhung commented
Спасибо вам большое!!! Я исправляю мои ошбки )

2016-09-28 16:30 UTC, ice-phoenix requested changes

2016-09-28 16:30 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val t= hoursArrive*60+minutesArrive-(hoursDepart*60+minutesDepart)
Просьба отформатировать код при помощи IntelliJ IDEA и в дальнейшем придерживаться такого же стиля

2016-09-28 16:30 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +{
Открывающая фигурная скобка перед телом функции обычно ставится на одной строке с заголовком функции

2016-09-28 16:30 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val m = (sqr(1+percent*0.01)*(1+percent*0.01))
Лучше либо написать и воспользоваться функцией возведения в куб, либо применить `Math.pow`

2016-09-28 16:30 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val x1=(sqr(b)+sqr(c)-sqr(a))/(2*b*c)
Достаточно посчитать косинус угла, противолежащего наибольшей стороне

2016-09-28 16:30 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        return if ((x < d && d < y) || (d == y) || (d > y)) false else true
Выражение `if (cond) false else true` можно заменить на ` ! cond`

2016-09-28 16:30 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if(n == Int.MAX_VALUE) return 10
Данное выражение лучше оформить как `when`

2016-09-28 16:30 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n){
Нет ли более точной верхней границы для возможного значения делителя числа `n`?

2016-09-28 16:30 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var s = 0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-09-29 09:51 UTC, ice-phoenix requested changes
Просьба исправлять замечания преподавателей перед подачей новых PR

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    println("b: $b")
Если вы хотели проверить, как работает ваша функция из `lesson3`, более правильно было бы
* либо написать для нее тест
* либо написать функцию `main` прямо в `lesson3`

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val t= (hoursArrive - hoursDepart)*60 + minutesArrive - minutesDepart
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val p = pow( 1+percent*0.01,3.0)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val result = (number - (number / 10) * 10) * 100 + (number / 10 - (number / 100) * 10) * 10 + (number / 100)
Выражения, соответствующие отдельным цифрам, лучше вынести в переменные с говорящими именами

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val x1=(sqr(b)+sqr(c)-sqr(a))/(2*b*c)
Достаточно посчитать косинус угла, противолежащего максимальной стороне треугольника

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return if(a == b) true else false
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        return if ((x < d && d < y) || !(d<y)) false else true
Выражение `if (cond) false else true` можно заменить на ` ! cond`

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i % n==0 && i % m==0){
Нет ли более быстрых алгоритмов поиска НОК?

2016-09-29 09:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (b < c || a > d)          -> -1
Данный набор условий можно упростить

2016-10-12 10:15 UTC, ice-phoenix commented
Исправляйте, пожалуйста, замечания к предыдущим урокам перед тем, как решать следующие.

2016-10-12 10:17 UTC, ice-phoenix requested changes

2016-10-12 10:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if(v.isEmpty()) return 0.0
Если список пустой, сколько раз будет выполнено тело цикла ниже? Имеет ли смысл данная проверка?

2016-10-12 10:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    else return list.sum()/list.size
Форматирование кода

2016-10-12 10:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if ( p.isEmpty() ) return 0.0
См. замечание к функции `abs`

2016-10-12 10:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if ( list.isEmpty() ) return mutableListOf()
В задании сказано, что пустой список изменять не следует

2016-10-13 13:45 UTC, ice-phoenix requested changes
Исправляйте замечания к предыдущим урокам перед тем, как делать следующие

2016-10-13 13:45 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +//14916253649648110012114416919622525628932436140044148452957665267672978484190096110241089
Что это такое?

2016-10-13 13:45 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int=(hours*3600+minutes*60+seconds)
Просьба отформатировать код при помощи IntelliJ IDEA и в дальнейшем придерживаться такого же стиля форматирования

2016-10-13 13:45 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +       ((age % 10 < 5) && (age % 100 !in 11..14) && (age % 10 != 0)) -> "$age года"
Это условие можно выразить проще

2016-10-13 13:45 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (s1 > (s / 2)) return s / (2 * v1)
Данное выражение лучше оформить как `when`

2016-10-13 13:45 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if( hyp == a ) {
Форматирование кода

2016-10-13 13:45 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val a=number/1000+number/100-(number/1000)*10
Форматирование кода

2016-10-20 11:55 UTC, ice-phoenix requested changes
Исправляйте предыдущие замечания перед работой над следующими уроками

2016-10-20 11:55 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +import lesson3.task1.squareSequenceDigit
Зачем вам эти импорты здесь?

2016-10-20 11:55 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        (hoursArrive - hoursDepart)*60 + minutesArrive - minutesDepart
Форматирование кода должно быть единообразным везде. Если вы отделяете различные операции и операнды пробелами, делайте это везде. Попробуйте отформатировать ваш код при помощи IntelliJ IDEA и придерживаться такого стиля форматирования дальше.

2016-10-20 11:55 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +       ((age % 10 < 5) && (age % 100 !in 11..14) && (age % 10 != 0)) -> "$age года"
Это условие все еще можно выразить проще

2016-10-20 11:55 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (m%i == 0 && n%i ==0) return false
Можно ли решить эту задачу при помощи других функций, разработанных вами в этом модуле?

2016-10-20 11:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        element+= list[i]
[Здесь и много еще где] Исправляйте форматирование

2016-10-27 12:15 UTC, buithuynhung commented
Почему lesson5.task1/bestLongJump не работает? В моем тесте 2147483647 получилось, не -1

2016-10-27 13:28 UTC, ice-phoenix requested changes

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +/*fun timeStrtoSeconds(str: String): Int {
Устаревшие комментарии лучше удалять

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        n == 0 -> 1
Почему эти две проверки не сделать перед циклом, чтобы не делать лишнюю работу?

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            k = i
Почитайте про более быстрые алгоритмы поиска НОК

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Нет ли более точной верхней границы возможных делителей числа `n`, не равных `n`, чем `n`?

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            k = i
Можно обойтись без переменной `k`, если возвращать результат сразу

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var s = 0
Это замечание все еще в силе

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        s += c
Нет ли у вас уже готовой функции, которая считала бы вам `c`?

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (s == n) return b % 10
Зачем данная проверка?

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        sum += v[i] * v[i]
Если вам не нужен индекс, то лучше использовать циклы в foreach-стиле
```
for (e in list) {
    foo(e)
}
```

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var str: String
Зачем вам эта переменная?

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var numb: Int
Зачем вам эта переменная?

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val month_names = listOf<String>("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
* В Котлине принят `camelCase`
* Можно просто `listOf(...)`

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            else "${twoDigitStr(parts[0].toInt())}.${twoDigitStr(month_numbers)}.${parts[2].toInt()}"
Составные части даты лучше вынести в отдельные переменные

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                if (month_numbers == parts[1].toInt()) return parts[0].toInt().toString() + " " + month + " " + parts[2]
Зачем такой сложный цикл? Почему нельзя просто достать название месяца по его индексу?

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val parts = phone.filter { it != '-' && it != ' ' && it != '(' && it != ')' }
Можно проще через `it !in "..."`

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    else parts1
Не следует строить свой алгоритм таким образом, чтобы он постоянно работал с разными переменными, полученными друг из друга. Намного понятнее, если сразу после построения какой-либо переменной вы выполняете все связанные с ней проверки, а потом уже идете дальше, если все в порядке.

2016-10-27 13:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        result = parts.map { it.toInt() }
Каким образом ваш алгоритм учитывает успешность или неуспешность попытки?

2016-11-01 14:23 UTC, ice-phoenix requested changes
Ваши дальнейшие уроки **не будут проверяться** до тех пор, пока вы не исправите все замечания

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return if (n == Int.MAX_VALUE) 10 else if (n == 0) 1
Данное выражение лучше оформить как `when`

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n / 2) {
Перепишите эту функцию в стиле `maxDivisor` без ненужных переменных

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqRoot_m = Math.sqrt(m.toDouble()).toInt()
В Котлине принят `camelCase`

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqRoot_n = Math.sqrt(n.toDouble()).toInt()
Округлять переменные лучше при помощи специальных функций `floor / ceil / round`

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (k * k >= m && k * k <= n) return true
Если вы воспользуетесь правильными функциями для округления, можно будет обойтись без цикла

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var digit: Int
Почему эта переменная объявлена здесь, а не в цикле?

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        else -> n
Что?

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var numb = ""
Лучше воспользоваться списком строк или `StringBuilder`

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (char in alphabet) digits += alphabet.indexOf(char) + 10
Лучше проверять наличие или отсутствие символа в строке через результат `indexOf(...)`

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            val Day = parts[0].toInt()
`camelCase`

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            val Month: Int = month_names.indexOf(parts[1]) + 1
* Система типов Котлина выведет тип переменной автоматически

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val result: List<Int>
Почему эта переменная объявлена здесь?

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return result.max() ?: -1
`return` можно писать внутри `try`

2016-11-01 14:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            val Day = parts[0].toInt().toString()
См. замечания выше

2016-11-03 10:46 UTC, buithuynhung commented
recheck all

2016-11-03 10:46 UTC, buithuynhung commented
recheck all

2016-11-07 12:12 UTC, ice-phoenix requested changes

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +import lesson3.task1.squareSequenceDigit
Зачем вам здесь эти два импорта?

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = (sagenes * 48 + arshins * 16 + vershoks) * 0.04445
Длинные строки принято разбивать на несколько более коротких, например, здесь можно начать новую строку после знака `=` в объявлении функции

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return m * n / min
Вычисление GCD следует вынести в отдельную функцию

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = (lcm(m, n) == m * n)
Через GCD это условие выражается несколько проще

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqRoot_m = Math.ceil(Math.sqrt(m.toDouble())).toInt()
В Котлине для именования переменных принят `camelCase`

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return sqRoot_n - sqRoot_m >= 0
:+1:

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var s = 0
Да-да, переменные все еще следует переименовать так, чтобы по их названию было примерно понятно, в чем заключается их смысл с точки зрения решаемой задачи

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        s += c
Это замечание все еще в силе

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return s
Лучше сразу `return list.sum() / list.size`

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val numb: StringBuilder = StringBuilder("")
* Система типов Котлина выведет тип переменной автоматически

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun decimal(digits: List<Int>, base: Int): Int = polynom(digits.map { it.toDouble() }.reversed(), base.toDouble()).toInt()
:+1:

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val index = alphabet.indexOf(char)
Лучше воспользоваться ассоциативным массивом или свойствами букв `a-z`

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return if (month == 0) ""
Лучше как
```
if (month == 0) return ""
return "$..."
```

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            val day = parts[0].toInt().toString()
Зачем `toString()`?

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return if (monthNumbers in 1..12) {
Как и выше, лучше сперва проверки и `return ""`, если данные невалидны, и `return "$..."`, если все хорошо

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                day + " " + month + " " + parts[2]
Почему вы не проверяете `parts[2]` на валидность?

2016-11-07 12:12 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val parts1 = parts.filter { it != '+' }
Зачем вам переменная `parts1`?

2016-11-16 14:15 UTC, ice-phoenix requested changes

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = ((grad + min / 60.0 + sec / 3600.0) * Math.PI / 180.0)
Лишние скобки вокруг законченных выражений

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun GCD(m: Int, n: Int): Int {
В Котлине для именования переменных принят `camelCase`

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqRoot_m = Math.ceil(Math.sqrt(m.toDouble())).toInt()
Это замечание все еще актуально

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (digitNumb == n) return sq % 10
Зачем эта проверка?

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                return "$day " + month + " " + parts[2]
Почему здесь вы не используете string interpolation?

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (parts in " +") return ""
`in` работает несколько не так, как вы ожидаете здесь

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return numb
Форматирование кода

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun lineByPoints(a: Point, b: Point): Line = Line(a, Math.atan((a.y -b.y)/(a.x - b.x)))
Форматирование кода

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    val line = lineByPoints(a, b)
Форматирование кода

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    val angle :Double
Почему вы разделили определение и объявление этой переменной?

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var mindist = circles[0].distance(circles[1]) + 1
Форматирование кода

2016-11-16 14:15 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        if (inside() == false) return ""
`!inside()`

2016-11-21 08:28 UTC, mglukhikh commented
recheck all

2016-11-21 08:49 UTC, mglukhikh commented
Обращаю внимание @buithuynhung и @ice-phoenix , что какие-то тесты, похоже, зависли в бесконечном цикле.

2016-11-21 13:17 UTC, ice-phoenix commented
Ваша реализация `kingTrajectory` зависает, проверьте, пожалуйста, ее локально на различных входных данных.

2016-11-21 19:56 UTC, buithuynhung commented
Спасибо вам вольшое! Я уже исправила )

2016-11-22 16:26 UTC, ice-phoenix commented
recheck all

2016-11-22 17:15 UTC, ice-phoenix requested changes

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val hyp = Math.max(ab, c)
Можно сразу как `Math.max(Math.max(a, b), c)`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        val x = r2 - r1
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun GCD(m: Int, n: Int): Int {
`gcd`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqRoot_n = Math.floor(Math.sqrt(n.toDouble())).toInt()
Можно обойтись без `toInt()`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        digitNumb += c
Можно сразу `digitNumb += digitNumber(sq)`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val monthNames = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список лучше вынести на верхний уровень

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (monthNumbers in 1..12) {
Лучше сделать как в предыдущей функции --- ранний выход в случае ошибки формата

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (parts[i] == parts[i + 1])
Лучше оформить алгоритм так, чтобы он работал одновременно только с одной парой соседних индексов, а не с двумя, как у вас

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var mindist = circles[0].distance(circles[1]) + 1
Зачем `... + 1`???

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    when {
`when { return ... }` ==> `return when { ... }`
one-liner

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if (moveNumb == 0) return result
Данное выражение лучше оформить как `when`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if (moveNumb == -1) return listOf()
Данное выражение лучше оформить как `when`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            square.row < end.row && square.column < end.column -> Square(square.column + 1, square.row + 1)  //
Все это можно значительно упростить, если почитать про `Int.compareTo(Int)`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (result != null) return result else throw IllegalArgumentException()
???

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?) = other is MatrixImpl<*> && height == other.height && width == other.width
Почему не проверяется содержимое матрицы на равенство?

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        return result
См. замечание к `equals`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        sb.append("]")
Можно еще сделать вывод строк как отдельных строк

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        return "$sb"
Лучше через `toString()`

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +import lesson2.task1.timeForHalfWay
Зачем?

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    for (i in 0..transpose.height - 1) for (j in 0..transpose.width - 1) {
Форматирование кода

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    val result = createMatrix(matrix.height, matrix.width, matrix[0, 0])
Зачем `matrix[0, 0]`?

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    for (i in 0..size - 1) for (j in 0..size - 1) if (matrix[i, j] !in 1..size) return false
Форматирование кода

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        list.clear()
Почему бы просто не заводить новый список каждый раз? А лучше `Set`.

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    return true
Почему все три проверки нельзя сделать в рамках одного и того же цикла?

2016-11-22 17:15 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    for (i in 0..matrix.height - 1) for (j in 0..matrix.width - 1) {
Форматирование кода

2016-11-23 12:07 UTC, ice-phoenix requested changes

2016-11-23 12:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqRoot_m = Math.ceil(Math.sqrt(m.toDouble()))
`camelCase`

2016-11-23 12:07 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            square.row < end.row && square.column < end.column -> Square(square.column + 1, square.row + 1)
А теперь подумайте, нет ли соответствия между результатами `compareTo` и тем, `+1/-1` вы делаете

2016-11-23 12:07 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        if (height == 1 || width == 1) break
Почему эту проверку не сделать раньше? И нужна ли она вообще?

2016-11-23 12:07 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                    result[row, column] += matrix[i, j]
Нельзя ли при подсчете этой суммы переиспользовать результаты расчета предыдущих шагов?

2016-11-25 15:05 UTC, ice-phoenix requested changes

2016-11-25 15:05 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean = number / 1000 + number / 100 - (number / 1000) * 10 == number / 10 - (number / 100) * 10 + number - (number / 10) * 10
Длинная строка

2016-11-25 15:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (parts in " +") return ""
Все еще актуально

2016-11-25 15:05 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    return result
Поговорите с преподавателем на занятиях, как лучше реализовать эту функцию

2016-11-25 15:05 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    list.add(end)
Тут тоже лучше поговорить с преподавателем

2016-11-25 15:05 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        square = Square(square.column - column, square.row - row)
А вот это здорово =)

2016-11-25 15:05 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        return result
Все еще очень актуально

2016-11-25 15:05 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        var boolean = true
Ужасное название для переменной, ничего не говорить о том, зачем она

2016-11-25 15:05 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        var boolean = true
И кстати, зачем она?

2016-12-05 20:20 UTC, ice-phoenix commented
recheck all

2016-12-05 20:22 UTC, ice-phoenix requested changes
Есть довольно приличное количество старых, но еще не исправленных замечаний

2016-12-05 20:22 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (i in 1..parts.length - 1) if (phone[i] == '+') return ""
Для этого есть `any / all`, который вы, между прочим, используете строчкой ниже

2016-12-05 20:22 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (parts.any { it !in '0'..'9' && it != '+' } || parts == "+") return ""
Зачем вторая часть проверки?

2016-12-07 10:05 UTC, mglukhikh commented
В восьмом уроке, разница в результатах -- в лишнем переводе строки

2016-12-09 10:49 UTC, ice-phoenix commented
recheck all

2016-12-09 11:36 UTC, mglukhikh commented
recheck all

2016-12-09 11:40 UTC, mglukhikh commented
Вы бы поправили ошибку в `timeForHalfWay` во втором уроке. В восьмом в `sibilants` опять разница в переводе строки. И есть ещё чуть-чуть неисправленных замечаний на вкладке Files Changed.

2016-12-09 12:43 UTC, ice-phoenix requested changes

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = (sagenes * 48 + arshins * 16 + vershoks) * 0.04445
Все еще актуально

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val number3 = number / 100
Все эти цифры можно получить проще, если вспомнить про операцию взятия остатка от деления

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    ((age % 10 in 1..4) && (age % 100 !in 11..14)) -> "$age года"
Лишние скобки вокруг законченных выражений + второе условие можно слегка уменьшить, если учесть, что вы проверили строчкой выше

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        return !((r2 - r1 < centerDist && centerDist < r2 + r1) || centerDist > r2 + r1)
Это условие можно упростить, а потом можно упростить и всю функцию

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    else {
Можно обойтись без ветки `else`, так как в ветке `then` вы выходите из функции

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val numb = StringBuilder("")
Можно просто `StringBuilder()`

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                return ""
Здесь можно обойтись и без фигурных скобок, как вы делаете выше, например

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun circleByDiameter(diameter: Segment): Circle = Circle(Point((diameter.begin.x + diameter.end.x) / 2, (diameter.begin.y + diameter.end.y) / 2), diameter.begin.distance(diameter.end) / 2)
Длинная строка

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        return Point((a1 + a2) / c, (b1 + b2) / c)
Что будет, если углы прямых равны?

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var mindist = circles[0].distance(circles[1]) + 1
Все еще актуально

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    list.add(end)
Все еще актуально

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?) = other is MatrixImpl<*> && height == other.height && width == other.width && list == other.list
Очень длинная строка

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[row, column])
Как будем отличать один элемент от другого при печати?

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            result[j, i] = digit++
Форматирование кода

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    return Holes(rows, columns)
Форматирование кода

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                    result[row, column] += matrix[i, j]
Все еще актуально

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +            indexOfStr = text.indexOf(str.toLowerCase(), index + 1)
Может быть, перевод в нижний регистр можно сделать один раз?

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +    val map = mapOf<String, String>("Ы" to "И", "Я" to "А", "Ю" to "У", "ы" to "и", "я" to "а", "ю" to "у")
Можно не указывать тип generic'ов

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        if (line.isEmpty()) outputStream.newLine()
Может быть, тут можно сделать что-то еще, раз строка пустая?

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        if (line != lines.last()) outputStream.newLine()
Поговорите с преподавателем, как лучше сделать то, что вы здесь пытаетесь сделать

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +            if (line[i - 1] in "жчшщЖЧШЩ" && line[i] in "ыяюЫЯЮ")
Перечитайте задание внимательнее, требуется несколько более точная проверка

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        if (lines.size != 1 && line != lines.last()) outputStream.newLine()
См. замечание выше

2016-12-09 12:43 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        if (line.trim().length > maxLength) maxLength = line.trim().length
Форматирование кода

2016-12-15 19:59 UTC, mglukhikh commented
recheck all

2016-12-16 23:52 UTC, buithuynhung commented
recheck all

2016-12-16 23:53 UTC, buithuynhung commented
recheck all

2016-12-18 19:19 UTC, ice-phoenix commented
recheck all

2016-12-18 19:33 UTC, ice-phoenix requested changes

2016-12-18 19:33 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        if (c == 0.0) throw IllegalArgumentException()
Проверять на точное равенство с `0.0` --- не очень хорошая идея

2016-12-18 19:33 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[row, column])
Все еще актуально

2016-12-18 19:33 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    val matr = createMatrix(matrix.height + 1, matrix.width + 1, 0)
Зачем вам здесь вторая матрица?

2016-12-18 19:33 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        val str1 = str.toLowerCase()
Очень плохие имена переменных

2016-12-18 19:33 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        if (line.trim().length > maxLength) maxLength = line.trim().length
Повторно используемое выражение следует выносить в переменную

2016-12-18 19:33 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        if (lines.size != 1 && line != lines.last())
Зачем?

2016-12-18 19:35 UTC, ice-phoenix commented
Несмотря на все еще имеющиеся замечания, у вас "Отлично". Мои поздравления!

2016-12-18 19:45 UTC, buithuynhung commented
@ice-phoenix Спасибо вам большое!!!!!!

2017-07-26 18:24 UTC, closed without merging