lesson1-2
Kotlin-Polytech/KotlinAsFirst2016 pull request #112
Opened 2016-09-26 16:15 UTC by fav77

lesson1: comp
lesson2.1:comp
lesson2.2:comp

2016-09-27 09:57 UTC, belyaev-mikhail commented
В ваших решениях присутствуют ошибки. Их следует исправить.

2016-09-27 09:57 UTC, belyaev-mikhail commented
recheck assignment

2016-09-27 10:01 UTC, belyaev-mikhail requested changes

2016-09-27 10:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = (sagenes * 48 + arshins * 16 + vershoks)* 4.445/100
Длинные сроки, не влезающие в экран, в коде недопустимы, их следует переносить.

2016-09-27 10:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad+min/60.0+sec/(60.0*60))/(180/PI)
Длинные сроки, не влезающие в экран, в коде недопустимы, их следует переносить.

2016-09-27 10:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun thirdDigit(number: Int): Int {
Следует корректно форматировать код. Закрывающая скобка функции ставится на отдельной строке.

2016-09-27 10:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return a*100+b*10+c }
Аналогично

2016-09-27 10:01 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if (hS <= (v1*t1 + v2*t2)) return t1 + ((hS - v1 * t1) / v2)
Следует придерживаться *единого* стиля форматирования кода. Если вы ставите пробелы до и после знаков, то следует их ставить **везде**. Если не ставите &mdash; их не следует ставить **нигде**.

2016-09-27 10:01 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +                                   else return -1 }
См. комментарий про форматирование

2016-09-27 10:01 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    return false }
См. комментарий про форматирование

2016-09-28 10:25 UTC, belyaev-mikhail commented
Почему у вас в одном PR коммиты от разных людей?
Как говорят учителя в школе, "оценку мы тоже на двоих делить будем"?

2016-09-28 14:33 UTC, belyaev-mikhail requested changes

2016-09-28 14:33 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        var div = n - 1
Отступы в коде должны быть консистентными

2016-09-28 14:33 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        var div = 2
Отступы в коде должны быть консистентными

2016-09-28 14:33 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +                        return result
Отступы в коде должны быть консистентными

2016-09-28 14:34 UTC, belyaev-mikhail commented
Исправьте, пожалуйста, замечания по оформлению.

2016-09-29 17:34 UTC, fav77 commented
Прошу прощение за такое количество работ ("Push & Commit") . Это произошло из-за зависания программы.

2016-09-29 17:51 UTC, belyaev-mikhail commented
recheck all

2016-09-29 17:57 UTC, belyaev-mikhail requested changes

2016-09-29 17:57 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if (((Math.sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2))) + r1) <= r2) return true
Конструкция `if (x) return true else return false` лишена смысла, т.к. ничем не отличается от просто `return x`

2016-09-29 17:57 UTC, closed without merging