Lesson 1 : 1,2,4,5,6,8
Kotlin-Polytech/KotlinAsFirst2016 pull request #113
Opened 2016-09-26 18:06 UTC by pentagon1337

Lesson 2 task2: 1

2016-09-27 09:56 UTC, belyaev-mikhail requested changes

2016-09-27 09:56 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int =((minutesArrive+60*hoursArrive)-(minutesDepart+60*hoursDepart))
Длинные строки в коде следует разбивать на более короткие.
В данном случае следует поставить перенос строки после знака `=`

2016-09-27 09:56 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int =((number/100)+((number/10-(number/100*10))*10)+((number-(number/10*10))*100))
Аналогично

2016-09-27 09:56 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +        if ((number / 1000) +(number / 100 % 10) == (number % 100 / 10 + number % 10)) return true
Код следует корректно форматировать посредством отступов. Обе ветки `if` должны быть выровнены по одному отступу.

2016-09-27 09:56 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +        if ((number / 1000) +(number / 100 % 10) == (number % 100 / 10 + number % 10)) return true
Что, по-вашему, делает операция `+` в выражении `+(number / 100 % 10)`?
Если вы не знаете, зачем нужна та или иная операция, не используйте её.

2016-09-27 09:56 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = (3600*hours+60*minutes+seconds)
Следует придерживаться единого стиля форматирования кода во всём своём коде. Если вы ставите пробелы до и после знаков, то нужно делать это **везде**. Если вы этого не делаете, не делайте этого **нигде**.

2016-09-28 20:47 UTC, belyaev-mikhail commented
recheck all

2016-09-28 20:50 UTC, belyaev-mikhail commented
recheck all

2016-09-29 17:12 UTC, belyaev-mikhail commented
У вас бесконечный цикл в функции `revert()`. Причём он возникает при любом запуске этой функции, вне зависимости от контекста и параметров.
Это говорит о том, что вы даже не  пытались её перед коммитом запускать.
Не надо так.

2016-09-29 18:31 UTC, belyaev-mikhail requested changes

2016-09-29 18:31 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +fun digitNumber(n: Int): () -> Unit = {
Что это такое?

2016-10-26 13:49 UTC, belyaev-mikhail commented
recheck all

2016-11-25 21:58 UTC, mglukhikh commented
recheck all

2016-11-30 15:06 UTC, belyaev-mikhail commented
recheck all

2017-07-26 18:24 UTC, closed without merging