Lesson2. task1,2
Kotlin-Polytech/KotlinAsFirst2016 pull request #117
Opened 2016-09-27 21:06 UTC by KamikoFuroraru

done

2016-09-27 22:46 UTC, gagarski requested changes

2016-09-27 22:46 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int) : Double { return ((vershoks * 4.445 + arshins * 16* 4.445 + sagenes * 48* 4.445) / 100) }
- [Здесь и далее] Функции, состоящие только из оператора `return` в Котлине принято записывать в виде однострочных функций (через `=` как `seconds`, реализованная вами выше). 
 - [Здесь и далее] Длинные строки принято переносить на новую строку (вертикальная линия в IDEA на 120 символов вам на это намекает). В текущем виде это лучше сделать так:
```kotlin
fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int) : Double { 
    return ((vershoks * 4.445 + arshins * 16* 4.445 + sagenes * 48* 4.445) / 100) 
}
```
В однострочном (см. предыдущее замечание) - строку можно перенести после знака `=`

2016-09-27 22:46 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double {  return (( grad +(( min + sec / 60.0) /60.0)) * Math.PI /180)  }
См. `lengthInMeters`

2016-09-27 22:46 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double { return sqrt(sqr(x2 - x1) + sqr(y2 - y1)) }
См. `lengthInMeters`

2016-09-27 22:46 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun thirdDigit(number: Int): Int { return (number/100)%10}
См. `lengthInMeters`

2016-09-27 22:46 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int { return ((hoursArrive * 60 + minutesArrive) - (hoursDepart * 60 + minutesDepart)) }
См. `lengthInMeters`

2016-09-27 22:46 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double { return ((initial+initial*0.01*percent) + (initial+initial*0.01*percent)*0.01*percent) + ((initial+initial*0.01*percent) + (initial+initia
Постарайтесь упростить выражение с помощью арифметических преобразований и/или создания вспомогательных переменных.

2016-09-27 22:46 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if ((age / 10) % 10 == 1)
Это условие можно внести внутрь `when`

2016-09-27 22:46 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        (a + b <= c) || (a + c <= b) || (b + c <= a) -> -1
После того, как вы выяснили, существует ли треугольник, нужны ли проверки, в которых фигурируют длины сторон, а не их квадраты? (`(c >= a) && (c >= b)` и т. п.)

2016-09-27 22:46 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    return if ((x1 != x2) && (y1 != y2)
Здесь то же, что и в  `isNumberHappy`, но с поправкой на то, что `x` нужно инвертировать.

2016-09-27 22:46 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if ((f+th)==(t+number%10)) return true
- Вы используете довольно многословный способ вычисления булевского значения.
Постарайтесь озознать (в уме или на бумаге), что 
```kotlin
if (x) true else false
```
эквивалентно
```kotlin
x
```

2016-09-27 22:46 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    return if (d <= (r2 - r1)) true
См. `isNumberHappy`

2016-09-27 22:46 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    return if((a*b<=s*r)||(b*c<=s*r)||(a*c<=s*r)) true
См. `isNumberHappy`

2016-10-03 12:51 UTC, KamikoFuroraru commented
Проверьте пожалуйста мои исправления

2016-10-03 13:57 UTC, gagarski approved these changes

2016-10-03 13:58 UTC, closed without merging