Lesson 1, 2
Kotlin-Polytech/KotlinAsFirst2016 pull request #118
Opened 2016-09-28 09:22 UTC by makosenkov

2016-09-28 10:17 UTC, gagarski requested changes

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if ((age in 5..20) || (age in 105..120)) return "$age лет"
В этой функции несколько веток, из которых в зависимости от входных данных выполняется только одна.
Лучше записать это в виде

``` kotlin
if (...) ...
else if (...) ...
else if (...) ...
else ...
```

или (лучше) в виде конструкции `when`

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    return t1 + t2 + (hw - t1 * v1 - t2 * v2) / v3
Последний `return` можно внести в `when` в виде ветки `else`

``` kotlin
when {
    // ...
   else -> // ...
}
```

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX != rookX1) && (kingX != rookX2) && (kingY != rookY1) && (kingY != rookY2)) return 0
`if - else if - else` или `when` (см. `ageDescription`).

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX) || (kingY == rookY)) && (Math.abs(kingY - bishopY) != Math.abs(kingX - bishopX))) return 1
`if - else if - else` или `when` (см. `ageDescription`).

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if ((cos1 < 0) || (cos2 < 0) || (cos3 < 0)) return 2
`if - else if - else` или `when` (см. `ageDescription`).

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    when{
- Последний `return` можно внести в `when` как ветку `else`
 - Также это эквивалентно просто `return x1==x2 || y1==y2 || (Math.abs(x2-x1)==Math.abs(y2-y1))`
 - После этого это записывается в виде функции с `=`

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    when{
См. `queenThreatens`

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    return -1
- Можно внести последний `return` в  `when`
 - После этого можно записать как
```kotlin
fun segmentLength(a: Int, b: Int, c: Int, d: Int): Int  = when {
    c <= b && c >= a && d >= b -> b - c
    // ...
}
```

2016-09-28 10:17 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if (s>=a && (r>=b || r>=c)) return true
- Если найти две минимальные стороны кирпича, то условие упростится
 - См. комментарии про `if - else if - else` и `when`

2016-09-28 10:18 UTC, gagarski commented
recheck all

2016-10-06 11:30 UTC, gagarski requested changes

2016-10-06 11:30 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    return -1
- Можно внести последний `return` в  `when` (в качестве ветки `else`)

2016-10-06 11:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean {
Можно решить данную задачу с учётом того, что вы сделали ранее.

2016-10-06 11:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (a % b > 0) {
Поиск НОД лучше вынести в отдельную функцию.

2016-10-06 11:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    return n * m / b
Лучше сначала поделить на `b`, а потом умножить на `m`. Так вы избежите целочисленного переполнения в некоторых случаях, в которых его быть не должно (например, НОК(1000000, 1000000))

2016-10-06 11:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (revert(n) == n) return true
- Вы используете довольно многословный способ вычисления булевского значения.
Постарайтесь озознать (в уме или на бумаге), что 
```kotlin
if (x) true else false
```
эквивалентно
```kotlin
x
```

2016-10-26 10:05 UTC, gagarski requested changes
Исправьте пожалуйста имеющиеся  ошибки и замечания прежде чем приступать к следующим задачам.

2016-10-26 10:05 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var result = x
Протестируйте ваши реализации синуса и косинуса на больших числах (`10 * PI,`20 \* PI`,`100 \* PI`). Правильный ли результат она вовзращает? Исправьте проблему, используя свойства синуса и косинуса.

2016-10-26 10:05 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Нет необходимости рассматривать пустой список как особый случай. В случае пустого списка ваш цикл `for` просто не будет выполняться.

2016-10-26 10:05 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if ((a.isEmpty()) && (b.isEmpty())) return 0.0
Нет необходимости рассматривать пустой список как особый случай. В случае пустого списка ваш цикл `for` просто не будет выполняться.

2016-10-26 10:05 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Нет необходимости рассматривать пустой список как особый случай. В случае пустого списка ваш цикл `for` просто не будет выполняться.

2016-10-26 10:05 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    while (number > 1) {
- Эту задачу можно решить не проверяя число на простоту
- Вы каждую итерацию внешнего цикла ищете делитель начиная с 2. Этого делать не нужно (можно перебирать, начиная с текущего делителя)
- Используйте оператор `&&` вместо `and`. Во-первых, при его использовании правый аргумент не вычисляется без необходимости, во вторых его приоритет ниже, чем у `==` и можно уменьшить число скобок.

2016-10-26 10:05 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in 0..resList.size - 1) {
`result.reverse()`

2016-10-26 10:05 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        if (number[i].toInt() > 9) result.add((alphabet[number[i].toInt() - 10]).toString())
Вы преобразовываете каждый элемент списка в строку, а затем обратно в целое число. Избавьтесь от этого.

2016-10-26 10:05 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        result += digits[i] * Math.pow(base.toDouble(), (digits.size - i-1).toDouble()).toInt()
Переход к числам с плавающей точкой в целочисленных задачах может привести к ошибкам округления, которых можно избежать в целых числах. Реализуйте `pow` для целых чисел или используйте ваш цикл для вычисления текущего значения множителя.

2016-12-07 09:18 UTC, mglukhikh commented
recheck all

2016-12-19 22:24 UTC, mglukhikh commented
recheck all

2016-12-20 18:21 UTC, gagarski commented
Для получения оценки "хорошо" решите ещё хотя бы одну сложную задачу и напишите завтра успешно тест.

2016-12-20 18:23 UTC, gagarski requested changes

2016-12-20 18:23 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    if (newAngle == Math.PI) newAngle = 0.0
Сравнение `Double` на точное равенство

2016-12-20 18:23 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    var num = 0
Эта переменная явно должна быть булевской

2016-12-20 18:24 UTC, gagarski commented
Для получения оценки "хорошо" решите/исправьте ещё хотя бы одну сложную задачу и напишите завтра успешно тест.

2016-12-21 09:16 UTC, gagarski commented
recheck all

2017-02-18 18:18 UTC, closed without merging