Lesson2-3
Kotlin-Polytech/KotlinAsFirst2016 pull request #121
Opened 2016-09-28 10:31 UTC by Janget

2016-09-28 10:32 UTC, Janget commented
recheck all

2016-09-28 12:10 UTC, maximpetrov commented
recheck all

2016-09-29 10:27 UTC, ice-phoenix requested changes

2016-09-29 10:27 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial*(100+percent)*0.01*(100+percent)*0.01*(100+percent)*0.01
Повторно используемые выражения лучше вынести в отдельные переменные

2016-09-29 10:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (age%100 in 5..20) return "$age лет"
Данное выражение лучше оформить как `when`

2016-09-29 10:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val hS = (t1 * v1 + t2 * v2 + t3 * v3) / 2
Повторно используемые выражения лучше вынести в отдельные переменные

2016-09-29 10:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val cos1 = (a*a + b*b - c*c)/(2*a*b)
Можно считать только косинус угла, противолежащего максимальной стороне треугольника

2016-09-29 10:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (c<=a && d>=b) return b-a
Данное выражение лучше оформить как `when`

2016-09-29 10:27 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (number%10+(number/10)%10 == (number/100)%10+(number/1000)%10) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-29 10:27 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (x1==x2 || y1==y2 || Math.abs(x1-x2)==Math.abs(y1-y2)) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-29 10:27 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)) <= (r2-r1))) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-30 15:09 UTC, ice-phoenix commented
Для того, чтобы мы проверили ваши решения, сперва вы должны исправить замечания к предыдущим PR

2016-10-25 09:32 UTC, ice-phoenix commented
recheck all

2016-10-25 09:35 UTC, ice-phoenix requested changes

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = ((grad * 3600 + min * 60 + sec) * 1.0) / (180.0 / PI) / 3600.0
Зачем умножать на 1.0?

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = (hoursArrive * 60 + minutesArrive) - (hoursDepart * 60 + minutesDepart)
Длинные строчки принято разбивать на несколько более коротких, в данном случае, например, после знака `=` в объявлении функции

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var cos = 0.0
Можно так
```
val cos = when {
    a -> cosA
    b -> cosB
    else -> cosC
}
```

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean = (number % 10 + (number / 10) % 10 == (number / 100) % 10 + (number / 1000) % 10)
Длинная строка

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return when {
Все это можно записать намного проще, если вспомнить, как объединяются переменные типа `Boolean`

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var N = n
Переменные в Котлине принято называть `camelCase`

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (n * m) / b
Подсчет GCD следует вынести в отдельную функцию

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Нет ли более точной границы для максимального возможного делителя числа, чем `n`?

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in n - 1 downTo 1) {
Нет ли более точной границы для искомого делителя числа, чем `n - 1`?

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (a % i == 0 && b % i == 0) return false
Подумайте, что общего есть у кода данной функции и функции `lcm`. Можно ли написать функцию `isCoPrime` короче?

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i >= m && i * i <= n) return true
Можно ли уточнить границы для возможных значений `i`, учитывая условия задачи?

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        b = -b * x * x / (c * (c - 1))
Как считается значение `n!`?

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    N = n
Нет ли уже готовой функции, которая может посчитать количество цифр в числе?

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        r = r + N % 10 * (Math.pow(10.0, i - 1.toDouble()).toInt())
Напишите функцию `pow(Int, Int): Int`, работающую в целых числах

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (r == N) return true
Не повторяет ли код данной функции код функции `revert` практически полностью?

2016-10-25 09:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var prevLenght = 0
`prevLength`

2016-10-27 21:09 UTC, Janget commented
Необходимо сначала полностью исправить предыдущие уроки, или уже можно выложить 4-5?
Спасибо.

2016-10-28 10:40 UTC, ice-phoenix requested changes

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var cos = 0.0
Ок, сформулирую это замечание как "лучше сделать так"

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (c <= a && d >= b) -> return b - a
`return` внутри веток `when` можно убрать

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        = ((Math.sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1)) <= (r2 - r1)))
Лишние скобки вокруг законченных выражений

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return bP
Проще сперва найти две минимальные стороны кирпича и потом все решать относительно них

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    fun GCD(a: Int, b: Int): Int {
* Эту функцию лучше вытащить на верхний уровень, потому что она может вам пригодиться в нескольких других функциях дальше
* `gcd`

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = lcm(m, n) == m * n
Если бы у вас была функция `gcd`, эту задачу можно было бы решить еще проще

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i >= m && i * i <= n) return true
Подумайте, нельзя ли сократить границы перебора точнее, чем это делаете вы (подсказка: можно), или реализовать функцию вообще без цикла (подсказка: да)?

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = x
Попробуйте подумать, нельзя ли ограничить рассматриваемые значения `x`, используя тригонометрические свойства синуса?

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        b = -b * x * x / (c * (c - 1))
Неплохой трюк :+1:

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = 1.0
См. замечания к `sin`

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    initial = n
Нет ли у вас уже реализованной функции, которая может посчитать значение `count`?

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        reverse = reverse + initial % 10 * (Math.pow(10.0, i - 1.toDouble()).toInt())
> Реализуйте функцию `pow(Int, Int)`, работающую в целых числах

Раз вы ее уже реализовали, почему вы ей здесь не воспользовались?

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = 0
Почему эти переменные объявлены здесь, а не в цикле?

2016-10-28 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (prevLength - +line.length < n) {
Тесты говорят, что где-то здесь ошибка

2016-11-22 15:57 UTC, ice-phoenix commented
recheck all

2016-11-22 15:58 UTC, ice-phoenix commented
recheck all

2016-11-22 16:08 UTC, ice-phoenix requested changes

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +//Выполнялось умножение на 1.0 из-за ошибки с типом переменных.
Для беседы с преподавателем лучше использовать комментарии к PR

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        a > b && a > c -> (c * c + b * b - a * a) / (2 * c * b)
Лучше сперва найти максимальную сторону, а потом все считать относительно нее

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`when { ... -> return ... }` ==> `return when { ... }`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`return when (cos) { ... }`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        min2 = Math.min(min2, c)
Форматирование кода

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (Math.min(min1, min2) <= Math.min(r, s) && Math.max(min1, min2) <= Math.max(r, s)) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun gCD(a: Int, b: Int): Int {
`gcd`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = 1
Почему эта переменная объявлена здесь?

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = Math.max(m, n)
Почему `var`?

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqrtK = Math.sqrt(n.toDouble()).toInt()
Для округления следует использовать специальные функции `floor / ceil / round`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (m <= sqrtK * sqrtK && sqrtK * sqrtK <= n)
Зачем проверять второе условие?

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = x
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (Math.abs(Math.sin(a)) > 1) break   // Не знаю, как можно ограничить еще.
Это не то, что имелось в виду в комментарии выше

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = 1.0
Это все еще в силе

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun powInt(m: Int, n: Int): Int {
Данная функция должна называться `pow`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var N = n
`camelCase`

2016-11-22 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var a = 0
Почему вы разделили определения и объявления этих переменных?

2016-11-23 02:34 UTC, Janget commented on src/lesson3/task1/Loop.kt
> +        var a = 0
Но разве N (сейчас number) не нужно объявлять до цикла?

2016-11-23 02:37 UTC, Janget commented on src/lesson3/task1/Loop.kt
> +        if (Math.abs(Math.sin(a)) > 1) break   // Не знаю, как можно ограничить еще.
Не понимаю, о каком именно тригонометрическом свойстве идет речь. Разве значения x можно как-то ограничить, если область определения sin(x) это множество R?

2016-11-23 04:29 UTC, Janget commented on src/lesson3/task1/Loop.kt
> +        var a = 0
Будет исправлено, извиняюсь за невнимательность.

2016-11-23 10:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (Math.abs(Math.sin(a)) > 1) break   // Не знаю, как можно ограничить еще.
Можно, если вспомнить о том, что у `sin` область значений весьма интересным образом зависит от интервалов области определения

2016-11-23 10:58 UTC, ice-phoenix requested changes

2016-11-23 10:58 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
`return when (cos) { ... }`

2016-11-23 10:58 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    } else min2 = c // нахождение 2 меньших сторон
Форматирование кода

2016-11-23 10:58 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +import lesson4.task1.abs
Зачем?

2016-11-23 10:58 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        k = max
Зачем сперва делать `k = 1`,  а потом сразу `k = max`?

2016-11-23 10:58 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var set = x
Нельзя ли как-то ограничить диапазон рассматриваемых значений `x`?

2016-11-23 10:58 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        mod2 = number % 10
Почему вы разделили определения и объявления переменных?

2016-11-25 21:22 UTC, Janget commented on src/lesson3/task1/Loop.kt
> +    var set = x
Я буду продолжать думать над этим.

2016-11-27 12:52 UTC, ice-phoenix requested changes

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (hS <= (s1 + s2)) -> t1 + (hS - s1) / v2
Лишние скобки вокруг законченных выражений + в подобных случаях обычно выражения сравнивают в одном и том же порядке

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var set = x
Подумайте над тем, нет ли какого-либо числа `W` такого, что `sin(x) == sin(x + W)` для любого `x`?

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var mod1 = number % 10
Почему `var`, а не `val`???

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        0.0 -> 0.0
Вообще-то, тут следует проверять то, что список не пустой

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var sum = list[0]
Если убрать проверку выше и инициализировать сумму нулем, что изменится?

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val symbols = listOf<Char>('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
Вместо этого списка можно было просто завести такую же строку

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = String()
Либо список строк, либо `StringBuilder`

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var countExp = 0
Зачем вам эта переменная?

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val symbols = listOf<Char>('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g',
Строка

2016-11-27 12:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return result
Почему бы здесь не воспользоваться уже написанной выше функцией `decimal`?

2016-11-28 02:12 UTC, Janget commented on src/lesson3/task1/Loop.kt
> +    var set = x
W =  2*PI, но я не понимаю, как это можно применить здесь.

2016-12-04 19:41 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var set = x
Попробуйте подумать про это соотношение и операцию взятия остатка от деления.

2016-12-04 19:58 UTC, ice-phoenix requested changes

2016-12-04 19:58 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val sum = list[i - 1]
Тут можно обойтись без введения этой дополнительной переменной

2016-12-04 19:58 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += symbols.indexOf(str[i], 0).toInt()
А зачем вы, боюсь спросить, добавили вызов `toInt()`???

2016-12-07 09:29 UTC, mglukhikh commented
recheck all

2016-12-18 22:18 UTC, ice-phoenix commented
recheck all

2016-12-18 22:20 UTC, ice-phoenix commented
В настоящее время у вас нет даже зачета.

2016-12-19 09:17 UTC, ice-phoenix commented
Сразу --- 7 урок учитываться не будет, так как он был закоммичен после дедлайна.

2016-12-19 09:17 UTC, ice-phoenix commented
recheck all

2016-12-19 09:21 UTC, ice-phoenix commented
recheck all

2016-12-19 09:39 UTC, ice-phoenix requested changes

2016-12-19 09:39 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val months = listOf<String>("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября",
Так как этот список используется в двух функциях, его лучше бы вынести на верхний уровень

2016-12-19 09:39 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (phone.matches(Regex("""(\+\d+\s)?(\(\d+\))?[0-9- ]+""")) == true) {
`Boolean == true`???

2016-12-19 09:39 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +      }
Совсем неправильно так организовывать процесс вычисления в этой функции

2016-12-19 09:39 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return string.indexOf("#")
Нет.

2016-12-19 09:39 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        val x = (c1 * b2 - c2 * b1) / denominator
Если знаменатель ноль, что делаем?

2016-12-19 09:39 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val string2 = "12345678"
Ужасные имена переменных

2016-12-19 09:39 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        if (string2[i] == notation[1]) row = i + 1
Эти два цикла можно заменить на простой вызов простой функции

2016-12-19 09:39 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    }
Это все можно сделать проще

2016-12-19 09:40 UTC, ice-phoenix commented
При условии исправления всех замечаний и успешного прохождения тестирования у вас, возможно, получится получить "Удовлетворительно".

2016-12-19 18:00 UTC, Janget commented on src/lesson5/task1/Parse.kt
> +      }
Как будет правильнее?

2017-07-26 18:23 UTC, closed without merging