lesson_2.1_&_2.2
Kotlin-Polytech/KotlinAsFirst2016 pull request #124
Opened 2016-09-28 20:09 UTC by Anastasiiachu

2016-09-28 20:23 UTC, belyaev-mikhail commented
recheck all

2016-09-28 20:24 UTC, belyaev-mikhail commented
recheck all

2016-09-28 20:26 UTC, belyaev-mikhail commented
recheck all

2016-09-29 09:40 UTC, belyaev-mikhail requested changes

2016-09-29 09:40 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +
Длинные цепочки `if`-`else if`-`else if` лучше заменять на конструкцию `when`

2016-09-29 09:40 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +
См. комментарий про `when`

2016-09-29 09:40 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +
См. комментарий про `when`

2016-09-29 09:40 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else return b - a
См. комментарий про `when`

2016-09-29 09:40 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +
Конструкция `if(x) return true else return false` не имеет никакого смысла, т.к. у вас и так есть значение логического типа. Т.е. это ничем не отличается от более короткого `return x`

2016-09-29 09:40 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +
Аналогично

2016-09-29 09:40 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +
Аналогично

2016-10-27 10:20 UTC, Anastasiiachu commented
lesson2/task1 замена конструкции if на when

2016-10-27 10:28 UTC, Anastasiiachu commented
lesson2/task2 исправлены недочеты

2016-10-28 11:20 UTC, belyaev-mikhail commented
recheck all

2016-11-10 12:39 UTC, belyaev-mikhail commented
Вы так и не исправили ошибку в уроке 3. Дальнейшие задания проверяться не будут.

2016-11-14 12:06 UTC, belyaev-mikhail requested changes

2016-11-14 12:06 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if (a + b == c + d) return true
Конструкция `if(X) return true else return false` лишена смысла, т.к. ничем не отличается от просто `return X`

2016-11-14 12:06 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        if (nod == 1) return true
Конструкция `if(X) return true else return false` лишена смысла, т.к. ничем не отличается от просто `return X`

2016-11-14 12:06 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    }
Эту функцию можно легко реализовать на основе функции `lcm`

2016-11-14 12:06 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    else return false
+1

2016-11-14 12:06 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        list[i] = element - mean
Форматирование

2016-11-14 12:06 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        polynomial += p[i] * Math.pow(x, i * 1.0)
Откуда вы взяли идиому `i * 1.0` вместо `i.toDouble()` ?

2016-11-14 12:06 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        number += digits.reversed()[i] * Math.pow(base * 1.0, i * 1.0)
Использовать `Math.pow()` для возведения в степень целых чисел некорректно.
Ваша функция может выдавать на некоторых числах некорректный результат из-за округления.

2016-11-14 12:06 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    return number.toInt()
Аналогично

2016-11-17 13:43 UTC, belyaev-mikhail requested changes

2016-11-17 13:43 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +}
Отступы

2016-11-17 13:43 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    // println("----------")
Отладочный код перед отправкой нужно удалять, а не комментировать.

2016-11-17 13:43 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            'a' -> list.add(10.0)
Вы точно уверены, что это нельзя было сделать без китайского кода с полным перебором вариантов?

2016-11-22 16:16 UTC, belyaev-mikhail commented
Ок

2016-11-22 16:16 UTC, closed without merging