первая часть второго урока
Kotlin-Polytech/KotlinAsFirst2016 pull request #128
Opened 2016-09-29 09:42 UTC by KiriII

2016-09-29 10:11 UTC, belyaev-mikhail commented
recheck all

2016-09-29 10:15 UTC, belyaev-mikhail commented
recheck all

2016-09-29 15:01 UTC, KiriII reviewed
first part

2016-09-29 15:02 UTC, KiriII commented
first part second lesson

2016-09-29 15:03 UTC, belyaev-mikhail commented
recheck all

2016-09-29 15:05 UTC, KiriII reviewed
передалал второй урок

2016-09-29 17:16 UTC, belyaev-mikhail commented
recheck all

2016-09-29 17:17 UTC, belyaev-mikhail commented
recheck all

2016-09-29 18:07 UTC, belyaev-mikhail requested changes

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = ((sagenes * 3 + arshins) * 16 + vershoks) * 0.04445
Длинные строки в коде следует разбивать на несколько строк. В случае однострочных функций лучше всего ставить перенос после знака `=`.

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (((grad * 60 + min) * 60 + sec) * Math.PI) / 648000
Аналогично

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = Math.sqrt(sqr(x1-x2) + sqr(y1-y2))
Аналогично

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = (hoursArrive * 60) + minutesArrive - (hoursDepart * 60) - minutesDepart
Аналогично

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = Math.pow(1.0 + percent / 100.0, 3.0) * initial
Аналогично

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = (number % 10) * 100 + ((number % 100) / 10) * 10 + number / 100
Аналогично

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    return if ((age in (5..20)) || (age in (105..120)) || (age % 10 > 4) || (age % 10 == 0)) "$age лет"
Зачем делать `return` внутри условного оператора, перед которым и так стоит `return`?
Вообще, всю эту конструкцию лучше заменить одной конструкцией `when`.

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +        else attack = 0
`if` и `else`, как правило, выравниваются по одному отступу

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else attack = attack
Что значит `attack = attack`? Зачем вы присваиваете переменную саму себе?
Попытки обмануть компилятор в учебных программах делать не стоит, лучше просто инициализировать переменную в месте объявления, что значительно проще и правильнее.

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if (((maxComa == a) && (maxComa == b)) && ((maxComa == c) && (maxComa == d))) return 0
Если вы видите в коде длинную цепочку `if`-`else if`-`else if`, её однозначно следует немедленно заменить на `when`.
Но даже если этого не делать, как правило, в такой конструкции все `else` выравнивают по одному отступу, потому что так программа легче читается.

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +}
Конструкция вида `if(x) return true else return false` лишена смысла, т.к. ничем не отличается от просто `return x`.

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +}
Конструкция вида `if(x) return true else return false` лишена смысла, т.к. ничем не отличается от просто `return x`.

2016-09-29 18:07 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +}
Конструкция вида `if(x) return true else return false` лишена смысла, т.к. ничем не отличается от просто `return x`.

2016-11-07 11:56 UTC, belyaev-mikhail commented
Вы отправляете новые задания, не исправляя замечания к старым. Довожу до вашего сведения, что проверяться и засчитываться они до исправлений не будут.

2016-11-25 20:21 UTC, belyaev-mikhail commented
recheck all

2016-12-05 15:55 UTC, belyaev-mikhail commented
recheck all

2016-12-05 16:19 UTC, KiriII commented
org.opentest4j.AssertionFailedError : You should mutate an input list, not create a copy. Я не понимаю, что я должен изменить в программе. Я считаю, что изменял исходную строку

2016-12-07 21:17 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (list.size == 0) return mutableListOf()
В этом месте вы создаёте копию исходного списка, чего здесь вы делать не должны. То же в accumulate

2016-12-12 20:25 UTC, KiriII commented
Что мне ещё сделать, чтобы стали проверять мои новые работы и засчитывать их?

2016-12-12 20:30 UTC, belyaev-mikhail commented
recheck all

2016-12-12 20:32 UTC, belyaev-mikhail commented
Начать чинить сломанные задания до того, как пытаться сдавать следующие?
У вас в первом уроке баг несколько месяцев неисправленным висел, а вы тут претензии предъявляете.

2016-12-12 20:36 UTC, belyaev-mikhail commented
И, как всем видно, продолжает висеть.

2016-12-12 20:59 UTC, KiriII commented
А если я не могу исправить ошибку, то вместо задачи отправить "=TODO" ?

2016-12-12 21:03 UTC, belyaev-mikhail commented
В принципе, можно и так.

2016-12-12 21:03 UTC, KiriII commented
Спасибо!

2016-12-17 21:49 UTC, belyaev-mikhail commented
recheck all

2016-12-17 22:11 UTC, belyaev-mikhail requested changes

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    val halfWay: Double= (t1 * v1 + t2 * v2 + t3 * v3) / 2.0
Пробелы

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX-bishopX) * (kingX-bishopX) == (kingY-bishopY) * (kingY-bishopY)) {
Пробелы

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if ((((sqr(b) + sqr(c) - sqr(a))/(2*b*c)) > 0) && (((sqr(a) + sqr(c) - sqr(b))/(2*a*c)) > 0) && (((sqr(b) + sqr(a) - sqr(c))/(2*b*a)) > 0)) return 0
Пробелы

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +if (n <=2) 1
Форматирование

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    var Arnold : Int = 0
Названия переменных должны соответствовать их значениям. Называть переменные случайными словами &mdash; очень плохая практика.

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    if (Arnold == 0) return true
Конструкция `if (X) return true else return false` не имеет смысла, т.к. ничем не отличается от просто `return X`

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    for (sqrPants in 1..m) {
См. комментарий про имена переменных.

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    val copy: Int = n
Зачем нужна эта переменная? Она ничего не делает, её существование ничем не обусловлено.

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        if (revert(copy / ten(lenght / 2)) != copy % ten(lenght/ 2)) return false
См. комментарий про `if`

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        if (revert(copy / ten((lenght + 1) / 2)) != copy % ten((lenght - 1) / 2)) return false
Аналогично

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    else return true
См. все предыдущие комментарии

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +           if ((part[i] != iNeedIt[11]) && (part[i] != iNeedIt[12]) && (part[i] != iNeedIt[13]) && (part[i] != iNeedIt[14])) strAnsw += part[i]
Длинные строки следует разбивать на короткие.

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +           if ((part[i] != iNeedIt[11]) && (part[i] != iNeedIt[12]) && (part[i] != iNeedIt[13]) && (part[i] != iNeedIt[14])) strAnsw += part[i]
Магических констант типа 11, 12 в коде следует избегать. Тем более что в данном случае они совершенно не нужны.

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +            if (part[i] == iNeedIt[10]) mbAnsw += element + " "
Аналогично

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +                if ((i > 9) && ((part[0] == iNeedIt[10]) || (part[0] == iNeedIt[11]))) throw IllegalArgumentException()
Форматирование

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +        if (parts[i].capitalize() == parts[i+1].capitalize()) {
Зачем вы делаете здесь `capitalize()`?

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..roman.length - 1){
Ужасный спагетти-код с адской вложенностью и гигантским количеством магических констант.
По-хорошему, его следует весь переписать.

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        if (center.distance(other.center) > radius + other.radius) return center.distance(other.center) - (radius + other.radius)
Форматирование

2016-12-17 22:11 UTC, belyaev-mikhail commented on src/lesson6/task2/Chess.kt
> +        val ABC = "abcdefgh"
Именование переменных должно быть системным. Не следует использовать капс только для одной переменной в программе.

2016-12-20 11:11 UTC, mglukhikh commented
recheck all

2016-12-20 11:14 UTC, mglukhikh commented
recheck all

2016-12-20 18:28 UTC, belyaev-mikhail commented
recheck all

2016-12-20 18:34 UTC, belyaev-mikhail commented
recheck all

2017-07-26 18:23 UTC, closed without merging