Решил 2 урок
Kotlin-Polytech/KotlinAsFirst2016 pull request #130
Opened 2016-09-29 10:18 UTC by mizunotlt

решил 2 урок

2016-09-29 11:03 UTC, belyaev-mikhail commented
recheck all

2016-09-29 12:41 UTC, belyaev-mikhail commented
recheck all

2016-09-29 17:13 UTC, belyaev-mikhail commented
recheck all

2016-09-29 17:16 UTC, belyaev-mikhail commented
recheck all

2016-09-29 17:18 UTC, mizunotlt commented
отправил https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/130/commits/df62e82e4082f1e704e165333b0710a52c594b9e

2016-10-01 23:26 UTC, belyaev-mikhail commented
recheck all

2016-10-01 23:43 UTC, belyaev-mikhail requested changes

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = (sagenes*48.0*4.445 + arshins*16.0*4.445 + vershoks*4.445)/100.0
Длинные строки следует разбивать на более короткие. Для однострочных функций лучше всего ставить перенос после знака `=`.

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = hoursArrive*60+minutesArrive - (hoursDepart*60+minutesDepart)
Стиль оформления должен быть консистентным. Если вы ставите пробелы до и после операторов, их следует ставить **везде**, если не ставите &mdash; их не следует ставить **нигде**.

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return amountHundreds*100 + amountDec*10 + amountUnits
См. комментарий про пробелы

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if (abs((kingX - bishopX).toDouble()) == abs((kingY - bishopY).toDouble()) )
Зачем вы делаете здесь `toDouble()`?
Это не только бессмысленно, но и потенциально некорректно, потому что значения типа `Double` в общем случае **нельзя** сравнивать с помощью операции `==`.

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +        if ((x1 == x2) || (y1 == y2) || (abs((x1 - x2).toDouble()) == abs((y1 - y2).toDouble()))) true
См. комментарий про `toDouble()`

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        if ((sqr(i.toDouble()).toInt()<= n)&&((sqr(i.toDouble()).toInt() >= m)))
Неужели написать некорректное `sqr(i.toDouble()).toInt()` вам кажется более простым, чем корректное `i * i`?

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +fun countNumber (x: Int): Int = if (x < 10) 1 else countNumber (x % 10) +  countNumber (x / 10)
Какой смысл в вызове `countNumber(x % 10)`, который *всегда* возвращает `1`?

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    return result.toInt()
Производить чисто целочисленные вычисления в вещественных числах, а потом переводить результат обратно в целое число &mdash; не только бессмысленно, но также медленно и потенциально некорректно.
Любая операция с плавающей точкой может вернуть число вида `159.9999999998`, которое, вопреки вашим ожиданиям, после вызова `toInt()` будет равно не `160`, а `159`.

2016-10-01 23:43 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +            logic = true
Неконсистентные отступы

2016-10-27 12:41 UTC, belyaev-mikhail commented
recheck all

2016-10-27 21:00 UTC, belyaev-mikhail requested changes

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +        if ( (sqrt(sqr(x1-x2) + sqr(y1 - y2)) + r1 ) <= r2) true
Конструкция `if(X) true else false` лишена всякого смысла, т.к. ничем не отличается от просто `X`

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int = if (n < 3) 1 else fib(n-1) + fib (n-2)
Это крайне неэффективный способ подсчёта числа Фибоначчи.
Его следует заменить на более быстрый.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +fun NOD(m: Int, n: Int): Int{
Функции следует называть с маленькой буквы.
Кроме того, наибольший общий делитель на английском сокращается как `gcd`, а не `nod`.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        for (i in 3 .. n step 2 )
Обязательно ли перебирать все числа до `n`? Как минимум, половина из них точно не является делителем `n`.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    for (i in 1 .. n step 1)
Аналогично

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean {
Эту функцию можно реализовать гораздо проще и, одновременно, значительно эффективнее с использованием вышенаписанных функций для НОК или НОД.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    val right = sqrt(n.toDouble()).toInt()
Это некорректный способ выделения ближайшего снизу квадрата. Если `n` само является квадратом, оно может выдать меньшее число в результате ошибок округления для `Double`.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +            break
Какой смысл использовать `break`, если можно вместо него просто использовать `return`?

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +            result = false
Зачем заново присваивать значение переменной, которая ни в какой ситуации не может иметь другого значения на этот момент?

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    var logic = false
Вы знаете, что переменные можно объявлять не только как `var`?
Вы знаете, что переменные можно объявлять не только в начале функции? 
Это Kotlin, а не С и не бейсик.

Переменные следует объявлять ближе к месту использования, особенно, если вы их называете подобными ни о чем не говорящими именами.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty() == true){
`if(X == true)` ничем не отличается от просто `if(X)`

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            while ((digit % primeNumber) == 0)
Ваш стиль кодирования должен быть консистентным. Вы либо ставите открывающую скобку после циклов на той же строке, либо на следующей, но не &laquo;так или так в зависимости от настроения&raquo;.
Ваш код предназначен в первую очередь для того, чтобы его читали другие люди, проявите к ним уважение.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        for (i in 0..value.size - 1 step 1)
Зачем здесь отступ до конца функции?

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    val litter = listOf('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',
Слово letter пишется не так.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    var result = ""
Если уж вы генерируете строку таким странным образом, то не стоит складывать результаты в `String`, это работает **крайне** неэффективно.
Либо почитайте про `StringBuilder`, либо используйте просто список символов.

2016-10-27 21:00 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +        try {
Зачем тут отступ до конца функции?

2016-10-27 22:43 UTC, mizunotlt commented on src/lesson4/task1/List.kt
> +    var result = ""
то есть вместо строки создать список куда заносить тоже самое ?

2016-10-27 22:54 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    var result = ""
Да, и в конце слепить его в строку.
Просто список предназначен для добавления в него элементов, а строка &mdash; нет.

2016-11-07 11:50 UTC, belyaev-mikhail commented
Вы отправляете новые задания, не исправляя замечания к старым. Довожу до вашего сведения, что до исправления ничего проверяться (и засчитываться) не будет.

2016-11-23 11:21 UTC, mglukhikh commented
recheck all

2016-11-23 22:10 UTC, belyaev-mikhail commented
recheck all

2016-11-25 12:45 UTC, belyaev-mikhail requested changes

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +fun lineByPoints(a: Point, b: Point): Line = Line(Point(a.x, a.y),atan( (b.y - a.y) / (b.x - a.x)))
А что будет, если сегмент параллелен оси Y?

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +fun lineByPoints(a: Point, b: Point): Line = Line(Point(a.x, a.y),atan( (b.y - a.y) / (b.x - a.x)))
Причем в точно такой же задаче `lineBySegment` вы это учли.

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +fun lineByPoints(a: Point, b: Point): Line = Line(Point(a.x, a.y),atan( (b.y - a.y) / (b.x - a.x)))
Пробелы

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        return Line (Point((b.x + a.x) / 2 , (b.y + a.y) / 2), atan( (- 1) * 1 /((b.y - a.y)/(b.x - a.x))))
Пробелы

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        throw IllegalArgumentException()
Отступы

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +            when (commands[indexCommands - 1]){
Что это за ерунда? Зачем вы в каждом кейсе заново проверяете, что значение действительно такое, как указано в кейсе?

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +            if (parth[i].toDouble() < 0)
Вы множество раз вызываете `parth[i].toDouble()` притом, что операция разбора числа с плавающей точкой из строки &mdash; это, вообще говоря, очень дорогая операция.

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +            if ((parth[i].length == parth[j].length) && (parth[i] in parth[j])) {
Что за странная проверка на равенство? Почему нельзя просто написать `parth[i] == parth[j]`?

2016-11-25 12:45 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    var result = ""
Складывать результат в строку через `+=` &mdash; крайне неэффективно. Либо используйте список, либо `StringBuilder`.

2016-11-25 20:47 UTC, belyaev-mikhail commented
recheck all

2016-11-25 21:05 UTC, belyaev-mikhail commented
recheck all

2016-11-25 21:20 UTC, belyaev-mikhail commented
recheck all

2016-11-25 21:32 UTC, belyaev-mikhail commented
recheck all

2016-11-29 14:35 UTC, belyaev-mikhail commented
recheck all

2016-11-29 14:46 UTC, belyaev-mikhail commented
recheck assignment

2016-11-29 16:22 UTC, belyaev-mikhail commented
recheck assignment

2016-11-29 16:25 UTC, belyaev-mikhail commented
recheck assignment

2016-11-29 16:28 UTC, belyaev-mikhail commented
recheck assignment

2016-12-17 16:28 UTC, mizunotlt commented
Я запускаю у себя программу на тесте, которую выдал бот и она работает правильно, а бота не проходит

2016-12-17 20:44 UTC, mglukhikh commented
Окончательное мнение по поводу урока 8 вам выскажет Михаил Анатольевич, но в `countSubstrings` имеется довольно очевидный баг (именно поэтому результаты слегка расходятся с результатами бота). В `transliterate` подробно я не разбирался, но она в принципе написана не очень удачно, стоит подумать, как написать её лучше. Проблемы в тестах, скорее всего, возникают из-за лишних пробелов.

2016-12-17 22:44 UTC, belyaev-mikhail requested changes

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if( a <= r )
`if` внутри `if`? Зачем? Оператор `&&` вам незнаком?

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            result += letter[digit.indexOf(value[i])]
`digit.indexOf()` вместо того, чтобы просто прибавить к индексу 10.

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            result += digit[letter.indexOf(i)] * powInt(base, count)
Аналогично, только с буквами.

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            result += (i.toInt() - '0'.toInt()) * powInt(base, count)
`i.toInt() - '0'.toInt()` ничем не отличается от `i - '0'`.

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +            if ((i != "") && (i.toInt() > max))
Много раз делать `i.toInt()` для длинных чисел это неэффективно.

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +                   if (parth[i - 1].toInt() > max)
Аналогично

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +    val libraryNumber = listOf(1, 5, 10, 50, 100, 500, 1000)
Зачем этот список и последующие к нему обращения?
Это тот случай как раз, когда `libraryNumber[3]` гораздо менее очевидно, чем `50`.
В результате что ваш код делает и как &mdash; решительно непонятно.

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        val x =(point.x * tan(angle) - other.point.x * tan(other.angle) + other.point.y - point.y) / (tan(angle) -tan(other.angle))
А если прямая параллельная оси Y?

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        return Line (Point((b.x + a.x) / 2 , (b.y + a.y) / 2), atan( (- 1) * 1 / ((b.y - a.y) / (b.x - a.x))))
`-1 * 1`?

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson7/task1/Matrix.kt
> +        if ((other is MatrixImpl<*>) && (height == other.height) && (width == other.width))
`equals()` любой вменяемой реализации интерфейса должен работать для **любых** реализаций этого интерфейса, а не только для вашей. Ваша же реализация работает только для ваших же матриц.

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson7/task1/Matrix.kt
> +        var result = false
Зачем эта переменная? Вы её один раз присваиваете и возвращаете тоже 1 раз.

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson8/task1/Files.kt
> +        result.delete(0, result.length)
Зачем? Не проще создавать на каждой итерации новый билдер?

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson8/task1/Files.kt
> +        for (parth in parthLine) {
Зачем делить строку дальше на слова, если вы всё равно оперируете на уровне символов?

2016-12-17 22:44 UTC, belyaev-mikhail commented on src/lesson8/task1/Files.kt
> +                if (i.toUpperCase() in dictionary.keys)
А без трёх условий это никак не проверить?

2016-12-17 22:45 UTC, belyaev-mikhail commented
Вы решили отправить как можно больше неправильно работающих задач вместо того, чтобы исправлять уже имеющиеся? Это не самая лучшая стратегия в текущей ситуации.

2016-12-20 11:08 UTC, mglukhikh commented
recheck all

2016-12-20 11:09 UTC, mglukhikh commented
recheck all

2016-12-20 11:11 UTC, mglukhikh commented
recheck all

2016-12-20 11:13 UTC, mglukhikh commented
recheck all

2017-07-26 18:23 UTC, closed without merging