Src: Lesson1; Lesson2; Lesson3; Lesson4;  Test: Lesson2.task1
Kotlin-Polytech/KotlinAsFirst2016 pull request #131
Opened 2016-09-29 10:19 UTC by tyushin

2016-09-29 11:19 UTC, mglukhikh commented
recheck all

2016-09-29 14:09 UTC, mglukhikh commented
recheck all

2016-09-29 16:46 UTC, maximpetrov requested changes

2016-09-29 16:46 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +    val year1: Double =(initial+initial/100.0*percent)
Попробуйте упростить это до одного выражения с помощью математических преобразований

2016-09-29 16:46 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +        if (ageEnd == 1) return ("$age год")
Скобки вокруг возвращаемого значения не обязательны

2016-09-29 16:46 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +    val year1: Double =(initial+initial/100.0*percent)
Указывать тип переменной необязательно, если Вы её инициализируете: в этом случае компилятор сам может вывести тип переменной.

2016-09-29 16:46 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> + if (((kingX == rookX1) && (kingX == rookX2)) || ((kingY == rookY1) && (kingY == rookY2)) || ((kingX == rookX1) && (kingY == rookY2)) || ((kingX == rookX2) && (kingY == rookY1))) return (3)
Условия угрозы каждой из ладей королю лучше вынести в отдельные переменные.

2016-09-29 16:46 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if ((number1 + number2) == (number3 + number4)) return true
Выражение `if (x) return true else return false` эквивалентно `return x`.

2016-09-29 16:46 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if (((a <= r) && ((b <= s)||(c <= s))) || ((b <= r) && ((a <= s)||(c <= s))) || ((c <=r) && ((a <= s) || (b <=s)))) return true
Если предварительно вычислить наименьшие стороны кирпича, то условие можно будет записать намного проще.

2016-10-29 23:51 UTC, maximpetrov commented
Решения новых задач не будут проверяться, пока Вы не исправите старые замечания

2016-11-13 18:53 UTC, maximpetrov commented
recheck all

2016-11-14 14:42 UTC, maximpetrov requested changes

2016-11-14 14:42 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double  = (initial + initial/100.0*percent*3 + initial/10000.0*percent*percent*3 + initial/1000000.0*percent*percent*percent)
Это выражение можно упростить гораздо сильнее, пока Вы его скорее усложнили.

2016-11-14 14:42 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +        if (ageEnd == 1) return "$age год"
Стоит записать цепочку условий с помощью `when` или хотя бы `if ... else if ...`.

2016-11-14 14:42 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> + if (danger1==true && danger2==true) return (3)
- Проверка на  `== true` не имеет смысла.
- Скобки вокруг возвращаемого значения не нужны.

2016-11-14 15:09 UTC, maximpetrov requested changes

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    val count = v.size
Зачем заводить эту переменную?

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    return (Math.sqrt(result))
Скобки вокруг возвращаемого значения не нужны

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var count = 0
Зачем Вам считать количество элементов вручную?

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    else return (result / count)
Скобки вокруг возвращаемого значения не нужны

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    else return (0.0)
Скобки вокруг возвращаемого значения не нужны

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    else return (0.0)
Скобки вокруг возвращаемого значения не нужны

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (count > 0) {
Нужна ли эта проверка? Если элементов 0, то ни одна итерация цикла не выполнится.

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (count > 0) {
Нужна ли эта проверка? Если элементов 0, то ни одна итерация цикла не выполнится.

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +            result += (p[i]*Math.pow(x,doubleI))
Здесь эффективнее было бы накапливать множитель `x` в степени, а не вычислять его каждый раз заново.

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        var i = 2
Перебор лучше бы ограничить сверху.

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (n < base){
Зачем здесь этот отдельный случай?

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +            number += 48
Вместо "магических чисел" 48 и 87 можно использовать сами символы `'0'` и `'a'`.

2016-11-14 15:09 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +fun convert(n: Int, base: Int): List<Int> {
Ваш алгоритм перевода крайне неэффективен. Попробуйте переводить традиционным способом, т.е. начиная с младших цифр.

2016-11-19 17:06 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +            number += 48
Ещё в силе

2016-11-19 17:06 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +fun center(list: MutableList<Double>): MutableList<Double> {
Ещё в силе

2016-11-19 17:14 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        var i = 2
Ещё в силе

2016-11-19 17:29 UTC, tyushin commented
+fun factorizeToString(n: Int): String {
+ val result = factorize(n)
+ return result.joinToString(separator = "*")
+}

2016-11-19 20:14 GMT+03:00 Maxim Petrov <notifications@github.com>:

> *@maximpetrov* commented on this pull request.
> ------------------------------
>
> In src/lesson4/task1/List.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/131>:
>
> > @@ -165,7 +208,19 @@ fun factorize(n: Int): List<Int> = TODO()
>   * Разложить заданное натуральное число n > 1 на простые множители.
>   * Результат разложения вернуть в виде строки, например 75 -> 3*5*5
>   */
> -fun factorizeToString(n: Int): String = TODO()
> +fun factorizeToString(n: Int): String {
> +    var number = n
> +    val result = mutableListOf<Int>()
> +    while (number != 1){
> +        var i = 2
>
> Ещё в силе
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/131>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AVCZa42bH5mfLVtnFyYwkl8zt3y03pohks5q_y6HgaJpZM4KJ0ga>
> .
>

2016-11-19 17:33 UTC, maximpetrov commented
Ещё в силе замечание про ограничение перебора сверху

2016-11-19 18:24 UTC, maximpetrov requested changes

2016-11-19 18:24 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +                number += 48
Всё-таки замените "магические числа" (48 и 97) на соответствующие символы.

2016-11-19 18:24 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        while ((number % i != 0) && (i < 2147483648)) {
Я имел ввиду не совсем это: нужно ограничить перебор сверху на основании того, какой может быть самый большой простой делитель у конкретного числа (не считая само число)

2016-11-19 20:06 UTC, maximpetrov requested changes

2016-11-19 20:06 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        while ((number % i != 0) && (i < n)) {
Число действительно может быть простым, но этот случай можно рассмотреть отдельно (если не будут найдены другие делители)

2016-11-19 20:06 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +                result.add(number + 'W'.toInt())
Во-первых, `toInt()` не обязательно, сам символ уже является числом (кодом символа). Во-вторых, почему Вы используете `'W'`? используйте более подходящий в данной ситуации символ.

2016-11-21 08:25 UTC, mglukhikh commented
recheck all

2016-11-26 20:32 UTC, maximpetrov requested changes

2016-11-26 20:32 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        var i = 2
Не заметил сразу: не стоит на каждой итерации перебирать все множители с начала.

2016-11-26 20:32 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        if (i <= n/2) {
Границу можно сделать меньше

2016-11-27 15:15 UTC, maximpetrov requested changes

2016-11-27 15:15 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        if (n/i < 2) {
От перестановки множителей ничего не меняется. Можно придумать границу меньше, чем `n/2`.

2016-11-28 00:00 UTC, maximpetrov requested changes

2016-11-28 00:00 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        // Если в условии ниже поставить "<= 2" то программа будет работать неверно. Я думаю, что "< 2" это крайнее значение
Если менять только условие ниже, то программа действительно будет работать неверно, нужно немного поменять алгоритм ещё в одном месте.

2016-12-19 14:22 UTC, maximpetrov commented
recheck all

2017-07-26 18:23 UTC, closed without merging