сделал 1,2 урок и 3 урок посл задачу
Kotlin-Polytech/KotlinAsFirst2016 pull request #133
Opened 2016-09-29 10:26 UTC by alekszalata

2016-09-29 11:18 UTC, mglukhikh commented on pom.xml
> +        <dependency>
Вам не следовало менять файл pom.xml. Аккуратно посмотрите, что вы в нём поменяли, и верните его в начальное состояние. После этого повторите commit & push, и бот перепроверит ваше решение

2016-09-29 18:06 UTC, mglukhikh commented
Ещё раз обращаю ваше внимание на моё замечание по поводу pom.xml. Пока вы не исправите эту проблему, бот не сможет проверить ваши решения.

2016-09-30 06:41 UTC, mglukhikh commented
recheck all

2016-09-30 06:47 UTC, mglukhikh commented
Нет, pom.xml вы не поправили. В виде исключения поправил его сам. Больше его не меняйте, пожалуйста. Не забудьте сделать git pull (Version Control --> Git --> Pull), когда в следующий раз откроете проект; лучше, чтобы IDEA забыла ваши неправильные настройки (у вас, собственно, была настроена компиляция Котлина в JavaScript; это интересная возможность, но нам она совершенно не нужна), удалить перед этим в проекте папку .idea. Если IDEA предложит импортировать pom.xml заново -- соглашайтесь.

2016-09-30 06:48 UTC, mglukhikh commented
Задачи, кроме одной, решены верно (см. сообщения бота); код я посмотрю чуть позже.

2016-09-30 07:38 UTC, mglukhikh requested changes
Помимо ошибки в `digitNumber` , много мелких замечаний по коду.

2016-09-30 07:38 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial*(1+percent*0.01)*(1+percent*0.01)*(1+percent*0.01)
Используйте `Math.pow` для возведения в степень

2016-09-30 07:38 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun squareSequenceDigit(n: Int): Int {
Поправьте выравнивание кода в этой функции (выделить её код и нажать Ctrl+Alt+L). Отступ в блоке фигурных скобок должен быть четыре пробела. `return` должен находиться на одном уровне с остальным

2016-09-30 07:38 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        var N = 0
Переменные не следует называть с большой буквы, такие имена используются только для типов

2016-09-30 07:38 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            val k = Math.pow(10.0, (N - n).toDouble()).toInt()
Здесь лучше написать свою функцию `pow(x: Int, y: Int): Int = ...`, так как вы работаете с целыми числами. Преобразование к `Double` и обратно может приводить к ошибкам округления, да и операции с вещественными числами имеют погрешность.

2016-09-30 07:38 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +        if ((s>=b) or (s>=c)) x=true
Лучше сразу `return true`. В этом случае переменная `x` (ещё и мутирующая) вам не нужна.

2016-09-30 07:38 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +fun triangleKind(a: Double, b: Double, c: Double): Int {
Полный беспорядок с пробелами. Выделите код функции и нажмите Ctrl+Alt+L для поправки выравнивания. В дальнейшем старайтесь отделять операторы от аргументов пробелами: `a + b` вместо `a+b`

2016-09-30 07:38 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((d>=a) and (d>=b) and (c>=a))
Предпочитайте операторы `&&` и `II` функциям `and` и `or`.

2016-10-28 12:56 UTC, mglukhikh requested changes
Я рад, что вы решили много задач и решили правильно, но замечаний по стилю очень много. Пожалуйста, пройдитесь по вашим файлам и исправьте все замечания, сейчас читать ваш код очень сложно. Потом я пересмотрю его ещё раз. Пожалуйста, исправьте замечания до того, как начнёте решать какие-то ещё задачи

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = 4.445*(sagenes*48+arshins*16+vershoks)/100
Повторно: по-прежнему полный беспорядок с пробелами. Принятый стиль: это использование пробелов вокруг знаков операций, чтобы улучшить читаемость программы. Напоминаю, что его можно исправить используя комбинацию Ctrl+Alt+L

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = grad*PI/180+min*PI/(180*60)+sec*PI/(180*60*60)
Пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(sqr(x1-x2)+ sqr(y1-y2))
Пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun thirdDigit(number: Int): Int = (number/100)%10
Пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = (hoursArrive-hoursDepart)*60+(minutesArrive-minutesDepart)
Пробелы + слишком длинная строка

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial*Math.pow(1+percent*0.01,3.0)
Пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = (number%10)*100+(number/10%10)*10+(number/100)
Пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +fun triangleKind(a: Double, b: Double, c: Double): Int {
Здесь всё исправлен, да.

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((d>=a) && (d>=b) && (c>=a))
Здесь и далее: пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean = (number/1000+(number/100)%10) == ((number%100)/10+number%10)
Пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if ((x1 == x2)||(y1 == y2)||(Math.abs(x2-x1) == Math.abs(y2-y1))) return true
Пробелы. Кроме этого, `if (x) return true else return false` эквивалентно `return x`

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +        if ((s>=b) or (s>=c)) return true
Пробелы. Вместо `or` и `and` почти всегда следует использовать `||` и `&&`

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        x+=1
Пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            second = result}
Закрывающая } на отдельной строке

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun squareSequenceDigit(n: Int): Int {
Ещё раз прошу поправить форматирование кода

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        var N = 0
Ещё раз обращаю ваше внимание, что переменные не следует называть с большой буквы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    result = Math.sqrt(x)
`val result = Math.sqrt(x)`. По возможности объявляйте переменные как можно позже

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var x:Double = 0.0
`var x = 0.0`. То, что тип Double -- очевидно

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +
Лишние пустые строки, добавленные просто так, не украшают код

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +     return   (list.sum()/list.size)
`return if (...) 0.0 else list.sum() / ...`. А ещё лучше `fun mean(...): Double = if ...`

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        x = 0.0 else
Если конструкция if / else вся не умещается на одной строке, следует записывать все `if` и `else` на одном уровне:

```
if (...)
    doFirst
else
    doSecond
```

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (x == 0.0) return list else
См. выше

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        list[i]=list[i]-x
Пробелы

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            c += a[k] * b[k]
Полный кошмар с форматированием

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        x = 0.0 else
Если внутри `else` находится большая конструкция вроде `for`, её лучше взять в фигурные скобки.

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            z += p[i]*Math.pow(x,i.toDouble())
Полный кошмар с форматированием

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    list = listOf()
Эти два действия лучше сделать в одной строчке: `var list = listOf<Int>()`

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..jumps.length - 1) if ((jumps == "") || ((jumps[i] != '%') && (jumps[i] != '-') && (jumps[i] != ' ') && (jumps[i]!in '0'..'9'))) return -1
1) Проверку `jumps` нужно вынести из цикла; 
2) Вместо `for (i in ...)` лучше использовать `for (jump in jumps)`
3) Слишком длинные строки принято разрывать

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..parts.size - 1)
`for (part in parts)`

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            parts2 = parts2 + parts[i].toInt()
Попробуйте реализовать этот фрагмент с помощью функции `map`.

2016-10-28 12:56 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        result = Math.max(result, parts2[i])
У списка есть функция `max`.

2016-11-25 19:46 UTC, mglukhikh commented
recheck all

2016-11-25 19:59 UTC, mglukhikh requested changes
Код довольно грязный, плюс несколько неработающих задач -- см. отчёт бота. Пожалуйста, исправьте замечания, прежде чем решать новые задачи

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun squareSequenceDigit(n: Int): Int {
Поправлено

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        x = list.sum() / list.size
Есть готовая функция `mean`

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (a.size == 0) return c
Эта проверка не нужна

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (p.size == 0) return 0.0
Эта проверка не нужна.

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        }
Форматирование

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..jumps.length - 1) if ((jumps == "") || ((jumps[i] != '%') && (jumps[i] != '-') && (jumps[i] != ' ') && (jumps[i]!in '0'..'9'))) return -1
Замечание по-прежнему в силе

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..parts.size - 1)
Замечание по-прежнему в силе

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            parts2 = parts2 + parts[i].toInt()
Замечание по-прежнему в силе

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        result = Math.max(result, parts2[i])
Замечание по-прежнему в силе

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    var SecondPoint = Point(0.0, 0.0)
`camelCase`: `firstPoint`, `secondPoint`

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    var Length = FirstPoint.distance(SecondPoint)
С маленькой буквы

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            val Distance = points[k].distance(points[i])
С маленькой буквы

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            }
Форматирование. И советую почитать про `atan2`, а то возникают вопросы, что будет, если `second` ноль

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val niceangle = lineBySegment(line).angle
`niceAngle`

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return Circle(BissAB.crossPoint(BissAC), a.distance(BissAB.crossPoint(BissAC)))
Мне кажется, или `crossPoint` у вас не реализована? Поэтому бот и ведёт себя так странно

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val BissAB = bisectorByPoints(a, b)
С маленькой буквы

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +import java.sql.SQLNonTransientException
Ненужный импорт

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        if (start.row == end.row) return 1
Можно использовать `||`

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    val mutabellist = mutableListOf<Square>(start)
`mutableList`

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    val MatrixAnswer = MatrixImpl(height, width, e)
С маленькой буквы

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            for (j in 0..width - 1) if (other[i, j] != this[i, j]) return false
Достаточно сравнить просто списки, сравнивать их отдельные элементы не обязательно

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        result = result * 31 + width
Сюда следует добавить хэш-код списка элементов

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[row, column])
Добавьте разделитель между элементами, например, пробел или запятую. Иначе вы же сами не сможете это прочитать в отчётах бота.

2016-11-25 19:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return true
В этой ветке матрицы не обязаны быть равны

2016-12-20 08:31 UTC, mglukhikh commented
recheck all

2016-12-20 09:06 UTC, mglukhikh requested changes
Короче говоря, по нынешнему состоянию это "3". При условии исправления всех замечаний к четвергу можно подумать о повышении оценки до "4". Плюс у вас не написано тестирование. А копирование чужих решений меня вообще удручает.

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (a in 5..9)
Здесь лучше `when (a)` и далее по тексту

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val length: Double = (t1 * v1 + t2 * v2 + t3 * v3) / 2.0
Тип не нужен

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        if (((sqr(a) - sqr(b) - sqr(c)) / ((-2.0) * b * c) > 0) && ((sqr(b) - sqr(a) - sqr(c)) / ((-2.0) * a * c) > 0) && ((sqr(c) - sqr(b) - sqr(a)) / ((-2.0) * b * a) > 0))
Здесь и ниже очень длинные строки

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        x = list.sum() / list.size
По-прежнему в силе

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +    return answer
Точная копия вашей функции: https://github.com/nightonyx/KotlinAsFirst2016/blob/master/src/lesson8/task1/Files.kt. Даже все имена те же

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return true
Замечание по-прежнему в силе

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        result = result * 31 + width
Замечание по-прежнему в силе

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[row, column])
Замечание по-прежнему в силе

2016-12-20 09:06 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    }
Тоже один в один похожая функция: https://github.com/nightonyx/KotlinAsFirst2016/blob/master/src/lesson6/task1/Geometry.kt

2016-12-20 18:25 UTC, alekszalata commented on src/lesson6/task1/Geometry.kt
> +    }
Извините, но я не списывал задачи. Просто мы живем в одной комнате. Я не мог разобраться с  этими задачами и попросил nightonyx'a мне их разъяснить.

2016-12-20 18:32 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    }
Ага, и на всякий случай написали их точно так же, как и он, с теми же именами переменных, с теми же не соответствующим Code Style большими X и Y и так далее. Вы могли попросить однокурсника разъяснить вам задачи, и он мог вам их объяснить, но написать решение после этого вы должны были сами. Вы же его просто скопировали -- или перепечатали, уж не знаю, как оно у вас там было. В то, что вы случайно всё написали так, как он, извините, не верю.

2016-12-20 19:09 UTC, alekszalata commented
Он показывал на примере своей задачи, я понял но ничего лучше написать не смог и отослал разобранную. Извиняюсь еще раз.  Сейчас работаю над исправлением не рабочих задач из восьмого и шестого урока . И еще не подскажите почему в 6 уроке очень сложная задача то проходит на сайте , то нет?

2016-12-20 19:16 UTC, mglukhikh commented
Потому что бот тестирует задачи на случайно подобранных тестах. Тест, на котором проявляется неправильность вашего решения, то попадает в подборку, то нет. В целом это значит, что в одном из частных случаев ваше решение таки неверно.

2016-12-20 19:17 UTC, alekszalata commented
Спасибо, буду искать ошибку.

2016-12-21 18:07 UTC, alekszalata commented
Михаил, у меня не получается разобраться в какой из задач (из которых состоит очень сложная) у меня недочет.

2016-12-26 06:38 UTC, mglukhikh commented
В `crossPoint`.

2017-07-26 18:23 UTC, closed without merging