Lesson 1,2,3
Kotlin-Polytech/KotlinAsFirst2016 pull request #134
Opened 2016-09-29 10:34 UTC by Xepishons

2016-09-29 11:16 UTC, mglukhikh commented
recheck all

2016-09-29 14:10 UTC, mglukhikh commented
recheck all

2016-09-29 17:20 UTC, maximpetrov requested changes

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (age <= 10) {
Попробуйте уменьшить количество проверяемых условий. Кроме того, цепочку условий `if ... else if ...else` принято записывать на одном уровне:

``` kotlin
if (...) ...
else if (...) ...
else ...
```

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    var S = (t1 * v1) + (t2 * v2) + (t3 * v3)
Переменную `S` можно было сделать `val`, если поделить на 2 сразу.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    var S = (t1 * v1) + (t2 * v2) + (t3 * v3)
Лучше завести переменные для длин отрезков пути.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (((rookX1 == kingX) || (rookY1 == kingY)) && (rookX2 == kingX) || (rookY2 == kingY)) return 3 else
Лучше завести переменные для условий угрозы от каждой из ладей.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (((rookX == kingX) || (rookY == kingY)) && ((Math.abs(kingX - bishopX)) == (Math.abs(kingY - bishopY)))) return 3 else
Лучше завести переменные для условий угрозы от ладьи и от слона.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +  if (((a + b) <= c) || ((a + c) <= b) || ((b + c) <= a)) return -1 else
Лучше сначала найти наибольшую из сторон , а тогда вычислений будет намного меньше

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((c in a..b) && (d in a..b)) return d - c
Здесь можно использовать конструкцию `(c..d) in (a..b)`

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if ((a + b) == (c + d)) return true else return false
[Здесь и далее] Выражение `if (x) return true else return false` эквивалентно `return x`

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +fun brickPasses(a: Int, b: Int, c: Int, r: Int, s: Int): Boolean =
Если сначала найти наименьшие стороны кирпича, то условие станет намного проще.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    if (n == 1) return 1
Если задать 1 в качестве начального значения для `l`, то проверки на `n == 1` и `n == 2` не нужны.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n*m) {
Существует намного более оптимальный метод нахождения НОК, чем полный перебор.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n)
Не обязательно перебирать числа до `n`.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n-1 downTo 1)
Не обязательно перебирать числа до 1.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..m){
Подумайте над более оптимальным решением.

2016-09-29 17:20 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (k in 1..n)
Во-первых, 0 - тоже целое число, во-вторых, перебирать до `n` совсем не эффективно.

2016-10-29 12:49 UTC, maximpetrov requested changes

2016-10-29 12:49 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (age <= 10) {
Замечание про упрощение этой функции всё ещё в силе

2016-10-29 12:49 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val halfAllWay = (t1 * v1 + t2 * v2 + t3 * v3) / 2
Эту переменную можно вычислить через две следующие

2016-10-29 12:49 UTC, maximpetrov commented
recheck all

2016-11-29 15:37 UTC, maximpetrov commented
Новые уроки всё ещё не рассматриваются в связи с отсутствием исправления замечаний по предыдущим урокам.

2016-11-30 22:15 UTC, maximpetrov requested changes

2016-11-30 22:15 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else if ((age in 2..4) || ((age % 10) in 2..4)) return "$age года"
Зачем отдельно рассматривается случай `age in 2..4`?

2016-12-01 16:28 UTC, Xepishons commented on src/lesson2/task1/IfElse.kt
> +    else if ((age in 2..4) || ((age % 10) in 2..4)) return "$age года"
А как без него?

2016-12-01 19:13 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else if ((age in 2..4) || ((age % 10) in 2..4)) return "$age года"
Чем он выделяется из `((age % 10) in 2..4)`?

2016-12-06 08:01 UTC, maximpetrov commented
Всё ещё не исправлены [замечания](134/files) по 2 и 3 урокам.

2016-12-08 12:42 UTC, mglukhikh commented
recheck all

2016-12-08 12:42 UTC, mglukhikh commented
recheck all

2016-12-08 12:47 UTC, mglukhikh commented
Прошу обратить внимание на тесты, которые не проходят в уроках 4 и 5. В уроке 6, рекомендую решить ещё хотя бы одну задачу более высокой сложности.

2016-12-08 14:45 UTC, maximpetrov requested changes

2016-12-08 14:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            for (i in 2..n * m) {
Нужно заменить весь алгоритм определения НОК на более быстрый, а не рассматривать несколько частных случаев отдельно.

2016-12-08 14:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            ?: n
Лучше не стоит выносить этот оператор на отдельную строку.

2016-12-08 14:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            ?: n
Лучше не стоит выносить этот оператор на отдельную строку.

2016-12-08 14:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    return (n - 1 downTo 1).firstOrNull { (n % it) == 0 }
Интервал перебора можно уменьшить.

2016-12-08 14:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..m) {
Используемый метод всё ещё не оптимален

2016-12-08 14:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if (sqrt % 1 == 0.0)
Проверять таким образом `double` на то, что оно целое, неправильно.

2016-12-08 14:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            if (sqrt * sqrt in m..n) return true
Эта проверка не имеет смысла: `sqrt` у Вас - это точный корень, его квадрат может отличаться от `result` только в пределах точности `double`.

2016-12-16 15:05 UTC, maximpetrov commented
recheck all

2016-12-16 15:30 UTC, maximpetrov requested changes

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun nok(a: Int, b: Int): Int {
Почему `nok`, если НОД.

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun maxDivisor(n: Int): Int = ((n/2) downTo 1).firstOrNull { (n % it) == 0 } ?: n
Интервал можно сделать ещё меньше (перебирать не до 1)

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    val new = list.map { it - average }
По заданию нужно изменять тот список, который передан на вход, а не создавать новый.

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        result += p[i] * Math.pow(x, i.toDouble())
Здесь лучше бы накапливать множитель `x` в степени, а не вычислять его заново.

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var result = list[0]
Можно обойтись без промежуточной переменной

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    while (divider < m) {
Здесь стоит сильнее ограничить перебор сверху

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        divider++
Лучше инициализировать эту переменную 2, а увеличивать после выполнения итерации, чтобы не никого запутывать.

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    while (m > 0) {
Здесь лучше бы воспользоваться `SortedMap`.

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if (a[0].toInt() in 1..9) result += "0" + a[0] + "."
Собирать `String` по частям не эффективно, используйте `StringBuilder`, хотя гораздо лучше будет сохранить все компоненты даты в `int` переменные, а потом собрать строку с помощью `String.format`.

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        when {
Используйте синтаксис `when` с аргументом. Или, что лучше, создайте список месяцев и используйте его (причём общий со следующем функцией).

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if (a[0].toInt() in 1..9) result += (a[0].toInt()).toString() + " "
Те же замечания, что и к предыдущей функции

2016-12-16 15:30 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (phone.matches(Regex("^[+]?[-()0-9 ]+"))) {
Если уж Вы используете регулярное выражение для разбора формата, то делайте это честно: плюс на первом месте - это не единственное требование формата.

2016-12-18 16:16 UTC, Xepishons commented on src/lesson3/task1/Loop.kt
> +fun maxDivisor(n: Int): Int = ((n/2) downTo 1).firstOrNull { (n % it) == 0 } ?: n
Но у простых чисел максимальный делитель 1

2016-12-19 14:02 UTC, maximpetrov commented
recheck all

2016-12-19 14:18 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            "01" -> month += "января"
Почему `+=`?

2016-12-19 14:18 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            "января" -> month += 1
Почему `+=`?

2016-12-19 14:18 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun maxDivisor(n: Int): Int = ((n/2) downTo 1).firstOrNull { (n % it) == 0 } ?: n
У простых чисел минимальный делитель действительно 1. А максимальный у них - само число, но это не помешало Вам в прошлой задаче перебирать множители до корня из этого числа.

2016-12-21 20:58 UTC, maximpetrov requested changes

2016-12-21 20:58 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if (a[0].toInt() in 1..31) day += a[0].toInt()
- Почему здесь тоже +=?
- Почему бы сначала не сохранить переведённое в `Int` число в переменную, а потом уже проверять эту переменную, чтобы не делать перевод два раза?

2016-12-21 20:58 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val year = a[2].toInt()
Почему Вы считаете, что год точно правильно переведётся в `Int`?

2016-12-21 20:58 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val year = a[2].toInt()
Почему Вы считаете, что год точно правильно переведётся в `Int`?

2016-12-21 20:58 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if (a[0].toInt() in 1..31) day += a[0].toInt()
- Почему здесь тоже +=?
- Почему бы сначала не сохранить переведённое в `Int` число в переменную, а потом уже проверять эту переменную, чтобы не делать перевод два раза?

2016-12-22 22:38 UTC, Xepishons commented on src/lesson5/task1/Parse.kt
> +    val year = a[2].toInt()
Потому что год - целое число. И, вроде как, работает...

2016-12-22 22:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val year = a[2].toInt()
Никто не мешает передать в эту функцию строку вида "1 марта qwerty". И что тогда произойдёт с Вашей функцией?

2017-07-26 18:23 UTC, closed without merging