Lesson 1
Kotlin-Polytech/KotlinAsFirst2016 pull request #136
Opened 2016-09-29 10:52 UTC by lixir

2016-09-29 17:15 UTC, belyaev-mikhail commented
recheck all

2016-09-29 17:59 UTC, belyaev-mikhail commented
В задании 2.1 у вас не проходят даже базовые тесты. Пожалуйста, не отправляйте решений, которые не проходят базовые тесты.

2016-10-08 19:49 UTC, lixir commented
0 не натуральное число, а в заданиях [Normal] lesson4.task1/convert и [Hard] lesson4.task1/convertToString указано любое натуральное число

2016-10-08 19:55 UTC, maximpetrov commented
recheck assignment

2016-10-08 20:14 UTC, maximpetrov commented
recheck assignment

2016-10-08 21:15 UTC, belyaev-mikhail commented
Является ли 0 натуральным числом, математика до сих пор не определилась.
В данном задании подразумевалось, что является.

2016-10-10 11:22 UTC, belyaev-mikhail commented
Ваше решение на `factorize()` работает за время, кратное квадрату от числа элементов. Для любых чисел больше 1000000 оно работает дольше 10 минут. Это следует переделать.

2016-10-10 19:43 UTC, lixir commented
Спасибо, исправил.

2016-10-10 20:22 UTC, belyaev-mikhail requested changes

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double {
Формулировка задачи подразумевает, что готовую функцию преобразования градусов в радианы использовать нельзя.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val L = Math.sqrt( sqr(x0) + sqr(y0))
Называть переменные нужно консистентно. Либо вы их называете с больших букв, либо с маленьких, но одинаково везде.
В котлине общепринято называть переменные с маленькой буквы.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val ostatok = number % 1000
Использование транслита в коде &mdash; признак очень плохого стиля

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int = if (n<=2) 1 else fib(n-1) + fib(n-2)
Пробелами в коде следует пользоваться консистентно. Если вы ставите пробелы до и после операторов, следует ставить их **везде**, если не ставите &mdash; не следует их ставить **нигде**.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    var NOK = 1
См. комментарии про имена переменных и транслит.
Кроме того, очень странный алгоритм вычисления НОК.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    var NOD = 1
См. комментарии про имена переменных и транслит.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    return if (k == 0) false
Конструкция `return if(X) false else true` лишена смысла, т.к. ничем не отличается от `return !X`

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        if ((m % i == 0) && (n % i == 0)) k = 0
Зачем перебирать оставшиеся множители, если мы уже нашли общий? Почему нельзя прямо здесь вернуть `false`?

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        if ((Math.sqrt(i.toDouble()) % 1) == 0.0) return true
Это некорректная проверка на целость квадратного корня. Значения типа `Double` нельзя сравнивать на равенство, т.к. они по определению являются приближёнными.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        result+= element
См. комментарий про пробелы.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        list[i]=list[i]-center
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        element=element+(a[i]*b[i])
См. комментарий про пробелы.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        x1=x1*x
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        a[i]=list[i]+a[i-1]
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +                list.add(i)
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String {
В решении задач можно использовать функции из других задач. В частности, незачем было копировать 90% кода функции `factorize`, когда её можно было просто вызвать и таким образом реализовать `factorizeToString` в одну строчку.

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        n1/=base
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        mod=n1%base
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            if (mod==10) list.add(0,"a")
Вы уверены, что никак нельзя таблицу символов `'a'-'z'` записать как-то иначе?
Например, объявить обычную строковую переменную и её индексировать?

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        x1 = x1*x
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    }
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        result += (Int*step(base,str.length-1-i))
См. комментарий про пробелы

2016-10-10 20:22 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        if ((thous%10 == 0) && (x==1)) str1+=" тысяч "
См. комментарий про пробелы

2016-10-14 21:45 UTC, belyaev-mikhail commented
Исправляйте, пожалуйста, представленные замечания. Они носят не рекомендательный, а обязательный характер.

2016-10-15 20:48 UTC, belyaev-mikhail requested changes

2016-10-15 20:48 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        for (i in 'a'..'z') str += i
Что вы тут пытались сделать? Сейчас этот код не имеет никакого смысла.

2016-10-15 20:48 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +    val result= str0+"."+str1+"."+parts[2]
Лучше использовать интерполяцию: `"$str0.$str1.${parts[2]}"`

2016-10-15 20:48 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +        if (parts[i]==parts[i+1]) return sum
Пробелы

2016-10-15 20:57 UTC, lixir commented on src/lesson4/task1/List.kt
> +        for (i in 'a'..'z') str += i
Простите, я забыл стереть. Пытался исправить и не придумал нового решения

2016-10-16 12:55 UTC, belyaev-mikhail commented
По заданию 5: внимательно следите за тем, что в задании просят сделать в случае некорректного ввода. В задании 5.1 `plusMinus` нужно выбросить `IllegalArgumentException`.
При проверке задания ботом такие ситуации тоже проверяются, причем важен только тип исключения (он должен таким, как указано в задании), а не его содержимое.

2016-10-18 20:50 UTC, lixir commented
не проверилось

2016-10-19 17:01 UTC, belyaev-mikhail commented
recheck assignment

2016-10-19 17:44 UTC, belyaev-mikhail commented
recheck assignment

2016-10-19 17:50 UTC, belyaev-mikhail commented
recheck assignment

2016-10-20 13:06 UTC, belyaev-mikhail requested changes

2016-10-20 13:06 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val meters = (( sagenes * 48) + (arshins * 16) + vershoks) *4.445 / 100
Пробелы

2016-10-20 13:06 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val sum1 = initial + ( initial * per )
Пробелы

2016-10-20 13:06 UTC, closed without merging