Programs by ProkhorovMax (13531/3)
Kotlin-Polytech/KotlinAsFirst2016 pull request #137
Opened 2016-09-29 11:35 UTC by Prokhorovmax

2016-09-29 12:33 UTC, ice-phoenix commented
recheck all

2016-09-29 12:37 UTC, ice-phoenix commented
recheck all

2016-09-29 12:53 UTC, ice-phoenix requested changes
Исправляйте **все** предыдущие замечания к вашему коду перед подачей следующих PR

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val a = hours*3600
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val dlina = sqrt (sqr(x2-x1)+sqr(y2-y1))
Использование транслитерации в имени переменной --- **очень плохой** стиль

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val a = number%10
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +       (age % 10 == 1)&&(age%100 != 11) -> "$age год"
Отформатируйте код при помощи IntelliJ IDEA и в дальнейшем постарайтесь придерживаться данного стиля кодирования

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX1) || (kingY == rookY1)) && ((kingX == rookX2) || (kingY == rookY2))) return 3
Выражения, проверяющие факт атаки короля той или иной фигурой, следует вынести в отдельные переменные

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return  if ((c>=a) && (d<=b)) d-c
Данное выражение лучше оформить как `when`

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +import lesson2.task1.timeForHalfWay
Зачем в `lesson3` импорт функции из `lesson2`?

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number = n
Форматирование кода

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        else continue
Данная конструкция является излишней

2016-09-29 12:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n%i == 0) res = i
Зачем при поиске максимального делителя идти от минимального делителя к максимальному?

2016-09-29 13:38 UTC, Prokhorovmax commented on src/lesson3/task1/Loop.kt
> +import lesson2.task1.timeForHalfWay
Без понятия, откуда там эта строчка и зачем.

2016-09-29 13:39 UTC, Prokhorovmax commented on src/lesson1/task1/Simple.kt
> +    val dlina = sqrt (sqr(x2-x1)+sqr(y2-y1))
Я давно это понял. Извините, просто забыл исправить старые ошибки.

2016-09-29 13:52 UTC, Prokhorovmax commented on src/lesson3/task1/Loop.kt
> +        if (n%i == 0) res = i
Не могу реализовать программу, когда надо перебирать значения от большего к меньшему(любую программу). У меня выделяется красным "downto", поэтому я не понимаю, что делать в данном случае и еще не могу решить пару других задач, где это нужно. Был бы признателен, если бы вы объяснили, что не так. Спасибо

2016-09-29 14:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n%i == 0) res = i
Можно попробовать подойти к преподавателю на занятиях и спросить, что не так

2016-09-29 14:25 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +import lesson2.task1.timeForHalfWay
Как разработчик, вы отвечаете за весь код и все изменения, сделанный вами. Вариант "без понятия, откуда что-то где-то", к сожалению, не подходит ни для нас во время учебы, ни для вашего начальника во время работы. В будущем просматривайте изменения перед комитом и убеждайтесь в том, что там нет ничего лишнего.

2016-09-29 18:15 UTC, ice-phoenix requested changes

2016-09-29 18:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        str += (i * i).toString()
Подумайте, строка какой длины потребуется для того, чтобы посчитать `squareSequenceDigit(1000000)`. Можно ли обойтись без хранения значений промежуточных квадратов?

2016-09-29 18:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        result += number % 10 * Math.pow(10.toDouble(), length - i.toDouble())
Подумайте, как можно организовать ваш код так, чтобы не было необходимо каждый раз возводить 10 в требуемую степень с самого начала

2016-10-03 11:45 UTC, belyaev-mikhail commented
recheck assignment

2016-10-03 14:12 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        if (n%i == 0) res = i
Раз уж заметил: нужно писать `downTo`. Это ошибка в учебном пособии, которая сейчас уже исправлена.

2016-10-03 20:12 UTC, ice-phoenix commented
recheck all

2016-10-03 20:17 UTC, ice-phoenix commented
Просьба исправить предыдущие замечания перед тем, как продолжать работу над следующими модулями

2016-10-03 20:21 UTC, ice-phoenix requested changes
Кроме этих замечаний, исправьте предыдущие замечания

2016-10-03 20:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            sum += v[i] * v[i]
Если вам не нужен явный индекс, то лучше воспользоваться циклом в `foreach` стиле.
```
for (e in list) {
    foo(e)
}
```

2016-10-03 20:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        average /= length
Вместо всего этого можно просто `list.sum() / list.size`

2016-10-03 20:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    number = square.toDouble()/Math.pow(10.0, (count).toDouble())
Вычисления в `Double` могут выполняться с недостаточной точностью. Нельзя ли организовать код так, чтобы все вычислять в `Int`?

2016-10-06 13:45 UTC, ice-phoenix commented
recheck all

2016-10-06 13:51 UTC, ice-phoenix commented
recheck all

2016-10-11 14:35 UTC, ice-phoenix requested changes

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val hoursInSeconds = hours*3600
Форматирование кода должно быть единообразным. Если вы разделяете операции пробелами, то делайте это везде. Если вы пишете операции вместе с операндами, то тоже делайте это везде. У вас же стиль плавает туда-сюда, что не есть очень хорошо.

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val res = if (half <= s1) half / v1
Если вы используете `if` как выражение, то форматирование должно выглядеть как

```
val a = if (...) ...
        else if (...) ...
        else ...
```

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var first = 0
- Почему `first` и `second` не типа `Boolean`?
- Почему их значения не инициализируются сразу при объявлении?

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((first == 1) && (second == 1)) return 3
Данное выражение лучше оформить как `when`

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            res = i
Можно обойтись без переменной `res`, если сразу возвращать результат работы функции

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            res = i
Можно обойтись без переменной res, если сразу возвращать результат работы функции

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((m % i == 0) && (n % i == 0)) return false
Можно ли данную функцию выразить через другие функции данного модуля?

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var sign = 1 // Значение будет определять, с каким знаком брать очередной член ряда.
Почему у данной переменной тип не `Boolean`?

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +                numerals[i] = alphabet[(numerals[i].toInt() - 10)].toString()
Почему нельзя сразу записывать правильное представление очередной цифры в итоговый список?

2016-10-11 14:35 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        res += digits[i] * Math.pow(base.toDouble(), (length - i - 1).toDouble()).toInt()
Лучше было пару уроков назад написать `pow`, принимающий `Int`

2016-10-11 14:35 UTC, ice-phoenix commented
recheck all

2016-10-11 14:41 UTC, ice-phoenix commented
Исправляйте замечания (см. вкладку `Files changed`) и продолжаем работать дальше =)

2016-10-20 10:07 UTC, ice-phoenix commented
recheck all

2016-10-20 10:48 UTC, ice-phoenix requested changes
Исправляем замечания и работаем дальше

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (half <= s1) half / v1
Данное выражение лучше оформить как `when`

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var first : Boolean = false
* Система типов Котлина выведет тип переменной автоматически

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX == rookX1) || (kingY == rookY1)) first = true
Если присвоить переменной значение сразу при объявлении, то можно будет сделать ее `val`

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +import java.lang.reflect.Executable
Зачем вам этот импорт?

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((n == 1) || (n == 2)) 1
Лишние скобки

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    throw Exception()
Что?

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            return i
Почитайте про более быстрые алгоритмы поиска НОК

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    throw Exception()
Зачем?

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((m % i == 0) && (n % i == 0)) return false
Нельзя ли эту функцию выразить через другие функции, разработанные вами в этом модуле?

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            sign = true
Лучше сделать `sign = !sign` и вынести это из `if`

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (Math.abs(Math.pow(x1, a) / factorial(b)) >= eps)
Повторно используемое выражение (тем более, с факториалом) лучше не считать два раза

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return ((square / (Math.pow(10.0, (count).toDouble()))) % 10).toInt()
Напишите `pow`, который работает с целыми числами

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (v.size == 0) return 0.0
Подумайте, нужна ли эта проверка? Сколько раз выполнится тело цикла ниже в случае, если список пуст?

2016-10-20 10:48 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val revertedNumerals = mutableListOf<Int>()
Есть функция `reverse() / reversed()`, которая вроде бы делает то, что вам надо, но несколько попроще

2016-10-22 12:30 UTC, Prokhorovmax commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX == rookX1) || (kingY == rookY1)) first = true
Я не очень понимаю, что мы выиграем от этого, да и вдобавок компилятор не позволяет мне так сделать.

2016-10-23 17:43 UTC, Prokhorovmax commented on src/lesson4/task1/List.kt
> +    val revertedNumerals = mutableListOf<Int>()
К сожалению, эта функция не позволяет мне далее использовать индексы. Но, возможно что-то я делаю не так; спрошу у преподавателя на паре.

2016-10-24 11:58 UTC, Prokhorovmax commented on src/lesson4/task1/List.kt
> +    val revertedNumerals = mutableListOf<Int>()
Все узнал, получилось.

2016-10-24 11:59 UTC, Prokhorovmax commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX == rookX1) || (kingY == rookY1)) first = true
Мне подсказали, что имелось в виду, исправил.

2016-10-25 08:31 UTC, ice-phoenix requested changes
Спасибо за исправления, все очень и очень здорово! :sunglasses:

2016-10-25 08:31 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    (Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1))) <= (r2 - r1)
Лишние скобки вокруг законченного выражения `Math.sqrt(...)`

2016-10-25 08:31 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        Math.abs(m * n) / gcd(m, n)
Зачем вызов модуля?

2016-10-25 08:31 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        gcd(m, n) == 1
:+1:

2016-10-25 08:31 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val alphabet = listOf<Char>('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z')
В принципе, это можно заменить на строку `"abc...xyz"`

2016-10-25 08:31 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            else numerals.add(revertedNumerals[i].toString())
Весь этот цикл лучше заменить на вызов функции `map` над `revertedNumerals`

2016-10-25 17:47 UTC, Prokhorovmax commented on src/lesson4/task1/List.kt
> +            else numerals.add(revertedNumerals[i].toString())
Начал делать с помощью map, не все получалось, но в итоге сделал без map и существенно проще и короче.

2016-10-27 11:24 UTC, ice-phoenix requested changes

2016-10-27 11:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        Math.abs(m * n) / gcd(m, n)
Данное замечание все еще в силе

2016-10-27 11:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        return numerals.joinToString("")
Лучше сразу `numerals.reversed().joinToString(...)`

2016-10-27 11:24 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if ((e == '+') && (parts[i - 1].toInt() > maxHigh)) {
Вместо цикла можно `parts[i].contains(...) && ...`

2016-10-27 11:24 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                maxHigh = parts[i - 1].toInt()
Повторно используемые подвыражения лучше вынести в отдельные переменные с говорящими именами

2016-10-28 10:46 UTC, ice-phoenix commented
Все вообще отлично. Закрываю данный PR, чтобы облегчить жизнь GitHub'у, не забудьте создать новый PR после того, как решите следующие задачи.

2016-10-28 10:46 UTC, closed without merging