3 Lesson(hard)
Kotlin-Polytech/KotlinAsFirst2016 pull request #141
Opened 2016-09-29 16:45 UTC by onfound

2016-09-29 18:22 UTC, mglukhikh commented
Исправьте ошибки компиляции, пожалуйста, иначе бот не сможет ничего проверить

2016-09-29 18:23 UTC, ice-phoenix commented
Обратите внимание, что ваш код даже не компилируется. Напоминаю, что работоспособность вашего кода перед отправкой PR следует проверять локально, у себя на машине, при помощи встроенных тестов.

2016-09-30 09:03 UTC, ice-phoenix commented
recheck all

2016-09-30 09:32 UTC, ice-phoenix requested changes

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((age % 10 == 2) || (age % 10 == 3) || (age % 10 == 4)) && (age !in 12..14) && (age !in 112..114) -> "$age года"
Выражение `(age % 10 == 2) || (age % 10 == 3) || (age % 10 == 4)` можно записать проще, через оператор `in`

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val condition = (kingX == rookX1 || kingY == rookY1)
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val condition = (abs(kingX - bishopX) == abs(kingY - bishopY))
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((b >= c) && (d >= a)) {
Данное выражение лучше оформить как `when`

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        ((sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1)) + r1) <= r2)
[Здесь и везде] Лишние скобки вокруг всего выражения

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        (((b <= r) && ((a <= s) || (c <= s))) || ((a <= r) && ((b <= s) || (c <= s))) || ((c <= r) && ((a <= s) || (b <= s))))
Сгруппируйте отдельные составляющие логического выражения, отвечающие за разные варианты прохождения кирпича через отверствие, на разных строках

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        number = fib(n - 2) + fib(n - 1)
Переменная `number` избыточна, можно сразу делать `return` по нужному выражению

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            k++
* Нет ли взаимно однозначного соответствия между значениями `i` и `k`  в цикле?
* Нет ли  какой-то более точной оценки для минимально возможного значения НОК двух чисел, чем 1?

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var maxDiv = n - 1
Нет ли более точной оценки для возможного значения максимального делителя числа, не равного `n`?

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var devisor = 2
Можно ли данный алгоритм выразить через другие функции, разработанные вами в этом модуле?

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((sqrt(i.toDouble()) % 1) == 0.0) bool = true
* Что, по вашему, делает операция `a % 1`?
* Нет ли более быстрого способа проверить, существует ли требуемое `k`? Например, попытавшись построить более точные границы для перебора, выразив оценки для `k` из `m <= k*k <= n`?

2016-09-30 09:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var m = n
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-03 19:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        condition && (b != c) && (d != a) -> min(b, d) - max(a, c)
Второе условие лучше бы тоже вынести в отдельную переменную

2016-10-03 19:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (sqrt(i.toDouble()) == 0.0) bool = true
Что вы хотели выразить данным условием?

2016-10-03 19:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    number = square.toDouble() / pow(10.0, (count).toDouble())
При расчете в `Double` может сильно пострадать точность. Нельзя ли организовать код так, чтобы все считать в `Int`?

2016-10-03 19:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    number = fibonach.toDouble() / pow(10.0, (count).toDouble())
При расчете в `Double` может сильно пострадать точность. Нельзя ли организовать код так, чтобы все считать в `Int`?

2016-10-10 11:42 UTC, ice-phoenix requested changes
Исправляйте замечания

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val hazardLadya = (abs(kingX - bishopX) == abs(kingY - bishopY))
Использование транслита в именах переменных --- не очень хороший стиль

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (((k % m) != 0) || ((k % n) != 0)) k = i + 1 else break
* Зачем вам здесь две переменных `k` и `i`, если можно обойтись одной?
* Есть ли более хорошая нижняя граница на возможное НОК, чем 1?
* Почитайте про более быстрые алгоритмы поиска НОК

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var maxDiv = n - 1
К сожалению, ваш ответ `нет` удалился при редактировании кода, но быть неправильным от этого он не перестал. Подумайте сами или почитайте в интернете, каким числом ограничены все делители числа `n`, не включая само `n`.

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (sqrt(i.toDouble()) % 1 == 0.0) bool = true
А что делает данная проверка (отличающаяся от предыдущей `... % 1`)? Объясните словами в ответе на этот комментарий.

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun revert(n: Int): Long {
Почему вы поменяли тип возвращаемого значения функции?

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number: Double
Зачем объявлять переменную здесь, а определять в самом конце функции?

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number: Double
Зачем объявлять переменную здесь, а определять в самом конце функции?

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    number = (fibonach / pow(10.0, count.toDouble()))
Почему бы не вызвать `toInt()` прямо здесь?

2016-10-10 11:42 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    number = (square / pow(10.0, count.toDouble()))
Почему бы не вызвать `toInt()` прямо здесь?

2016-10-10 18:41 UTC, onfound commented on src/lesson3/task1/Loop.kt
> +        if (sqrt(i.toDouble()) % 1 == 0.0) bool = true
проверяет на целочисленность результат извлечения корня

2016-10-10 18:45 UTC, onfound commented on src/lesson3/task1/Loop.kt
> +fun revert(n: Int): Long {
Последняя проверка в тестовой функции бота  задает число n, при обработке которого в последней итерации цикла появляется число, превышающее тип integer.

2016-10-11 14:55 UTC, ice-phoenix requested changes

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (maxSide < (minSide + anotherSide)) {
Это тоже можно представить в виде одного из условий вложенного сейчас в `if` `when`

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        else -> -1
Браво! Это один из самых компактных, понятных и правильных способов решить эту задачу.

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (sqrt(i.toDouble()) % 1 == 0.0) bool = true
Проверять на целочисленность `Double` --- очень плохая идея вообще и в данной задаче в частности. Подумайте, нельзя ли слегка изменить ваш алгоритм так, чтобы все считать в `Int`.

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n.toLong() == revert(n)) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number: Int
Зачем?

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        for (element in v) sqr += element * element
Если `v` пустой, то цикл просто выполнится 0 раз, и все точно так же будет продолжать работать --- проверка на `v.isNotEmpty()` лишняя

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
См. замечание к `abs`

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var C = 0.0
Называть переменные с большой буквы в `Kotlin` не принято

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            val elementA = a[i]
Зачем вам переменные `elementA` и `elementB`?

2016-10-11 14:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        var mean = p[0]
Почему такое имя переменной?

2016-10-11 14:56 UTC, ice-phoenix commented
recheck all

2016-10-17 12:00 UTC, ice-phoenix requested changes
Исправляем все замечания и работаем дальше.

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> + * Вернуть 0, если угрозы нет,  1, если угроза только от ладьи, 2, если только от слона,
В будущем старайтесь не изменять не относящиеся к решаемой задаче места в коде

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var devisor = 2
`divisor`

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            k = true
Можно обойтись без переменной `k` и `break`, если сразу возвращать результат

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n) {
Нет ли более точных границ для перебора возможных квадратов между `m` и `n`?

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return results.toInt()
Если вы все считаете в `Long`, а потом обрезаете в `Int`, то зачем все было считать в `Long`?

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return n == revert(n)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return ((square / pow(10.0, count.toDouble())) % 10).toInt()
`toInt()` лучше вызвать максимально рано, чтобы как можно больше вычислений считать без потери точности (в идеале, конечно же, написать целочисленный `pow`)

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return ((fibonach / pow(10.0, count.toDouble())) % 10).toInt()
См. замечания к `squareSequenceDigit`

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return abs(sqrt(sqr))
Зачем брать модуль от результата извлечения квадратного корня?

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.size > 1) {
Сколько раз выполнится тело цикла `for` ниже, если размер списка 1?

2016-10-17 12:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += newListResult[i] + " "
Это все можно сделать через `joinToString`

2016-10-17 12:00 UTC, ice-phoenix commented
recheck all

2016-10-20 19:23 UTC, onfound commented on src/lesson4/task1/List.kt
> +    if (list.size > 1) {
0

2016-10-24 16:11 UTC, ice-phoenix requested changes

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        (grad * PI) / 180 + (min * PI) / (180 * 60) + (sec * PI) / (180 * 3600)
Выражение можно упростить с использованием математических законов

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        s / 2 <= s1 -> s / (2 * v1)
Если везде используется `s / 2`, то, может быть, следует именно это выражение вынести в отдельную переменную?

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    /*return when {
Устаревшие комментарии лучше удалять из кода

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var member1: Int = 1
- Система типов Котлина выведет тип переменной автоматически

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (((k % m) != 0) || ((k % n) != 0)) k = i + 1 else break
Все эти замечания все еще актуальны и должны быть исправлены

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var maxDiv = (n / 2).toInt()
Зачем здесь вызов `toInt()`?

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            bool = false
Нельзя ли эту функцию выразить через другие функции этого модуля?

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val squareRoot = sqrt(m.toDouble()).toInt()
Для округления лучше использовать специальные функции `floor / ceil / round`

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (squareRoot * squareRoot in m..n) || ((squareRoot + 1) * (squareRoot + 1) <= n)
Можно ли упростить данное условие, если воспользоваться правильной функцией из `floor / ceil / round`?

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (square / powInt(10, count) % 10)
В Котлине можно объявлять функции с одним и тем же именем, которые принимают на вход аргументы разных типов

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    /*return ((square / pow(10.0, count.toDouble())) % 10).toInt()*/
Лишние комменты лучше удалять из исходного кода

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        list[i] = element - mean
Можно сразу `list[i] = list[i] - mean`

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.size > 1) {
Зачем в таком случае проверять, что в списке лежит больше 1 элемента?

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result = list + result
Лучше всего добавлять результаты в конец `result`, а потом просто развернуть список при помощи `reverse() / reversed()`

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
Для сборки строки лучше использовать или список строк, или `StringBuilder`

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result+= digits[i]* powInt(base, digits.size-1-i)
Форматирование кода

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val arabicNumerals = listOf(1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000)
Вместо индексации по двум массивам следует сделать либо массив пар, либо `Map` из арабских чисел в римские, и потом искать требуемые данные

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return newListResult.joinToString(" ")
Можно сразу `listResult.filter { it != "" }.joinToString(" ")`

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    try{val list = listOf<String>("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Форматирование кода

2016-10-24 16:11 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (element in list) {
Это все можно сделать при помощи функции `list.indexOf(...)`

2016-10-24 16:12 UTC, ice-phoenix commented
Обращаю ваше внимание, что ваш код не проходит один из встроенных тестов. В дальнейшем убедительная просьба проверять работоспособность решений при помощи запуска тестов из IDE.

2016-10-28 09:29 UTC, ice-phoenix commented
recheck all

2016-10-28 10:06 UTC, ice-phoenix requested changes

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val devidedByTwo = s / 2
Лучше `halfWay`

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    /*var k = max(m, n)
Устаревший комментарий лучше удалить

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (m1 != n1) if (m1 > n1) m1 -= n1 else n1 -= m1
Вычисление НОД лучше вынести в отдельную функцию

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return sqr(ceil(sqrt(m.toDouble()))) in m..n
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return sqr(ceil(sqrt(m.toDouble()))) in m..n
:+1:

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (square / pow(10, count) % 10)
Лишние скобки вокруг законченного выражения

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val map1 = mapOf<Int, String>(1 to "I", 4 to "IV", 5 to "V", 9 to "IX", 10 to "X", 40 to "XL", 50 to "L", 90 to "XC", 100 to "C", 400 to "CD", 500 to "D", 900 to "CM", 1000 to "M")
Можно `mapOf(...)` без явного указания типов

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += map1[list[i]]
* Искать нужное значение лучше через `map.entries.find{ ... }`, потому что оно сразу вам вернет оба компонента
* Совсем хорошо было бы, если бы вы почитали про `SortedMap` и применили его

2016-10-28 10:06 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return "${twoDigitStr(parts[0].toInt())}.${twoDigitStr(list.indexOf(parts[1]) + 1)}.${parts[2]}"
Почему мы не проверяем год на валидность?

2016-11-01 13:29 UTC, ice-phoenix requested changes

2016-11-01 13:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = lcm(m, n) == m * n
Не лучше ли это выразить через функцию `gcd`?

2016-11-01 13:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = listOf<Int>()
Почему вы в некоторых задачах используете `var ...: List<Int>`, а в других `val ...: MutableList<Int>`? Лучше выбрать один стиль и везде придерживаться его.

2016-11-01 13:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val parse = map1.toSortedMap().entries.findLast { it.key <= number }.toString().split("=")
* `toSortedMap()` можно сделать сразу при объявлении переменной
* `findLast{ ... }` может вернуть `null`
* Вместо `toString().split("=")` лучше достать отдельно ключ/значение при помощи свойств `key / value`

2016-11-01 13:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
`StringBuilder()`

2016-11-01 13:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    println(dateStrToDigit("15 июля 2016"))
Зачем?

2016-11-01 13:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val list = listOf<String>("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Можно просто `listOf(...)`

2016-11-01 13:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if ((list.indexOf(parts[1]) == -1) || (parts[2].toInt() < 0) || (parts[0].toInt() !in 1..31)|| parts.size !=3) throw Exception()
Повторно используемые выражения лучше вытащить в отдельные переменные с говорящими именами

2016-11-01 13:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return "${oneDigitStr(parts[0].toInt())} ${list[parts[1].toInt()-1]} ${parts[2]}"
См. замечания выше

2016-11-16 09:22 UTC, ice-phoenix requested changes
Обратите внимание, что у вас не проходят некоторые тесты

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +import lesson3.task1.pow
:+1:

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = listOf<Int>()
Ап

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (parse != null) parse.toInt()
Зачем `parse.toInt()`?

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val parse = map1.keys.findLast {it <= number}
Можно искать в `entries`, чтобы сразу достать и ключ, и значение

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (parts.size != 3) throw IndexOutOfBoundsException()
Что должна делать функция при неправильном формате входной строки?

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if ((month == -1) || (year < 0) || (day !in 1..31)) throw NumberFormatException()
См. выше

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        val parts = digital.split(".")
Почему в предыдущей функции вы проверяете результат `split` на длину, а в этой нет?

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val list = phone.toMutableList()
Зачем?

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (list.filter { it !in "+0123456789-() " }.isEmpty()) return list.filter { it in "+0123456789" }.joinToString("")
Это можно заменить на `list.any / list.all`

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    return Segment(p1, p2)
Чему в итоге равны `p1` и `p2`?

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun circleByDiameter(diameter: Segment): Circle = Circle(Point((diameter.begin.x + diameter.end.x) / 2, (diameter.begin.y + diameter.end.y) / 2), diameter.end.distance(diameter.begin) / 2)
Длинные строки принято разбивать на несколько более коротких

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        a.y==b.y -> lineByPoints(halfSegment, Point(halfSegment.x,halfSegment.y+1))
Форматирование кода

2016-11-16 09:22 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        else -> {val pointBisector = Point(halfSegment.x + 1, sqr(b.y) - sqr(a.y) + sqr(b.x) - sqr(a.x) - 2 * (halfSegment.x + 1) * (a.x - b.x) / (b.y - a.y))
Форматирование кода!

2016-11-21 10:43 UTC, ice-phoenix requested changes

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        maxSide == sqrt((minSide * minSide + anotherSide * anotherSide)) -> 1
Лишние скобки вокруг законченных выражений

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val parse = map1.entries.findLast { it.key <= number }.toString().split("=")
Ключ и значение доступны как поля в объекте типа `Map.Entry`, можно без этого ужаса в виде `toString().split("=")`

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        val crossX = (other.point.x * sin2 * cos1 - point.x * sin1 * cos2 + point.y * cos1 * cos2 - other.point.y * cos2 * cos1) / (sin2 * cos1 - sin1 * cos2)
Длинные строки принято разбивать на несколько более коротких

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    if (angle >= PI / 2) return Line(halfSegment, angle - PI / 2)
Зачем данная проверка?

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    if (center == center1 && center == center2 && center1 == center2){
Форматирование кода

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    if (center == center1 && center == center2 && center1 == center2){
Зачем третья проверка?

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    if (center == center1 && center == center2 && center1 == center2){
Зачем вообще эта проверка?

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        else return "${str[column - 1]}" + "$row"
Зачем `"" + ""`?

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val row = notation[1].toString().toInt()
Для преобразования `Char -> digit` лучше использовать особенности кодирования символов цифр в кодировке `ASCII`

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val result = Square(str.indexOf(column) + 1, row)
То же самое, лучше использовать кодировку `ASCII`

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val inside = start.inside() && end.inside()
Зачем эта переменная?

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    var result =false
Форматирование кода

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val inside = start.inside() && end.inside()
Зачем эта переменная?

2016-11-21 10:43 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            if (start.column == end.column + abs(i) && start.row == end.row + abs(i)) result = true
Зачем `abs(i)`?
Зачем продолжать цикл, если `result == true`?

2016-11-23 19:54 UTC, onfound commented on src/lesson6/task1/Geometry.kt
> +    if (center == center1 && center == center2 && center1 == center2){
Извините, cлучайно забыл убрать, т.к. много у кого из группы не проходит проверку у бота данная задача.

2016-11-24 14:09 UTC, ice-phoenix requested changes

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val parse = map1.entries.findLast { it.key <= number } ?: continue
:+1:

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val list = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список лучше вынести на верхний уровень и соответствующим образом назвать

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: Exception) {
Следует ловить наиболее специфичный тип исключения, который может произойти у вас в коде

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: Exception) {
Следует ловить наиболее специфичный тип исключения, который может произойти у вас в коде

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return "${oneDigitStr(day)} ${list[month - 1]} ${year}"
Почему `oneDigitStr`???

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        val sinCosDifference = sin2 * cos1 - sin1 * cos2
Если вы используете выражение один раз, то выносить его в отдельную переменную не всегда хорошая идея

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val row = notation[1].toInt()-48
Форматирование + магические константы

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    else return result
Что будет, если подать на вход `"a1b"`?

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val result = Square(column.toInt()-96, row)
Почему `row` вы посчитали сразу, а `column` --- в месте использования?

2016-11-24 14:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        }
Это все можно проверить без цикла

2016-11-25 12:01 UTC, ice-phoenix commented
recheck all

2016-11-25 12:13 UTC, ice-phoenix requested changes

2016-11-25 12:13 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IndexOutOfBoundsException) {
После исправления этого исключения происходить не должно и эту проверку можно убрать =)

2016-11-25 12:13 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IndexOutOfBoundsException) {
См. выше

2016-11-25 12:13 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        val y2 = other.point.y
Если выражение используется один раз, то выносить его в отдельную переменную стоит не всегда. Здесь у вас почти везде очень простые выражения, и вынесение их в отдельную переменную усложняет понимание кода, а не упрощает его.

2016-11-25 12:13 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if (notation.length ==2)
Форматирование кода

2016-11-25 12:13 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    var result = Square(0,0)
Почему эту переменную нельзя объявить ниже?

2016-11-25 12:13 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val charLetterToInt = 96
Магические константы

2016-11-25 12:13 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        }
Эту проверку можно сделать вообще без цикла

2016-11-25 12:13 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        return "$sb"
Лучше через `toString()`

2016-11-26 21:11 UTC, ice-phoenix requested changes

2016-11-26 21:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var maxDiv = (n / 2)
Лишние скобки вокруг законченого выражения, коллега =)

2016-11-26 21:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = listOf<Int>()
Это замечание все еще в силе. Единый стиль вам пригодится в будущем при реальной работе над реальными проектами =)

2016-11-26 21:11 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    for (i in 0..circles.size - 2)
Форматирование кода --- пока вы не овладели сакральным пониманием того, когда можно не ставить фигурные скобки, лучше ставить их всегда =)

2016-11-26 21:11 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if (notation.length == 2 && Square(notation[0] - '`', notation[1] - '0').inside()) return Square(notation[0] - '`', notation[1] - '0')
Повторно используемое выражение лучше бы все таки вынести в переменную. И запомнить, что это следует делать самому, а не чтобы постоянно приходил Марат и говорил, что надо сделать =)

2016-11-28 10:40 UTC, ice-phoenix requested changes

2016-11-28 10:40 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[row, column])
Как будем отличать одно значение от другого?

2016-12-04 19:26 UTC, ice-phoenix commented
Закрываю PR для того, чтобы облегчить жизнь GitHub. После того, как решите следующие задания, не забудьте открыть новый PR.

2016-12-04 19:26 UTC, closed without merging