lesson 1,2,3(не полностью)
Kotlin-Polytech/KotlinAsFirst2016 pull request #142
Opened 2016-09-29 16:58 UTC by stprost

2016-09-29 17:18 UTC, mglukhikh commented
recheck all

2016-09-29 17:22 UTC, mglukhikh commented
recheck all

2016-09-30 22:43 UTC, gagarski requested changes

2016-09-30 22:43 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +    return hours*60*60+minutes*60+seconds
Однострочные функции лучше записывать, используя специальный синтаксис для этого (как вы сделали в `thirdDigit`).

2016-09-30 22:43 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +    return initial*(1+0.01*percent) *(1+0.01*percent)*(1+0.01*percent)
Однострочные функции лучше записывать, используя специальный синтаксис для этого (как вы сделали в `thirdDigit`).

2016-09-30 22:43 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        else return t1+t2+(s/2-s1-s2)/v3
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-30 22:43 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        c1=c}
Закрывающую фигурную скобку в Котлине принято ставить на новой строке.

2016-09-30 22:43 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    val x4 = (number-x3*100-x2*10-x1)/1000
Вычитание здесь не нужно. Когда вы делите целые числа, выполняется деление нацело.

2016-09-30 22:43 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if (x1+x2==x3+x4) return true
- Вы используете довольно многословный способ вычисления булевского значения.
Постарайтесь озознать (в уме или на бумаге), что 
```kotlin
if (x) true else false
```
эквивалентно
```kotlin
x
```

2016-09-30 22:43 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if ((sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1))+r1) <= r2) return true
- Вы используете довольно многословный способ вычисления булевского значения.
Постарайтесь озознать (в уме или на бумаге), что 
```kotlin
if (x) true else false
```
эквивалентно
```kotlin
x
```

2016-09-30 22:43 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int = if (n > 2) fib(n-1)+ fib(n-2)
- Рекурсивное решение напрашивается, исходя из определения чисел Фибоначчи, но попробуйте посчитать, к скольки вызовам функции `fib()` приведёт вызов `fib(10)`, `fib(40)`, `fib(55)`, сколько среди них вызовов с одинаковыми аргументами и решить задачу более оптимальным способом.

2016-09-30 22:43 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (s%n > 0 || s%m > 0) {
Почитайте про алгоритмы вычисления НОК/НОД и попробуйте решить задачу более оптимальным способом.

2016-09-30 22:43 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean {
Попробуйте решить эту задану не полным перебором, а с помощью функций, реализованных выше (подумайте о свойствах взаимно простых чисел).

2016-09-30 22:43 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var a = x - x*x*x
- Лучше изначально вычислить сумму только из одного члена ряда (`var a = x`)
- Переменным лучше давать осмысленные имена, соответствующие их назначению в коде.

2016-09-30 22:43 UTC, gagarski commented on tutorial/chapter01.adoc
> + = 1. Простые функции
- В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков. И это как раз тот случай, когда эта пробема может стать актуальной в данном проекте. Tutorial в `Kotlin-Polytech/KotlinAsFirst2016` постоянно обновляется, поэтому при создании PR могут возникнуть конфликты правок. Пожалуйста, верните файлы в каталоге `tutorial` в исходное состояние.

2016-09-30 22:45 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var a = x - x*x*x
Обратите также внимание, что для `sin` не проходит даже тест, имеющийся в проекте. По возможности, добивайтесь прохождения этих тестов перед отправкой на проверку.

2016-10-20 10:19 UTC, gagarski commented
recheck all

2016-10-20 10:39 UTC, gagarski requested changes

2016-10-20 10:39 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    return m * n / a
- Лучше `m / a * n`. Тогда вы избежите целочисленного переполнения во многих случаях. например, НОК(1000000, 10000000)
 - Вычисление НОД лучше вынести в отдельную функцию (`gcd`)

2016-10-20 10:39 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Можно ли уменьшить верхнюю границу перебора?

2016-10-20 10:39 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in n / 2 downTo 1) {
Можно ли уменьшить верхнюю границу перебора ещё сильнее, чем до половины от числа?

2016-10-20 10:39 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = lcm(m, n) == m * n
Когда вы вынесете `gcd` в отдельную функцию, лучше использовать его (опять таки, чтобы избежать проблем с целочисленным переполнением для больших чисел)

2016-10-20 10:39 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if (b != a % 10) s++
Нужен ли здесь подсчёт `s`? Можно просто завершить выполнение функции, если вы нашли различающиеся цифры.

2016-10-20 10:39 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty())
Пустой список можно не рассматривать как особый случай в данной функции. Для пустого списка ваш цикл не совершит ни одной итерации и без проверки на пустоту.

2016-10-20 10:39 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            for (j in 1..i) b *= x
Тут можно использовать `Math.pow()`, поскольку вы работаете с вещественными числами.

2016-10-27 08:40 UTC, mglukhikh commented
recheck all

2016-10-27 08:47 UTC, mglukhikh commented
Для задачи decimal из 4-го урока сообщение об ошибке ложное, случай с пустым списком цифр некорректен. Однако, остальные сообщения об ошибках справедливы

2016-10-27 09:04 UTC, belyaev-mikhail commented
recheck assignment

2016-11-02 09:21 UTC, stprost commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Если у меня дальше стоит break, и после нахождения минимального делителя цикл заканчивается, то верхняя граница никак не должна влиять на время выполнения программы.
Все равно надо исправлять?

2016-11-02 09:43 UTC, stprost commented on src/lesson3/task1/Loop.kt
> +    for (i in n / 2 downTo 1) {
Думаю, что нельзя.

2016-11-08 11:40 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
В случае с простым числом можно будет заранее вернуть его само, как минимальный делитель.

2016-11-08 11:47 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in n / 2 downTo 1) {
Можно. До квадратного корня от `n`.

2016-11-08 12:04 UTC, gagarski requested changes

2016-11-08 12:04 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    return s / 10
Здесь происходит переполнения. Избавьтесь от вычисления перевёрнутого числа, умноженного на 10.

2016-11-08 12:04 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(y) > eps) {
Протестируйте вашу реализвцию синуса на больших числах (10 * PI, 20 * PI, 100 * PI). Правильно ли она себя ведёт. Подумайте, почему, и какое свойство синуса можно использовать, чтобы это исправить.

2016-11-08 12:04 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var s = 0
См. пример.

2016-11-08 12:04 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (v.isEmpty()) return 0.0
Не нужно рассматривать пустой список, как особый случай. `a.sum()` вернёт 0.0 длч пустого списка.

2016-11-08 12:04 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty())
Не нужно рассматривать пустой список, как особый случай.

2016-11-08 12:04 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in n / 2 downTo 2) {
Корень из `n`.

2016-11-08 12:04 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        if (n % i == 0 && isPrime(i)) {
Проверять на простоту здесь неэффективно (`isPrime` в каждой итерации цикла будет перебирать делители от 2). Можно увеличивать делитель на 1, как вы и делаете и делить число на него, пока оно делится. Делители будут простыми, потому как вы в ходе цикла уже проверите делимость числа на все числа, меньшие `i`.

2016-11-27 13:29 UTC, gagarski commented
Просмотрите пожалуйста [имеющиеся замечания](https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/142/files) и исправьте их.

2016-12-19 15:24 UTC, gagarski commented
recheck all

2016-12-19 15:37 UTC, gagarski commented
По количеству решённых вами уроков и задач ваша могла бы быть "удовлетворительно", но с учётом неисправленных за долгое время замечаний вы получаете только зачёт.

2017-01-16 13:38 UTC, mglukhikh commented
recheck all

2017-03-06 21:41 UTC, closed without merging