3 lesson
Kotlin-Polytech/KotlinAsFirst2016 pull request #143
Opened 2016-09-29 18:39 UTC by Pashnik

Pn 13531/2

2016-09-30 19:15 UTC, mglukhikh commented
recheck all

2016-09-30 19:18 UTC, mglukhikh commented
recheck all

2016-09-30 22:08 UTC, gagarski requested changes

2016-09-30 22:08 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..Int.MAX_VALUE){
Зачем цикл по всем целым числам?!
Это можно переписать, используя цикл `while`

2016-09-30 22:08 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var k = 0
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-30 22:08 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var k = 0
- Поищите более оптимальные алгоритмы поиска НОК/НОД.

2016-09-30 22:08 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in n downTo 1) {
- Почему вы ищете минимальный делитель, начиная с наибольших чисел?

2016-09-30 22:08 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in n downTo 1){
Перебор можно завершить при нахождении первого делителя.

2016-09-30 22:11 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        else if (age % 10 in 2..4) return "$age года"
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-30 22:11 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +    return hours*3600 + minutes * 60 + seconds
Такие однострочные функции лучше оформлять с `=` (как `discriminant` или `sqr`)

2016-09-30 22:11 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +     numb = numb / 10
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-10-02 18:01 UTC, gagarski requested changes

2016-10-02 18:01 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +        grad * 0.0174533 + min * 0.0002908883333348684 + sec * 4.848138888912097615e-6
Используйте константу `Math.PI`, а не вычисленные собственноручно "магические числа". У ваших чисел не хватает точности.

2016-10-02 18:04 UTC, gagarski requested changes

2016-10-02 18:04 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var k = 0
Почитайте про более эффективные алгоритмы поиска НОД/НОК, чем полный перебор.

2016-10-06 12:57 UTC, gagarski requested changes

2016-10-06 12:57 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (m1 != n1) {
Лучше вынести вычисление НОД в отдельную функцию.

2016-10-06 12:57 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    return (m * n) / m1
Лучше сначала поделить на `m1`, а затем умножить на `n`. Так вы избежите целочисленного переполнения в некоторых случаях (например, НОК(1000000, 1000000))

2016-10-06 12:57 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..Math.min(m, n)) {
Используйте функции, определённые ранее в этом уроке вместо полного перебора.

2016-10-06 12:57 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var A = x
- Переменным лучше давать осмысленные имена, соответствующие их назначению в коде.
- В Котлине принято называть переменные с маленькой буквы.

2016-10-06 12:57 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +            while (m > 0) {
Зачем вложенный цикл? Можно просто сверять соседние цифры и если они отличаются, то возвращать `true`

2016-10-06 12:57 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        while (c > m) {
- Лучше делить число на 10 для подсчёта количества цифр (так вы избежите переполнения, например, для `Int.MAX_VALUE`)
 - Более того, у вас уже реализована функция `digitNumber`

2016-10-06 12:58 UTC, gagarski requested changes

2016-10-06 12:58 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var A = x
Протестируйте вашу реализацию синуса на больших числах (20 * PI, 200 * PI, 2000 * PI), постарайтесь понять проблему и подумать, какое свойство синуса можно использовать чтобы её решить.

2016-10-24 14:10 UTC, gagarski requested changes
Перед тем, как приступать к следующим задачам исправьте замечания и ошибки в уже сделанных.

2016-10-24 14:10 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Можно ли уменьшить верхнюю границу перебора?

2016-10-24 14:10 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in n - 1 downTo 1) {
Можно ли уменьшить верхнюю границу перебора?

2016-10-24 14:10 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if (i % Math.sqrt(i.toDouble()) == 0.0) {
Избегайте точного сравнения `Double` на равенство.

2016-10-24 14:10 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Нет необходимости рассматривать пустой список как особый случай. Если список пуст, то вы просто не попадёте в ваш цикл `for`.

2016-10-24 14:10 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (p.isEmpty()) return 0.0
Нет необходимости рассматривать пустой список как особый случай. Если список пуст, то вы просто не попадёте в ваш цикл `for`.

2016-10-24 14:10 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Нет необходимости рассматривать пустой список как особый случай. Если список пуст, то вы просто не попадёте в ваш цикл `for`.

2016-10-24 14:10 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        sum += digits[newSize - 1] * Math.pow(base.toDouble(), i.toDouble()).toInt()
Не стоит без необходимости переходить к числам с плавающей точкой в целочисленных задачах. Реализуйте `pow`  для целых чисел, либо вычисляйте множитель со степенью внутри вашего цикла.

2016-10-26 10:17 UTC, gagarski commented
recheck all

2016-10-26 10:18 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    return list.sorted()
А зачем `sorted()`? Вы ведь и так добавляете числа по возрастанию.

2016-10-26 10:31 UTC, gagarski approved these changes

2016-10-26 10:31 UTC, closed without merging