Решена задача про секунды
Kotlin-Polytech/KotlinAsFirst2016 pull request #146
Opened 2016-09-29 21:06 UTC by MalyshevPavel

2016-09-30 11:07 UTC, ice-phoenix requested changes

2016-09-30 11:07 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = abs((hoursDepart * 60) + minutesDepart - ((hoursArrive * 60) + minutesArrive))
Зачем вызов `abs`?

2016-09-30 11:07 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ThirdYear
* Данное выражение можно выразить проще, используя элементарные математические преобразования

2016-09-30 11:07 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad + ((min + sec/60)/60)) * Math.PI/ 180
Выражение `Int / Int` возвращает `Int`. Для того, чтобы деление выполнялось в числах с плавающей запятой, один из операндов должен быть `Double`.

2016-09-30 11:07 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = hours*3600+minutes*60+seconds
Отформатируйте код при помощи IntelliJ IDEA и в дальнейшем старайтесь придерживаться похожего и (что самое главное) единообразного стиля кодирования

2016-09-30 19:04 UTC, MalyshevPavel commented on src/lesson1/task1/Simple.kt
> +    return ThirdYear
Здравствуйте, можете подсказать, как исправить ошибку?
![2016-09-30 22 00 17](https://cloud.githubusercontent.com/assets/22070455/19003510/c9181b76-8759-11e6-8002-2017b1907e42.png)

2016-10-12 09:42 UTC, mglukhikh commented
Автору PR: вы сильно отстаёте от графика. Вам следует исправить приведённые в этом PR замечания и перейти к решению задач 2-го и 3-го урока, в противном случае вы рискуете получить неудовлетворительную оценку за октябрь месяц.

2016-10-12 09:45 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return ThirdYear
У вас какая-то неправильность в настройке проекта. Лучше всего было бы посмотреть на ошибку лично на занятиях (можете показать проблему любому из преподавателей). Можно попробовать также закрыть проект, удалить в нём папку .idea и открыть заново (в ответ на предложение заимпортировать файл pom.xml -- соглашайтесь).

2016-10-28 12:33 UTC, ice-phoenix commented
Вы не исправили ни одного замечания к первому уроку. Задачи из 2 и 3 урока *не будут учитываться*, пока вы не исправите первый урок.

2016-11-02 15:36 UTC, ice-phoenix requested changes

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val First = number % 10
Для именования переменных в Котлин принят `camelCase`

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +import lesson4.task1.abs
Зачем?

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((age % 10 == 0) || (age / 10 == 1) || (age / 10 == 11) || (age % 10 in 5..9)) return "$age лет"
Всю эту функцию лучше оформить как один `when`

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val S1 = v1 * t1
`camelCase`

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +         if (((kingX == rookX) || (kingY == rookY)) && (minusX != minusY)) return 1
Факты того, атакует ли ладья или слон короля, следует вынести в отдельные переменные, и потом проверять все по ним

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return when{
Можно просто `return a + b == c + d`

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (Math.sqrt(sqr(Math.abs(x2 - x1)) + sqr(Math.abs(y2 - y1))) + r1 > r2) return false
Выражение `if (cond) return false else return true` можно заменить на `return !cond`

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n % d == 0) return d
Зачем вам переменная `d`, если у вас есть переменная `i`?

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n) {
Нет ли более точной верхней границы для возможных делителей числа `n`?

2016-11-02 15:36 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n % d == 0) return d
См. замечания выше

2016-11-02 15:36 UTC, ice-phoenix commented
recheck all

2016-11-22 16:12 UTC, ice-phoenix commented
recheck all

2016-11-22 16:13 UTC, ice-phoenix commented
recheck all

2016-11-22 16:14 UTC, ice-phoenix commented
recheck all

2016-11-23 11:18 UTC, mglukhikh commented
Вы очень сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта, иначе в конце семестра это может кончиться вашим отчислением

2016-11-24 18:55 UTC, MalyshevPavel commented on src/lesson2/task1/IfElse.kt
> +import lesson4.task1.abs
Модуль не работал без этого

2016-11-24 20:01 UTC, MalyshevPavel commented on src/lesson3/task1/Loop.kt
> +        if (n % d == 0) return d
Чтобы иметь возможность увеличивать счетчик ( d++ ), так как i объявлена внутри цикла

2016-11-24 20:02 UTC, MalyshevPavel commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n) {
Исправил

2016-11-24 20:02 UTC, MalyshevPavel commented on src/lesson2/task2/Logical.kt
> +    if (Math.sqrt(sqr(Math.abs(x2 - x1)) + sqr(Math.abs(y2 - y1))) + r1 > r2) return false
Спасибо, изменил

2016-11-24 20:02 UTC, MalyshevPavel commented on src/lesson2/task2/Logical.kt
> +    return when{
Изменил

2016-11-24 20:03 UTC, MalyshevPavel commented on src/lesson2/task1/IfElse.kt
> +    if ((age % 10 == 0) || (age / 10 == 1) || (age / 10 == 11) || (age % 10 in 5..9)) return "$age лет"
Изменил

2016-11-24 20:04 UTC, MalyshevPavel commented on src/lesson2/task1/IfElse.kt
> +    val S1 = v1 * t1
Обозначил все переменные с строчной буквы.

2016-11-24 20:05 UTC, MalyshevPavel commented on src/lesson1/task1/Simple.kt
> +    val First = number % 10
Исправил

2016-11-24 20:10 UTC, MalyshevPavel commented on src/lesson3/task1/Loop.kt
> +        if (n % d == 0) return d
Исправил

2016-11-24 20:33 UTC, MalyshevPavel commented on src/lesson2/task1/IfElse.kt
> +         if (((kingX == rookX) || (kingY == rookY)) && (minusX != minusY)) return 1
Не совсем понял как реализовать

2016-11-27 11:52 UTC, ice-phoenix requested changes
Очень много замечаний, плюс во многих местах вы (как мне кажется) не до конца понимаете, что же вы делаете. Советую разобраться, возможно, с помощью преподавателя.

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad + ((min + sec/60.0)/60.0)) * Math.PI/ 180
Форматирование кода

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(sqr(x2-x1) + sqr(y2-y1))
Форматирование кода

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = (hoursArrive * 60) + minutesArrive - ((hoursDepart * 60) + minutesDepart)
Длинная строка

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val new = first * 100 + second * 10 + third
Заводить отдельную переменную, чтобы сразу ее вернуть, --- это совсем не упрощает понимание вашего кода

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +import lesson4.task1.abs
Покажите, пожалуйста, где в этом модуле вы используете функцию `abs` из четвертого урока

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (((age % 10 == 0) || (age / 10 == 1) || (age / 10 == 11) || (age % 10 in 5..9))) -> "$age лет"
Лишние скобки вокруг законченных выражений

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val a = (age - 1) % 10
Зачем вы делаете "минус один"???

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +         if (((kingX == rookX) || (kingY == rookY)) && (minusX != minusY)) return 1
Обсудите это с преподавателем на занятиях

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        cos=(a*a+b*b-c*c)/(2*a*b)
Что стало с форматированием кода? Если вы не можете пока еще форматировать код самостоятельно, хотя бы используйте средства автоформатирования, встроенные в Идею.

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((cos>=1) || (cos<=-1)) return -1
Данное выражение лучше оформить как `when`

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var cos = 0.0
Лучше как
```
val cos =
    if (...) ...
    else if (...) ...
    ...
```

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +
Зачем все эти пустые строки?

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((b-c)<=(d-a)) return b-c
Форматирование кода

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((c>=a) && (c<=b)) && (d<=b))
Данное выражение лучше оформить как `when`

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((a>=c) && (c<=d)) && (b<=d))
Лишние скобки вокруг законченных выражений

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return !(Math.sqrt(sqr(Math.abs(x2 - x1)) + sqr(Math.abs(y2 - y1))) + r1 > r2)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        return fib(n-1)+fib(n-2)
Фор-ма-ти-ро-ва-ни-е кода

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n-2) {
Нет ли еще более точной границы сверху на возможные делители числа?

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var d = n - 1
См. замечание выше

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return true
Решите эту задачу через `GCD`

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        {if ((m % i == 0) && (n % i == 0))
Форматирование кода

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (((i*i)>=m) && ((i*i)<=n)) return true
Форматирование кода + данную задачу следует решить без единого цикла

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    (0..v.size - 1).forEach { i -> a += sqr(v[i]) }
Менять внешнюю переменную внутри лямбды не очень хорошо. Тут можно обойтись старым добрым циклом.

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty() == true)
Зачем эта проверка? К тому же, достаточно просто `if (list.isEmpty())`, если бы эта проверка была нужна.

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            list[i] = element - average
Можно просто `list[i] = list[i] - a`

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        newString += when (parts[1]) {
адок еинаворитамроФ

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var newString = ""
Список строк или `StringBuilder`

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            else newString = day.toString() + "."
`String.padStart(...)`

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            newString += parts[2].toString()
См. замечание выше

2016-11-27 11:52 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            newString += parts[2].toString()
Зачем тут `toString()`???

2016-12-18 22:21 UTC, ice-phoenix commented
recheck all

2016-12-18 22:26 UTC, ice-phoenix commented
По статистике решенных задач в настоящее время у вас нет даже зачета.

2016-12-19 09:02 UTC, ice-phoenix requested changes

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val a = age % 10
Переменную мы завели, но практически не используем. Не очень хорошо.

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((a * a + b * b > c * c) && (c >= a) && (c >= b))
Избыточные условия + слишком сложный способ решения

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        !(((b >= c) && (b <= d)) || ((c >= a) && (c <= b)) || ((d >= a) && (d <= b)) || ((a >= c) && (a <= d))) -> -1
Избыточные условия + форматирование

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n - 2) {
Почему внезапно `for`???

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +                return false
Это следовало реализовать через поиск НОД

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    else
Вместо копирования кода можно было просто поменять переменные местами, если вам обязательно надо, чтобы `m` было больше `n`

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (((i * i) >= m) && ((i * i) <= n)) return true
Эту задачу следует решить без единого цикла

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        a /=10
Форматирование кода

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty() == true) return 0.0
Зачем переменную типа `Boolean` сравнивать на `==` с `true`???

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val average = list.sum() / list.size
А если список пустой?

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        }
Форматирование кода

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in str.length - 1 downTo 0) {
Лучше цикл в `foreach` стиле

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var stringBuilder = ""
Не имя переменной `StringBuilder`, а использовать класс `StringBuilder`

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                else stringBuilder = day.toString() + "."
`String.padStart(...)`

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    else return ""
Поток управления функции следовало построить не так

2016-12-19 09:02 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } else return ""
См. замечания выше

2016-12-19 09:04 UTC, ice-phoenix commented
При условии исправления всех замечаний и успешного прохождения тестирования мы, возможно, рассмотрим вопрос об "Удовлетворительно" автоматом.

2017-01-01 23:19 UTC, MalyshevPavel commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n - 2) {
У меня до этого тоже был for, просто границы менялись

2017-01-02 22:31 UTC, MalyshevPavel commented
Здравствуйте, можете подсказать как исправить проблему?
![2017-01-03 1 30 28](https://cloud.githubusercontent.com/assets/22070455/21596992/403bf18e-d154-11e6-82f4-ccf43df1f18a.png)

2017-01-13 10:15 UTC, ice-phoenix commented
Сходите в `pom.xml` и поменяйте там версии `junit` с M2 на M3 внутри тега `<properties>`

2017-01-13 20:24 UTC, MalyshevPavel commented
Спасибо, помогло. :)
Еще хотел сказать, что я успешно прошел тестирование

2017-01-16 08:53 UTC, ice-phoenix requested changes

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        if ((Math.abs(cosa) < 0.00001) || (Math.abs(cosb) < 0.00001) || (Math.abs(cosc) < 0.00001)) return 1 else
Данное выражение лучше оформить как `when`

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            !(((b >= c) && (b <= d)) || ((c >= a) && (c <= b)) || ((d >= a) && (d <= b)) || ((a >= c) && (a <= d))) -> -1
Это условие можно записать проще

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n - 2) {
Если вы итерируетесь по `d`, зачем вам цикл `for` по `i`???

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if ((m != 0) and (n != 0)) {
`and` ==> `&&`

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (gcd(m, n) == 1) return true
Выражение `if (cond) return true else return false` можно заменить на `return cond`

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return false
Эту задачу нужно решить без цикла

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val average = list.sum() / list.size
Все еще актуально

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Зачем эта проверка?

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val lettersToInt = mapOf<Char, Int>('0' to 0, '1' to 1, '2' to 2, '3' to 3, '4' to 4, '5' to 5, '6' to 6, '7' to 7, '8' to 8, '9' to 9, 'a' to 10,
Это преобразование можно сделать намного проще, если воспользоваться свойством кодировки ASCII

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список можно вынести на уровень выше, раз вы его используете в двух местах

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (maxHigh < parts[i - 1].toInt())
Повторно используемые выражения лучше вынести в отдельные переменные

2017-01-16 08:53 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    while (i < parts.size - 1 && parts[i] != parts[i + 1]) {
Как работает этот код?

2017-01-16 11:45 UTC, MalyshevPavel commented
recheck all

2017-01-16 11:47 UTC, ice-phoenix commented
recheck all

2017-01-16 11:51 UTC, ice-phoenix commented
recheck all

2017-07-26 18:23 UTC, closed without merging