2 урок
Kotlin-Polytech/KotlinAsFirst2016 pull request #147
Opened 2016-09-30 01:13 UTC by copchenka

2016-09-30 10:37 UTC, mglukhikh commented
Ваш проект не компилируется. Пожалуйста, исправьте ошибки, и впредь обязательно запускайте тесты в обучающем проекте перед отправкой кода нам.

2016-09-30 14:44 UTC, mglukhikh requested changes
Ошибка в одной из задач плюс замечания по форматированию кода, исправляйте.

2016-09-30 14:44 UTC, mglukhikh commented on IfElse.kt
> +
Этот файл, лежащий в корневой директории проекта, следует удалить из репозитория

2016-09-30 14:44 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Для age = 11 ответ получается неверным. См. сообщение бота

2016-09-30 14:44 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        if (s <= s1 + s2) return t1 + (s - s1) / v2 else
`if..else if` записывается на одном уровне:

```
if (...) return ...
else if (...) return ...
else if ...
```

2016-09-30 14:44 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX == rookX) || (kingY == rookY))  r += 1
Нарушены правила форматирования кода. Используйте Ctrl+Alt+L, чтобы его поправить, и в дальнейшем старайтесь соблюдать правила форматирования. В частности, все операторы блока должны находиться на одном уровне; знаки операций следует отделять от аргументов пробелами.

2016-09-30 14:44 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    ((a <= c) && (d <= b)) -> d - c
Здесь тоже нарушены правила форматирования. После открывающей фигурной скобки на той же строке никогда ничего не пишут, это некрасиво выглядит и плохо читается.

2016-10-03 16:01 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +return (x1==x2)||(y1==y2)||(x1+y1==x2+y2)||(x1-y1==x2-y2)
Нарушены правила форматирования. Отсутствуют пробелы рядом со знаками операций

2016-10-03 16:01 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return Math.sqrt(a+b)+r1<=r2
Отсутствуют пробелы рядом со знаками операций

2016-10-03 16:03 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    val c=number / 1000
Вы пишете
```
    val b = (number / 10) % 10 // с пробелами
    // А потом
    val c=number / 1000 // без пробелов
```

Старайтесь писать одинаково всюду. Лучше -- с пробелами, чем без. IDEA умеет форматировать код автоматически: Ctrl+Alt+L

2016-10-03 16:04 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    ((b < c) || (d < a)) -> -1
После фигурной скобки -- отступ ещё в 4 символа
```
fun segmentLength(...): Int {
    return when {
        b < c || d < a -> -1
        ...
    }
}
```

2016-10-03 16:07 UTC, mglukhikh commented
У вас остаётся ошибка в задаче ageDescription и, кроме того, довольно многочисленные проблемы с форматированием кода. Советую для их исправления применить автоформатирование IDEA: Ctrl+Alt+L в обоих файлах из 2-го урока, посмотреть, что изменится, и в дальнейшем стараться придерживаться такого же стиля. Пожалуйста, исправьте имеющиеся замечания, прежде чем решать новые задачи.

2016-10-10 20:02 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if ((r>=a)and ((s>=b)||(s>=c))) return true
Лучше вместо неленивого `and` использовать ленивое `&&`. И напоминаю вам ещё раз -- пожалуйста, будьте аккуратнее при расстановке пробелов и / или используйте Ctrl+Alt+L.

2016-10-28 14:33 UTC, mglukhikh commented
recheck all

2016-10-28 14:37 UTC, mglukhikh requested changes
Я не буду проверять третий урок, пока не будут исправлены замечания к первому и второму уроку.

2016-10-28 14:37 UTC, mglukhikh commented on IfElse.kt
> +
Ещё раз прошу удалить из репозитория этот файл.

2016-10-28 14:37 UTC, mglukhikh commented on Loop.kt
> +@file:Suppress("UNUSED_PARAMETER")
Этот файл в корневой директории тоже не нужен

2016-10-28 14:37 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Для age = 11 ответ по-прежнему неверный

2016-10-28 14:37 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    }
Нарушены правила форматирования кода

2016-10-28 14:37 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX == rookX) || (kingY == rookY))  r += 1
И здесь они по-прежнему нарушены

2016-10-28 14:37 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        else -> b - c
И здесь они тоже нарушены

2016-10-28 14:37 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    val c=number / 1000
По-прежнему бардак с пробелами

2016-10-28 14:37 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +return (x1==x2)||(y1==y2)||(x1+y1==x2+y2)||(x1-y1==x2-y2)
По-прежнему нарушены правила форматирования

2016-10-28 14:37 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return Math.sqrt(a+b)+r1<=r2
По-прежнему нарушены правила форматирования

2016-10-28 14:37 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if ((r>=a)and ((s>=b)||(s>=c))) return true
По-прежнему нарушены правила форматирования. Используйте ленивое `&&`

2016-10-28 20:49 UTC, copchenka commented on IfElse.kt
> +
подскажите пожалуйста,как его удалить?

2016-11-02 12:45 UTC, mglukhikh requested changes
Оставшиеся замечания к первым двум урокам. Главное, что нужно сделать -- убрать следы Merge Conflict

2016-11-02 12:45 UTC, mglukhikh commented on IfElse.kt
> +
Выбрав его в окне проекта (Alt+1) и нажав кнопку DEL. А потом выполнив Commit & Push

2016-11-02 12:45 UTC, mglukhikh commented on Loop.kt
> +@file:Suppress("UNUSED_PARAMETER")
Удаляется аналогично предыдущему

2016-11-02 12:45 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +>>>>>>> origin/master
Вижу следы неудачно выполненного Merge. Поправьте эту функцию, пожалуйста, иначе проект не компилируется

2016-11-02 12:45 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +                   }
Поехало форматирование

2016-11-02 12:45 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +>>>>>>> origin/master
Здесь тоже следы неудачного Merge, и их тоже нужно убрать

2016-11-02 12:45 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +return ( x1 == x2 ) || ( y1==y2 ) || ( x1+y1 == x2+y2 ) || ( x1-y1 == x2-y2 )
Форматирование

2016-11-02 12:45 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else if ( ( r >= c ) and ( ( s >= b ) || ( s >= a ) ) ) return true
Лучше вместо `and` использовать ленивый `&&`

2016-11-09 11:32 UTC, mglukhikh requested changes
Исправьте, пожалуйста, ошибки компиляции. Убедитесь, что в учебном проекте запускаются тесты

2016-11-09 11:32 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +<<<<<<< HEAD
У вас в файле следы Merge Conflicts. Естественно, их следует удалить из файла, иначе проект компилироваться не будет

2016-11-09 11:32 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +<<<<<<< HEAD
Удалите следы Merge Conflicts

2016-11-15 10:06 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return
`This function must return a value of type Double`. А вы пытаетесь не вернуть ничего, из-за этого проект не компилируется. Повторно прошу: исправьте ошибки компиляции в проекте. Убедитесь, что они исправлены все -- для этого достаточно запустить в проекте хотя бы один тест (при наличии ошибок компиляции вам не удастся это сделать).

2016-11-25 19:43 UTC, mglukhikh commented
Это здорово, что вы сделали столько уроков, но замечания к первым двум вы так и не исправили. См. вкладку Files Changed: https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/147/files

2016-11-30 12:35 UTC, mglukhikh commented
recheck all

2016-11-30 12:37 UTC, mglukhikh commented
recheck all

2016-11-30 12:47 UTC, mglukhikh requested changes
`ageDescription` и `digitNumber` не работают, плюс есть замечания по коду. Но спасибо за предыдущие исправления.

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else  return "$age лет"
На примере `111` ваша функция по-прежнему работает неверно

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +return (x1 == x2) || (y1 == y2) || (x1 + y1 == x2 + y2) || (x1 - y1 == x2 -y2)
Форматирование

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            a = i
Здесь можно сразу же делать `return i`. И тогда проверка `i < a` будет не нужна

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (isPrime(n) == true) return n
Просто `isPrime(n)`, сравнение на равенство с `true` избыточно

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun mean(list: List<Double>): Double = if (list.isEmpty()) 0.0 else list.sum() / list.size.toDouble()
`toDouble()` здесь избыточен

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        for (element in p) {
Лучше `for ((i, element) in p.withIndex()) { ... }` и не нужно вручную увеличивать `i`

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            "декабря" -> 12
Здесь и в следующей задаче лучше использовать список названий месяцев и обращаться к нему по индексу или использовать `indexOf`. Иначе у вас дважды повторяется один и тот же код.

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val littleReg = str.toLowerCase().split(" ")
Лучше не `littleReg`, а `lowerCase`. По английски нижний регистр называется так.

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val parth = description.split("; ", " ")
`part`

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        return (Line(s.begin, Math.abs(anglee))) else return (Line(s.begin, -Math.abs(anglee)))
Ветку `else` вынести на отдельные строчки

2016-11-30 12:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    while (n1 > 0) {
Для отрицательных чисел функция работает неправильно

2016-12-06 11:40 UTC, mglukhikh commented
Пока большая часть замечаний из последнего ревью в силе

2016-12-18 17:48 UTC, mglukhikh commented
recheck all

2016-12-18 17:51 UTC, mglukhikh commented
recheck all

2016-12-18 18:10 UTC, mglukhikh requested changes
Посмотрел последние исправления, написал немножко замечаний.

2016-12-18 18:10 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +   else ->  "$age лет"
Поправьте форматирование

2016-12-18 18:10 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val parth = description.split("; ", " ")
Исправьте название переменной, пожалуйста. Нет такого английского слова `parth`. Либо `part`, либо `parts`, либо ещё как-нибудь

2016-12-18 18:10 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    var anglee = 0.0
Угол по английски называется `angle`. Кроме этого, можно было сразу присвоить ему значение из следующей строчки и объявить как `val`

2016-12-18 18:10 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    anglee = Math.atan((s.begin.y - s.end.y) / (s.begin.x - s.end.x))
Здесь лучше использовать `Math.atan2`. В противном случае вы можете иметь странные эффекты при нулевом или близком к нулю знаменателю.

2016-12-18 18:21 UTC, copchenka commented
Исправлю)


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: Mikhail Glukhikh <notifications@github.com> Дата: 18.12.2016  21:10  (GMT+03:00) Кому: Kotlin-Polytech/KotlinAsFirst2016 <KotlinAsFirst2016@noreply.github.com> Копия: copchenka <mandragora2319@mail.ru>, State change <state_change@noreply.github.com> Тема: Re: [Kotlin-Polytech/KotlinAsFirst2016] 2 урок (#147) 
@mglukhikh requested changes on this pull request.

Посмотрел последние исправления, написал немножко замечаний.

In src/lesson2/task1/IfElse.kt:
> @@ -33,7 +33,11 @@ fun minBiRoot(a: Double, b: Double, c: Double): Double {
  * Мой возраст. Для заданного 0 < n < 200, рассматриваемого как возраст человека,
  * вернуть строку вида: «21 год», «32 года», «12 лет».
  */
-fun ageDescription(age: Int): String = TODO()
+fun ageDescription(age: Int): String = when {
+    age % 10 == 1 && age / 10 != 1 && age / 10 != 11 -> "$age год"
+    age % 10 in 2..4 && age / 10 != 1 && age /10 != 11 -> "$age года"
+   else ->  "$age лет"

Поправьте форматирование



In src/lesson5/task1/Parse.kt:
> @@ -142,7 +196,26 @@ fun firstDuplicateIndex(str: String): Int = TODO()
  * или пустую строку при нарушении формата строки.
  * Все цены должны быть положительными
  */
-fun mostExpensive(description: String): String = TODO()
+fun mostExpensive(description: String): String {
+    var result = ""
+    val parth = description.split("; ", " ")

Исправьте название переменной, пожалуйста. Нет такого английского слова parth. Либо part, либо parts, либо ещё как-нибудь



In src/lesson6/task1/Geometry.kt:
> @@ -105,22 +124,32 @@ data class Line(val point: Point, val angle: Double) {
  *
  * Построить прямую по отрезку
  */
-fun lineBySegment(s: Segment): Line = TODO()
+fun lineBySegment(s: Segment): Line {
+    var anglee = 0.0

Угол по английски называется angle. Кроме этого, можно было сразу присвоить ему значение из следующей строчки и объявить как val



In src/lesson6/task1/Geometry.kt:
> @@ -105,22 +124,32 @@ data class Line(val point: Point, val angle: Double) {
  *
  * Построить прямую по отрезку
  */
-fun lineBySegment(s: Segment): Line = TODO()
+fun lineBySegment(s: Segment): Line {
+    var anglee = 0.0
+    anglee = Math.atan((s.begin.y - s.end.y) / (s.begin.x - s.end.x))

Здесь лучше использовать Math.atan2. В противном случае вы можете иметь странные эффекты при нулевом или близком к нулю знаменателю.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Kotlin-Polytech/KotlinAsFirst2016","title":"Kotlin-Polytech/KotlinAsFirst2016","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Kotlin-Polytech/KotlinAsFirst2016"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mglukhikh requested changes on #147"}],"action":{"name":"View Pull Request","url":"https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/147#pullrequestreview-13468976"}}}

2016-12-19 08:20 UTC, mglukhikh commented
Переименование в IDEA нужно выполнять с помощью комбинации Shift+F6, тогда всё будет выполнено корректно. Вы же, видимо, всё делали вручную, в результате минимум в одном месте осталось старое имя, и получилась ошибка компиляции.

2016-12-19 08:20 UTC, mglukhikh commented
А на "зачёт" у вас пока не нарабатывается ввиду некоторых печальных обстоятельств. Подойдите сегодня к преподавателям на занятии, вам объяснят ситуацию.

2016-12-19 21:20 UTC, mglukhikh commented
По итогам ваших успехов на упражнениях таки поставлен "зачёт".

2016-12-19 21:20 UTC, closed without merging