Сделала Lesson 1 и Lesson2.
Kotlin-Polytech/KotlinAsFirst2016 pull request #148
Opened 2016-09-30 10:26 UTC by maria-sabo

Vottak.

2016-09-30 10:28 UTC, maria-sabo commented
recheck all

2016-09-30 10:38 UTC, mglukhikh commented
recheck all

2016-09-30 11:00 UTC, mglukhikh requested changes
Две ошибки во втором уроке + многочисленные замечания по коду. Вносите исправления, пожалуйста

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    val answer : Int = h * 3600 + m * 60 + s
Такой код избыточен. Достаточно написать

```
fun seconds(...): Int = h * 3600 + ...
```

без всяких переменных

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return answer
Аналогично

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return answer
Аналогично

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(sqr(x2-x1)+ sqr(y2-y1))
Беспорядок с пробелами. Следует либо ставить пробелы вокруг знаков операций, либо этого не делать. Можете использовать Ctrl+Alt+L в IDEA для автоформатирования

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = hoursArrive * 60 + minutesArrive - hoursDepart * 60 - minutesDepart
Слишком длинная строка, сделайте перенос после знака равно

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
Избыточный код

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
Избыточный код

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Данная функция содержит фактические ошибки (см. пример бота). Пожалуйста, добавьте в тестовую функцию дополнительную проверку на ситуацию, приведённую ботом

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Данная функция также содержит фактические ошибки (см. пример бота).

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        return 1
Вы по нескольку раз проверяете одни и те же условия. Можно ли этого избежать?

2016-09-30 11:00 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +}
Эквивалентно `return a + b == c + d`

2016-09-30 11:00 UTC, maria-sabo commented
Почему этот коммит не проверяется https://github.com/Kotlin-Polytech/KotlinAsFirst2016/commit/5d2ff63d6bf5ffbb628d011fe59fb65205648b6f?

2016-09-30 11:02 UTC, mglukhikh commented
Ну вот видите, тут же проверился. Автоматика :) Решение работает неверно для отрицательных чисел, подумайте над этим

2016-09-30 11:38 UTC, mglukhikh commented
Ага, задача из 3-го урока решена верно

2016-10-03 16:35 UTC, mglukhikh commented
recheck all

2016-10-04 09:54 UTC, mglukhikh requested changes
Кое-что вы поправили, но многие замечания из предыдущего Review по-прежнему в силе.

2016-10-04 09:54 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Да, решение верное, подтверждаю

2016-10-04 09:54 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Стало лучше, хотя условия всё равно проверяются по два раза. Можно добиться однократной их проверки.

2016-10-27 12:24 UTC, mglukhikh commented
recheck all

2016-10-27 12:25 UTC, mglukhikh commented
recheck all

2016-10-28 07:15 UTC, mglukhikh requested changes
Вы не исправили многие старые замечания, пожалуйста, относитесь к этому внимательнее. Написал также замечаний по новому коду. Пожалуйста, исправьте все замечания до того, как начнёте решать новые задачи

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    val answer : Int = h * 3600 + m * 60 + s
Это замечание всё ещё в силе

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return answer
И это тоже

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return answer
И это тоже

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(sqr(x2-x1)+ sqr(y2-y1))
И это тоже

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
И это тоже

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = hoursArrive * 60 + minutesArrive - hoursDepart * 60 - minutesDepart
И это тоже

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
И это тоже

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Функция по-прежнему содержит фактические ошибки

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Замечание по-прежнему в силе

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +}
Раз уж вы написали функцию `nod`, гораздо эффективнее использовать её для расчёта `lcm`

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    else return false
`if (x) return true else return false` эквивалентно `return x`. А

```
fun foo(...): Boolean {
    return x
}
```

эквивалентно `fun foo(...): Boolean = x`

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +   else return false
`if (x) return true else return false` эквивалентно ...

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun nod(m: Int, n: Int): Int {
Более правильное название для этой функции -- gcd. Для переименования функции, вы можете использовать комбинацию Shift+F6 в IDEA.

Эта функция много раз вызывает сама себя в процессе выполнения. Чтобы избежать переполнения стека, напишите впереди функции `tailrec`:

```
tailrec fun gcd(m: Int, n: Int): Boolean {
    ...
}
```

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (n < m)
Здесь лучше написать `else` вместо `if (n < m)`. К этому моменту, условие `n < m` уже абсолютно точно верно.

2016-10-28 07:15 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    else return 0
А эта ветка вообще не нужна -- сюда функция никогда не попадает.

2016-10-28 07:16 UTC, mglukhikh commented
Все активные замечания можно посмотреть на вкладке Files Changed.

2016-11-02 12:10 UTC, mglukhikh commented
recheck all

2016-11-02 12:17 UTC, mglukhikh requested changes
Существенную часть замечаний вы исправили, но не все. Одна функция `timeForHalfWay` по-прежнему написана неверно (не проходят тесты). Закончите исправление замечаний, пожалуйста. Все их можно просмотреть на вкладке Files Changed.

2016-11-02 12:17 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(sqr(x2-x1)+ sqr(y2-y1))
Поправьте здесь форматирование, наконец.

2016-11-02 12:17 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Замечание по-прежнему в силе

2016-11-02 12:17 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    //else return false
Не нужно оставлять в коде такие закомментированные фрагменты

2016-11-02 12:17 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +        else return false
if (x) return true else return false

2016-11-02 12:17 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +}
Повторно: раз уж вы написали функцию `nod`, гораздо эффективнее использовать её для расчёта `lcm`

2016-11-02 12:17 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    else return gcd(m-n, n)
Форматирование здесь должно быть единообразным: либо

```
if (n > m) return ...
else return ...
```

либо

```
if (n > m)
    return ...
else
    return ...
```

Либо то же самое с фигурными скобками. У вас же смешанный вариант, что нехорошо

2016-11-02 12:17 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Функция по-прежнему содержит фактические ошибки

2016-11-15 10:43 UTC, mglukhikh commented
Вынужден повторно обратить ваше внимание на имеющиеся замечания. Смотрите вкладку Files Changed и исправляйте их.

2016-11-15 10:45 UTC, mglukhikh commented
Решения из задач 4-го урока я посмотрю позже, когда вы закончите с исправлениями замечаний к первым трём.

2016-11-22 16:17 UTC, mglukhikh commented
Замечания с вкладки Files Changed по-прежнему в силе. Если вы их не понимаете, задайте вопрос мне здесь, или преподавателю на упражнениях

2016-11-24 20:06 UTC, maria-sabo commented
Я вроде бы наконец-то все исправила! Вы проверите мой 4 урок?

2016-11-25 07:07 UTC, mglukhikh commented
Спасибо! Да, сегодня вечером посмотрю уроки 4-5.

2016-11-25 07:07 UTC, mglukhikh commented
recheck all

2016-11-25 07:08 UTC, mglukhikh commented
Отмечу, что две задачи из уроков 4-5 решены неверно, судя по итогам тестирования. Можете пока посмотреть на них, если хотите.

2016-11-25 07:08 UTC, mglukhikh commented
recheck all

2016-11-25 07:25 UTC, mglukhikh commented
recheck all

2016-11-25 18:20 UTC, mglukhikh requested changes
Замечаний по коду почти нет, но две задачи решено неверно. Посмотрите на приведённые мною примеры и исправьте ошибки, после этого я закрою этот Pull Request.

2016-11-25 18:20 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return 0.0
Посмотрите, как работает ваше решение при следующих входных данных: `t1 = t2 = t3 = 1.0`, `v1 = v3 = 1.0`, `v2 = 0.0`. Подумайте, как поправить получающуюся ошибку.

2016-11-25 18:20 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +        if (a + r1 <= r2) return true else return false
`if (something) return true else return false` можно  заменить на `return something`

2016-11-25 18:20 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    return list
Ваше решение работает неверно при `n = 0`.

2016-11-28 07:28 UTC, mglukhikh commented
Уроки 1-5 приняты. Откройте, пожалуйста, новый Pull Request для задач урока 6.

2016-11-28 07:28 UTC, closed without merging