Number of fib
Kotlin-Polytech/KotlinAsFirst2016 pull request #150
Opened 2016-09-30 17:36 UTC by SidorenkoNikita

2016-10-01 19:28 UTC, mglukhikh commented
recheck all

2016-10-01 19:38 UTC, mglukhikh commented
recheck all

2016-10-01 19:48 UTC, mglukhikh requested changes
А кроме этого, вы игнорировали замечания по стилю, приведённые в вашем предыдущем PR https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/86. Настоятельно прошу исправить эти замечания.

2016-10-01 19:48 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val lenght:Double = (t1*v1+t2*v2+t3*v3)/2
По английски длина будет `length`. `Double` в этой строчке не нужно. Кроме этого, вы везде ставите пробелы рядом со знаками операций, а в этой функции почему-то нет.

2016-10-01 19:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int = if (n<3) 1 else fib(n-1)+ fib(n-2)
Это решение математически верно, но может выполняться очень долго. Попробуйте посчитать, сколько раз вызовется функция `fib` при, например, `n = 15`. Эта проблема приводит к тому, что не может завершиться за разумное время тест для `fibSequenceDigit`, так как она использует эту функцию.

2016-10-01 19:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        toString[n-1] == '0' -> c=0
То, что вы здесь хотите выразить, записывается проще -- `toString[n - 1] - '0'`. Символы тоже можно вычитать, при этом вычитаются их коды. Коды символов с `0` до `9` расположены в таблицах по порядку.

2016-10-01 19:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        numbers = numbers+ fib(i)
Использованная здесь идея не очень конструктивна. Во-первых, вы считаете существенно больше чисел Фибоначчи, чем нужно. Во-вторых, вы все их записываете в строку, и эта строка для больших `n` получится у вас очень длинной.

2016-10-25 11:00 UTC, mglukhikh commented
recheck all

2016-10-25 11:02 UTC, mglukhikh commented
recheck all

2016-10-28 13:29 UTC, mglukhikh commented
recheck all

2016-10-28 13:30 UTC, mglukhikh commented
recheck all

2016-10-28 13:48 UTC, mglukhikh requested changes
Очень много замечаний по коду, к тому же, по-прежнему неверно решена задача из 2-го урока. Пожалуйста, исправьте их все, прежде чем начинать решать новые задачи.

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = hours*3600+minutes*60+seconds
Здесь и далее: операторы должны быть отделены пробелами от своих аргументов, это упрощает чтение. Вы можете достичь этого автоматически, применив комбинацию Ctrl+Alt+L в IDEA

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = (1.0+0.01*percent)*(1.0+0.01*percent)*(1.0+0.01*percent)*initial
Одно и то же выражение повторяется трижды

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (age/10 ==1) return "$age лет"
Пробелы

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val lenght:Double = (t1 * v1 + t2 * v2 + t3 * v3) / 2
Тип указывать не обязательно. Длина по-английски `length`

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX == rookX2 || kingY == rookY2)&& (kingX == rookX1 || kingY == rookY1)) checkForPosition=3
Попробуйте придумать, как избежать двухкратной проверки одних и тех же условий

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
Ранее уже говорилось, что `if (x) return true else return false` можно заменить на `return x`. Более того

```
fun foo(...): Boolean {
   return x
}
```

можно заменить на `fun foo(...): Boolean = x`.

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
Те же замечания к последующим функциям в этом уроке

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var x2:Int = 1
```
var x1 = 1
var x2 = 1
```

И так понятно, что всё целое. Не замусоривайте код.

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (n<3) return 1
Пробелы

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Этот `when` можно записать в одну строчку, если немножко подумать

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        i = i+1
`i++`

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var toString:String = ""
`var toString = ""`

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        numbers = numbers+ fib(i)
Пробелы

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            val forList:Int = number - number / base * base
Тип не нужен

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        var l:Int = additional.size - 1
Тип не нужен

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            l = l - 1
`l--`

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        result.add(additional[0])
У списка есть функция `reversed`, переворачивающая его

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun fromNumberToNameT(n: Int): String {
1) Эта функция почти дублирует предыдущую. Избавьтесь от одной из них
2) И там и там следовало писать `when (n)`, тогда не нужно было бы писать всюду `== x`.
3) Следовало написать

```
return when (n) {
    900 -> "девятьсот"
    ...
    else -> ""
}
```

тогда не пришлось бы всюду писать ещё и `nameOf = `.

4) В идеале, все эти имена надо записать в списки и обращаться к этим спискам.

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            del=del/10
Такой фрагмент кода выше уже есть

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var forFunFrom: Int = 0
Не нужно всюду указывать типы. А переменные следует определять там, где они нужны, не надо делать это в начале функции

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        }
Вынесите этот `when` в отдельную функцию

2016-10-28 13:48 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else return "$age год"
Эта задача по-прежнему решена с ошибкой

2016-11-09 11:28 UTC, mglukhikh commented
Не нужно пока решать новые задачи, исправьте для начала имеющиеся ошибки

2016-11-15 10:29 UTC, mglukhikh requested changes
По-прежнему есть замечания, часть из них пишу повторно. Также обращаю внимание на то, что вы решаете задачи из 6-го урока, не только не исправив замечания из уроков 1-4, но и полностью пропустив урок 5.

2016-11-15 10:29 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = 1.0 * sqrt(sqr(x1 - x2) + sqr(y1 - y2))
Умножение на 1.0 лишнее

2016-11-15 10:29 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
Повторно! Здесь и далее в этом уроке: `if (expression) return true else return false` эквивалентно `return expression`. А 

```
fun foo(...): Boolean {
    return expression
} 
```

эквивалентно 

```
fun foo(...): Boolean = expression
```

2016-11-15 10:29 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Повторно! Этот `when` можно записать в одну строчку (достаточно вычесть `'0'` из имеющегося символа)

2016-11-15 10:29 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        return additional
Действительно ли эта ветка необходима?

2016-11-15 10:29 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            val forList: Int = number - number / base * base
Не нужно указывать тип локальных переменных

2016-11-15 10:29 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val additional = mutableListOf<Int>()
Неудачное название для переменной. В каком смысле `additional`?

2016-11-15 10:29 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        result.add(additional[0])
Повторно! Используйте `list.reversed()` или `mutableList.reverse()` для переворачивания списка.

2016-11-15 10:29 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun russian(n: Int): String {
Повторно! Исправьте замечания к этой функции из предыдущего Review (вы их проигнорировали). Замечания можно посмотреть у себя на почте или здесь, раскрыв "Show Outdated". От того, что вы выровняли код, замечания по сути никуда не деваются

2016-11-25 21:15 UTC, mglukhikh commented
recheck all

2016-11-25 21:19 UTC, mglukhikh commented
Вы всё-таки сделайте что-нибудь из 5-го урока, прежде чем начинать делать 6-й.

2016-11-30 12:19 UTC, mglukhikh requested changes
Довольно много замечаний, в том числе есть старые. Несколько неработающих тестов и полностью пустой 5-й урок. Пожалуйста, исправьте замечания, прежде чем переходить к следующим урокам.

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Повторно!

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            val forList: Int = number - number / base * base
Вы в курсе, что есть `%`? И тип здесь не нужен

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            numberOfThousands = numberOfThousands - numberOfThousands / del * del
Здесь и во многих местах ниже стоит воспользоваться `%`

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var forFunFrom: Int = 0
Зачем повсюду писать типы?

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun fromNumberToName(n: Int): String {
Эта и следующая функция делают почти и одно и то же. Объедините их в одну (достаточно добавить второй параметр)

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        n == "декабря" -> c = "12."
Для этой цели можно использовать список с названиями месяцев и `list.indexOf`

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    if (c == true) return n
`if (c)`

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    }
Этот цикл содержит сразу несколько ошибок, проверьте его внимательно, пожалуйста

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun checkForDate(n: String): String {
Лучше использовать названия `convertDay`, `convertMonth`, `convertYear`. От функции `check` ожидаешь, что её результат -- это Boolean (проверка, верно ли что-нибудь)

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (part in parts) {
`for ((index, part) in parts.withIndex())` { ... }

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        when {
Вынесите индекс вверх: `when (index) { ... }`

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            checkForParts == 3 -> result = result + checkForYear(part)
Используйте `+=`

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    }
`checkResult.size`

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val parts = str.split(" ")
Размер списка стоит проверить с самого начала

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun dateStrToDigit(str: String): String {
Проверьте работу этой функции на полностью некорректной строке вроде `abcde`

2016-11-30 12:19 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return ourCircle
Проверьте эту функцию на тесте, предоставленном ботом, и попробуйте исправить ошибки. Если возникнут проблемы, прокомментируйте мне использованные вами формулы, постараюсь вам помочь. С ходу возникает вопрос, а что будет, если `a.x == b.x` или `b.x == c.x`

2016-12-19 08:22 UTC, mglukhikh commented
Ни исправлений, ни решений 5-го урока пока не последовало, так что имеем "незачёт".

2016-12-19 21:14 UTC, mglukhikh commented
Заметим, что замечания вы так и не исправили, зато попытались решить очень сложную задачу в 6-м уроке. Надеюсь хотя бы к дополнительной сессии вы таки удосужитесь поправить замечания.

2017-01-15 14:19 UTC, SidorenkoNikita commented on src/lesson5/task1/Parse.kt
> +        n == "декабря" -> c = "12."
Является ли предложенный вами вариант обязательным или нет? Просто мне проще проверять в данном случае код, если выполнен не  длинной строкой, но множеством коротких.

2017-01-15 14:23 UTC, SidorenkoNikita commented on src/lesson5/task1/Parse.kt
> +fun checkForDate(n: String): String {
Название выбрано таким образом, т.к. тут помимо конвертации происходит проверка числа, на возможность отождествлять дату.

2017-01-15 14:28 UTC, SidorenkoNikita commented on src/lesson5/task1/Parse.kt
> +            checkForParts == 3 -> result = result + checkForYear(part)
Можно уточнить, есть ли разница в производительности моего варианта исполнения и предложенного вами? Если нет, то я предпочту писать так, т.к. это упрощает мне чтение моего кода.

2017-01-15 14:30 UTC, SidorenkoNikita commented on src/lesson4/task1/List.kt
> +    var forFunFrom: Int = 0
Так мне проще проверять, да и просто вошло в привычку.

2017-01-15 14:39 UTC, SidorenkoNikita commented on src/lesson3/task1/Loop.kt
> +    }
То, что это возможно я понял, но не могу понять, зачем мне это тут делать. Данный блок органично смотрится, а т.к. на тот момент я хотел оттачивать навыки использования условной конструкции when, я решил, что сильно на эффективность программы это не повлияет.

2017-01-15 17:13 UTC, mglukhikh commented
recheck all

2017-01-15 17:22 UTC, mglukhikh requested changes
Задач сделано едва-едва на зачёт, а исправлять замечания вы ленитесь. Приходите завтра в 14-00, будете заниматься их исправлениями прямо на последнем зачётном занятии.

2017-01-15 17:22 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Должен вас расстроить -- даже в виде конструкции when этот код можно записать значительно короче и органичнее. Пожалуйста, сделайте это, раз уж вы "оттачивали на тот момент навыки использования условной конструкции".

2017-01-15 17:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            val forList: Int = number - number / base * base
Ещё раз напоминаю, что есть операция %

2017-01-15 17:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            numberOfThousands = numberOfThousands - numberOfThousands / del * del
И здесь тоже есть %, как и во многих местах ниже

2017-01-15 17:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun fromNumberToName(n: Int): String {
Эта и следующая функция делают почти и одно и то же. Объедините их в одну (достаточно добавить второй параметр)

2017-01-15 17:22 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun dateStrToDigit(str: String): String {
Ок

2017-01-15 17:22 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        n == "декабря" -> c = "12."
И в этом примере тоже when можно написать более коротко, раз уж вы хотите непременно написать много коротких строк вместо одной. Все ваши короткие строки станут ещё короче.

2017-01-16 13:43 UTC, SidorenkoNikita commented
recheck all

2017-07-26 18:23 UTC, closed without merging