1,2(1/2 урок
Kotlin-Polytech/KotlinAsFirst2016 pull request #151
Opened 2016-09-30 19:37 UTC by naftasenka

2016-10-01 08:09 UTC, ice-phoenix requested changes

2016-10-01 08:09 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val hours = hours * 60 * 60
Называть переменную так же, как аргумент функции, --- **очень плохой** стиль. К тому же, имя `hours` не соответствует смыслу данной переменной, это не просто время в часах, это время в часах, выраженное в секундах.

2016-10-01 08:09 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val sagenes = sagenes * 48
См. замечания к `seconds`

2016-10-01 08:09 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val sec = sec / 3600.0
См. замечания к `seconds`

2016-10-01 08:09 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val number = (number % 1000)
См. замечания к `seconds`

2016-10-01 08:09 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val hoursDepart = hoursDepart * 60 + minutesDepart
См. замечания к `seconds`

2016-10-01 08:09 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (initial * (1 + 0.01 * percent)) * (1 + 0.01 * percent) + 0.01 * percent * (initial * (1 + 0.01 * percent)) * (1 + 0.01 * percent)
Повторно используемые выражения лучше вынести в отдельную переменную

2016-10-12 09:41 UTC, mglukhikh commented
Автору PR: вы сильно отстаёте от графика. Вам следует исправить приведённые в этом PR замечания и перейти к решению задач 2-го и 3-го урока, в противном случае вы рискуете получить неудовлетворительную оценку за октябрь месяц.

2016-10-13 12:33 UTC, ice-phoenix requested changes
В будущем убедительная просьба исправлять замечания к уже сделанным задачам перед тем, как решать следующие

2016-10-13 12:33 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (age % 10 == 1 && age / 10 != 1)
Данное выражение лучше оформить как `when`

2016-10-13 12:33 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (t1 * v1 >= s) return s / v1 else
* Данное выражение лучше оформить как `when`
* Попробуйте отформатировать ваш код при помощи IntelliJ IDEA и в дальнейшем придерживаться такого же стиля форматирования

2016-10-13 12:33 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (kingX != rookX1 && kingY != rookY1 && kingX != rookX2 && kingY != rookY2)
* Подвыражения, отвечающие за условия, при которых та или иная фигура атакует короля, следует вынести в отдельные переменные
* Данное выражение лучше оформить как `when`
* Форматирование кода

2016-10-13 12:33 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (kingX != rookX && kingY != rookY && bishopX + bishopY != kingX + kingY && bishopX - bishopY != kingX - kingY) return 0 else
* Подвыражения, отвечающие за условия, при которых та или иная фигура атакует короля, следует вынести в отдельные переменные
* Данное выражение лучше оформить как `when`
* Форматирование кода

2016-10-13 12:33 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a > (b + c) || b > (a + c) || c > (a + b)) return -1
* Данное выражение лучше оформить как `when`
* Лучше сперва найти минимальную сторону треугольника, а потом все считать относительно нее

2016-10-13 12:33 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a > d || c > b) return -1 else
* Данное выражение лучше оформить как `when`
* Форматирование кода

2016-10-25 09:40 UTC, ice-phoenix commented
recheck all

2016-10-25 10:37 UTC, ice-phoenix requested changes

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val hoursinseconds = hours * 60 * 60
Для именования переменных в Котлине принято использовать `camelCase`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +
Какое значение несет данная пустая строка?

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (number % 1000) / 100
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val totalminutesDepart = hoursDepart * 60 + minutesDepart
`camelCase`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return initial * k * k + 0.01 * percent * initial * k * k
Данное выражение можно упростить еще дальше

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        age % 10 >= 2 && age % 10 <= 4 && age / 10 != 1 && age / 10 % 10 != 1 -> return "$age года"
Можно как `age % 10 in 2..4`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val s = (v1 * t1 + v2 * t2 + v3 * t3) / 2
Повторно используемые подвыражения следует вынести в отдельные переменные

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        firstRookThreatens == false && secondRookThreatens == false -> return 0
Можно просто `!firstRookThreatens && !secondRookThreatens`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (rookThreatens == false && bishopThreatens == false) return 0 else
Данное выражение лучше оформить как `when`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        a > (b + c) || b > (a + c) || c > (a + b) -> return -1
Лучше сперва найти максимальную сторону треугольника и все считать относительно нее

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (a + b == c + d) return true else return false
Выражение `if (cond) return true else return false` можно заменить на `return cond`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (x1 == x2 || y1 == y2 || x1 + y1 == x2 + y2 || x1 - y1 == x2 - y2) return true else return false
* Выражение `if (cond) return true else return false` можно заменить на `return cond`
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) <= r2-r1) return true else return false
* Выражение `if (cond) return true else return false` можно заменить на `return cond`
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (((a <= r) && (b <= s)) || ((a <= s) && (b <= r)) || ((a <= r) && (c <= s)) || ((a <= s) && (a <= r)) || ((c <= r) && (b <= s)) || ((c <= s) && (b <= r))) return true else return false
* Выражение `if (cond) return true else return false` можно заменить на `return cond`
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (k==0) return 1 else return k
Форматирование кода должно быть единообразным везде в отношении пробелов, расстановки запятых, скобок, переносов строк и прочего. Считайте, что ваш код постоянно читает психопат с топором, который знает, где вы живете.

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +for (i in 3..n) {
Форматирование кода

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var fib1: Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n==1 || n==2) return 1 else return fib1
Чему будет равно `fib1`, если `n in 1..2`?

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var nok = (m * n) / nod
Подсчет GCD следует вынести в отдельную функцию

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var nod : Int
Зачем вы разделили объявление и определение переменной?

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i: Int = n - 1
* Система типов Котлина выведет тип переменной автоматически
* Нет ли более точной верхней границы на возможные делители числа, чем `n - 1`?

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +for (i in 2..max) {
Фор-ма-ти-ро-ва-ни-е ко-да!

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (noDivisor == false) return false else return true
Нельзя ли данную функцию выразить через другие функции данного модуля?

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(m.toDouble())).toInt()
* Система типов Котлина выведет тип переменной автоматически
* Для округления лучше использовать специальные функции `floor / ceil / round`

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (k*k >= m && k*k <= n) return true else return false
Если вы воспользуетесь правильной функцией округления, то можно будет обойтись без цикла и этой проверки

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        fraction = Math.pow(x,n*2.0+1)/factorial(n*2+1)
Форматирование кода

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        m = m*10 + last
Кода форматирование единым должно везде быть

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +       last = nn % 10
Зачем отдельная переменная для `last`?

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (answer == n) return true else return false
Не дублирует ли код этой функции код функции `revert`???

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (nn % 10 != digit) answer = true
Форматирование кода

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var answer = false
Можно обойтись без этой переменной, если сразу возвращать результат

2016-10-25 10:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    fun quantity(n: Int): Int {
Зачем вам эта функция? Нет ли у вас уже реализованной функции с той же функциональностью?

2016-10-27 14:39 UTC, ice-phoenix requested changes
Будьте внимательнее при исправлении замечаний и не пропускайте их. Если вы не согласны с какими-либо замечаниями, можете обсудить их с преподавателями на занятиях или в PR.

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return initial * k * k * (1 + 0.01 * percent)
Нет ли у вас уже готового выражения для `(1 + 0.01 * percent)`?

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        s1 >= s -> return s / v1
`when { return ... return ... return ... }` лучше записать как `return when { ... }`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        firstRookThreatens == true && secondRookThreatens == true -> return 3
Сравнивать переменную типа `Boolean` с `true` бессмысленно, сама переменная `a` имеет точно такое же значение, как и `a == true`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        rookThreatens == false && bishopThreatens == false -> return 0
См. замечание к `whichRookThreatens`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`when { return ... return ... return ... }` лучше записать как `return when { ... }`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`when { return ... return ... return ... }` лучше записать как `return when { ... }`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`when { return ... return ... return ... }` лучше записать как `return when { ... }`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        a > (b + c) || b > (a + c) || c > (a + b) -> return -1
Это замечание все еще в силе

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        b >= d && a >= c && a <= d -> return Math.abs(a - d)
Зачем вам модуль?

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`when { return ... return ... return ... }` лучше записать как `return when { ... }`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) <= r2 - r1) return true else return false
* Выражение `if (cond) return true else return false` можно заменить на `return cond`
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (((a <= r) && (b <= s)) ||
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (k == 0) return 1 else return k
Данные проверки лучше делать перед тяжелыми вычислениями, чтобы избежать этих самых тяжелых вычислений

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var nod = mm
Вычисление НОД лучше вынести в отдельную функцию

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((m % i == 0) && (n % i == 0)) noDivisor = false
Нельзя ли данную функцию выразить через другие функции данного модуля?

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(n.toDouble())).toInt()
* Для округления лучше использовать специальные функции `floor / ceil / round`
* Система типов Котлина выведет тип переменной автоматически

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (k * k >= m && k * k <= n) return true else return false
* Выражение `if (cond) return true else return false` можно заменить на `return cond`
* Если воспользоваться правильной функцией округления, данное условие можно упростить

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    xx = x % (2 * PI)
Зачем вы разделили определение и объявление переменной?

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    xx = x % (2 * PI)
Зачем вы разделили определение и объявление переменной?

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var last = 0
Почему эта переменная объявлена здесь, а не внутри цикла?

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (answer == n) return true else return false
Не дублирует ли код данной функции код функции `revert`?

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var answer = false
Это замечание все еще в силе

2016-10-27 14:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    fun quantity(n: Int): Int {
Это замечание все еще в силе

2016-10-27 14:40 UTC, ice-phoenix commented
recheck all

2016-10-27 16:31 UTC, naftasenka commented on src/lesson2/task1/IfElse.kt
> +        b >= d && a >= c && a <= d -> return Math.abs(a - d)
На мой взгляд, в некоторых случаях может получиться отрицательный результат, что не соответствует вопросу задачи.

2016-10-27 16:32 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    fun quantity(n: Int): Int {
Я не совсем понимаю, что Вы имеете в виду, поэтому не знаю как сделать по-другому.

2016-10-27 16:34 UTC, naftasenka commented on src/lesson2/task1/IfElse.kt
> +        a > (b + c) || b > (a + c) || c > (a + b) -> return -1
Мне кажется, что так задание будет выполнять сложнее, поэтому думаю, что лучше так.

2016-10-27 16:36 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +        if ((m % i == 0) && (n % i == 0)) noDivisor = false
Например, when?

2016-10-27 16:36 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var nod = mm
Имеете в виду присвоение вместе с выполнением совместить?

2016-10-27 17:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        a > (b + c) || b > (a + c) || c > (a + b) -> return -1
Так задание выполнять правильнее, потому что это делает ваш код более понятным для других разработчиков

2016-10-27 17:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        b >= d && a >= c && a <= d -> return Math.abs(a - d)
Давайте вы внимательно посмотрите на условия каждой из веток `when` и подумаете, могут ли разности быть отрицательными с учетом этих самых условий

2016-10-27 17:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        b >= d && a >= c && a <= d -> return Math.abs(a - d)
Если они могут, то может быть, следует поменять местами уменьшаемое и вычитаемое?

2016-10-27 17:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var nod = mm
Нет, имею в виду вынести весь алгоритм поиска НОД в отдельную функцию, которая вам еще пару раз потом пригодится

2016-10-27 17:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((m % i == 0) && (n % i == 0)) noDivisor = false
Например, одну из функций, написанных вами ранее, которая как-то связана с делителями или кратными

2016-10-27 17:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var last = 0
Что мешает объявить ее внутри цикла и сразу же определить в нужное вам значение?

2016-10-27 17:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    fun quantity(n: Int): Int {
Посмотрите на другие функции и подумайте, не реализовали ли вы ранее функцию, которая делает то же самое, что делает функция `quantity`

2016-10-27 20:07 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    if (k == 0) return 1 else return k
То есть мне k перед when проверять?

2016-10-27 20:09 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(n.toDouble())).toInt()
А функция такого вида не будет работать в данной задаче? Проверка выдает все верно.

2016-10-27 20:12 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    if (answer == n) return true else return false
Да, только заметила. Но ведь данная проверка работает, так задача легко решается:)

2016-10-27 20:13 UTC, naftasenka commented on src/lesson1/task1/Simple.kt
> +    return initial * k * k * (1 + 0.01 * percent)
Не могла никак заметить, простите. Исправлю.

2016-10-27 20:16 UTC, naftasenka commented on src/lesson2/task1/IfElse.kt
> +        b >= d && a >= c && a <= d -> return Math.abs(a - d)
Когда я делала без модуля, задача не проходила. А так не имеет значение в каком порядке идет вычитание.

2016-10-27 20:17 UTC, naftasenka commented on src/lesson2/task2/Logical.kt
> +    if (Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) <= r2 - r1) return true else return false
Kotlin автоматически меняет на return if. Это аналогично с return cond? Или можно убрать if?

2016-10-27 20:19 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var answer = false
У меня так не проходит задача почему-то, поэтому оставила так.

2016-10-28 07:45 UTC, naftasenka commented on src/lesson2/task1/IfElse.kt
> +        b >= d && a >= c && a <= d -> return Math.abs(a - d)
Поняла. Исправлю.

2016-10-28 08:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (answer == n) return true else return false
То, что ваш код работает, не значит, что код хороший или правильный. Дублировать код целой функции вместо того, чтобы просто **вызвать** эту функцию и воспользоваться результатами ее работы *безвозмездно-то-есть-даром*, --- очень странное и неправильное решение. А пытаться свое решение еще и защитить тем, что "все работает, и задача легко ж решается!", --- еще более странно.

2016-10-28 08:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(n.toDouble())).toInt()
В таком случае дополнительный вопрос. Как именно округляет `toInt()`? Какой из трех перечисленных мной выше функций он аналогичен?

2016-10-28 08:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (k == 0) return 1 else return k
Да, его лучше проверить перед всем циклом и сразу вернуть нужный результат, если `k == 0`

2016-10-28 08:36 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) <= r2 - r1) return true else return false
Попробуйте подумать самостоятельно, если у вас есть `return if (cond) true else false`, в каком случае ваша функция вернет `true`, в каком --- `false`, и как все это можно упростить

2016-10-28 12:12 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(n.toDouble())).toInt()
Если мне не изменяет память, round.

2016-10-28 12:16 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(n.toDouble())).toInt()
Round?

2016-10-28 12:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(n.toDouble())).toInt()
Вот видите, вы внезапно не знаете, как работает ваш код. Нет, не `round`.

2016-10-28 15:55 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(n.toDouble())).toInt()
Простите, я не помню, как ими пользоваться. Не могли бы Вы напомнить мне, в каком уроке я могу это посмотреть?

2016-10-28 16:08 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var answer = false
Нам ведь нужно проверять условие на каждом делении числа n, я не пойму как избавиться от answer.

2016-10-28 16:41 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var answer = false
Все, простите, поняла:)

2016-10-28 16:41 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var answer = false
Сейчас пришлю новый вариант

2016-10-28 16:55 UTC, naftasenka commented on src/lesson3/task1/Loop.kt
> +    var k: Int = (sqrt(n.toDouble())).toInt()
Вроде поняла, спасибо))

2016-10-31 12:15 UTC, ice-phoenix requested changes
Довольно много замечаний, просьба все их исправить перед работой над следующими уроками

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        if (max * max == mid * mid + min * min) return 1
Данное выражение лучше оформить как `when`, в остальном, прямо круто-круто =)

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a > b + c || b > c + a || c > a + b) return -1 else {
А разве недостаточно проверить неравенство треугольника относительно максимальной стороны?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (a + b == c + d)
Лишние скобки вокруг законченного выражения

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int) = (x1 == x2 || y1 == y2 || x1 + y1 == x2 + y2 || x1 - y1 == x2 - y2)
Длинная строка обычно разбивается на несколько более коротких, здесь, например, можно перенести строку после знака `=`

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) <= r2 - r1)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        ((a <= s) && (b <= r)) ||
Лишние скобки вокруг законченных выражений

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n == 0) return 1 else {
`else` лучше перенести на новую строку, а `return 1` заключить в фигурные скобки

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n == 1 || n == 2) return 1 else return fib1
`return` лучше вынести наружу из веток `if`

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun nod(m: Int, n: Int): Int {
`gcd`

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var mm = nod(m, n)
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (max == 1) return true else return false
Выражение `if (cond) return true else return false` можно заменить на `return cond`

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var max = nod(m, n)
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (k * k >= m && k * k <= n)
Затем первая часть проверки? Может ли `k * k < m`?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var last = nn % 10
Зачем вам эта переменная? Почему сразу не воспользоваться `n % 10` там, где необходимо это выражение?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var answer = revert(n)
Можно проще как `... = revert(n) == n`

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +
Зачем данная пустая строка?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    fun quantity(n: Int): Int {
Нет ли у вас уже реализованной функции, которая делает то же самое, что и данная функция?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        a = a + v[i] * v[i]
Лучше воспользоваться циклом в foreach-стиле

```
for (e in list) {
    foo(e)
}
```

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val sum = list.sum()
Зачем вам эта переменная как переменная?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return 0.0 else return sum / (list.size.toDouble())
Зачем `toDouble()`?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var mean = sum / list.size
Что будет, если список пустой? Почему не воспользоваться функцией `mean`?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Зачем эта проверка? Как отработает код внутри `if`, если список пустой?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var C = 0.0
В Котлине для именования переменных принято использовать `camelCase`

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        n++
Зачем вам `n`, если у вас есть `i`?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i: Int in 0..list.size - 1) {
Зачем `i: Int`???

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (isPrime(i) == true)
Если вы перебираете возможные делители от минимального к максимальному, возможна ли ситуация, когда число делится нацело на непростое числ?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var number: Int = n
* Система типов Котлина выведет тип переменной автоматически

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list = listOf()
Почему вы разделили определение и объявление переменной?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    fun isPrime(n: Int): Boolean {
Зачем вы еще раз реализовали ту же самую функцию, что и выше?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: List<Int>
Почему вы не воспользовались реализацией функции `factorize`, которая у вас уже есть?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list = listOf()
Почему вы разделили определение и объявление переменной?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (n == 0) str = ""
Зачем?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: List<Int>
Почему вы разделили определение и объявление переменной?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (list[i] > 9) str = str + (87 + list[i]).toChar()
Что такое 87?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else str = str + (list[i]).toString()
Зачем `toString()`? Почему не `toChar()`?

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var str: String = ""
Лучше список строк, список символов или `StringBuilder`

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        n = n + list[i] * Math.pow(basee, k)
Напишите функцию `pow(Int, Int): Int`, работающую в целых числах

2016-10-31 12:15 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var m = n.toInt()
Может быть, всю эту функцию можно заменить на вызов другой, уже реализованной вами выше функции?

2016-11-02 10:07 UTC, naftasenka commented on src/lesson4/task1/List.kt
> +        a = a + v[i] * v[i]
Т.е. a(i) = a + v[i] * v[i]?

2016-11-02 12:22 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        a = a + v[i] * v[i]
Нет

2016-11-22 16:14 UTC, ice-phoenix commented
recheck all

2016-11-22 16:25 UTC, ice-phoenix commented
recheck all

2016-11-23 11:17 UTC, ice-phoenix requested changes

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`when { return ... }` ==> `return when { ... }`

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`when { return ... }` ==> `return when { ... }`

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n == 0) {return 1}
Форматирование кода

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return if (n == 1 || n == 2) 1 else fib1
Почему не проинициализировать `fib1` единицей и не убрать проверку?

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return nok
Можно обойтись без промежуточных переменных

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return maxCoDivisor == 1
Можно обойтись без промежуточных переменных

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = ceil(sqrt(m.toDouble()))
[Здесь и много где] Почему `var`, а не `val`?

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var sin = x
Почему `x`, а не `xx`?

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    answer = i * i
Почему вы разделили определение и объявление этой переменной?

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> + * Разложить заданное натуральное число n > 1 на ПРОСТЫЕ множители.
Зачем?

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list = factorize(n)
Можно обойтись без вспомогательной переменной

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (n == 0) list = list + 0
Почему бы здесь сразу не вернуть то, что надо?

2016-11-23 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        k++
Нет ли взаимно однозначного соответствия между `k` и `i`?

2016-11-23 12:30 UTC, naftasenka commented on src/lesson4/task1/List.kt
> + * Разложить заданное натуральное число n > 1 на ПРОСТЫЕ множители.
Это было для себя, потом исправить забыла

2016-11-25 12:37 UTC, ice-phoenix requested changes

2016-11-25 12:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-25 12:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return nok
Если убрать вспомогательную переменную, то эту функцию можно записать как one-liner

2016-11-25 12:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return gcd(m, n) == 1
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-25 12:37 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return 0.0 else return list.sum() / (list.size)
Форматирование кода --- ветку else лучше вынести на отдельную строчку

2016-11-25 12:37 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (n == 0) return (list+0)
Форматирование кода или `listOf(0)`

2016-11-25 12:37 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var str = listOf<String>()
Не очень говорящее имя переменной

2016-11-25 12:37 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    fun distance(other: Circle): Double = if (center.distance(other.center) <= radius + other.radius) 0.0
Повторно используемое выражение лучше вынести в отдельную переменную

2016-11-25 12:37 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +    class MatrixImpl<E> : Matrix<E> {
Что случилось с форматированием?

2016-11-25 12:39 UTC, ice-phoenix commented
recheck all

2016-11-25 13:57 UTC, naftasenka commented on src/lesson7/task1/Matrix.kt
> +    class MatrixImpl<E> : Matrix<E> {
У меня не получилось сделать задание и я неудачно вернула все в начальное положение

2016-11-26 20:50 UTC, ice-phoenix requested changes
Раз уроки 5 и 6 вы решили на чуть-чуть, то и оценку мы вам будем выставлять, исходя из этого самого чуть-чуть.

2016-11-26 20:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (nn % 10 != n % 10) return true
Зачем постоянно считать `n % 10`?

2016-11-26 20:50 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            centerDistance - radiusSum
Тут лучше без фигурных скобок

2016-11-27 10:14 UTC, naftasenka commented
Марат Халимович, здравствуйте. Вы сказали, что будете ставить оценку на
основании упражнений 5 и 6 урока, но ведь для того, чтобы урок был
засчитан, нужно сделать 1 заданий из урока, что было выполнено мной. Значит
ли ваше сообщение, что мне снизят оценку? Исправления были сделаны, и
нужный критерий "одно задание из урока" было выполнено.

26 ноября 2016 г., 23:50 пользователь Marat Akhin <notifications@github.com>
написал:

> *@ice-phoenix* requested changes on this pull request.
>
> Раз уроки 5 и 6 вы решили на чуть-чуть, то и оценку мы вам будем
> выставлять, исходя из этого самого чуть-чуть.
> ------------------------------
>
> In src/lesson3/task1/Loop.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/151#pullrequestreview-10220498>
> :
>
> >
>  /**
>   * Средняя
>   *
>   * Для заданного числа n определить, содержит ли оно различающиеся цифры.
>   * Например, 54 и 323 состоят из разных цифр, а 111 и 0 из одинаковых.
>   */
> -fun hasDifferentDigits(n: Int): Boolean = TODO()
> +fun hasDifferentDigits(n: Int): Boolean {
> +    var nn = n
> +    while (nn > 0) {
> +        if (nn % 10 != n % 10) return true
>
> Зачем постоянно считать n % 10?
> ------------------------------
>
> In src/lesson6/task1/Geometry.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/151#pullrequestreview-10220498>
> :
>
> > @@ -55,7 +56,14 @@ data class Circle(val center: Point, val radius: Double) {
>       * расстояние между их центрами минус сумма их радиусов.
>       * Расстояние между пересекающимися окружностями считать равным 0.0.
>       */
> -    fun distance(other: Circle): Double = TODO()
> +    fun distance(other: Circle): Double {
> +        val centerDistance = center.distance(other.center)
> +        val radiusSum = radius + other.radius
> +        return if (centerDistance <= radiusSum) 0.0
> +        else {
> +            centerDistance - radiusSum
>
> Тут лучше без фигурных скобок
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/151#pullrequestreview-10220498>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVBw0DQQc8DaKwmBCZr_f0MIdMUhVDlQks5rCJudgaJpZM4KLcFr>
> .
>

2016-11-28 10:36 UTC, ice-phoenix requested changes

2016-11-28 10:36 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        else centerDistance - radiusSum
Форматирование кода

2016-11-28 17:02 UTC, naftasenka commented on src/lesson6/task1/Geometry.kt
> +        else centerDistance - radiusSum
Не могли бы вы уточнить, что именно отформатировать?

2016-12-04 20:30 UTC, ice-phoenix commented
recheck all

2016-12-04 20:39 UTC, ice-phoenix requested changes

2016-12-04 20:39 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((grad + minInGrad + secInGrad) * (PI / 180))
Лишние скобки вокруг законченного выражения

2016-12-04 20:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var k = 0
Так как в блоке `then` вы выходите из функции, блок `else` тут избыточен. Его тело можно просто написать сразу после вашего `if`.

2016-12-04 20:39 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    else return list.sum() / (list.size)
Зачем тут скобки вокруг `list.size`?

2016-12-04 20:39 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in list) if (i > 9) result += ('a' - 10 + i).toString()
Форматирование кода, е-мое!

2016-12-18 22:51 UTC, ice-phoenix commented
recheck all

2016-12-18 22:55 UTC, ice-phoenix commented
С учетом статистики решения задач, стиля кодирования и результатов тестирования, у вас "Удовлетворительно" автоматом.

2017-07-26 18:23 UTC, closed without merging