1,2,3 Lessons were done full
Kotlin-Polytech/KotlinAsFirst2016 pull request #152
Opened 2016-09-30 19:41 UTC by StarKRE

Михаил Игоревич, извините за предыдущий коммит, буду относиться с пониманием...

2016-10-01 08:11 UTC, ice-phoenix commented
recheck all

2016-10-01 08:40 UTC, ice-phoenix requested changes
Просьба внимательнее относиться к форматированию кода

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    seconds <= 60
Что, по вашему мнению, делает данная цепочка логических выражений?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return vershoks * 0.04445 + arshins * 16 * 0.04445 + sagenes * 48 * 0.04445
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (grad.toDouble() + min.toDouble()/60 + sec.toDouble()/3600) / (180 / Math.PI)
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`
* Для того, чтобы результат деления имел тип `Double`, обычно делают `a / 60.0`, а не `a.toDouble() / 60`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return sqrt(sqr(x2-x1)+sqr(y2-y1))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (number/100)%10
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    minutesArrive <= 60
В чем смысл данной цепочки выражений?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    min = (hoursArrive - hoursDepart) * 60 + (minutesArrive - minutesDepart)
Лучше объединить определение и объявление переменной `min`, что сократит код, позволит сделать переменную `val` вместо `var` и сделает ненужным явное указание ее типа

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((1+percent.toDouble()/100)*(1+percent.toDouble()/100)*(1+percent.toDouble()/100) * initial.toDouble())
* Повторно используемые выражения лучше вынести в отдельные переменные
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`
* `toDouble() -> 100.0`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((number % 10) * 100) + ((number / 100)) + (number - ((number / 100)*100) - (number % 10))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    age > 0
Зачем?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
Данное выражение лучше оформить как `when`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +      val s2 =(((v1*t1)+(v2*t2)+(v3*t3))/2)
Форматирование кода должно быть единообразным. Попробуйте отформатировать код при помощи IntelliJ IDEA и в дальнейшем придерживайтесь данного стиля кодирования.

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (s2 <= v1*t1){
Повторно используемые выражения лучше вынести в отдельные переменные

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (kingX != rookX1 && kingX != rookX2 && kingY != rookY2 && kingY != rookY1){
* Данное выражение лучше оформить как `when`
* Повторно используемые выражения лучше вынести в отдельные переменные с говорящими именами

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (abs(kingX.toDouble() - bishopX.toDouble()) == abs(kingY.toDouble() - bishopY.toDouble()) && kingX != rookX && kingY != rookY) {
* Данное выражение лучше оформить как `when`
* Повторно используемые выражения лучше вынести в отдельные переменные с говорящими именами
* Для чего вы приводите аргумент функции `abs` к типу `Double`?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            var min: Double
Форматирование кода

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            if (max >= min + nor){
Данное выражение лучше оформить как `when`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (d >= b) {
Данное выражение лучше оформить как `when`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    var a:Int = number/1000
* Форматирование кода
* Система типов Котлина выведет тип переменной автоматически
* Данная переменная может быть объявлена как `val`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return Math.abs(x1-x2) == Math.abs(y1-y2) || x1 == x2 || y1 == y2
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        return r1 <= r2 && Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) <= r2-r1
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    var  min: Int
Форматирование кода

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k: Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var x1: Int = 1
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var min: Int = 0
Форматирование кода

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (m * n )/ k
Поиск НОД лучше вынести в отдельную функцию

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Нет ли более точной верхней границы для возможного делителя числа `n`, чем `n`?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n-1) {
Зачем при поиске максимального делителя идти от минимального возможного делителя к максимальному?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..min){
Здесь вы делаете тот же самый поиск НОД, как и в задаче с поиском НОК

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (sqrt(i.toDouble()).toInt().toDouble() == sqrt(i.toDouble())) {
Сравнивать значения типа `Double` на равенство при помощи `==` --- не очень хорошая идея. Подумайте, нельзя ли решить данную задачу в рамках типа `Int`?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var k: Double = 1.0
**Форматирование кода**

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            if (k % 2.0 == 1.0 && k % 4.0 != 1.0) {sin = sin - number}
Почему переменная `k` имеет тип `Double`?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        while (Math.abs(number) * 1000 > eps) {
Нельзя ли считать ряд в рамках одного цикла?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k: Double = 0.0
См. замечания к `sin`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        while (s > 0) {
Почему не воспользоваться уже написанной вами функцией `revert`?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var k = 0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            while (s >0 ){
Почему не воспользоваться уже написанной вами функцией для подсчета количества цифр в числе?

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            while (s > 0 ){
См. замечания выше

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +   var sum: Double = 0.0
* Система типов Котлина выведет тип переменной автоматически

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0 .. v.size-1){
Если вам явно не нужен индекс значений в списке, лучше воспользоваться циклом в `foreach` стиле
```
for (element in list) {
    foo(element)
}
```

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0 .. list.size - 1){
Можно просто `list.sum()`

2016-10-01 08:40 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (a.size < b.size){
Скалярное произведение векторов разных размерностей неопределено

2016-10-01 08:40 UTC, ice-phoenix commented
recheck all

2016-10-01 08:42 UTC, ice-phoenix commented
recheck all

2016-10-01 14:22 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +    if (a.size < b.size){
Определил, нашел наименьшую длину min из двух списков и в цикле пробежался от 0 до min -1 , потому что от i min и до длины большей строки произведения скалярных векторов равно 0.

2016-10-01 14:50 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    age > 0
По условию задачи

2016-10-01 18:43 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
когда пишу код через when . Idea выдает ошибку SDE is not occupated

2016-10-01 18:57 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    if (kingX != rookX1 && kingX != rookX2 && kingY != rookY2 && kingY != rookY1){
когда пишу код через when . Idea выдает ошибку SDE is not occupated

2016-10-01 18:59 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    if (abs(kingX.toDouble() - bishopX.toDouble()) == abs(kingY.toDouble() - bishopY.toDouble()) && kingX != rookX && kingY != rookY) {
когда пишу код через when . Idea выдает ошибку SDE is not occupated

2016-10-01 19:50 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
А можно, например, увидеть скриншот этой ошибки? Или приложить пример кода, который ее вызывает?

2016-10-01 19:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    age > 0
По условию задачи все прекрасно. Вот только как вы думаете, что именно делает ваше выражение `age < 200` в случае, если `age == 201` при выполнении кода?

2016-10-01 19:53 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (a.size < b.size){
Скалярное произведение векторов разных размерностей неопределено с **математической точки зрения**. То, что вы его доопределили, это интересно, но не соответствует тому, как это должно работать на практике.

2016-10-01 21:57 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
KotlinCompilerException: <Exception from standalone Kotlin compiler>
fun whichRookThreatens(kingX: Int ,kingY: Int ,
                       rookX1: Int ,rookY1: Int ,
                       rookX2: Int ,rookY2: Int): Int {
    var BRookx1: Boolean = kingX == rookX1
    var BRookx2: Boolean = kingX == rookX2
    var BRooky1: Boolean = kingY == rookY1
    var BRooky2: Boolean = kingY == rookY2
    when (BRookx1 == false && BRookx2 == false && BRooky1 == false && BRooky2 == false) {
        return 0
        ->
            when ((BRookx1 == true && BRookx2 == false && BRooky2 == false) || (BRooky1 == true && BRookx2 == false && BRooky2 == false)) {
                return 1
                ->
                    if ((BRookx1 == false && BRookx2 == true && BRooky1 == false) || (BRooky2 == true && BRookx1 == false && BRooky1 == false)) {
                        return 2
                    }else {
                                return 3
                            }
                    }
            }
    }

2016-10-01 21:58 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
<Exception from standalone Kotlin compiler>

2016-10-01 21:59 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
Exception from standalone Kotlin compiler - ошибка

2016-10-01 22:13 UTC, StarKRE commented
В 1-м уроке в задании с поездом, где нужно рассчитать время пути, бот вывел ошибку: 
Expected: 0
Actual: 1440
Inputs:
hoursDepart -> 1
minutesDepart -> 1
hoursArrive -> 1
minutesArrive -> 1
НО Поезд мог проехать ровно сутки и прибыть в то же время только уже на другой станции.

2016-10-01 22:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
Внимательно прочитайте раздел про `when` в [обучающих материалах](https://github.com/Kotlin-Polytech/KotlinAsFirst2016/blob/master/tutorial/chapter02.adoc) и попробуйте понять, где у вас ошибка.

2016-10-01 22:51 UTC, ice-phoenix commented
Ваш последний коммит не компилируется. Убедительная просьба **проверять коммит на работоспособность** локально перед отправкой PR.

2016-10-02 10:23 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
Спасибо)

2016-10-02 15:36 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((age%10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
Приведенный код, конечно, неверен, но сама по себе проблема любопытная. Попробую повторить ошибку у себя, спасибо

2016-10-03 08:18 UTC, ice-phoenix requested changes
Ваш код все еще не компилируется

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad.toDouble() + min /60.0 + sec /3600.0) / (180.0 / Math.PI)
- Форматирование кода --- старайтесь придерживаться единого стиля форматирования везде.
- Можно просто `grad` вместо `grad.toDouble()`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    var min: Int = (hoursArrive - hoursDepart) * 60 + (minutesArrive - minutesDepart)
* Система типов Котлина выведет тип переменной автоматически
* Данная переменная может быть объявлена как `val`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = ((1+percent.toDouble()/100)*(1+percent.toDouble()/100)*(1+percent.toDouble()/100) * initial.toDouble())
* Повторно вычисляемые выражения лучше вынести в отдельную переменную
* Вместо `a.toDouble() / 42` обычно делают `a / 42.0` при необходимости вычислений с плавающей запятой

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((age % 10 == 1) && (age / 10 != 1) && (age / 10 != 11)) {
Данное выражение лучше оформить как `when`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var ss1: Double = v1 * t1
* Система типов Котлина выведет тип переменной автоматически
* Данная переменная может быть объявлена как `val`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val s2 = (((ss1) + (ss2) + (ss3)) / 2)
Скобки вокруг одинарной переменной излишни

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (s2 <= ss1) {
Данное выражение лучше оформить как `when`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var rook1: Boolean = (kingX == rookX1 || kingY == rookY1)
* Система типов Котлина выведет тип переменной автоматически
* Данная переменная может быть объявлена как `val`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        rook1 == false && rook2 == false -> 0
Можно проще как `!rook1 && !rook2`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var Bbishop: Boolean = abs(kingX - bishopX) == abs(kingY - bishopY)
* Почему такие странные имена переменных?
* См. замечания выше

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Оператор `when` пишется немного не так (вы уже использовали правильную форму выше по коду). Посмотрите на примеры в главе 2 и разберитесь, как можно упростить данную "лестницу".

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (d >= b) {
Весь этот `if` можно записать как один плоский оператор `when`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    var min: Int
Вы два раза выполняете одинаковые действия в двух разных функциях. В таких случаях обычно делают вспомогательную функцию, которую и используют при необходимости.

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun NOD(m: Int, n: Int): Int {
`GCD`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..min) {
Зачем при поиске наибольшего общего делителя перебирать делители от минимального к максимальному?

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            k = i
Почитайте про алгоритмы поиска НОД, которые работают быстрее полного перебора

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun squareBetweenExists(m: Int, n: Int): Boolean = m <= sqr(sqrt(n.toDouble()).toInt().toDouble()) && sqr(sqrt(n.toDouble()).toInt().toDouble()) <= n
* Повторно используемые выражения лучше вынести в отдельные переменные
* Для округления лучше использовать специальные функции из пакета `Math`: `round / floor / ceil`

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    (n..number - 1).forEach { numberi -> result = result / 10 }
Изменять внешнюю переменную в лямбде --- **очень плохой** стиль. В данном случае лучше воспользоваться обычным циклом `for`.

2016-10-03 08:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    (n..number - 1).forEach { i -> result = result / 10 }
Изменять внешнюю переменную в лямбде --- очень плохой стиль. В данном случае лучше воспользоваться обычным циклом for.

2016-10-04 07:25 UTC, StarKRE commented on src/lesson3/task1/Loop.kt
> +fun NOD(m: Int, n: Int): Int {
А что такое GCD?

2016-10-04 09:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun NOD(m: Int, n: Int): Int {
GCD = greatest common divisor

2016-10-04 14:12 UTC, StarKRE commented on src/lesson1/task1/Simple.kt
> +    var min: Int = (hoursArrive - hoursDepart) * 60 + (minutesArrive - minutesDepart)
min я объявил var, потому что условие изменяет переменную:  =)
 if (min < 0){
        min += 24 * 60
    }

2016-10-04 14:16 UTC, StarKRE commented on src/lesson1/task1/Simple.kt
> +    var min: Int = (hoursArrive - hoursDepart) * 60 + (minutesArrive - minutesDepart)
Не подскажите, почему возникает фатальная ошибка IDE internal error occured?

2016-10-04 14:42 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    var Bbishop: Boolean = abs(kingX - bishopX) == abs(kingY - bishopY)
Имена заданы исходя из моих соображений: =)
Bbishop - boolean bishop
Brook -boolean rook

2016-10-04 14:46 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +        rook1 == false && rook2 == false -> 0
О, круто спасибо)

2016-10-04 14:48 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    return when {
Согласен, Перемудрил немного...

2016-10-04 15:14 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    var min: Int = (hoursArrive - hoursDepart) * 60 + (minutesArrive - minutesDepart)
А можно поподробнее об ошибке? Скриншот или копию описания?

2016-10-04 15:14 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var Bbishop: Boolean = abs(kingX - bishopX) == abs(kingY - bishopY)
А почему тогда все остальные имена не имеют префикса в соответствии с их типами?

2016-10-04 15:26 UTC, StarKRE commented on src/lesson3/task1/Loop.kt
> +fun NOD(m: Int, n: Int): Int {
Понял)

2016-10-04 19:22 UTC, ice-phoenix requested changes

2016-10-04 19:22 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val k: Double = 1 + percent / 100.0
* Система типов Котлина выведет тип переменной автоматически

2016-10-04 19:22 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +fun minBiRoot(a: Double , b: Double , c: Double): Double {
Почему такое странное форматирование? Где-то пробел перед запятой, где-то вообще без пробела, где-то он после? Код должен быть оформлен единообразно везде и всюду.

2016-10-04 19:22 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val ss1: Double = v1 * t1
* Система типов Котлина выведет тип переменной автоматически

2016-10-04 19:22 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Отформатировать его еще бы нормально, и совсем хорошо станет!

2016-10-04 19:22 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        return when {
А нельзя `if` объединить со вложенными `when`?

2016-10-04 19:22 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun NOD2(m: Int, n: Int): Int{
Все-таки эту функцию лучше назвать `gcd`

2016-10-04 19:22 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> + return list.sum() / list.size
Про форматирование кода есть хорошая цитата

> Always code as if the person who ends up maintaining your code is a violent psychopath who knows where you live

Всегда думайте о том, чтобы ваш код не только хорошо и быстро писался (что вас, безусловно, интересует с точки зрения получения зачета и всего подобного), но и хорошо и приятно читался. Нам просто выяснить, где вы живете, если что...

2016-10-05 09:59 UTC, ice-phoenix commented
recheck all

2016-10-05 10:06 UTC, ice-phoenix requested changes

2016-10-05 10:06 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        sum += q2(v[i])
Если вам явно не нужен индекс значения в списке, лучше воспользоваться `foreach` вариантом цикла

```
for (e in list) {
    foo(e)
}
```

2016-10-05 10:06 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if ((list[i]).toInt().toDouble()==list[i]) {
Зачем нужна эта проверка???

2016-10-05 10:06 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            list[i] = sumnumb(list[i].toInt())
`accumulate` должен делать немножко не это

2016-10-05 10:06 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            s /= i
Подумайте, как ваш код будет работать для `n = 3`

2016-10-05 10:54 UTC, mglukhikh commented
recheck all

2016-10-06 11:21 UTC, ice-phoenix requested changes
Убедительная просьба перед продолжением решения задач исправить предыдущие замечания

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun sqRoot(a: Double,b: Double,c: Double) = (-b + sqrt(discriminant(a,b,c))) / (2 * a)
[Здесь и везде] Форматирование должно быть единообразным. Либо пробелы до запятой, либо пробелы после запятой, либо пробелов вообще нет, --- код должен смотреться одинаково.

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val s2 = ((ss1) + (ss2) + (ss3)) / 2
Лишние скобки вокруг одинарной переменной

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    nor = a + b + c - max - min
Все это можно выразить проще через функцию `max / min` или написав собственную версию с `vararg` (про второй вариант вам придется немножко дополнительно почитать самостоятельно)

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val a = number/1000
Форматирование кода

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var last = 1
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return a shl shift
А можете объяснить, что здесь происходит, своими словами? =)

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (b !== 0)
Вместо `!==` здесь лучше `!=`

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun squareBetweenExists(m: Int, n: Int): Boolean = m <= sqr(floor(sqrt(n.toDouble()))) && sqr(floor(sqrt(n.toDouble())))  <= n
Повторно вычисляемое выражение лучше вынести в отдельную переменную

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var sin: Double = x
* Система типов Котлина выведет тип переменной автоматически

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var cos: Double = 1.0
* Система типов Котлина выведет тип переменной автоматически

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val maincipher = n % 10
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        numberi ++
Форматирование кода

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +import lesson3.task1.revert
Зачем вам здесь этот импорт?

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var sum: Double = 0.0
* Система типов Котлина выведет тип переменной автоматически

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var min: Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        min = b.size - 1
Можно воспользоваться функцией `min`

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (i >= s) break
Это условие можно убрать в условие продолжения выполнения цикла

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return list
Лучше `list.reversed()`

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: MutableList<Int> = convert(n, base).toMutableList()
* Система типов Котлина выведет тип переменной автоматически

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var str = list2.joinToString("")
Можно сразу вернуть результат операции без сохранения его в новую переменную

2016-10-06 11:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0..list.size - 1) {
Все это можно сделать при помощи функции `map` в 1-2 строчки

2016-10-06 11:21 UTC, ice-phoenix commented on test/lesson2/task1/Tests.kt
> +    fun rokOrBishopThreatens() {
Менять имена тестов --- не очень хорошая идея

2016-10-12 10:13 UTC, ice-phoenix commented
Перед тем, как будет проверен урок 4, исправьте замечания к предыдущим урокам (см. вкладку `Files changed`)

2016-10-12 10:37 UTC, StarKRE commented on test/lesson2/task1/Tests.kt
> +    fun rokOrBishopThreatens() {
Случайно

2016-10-12 10:41 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +    return list
Ругается: Found Unit

2016-10-12 10:45 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +import lesson3.task1.revert
Хотел сделать одно задание через revert , но воспользовался reverse

2016-10-17 11:32 UTC, ice-phoenix commented
Еще раз напомню, что пока вы не исправите предыдущие замечания к вашим урокам (см. вкладку `Files changed`), ваши решения уроков 4 и 5 не будут проверятся.

2016-10-18 17:36 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +            list[i] = sumnumb(list[i].toInt())
?

2016-10-18 18:45 UTC, StarKRE commented on src/lesson2/task2/Logical.kt
> +    var min: Int
я правда не знаю, как написать функцию для трех, т.е не три функции min nor max, f одну для трех

2016-10-18 18:47 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +        return when {
Подскажите, пожалуйста, комбинацию клавиш для форматирования всей страницы или выделенного текста. Можно, только почему не желательно делать иерархическое ветвление?)

2016-10-18 19:03 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +            list[i] = sumnumb(list[i].toInt())
Я понял ошибку, которая в функции sumnumb

2016-10-18 19:43 UTC, StarKRE commented on src/lesson3/task1/Loop.kt
> +    return a shl shift
Признаюсь, нашел функцию в интернете переписал на Kotlin. Тут происходят сдвиги разрядов чисел в двоичной системе. shl - сдвиг битов влево, а shr - вправо. Не понятно только как выполняется это условие: (a and 1 == 0)

2016-10-20 11:18 UTC, ice-phoenix requested changes
Исправляем все замечания и работаем дальше

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val x1x2 = quadraticRootProduct(1.0, - 3.0, 2.0)
Почему внезапно форматирование отрицательных чисел стало таким странным?

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (y3<0.0) return Double.NaN // 6
Здесь тоже почему-то форматирование стало не соответствовать общему стилю

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val ss1=v1 * t1
Форматирование должно быть единообразным везде. Если вы отделяете операции пробелами, делайте это для всех операций, пожалуйста. Можете попробовать отформатировать ваш код при помощи IntelliJ IDEA и посмотреть, как это должно бы выглядеть.

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX) || (kingY == rookY)) && (minusX != minusY)) return 1
- Вынести в отдельные переменные факты атаки короля ладьей или слоном (как вы сделали в `whichRookThreatens`)
- Данное выражение лучше оформить как `when`

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    nor = a + b + c - max - min
Почему бы просто не воспользоваться `Math.max / Math.min`???

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    var min: Int
Хорошо, этому вы действительно научитесь несколько позже. Тогда поправьте код с использованием `Math.max / Math.min`.

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return a shl shift
Если вы взяли этот алгоритм из интернета и *не разобрались*, как он работает, я его у вас не приму. Либо разбирайтесь в том, что делают все эти сдвиги, и за счет чего они находят НОД, либо используйте алгоритм, который вы сможете разобрать.

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return m <= square && square <= n
А вот это хорошо, один из самых кратких и эффективных способов решить эту задачу!

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        } else cos += number
Скобки вокруг тела `else`

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = 0
Нет ли у вас функции, которая уже делает ровно это?

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            list[i] = - element
Странное форматирование наносит ответный удар

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    (0..v.size - 1).forEach { i -> sum += q2(v[i]) }
Менять внешнюю переменную внутри лямбда-функции --- **очень плохой стиль**. Тут лучше воспользоваться старым добрым циклом `for`.

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (i >= s) break
Почему бы эту проверку не убрать в условие `while`?

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list2 = mutableListOf<Char>()
`res`

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        number += digits[i] * Math.pow(base.toDouble(), digits.size.toDouble() - i - 1)
Лучше сделать `pow`, работающий в `Int`

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list = listOf()
Почему определение переменной отделено от объявления?

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val str1 = str
Зачем???

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: List<Int>
Почему вы где-то используете изменяемый список в `val`,  а где-то неименяемый список в `var`?

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (str1[i] in '0'..'9') list += ((str1[i]).toInt() - 48)
Вместо 48 и 87 лучше использовать соответствующие символы

2016-10-20 11:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            else result = parts[0].toInt().toString() + "."
Повторно используемые выражения лучше вынести в отдельные переменные

2016-10-20 11:19 UTC, ice-phoenix commented
recheck all

2016-10-25 20:25 UTC, StarKRE commented on src/lesson3/task1/Loop.kt
> +    return a shl shift
Я разобрался:
1. Проверяем, если одно из 2-х чисел равно 0 -> выводим второе, даже если бы a = 0 и b = -3, то все-рано выводим b, на ноль нельзя делить.
2. Цикл: Пока Суммы битных разрядов умножаются "побитно" на 1 равно 0, то делаем цикл:
Сдвигаем в дв. системе счисления на один разряд вправо в обоих числах.
3. В следующем цикле сдвигаем вправо теперь только число a.
4.  А вот  тело do{...} интересное: сначала мы запускаем цикл пока b != 0, в теле находится еще один подцикл, с помощью которого мы аналогично сдвигаем вправо биты числа b. Условие: if (abs(a) > abs(b)) {
            val t = abs(b)
            b = abs(a)
            a = t
        }
b -= abs(a)
сравнивает, какое число больше, если a > b -> поменяли местами, иначе ничего делать не нужно; вычли из b число а. (Я немножко усовершенствовал и написал модули, чтобы эта функция работала и для отрицательных чисел. Например, а < 0, b > 0 и т. д.) 
5. После цикла у нас b должно быть равняться 0 и число а shl (Сдвиг Влево) - это и будет НОД. =) Чуть-чуть попозже сделаю Commit

2016-10-25 20:25 UTC, StarKRE commented on src/lesson3/task1/Loop.kt
> +    return m <= square && square <= n
Спасибо =)

2016-10-25 20:54 UTC, StarKRE commented on src/lesson3/task1/Loop.kt
> +    var k = 0
Вы имеете ввиду написать функцию, которая работает быстрее?

2016-10-25 21:21 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +    val list2 = mutableListOf<Char>()
Не понял

2016-10-25 21:23 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +        number += digits[i] * Math.pow(base.toDouble(), digits.size.toDouble() - i - 1)
Нужно свою функцию возведения написать в виде цикла для Int?

2016-10-25 21:26 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +        if (i >= s) break
Тут нельзя, иначе получается бесконечный цикл

2016-10-28 00:47 UTC, StarKRE commented
Подскажите, пожалуйста, что делать, если bestLongJump и mostExpensive не проходят через ваш компилятор? (Согласен вопрос немного странноватый, но дочитайте, пожалуйста) Я беру входные значения теста, через который не прошла foo bestLongJump добавляю в локальные тесты в Idea к себе, и все работает. Foo most expensive вообще нельзя проверить локально, так как такой формат входных данные не допустим, потому что имя товара состоит из любых символов кроме пробела (насколько я понял, но могу ошибаться, конечно). Как добиться положительного результата?

2016-10-28 13:49 UTC, ice-phoenix commented
К сожалению, форматирование GitHub удаляет множественные пробельные символы. Попробуйте запустить ваше решение на примере вида `- %   % 1`.

2016-10-28 14:46 UTC, ice-phoenix requested changes

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        age % 10 > 1 && age % 10 < 5 && age / 10 != 1 && age / 10 != 11 -> "$age года"
Можно проще через `a in 1..5`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val s2 = ((ss1) + (ss2) + (ss3)) / 2
Лишние скобки вокруг отдельных переменных

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val ROOK1 = (kingX == rookX1 || kingY == rookY1)
В Котлине принято называть переменные `camelCase`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +fun MaxofThree(a: Double, b: Double, c: Double): Double {
`camelCase`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +fun MinofThree(a: Double, b: Double, c: Double): Double{
`camelCase`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +fun MediumofThree(a: Double, b: Double, c: Double): Double = a + b + c - MinofThree(a,b,c) - MaxofThree(a,b,c)
`camelCase`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (d >= b) {
Ап

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        return when {
Все эти условия можно упростить

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +                 x2: Double, y2: Double, r2: Double): Boolean  = r1 <= r2 && Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) <= r2-r1
Длинные строки обычно разделяют на несколько строк поменьше, здесь, например, можно перенести строку после знака `=`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun MaxofThree(a: Int, b: Int, c: Int): Int {
Зачем еще раз реализовывать функции, которые вы уже реализовали ранее?

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val nor = MediumofThree(a,b,c)
Форматирование кода

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +}
Вы, конечно, описали путем дословного изложения, что делает этот код. А что он делает "по сути"? Почему он работает? За что логически отвечают различные циклы в данном коде?

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (m * n) / gcd(m, n)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i = n - 1
Нет ли более точной верхней границы для возможных делителей числа, чем `n - 1`?

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number: Double = x
* Система типов Котлина выведет тип переменной автоматически

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        } else {sin += number}
Форматирование кода

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        } else {cos += number}
Форматирование кода

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number: Double = x
* Система типов Котлина выведет тип переменной автоматически

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = 0
Я имею в виду функцию, которая делает ровно то же самое, что делает функция `count`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun q2(g: Double) = g * g
Можно было обойтись и без этой функции

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0..v.size - 1) {
Лучше цикл в foreach стиле
```
for (e in list) {
    foo(e)
}
```

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var sum: Double = 0.0
* Система типов Котлина выведет тип переменной автоматически

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (i >= s) break
Почему, если убрать эту проверку вместо `s > 0` в первом `while`, получится бесконечный цикл?

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list2 = mutableListOf<Char>()
Это переменную лучше назвать `res`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun powInt(a: Int, b: Int): Int {
`pow`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    (1..b).forEach { i -> result *= a }
Это лучше заменить на старый добрый цикл `for`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: List<Int> = listOf()
* Система типов Котлина выведет тип переменной автоматически

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (str1[i] in '0'..'9') list += ((str1[i]).toInt() - '0'.toInt())
`toInt()` можно вынести за скобки

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var result = ""
`StringBuilder` или список строк

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (day in 0..9) result = '0' + day.toString() + "."
`String.padStart()`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            else result = day.toString()
Так чему в итоге равен `result`?

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var result = ""
`StringBuilder` или список строк

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val phoneResult = Regex("""(\+\d+)?(\(\d+\))?\d+""")
Лучше незахватывающие группы, а так все хорошо =)

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val parts = jumps.split(" ")
Проверьте ваше решение на строках, в которых встречаются несколько пробелов подряд

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        val jumpRegular = Regex("""\d+(\+|\%|\-)+""")
Лучше воспользоваться классом символов `[...]`

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var count = 0
Зачем вам эта переменная?

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..parts.size - 1 step 2) {
Подумайте про допустимые границы итерирования здесь

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val sumstr = Regex("""((\d+\ +(\+|\-)\ +)+)?\d+""")
* Класс символов `[...]`
* Вместо явного пробела лучше использовать `\s`
* Незахватывающие группы

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (parts.size == 1) return expression.toInt()
Почему не просто `return sum`?

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                if (parts[i + 1] == '+'.toString()) {
Зачем `'+'.toString()`, а не `"+"`?

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if ((parts[i] == parts[i + 1]) && (parts[i] != "")) {
Все пустые строки лучше сперва отфильтровать

2016-10-28 14:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val priseRegex = Regex("""\S+\ \d+\.\d+((\;\ \S+\ \d+\.\d+)+)?""")
`priceRegex` + `\s`

2016-11-01 15:36 UTC, StarKRE commented on src/lesson3/task1/Loop.kt
> +    var i = n - 1
Нет, потому что функция Int, в задании написано максимальный делитель меньше n

2016-11-01 15:42 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +fun q2(g: Double) = g * g
Нет в java.lang.Math.* foo sqr

2016-11-01 15:48 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +fun powInt(a: Int, b: Int): Int {
Вы же сами попросили написать foo pow для Int

2016-11-01 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun powInt(a: Int, b: Int): Int {
Да, и называться эта функция должна `pow`

2016-11-01 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun q2(g: Double) = g * g
Можно было просто написать `it * it` по месту использования

2016-11-01 15:56 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +fun powInt(a: Int, b: Int): Int {
ice-phoenix 4 days ago contributor
Почему, если убрать эту проверку вместо s > 0 в первом while, получится бесконечный цикл?

Потому что внутренний цикл остановится, а s всегда будет больше 0

2016-11-01 15:57 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i = n - 1
Отлично, давайте думать. Выпишите пожалуйста дома в свободное время на бумажке в столбик все числа от 1 до 100, а рядом --- их максимальные делители. Посмотрите на то, что получилось, и подумайте, может быть, все же есть более точная верхняя граница?

2016-11-01 15:59 UTC, StarKRE commented on src/lesson4/task1/List.kt
> +    var list: List<Int> = listOf()
Ругается, если убираю List<Int>

2016-11-01 16:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (i >= s) break
> Потому что внутренний цикл остановится, а s всегда будет больше 0

Еще раз, мы эту проверку уносим во внешний цикл, т.е. делаем
```
while (i < s) {
    while (s % i == 0) {
        ...
    }
    ...
}
```
Почему это не работает?

2016-11-01 16:02 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: List<Int> = listOf()
Вы не пробовали читать, как именно он ругается? Скорее всего, он ругается, что не может вывести тип элемента списка. В этом случае ему можно подсказать при помощи `listOf<Int>()`.

2016-11-01 16:27 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +            else result = day.toString()
Строке, состоящей из числа, месяца и года

2016-11-01 16:28 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +    val phoneResult = Regex("""(\+\d+)?(\(\d+\))?\d+""")
Поясните, пожалуйста, что значит незахватывающие группы?)

2016-11-01 16:30 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +    var count = 0
maxhigh -наивысший прыжок
count - счетчик, который считает, сколько успешных прыжков

2016-11-01 16:37 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +            if ((parts[i] == parts[i + 1]) && (parts[i] != "")) {
Я не знаю, как отфильтровать пустую строку, ругается, фильтрует только Char

2016-11-02 10:55 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if ((parts[i] == parts[i + 1]) && (parts[i] != "")) {
Отфильтровать `parts` и убрать из него пустые строки

2016-11-02 10:55 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var count = 0
Зачем вам здесь знать, сколько успешных прыжков?

2016-11-02 10:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val phoneResult = Regex("""(\+\d+)?(\(\d+\))?\d+""")
А для этого надо было приходить на лекцию по Regex, сейчас читайте слайды и разбирайтесь при помощи интернета

2016-11-02 10:57 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            else result = day.toString()
Посмотрите внимательно на `if`, на обе его ветки и подумайте, нужен ли он вообще

2016-11-08 16:37 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +    var count = 0
Нужно узнать, есть ли хотя бы 1 успешный прыжок?

2016-11-09 13:54 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var count = 0
Значение наивысшего прыжка не может вам подсказать о том, был или не был успешный прыжок?

2016-11-17 14:28 UTC, ice-phoenix commented
recheck all

2016-11-17 15:07 UTC, ice-phoenix requested changes
Обратите внимание, что некоторые тесты не работают

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        age % 10 in 1..4 && age / 10 != 1 && age / 10 != 11 -> "$age года"
Более правильно `age % 10 in 2..4 && ...`

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val FirstRook = (kingX == rookX1 || kingY == rookY1)
В Котлине принят `camelCase` для именования переменных

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val BishopThreaten = (abs(kingX - bishopX) == abs(kingY - bishopY))
См. замечания выше

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +fun MaxofThree(a: Double, b: Double, c: Double): Double {
Ап

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a > b) {max = a} else {max = b}
Форматирование кода

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a < b) {min = a} else {min = b}
Форматирование кода

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val min = MinofThree(a,b,c)
Форматирование кода

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            else -> d - c
Этот набор условий можно упростить

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = Math.abs(x1-x2) == Math.abs(y1-y2) || x1 == x2 || y1 == y2
Длинные строки в Котлине принято разбивать на несколько более коротких

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        r1 <= r2 && Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) <= r2-r1
Зачем проверять первое условие?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val min = MinofThree(a.toDouble(),b.toDouble(),c.toDouble()).toInt()
Зачем `toInt()`?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +}
Если вы не исправите это замечание, ни одна задача этого урока не будет зачтена в конце семестра

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n % i == 0) {
Зачем эта проверка???

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        return n / i
Почему бы не переиспользовать функцию `minDivisor`?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(number) * 1000 > eps) {
Зачем умножать на 1000?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(number) * 1000 > eps) {
См. выше

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = 0
Это все еще в силе

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    result = numberi * numberi
Почему вы разделили определение и объявление этой переменной?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    result = fib(numberi)
См. выше

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    (0..v.size - 1).forEach { i -> sum += (v[i] * v[i]) }
Изменять переменную внутри лямбды --- не очень хороший стиль. Лучше использовать старый добрый цикл `for`.

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty())
Зачем данная проверка?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (i >= s) break
Итак?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list = convert(n, base).toMutableList()
Зачем `toMutableList()`?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        for (i in 0..list.size - 1) {
Если вам не нужен индекс, лучше использовать цикл в `foreach` стиле

```
for (e in list) {
    foo(e)
}
```

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun powInt(a: Int, b: Int): Int {
Это замечание все еще в силе

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    (1..b).forEach { i -> result *= a }
Ап

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list = listOf<Int>()
Почему вы где-то используете `var a: List<Int>`, а где-то `val b: MutableList<Int>`?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0..str1.length - 1)
`foreach`

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var StringBuilder = ""
Вообще-то, имелось в виду, что (как и выше) для операции собирания строки из составных частей лучше использовать `StringBuilder` или список строк

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (day in 0..9) StringBuilder = '0' + day.toString() + "."
Почитайте про `String.padStart`

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        throw NumberFormatException("IllegalArgumentException")
Какое исключение свидетельствует об ошибке формата строки?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (parts.size == 1) return sum
Зачем эта проверка?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if ((parts[i] == parts[i + 1]) && (parts[i] != "")) {
Ап

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +                    maxdistance = points[i].distance(points[index])
Повторно используемые выражения следует вынести в отдельные переменные

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            (Math.cos(angle) == Math.cos(Math.PI / 2)) -> point.x
Может быть, вместо косинусов можно сравнивать сам угол?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var NearestCircle1 = circles[0]
`camelCase`

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var mindistance = (circles[0].center.distance(circles[1].center)).toDouble() - circles[0].radius - circles[1].radius
Зачем `toDouble()`?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun circleByThreePoints(a: Point, b: Point, c: Point): Circle = Circle(bisectorByPoints(a, b).crossPoint(bisectorByPoints(a, c)),
Повторно используемые выражения следует вынести в отдельные переменные

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            notation[0] in 'a'..'h' && notation[1] in '1'..'8' && notation.length == 2 ->
Почему вы длину строки проверяете после того, как воспользовались ее элементами?

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            (start.column == end.column).xor(start.row == end.row) -> 1
Лучше использовать логические операции вместо аналогичных функций

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            rookMoveNumber(start, end) == 2 -> listOf(start, Square(start.column, end.row), end)
Лучше `when (rookMoveNumber(start, end)) { ... }`

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val MoveList = mutableListOf<Square>(start)
`camelCase`

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> + if (StartX == StartY) return MoveList
Форматирование кода

2016-11-17 15:07 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    var StartX = start.column
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-17 15:08 UTC, ice-phoenix commented
recheck all

2016-11-23 09:39 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +    val FirstRook = (kingX == rookX1 || kingY == rookY1)
я исправлю, но camelCase и kotlinFirst и KotlinFirst =)

2016-11-23 09:50 UTC, StarKRE commented on src/lesson3/task1/Loop.kt
> +}
Я рассказал Михаилу Игоревичу на уроке практики, как это все работает, и он засчитал =)
(Гулькин Игорь)

2016-11-23 10:01 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +}
Я подтверждаю, что такой разговор действительно имел место 👍 Игорь действительно понимает, как этот код работает.

2016-11-23 10:07 UTC, StarKRE commented on src/lesson2/task1/IfElse.kt
> +            else -> d - c
Вы имеете ввиду вынести буленовские переменные?

2016-11-23 10:15 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            else -> d - c
Нет, я имею в виду, подумать, как можно все это записать намного компактнее =)

2016-11-23 10:15 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +}
:+1:

2016-11-23 10:16 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val FirstRook = (kingX == rookX1 || kingY == rookY1)
Вы не путайте именование переменных и именование, например, классов или проектов. `KotlinFirst` --- это все же не переменная, а название нашего учебного проекта.

2016-11-23 12:16 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +    val parts = jumps.split(" ")
честно: работает =)

2016-11-23 12:17 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +    val parts = jumps.split(" ")
но я подумаю, и все-равно попозже перепишу =)

2016-11-23 12:18 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +    var count = 0
Понял, максимально взятую высоту)

2016-11-23 13:10 UTC, StarKRE commented on src/lesson6/task1/Geometry.kt
> +fun circleByThreePoints(a: Point, b: Point, c: Point): Circle = Circle(bisectorByPoints(a, b).crossPoint(bisectorByPoints(a, c)),
Хорошо, а как сделать и через равно, и вынести отдельные переменные

2016-11-23 13:19 UTC, StarKRE commented on src/lesson6/task2/Chess.kt
> +            notation[0] in 'a'..'h' && notation[1] in '1'..'8' && notation.length == 2 ->
вдруг входные файлы e4rt?

2016-11-23 13:22 UTC, StarKRE commented on src/lesson6/task2/Chess.kt
> +            rookMoveNumber(start, end) == 2 -> listOf(start, Square(start.column, end.row), end)
Согласен)

2016-11-24 12:28 UTC, ice-phoenix commented
recheck all

2016-11-24 13:09 UTC, ice-phoenix requested changes

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val SecondRook = (kingX == rookX2 || kingY == rookY2)
`camelCase`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (c > max){
Форматирование кода

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (c < min){
Форматирование кода

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +fun maxofThree(a: Double, b: Double, c: Double): Double {
`camelCase`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (n % i != 0) i ++
Форматирование кода

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun maxDivisor(n: Int): Int = n / minDivisor(n)
:+1:

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +   var result = numberi * numberi
Форматирование кода

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        fun center(list: MutableList<Double>): MutableList<Double> {
Что ж здесь такое с форматированием кода произошло???

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val factorazeList = mutableListOf<Int>()
`factorizeList`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list = convert(n, base).toList()
Зачем `toList()`???

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val resListChar = mutableListOf<Char>()
Можно просто `res`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            when {
Форматирование кода

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                parts[0].toInt() > 32 -> return ""
Если вы проверяете это, то почему не проверяете корректное число дней в каждом месяце?

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val phonefilter = phone.filter { it != ' ' && it != '-' }
`camelCase`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val phoneResult = Regex("""(?:\+\d+)?(\(\d+\))?\d+""")
Почему одна группа незахватывающая, а вторая --- нет?

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val phonefilter = phone.filter { it != ' ' && it != '-' }
Проще через `it in "..."`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        for (i in 0..listOfWords.size - 2) {
Форматирование

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    }
Почему бы вместо всего этого цикла не сделать простой `filter`?

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            for (index in (i + 1)..points.size - 1) {
Общепринято называть второй индекс во вложеном цикле как `j`,  а не `index`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun circleByDiameter(diameter: Segment): Circle = Circle(Point((diameter.begin.x + diameter.end.x) / 2,
Форматирование кода (вообще непонятно, где аргументы `Circle`, а где --- `Point`)

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        (a.y + b.y) / 2), Math.atan((b.y - a.y) / (b.x - a.x)) + Math.PI / 2)
См. выше про форматирование

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var minDistance = circles[0].center.distance(circles[1].center) - circles[0].radius - circles[1].radius
Нет ли у вас уже готовой функции, которая считает расстояние между окружностями?

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +                val LengthCircles = circles[i].distance(circles[index])
`camelFunkingCase`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            for (index in (i + 1)..circles.size - 1) {
`j`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var nearestCircle2 = circles[1]
Почему вы проверяете количество окружностей уже после того, как считаете, что их как минимум две?

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            else -> throw IllegalArgumentException("IllegalArgumentException")
Что будет, если вашему коду подать на вход `"a1b"`?

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +                Square((notation[0] - 'a').toInt() + 1, notation[1].toString().toInt())
Вместо `toString().toInt()` лучше сделать напрямую над `Char`

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            , end)
Форматирование кода

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        Math.abs(start.row - end.row) )
Форматирование кода

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> + if (kingX == kingY){
Что же опять с форматированием кода случилось???

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val distanceRow = end.row - start.row >= 0
Через функцию `compareTo` все это получится намного короче

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            when{
Форматирование кода

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +import java.sql.Array
Зачем?

2016-11-24 13:09 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        return matrix
На всякий случай, напоминаю про психопата, который знает, где вы живете и который очень не любит, когда кто-то плохо форматирует свой код

2016-11-24 22:15 UTC, StarKRE commented
Как избежать погрешность в задании Impossible minContainingCircle, и почему foo diameter использует тип Array<PointsOut> вместо Point

2016-11-25 10:19 UTC, StarKRE commented
Марат Халимович, подскажите, пожалуйста, (спрашивать больше не у кого) тест:
assertFalse(isLatinSquare(createMatrix(2, 2, listOf(listOf(1, 2), listOf(1, 2))))) 
- ничего не выводит...
Мы проверяем сначала в столбиках уникальность значений, а затем в рядах.
Код непосредственно:
fun isLatinSquare(matrix: Matrix<Int>): Boolean {
    if (matrix.height != matrix.width) {
        throw IllegalArgumentException("IllegalArgumentException")
    } else {
        for (i in 0..matrix.width - 1) {
            for (j in 0..matrix.height - 1) {
                for (k in 0..matrix.height - 1) {
                    if (j != k && matrix[i, j] == matrix[i, k] ||
                            matrix[i, j] !in 1..matrix.width) {
                        return false
                    }
                }
            }
        }

        for (l in 0..matrix.height - 1) {
            for (m in 0..matrix.width - 1) {
                for (n in 0..matrix.width - 1) {
                    if (m != n && matrix[l, m] == matrix[l, n] ||
                            matrix[l, m] !in 1..matrix.width) {
                        return false
                    }
                }
            }
        }
        return true
    }
}

2016-11-25 10:20 UTC, StarKRE commented
fun isLatinSquare(matrix: Matrix<Int>): Boolean {
    if (matrix.height != matrix.width) {
        throw IllegalArgumentException("IllegalArgumentException")
    } else {
        for (i in 0..matrix.width - 1) {
            for (j in 0..matrix.height - 1) {
                for (k in 0..matrix.height - 1) {
                    if (j != k && matrix[i, j] == matrix[i, k] ||
                            matrix[i, j] !in 1..matrix.width) {
                        return false
                    }
                }
            }
        }
        for (l in 0..matrix.height - 1) {
            for (m in 0..matrix.width - 1) {
                for (n in 0..matrix.width - 1) {
                    if (m != n && matrix[l, m] == matrix[l, n] ||
                            matrix[l, m] !in 1..matrix.width) {
                        return false
                    }
                }
            }
        }
        return true
    }
}

2016-11-26 19:41 UTC, ice-phoenix reviewed
Ответил на ваши вопросы. В остальном, осталось очень много старых замечаний, поэтому новый код смотреть пока не буду.

2016-11-26 19:41 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun diameter(vararg points: Point): Segment {
По поводу того, как вызывать vararg-функции и что они из себя представляют, --- let me google it for you: https://kotlinlang.org/docs/reference/functions.html#variable-number-of-arguments-varargs

2016-11-26 19:41 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var PointTriangleA = Point(0.0, 0.0)
`camelCase`

2016-11-26 19:41 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        var maxSegment = PointTriangleA.distance(PointTriangleB)
Подобный код лучше записывать как
```
if (errorCond0) throw Bla
if (errorCond1) return Foo
if (errorCond2) return Bar
// В этом месте все уже точно в порядке, и можно просто считать что надо
var maxSegment = ...
```

2016-11-26 19:41 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            val TriangleSquareOfPoints = Triangle(PointTriangleA, PointTriangleB, points[i]).area()
Почему вы внезапно считаете, что площадь треугольника является хорошей мерой того, решает ли он задачу или нет?

2016-11-26 19:47 UTC, ice-phoenix reviewed
И про `isLatinSquare`

2016-11-26 19:47 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +fun isLatinSquare(matrix: Matrix<Int>): Boolean {
Подумайте внимательно, как именно вы бегаете по матрице в двух циклах ниже. Нарисуйте картинку и пройдитесь по вашему алгоритму шаг за шагом. Должно помочь понять, где у вас ошибка.

2016-11-26 19:47 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                if ((matrix[i, j] == matrix[i, k] && j != k) ||
Все это можно сделать намного проще через `Set`

2016-11-26 19:47 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    for (l in 0..matrix.height - 1) {
Можно было снова назвать переменные как `i / j / k`, а не запутывать вероятного читателя вашего кода новыми обозначениями

2016-11-30 11:12 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +                parts[0].toInt() > 32 -> return ""
действительно, а почему бы и нет =)

2016-11-30 11:49 UTC, StarKRE commented on src/lesson6/task2/Chess.kt
> +    val distanceRow = end.row - start.row >= 0
Я в общем понял, что это делает... Например: return "Kotlin".compareTo(KotlinAsFirstn) выведет -7?

2016-11-30 11:59 UTC, StarKRE commented on src/lesson6/task1/Geometry.kt
> +            val TriangleSquareOfPoints = Triangle(PointTriangleA, PointTriangleB, points[i]).area()
Наверно, все-таки это не очень хорошая идея, для тупоугольного треугольника... Подумаю еще =)

2016-11-30 14:50 UTC, StarKRE commented on src/lesson6/task1/Geometry.kt
> +            val TriangleSquareOfPoints = Triangle(PointTriangleA, PointTriangleB, points[i]).area()
Ура, получилось!!!!!!!!!!!! =)

2016-12-09 14:22 UTC, ice-phoenix commented
recheck all

2016-12-16 10:25 UTC, ice-phoenix commented
Так вас проверять или как? =)

2016-12-16 10:25 UTC, ice-phoenix commented
recheck all

2016-12-16 10:26 UTC, ice-phoenix commented
recheck all

2016-12-16 11:04 UTC, ice-phoenix commented
recheck all

2016-12-16 22:20 UTC, StarKRE commented
Подскажите, пожалуйста, работал на другом компьютере, склонировал репозиторий с GitHub, при push ошибка: Failed with error: fatal: unable to access 'https://github.com/StarKRE/KotlinAsFirst2016.git/': The requested URL returned error: 403

2016-12-17 21:18 UTC, mglukhikh commented
Возможно, логин / пароль неверные или что-то не так в этот момент было с Интернет

2016-12-18 19:58 UTC, ice-phoenix commented
recheck all

2016-12-18 20:35 UTC, ice-phoenix requested changes

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = ((number % 10) * 100) + ((number / 100)) + (number - ((number / 100) * 100) - (number % 10))
Длинные строки не есть очень хорошо

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var min= 0.0
Форматирование, ну е-мое!

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            else -> d - c
Все еще актуально

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number = x % (2 * Math.PI)
Может быть, можно не считать два раза одно и то же?

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        fun center(list: MutableList<Double>): MutableList<Double> {
Неужели так сложно исправить форматирование было, е-мое???

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                parts[1] == "января" && parts[0].toInt() < 32 -> ".01."
* Мне кажется, число следовало вынести в отдельную переменную
* А почему вы не проверяете на отрицательные числа?

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                return ""
А тут внезапно лень-матушка и числа месяцев не проверяем для каждого месяца. А-тя-тя...

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var count = 0
Похоже, все-таки не поняли

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IndexOutOfBoundsException){
Этого исключения быть не должно

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        listOfWords.add(part)
Чем вас оригинальный список слов не устроил, ммм? Зачем перекладывать???

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            val prise = parts[i].filter { it != ';' }.toDouble()
Очень странный способ убрать `;`, можно лучше

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                max = prise
`price`

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        Point(
Форматирование кода

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var maxdistance = point1.distance(point2)
`camelCase`

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        Point(
Форматирование кода

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        var minDistance = circles[0].center.distance(circles[1].center) - circles[0].radius - circles[1].radius
Может быть, это расстояние можно посчитать проще?

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        val TriangleSquareOfPoints = Triangle(pointTriangleA, pointTriangleB, points[i]).area()
`camelCase` + почему вы продолжаете считать площадь треугольника хорошей мерой для решения данной задачи?

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        if ((Math.abs(end.column - start.column) + Math.abs(end.row - start.row)) % 2 == 1) {
Зачем проверять это здесь? Вы же ниже используете функцию `bishopMoveNumber`, которая и так это вам проверит.

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            bishopMoveNumber(start, end) == -1 -> listOf()
Повторно используемые вызовы функций следует выносить в отдельные переменные

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +} catch (e: IndexOutOfBoundsException){
Этого исключения быть не должно

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val distanceRow = end.row - start.row >= 0
Можно прямо еще проще...

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            sqr(end.row - start.row) + sqr(end.column - start.column) == 85 -> 5
Я этого не видел.

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +    if (height <= 0 || width <= 0)
Это супер, мы сначала все сделали, а потом проверили, можно ли было это делать!

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        return true
Вы хотя бы научились пользоваться авто-генерацией из Идеи, уже неплохо...

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            j = k
А почему бы просто не поиспользовать переменную `k` здесь и выше???

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            i = k
См. выше...

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +fun isLatinSquare(matrix: Matrix<Int>): Boolean {
Решили не думать внимательно. Тоже вариант!

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    val NeighboursMatrix = matrix // создание расширенной и преобразованной матриц
`camelCase`

2016-12-18 20:35 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    val extendedMatrix = createMatrix<Int>(matrix.height + 2, matrix.width + 2, 0)
А вот это неплохой трюк

2016-12-18 20:38 UTC, ice-phoenix commented
recheck all

2016-12-18 20:40 UTC, ice-phoenix commented
Несмотря на то, что вы выполнили формальные требования на оценку "Отлично", учитывая множественные замечания, ваш стиль написания кода и все еще не работающие тесты к некоторым задачам, мы не можем вам поставить выше "Хорошо". Но и это тоже очень здорово!

2016-12-19 01:04 UTC, StarKRE commented on src/lesson5/task1/Parse.kt
> +                parts[1] == "января" && parts[0].toInt() < 32 -> ".01."
Подскажите, как выносить, если там стоит конъюнкция?

2016-12-19 01:22 UTC, StarKRE commented on src/lesson6/task1/Geometry.kt
> +        var minDistance = circles[0].center.distance(circles[1].center) - circles[0].radius - circles[1].radius
у меня не получилось вставить foo diameter...

2016-12-19 01:27 UTC, StarKRE commented on src/lesson6/task1/Geometry.kt
> +        val TriangleSquareOfPoints = Triangle(pointTriangleA, pointTriangleB, points[i]).area()
потому что max площадь треугольника прямо пропорциональна max высоте (расстоянию - перпендикуляру от третьей дальней точки до max основания).

2016-12-19 01:36 UTC, StarKRE commented on src/lesson7/task2/Matrices.kt
> +            j = k
не понял...

2016-12-21 09:10 UTC, StarKRE commented
recheck all

2016-12-21 15:05 UTC, StarKRE commented
recheck all

2016-12-21 15:15 UTC, StarKRE commented
recheck all

2017-07-26 18:23 UTC, closed without merging