2 урок
Kotlin-Polytech/KotlinAsFirst2016 pull request #153
Opened 2016-09-30 21:40 UTC by malashik35

2016-10-01 19:25 UTC, mglukhikh commented
Как вы видите из сообщений бота, несколько задач решены неверно. Разбирайтесь, причины должны быть достаточно понятны. Бот в Expected выводит ожидаемый им (правильный) результат, в Actual -- реально полученный от вашей функции результат, в Inputs: тот набор значений параметров функции, на котором это произошло.

2016-10-01 19:27 UTC, mglukhikh commented
Со стилем кода тоже много проблем. Я вам советую отформатировать код автоматически с помощью средств IDEA (Ctrl+Alt+L переформатирует код в файле), посмотреть, что получится, и в дальнейшем стараться придерживаться полученного стиля.

2016-10-12 09:51 UTC, mglukhikh commented
Автору PR: вы несколько отстаёте от графика. Вам следует исправить ошибки и имеющиеся замечания по стюлю во 2-м уроке и перейти к решению задач 3-го урока.

2016-10-26 10:19 UTC, mglukhikh requested changes
Замечания к 3-му и 4-му уроку. Не забудьте, пожалуйста, исправить также более ранние замечания к уроку номер 2. Пожалуйста, сделайте это ДО ТОГО, как начнёте решать следующие задачи

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        k = k + 1
Лучше просто k++

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        n1 = n1 / 10
Лучше n1 /= 10

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (n == 2) return 1
if (n <= 2) return 1

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun NOD(a: Int, b: Int): Int {
1. Лучше эту функцию назвать `nod`, а ещё лучше `gcd` (сокращение от greatest common divisor). 
2. Эту же функцию можно использовать в `lcm` (сейчас код там у вас дублируется)

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    else return false
if (x) return true else return false эквивалентно return x

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return false
Над этой функцией нужно ещё поработать. Во-первых, она выдаёт ошибки на тестах бота, а во-вторых, может требовать очень много времени для выполнения. Подумайте, как сделать так, чтобы перебирать в цикле поменьше возможных вариантов или, возможно, обойтись без цикла в принципе

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return k
Функция работает неверно для отрицательных чисел

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var f = x % (2 * Math.PI)
Можно объявить как val. Старайтесь объявлять как var только переменные, которые собираетесь изменять. Тем более, что IDEA подсвечивает жёлтым цветом те var, которые на самом деле никем не изменяются

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun isPalindrome(n: Int): Boolean {
Функция очень похожа на предыдущую. Нельзя ли реализовать одно через другое?

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        x += 1
Лучше x++

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun zap(n: Int): Int = n.toString().length
Старайтесь использовать говорящие имена для функций

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +import kotlin.system.exitProcess
Мне кажется, почти все эти импорты не используются. Удалите те из них, которые IDEA подсвечивает серым

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        var slog = 0.0
Лучше `sum`

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            var list1: MutableList<Double> = list.subList(fromIndex = 1, toIndex = last)
В этой функции по условию задачи не следует создавать новых списков. Вместо этого необходимо изменить переданный вам список `list`.

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        if (list.size == 1) {
Можно просто list.size <= 1 и убрать первый if

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +                k = list1[index]
Если вы пишете цикл так, используйте `element` вместо `list1[index]`.

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        if ((isPrime(i) == true) && (n1 % i == 0)) {
if (x == true) можно заменить на if (x). А if (x == false) на if (!x).

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    result.sorted()
Эта функция не изменяет `result`, а просто возвращает отсортированный список как результат. Если вы хотели отсортировать числа перед возвратом, следовало написать `return result.sorted()`.

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String {
Вы уже решили часть этой задачи в функции `factorize`, здесь осталось только превратить список чисел в строку в нужном формате. Используйте `joinToString`.

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var list1: List<Int> = result.subList(fromIndex = 0, toIndex = result.size)
`list.subList(0, list.size)` даст вам просто оригинальный список. Так что непонятно, зачем нужен вызов этой функции

2016-10-26 10:19 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    while (n1 != 0) {
Функция работает неверно при n = 0

2016-10-27 20:14 UTC, mglukhikh commented
Пожалуйста, исправьте все предыдущие замечания (см. вкладку Files Changed)

2016-11-22 15:41 UTC, mglukhikh commented
recheck all

2016-11-22 16:00 UTC, mglukhikh requested changes
Две неверно решённых задачи из 5-го урока плюс целый ряд замечаний по коду. Пожалуйста, исправьте свои ошибки, прежде чем решать новые задачи.

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    else return false
Всё это можно записать в одну строчку, без переменной `n2`, без двух вызовов `revert`, без конструкции `if (...) return true else return false`. Сделайте это, пожалуйста

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun isPalindrome(n: Int): Boolean {
Исправлено (но см. замечание ниже)

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        x += 1
Всё ещё лучше `x++`

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            c = c + a[index] * b[index]
Тогда уж `c += element * b[index]`

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            func += p1[index] * Math.pow(x, index1 + 1)
1) Не нужно указывать повсюду тип локальных переменных
2) `p1[index]` можно заменить на `element`

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +                list[index]=k
Пробелы (нажмите Ctrl+Alt+L)

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String {
Сделано

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (n==0) {
Пробелы

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..digits.size - 1) dec += (Math.pow(base.toDouble(), i.toDouble()) * digits[digits.size - 1 - i]).toInt()
1) Здесь лучше поставить фигурные скобки для тела цикла, так читается лучше (и так принято в Code Style)
2) Не используйте `Math.pow` для целых чисел, напишите свой вариант `fun pow(x: Int, y: Int) = TODO()`

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список встречается дважды. Вынесите его на верхний уровень и используйте в обоих функциях

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if ((i.toInt() < 58) && (i.toInt() > 47) || (i.toInt() == 43)) result += i
Магические константы 58, 47, 43 следует заменить на соответствующие им символы

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    var result1 = -0.0
Эти две переменные лучше назвать иначе, например, `longest` и `longestLength` (можно использовать Shift+F6 для переименования)

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    }
В этой функции многие условия вычисляются по несколько раз. Перепишите её так, чтобы повторений не было

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    }
Поправьте форматирование и используйте expression body: `fun foo(...): Type = ...`

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return false
`if (...) return true else return false` эквивалентно ?

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    } else return false
`if (...) return true else return false` эквивалентно ?

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    }
`if (...) return true else return false` эквивалентно ?

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if (((a <= r) && (b <= s)) || ((a <= s) && (b <= r)) || ((c <= s) && (a <= r)) || ((c <= r) && (a <= s)) || ((b <= s) && (c <= r)) || ((b <= r) && (c <= s))) {
Слишком длинная строка

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result
Функция работает неправильно для `expression = ""` (и для многих других с нарушением формата входной строки). Необходимо поймать и обработать `NumberFormatException`.

2016-11-22 16:00 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    }
Функция работает неправильно для строки с несколькими пробелами подряд, например

```
jumps = "100  200"
```

2016-11-25 21:18 UTC, mglukhikh commented
Прошу исправить замечания к урокам 3-5. Урок 6 буду смотреть только после их исправления

2016-11-25 21:54 UTC, malashik35 commented
Мне нужно сделать ВСЕ задачи из предыдущих уроков?
Допустим в третьем уроки я все ваши замечания исправил

2016-11-25 22:29 UTC, malashik35 commented
Михаил Игоревич!
У меняя проблемка
я не заходил на майл и не видел ваших замечаний
но при этом делал 5 и 6 урок
не исправленные замечания на момент аттестации повлияют на оценку?

2016-11-28 07:38 UTC, mglukhikh commented
Вам не нужно делать все задачи из всех уроков. Но имеющиеся замечания следует исправить.

2016-12-05 19:58 UTC, mglukhikh requested changes
Я посмотрел уроки 6 и 7, но обращаю внимание на то, что две задачи в 5-м уроке по-прежнему не проходят тесты

2016-12-05 19:58 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    }
Это замечание по-прежнему в силе

2016-12-05 19:58 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result
И это тоже

2016-12-05 19:58 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    var result1 = -0.0
Плохое название переменной. И почему вдруг -0.0?

2016-12-05 19:58 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val a1 = Math.tan(angle)
Что будет, если угол равен пи пополам?

2016-12-05 19:58 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val a2 = Math.tan(other.angle)
И здесь будет то же самое

2016-12-05 19:58 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    var ugl = 0.0
`angle`

2016-12-05 19:58 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val center = bisectorByPoints(a, b).crossPoint(bisectorByPoints(a, c))
Функция не проходит тесты из-за проблем в `crossPoint`

2016-12-14 12:42 UTC, mglukhikh commented
recheck all

2016-12-14 13:04 UTC, mglukhikh requested changes
Две задачи из урока 6.1 не проходят тесты, написал, почему. Кроме этого, обнаружил много неудачных оборотов в предыдущих уроках (всё это правится довольно быстро). В принципе, всё довольно хорошо, на "отлично" вам осталось только исправить замечания (в том числе, правильно построить окружность по трём точкам) и решить что-нибудь из урока 8. Если вас устраивает "хорошо", достаточно просто исправить большую часть замечаний (разбираться с окружностью по трём точкам при этом необязательно).

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        (rookThreatens == true && bishopThreatens == true) -> 3
`rookThreatens == true` эквивалентно просто `rookThreatens`. В свою очередь, `rookThreatens == false` эквивалентно `!rookThreatens`. Запомните это, пожалуйста. Явные сравнения с true и false не нужны

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
`if (...) return true else return false` эквивалентно `return ...`.

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
`if (...) return true else return false` эквивалентно `return ...`.

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
`if (...) return true else return false` эквивалентно `return ...`.

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    else return false
`if (...) return true else return false` эквивалентно `return ...`. После этого функцию можно записать в одну строчку: `fun isCoPrime(...): Boolean = ...`

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        var c: Double = 0.0
Явное указание типа не нужно

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    return list1
Зачем вам здесь понадобился `list1`?

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            }
Поехало форматирование

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    var result1 = -1.0
Придумайте более говорящие названия переменных. `result` и `result1` в сочетании выглядят довольно плохо

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val circle = Circle(center, radius)
Эта промежуточная переменная не нужна

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val b1 = -point.x *(a1/a2) + point.y
Что будет, если `a2 == 0.0`? Кроме этого, беспорядок с пробелами.

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val b2 = -other.point.x *(a3/a4)+ other.point.y
Что будет, если `a4 == 0.0`? Кроме этого, беспорядок с пробелами.

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        angle = Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x))
Здесь гораздо надёжнее использовать `atan2`, нежели вначале делить на 0, а потом надеяться, что арктангенс бесконечности посчитается правильно

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        for (j in 1..circles.size - 1) {
Такое решение определит как наименее удалённую пару из какой-либо окружности и её же самой.

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val center = bisectorByPoints(a, b).crossPoint(bisectorByPoints(a, c))
Функция по-прежнему не проходит тесты из-за проблем в `crossPoint`

2016-12-14 13:04 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +
Отсутствует определение функции `hashCode()`. Одно из правил, которое программисту под JVM стоит запомнить: если определил `equals` -- определи и `hashCode`. Идея, кстати, об этом напоминает.

2016-12-16 21:07 UTC, mglukhikh approved these changes

2016-12-16 21:08 UTC, mglukhikh commented
Что же, этот Pull Request я закрою, первые 7 уроков у вас приняты. На "4" вы уже точно наработали.

2016-12-16 21:08 UTC, closed without merging

2016-12-18 10:54 UTC, malashik35 commented
Михаил Игоревич, у меня небольшая непонятица
Я сделал одну задачу из 8 урока и сделал коммит 
Но в моих комиттах он не отображается зеленой галочкой, как это должно быть
Не подскажете, вы получили задачу?
И если нет, как исправить ситуацию?

Отправлено с iPhone

> 17 дек. 2016 г., в 0:08, Mikhail Glukhikh <notifications@github.com> написал(а):
> 
> Что же, этот Pull Request я закрою, первые 7 уроков у вас приняты. На "4" вы уже точно наработали.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>