Решены все задачи из lesson2.task1 IfElse.kt
Kotlin-Polytech/KotlinAsFirst2016 pull request #154
Opened 2016-10-01 01:19 UTC by InnaKakicheva

2016-10-01 16:53 UTC, mglukhikh commented
Программа не компилируется. Исправляйте ошибку, и впредь, пожалуйста, проверяйте ваши решения на тестах в учебном проекте, прежде чем отправлять их нам.

2016-10-01 17:51 UTC, InnaKakicheva commented
Доброго времени суток. Вероятнее всего я чего-то не понимаю, но у меня все задачи работают, даже та, что я исправила. И да, я все задачи заранее проверяю, прежде чем отправлять их вам. Прошу прощения, если задача действительно не компилируется и я делаю что-то не так.

>Суббота,  1 октября 2016, 19:53 +03:00 от Mikhail Glukhikh <notifications@github.com>:
>
>Программа не компилируется. Исправляйте ошибку, и впредь, пожалуйста, проверяйте ваши решения на тестах в учебном проекте, прежде чем отправлять их нам.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-10-03 16:26 UTC, mglukhikh requested changes
Хорошо, показываю вам место ошибки -- смотрите комментарий к вашему коду. Компилироваться такой код не может -- разве что вы отправили на GitHub не все изменения с локального компьютера, что тоже в принципе возможно. Если код на локальном компьютере выглядит не так, выполните операции Commit и Push для отправки изменений на GitHub.

2016-10-03 16:26 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else if ((age%100==11)||(age%100==12)||(age%100==13)||(age%100==14)||(age%10=0)) "$age лет"
В последнем условии стоит `=` вместо `==`. Из-за этого программа не компилируется.

2016-10-04 06:24 UTC, InnaKakicheva commented
Всё, спасибо, я увидела свою ошибку.


>Понедельник,  3 октября 2016, 19:26 +03:00 от Mikhail Glukhikh <notifications@github.com>:
>
>@mglukhikh requested changes on this pull request.
>Хорошо, показываю вам место ошибки -- смотрите комментарий к вашему коду. Компилироваться такой код не может -- разве что вы отправили на GitHub не все изменения с локального компьютера, что тоже в принципе возможно. Если код на локальном компьютере выглядит не так, выполните операции Commit и Push для отправки изменений на GitHub.
>----------------------------------------------------------------------
>In  src/lesson2/task1/IfElse.kt :
>> @@ -33,8 +33,13 @@ fun minBiRoot(a: Double, b: Double, c: Double): Double {
  * Мой возраст. Для заданного 0 < n < 200, рассматриваемого как возраст человека,
  * вернуть строку вида: «21 год», «32 года», «12 лет».
  */
-fun ageDescription(age: Int): String = TODO()
-
+fun ageDescription(age: Int): String = if ((age%10==2)&&(age%100!=12)) "$age года"
+    else if ((age%10==1)&&(age%100!=11)) "$age год"
+    else if ((age%10==3)&&(age%100!=13)) "$age года"
+    else if ((age%10==4)&&(age%100!=14)) "$age года"
+    else if ((age%10==5)||(age%10==6)||(age%10==7)||(age%10==8)||(age%10==9)) "$age лет"
+    else if ((age%100==11)||(age%100==12)||(age%100==13)||(age%100==14)||(age%10=0)) "$age лет"
>В последнем условии стоит = вместо ==. Из-за этого программа не компилируется.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-10-05 19:58 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> -@file:Suppress("UNUSED_PARAMETER")
В этом коммите вы удалили из репозитория `lesson2/task1/IfElse.kt` вместе со всем содержимым. Пожалуйста, верните его на место, иначе бот будет очень сильно и грязно на вас ругаться.

2016-11-23 10:22 UTC, mglukhikh commented
Вам следует продолжать решать задачи учебного проекта, иначе в конце семестра история неизбежно кончится вашим отчислением. Вряд ли этот вариант для вас желателен.

2017-07-26 18:23 UTC, closed without merging