lessons 1,2,3
Kotlin-Polytech/KotlinAsFirst2016 pull request #157
Opened 2016-10-03 07:34 UTC by petianastasia

2016-10-17 11:32 UTC, belyaev-mikhail commented
recheck all

2016-10-17 11:34 UTC, belyaev-mikhail commented
У вас достаточно много тестов из стандартной поставки не проходит. Пожалуйста, убеждайтесь в том, что тесты проходят прежде, чем отправлять свои решения.

2016-10-17 15:16 UTC, belyaev-mikhail commented
Пожалуйста, исправьте задачи из урока 3 прежде, чем решать и сдавать последующие уроки.

2016-10-17 15:31 UTC, petianastasia commented
Проверяла, все задачи до третьего урока включительно проходили.

Всё исправлю.

понедельник, 17 октября 2016 г. пользователь Mikhail Belyaev написал:

> Пожалуйста, исправьте задачи из урока 3 прежде, чем решать и сдавать
> последующие уроки.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/157#issuecomment-254237716>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVDO_TPR5cBGnbOsBIz0sC_ImSR-K09-ks5q05ExgaJpZM4KMTre>
> .
>

2016-10-27 12:39 UTC, belyaev-mikhail commented
Тег waiting for fix означает, что любые задания, которые вы после него прислали, проверяться не будут, пока вы не исправите то, из-за чего он поставлен.

2016-11-22 22:53 UTC, petianastasia commented
recheck all

2016-11-23 17:34 UTC, petianastasia commented
recheck all

2016-11-25 13:03 UTC, belyaev-mikhail requested changes

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +        (hoursArrive*60+minutesArrive)-(hoursDepart*60+minutesDepart)
Отступы в коде должны быть консистентными.

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +        return (ageResult)
Отступы

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if (t1*v1 >= s) time=s/v1
Сложные цепочки `if`-`else if` следует заменять на `when`.

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if (((rookX1==kingX)||(rookY1==kingY))&&((rookX2!=kingX)&&(rookY2!=kingY))) return (1)
Сложные цепочки `if`-`else if` следует заменять на `when`.

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if (((rookX==kingX)||(rookY==kingY))&&(Math.abs(kingX-bishopX)!=Math.abs(kingY-bishopY))) return (1)
Сложные цепочки `if`-`else if` следует заменять на `when`.

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if (((a + b) < c) || ((b + c) < a) || ((c + a) < b)) return (-1)
Сложные цепочки `if`-`else if` следует заменять на `when`.

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if ((x1 == x2) || (y1 == y2) || ((Math.abs(x1 - x2)) == Math.abs(y1 - y2))) return (true)
Использование пробелов в коде должно быть консистентным. Если вы ставите пробелы до и после операторов &mdash; их следует ставить **везде**. Если не ставите &mdash; их не следует ставить **нигде**.

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if ((x1 == x2) || (y1 == y2) || ((Math.abs(x1 - x2)) == Math.abs(y1 - y2))) return (true)
Конструкция `if(X) return true else return false` лишена всякого смысла, т.к. это то же самое, что и просто `return X`

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    else return (false)
Аналогично

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    else return (false)
Аналогично

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    var k= Math.min(m,n)
Пробелы

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    if (nod == 1) return (true)
См. комментарий про `return true`

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    else return false
См. комментарий про `return true`

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +import org.jetbrains.annotations.Mutable
Это ещё зачем?

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()==false) return result
Пробелы

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        result += p[i] * Math.pow(x, i * 1.0)
Что значит `i * 1.0`?

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            10 -> list.add("a")
Полный перебор всех чисел &mdash; это очень плохо.

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        result += digit * Math.pow(base * 1.0, i)
Что такое `base * 1.0`?

2016-11-25 13:03 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    str.reversed().mapIndexed { i, c -> (if (c in '0'..'9') c - '0' else c - 'a' + 10) * Math.pow(base * 1.0, i * 1.0)}.sum().toInt()
Откуда вы вообще взяли это `x * 1.0`???

2016-11-25 13:03 UTC, belyaev-mikhail commented
recheck all

2016-11-25 13:06 UTC, belyaev-mikhail commented
recheck all

2016-11-25 20:06 UTC, petianastasia commented
recheck all

2016-11-25 20:10 UTC, petianastasia commented
почему остался 'waiting for fix'?

2016-11-25 20:11 UTC, belyaev-mikhail commented
То, что я откомментировал не все места с, например, неконсистентными пробелами, не значит, что их не надо исправить.

2016-11-25 20:12 UTC, belyaev-mikhail commented
waiting for fix убрал

2016-11-25 20:26 UTC, belyaev-mikhail commented
recheck all

2016-11-25 20:26 UTC, belyaev-mikhail commented
(бот почему-то проигнорировал урок 5)

2016-11-25 20:28 UTC, petianastasia commented
recheck all

2016-11-25 20:29 UTC, belyaev-mikhail commented
recheck all

2016-11-25 20:31 UTC, belyaev-mikhail commented
всё хорошо, все ваши однокурсники одновременно постят задания, бот немного устал

2016-11-25 20:32 UTC, belyaev-mikhail commented
recheck all

2016-11-25 20:38 UTC, belyaev-mikhail commented
Не нравитесь вы ему, не хочет он вас сегодня проверять =(

2016-11-25 20:39 UTC, petianastasia commented
заставим! :D

2016-11-25 20:44 UTC, belyaev-mikhail requested changes

2016-11-25 20:44 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    str.reversed().mapIndexed { i, c -> (if (c in '0'..'9') c - '0' else c - 'a' + 10) * Math.pow(base.toDouble(), i.toDouble())}.sum().toInt()
Вообще говоря, считать всё в `Int`, потом возводить в степень и суммировать в `Double`, а потом обрато переводить в `Int`нехорошо. Вам нужна либо функция возведения целых чисел в целые степени, либо гарантировать корректность округления (`toInt()` не округляет, а просто отбрасывает дробную часть).

2016-11-25 20:50 UTC, petianastasia commented
recheck all

2016-12-18 22:41 UTC, belyaev-mikhail commented
У вас решено только 6 уроков. Несмотря на достаточное количество решенных задач, в данный момент вам светит автоматом только "3".

2016-12-18 22:54 UTC, petianastasia commented
lesson_7 в процессе. скоро отправлю

2016-12-19 11:09 UTC, petianastasia commented
Recheck all

2016-12-19 11:12 UTC, petianastasia commented
Check me

2016-12-19 11:19 UTC, petianastasia commented
recheck all

2016-12-20 12:10 UTC, petianastasia commented
CHECK ME

2016-12-20 12:21 UTC, belyaev-mikhail commented
И чего я там должен проверять? У вас в 7 уроке две строчки написано.

2016-12-20 12:21 UTC, belyaev-mikhail commented
4 за декабрь у вас стоит, успокойтесь.

2017-07-26 18:23 UTC, closed without merging