Kotlin
Kotlin-Polytech/KotlinAsFirst2016 pull request #162
Opened 2016-10-06 12:40 UTC by nightonyx

Lessons 1;   2.0,  2.1;   3.0(1 hard)

2016-10-06 14:55 UTC, maximpetrov requested changes

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +    val answer = hours * 3600 + minutes * 60 + seconds
[Здесь и далее в этом файле] Нет необходимости создавать переменную только для того, чтобы её сразу вернуть, можно просто вернуть результат этого выражения. Кроме того, такие функции принято записывать как однострочные.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +    return initial * (1 + 0.01 * percent) * (1 + 0.01 * percent) * (1 + 0.01 * percent)
Здесь нужно было либо завести переменную для повторяющегося выражения, либо преобразовать это математически, используя возведение в степень.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +    val Sotni = number / 100
Старайтесь избегать транслита в именах. Кроме того, в Kotlin принято называть переменные с маленькой буквы.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +    val answer = CreateNewNumber
Эта строка совсем лишняя.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (age % 100 in 5..19)
Можно объединить три первых случая в одну ветку с помощью ИЛИ (`||`)

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (age % 100 in 5..19)
Здесь лучше воспользоваться конструкцией `when`.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    return Double.NaN
Используйте `else`, чтобы избежать ненужного `return` в конце.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    return "invalid input"
Используйте `else`, чтобы избежать ненужного `return` в конце.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val a2 = Math.pow(a, 2.toDouble())
- Вместо `2.toDouble()` лучше просто написать `2.0`.
- Лучше вручную перемножить `a` на `a`, чем использовать `pow`, так эффективнее.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    var crossing = 0
- Некоторые условия можно упростить
- Можно делать `return` из каждого `if`, только придется исправить условия.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if ((number % 100 / 10 + number % 10) == (number / 1000 + (number / 100) % 10))
[Здесь и далее в этом файле] Условие `if` уже является логическим выражением, поэтому
```kotlin
if (x)
    return true
else
    return false
```
эквивалентно `return x`.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (counter <= n) {
Здесь правильнее использовать цикл `for`.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    if (n == 1 || n == 2) return 1
Этот `if` не нужен.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var s1 = 0
Давайте переменным более говорящие имена.

2016-10-06 14:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        val s3 = Math.pow(10.0, (s1 - n).toDouble()).toInt()
Не стоит использовать Double в целочисленных задачах, чтобы не столкнуться с проблемами с точностью, лучше напишите свой `pow` для целых чисел или вообще обойдитесь без этого множителя.

2016-10-29 12:53 UTC, maximpetrov commented
recheck all

2016-10-29 12:53 UTC, maximpetrov commented
recheck all

2016-10-29 22:25 UTC, maximpetrov requested changes
И верните каталог input в корень проекта.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +        crossingFirst -> 0
Этот случай входит в предыдущий

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        var answer = 0
Объявление этой переменной лучше внести в цикл и сделать `val`.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (n % divider != 0) {
Здесь лучше использовать цикл `for` и ограничить перебор снизу.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    return result + number % 10
Во-первых, эту итерацию тоже можно было бы внести в цикл. А во-вторых, конкретно здесь остаток брать незачем, ведь `number` итак меньше 10.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        val element = v[i]
Здесь лучше воспользоваться циклом `for` в формате `for (element in v)`

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    val NewList = factorize(n)
Здесь можно было обойтись без временной переменной и вообще записать в виде однострочной функции.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var answer = listOf<Int>()
Не стоит использовать неизменяемый `List`, используйте `MutableList`.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +            answer = list + answer
Лучше вставлять в конец, а потом перевернуть список.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var answer = ""
Лучше собирать символы в ещё один список, т.к. строка неизменяема.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var answer = listOf<Int>()
Лучше использовать изменяемый `MutableList`.

2016-10-29 22:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            if ((parts[i - 1].toInt() > BestHeight) && (counter == '+'))
Во-первых, первая часть выражения не зависит от `counter` и совершенно зря вычисляется каждый раз заново. Во-вторых, + в строке можно найти гораздо проще: `if ('+' in parts[i])`

2016-11-25 11:43 UTC, maximpetrov requested changes

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +        crossingFirst -> 0
Эта строка теперь лишняя + вместо `when` теперь достаточно `if`.

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        var counter = 0
Внутри цикла можно объявить переменную `counter`, значение которой к следующей итерации Вам не нужно.

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    if (n in 1..2)
Теперь этот `if` не нужен.

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (n % devider != 0)
От того, что Вы перенесли код в `minDivisor`, замечание не поменялось: здесь лучше исппользовать цикл `for` и ограничить сверху диапазон перебора.

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    var Diameter = PointFirst.distance(PointSecond)
Зачем Вы считаете это расстояние через `distance`?

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    return Circle(BissAB.crossPoint(BissAC), a.distance(BissAB.crossPoint(BissAC)))
Сохраните точку пересечения, чтобы не пересчитывать её второй раз.

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson6/task2/Chess.kt
> +            val SetArray = listOf('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
Проще использовать строку вместо списка.

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson6/task2/Chess.kt
> +    val SetArray = listOf('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
Проще использовать строку вместо списка.

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson6/task2/Chess.kt
> +        start.row == end.row -> 1
Эти два условия можно через ИЛИ объединить

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson7/task1/Matrix.kt
> +            NewMatrix[row, column] = e
Зачем этот цикл?

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson7/task1/Matrix.kt
> +        throw IllegalArgumentException()
Почему эта проверка в конце?

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson7/task2/Matrices.kt
> +operator fun Matrix<Int>.plus(other: Matrix<Int>): Matrix<Int> = TODO()
Зачем Вы удалили пример?

2016-11-25 11:43 UTC, maximpetrov commented on src/lesson7/task1/Matrix.kt
> +    override fun toString(): String {
Не хватает пробелов и переносов строк.

2016-11-25 21:46 UTC, mglukhikh commented
recheck all

2016-11-25 21:50 UTC, mglukhikh commented
Повторно обращаю ваше внимание, что каталог `input` обязательно следует вернуть на место, иначе вы не сможете решать задачи 8-го урока.

2016-12-12 08:47 UTC, maximpetrov requested changes

2016-12-12 08:47 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else if (crossingFirst) 0
Эта проверка всё ещё лишняя: может ли она пройти, если первая проверка не прошла?

2016-12-12 08:47 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        var counter = 0
Эту переменную лучше сделать `val` и сразу инициализировать `num2`.

2016-12-12 08:47 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for(i in 2..n) {
Уже лучше, но верхнюю границу перебора можно сделать меньше.

2016-12-12 08:47 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            if ((parts[i - 1].toInt() > BestHeight) && (counter == '+'))
Замечание ещё в силе

2016-12-12 08:47 UTC, maximpetrov commented on src/lesson7/task1/Matrix.kt
> +    override fun toString(): String {
Замечание ещё в силе

2016-12-14 20:18 UTC, nightonyx commented on src/lesson3/task1/Loop.kt
> +    for(i in 2..n) {
Какое замечание lesson5/Parse/bestHighJump?
Не нашёл с прошлых замечаний.

2016-12-14 20:19 UTC, nightonyx commented on src/lesson3/task1/Loop.kt
> +    for(i in 2..n) {
И ещё пока не разобрался как переделать lesson7/matrix/equals, но обязательно соображу!

2016-12-14 20:44 UTC, maximpetrov requested changes
Незакрытые изменения ищите на вкладке [Files changed](162/files).

2016-12-14 20:44 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for(i in 2..n / 2) {
Границу перебора можно сделать ещё меньше

2016-12-15 08:36 UTC, maximpetrov requested changes
Верните входные файлы для 8 урока на место, иначе бот не сможет его проверить.

2016-12-15 08:36 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if ((parts[i - 1].toInt() > bestHeight) && ('+' in parts[i]))
Почему не используете `jump` здесь?

2016-12-15 09:24 UTC, mglukhikh commented
> Верните входные файлы для 8 урока на место, иначе бот не сможет его проверить.

Если вы не можете откатить соответствующее изменение, возьмите эти файлы здесь https://github.com/Kotlin-Polytech/KotlinAsFirst2016/tree/master/input и поместите в каталог input в вашем проекте.

2016-12-15 19:02 UTC, nightonyx commented
Каталог input всегда был у меня на месте. Бот выдал ошибку на GitHub`e. Удалил input и загрузил новый. Теперь бот вообще не проверяет 8-й урок)
Что делать?


>Четверг, 15 декабря 2016, 11:36 +03:00 от Maxim Petrov <notifications@github.com>:
>
>@maximpetrov requested changes on this pull request.
>Верните входные файлы для 8 урока на место, иначе бот не сможет его проверить.
>----------------------------------------------------------------------
>In  src/lesson5/task1/Parse.kt :
>>      var parts = jumps.split(" ")
     for (i in 1..parts.size - 1 step 2) {
-        for (counter in parts[i]) {
-            if ((parts[i - 1].toInt() > BestHeight) && (counter == '+'))
-                BestHeight = parts[i - 1].toInt()
-        }
+        val jump = parts[i - 1].toInt()
+        if ((parts[i - 1].toInt() > bestHeight) && ('+' in parts[i]))
>Почему не используете jump здесь?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-12-15 19:42 UTC, maximpetrov commented
Вам нужно перенести каталог `input` из `tutorial` обратно в корень проекта и закоммитить его.

2016-12-17 20:27 UTC, maximpetrov commented
recheck all

2016-12-18 15:54 UTC, nightonyx commented
Посмотрите, пожалуйста, у меня хватает задач на 5-ку? Надо ли ещё что-то доделать?
1 из 8 урока, тестовая лежит в Loop.kt

2016-12-19 10:23 UTC, maximpetrov commented
recheck all

2017-07-26 18:23 UTC, closed without merging