lesson 4
Kotlin-Polytech/KotlinAsFirst2016 pull request #163
Opened 2016-10-08 14:03 UTC by lopolPol

2016-10-10 20:25 UTC, belyaev-mikhail commented
В заданиях на модификацию списка следует изменять содержимое того списка, **который вам подают на вход**, а не создавать новый.

2016-10-12 10:41 UTC, belyaev-mikhail commented
recheck all

2016-10-12 11:32 UTC, belyaev-mikhail commented
У вас не исправлена ошибка в задании 1.1. Пожалуйста, исправляйте ошибки в старых заданиях прежде, чем приступать к сдаче следующих.

2016-10-26 12:42 UTC, belyaev-mikhail commented
Все задания, поданные после установки тега waiting for fix, засчитаны не будут.

2016-10-26 13:13 UTC, belyaev-mikhail commented
recheck all

2016-10-26 13:22 UTC, belyaev-mikhail requested changes

2016-10-26 13:22 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val a = (x2-x1)*(x2-x1)
Ваш стиль кодирования должен быть консистентным. Если вы используете пробелы до и после операций &mdash; их следует использовать **везде**, если не используйте &mdash; не используйте их **нигде**.

2016-10-26 13:22 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val a = ((hoursArrive-hoursDepart-1)*60+((60-minutesDepart)+minutesArrive))
См. комментарий про пробелы

2016-10-26 13:22 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return (initial*(1+0.01*percent))*(1+0.01*percent) + 0.01*percent*(initial*(1+0.01*percent))*(1+0.01*percent)
См. комментарий про пробелы

2016-10-26 13:22 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val e = secondDigit*100+thirdDigit*10+firstDigit
См. комментарий про пробелы

2016-10-26 13:22 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else if ((age % 10) == 1) "$age год"
Длинные цепочки `if`-`else if`-`else if` следует заменять на `when`.

2016-10-26 13:22 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    return if (((kingX == rookX1) || (kingY == rookY1)) && ((kingY == rookY2) || (kingX == rookX2))) 3
См. комментарий про `when`.

2016-10-26 13:22 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    return if ((a !in c..d) && (b in c..d)) b - c
См. комментарий про `when`.

2016-11-07 11:54 UTC, belyaev-mikhail commented
Вы отправляете новые задания, не исправляя замечания к старым. Довожу до вашего сведения, что проверяться и засчитываться они до исправлений не будут.

2016-11-07 17:40 UTC, lopolPol commented
Сказали, что ошибки в оформлении не считаютс

7 ноя 2016 г. 2:54 PM пользователь "Mikhail Belyaev" <
notifications@github.com> написал:

> Вы отправляете новые задания, не исправляя замечания к старым. Довожу до
> вашего сведения, что проверяться и засчитываться они до исправлений не
> будут.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/163#issuecomment-258816873>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVAMRMSdxQI7-0RecEAo0cedUrZnodETks5q7xF9gaJpZM4KRunN>
> .
>

2016-11-07 17:45 UTC, belyaev-mikhail commented
Не знаю, кто вам это сказал, но ваш PR проверяю в данный момент я.
И я решаю, что считается, а что нет.

2016-11-09 10:49 UTC, lopolPol commented
Исправил

7 ноя 2016 г. 2:54 PM пользователь "Mikhail Belyaev" <
notifications@github.com> написал:

> Вы отправляете новые задания, не исправляя замечания к старым. Довожу до
> вашего сведения, что проверяться и засчитываться они до исправлений не
> будут.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/163#issuecomment-258816873>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVAMRMSdxQI7-0RecEAo0cedUrZnodETks5q7xF9gaJpZM4KRunN>
> .
>

2016-11-09 12:31 UTC, belyaev-mikhail requested changes

2016-11-09 12:31 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = seconds+(minutes*60)+(hours*60*60)
Пробелы

2016-11-09 12:31 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val a = (sec / 3600.0 + min / 60.0 + grad) * PI / 180
Зачем заводить переменную и тут же её возвращать?

2016-11-09 12:31 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val a = (number/100)
Пробелы

2016-11-09 12:31 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val e = secondDigit * 100 + thirdDigit * 10 + firstDigit
См. комментарий про возврат переменной.

2016-11-09 12:31 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    ((a !in c..d) && (b in c..d)) -> (b - c)
Отступы

2016-11-09 12:31 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    return ((a <= r) && (b <= s) || (a <= s) && (b <= r) || (a <= r) && (c <= s) || (b <= r) && (c <= s) || (c <= r) && (a <= s) || (c <= r) && (b <= s))
Длинная строка, разбейте.

2016-11-09 12:31 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        return (m * n) / nod(m, n)
Отступы

2016-11-09 13:43 UTC, closed without merging

2016-12-19 22:26 UTC, mglukhikh commented
Имеющихся задач кое-как хватает на "зачёт"