Sidorina_Lesson5_task1
Kotlin-Polytech/KotlinAsFirst2016 pull request #167
Opened 2016-10-13 10:09 UTC by ElenaLaufeyson

Тут будут решения 5 урока.

2016-10-18 11:27 UTC, maximpetrov requested changes

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var year = 0
`numb` и `year` можно сделать `val`, если не инициализировать их 0.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var index = month.indexOf(parts[1])
`month` и `index` можно сделать `val`.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var month = listOf<String>("января", "февраля", "марта", "апреля", "мая",
Тип хранимых значений списка указывать необязательно.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    return String.format("%02d.%02d.%d", numb, index + 1, year)
Неплохо бы ещё проверить, что дата сама по себе корректна.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var year = 0
Все эти переменные можно сделать `val`.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var listmonth = listOf<String>("января", "февраля", "марта", "апреля", "мая",
Этот список совпадает со списком из предыдущей функции, лучше сделать этот список общим.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if (month !in 1..12) return ""
Опять же, неплохо бы проверить корректность даты.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (!phonenum.equals(phonenum1)) return ""
Для этой проверки лучше воспользоваться `any` или `all`, а не `filter`.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (indexplus > 0) return ""
Раз уж Вы так тщательно проверяете формат, то неплохо бы проверить, что корректность префикса, т.е. что между + и открывающей скобкой есть хотя бы одна цифра.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (indexopen != -1) { //если открывающаяся скобка есть, то проверяем, что она одна
Вы три раза ищете в строке символ, который должен встречаться только один раз. Лучше вынести этот поиск в отдельную функцию.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    jump = jump.trim() //убираем пробелы спереди и сзади
Нет большого смысла это делать, всё равно у Вас останутся лишние пробелы внутри, которые и так Вы обрабатываете.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var jump = jumps.filter { it != '%' && it != '-' }
Можно сделать `val`.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var results = jump.split(" ")
Можно сделать `val`.

2016-10-18 11:27 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            if (element.length != 0 && element.toInt() > answer)
Вместо этого цикла, в принципе, можно обработать список с помощью `filter` и/или `map`, а от результата найти `max()`.

Если оставлять так, то не стоит два раза переводить в `Int`, лучше сохранить в переменную результат.

2016-10-18 21:25 UTC, maximpetrov requested changes

2016-10-18 21:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (month == 2) {
Здесь лучше `else if`.

2016-10-18 21:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +fun search(index: Int, str: String, ch: Char): Boolean {
Вообще я предполагал, что эта функция будет делать всё, то есть и искать первое вхождение тоже.

2016-10-18 21:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var elem: Int
Объявление этой переменной лучше перенести в место инициализации и сделать `val`.

2016-10-18 21:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    jump = deletespace(jump)
Всё же лучше просто пофильтровать список после разбиения.

2016-10-18 21:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        new = new.replace("  ", " ")
Цикл здесь не нужен, `replace` и так заменит все вхождения.

2016-10-20 12:46 UTC, maximpetrov requested changes

2016-10-20 12:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    strin = strin.trim()
Отбрасывание начальных и конечных пробелов здесь лишнее: задание подразумевает, что входная строка корректна, то есть пробелов в начале и конце нет. Если бы они были, то отбрасывать их было бы ошибкой, потому что тогда у Вас сместились бы индексы.

2016-10-20 12:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var strin = str
Переменную можно сделать `val`, если прямо здесь выполнить все нужные преобразования над `str`.

2016-10-20 12:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    express = deletespace(express)
Здесь тоже лучше (красивее и эффективнее) отфильтровать результат `split`, убрав пустые строки, вместо удаления дублирующихся пробелов.

2016-10-20 12:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            if (expressions[i].equals("+")) answer += expressions[i + 1].toInt()
Здесь лучше использовать `when`.

2016-10-20 12:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val jump = jumps.filter { it != '%' && it != '-' }
Результаты в строке группируются парами, поэтому выкидывать % и - не самое лучшее решение, потому что некоторые пары перестанут быть парами и Вы не сможете перебирать значения парами.

2016-10-20 12:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (results.size < 2 || results[0] == "+") return -1
Эти проверки не нужны, если перебирать значения парами.

2016-10-20 12:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        for (i in 0..results.size - 2) {
С учётом предыдущих комментариев, здесь лучше перебирать значения попарно, то есть с шагом 2.

2016-10-20 12:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            if (results[i + 1] == "+" && results[i].toInt() > answer)
Для `results[i].toInt()` лучше завести переменную и не переводить 2 раза.

2016-10-20 19:57 UTC, ElenaLaufeyson commented on src/lesson5/task1/Parse.kt
> +    val jump = jumps.filter { it != '%' && it != '-' }
Я поняла, что Вы имеете в виду, но не вижу сейчас особого смысла перебирать значения попарно, поскольку в уже написанной мной функции итак учтены все возможные варианты и она работает корректно и без перебирания значений парами.

2016-10-20 20:31 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var strInt = 0.0
Эту переменную можно сделать `val`, если внести её внутрь `for`.

2016-10-20 20:31 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val express = expression
Эта переменная у Вас теперь лишняя.

2016-10-20 20:31 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val jump = jumps.filter { it != '%' && it != '-' }
Это не совсем так. В такой реализации у Вас никак правильность формата не проверяется. То есть и несколько чисел подряд, и несколько плюсов или других результатов подряд у Вас не вызовут ошибку, хотя должны бы по условию задачи.

2016-10-23 16:42 UTC, maximpetrov requested changes

2016-10-23 16:42 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (!phonenum.equals(phonenum1)) return ""
Это замечание все ещё в силе

2016-10-23 16:42 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            if (strInt >= strings[maxindex].toDouble()) {
Лучше найденное максимальное значение тоже сохранять, а не только его индекс, чтобы не переводить каждый раз его в double.

2016-10-23 17:32 UTC, ElenaLaufeyson commented on src/lesson5/task1/Parse.kt
> +    if (!phonenum.equals(phonenum1)) return ""
Я не вижу в данной ситуации смысла исправлять нормально работающую функцию на функцию с any или all, поскольку считаю вариант решения с filter для себя более простым и понятным. Мне кажется, у каждого задания может быть несколько вариантов решения, а не только тот, который предлагаете Вы, поэтому мое решение тоже имеет место быть.

2016-10-23 17:46 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (!phonenum.equals(phonenum1)) return ""
Ваше решение не оптимально: Вы сначала создаёте копию строки, а потом ещё и сравниваете две строки, вместо того, чтобы просто, не создавая копию, один раз пройти по строке и проверить её.

2016-10-23 18:08 UTC, ElenaLaufeyson commented on src/lesson5/task1/Parse.kt
> +    if (!phonenum.equals(phonenum1)) return ""
Зато в моем решении проверяется ГОРАЗДО больше, чем, в принципе, необходимо по заданию, что, как мне кажется, должно вызывать похвалу, а не количество замечаний, растущее в геометрической прогрессии. В задании не сказано, как именно решать задачу, поэтому я все же считаю, что моё решение, хоть и не совсем оптимально, рассматривает очень большое количество вариантов и имеет место быть. Функция filter мне кажется более удобной и понятной, и тут я предпочту все же пользоваться ей.
И, если говорить об оптимальности, то разве оптимально в других функциях вместо того, чтобы один раз объявить переменную var и в цикле просто менять ее значение, переносить объявление переменной в место ее инициализации(в цикл) и делать ее Val, каждый раз заново выделяя и удаляя для неё память?

2016-10-23 19:16 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (!phonenum.equals(phonenum1)) return ""
Во-первых, я не отрицаю, что Вы проверяете больше, чем большинство Ваших одногруппников, но не больше, чем необходимо по заданию. Во-вторых, количество замечаний если и увеличилось, то уж точно не в геометрической прогрессии: большинство новых замечаний - это замечания к исправлениям, а конкретно к этой функции новых замечаний вообще не появлялось. В-третьих, дело даже не столько в производительности, сколько в том, что Ваше решение выглядит таким образом, как будто Вы узнали про функцию `filter` и она Вам так понравилась, что Вы решили использовать её везде, где нужно и где не нужно. В этом месте её использование не оправдано ни с точки зрения оптимальности, ни с точки зрения понятности: куда более очевидное решение просто пройти по символам строки и проверить каждый на правильность. Сделать это можно как "вручную" в цикле, так и с помощью функций `all` или `any`, которые, кстати, не отличаются по синтаксису от `filter` и очень похожи на неё по принципу действия.
P. S. Оптимальность не страдает при переносе переменных внутрь цикла, поскольку память под них всё равно будет выделена один раз, а вот их область видимости уменьшиться до минимально необходимой.

2016-10-24 19:45 UTC, ElenaLaufeyson commented on src/lesson5/task1/Parse.kt
> +    if (!phonenum.equals(phonenum1)) return ""
Исправила данное замечание, воспользовавшись функцией all, а не filter.

2016-10-24 23:27 UTC, maximpetrov commented
Все замечания исправлены, 5 урок принят.

2016-10-24 23:27 UTC, closed without merging