2 и 3 уроки
Kotlin-Polytech/KotlinAsFirst2016 pull request #170
Opened 2016-10-17 12:38 UTC by elkaties

Достаточно долго пыталась решить в третьем уроке хотя бы одну задачу через рекурсию, но пока не получилось. Попробую потом вернуться к решению через рекурсии, сейчас сложно для понимания в каком виде возвращается функция и какие ограничения ставить на количество раз ее вызова.

2016-10-17 16:23 UTC, elkaties commented
Очень странно, что пишет ошибку в тривиальной задаче 3-го урока, в idea все тесты проходят...

2016-10-17 16:25 UTC, belyaev-mikhail commented
И что в этом странного? Из сообщения довольно очевидно, что вы не поддерживаете отрицательные числа.
Тесты из проекта не являются мерилом правильности выполнения задания, они вам даны в иллюстративных целях.

2016-10-26 12:42 UTC, belyaev-mikhail commented
recheck all

2016-10-26 12:43 UTC, belyaev-mikhail commented
У вас не исправлена ошибка в задании 2.1. Пожалуйста, исправляйте ошибки в старых заданиях прежде, чем приступать к сдаче следующих.

2016-10-26 12:44 UTC, belyaev-mikhail commented
Все задания, поданные после установки тега waiting for fix, засчитаны не будут.

2016-10-27 21:01 UTC, belyaev-mikhail commented
Напоминаю, что у вас не исправлена ошибка в уроке 1.
См. предыдущий комментарий.

2016-10-27 21:05 UTC, belyaev-mikhail commented
Ваш код не компилируется. Пожалуйста, проверяйте код перед отправкой.

2016-10-27 21:13 UTC, elkaties commented
Да, видела проблему с компиляцией, но не до конца понимаю в чем проблема, Вы не сможете пояснить что не так?

2016-10-27 21:17 UTC, belyaev-mikhail commented
Ваш код не компилируется. Что в этом непонятного?
Ваша среда разработки должна вам показать, где.
Если вы хотите, чтобы я поработал средой разработки вместо неё, ок, попробую.
Вероятно, вы где-то поставили после заголовка функции знак `=` как-то так:
```
fun blablabla(): Bla = {
    blablabla
    ...
    return Bla
}
```

Так в котлине делать нельзя. Можно либо без `=` и с указанием возвращаемого типа (будет работать) или без `return` и скобок (как вы писали в однострочных функциях в первом уроке). Также можно использовать функцию `run`:
```
fun blablabla(): Bla = run {
    blablabla
    ...
    return Bla
}
```

Где именно вы допустили подобную оплошность я предоставляю вам найти самостоятельно.

2016-10-27 21:18 UTC, belyaev-mikhail commented
Да, мне такие правила языка тоже кажутся странными. Нет, обойти это никак нельзя.

2016-10-27 21:26 UTC, elkaties commented
Ох...уверена, что теперь запомню это надолго.

2016-10-27 22:17 UTC, belyaev-mikhail requested changes

2016-10-27 22:17 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = hours*3600 + minutes*60 + seconds
Ваш стиль кодирования должен быть консистентным. Если вы ставите пробелы до и после знаков операций, то ставьте их **везде**. Если не ставите &mdash; не ставьте их **нигде**.

2016-10-27 22:17 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = 0.04445*(sagenes*48 + arshins*16 + vershoks)
Аналогично

2016-10-27 22:17 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if ((a >= b + c) || (b >= a + c) || (c >= a + b)) return -1
Длинные цепочки из `if`-`else if`-`else if` лучше заменять на `when`.

2016-10-27 22:17 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    if (number1 == n) return true
Конструкция `if(X) return true else return false` лишена смысла, т.к. ничем не отличается от просто `return X`.

2016-10-27 22:38 UTC, belyaev-mikhail commented
Ок

2016-10-27 22:38 UTC, closed without merging