3 урок полностью
Kotlin-Polytech/KotlinAsFirst2016 pull request #173
Opened 2016-10-19 10:45 UTC by Perepicica

2016-10-19 20:31 UTC, mglukhikh requested changes
Почти всё хорошо. Попробуйте решить проблемы с точностью синуса и косинуса и исправьте немногочисленные замечания по стилю, пожалуйста.

2016-10-19 20:31 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return if (a == 1) true else false
`if (x) true else false` эквивалентно `x`

2016-10-19 20:31 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(e) >= Math.abs(eps)) {
У такой реализации возникают проблемы при больших значениях `x` -- например, `10 * PI` или `100 * PI`. Чем больше `x`, тем больше членов ряда надо для расчёта, и из-за этого увеличивается погрешность операций -- ведь каждая операция с Double вносит пусть маленькую, но погрешность. Добавьте в тестовую функцию случай с `x = 100 * PI`, ожидаемым результатом 0 и точностью `1e-10`. Придумайте, как справиться с описанными здесь проблемами, используя хорошо известные свойства функции "синус". Примерно то же самое для косинуса.

2016-10-19 20:31 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun isPalindrome(n: Int): Boolean {
Не кажется ли вам, что реализация этой функции очень похожа на предыдущую функцию? Нельзя ли как-нибудь выразить одно через другое?

2016-10-26 12:02 UTC, mglukhikh requested changes
Написал вам замечаний. Отмечу, что многие ваши решения совпадают с решениями Владиславы Васильевой. Постарайтесь хотя бы часть времени работать отдельно друг от друга.

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +}
Лучше просто `fun isPalindrome(n: Int): Boolean = n == revert(n)`

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..v.size - 1) {
Правильнее использовать цикл по элементам: `for (elem in v) { ... }`. Не используйте операцию индексации там, где достаточен просто перебор элементов списка.

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Здесь можно использовать просто `list.sum()`.

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
У вас уже есть функция `mean`

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        val element=list[i]
Беспорядок с пробелами

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Есть функция `list.revert()`, изменяющая порядок элементов в списке на обратный

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun convertToString(n: Int, base: Int): String {
У вас уже есть функция `convert`, попробуйте воспользоваться ей и затем превратить список цифр в строку

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var alf =listOf<Char>('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z')
Здесь лучше вместо списка символов использовать строку

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +   for (i in 0..digits.size-2){
Поехало выравнивание

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun decimalFromString(str: String, base: Int): Int{
Попробуйте вначале сделать из строки список цифр, а потом вызвать `decimal`.

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    for (i in k..Int.MAX_VALUE) {
Такой способ вычисления НОК очень долгий. Нельзя ли как-нибудь побыстрее?

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun convert(n: Int, base: Int): List<Int> {
Функция работает неверно для n = 0

2016-10-26 12:02 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var n = digits[0]
Список цифр может быть пустым, в этом случае следует вернуть 0

2016-10-31 07:44 UTC, mglukhikh commented
recheck all

2016-10-31 07:51 UTC, mglukhikh commented
recheck all

2016-10-31 07:52 UTC, mglukhikh requested changes
Мелкие замечания по стилю, в основном к 5-му уроку

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Виноват, функция называется `list.reversed()`.

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun convert(n: Int, base: Int): List<Int> {
Исправлено

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    while (m > 0){
Перед фигурной скобкой лучше ставить пробел

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 1..result1.size ){
И здесь тоже

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val alf =listOf<Char>('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z')
Эту переменную лучше вынести на верхний уровень, так как она используется в двух функциях. Правильнее сделать её строкой и написать капсом, так как это константа: `val ALPHABET = "abcdef...xyz"`.

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun decimalFromString(str: String, base: Int): Int{
Это замечание по-прежнему в силе

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                "декабря" -> "12."
Такие длинные `when` не украшают код. Сделайте список названий месяцев и используйте его. Лучше сделать его глобальной переменной, так как в следующей функции он тоже понадобится

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            else result = day.toString()
Зачем этот if / else ?

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                "12" -> " декабря "
См. замечание к функции выше

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            result += parts[2].toInt().toString()
Зачем это двойное преобразование?

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            var day = parts[0].toInt()
Почему вдруг var, она же не меняется? (обращайте внимание на предупреждения идеи)

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            var day = parts[0].toInt()
Почему вдруг var, она же не меняется? (обращайте внимание на предупреждения идеи)

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            else result = day.toString() + "."
Для этой цели лучше использовать `String.format`

2016-10-31 07:52 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            result += parts[2].toInt().toString()
Зачем это двойное преобразование?

2016-11-09 10:31 UTC, mglukhikh requested changes
Всё почти хорошо. `bestLongJump`, судя по всему, проблема бота, `plusMinus` ваша

2016-11-09 10:31 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun decimalFromString(str: String, base: Int): Int{
Исправлено

2016-11-09 10:31 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun convertToString(n: Int, base: Int): String {
Пока по-прежнему в силе

2016-11-09 10:31 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result
Необходимо ловить в этой функции NumberFormatException

2016-11-09 11:11 UTC, mglukhikh commented
recheck all

2016-11-09 11:43 UTC, mglukhikh commented
Относительно `bestLongJump`, это всё-таки НЕ проблема бота. Попробуйте вот такую исходную строку: `"201 202  203"`.

2016-11-09 12:04 UTC, gagarski commented
recheck assignment

2016-11-16 17:30 UTC, mglukhikh commented
recheck all

2016-11-21 07:41 UTC, mglukhikh requested changes
Довольно много замечаний по стилю + три фактические ошибки. Пожалуйста, исправьте ошибки и замечания, прежде чем двигаться дальше

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    for (i in k..Int.MAX_VALUE) {
Это замечание по-прежнему в силе

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun convertToString(n: Int, base: Int): String {
Исправлено

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var result1 = String()
Лучше `var result1 = ""`. Попробуйте придумать более говорящие названия переменных, чем `result1` и `result2`.

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        result1 += ALPHABET[m - 10]
В такой конструкции `else` должно быть с новой строчки.

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    return result
Ваше решение чрезвычайно длинное и прямолинейное (и к тому же содержит ошибки -- см. тесты бота). Подумайте, можно ли заранее сохранить в списках или ассоциативном массиве численные значения, соответствующие римским цифрам, и после этого обрабатывать все римские цифры одним и тем же способом.

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +val un1 = listOf("один","два","три","четыре","пять","шесть","семь","восемь","девять")
Нажмите на этом фрагменте Ctrl+Alt+L

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        } else {
Старайтесь форматировать if / else одинаково: либо так

```
if (...) {
}
else {
}
```

либо так

```
if (...) {
} else {
}
```

У вас же встречаются оба варианта, что делает код грязным

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            if(mid2 == 0 )  result += ""
Аккуратнее с пробелами

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    return result
1) Поправьте форматирование (Ctrl+Alt+L), с пробелами изрядный бардак
2) Функция включает два очень похожих фрагмента кода -- один для единиц, другой для тысяч. Попробуйте написать отдельную функцию для конвертации в русскую строку числа 0..999 и воспользоваться ею в данной функции
3) Судя по проваленным тестам бота, где-то в результате у вас появляются лишние пробелы. Проверьте это на том случае, который привёл бот, и исправьте ошибку

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result
Функция закомментирована, пока замечание игнорируем

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        return if (center.distance(other.center)> radius+other.radius) center.distance(other.center)-(radius+other.radius)
Бардак с пробелами

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        if (!(inside())) return ""
Лишняя пара круглых скобок вокруг вызова `inside()`

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        var result = String()
Лучше `= ""`

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        result+= row
Бардак с пробелами

2016-11-21 07:41 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        return Square(ALF.indexOf(notation.first() + 1), (notation.last().toInt() - 48))
1) Что такое 48? Заменить на соответствующий символ
2) Отформатируйте if ... else правильно
3) Логическая ошибка в условии `if`, подумайте ещё раз

2016-11-25 20:46 UTC, mglukhikh commented
recheck all

2016-11-25 20:49 UTC, mglukhikh commented
recheck all

2016-11-25 20:59 UTC, mglukhikh requested changes
В принципе, всё очень даже хорошо, вот только две небольших ошибки в уроке 6.2. Исправьте их, и я закрою этот Pull Request.

2016-11-25 20:59 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    if ((notation.first() in 'a'..'h') && (notation.last() in '1'..'8') && (notation.length == 2)) {
Вам следует переставить проверки местами, с тем, чтобы первой проверялась длина. Иначе, функция `first` будет кидать исключение для пустых строк.

2016-11-25 20:59 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    }
Нет проверки корректности клеток

2016-12-01 19:00 UTC, mglukhikh commented
Исправления в уроке 6.2 верные, но две новые задачи из урока 5 не проходят тесты :(

2016-12-14 10:13 UTC, mglukhikh commented
recheck all

2016-12-14 12:01 UTC, mglukhikh requested changes
Написал замечаний по урокам 4 и 5 (большую часть сегодня обсуждали с вами лично)

2016-12-14 12:01 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        if (part1 % 10 == 1) result.add("тысяча")
Для `part1` равного 11 или 111, этот код работает неверно

2016-12-14 12:01 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Сделайте, пожалуйста, из `months` глобальную переменную (для этого нужно определить её ПЕРЕД функцией) -- она у вас используется в двух разных функциях и имеет одинаковые значения

2016-12-14 12:01 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
См. выше

2016-12-14 12:01 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if ((i.toInt() < 58) && (i.toInt() > 47) || (i.toInt() == 43)) result += i
Здесь необходимо заменить магические числа на соответствующие символы

2016-12-14 12:01 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    if (result.first() == '+' && result.length == 1) return ""
Может оказаться, что `result` пуст (например, для входной строки из одних пробелов или чёрточек)

2016-12-14 12:03 UTC, mglukhikh commented
В целом, вам желательно исправить имеющиеся замечания и сделать урок номер 7 (7.1 полностью и одну задачу из 7.2). Тогда у вас получается оценка "хорошо". Побороться за "отлично" вы тоже можете попробовать, но для этого надо также решить одну задачу из урока номер 8 -- не уверен, хватит ли у вас на это времени.

2016-12-15 07:06 UTC, mglukhikh commented
Вы можете использовать комментарий "recheck all". Он, правда, не всегда срабатывает с первой попытки.

2016-12-15 07:06 UTC, mglukhikh commented
recheck all

2016-12-15 07:11 UTC, mglukhikh commented
recheck all

2016-12-16 20:22 UTC, mglukhikh commented
recheck all

2016-12-16 20:38 UTC, mglukhikh requested changes
Посмотрел задачи 7-го урока. В основном всё в порядке.

2016-12-16 20:38 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        list.equals(other.list)
Лучше `list == other.list`

2016-12-16 20:38 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            for (column in 0..width - 1) sb.append(this [row,column])
При таком способе вывода у вас элементы одной строки сольются. Добавьте между ними какой-нибудь разделитель. Кроме этого, в этой функции случился кошмар с форматированием

2016-12-16 20:38 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +      }
Нет функции hashCode(). Одно из важных правил JVM-программиста -- определил equals, определи и hashCode. Подробности я рассказывал на лекциях.

2016-12-16 20:38 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        rookMoveNumber(start, end) == 0 -> listOf(start)
Здесь лучше так:

```
return when (rookMoveNumber(start, end)) {
    0 -> ...
    1 -> ...
    else -> ...
}
```

2016-12-16 20:38 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var succes = ""
`success`

2016-12-16 20:38 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if (jumps[i] in number) {
Лучше `jumps[i].isDigit()`, такая функция есть в Котлине

2016-12-16 20:38 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result
Эта функция не проходит тесты. Возьмите один из контр-примеров бота и попробуйте разобраться, что не так. Вообще решение получилось сложноватым -- разбить строку на части по пробелам и уже потом разбираться гораздо проще.

2016-12-16 20:42 UTC, mglukhikh commented
recheck all

2016-12-16 20:52 UTC, mglukhikh commented
recheck all

2016-12-18 09:11 UTC, Perepicica commented on src/lesson5/task1/Parse.kt
> +    return result
я 3 раза переделывала эту вроде как среднюю задачу разными способами, но она у меня всё равно где-то, да не работает, и у меня уже аллергия на неё. я нашла ошибку, и знаю почему не работает именно тот тест, но мне сейчас легче просто удалить её, чем ломать голову и писать сначала.. займусь 8 уроком, если вы не против

2016-12-18 17:09 UTC, mglukhikh requested changes
Ну что ж, в целом я вами доволен, хотя и позволю себе вас попросить исправить оформление в первых уроках и ещё несколько мелочей, см. замечания ниже. Пока пишу good (4), но после исправления замечаний это превратится в excellent (5).

2016-12-18 17:09 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +        (initial * (1 + percent * 0.01) * (1 + percent * 0.01) * (1 + percent * 0.01))
Примените здесь возведение в степень, пожалуйста :)

2016-12-18 17:09 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val hs=(t1*v1+t2*v2+t3*v3)/2
А здесь примените авто-форматирование (Ctrl+Alt+L)

2016-12-18 17:09 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return  sum1==sum2
И здесь авто-формат вам поможет

2016-12-18 17:09 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return (a<=r &&b<=s) || (a<=s && b<=r) || (b<=r && c<=s) || (b<=s&& c<=r) || (a<=r && c<=s) || (a<=s &&c<=r )
И здесь тоже авто-формат (он сразу на весь файл действует, если не выделять конкретный кусок кода)

2016-12-18 17:09 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return false
`if (...) return true else return false` эквивалентно?

2016-12-18 17:09 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val ALPHABET = "abcdefghijklmnopqrstuvwxyz"
Константу (тем более, именованную капсом) лучше вынести за пределы функции

2016-12-18 17:09 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return sb.toList().joinToString(separator = ",", prefix = "[ ", postfix = " ]").split(",]").joinToString(separator = "]").split("[,").joinToString(separator = "[")
Какой ужас... вы не могли бы пояснить, что вы тут имели в виду?

2016-12-18 17:09 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +    val text2 = "иауИАУ"
Ещё лучше было бы применить здесь `Map` (ассоциативный массив) для преобразования "плохого" символа в "хороший"

2016-12-18 17:10 UTC, mglukhikh commented
recheck all

2016-12-18 17:35 UTC, mglukhikh commented
recheck all

2016-12-21 17:08 UTC, closed without merging