kotlin
Kotlin-Polytech/KotlinAsFirst2016 pull request #174
Opened 2016-10-19 18:12 UTC by milkyway23

2016-10-19 20:05 UTC, mglukhikh requested changes
Много мелких замечаний по стилю + одна задача решена неверно. Исправляйте, пожалуйста.

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ( ( age in 5..20 ) or ( age in 105..120 ) ) return "$age лет"
Лучше вместо неленивого `or` использовать ленивый `||`. В данном случае особой разницы нет, но во многих случаях это критически важно

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val p:Double =t1*v1+t2*v2+v3*t3
Тип локальных переменных обычно выводится автоматически. Кроме этого, рекомендуется расставлять пробелы в единообразном стиле: `val p = t1 * v1 + t2 * v2 + t3 * v3`. Такой стиль можно получить автоматически, использовав комбинацию клавиш Ctrl+Alt+L в IDEA

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    var rook:Int=0; var bishop:Int=0; var p:Int=0
Определение нескольких переменных в одной строке выглядит очень некрасиво

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((rookX2==kingX)or(rookY2==kingY)) bishop = 1
`or` --> `||`. Обе переменные `rook`, `bishop` следует сделать логическими, так как они обозначают наличие угрозы от ладьи (слона). Угроза или есть, или её нет.

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +                p=1
Подобную конструкцию следует оформлять так:

```
if (!rook && !bishop) p = 0
else if (rook && bishop) p = 3
else if (bishop) p = 2
else p = 1
```

или с помощью `when`:

```
when {
    !rook && !bishop -> p = 0
    rook && bishop -> p = 3
    bishop -> p = 2
    else -> p = 1
}
```

И не забывайте расставлять пробелы правильно (Ctrl+Alt+L)

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((rookX2==kingX)or(rookY2==kingY)) bishop = 1
Вы, судя по всему, скопировали текст этой функции с последующей, в которой действительно есть ладья и слон. Здесь же есть две ладьи, поэтому переменные следовало назвать `rook1` и `rook2`.

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Те же замечания, что и для предыдущей функции

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +            if ((a * a + b * b == c * c) or (a * a + c * c == b * b) or (b * b + c * c == a * a)) n = 1 else
`or` --> `||`; поправить выравнивание if..else if (см. пример выше)

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    } else n=-1
`n = -1`

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +                if (c>=a && c<=b && d<=b) n = (d-c) else n = -1
Поправить выравнивание if..else if (см. пример выше), пробелы

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if ((number % 10 + number / 10 % 10) == (number / 100 % 10 + number / 1000)) return true else return false
`if (x) return true else return false` эквивалентно `return x`.

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
`if (x) return true else if (y) return true else return false` эквивалентно `return x || y`.

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
`if (x) return true else return false`

2016-10-19 20:05 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if (((a <= r) && (b <= s)) || ((a <= s) && (b <= r)) || ((a <= r) && (c <= s)) || ((a <= s) && (a <= r)) || ((c <= r) && (b <= s)) || ((c <= s) && (b <= r))) return true else return false
Эта очень длинная строка. В ней довольно просто ошибиться, что вы и сделали (см. сообщение бота). Добавьте в тестовую функцию тот случай, который привёл для вас бот. А эту функцию попробуйте записать короче. Используйте тот факт, что кирпич в любом случае следует вставлять самой длинной стороной вдоль отверстия, то есть, самая длинная сторона кирпича должна игнорироваться при сравнении

2016-10-26 20:39 UTC, mglukhikh commented
Название Pull Request не соответствует его содержанию. Будьте любезны его исправить

2016-10-26 21:34 UTC, mglukhikh requested changes
Поправьте, пожалуйста, приведённые ниже замечания

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    var rook: Int = 0;
`val rook1 = rookX1 == kingX || rookY1 == kingY`. Раз речь идёт о 1-й ладье, то и назвать переменную нужно `rook1`, а не просто `rook`. Кроме этого, у этой переменной может быть всего два значения: есть угроза или нет. А значит, она должна быть логической, а не целой. То же самое со 2-й ладьёй.

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((rook == 0) && (rook1 == 0)) p = 0 else
Подобные многоэтажные проверки лучше записывать через `when`. Заодно, с форматированием кода будет проще -- сейчас это читать невозможно

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    var rook = 0;
См. замечания к предыдущей функции

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        if ((a * a + b * b < c * c) || (a * a + c * c < b * b) || (b * b + c * c < a * a)) n = 2
Здесь тоже лучше использовать `when` или, по крайней мере, написать все три проверки на одном уровне, а не лестницей.

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (c <= a && d >= b) n = (b - a)
См. замечания к предыдущей функции

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return ((number % 10 + number / 10 % 10) == (number / 100 % 10 + number / 1000))
Для этой функции можно использовать expression body: `fun isNumberHappy(number: Int): Boolean = ` и далее выражение, которое у вас стоит после `return`.

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        n2 = n2 / 10
Лучше `n2 /= 10`

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        if (n % i == 0) if (i <= a) a = i
Поскольку вы перебираете возможные делители по возрастанию, вы можете сразу же вернуть делитель из функции, когда убедились, что `n` делится на него без остатка. Промежуточная переменная `a` здесь не нужна.

2016-10-26 21:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun isPalindrome(n: Int): Boolean {
Эта функция практически повторяет предыдущую, попробуйте выразить `isPalindrome` через `revert`

2016-10-28 17:00 UTC, milkyway23 commented
А пока я не исправлю замечания, урок не будет учитываться при промежуточной аттестации?

2016-11-04 18:58 UTC, mglukhikh requested changes
Довольно много замечаний к урокам 2, 3 и 4. Прошу их исправить, перед тем как решать следующие уроки.

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    var rook: Int = 0;
Это замечание всё ещё в силе

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((rook == 0) && (rook1 == 0)) p = 0 else
Это замечание всё ещё в силе

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        if ((a * a + b * b < c * c) || (a * a + c * c < b * b) || (b * b + c * c < a * a)) n = 2
Это замечание всё ещё в силе

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return ((number % 10 + number / 10 % 10) == (number / 100 % 10 + number / 1000))
Это замечание всё ещё в силе

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return (a == n)
Переменная `a` здесь не нужна. А вместо `return` для такой простой функции следует использовать expression body: `fun isPalindrome(...): Boolean = ...`.

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (failed == false) return true else return false
Эквивалентно `return !failed`

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return r
Не кажется ли вам, что у вас уже есть подобная функция?

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var resalt = 0
result

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var length: Double = 0.0
В котлине почти никогда не нужно указывать тип локальных переменных -- он очевиден из контекста.

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Здесь лучше использовать for-each: `for (elem in v) { ... }`, перебирая все элементы вектора. Индексация может быть довольно медленной операцией, да и лишняя переменная появляется

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Можно просто `val length = list.sum()`.

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    else a.zip(b, { elementOfa, elementOfb -> elementOfa * elementOfb }).sum()
Поясните мне в комментарии, что происходит в этой строчке, пожалуйста

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    else a.zip(b, { elementOfa, elementOfb -> elementOfa * elementOfb }).sum()
Поясните мне в комментарии, что происходит в этой строчке, пожалуйста

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    else a.zip(b, { elementOfa, elementOfb -> elementOfa * elementOfb }).sum()
Поясните мне в комментарии, что происходит в этой строчке, пожалуйста

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    else a.zip(b, { elementOfa, elementOfb -> elementOfa * elementOfb }).sum()
Поясните мне в комментарии, что происходит в этой строчке, пожалуйста

2016-11-04 18:58 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
В этой функции (и для косинуса тоже) у вас возникают проблемы с точностью для больших значений `x`. Попробуйте написать тест для вычисления `sin(100 * Math.PI)`, точность задайте `1e-10`, ожидаемый результат равен 0. Из-за того, что вам потребуется просуммировать очень большое количество членов ряда, нужной точности достигнуть вам не удастся. Подумайте, как решить эту проблему, используя хорошо известные математические свойства синуса.

2016-11-23 10:29 UTC, mglukhikh commented
Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.

2016-11-23 21:33 UTC, milkyway23 commented
Извините, просто давно не отсылала из-за неполадок с интернетом(

Отправлено с iPad

> 23 нояб. 2016 г., в 13:29, Mikhail Glukhikh <notifications@github.com> написал(а):
> 
> Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-11-24 08:58 UTC, mglukhikh commented
А на упражнения ходить что мешает?

2016-11-24 21:46 UTC, milkyway23 commented
Я только на одном занятии не была(
Просто с того компьютера не отправляла ничего. Не ругайтесь, пожалуйста((

Отправлено с iPad

> 24 нояб. 2016 г., в 11:58, Mikhail Glukhikh <notifications@github.com> написал(а):
> 
> А на упражнения ходить что мешает?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-11-25 07:14 UTC, mglukhikh commented
Я пока ещё не очень сильно ругаюсь :)

2016-11-25 20:37 UTC, mglukhikh commented
А исправить все замечания к урокам 2-4? Посмотрите, пожалуйста, замечания и вопросы на вкладке Files Changed: https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/174/files. Потом буду смотреть остальное.

2016-12-19 08:27 UTC, mglukhikh commented
"Зачёт" готов поставить только после исправления ВСЕХ замечаний.

2016-12-19 08:29 UTC, mglukhikh commented
Замечания вы можете найти на вкладке Files Changed

2017-07-26 18:23 UTC, closed without merging