Решён урок 3
Kotlin-Polytech/KotlinAsFirst2016 pull request #176
Opened 2016-10-20 10:27 UTC by Chelobiaka

2016-10-24 11:31 UTC, maximpetrov requested changes

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    if (n in 1..2) return 1
Эта проверка лишняя, если `n` равно 1 или 2, то программа в цикл всё равно не зайдёт, а возвращать можно не `s`, а `fib2`.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        var s = 0
Эту переменную лучше внести внутрь цикла и сделать `val`.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    } while ((k % m != 0) || (k % n != 0))
Есть намного более оптимальный алгоритм для поиска НОК.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    } while (n % d != 0)
Здесь красивее было бы применить цикл `for`.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    } while (n % d != 0)
Здесь тоже красивее было бы применить цикл `for`.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if ((m % d == 0) && (n % d == 0)) return false
Здесь тоже существует намного более оптимальный алгоритм.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var k = 0
Эта функция не работает

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if (i % 2 == 1) sinX += Math.pow(y, k.toDouble()) / factorial(k)
Очередной член ряда лучше поместить в переменную, чтобы не вычислять его несколько раз. А ещё лучше вычислять из предыдущего, а не каждый раз заново.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var k = 0
См. замечания по `sin`.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var m = n
Ваша реализация этой функции практически полностью копирует код предыдущей. Используйте предыдущую функцию без копирования кода.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        m /= 10
Эти две строчки такие же, как внутри цикла. Измените код, чтобы не требовалось эти действия выполнять перед циклом.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        val ex = Math.pow(10.0, (c - n).toDouble()).toInt()
Нехорошо использовать `double` в целочисленных задачах, можно наткнуться на проблемы с точностью. Лучше напишите свою целочисленную функцию `pow`.

2016-10-24 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        val ex = Math.pow(10.0, (c - n).toDouble()).toInt()
См. замечание к `squareSequenceDigit`.

2016-10-24 16:46 UTC, Chelobiaka commented
К очень большому сожалению, я не смогу нормально исправить код.
Дело в том, что на момент создания PR произошёл крах системы с BSOD`ом (название ошибки не запомнила, увы), после которого IDEA теперь работает очень странно: я не могу отслеживать свои ошибки и тестировать код, потому что такой функционал куда-то пропал :О 
Скриншот прилагается. 
![default](https://cloud.githubusercontent.com/assets/22213633/19654528/2eaad10c-9a08-11e6-91f2-6095becf0aea.PNG)
Здесь можно обратить внимание на то, что напротив каждого теста отсутствуют зелёные треугольники, с помощью которых запускается тест.
Если подскажете, как вернуть проект в нормальное состояние, буду очень благодарна :)

2016-10-24 16:48 UTC, maximpetrov commented
Для начала, попробуйте пересоздать проект.

2016-10-24 17:29 UTC, Chelobiaka commented
Всё работает, спасибо большое :)

2016-10-29 09:49 UTC, maximpetrov commented
recheck all

2016-10-29 10:54 UTC, maximpetrov requested changes

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (m % n > 0) {
Вы 2 раза находите один и тот же остаток от деления, хотя этого можно и не делать.

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int = Math.abs(m * n) / gcd(m, n)
Во-первых, модуль здесь не нужен, предполагается, что числа положительные. Во-вторых, лучше сначала поделить одно из чисел на НОД, а потом уже умножать на второе, чтобы не получилось переполнения там, где его не должно быть (например, 1000000 и 1000000)

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Зачем Вам `d`, если у Вас есть `i`?

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n - 1 downTo 1) {
См. замечание к `minDivisor`.

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Кроме того, не обязательно перебирать до `n`.

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n - 1 downTo 1) {
Не обязательно перебирать от `n - 1` до `1`, можно сузить интервал перебора.

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if (m == 0) return true
Что эта проверка делает внутри цикла?

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (k * k <= m) {
Не очень логичный диапазон, к тому же он заставляет Вас рассматривать 0 как отдельный случай.

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        val z = Math.pow(y, k.toDouble()) / factorial(k)
Во-первых, хорошо бы вычислять очередной член последовательности только один раз и не пересчитывать его в проверке условия. Во-вторых, неплохо было бы вычислять этот член из предыдущего.

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun cos(x: Double, eps: Double): Double {
См. замечания по `sin`.

2016-10-29 10:54 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if (m < 10) break
Что мешает Вам сделать это условие условием `while`?

2016-11-10 11:24 UTC, maximpetrov requested changes

2016-11-10 11:24 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Я имел ввиду, что можно `d` вообще убрать и находить остаток от деления на `i`.

2016-11-10 11:24 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Это ещё актуально, подумайте, чем ограничен сверху минимальный делитель числа, если оно не простое.

2016-11-10 11:24 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var z = y / factorial(k)
Зачем здесь факториал, ведь известно, чему равно `k`?

2016-11-10 11:24 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var z = 1.0 / factorial(k)
Зачем здесь факториал, ведь известно, чему равно `k`?

2016-11-10 23:30 UTC, maximpetrov requested changes

2016-11-10 23:30 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n / 2) {
Уже почти. Но можно ограничить ещё больше.

2016-11-11 08:01 UTC, maximpetrov commented
Принято

2016-11-11 08:01 UTC, closed without merging