4 lesson
Kotlin-Polytech/KotlinAsFirst2016 pull request #177
Opened 2016-10-20 16:49 UTC by Galentin

2016-10-24 15:24 UTC, maximpetrov requested changes

2016-10-24 15:24 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if (number / 1000 + (number % 1000) / 100 == (number % 100) / 10 + number % 10){
`if (x) return true else return false` эквивалентно `return x`

2016-10-24 15:24 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (abs == 0.0) {
Во-первых, сравнение `double` на `==` - плохая идея, Вы можете получить неожиданные ошибки. Во-вторых, зачем Вам вообще это сравнение, почему нельзя из 0 извлечь корень? Если Вы так обрабатываете пустой вектор, то вместо этого нужно проверить его на `isEmpty` причем в самом начале.

2016-10-24 15:24 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty())
Эта проверка должна быть в самом начале.

2016-10-24 15:24 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +            val element = list[i]
Временная переменная не нужна: `list[i] -= a`

2016-10-28 11:44 UTC, maximpetrov requested changes

2016-10-28 11:44 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (n % mindel != 0)
Вы уверены, что нужно перебирать все числа? Может быть можно выделить меньший диапазон?

2016-10-28 11:44 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    else return fib(n - 1) + fib(n - 2)
Такая рекурсивная реализация вычисления чисел Фибоначчи вызывает экспоненциальный рост количества вызовов этой функции (Посчитайте, сколько раз функция вызовется для n равного 50). Это и приводит к ошибке с таймаутом в функции `fibSequenceDigit`.

2016-10-28 11:44 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        chislo += digitNumber(fib(number))
Сохраняйте очередное вычисленное число, чтобы не вычислять его ещё раз.

2016-10-28 11:44 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        list.add(minDivisor(n2))
`minDivisor` каждый раз начинает поиск с 2 и проходит все множители, которые Вы уже проверяли.

2016-10-28 11:44 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val Months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список можно сделать общим для этой и следующей функций.

2016-10-28 11:44 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if ((parts[0].toInt() !in 1..31) || (parts[1].toInt() !in 1..12)) return ""
Сохраните переведённые в `int` значения, чтобы не переводить их несколько раз.

2016-10-28 11:44 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if ((parts[0].toInt() !in 1..31) || (parts.size != 3)) return ""
Сохраните переведённые в `int` значения, чтобы не переводить их несколько раз.

2016-10-30 18:04 UTC, maximpetrov commented
recheck all

2016-10-30 18:13 UTC, maximpetrov requested changes

2016-10-30 18:13 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    if (n == 2 || n ==1) return 1
Этот `if` не нужен, если возвращать `fib2`, а не `fib3`. А `fib3` лучше внести в цикл и сделать `val`.

2016-10-30 18:13 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            mindel += 2
Это хорошее улучшение, но я имел ввиду, что можно ограничить диапазон сверху.

2016-11-08 22:39 UTC, maximpetrov commented
recheck all

2016-11-08 23:22 UTC, maximpetrov requested changes

2016-11-08 23:22 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            mindel += 2
Все ещё актуально

2016-11-08 23:22 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        list.add(minDivisor(n2))
Ещё актуально

2016-11-08 23:22 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +                var part = parts[i - 1].toInt()
Во-первых, почему эта переменная `var`, а не `val`? Во-вторых, зачем она вычисляется на каждой итерации цикла, хотя не зависит от `j`? И в-третьих, этот цикл вообще не нужен, можно просто проверить `if ('+' in parts[i])`.

2016-11-08 23:22 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +        return dist < radius
Вы здесь не рассматриваете случай, когда точка лежит на окружности.

2016-11-08 23:22 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +        var adress = Segment(points[0], points[0])
Придумайте имя для переменной, которое отражало бы её назначение.

2016-11-23 08:18 UTC, maximpetrov commented
recheck all

2016-11-23 11:31 UTC, maximpetrov requested changes

2016-11-23 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        while (mindel < n/2 ) {
Можно сильнее ограничить перебор.

2016-11-23 11:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            if (n % mindel == 0) break
Здесь можно сразу вернуть результат

2016-11-23 11:31 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        if (isPrime(i) == true) {
Лучше не стало: `isPrime` тоже перебором проверяет все делители до этого числа. Нужно ли вообще проверять, что делитель простой?

2016-11-23 11:31 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    for (i in 1..n) {
Перебор можно сильнее ограничить сверху.

2016-11-23 11:31 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        while (i < parts.size) {
Неплохо бы проверить, что число строк после разбиения нечётное, то есть нет какого-нибудь элемента в конце, который вы отбросите не рассматривая.

2016-11-23 11:31 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +                "-" -> result -= parts[i].toInt()
А что, если там не + и не -?

2016-11-23 11:31 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +        var addresSegment = Segment(points[0], points[0])
Лучше не стало

2016-11-23 11:31 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    val middle =  circleByDiameter(Segment(a, b)).center
Создавать круг, чтобы найти середину отрезка не очень хорошо, лучше тогда уж написать функцию нахождения середины отрезка и использовать её тут и в `circleByDiameter`.

2016-11-25 09:13 UTC, maximpetrov requested changes

2016-11-25 09:13 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        while (mindel < n/3 ) {
Можно ограничить ещё сильнее

2016-11-25 09:13 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if (mindel >= n/3) return n
Зачем теперь этот `if`?

2016-11-25 09:13 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    for (i in 2..n/2) {
Перебор можно ограничить ещё сильнее

2016-11-25 09:13 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    val middle =  circleByDiameter(Segment(a, b)).center
Ещё актуально

2016-11-25 09:13 UTC, maximpetrov commented on src/lesson7/task1/Matrix.kt
> +fun <E> createMatrix(height: Int, width: Int, e: E): MatrixImpl<E> {
Несмотря на то, что Вы возвращаете реализацию матрицы, тип возвращаемого значения меняет не следует.

2016-11-25 21:44 UTC, mglukhikh commented
recheck all

2016-12-01 17:03 UTC, Galentin commented on src/lesson3/task1/Loop.kt
> +        if (mindel >= n/3) return n
If проверяет число на простоту. Если его убрать, то при вводе простого числа результат будет неверным
Подскажите, пожалуйста, как еще сильнее можно ограничить диапазон в minDivisor  и factorize

2016-12-01 19:31 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if (mindel >= n/3) return n
- Если бы число не было простым, то Вы нашли бы делитель внутри цикла, сразу его вернули и не попали бы сюда вообще.
- Если число не простое, то у его минимального простого делителя (и у любого другого делителя) есть парный (не обязательно простой), то есть такой, чтобы при перемножении этих делителей получалось исходное число. Этот парный делитель больше минимального (иначе минимальным был бы он сам). Вы перебираете до `n/3`, то есть до того возможного делителя, парным которому было бы 3. 3 почти всегда будет меньше `n/3`, то есть минимальным делителем `n/3` быть не может. Подумайте какую границу можно взять исходя из этих рассуждений.

2016-12-14 17:24 UTC, Galentin commented
recheck all

2016-12-14 17:32 UTC, Galentin commented
Checkme

2016-12-14 20:03 UTC, maximpetrov requested changes

2016-12-14 20:03 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if (mindel > Math.sqrt(n.toDouble())) return n
Ещё раз: может ли программа попасть сюда, когда `mindel` будет меньше или равен корню из `n`?

2016-12-19 07:51 UTC, maximpetrov commented
recheck all

2017-07-26 18:23 UTC, closed without merging