5th lesson
Kotlin-Polytech/KotlinAsFirst2016 pull request #178
Opened 2016-10-20 16:57 UTC by grafovdenis

2016-10-24 16:57 UTC, mglukhikh requested changes
В целом всё очень хорошо, решения верные, имеются отдельные замечания по стилю.

2016-10-24 16:57 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        for (i in 0..listOfMonths.size - 1) {
Для этого есть `list.indexOf`.

2016-10-24 16:57 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        val parts = str.split(" ")
Может быть, если вы уж применяете регулярное выражение, лучше сразу же и разбить его на отдельные группы, и не делать потом отдельно `split`?

2016-10-24 16:57 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        val parts = digital.split(".")
См. выше по поводу Regex / split

2016-10-24 16:57 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        for (i in 0..parts.size - 1) {
Здесь лучше так: `for (part in parts) { ... }`, не занимаясь перебором индексов. Так короче, а во многих случаях также быстрее (например, у линейного списка индексация может требовать числа операций, пропорционального индексу).

2016-10-24 16:57 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        for (element in listOfHits) {
Здесь можно так: `return listOfHits.max() ?: -1`. `list.max()` возвращает максимальный элемент списка, а для пустого списка `null`. Элвис-оператор `?:` подставит вместо `null` правую часть (-1), сохранив левую часть в неприкосновенности, если там не `null`. Завтра на лекции расскажу про это подробнее

2016-10-24 18:08 UTC, grafovdenis commented on src/lesson5/task1/Parse.kt
> +        val parts = str.split(" ")
То есть сначала разбивать на группы через regex, а затем ловить исключения, я  правильно понял?

2016-10-25 14:19 UTC, grafovdenis commented on src/lesson5/task1/Parse.kt
> +        val parts = str.split(" ")
`fun dateStrToDigit(str: String): String {
    val matchResult = Regex("""\d+\s[а-я]+\s\d+""").find(str) ?: return ""
    val parts = str.split(" ")
    val day = parts[0].toInt()
    val month = listOfMonths.indexOf(parts[1]) + 1
    val year = parts[2].toInt()
    return if (day in 1..31 && month != 0)
        String.format("%02d.%02d.%d", day, month, year)
    else ""
}`
Такой рефакторинг имеет место быть, или это не совсем то, что Вы просили?

2016-10-28 13:05 UTC, mglukhikh reviewed
Не считая нескольких незначительных замечаний, всё в порядке. Пожалуйста, исправьте их в следующем PR.

2016-10-28 13:05 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                toBreak = true
Почему бы здесь сразу же не написать return?

2016-10-28 13:05 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        val listOfRoman = mutableListOf("M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I")
Здесь лучше `mapOf`, но мы его ещё не проходили. Если вам интересно, разберитесь сами. Ну и лучше, конечно, просто `listOf`, а не `mutableListOf`.

2016-10-28 13:05 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                if (pricesList[i] >= maxPrice && pricesList.size != 1) {
Проверка на размер здесь не нужна

2016-10-28 13:05 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            for (i in 0..pricesList.size - 1) {
Ещё лучше `for ((i, price) in pricesList.withIndex()) { ... }`

2016-10-28 13:05 UTC, closed without merging