Lesson 4 (+1cm fix)
Kotlin-Polytech/KotlinAsFirst2016 pull request #181
Opened 2016-10-22 18:40 UTC by KamikoFuroraru

2016-10-24 12:29 UTC, ice-phoenix requested changes
Все довольно неплохо, исправляйте замечания и можно работать дальше

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        ((vershoks * 4.445 + arshins * 16* 4.445 + sagenes * 48* 4.445) / 100)
Лишние скобки вокруг законченного выражения

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        (( grad +(( min + sec / 60.0) /60.0)) * Math.PI /180)
Почему здесь открывающие скобки внезапно испугались и отделились от остальных частей пробелами?

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun thirdDigit(number: Int) = (number/100)%10
Пожалуйста, старайтесь придерживаться **единого стиля кодирования** везде. Представьте, что за вашим кодом следит психопат с обсессивно-компульсивным синдромом по поводу правильного форматирования кода и что он знает, где вы живете.

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (k + k*0.01*percent) + (k + k*0.01*percent)*0.01*percent
Это выражение можно упростить еще дальше

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((age / 10) % 10 == 1)
Этот `if` может быть частью следующего за ним `when`

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (s / 2 <= s1) return (s / 2) / v1
Данное выражение лучше оформить как `when`

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (kingX != rookX1) && (kingX != rookX2) && (kingY != rookY1) && (kingY != rookY2) -> 0
Выражения, соответствующие факту атаки короля той или иной ладьей, следует вынести в отдельные переменные

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if ((kingX != rookX) && (kingY != rookY)
* Данное выражение лучше оформить как `when`
* Факты атаки короля ладьей или слоном следует вынести в отдельные переменные

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val cosA = (b * b + c * c - a * a) / (2 * b * c)
Достаточно посчитать косинус угла против максимальной стороны треугольника

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val f = (number / 1000) % 10
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (x1 == x2) || (y1 == y2) || (x1 + y1 == x2 + y2) || (x1 - y1 == x2 - y2)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) + r1) <= r2
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (a <= r) && (b <= s) || (a <= r) && (c <= s) ||
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var m0 = m
Нахождение GCD лучше вынести в отдельную функцию и просто воспользоваться ею здесь

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var d = n - 1
Нет ли более точной верхней границы для всех возможных делителей числа `n`?

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return m0 == 1
Если бы у вас была отдельная функция для поиска НОД, то данная функция выглядела бы **намного** проще

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = Math.sqrt(n.toDouble()).toInt()
Для округления чисел типа `Double` следует использовать специальные функции `floor / ceil / round`

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (k * k <= n) {
Можно ли обойтись вообще без цикла при решении данной задачи?

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var n0 = n
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            p = num % 10
Зачем при решении данной задачи вам менять `p`, с которым вы сравниваете все остальные числа?

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var q = 0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        q += digitNumber(fib(i))
Значение `fib(i)` не следует считать несколько раз

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (v.isEmpty()) return 0.0
Если убрать эту проверку, сколько раз будет выполнено тело цикла ниже и что вернет ваша функция?

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Зачем эта проверка?

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var C = 0.0
Называть переменные с большой буквы в Котлине не принято

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (p.isEmpty()) return 0.0
Зачем эта проверка?

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var Z = 0.0
* Называть переменные с большой буквы в Котлине не принято
* Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-24 12:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result.add(minDivisor(n0))
Повторно используемые выражения (тем более, содержащие вызовы тяжелых функций) следует вынести в отдельные переменные

2016-10-26 19:14 UTC, furoraru commented on src/lesson4/task1/List.kt
> +    if (v.isEmpty()) return 0.0
^-^

2016-10-27 16:59 UTC, KamikoFuroraru commented on src/lesson4/task1/List.kt
> +        result.add(minDivisor(n0))
Извините, но я плохо понимаю, как это можно исправить, ведь переменная, которая вызывается в тяжелой функции, меняется в цикле ;c

2016-10-27 17:42 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result.add(minDivisor(n0))
А что вам мешает определить эту переменную прямо в цикле?

2016-10-27 17:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (v.isEmpty()) return 0.0
(╯°□°）╯︵ ┻━┻

2016-10-27 21:52 UTC, KamikoFuroraru commented
Я не могу загрузить изменения из-за ошибки, что делать? 

Push failed
			Failed with error: Error: Could not find or load main class org.jetbrains.git4idea.http.GitAskPassApp
			error: unable to read askpass response from 'C:\Users\Алиса\.IdeaIC2016.2\system\tmp\intellij-git-askpass.bat'
			error: failed to execute prompt script (exit code 1)
			fatal: could not read Username for 'https://github.com': No error

2016-10-28 10:11 UTC, ice-phoenix commented
Можете приложить лог идеи (`Help->Show Log in...`)?

2016-10-28 10:34 UTC, KamikoFuroraru commented
![1](https://cloud.githubusercontent.com/assets/22070439/19803758/8b00810c-9d1b-11e6-83b0-556bdca6ab1a.jpg)

2016-10-28 10:44 UTC, ice-phoenix commented
Я, конечно, обладаю телепатическими и экстрасенсорными способностями, но по фотографии открытого Explorer'а с файлом понять, что в этом самом файле, не могу. Можно все-таки получить сам файл idea.log?

2016-10-28 10:48 UTC, KamikoFuroraru commented
[2.txt](https://github.com/Kotlin-Polytech/KotlinAsFirst2016/files/558171/2.txt)

2016-10-28 10:56 UTC, ice-phoenix commented
Проверьте, пожалуйста, что в настройках IntelliJ IDEA указан правильный путь к установленному `git`

2016-10-28 11:00 UTC, KamikoFuroraru commented
![image](https://cloud.githubusercontent.com/assets/22070439/19804415/403134f6-9d1f-11e6-9145-0e1137a62a82.png)

2016-10-28 11:02 UTC, ice-phoenix commented
А если попробовать жамкнуть `Test`, что будет?

2016-10-28 11:03 UTC, KamikoFuroraru commented
![image](https://cloud.githubusercontent.com/assets/22070439/19804480/a3043394-9d1f-11e6-8483-7fc9c9eb0bc3.png)

2016-10-28 11:05 UTC, ice-phoenix commented
А давайте вы теперь снова попробуете сделать Git push и покажете новый лог после этого

2016-10-28 11:07 UTC, KamikoFuroraru commented
Я не могу сделать пуш снова, потому что: 
![image](https://cloud.githubusercontent.com/assets/22070439/19804566/27042154-9d20-11e6-9b7f-7652c70d2bc4.png)

2016-10-28 11:08 UTC, ice-phoenix commented
`VCS -> Git -> Push`?

2016-10-28 11:10 UTC, KamikoFuroraru commented
![image](https://cloud.githubusercontent.com/assets/22070439/19804625/837433de-9d20-11e6-9e2b-3df2ae29992d.png)
[2.txt](https://github.com/Kotlin-Polytech/KotlinAsFirst2016/files/558206/2.txt)

2016-10-28 11:18 UTC, ice-phoenix commented
Попробуйте переуказать ваши данные для GitHub и попробуйте снова

2016-10-28 11:19 UTC, KamikoFuroraru commented
Эти?
![image](https://cloud.githubusercontent.com/assets/22070439/19804834/ea7dc0b2-9d21-11e6-99ee-d2f716bcc4e5.png)

2016-10-28 11:20 UTC, ice-phoenix commented
Да, не помогло?

2016-10-28 11:21 UTC, KamikoFuroraru commented
Не помогло :с

2016-10-28 11:21 UTC, KamikoFuroraru commented
Может я что-то не так установила? (До этого работала на другом компьютере)

2016-10-28 11:22 UTC, KamikoFuroraru commented
У меня будет 3? т.т

2016-10-28 11:24 UTC, ice-phoenix commented
Ок, если это новый компьютер, как вы затянули свой проект на него? Скопировали всю папку с проектом или сделали `git clone`?

2016-10-28 11:26 UTC, KamikoFuroraru commented
Я устанавливала всё по инструкции из туториала, мне подгрузились все мои задачки, затем я просто стала их исправлять

2016-10-28 11:36 UTC, ice-phoenix commented
А если открыть консоль и попробовать сделать `git push origin master` из директории, в которой у вас лежит проект?

2016-10-28 11:38 UTC, KamikoFuroraru commented
Как это сделать?

2016-10-28 11:43 UTC, ice-phoenix commented
Это я точно вам тут не объясню. Можно попробовать удаленно зайти к вам на машину через https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp, но это супер тяжелая артиллерия =)

2016-10-28 11:44 UTC, KamikoFuroraru commented
Я через консоль могу зайти в папку, но что делать дальше?

2016-10-28 11:46 UTC, ice-phoenix commented
Дальше попробовать выполнить `B:\Program Files\Git\Git\bin\git.exe push origin master`

2016-10-28 11:48 UTC, KamikoFuroraru commented
У меня ещё TeamViewer есть :)

2016-10-28 11:51 UTC, ice-phoenix commented
У меня его нет =)

2016-10-28 11:54 UTC, KamikoFuroraru commented
Хорошо, я установила вышескинутое

2016-10-28 11:56 UTC, ice-phoenix commented
Запустите CRD в режиме шаринга и скиньте мне Access Code на почту `akhin[at]kspt.icc.spbstu.ru`

2016-10-28 12:09 UTC, KamikoFuroraru commented
Я отправила
А ещё там есть тайм-аут

2016-10-28 13:39 UTC, KamikoFuroraru commented
OH MY GOD

2016-10-28 13:39 UTC, KamikoFuroraru commented
OH MY GOD

2016-11-01 05:25 UTC, KamikoFuroraru commented
Посмотрите пожалуйста ^^

2016-11-01 16:23 UTC, KamikoFuroraru commented
Посмотрите пожалуйста ^^

2016-11-02 12:21 UTC, ice-phoenix requested changes

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        (vershoks * 4.445 + arshins * 16 * 4.445 + sagenes * 48 * 4.445) / 100
Можно слегка упростить выражение с учетом математических законов

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val bc = sqr(b) + sqr(c)
Проще сперва найти максимальную сторону, а потом все считать относительно нее

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        (Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) + r1) <= r2
Лишние скобки вокруг законченного выражения

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun GCD(a: Int, b: Int): Int { /**алгоритм Евклида*/
В Котлине принят `camelCase`

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (curA > curB) curA %= curB
Может быть, можно огранизовать код так, чтобы `curA >= curB` выполнялось всегда?

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int = Math.abs(m * n) / GCD(m, n)
Зачем `abs`?

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return if (GCD(m, n) == 1) true
- Выражение `if (cond) true else false` можно заменить на `cond`
- Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val dif = curN.toInt() - curM.toInt()
Для округления следует использовать специальные функции `floor / ceil / round`, и если применить правильную, то можно значительно упростить код ниже

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        }
Может быть, тут можно обойтись возведением в степень? Через свеже-вами-написанную функцию `pow(Int, Int): Int`?

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        }
См. замечание выше

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
Лучше список строк или `StringBuilder`

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        p += digits[i] * Math.pow(base.toDouble(), (digits.size - 1 - i).toDouble()).toInt()
Напишите `pow(Int, Int): Int`

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if ((day in 30..31) && (month == 2)) return ""
А почему мы проверяем на допустимость только число дней в феврале?

2016-11-02 12:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return String.format("%02d.%02d.%d", day, month, year)
В подобных функциях обычно проверяют данные на невалидность и возвращают соответствующее значение, а в самом конце возвращают результат, если все хорошо

2016-11-02 19:14 UTC, KamikoFuroraru commented on src/lesson5/task1/Parse.kt
> +        if ((day in 30..31) && (month == 2)) return ""
Потому, что только в феврале никогда не может быть 30 и 31 числа (не считая, по предположениям, 30 февраля 3328 года), или, имеется ввиду, что если ввести 31 февраля, то программа должна работать?

2016-11-02 19:16 UTC, KamikoFuroraru commented on src/lesson5/task1/Parse.kt
> +        if ((day in 30..31) && (month == 2)) return ""
Или, вы хотите сказать, что..нужно проверять високосный ли год?

2016-11-02 20:34 UTC, KamikoFuroraru commented on src/lesson3/task1/Loop.kt
> +        if (curA > curB) curA %= curB
??

2016-11-14 11:31 UTC, ice-phoenix requested changes

2016-11-14 11:31 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when (max) {
Лучше как
```
val cos = when (max) { ... }
```

2016-11-14 11:31 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i in m..n) return true
Решить задачу без циклов =)

2016-11-14 11:31 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun powInt(x: Int, y: Int): Int {
Функцию следует назвать `pow`

2016-11-14 11:31 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    }
Весь этот цикл можно заменить на `list.any / list.all` или на регулярное выражение

2016-11-14 11:31 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return phone.filter { (it in '0'..'9') || (it == '+') }
Лишние скобки вокруг законченного выражения

2016-11-14 11:31 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val listOfPerm = listOf("", "-", "%", " ")
Лучше просто `nonPermittedSymbols`

2016-11-14 11:31 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: Exception) {
Лучше ловить максимально точное исключение, в данном случае, `NumberFormatException`

2016-11-14 11:31 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (('+' in parts[i]) && (parts[i - 1].toInt() > result)) result = parts[i - 1].toInt()
Как данный код проверяет корректность формата строки?

2016-11-15 07:08 UTC, KamikoFuroraru commented
Не понимаю, как вызвать функцию "diameter" в самой последней задачке, которой на вход тоже поступает множество точек
(Хочу выполнить действие: val theLargestSegment = diameter(vararg points)

2016-11-15 09:36 UTC, ice-phoenix commented
Let me google that for you: https://kotlinlang.org/docs/reference/functions.html

2016-11-18 20:04 UTC, KamikoFuroraru commented
(╥﹏╥)

2016-11-22 08:11 UTC, KamikoFuroraru commented
Check me pls!!

2016-11-23 10:48 UTC, mglukhikh commented
recheck all

2016-11-24 11:56 UTC, ice-phoenix requested changes

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        vershoks * 0.04445 + arshins * 16 * 0.04445 + sagenes * 48 * 0.04445
Можно вынести общий множитель

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (s / 2 > s1) && (s / 2 <= s1 + s2) -> t1 + (s / 2 - s1) / v2
Первую часть условия можно не проверять, вы уже ее проверили выше

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return if (difference >= 0) true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return ((i * i) / pow(10, curN - n)) % 10
Лишние скобки

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if ((parts.size != 3) || (day !in 1..31) || (month == 0)) return ""
Лучше проверить результат сплита на размер до того, как вы начинаете по нему ползать

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: Exception) {
Надо ловить наиболее точный вид исключения, который может здесь возникнуть

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: Exception) {
Надо ловить наиболее точный вид исключения, который может здесь возникнуть

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if ((parts.size != 3) || (day !in 1..31)) return ""
Лучше проверить результат сплита на размер до того, как вы начинаете по нему ползать

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return ""
Все это можно заменить на `any / all`

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if ((part !in permittedSymbols) && (part.toInt() > result)) result = part.toInt()
Все это можно заменить на `filter + map + max`

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +
Зачем?

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                    if (other[i, j] == map[Pair(i, j)]) return true
Почему бы просто не сравнить поля `map` на равенство друг с другом?

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                if (column < width - 1) sb.append(", ")
Чтобы избежать лишней (и довольно дорогой) проверки внутри цикла, обычно запятую добавляют всегда, а потом ее откусывают от `StringBuilder` после цикла

2016-11-24 11:56 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        return "$sb"
Лучше через `toString()` (string interpolation обычно используется для того, чтобы собрать сложную строку, а не просто сделать строку из одной переменной)

2016-11-25 12:26 UTC, ice-phoenix commented
Урок 7 посмотрю после того, как вы исправите остальные замечания к предыдущим урокам

2016-11-30 16:28 UTC, KamikoFuroraru commented
checkme

2016-12-01 17:36 UTC, KamikoFuroraru commented
checkme

2016-12-02 07:38 UTC, KamikoFuroraru commented
Checkme

2016-12-05 11:48 UTC, ice-phoenix commented
recheck all

2016-12-05 12:01 UTC, ice-phoenix requested changes

2016-12-05 12:01 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        return Point((b1 + b2) / tanDif, (a1 + a2) / tanDif)
Что будет, если `tanDif == 0.0`?

2016-12-05 12:01 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                    if (other.map == map) return true
Лучше не проверять всю матрицу на равенство всей другой матрице в каждой ячейке

2016-12-05 12:01 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +            sb.removePrefix(", ")
Почему `removePrefix`? Разве запятая в конце будет префиксом строки?

2016-12-05 12:01 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                    result[row, column] += matrix[i, j]
Подумайте над тем, нельзя ли переиспользовать результаты расчета одних подматриц при подсчете других

2016-12-05 12:01 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        for (j in 0..this.width - 1) this[i, j] = -this[i, j]
Форматирование кода

2016-12-05 16:51 UTC, KamikoFuroraru commented
ЧТО ЭТО?????? ЭТОГО НЕ БЫЛО, Я ВООБЩЕ ЭТО НЕ ТРОГАЛА

2016-12-07 15:19 UTC, ice-phoenix commented
recheck all

2016-12-07 15:51 UTC, ice-phoenix requested changes

2016-12-07 15:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (s / 2 <= s1 + s2) -> t1 + (s / 2 - s1) / v2
Лишние скобки

2016-12-07 15:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    else {
Тут можно без блока `else`

2016-12-07 15:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    else {
И тут тоже можно без блока `else`

2016-12-07 15:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    else {
Лишний-лишний-лишний `else`

2016-12-07 15:51 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    for (i in 0..points.size - 2)
Форматирование кода

2016-12-07 15:51 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +            if (other.map == map) return true
Может быть, эти два `if` можно объединить в один???

2016-12-07 15:51 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                    result[row, column] += matrix[i, j]
Все еще актуально

2016-12-07 15:58 UTC, ice-phoenix commented
recheck all

2016-12-12 20:49 UTC, KamikoFuroraru commented
recheck all

2016-12-14 10:16 UTC, KamikoFuroraru commented
Checkme!!

2016-12-14 15:59 UTC, ice-phoenix requested changes

2016-12-14 15:59 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        map[Pair(row, column)] = value
Почему мы не проверяем возможность выхода за границы?

2016-12-14 15:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            }
Чтобы не делать `when` в подобных случаях, обычно отдельным циклом проходятся по первой строке/столбцу матрицы, а потом уже идут вглубь

2016-12-14 15:59 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        for (string in substrings) {
Ужасное имя переменной

2016-12-14 15:59 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +            val parts = line.toLowerCase().split(string.toLowerCase())
Более правильно сделать это через `String.findAnyOf`

2016-12-14 15:59 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +                else result.set(string, result.get(string)!! + parts.size -1)
Лучше вместо всего этого использовать `Map.getOrElse`

2016-12-14 17:40 UTC, mglukhikh requested changes
У вас осталось минимум замечаний и один неработающий тест. Задач вы сделали много, а значит, близки к отличной оценке :)

2016-12-14 17:40 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (phone.matches(Regex("""[\d\s()+-]+"""))) phone.filter { it !in "()- " }
Есть ощущение, что это может работать неправильно, например, для `phone = "\t"` (табуляция). Табуляция с точки зрения рег-экса является пробельным символом, но не будет отфильтрована.

2016-12-16 14:26 UTC, KamikoFuroraru commented
Я отметила не то что хотела, поэтому так отправилось

2016-12-19 13:48 UTC, KamikoFuroraru commented
Я люблю программирование!!

2016-12-19 13:50 UTC, KamikoFuroraru commented
Спасибо.

2017-07-26 18:23 UTC, closed without merging