Lesson5
Kotlin-Polytech/KotlinAsFirst2016 pull request #182
Opened 2016-10-23 10:32 UTC by Lestwald

2016-10-25 11:33 UTC, ice-phoenix requested changes

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (sagenes * 48 + arshins * 16 + vershoks) * 4.445 / 100
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return grad * PI / 180 + min * PI / ( 180 * 60 ) + sec * PI / ( 180 * 3600 )
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return sqrt(sqr(x1 - x2) + sqr(y1 - y2))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((age / 10) % 10 == 1) return "$age лет" else {
Все лучше записать в один `when`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((a + b) <= c) || ((a + c) <= b) || ((b + c) <= a)) return -1 else {
Лучше сперва найти максимальную сторону, а потом все считать относительно нее

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (x1 == x2) || (y1 == y2) || (x1 + y1 == x2 + y2) || (x1 - y1 == x2 - y2)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) + r1) <= r2
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (a <= r) && (b <= s) || (a <= r) && (c <= s) ||
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((k % m == 0) && (k % n == 0)) break
Почитайте про более быстрые алгоритмы поиска НОК

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (mind <= n)
Нет ли более точной верхней границы для потенциальных делителей числа `n`, чем `n`?

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var maxd = n - 1
Нет ли более точной верхней границы для потенциальных делителей числа n, чем `n - 1`?

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return true
Нельзя ли данную функцию выразить через другие функции этого модуля?

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = Math.sqrt(m.toDouble()).toInt()
Для округления следует использовать специальные функции `floor / ceil / round`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (k * k <= n)
Можно ли обойтись вообще без перебора и цикла при решении этой задачи?

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (Math.abs(Math.pow(x1, i.toDouble()) / factorial(i)) >= eps)
Считать факториал несколько раз --- не очень хорошая идея. Повторно используемые выражения следует вынести в отдельные переменные.

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var num: Int
Почему переменная объявлена здесь?

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        val ex = powInt(10, currentN - n)
В Котлине можно объявлять несколько функций c одинаковым именем и разными типами аргументов --- данная функция должна называться `pow`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (currentN == n) return (i * i) % 10
Что сделает код ниже в случае, если `currentN == n`? Имеет ли смысл данная проверка?

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (currentN == n) return (fib(i)) % 10
Считать `fib(i)` несколько раз не очень хорошо

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        val ex = powInt(10, currentN - n)
См. замечания выше

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            result += element * Math.pow(x, k)
Вместо отдельной переменной `k` лучше воспользоваться циклом по списку с индексом через `list.withIndex()`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if ((number % i == 0) && isPrime(i)) {
Нет ли у вас отдельной функции, которая находит возможные делители какого-либо числа?

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return list.joinToString(separator = "*")
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            list = listOf(number % base)
Проще добавлять элементы в конец списка, а потом его развернуть при помощи `reverse() / reversed()`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
Вместо строки при необходимости частой конкатенации строк вместе лучше использовать список строк или `StringBuilder`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += (element * powInt(base, p))
`list.withIndex()`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val roman = listOf("I", "IV", "V", "IX", "X", "XL", "L", "XC", "C", "CD", "D", "CM", "M")
Вместо двух отдельных списков лучше использовать список пар

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            when (i) {
Весь этот `when` можно записать плоско и проще

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        listInt = listInt.subList(0, listInt.size - 3)
Изменяемая переменная несколько усложняет понимание кода, лучше здесь завести новую переменную с говорящим именем

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var listStr = numberBelowThousandToRussian(listInt.subList(Math.max(listInt.size - 3, 0), listInt.size), false)
Для частых добавлений к строке лучше использовать `StringBuilder` или список строк

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var listStr = numberBelowThousandToRussian(listInt.subList(Math.max(listInt.size - 3, 0), listInt.size), false)
Все подсписки, с которыми вы работаете, лучше вынести в отдельные переменные с нормальными именами

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (listInt.size > 2 && listInt[listInt.size - 2] == 1) listStr = listOf(thousands[2]) + listStr
Все это можно записать в виде одного плоского `when`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return String.format("%02d.%02d.%d", day, month, year)
Лучше воспользоваться string interpolation

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return String.format("%d %s %d", day, month, year)
Лучше воспользоваться string interpolation

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    catch(e: Exception) {
Ловить все исключения --- плохая идея, необходимо делать спецификацию допустимого исключения как можно более узкой

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    catch(e: Exception) {
Ловить все исключения --- плохая идея, необходимо делать спецификацию допустимого исключения как можно более узкой

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return result
Все это можно сделать через `filter{...}` и `max{...}`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        while (i <= parts.size - 1) {
`i < parts.size`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val parts = strLow.split(" ")
Можно обойтись без промежуточной переменной `strLow`

2016-10-25 11:33 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        while (i <= roman.length - 1) {
Весь этот код можно упростить, если воспользоваться `String.startsWith(...)` для определения того, подходит ли какая-либо римская цифра текущей позиции в строке

2016-10-25 11:33 UTC, ice-phoenix commented
recheck all

2016-11-22 15:18 UTC, ice-phoenix requested changes

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    max = Math.max(max, c)
Лучше как
```
val max0 = Math.max(a, b)
val min1 = Math.min(a, b)
val min2 = Math.min(max0, c)
val max = Math.max(max0, c)
```

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    max = Math.max(max, c)
:+1:

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    ((b < c) || (d < a)) -> -1
Лишние скобки вокруг законченных выражений

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int) = (x1 == x2) || (y1 == y2) || (x1 + y1 == x2 + y2) || (x1 - y1 == x2 - y2)
Длинная строка

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +                 x2: Double, y2: Double, r2: Double) = (Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) + r1) <= r2
Лишние скобки

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (mind <= Math.ceil(Math.sqrt(n.toDouble())))
Выражение для границы лучше посчитать один раз и сохранить в переменную

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var flag = false
Зачем эта переменная, почему нельзя сразу возвращать результат?

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (maxd >= Math.floor(Math.sqrt(n.toDouble())))
См. замечания выше

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (k * k in m..n)
Лишние скобки

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        i += 2
Нет ли какого-то взаимнооднозначного соответствия между `i` и `k`? Может быть, одну из них можно убрать?

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (Math.abs(Math.pow(x1, i.toDouble()) / factorial) >= eps)
Повторно вычисляемое выражение следует вынести в переменную

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    } while (Math.abs(Math.pow(x1, i.toDouble()) / factorial) >= eps)
См. замечания выше

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            num = number % 10
Зачем передвигать `num` с цифры на цифру?

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (p.isEmpty()) return 0.0
Лишняя проверка списка на пустоту

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += (element * pow(base, digits.size - index - 1))
Лишние скобки

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (i!= null) {
Форматирование кода

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val i = map.keys.findLast { it <= number }
Лучше искать в `entries`, чтобы сразу найти и ключ, и значение

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            result += map[i].toString()
Зачем `toString()`?

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (f) break
Почему сразу не сделать `break` там, где вы ставите `f` в `true`?

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in Math.max(list.size - 3, 0)..list.size - 1) {
Зачем цикл, если вы делаете разные вещи, если `i` принимает разные значения???

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (listInt.size > 3) {
Эту проверку можно убрать, если почитать, что вернет `subList`, если правая граница меньше левой

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val listBelowThousand = listInt.subList(Math.max(listInt.size - 3, 0), listInt.size)
Подобные штуки проще делать через `list.takeLast / list.dropLast`

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val listOfMonth = listOf("января", "февраля", "марта", "апреля", "мая", "июня",
Можно вынести на верхний уровень, чтобы не переобъявлять этот же список в функции ниже

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return String.format("%02d.%02d.%d", day, month, year)
Почему не `string interpolation`?

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return listOfJumpsInt.max() ?: -1
Все это можно записать в виде одной длинной цепочки как
```
return jumps
    .split(" ")
    .filter { it.matches(Regex("[0-9]+")) }
    .map { it.toInt() }
    .max() ?: -1
```

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        while (i < parts.size) {
Что будет, если в конце строки остался висящий знак операции (`1 + 2 +`)?

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var result = -1
Почему сразу не вернуть результат там, где надо?

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val listOfRoman = listOf("M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I")
Два связанных списка --- список пар

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                maxPrice = thingAndPrice[1].toDouble()
Повторно используемое выражение лучше вынести в отдельную переменную

2016-11-22 15:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var f = false
Не очень удачное имя переменной

2016-11-25 11:52 UTC, ice-phoenix commented
Урок 6 не будет проверен до тех пор, пока вы не исправите ВСЕ имеющиеся замечания к предыдущим урокам

2016-11-25 11:53 UTC, ice-phoenix commented
recheck all

2016-11-27 10:53 UTC, ice-phoenix requested changes

2016-11-27 10:53 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int) = grad * PI / 180 + min * PI / ( 180 * 60 ) + sec * PI / ( 180 * 3600 )
Форматирование кода

2016-11-27 10:53 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += minDivisor(number)
Зачем считать делитель два раза? Почему здесь вы решили не экономить и вызывать функцию два раза, а в функции `fibSequenceDigit` решили не вызывать функцию `fib`, а реализовали ее заново, чтобы не пересчитывать числа Фибоначчи повторно? Объясните свою логику, пожалуйста.

2016-11-27 10:53 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        listOfThousands.getOrNull(listOfThousands.size - 2) == 1 -> result = listOf(thousands[2]) + result
В обеих функциях, раз вы рассчитываете на определенный размер списка с цифрами числа, лучше достать все эти `list.getOrNull(magicExpression)` в отдельные переменные с нормальными именами

2016-11-27 10:53 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (parts.last() in listOf("+", "-")) throw IllegalArgumentException()
А если там внезапно буква?

2016-11-27 10:53 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    fun distance(other: Circle): Double = Math.max(other.center.distance(center) - (other.radius + radius), 0.0)
:+1:

2016-11-27 10:53 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    fun notation() = if (!inside()) "" else (column + 'a'.toInt() - 1).toChar() + "$row"
Зачем `toInt()`?

2016-11-27 10:53 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        if (!Square(column, row).inside()) throw IllegalArgumentException()
Повторно используемое выражение следует выносить в отдельную переменную самостоятельно

2016-12-17 11:42 UTC, mglukhikh commented
recheck all

2016-12-18 19:36 UTC, ice-phoenix commented
recheck all

2016-12-18 19:55 UTC, ice-phoenix requested changes

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        val num = number % 10
На будущее --- такие ветки `else` можно не писать как ветки `else`, потому что в `then` вы и так выходите из функции

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (i != null) {
* Ужасное имя переменной
* Допустим, что мы ничего не нашли в нашей `Map`. Что это значит с точки зрения нашего алгоритма?

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (thingAndPrice[1].toDouble() >= maxPrice) {
Нет ли у вас уже этого значение в переменной?

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        val row = notation[1].toString().toInt()
Есть способ получше сделать из символа соответствующее ему число

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +            result [row, column] = e
Лишний пробел

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        map[cell] = value
Почему мы (неявно) проверяем границы индексов при чтении, но не проверяем здесь при записи?

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                result[row, center] = Math.min(height, width) / 2 + 1
Часто используемые выражения лучше считать один раз и сохранять в переменные

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    val result = createMatrix(matrix.height, matrix.width, 0)
Нужна ли вам эта матрица?

2016-12-18 19:55 UTC, ice-phoenix commented on src/lesson8/task1/Files.kt
> +        if (previousChar in letters && map.containsKey(char)) writer.append(map[char] ?: ' ')
Есть структура побыстрее списка для операции определения вхождения элемента в множество

2016-12-18 19:58 UTC, ice-phoenix commented
Несмотря на оставшиеся замечания и отсутствие тестов (что очень-очень-очень плохо, на самом деле), оценку мы вам ставим "Отлично". Мои поздравления!

2017-07-26 18:23 UTC, closed without merging