решения 5го урока
Kotlin-Polytech/KotlinAsFirst2016 pull request #183
Opened 2016-10-23 18:47 UTC by KuzinaMari

2016-10-24 08:01 UTC, mglukhikh commented
recheck all

2016-10-24 08:13 UTC, mglukhikh requested changes
В целом очень хорошо. Однако, три задачи решены неверно (sin и cos из 3-го урока и flattenPhoneNumber из 4-го). Кроме этого, в задачах 4-го и 5-го урока вы часто дублируете код в ситуации, где можно было использовать списки. Прочитайте, пожалуйста, мои замечания и исправьте ошибки.

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                "декабря" -> "12"
В таких случаях обычно ПЕРЕД функцией заводится переменная, содержащая список названий месяцев:

```
val MONTH_NAMES = listOf("января", "февраля", "марта", ...)
```

после чего вы можете использовать `MONTH_NAMES.indexOf(parts[1]) + 1` для определения нужного вам номера месяца. Если результат `indexOf` равен -1 -- значит, название не соответствует ни одному из месяцев.

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                "12" -> "декабря "
А здесь вы можете использовать обращение по индексу к тому же массиву `MONTH_NAMES`.

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            result = result + parts[2].toInt().toString()
Почему не просто `result += parts[2]` ?

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            else result = parts[0].toInt().toString() + "."
Здесь и далее: `string.toInt().toString()` даёт тот же самый `string`, который был на входе

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        for (i in 1..phone.length - 1) {
Код этого цикла `for` здесь и ниже повторяется. Подумайте, как избежать повторения (можно его вынести в отдельную функцию или переписать код в этой так, чтобы дублирования не было).

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if ((string[i].toInt() > maxMax) && (checkPlus(string[i + 1]) == true)) {
Запись `someBoolean == true` в условии избыточна, можно (и нужно!) писать просто `someBoolean`.

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            for (i in 1..parts.size - 1 step 2) if (parts[i - 1] == "-") result -= parts[i].toInt()
Здесь лучше поставить фигурные скобки хотя бы для `for`, иначе непонятно, что к чему относится:

```
for (...) {
    if (...) result -= ...
    else result += ...
}
```

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            for (i in 2..parts.size - 1 step 2) if (parts[i - 1] == "-") result -= parts[i].toInt()
Код повторяется, подумайте, можно ли избежать повтора

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        (thousands100 == 1) -> result += "сто"
Здесь и далее, следовало записать константы `"сто"`, `"двести"` и последующие в списки и затем использовать обращение по индексу к этим спискам. Лучше определить их на верхнем уровне (перед функцией `russian`), например:

```
val HUNDREDS_LIST = listOf("сто", "двести", ...)
```

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        (hundreds == 1) -> result += ("C")
Логика этих трёх `when` одинакова. Подумайте, как можно избежать дублирования кода

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    if (phone[0].toString() == "+") {
Исходный номер может оказаться пустой строкой (см. сообщение бота)

2016-10-24 08:13 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(number) * 1000 > eps) {
У вас не проходят тесты бота для задач `sin` и `cos`. Проблема связана с понижением точности расчёта при увеличении `x` из-за увеличения необходимого числа членов ряда. Вы использовали в целом правильную идею (следует с самого начала уменьшить `x`, используя периодичность синуса), но неверно её реализовали. Прочитайте код внимательно и исправьте ошибки. NB: умножение на 1000 в цикле while ничего хорошего вам не даст.

2016-10-26 21:07 UTC, mglukhikh requested changes
Ага, спасибо, тесты вы поправили, остались только замечания по стилю.

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var string = str.toLowerCase().split(" ")
Очень неудачное название переменной. Любому читателю будет очевидно, что переменная с именем `string` имеет тип `String`, хотя в вашем случае это совершенно неверно -- её тип `List<String>`. Можно назвать её `parts` или `stringParts`, или ещё как-нибудь в таком духе.

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            return throw IllegalArgumentException("Description")
`return` здесь не нужен, IDEA вам его подсветит как недостижимый. Просто: `throw ...`.

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if ((expression == "") || ((expression[i] != '+') && (expression[i] != '-') && (expression[i] != ' ') && (expression[i] !in '0'..'9')))
Сравнение выражения с пустой строкой лучше вынести из цикла и записать как `expression.isEmpty()`, это быстрее, чем сравнение строк. Что касается цикла, то лучше записать его через перебор символов `for (char in expression)` и поставить фигурные скобки -- это улучшит читаемость

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var resultExpression = expression
Не понял назначение этой переменной. Чем плох просто `expression`?

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        throw IllegalArgumentException()
В таком виде блок `catch` не имеет особого смысла, так как бросает дальше то же самое исключение, которое ловит. Возможно, поймать вы хотели `NumberFormatException` (и это как раз было бы правильно, так как контролировало бы нарушение формата строки)

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun checkPlus(str: String): Boolean {
В качестве упражнения: попробуйте написать эту функцию с помощью функции высшего порядка `any` (это её сократит примерно в 5 раз)

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var string = listOf<String>()
`stringList` или `strings`, но никак не `string`, поскольку переменная с названием `string` с очевидностью должна иметь тип `String`.

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        string = jumps.split(" ")
Лучше было бы определить переменную прямо здесь: `val stringList = ...`.

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if ((jumps == "")
Эту проверку лучше вынести из цикла

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..jumps.length - 1)
Лучше так: `for (jump in jumps) { ... }`

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..parts0.size - 1) result = Math.max(result, parts0[i])
Здесь всё получилось как-то сложно. Вначале вы выкинули из строки чёрточки и проценты, а потом получили проблему с возможными пустыми строками. Кроме этого, вполне можно обойтись без списка `parts0` и без двух отдельных циклов.

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..phone.length - 1)
`for (char in phone) { ... }`, и никаких индексов не нужно

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            for (i in 0..result.length - 1) if (result[i] !in '0'..'9') return ""
Эти две ветки очень похожи, необязательно их повторять полностью

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            else result = parts[0].toInt().toString() + "."
Это замечание остаётся в силе

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        (thousands100 == 1) -> result += "сто"
Это замечание остаётся в силе

2016-10-26 21:07 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if ((month1 != 0) && (month1 < 10)) {
Здесь можно использовать `String.format("%02d", month1)` для получения номера месяца из двух цифр

2016-10-27 20:26 UTC, mglukhikh requested changes
Стало лучше, но ещё, как видите, есть над чем работать. Особенно это касается функции `russian`.

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +import kotlin.system.exitProcess
Это лишнее

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..parts.size - 1)
Лучше `for (part in parts) { ... }`

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +val HUNDREDS1_LIST = listOf<String>("", "C", "CC", "CCC", "DC", "D", "CD", "CCD", "CCCD", "MC")
Лучше убрать 1 из всех этих имён. Кроме этого, не DOZENS (дюжины), а TENS (десятки)

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +val DOSENS_LIST = listOf("двадцать", "тридцать", "сорок", "пятьдесят", "шестьдесят", "семьдесят", "восемьдесят", "девяносто")
Здесь я бы использовал имена `TEENS_LIST` и `TENS_LIST`.

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (n3.length >= 3) result2 += HUNDREDS1_LIST[n3[2].toString().toInt()]//если есть и сотни, то тоже запишет римскими//
`n3[i] - '0'` было бы понятнее, чем `n3[i].toString().toInt()`.

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        (thousands100 == 9) -> result += HUNDREDS_LIST[8]
Мне кажется, эти 9 строчек можно превратить в одну

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        (thousands10 == 9) -> result += DOSENS_LIST[7]
Аналогично

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        ((thousands10 != 1) && (thousands == 9)) -> result += UNITS_LIST[8]
Аналогично (здесь, правда, скорее в две)

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        (hundreds == 9) -> result += HUNDREDS_LIST[8]
Аналогично

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        (dozens == 9) -> result += DOSENS_LIST[7]
Аналогично.

2016-10-27 20:26 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        ((dozens != 1) && (units == 9)) -> result += UNITS_LIST[8]
Аналогично

2016-11-02 12:19 UTC, mglukhikh commented
recheck all

2016-11-02 12:39 UTC, mglukhikh requested changes
Замечания, к моему сожалению, по-прежнему остаются

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +import java.util.function.IntToDoubleFunction
Используете ли вы эту функцию? Если нет, то импорт нужно удалить

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
For-each: `for (element in v) { result.add(element * element) }`. Ещё короче это можно записать с помощью функции высшего порядка `map`.

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    } else
Действительно ли нужна эта ветка `else`? Впечатление, что она полезна только для случая с `n = 0`. А его можно обработать проще в начале функции

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            result1 += (result[i] + 87).toChar()
Что такое 87? Замените это на соответствующий символ

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        val ss = (numbers[i] * Math.pow(base.toDouble(), i.toDouble())).toInt()
Здесь лучше написать свою функцию `pow` для целых чисел, а не заниматься конвертацией вначале в `Double`, а потом в `Int`. Помимо того, что некрасиво, вы можете здесь нарваться на ошибку округления

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        else list += ((string1[i]).toInt() - 87)
48, 87 -- что они значат? Подставьте вместо них соответствующие символы

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..string1.length - 1)
Здесь лучше использовать for-each: `for (char in srting1) { ... }`.

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var string1 = str
Зачем `string1`, чем вас `str` не устраивает?

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +import kotlin.system.exitProcess
Мне кажется, этот импорт не нужен

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (maxI == -1) return -1 else return stringList[maxI].toInt()
Здесь стоило использовать `maxMax`, раз уж вы её создали. И можно обойтись совсем без переменной `maxI`

2016-11-02 12:39 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun checkPlus(str: String): Boolean = str.any { str == "+" }
`str.any { it == "+" }`. `str` -- это название параметра `checkPlus`. А `it` -- это название единственного параметра лямбды (в том случае, если оно не указано явно, как например здесь: `str.any { char -> char == "+" }`). По-видимому, из-за этой ошибки у вас сейчас не проходят тесты `bestHighJump`

2016-11-02 12:39 UTC, mglukhikh commented on test/lesson4/task1/Tests.kt
> +        assertEquals("сто одиннадцать тысяч пятьсот восемь", russian(111508))
На будущее: никогда не исправляйте имеющиеся тесты на новые. Лучше оставить старый тест, и добавить новый. Тогда вы проверите оба случая

2016-11-24 20:18 UTC, KuzinaMari commented
Извините пожалуйста, совсем не понимаю, почему в Уроке 6.2 не проходят проверку задачи. Исключение не ловится? Получается нужен catch..?

2016-11-25 07:21 UTC, mglukhikh commented
Вы кидаете не то исключение. Нужно IllegalArgument..., а вы кидаете IllegalAccess...

2016-11-25 19:04 UTC, mglukhikh commented
recheck all

2016-11-25 19:30 UTC, mglukhikh commented
recheck all

2016-11-25 19:34 UTC, mglukhikh requested changes
Код довольно грязный плюс неверно работает `flattenPhoneNumber`. Пожалуйста, исправьте замечания, прежде чем двигаться дальше

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var n2: Int = n
Тип локальных переменных указывать не требуется

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var i: Int = 2
Тип локальных переменных указывать не требуется

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var count: Int = 1
Тип локальных переменных указывать не требуется

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var failed: Boolean = false
Тип локальных переменных указывать не требуется

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (failed == true) return false else return true
Эту чудо-конструкцию можно записать гораздо короче

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        else false
Вспомните то, что рассказывал на последней лекции Марат Халимович, и напишите эту функцию нормально. Выглядит это абсолютно страшно

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (result == n) return true else return false
Эта функция очень похожа на `revert`. Попробуйте написать одно через другое

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (indicator == false) return true else return false
Эту конструкцию можно записать гораздо короче

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var indicator = true
Зачем нужна эта переменная?

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +import java.util.function.IntToDoubleFunction
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val arithmeticaverage = sum / count
`camelCase`: `arithmeticAverage`. А ещё лучше просто `mean`. И не забывайте, что выше вы уже написали эту функцию

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i: Int in 0..list.size - 1) {
Указание индекса здесь не нужно

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    } else
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            result1 += (result[i] + 87).toChar()
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        val ss = (numbers[i] * Math.pow(base.toDouble(), i.toDouble())).toInt()
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var string1 = str
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..string1.length - 1)
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        else list += ((string1[i]).toInt() - 87)
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var result2: String = ""
Типы указывать не требуется. Неудачные названия переменных

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +val HUNDREDS_LIST = listOf<String>("", "C", "CC", "CCC", "DC", "D", "CD", "CCD", "CCCD", "MC")
Типовой параметр `String` указывать не нужно, и так ясно, что это список строк

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        result += UNITS_LIST[units]
Данная функция состоит из двух практически повторяющихся фрагментов кода. Предлагаю вам вынести в отдельную функцию расчёт строкового представления для чисел от 1 до 999 и использовать её.

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +import kotlin.system.exitProcess
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun checkPlus(str: String): Boolean = str.any { str == "+" }
Замечание более не актуально

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (maxI == -1) return -1 else return stringList[maxI].toInt()
Это замечание всё ещё в силе

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        = Circle(Point(((diameter.begin.x + diameter.end.x) / 2), ((diameter.begin.y + diameter.end.y) / 2)), (diameter.begin.distance(diameter.end) / 2))
Очень длинная строка

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        return Math.atan(y / x)
Форматирование

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +fun corner(a: Point, b: Point): Double {
Тот угол, который вы имели здесь в виду, по английски называется `angle`. А `corner` -- это, например, угол футбольного поля или комнаты.

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    angle = angle - Math.PI  }
Форматирование

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        if (circles.size >= 2) {
См. условие: если в списке менее двух окружностей...

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        var indicator = 1
Нельзя ли обойтись без этой переменной?

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +            val list_lat = listOf("a", "b", "c", "d", "e", "f", "g", "h")
`"abcdefgh"`. Не нужно создавать списки символов там, где можно обойтись строкой

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    return Square(list_lat[notation[0]]!!, notation[1].toString().toInt())
Здесь всё можно сделать гораздо проще и изящнее, используя вычитание символов

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        }
`when` можно упростить. Кроме этого, поехало форматирование

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    result.add(Square(start.column, start.row))
Просто `result.add(start)`

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +                    if (other[i, j] != this[i, j]) return false
Вы можете просто сравнить списки

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return true
Этот результат неверен (вернее, верен не всегда), подумайте ещё раз, когда мы можем попасть в эту ветку

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +                bilder.append(this[row, column])
Вы не сможете что-либо понять в таком строковом представлении. Следует добавить какие-либо разделители между элементами строки (например, запятые или пробелы)

2016-11-25 19:34 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        val bilder = StringBuilder()
`builder`

2016-12-03 21:33 UTC, mglukhikh commented
Ваши изменения посмотрю несколько позже, но пока обратите внимание. что часть тестов не пройдена.

2016-12-06 11:38 UTC, mglukhikh requested changes
Осталась часть старых замечаний плюс появилось несколько новых. Четыре задачи не проходят тесты

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +import java.util.function.IntToDoubleFunction
Используете ли вы эту функцию? Если нет, то импорт нужно удалить

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        val ss = (numbers[i] * Math.pow(base.toDouble(), i.toDouble())).toInt()
Здесь лучше написать свою функцию `pow` для целых чисел, а не заниматься конвертацией вначале в `Double`, а потом в `Int`. Помимо того, что некрасиво, вы можете здесь нарваться на ошибку округления

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var string1 = str
Зачем `string1`, чем вас `str` не устраивает?

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..string1.length - 1)
Здесь лучше использовать for-each: `for (char in srting1) { ... }`.

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun less_thousand(a: Int, b: Int, c: Int, index: Int): String {
camelCase: `lessThousand`. Кроме этого, следует придумать более говорящие имена для параметров -- по смыслу a это сотни, b это десятки, c это единицы. Насчёт index сообразите сами.

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..phone.length - 1)
`for (char in phone) { ... }`, и никаких индексов не нужно

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            for (i in 0..result.length - 1) if (result[i] !in '0'..'9') return ""
Эти две ветки очень похожи, необязательно их повторять полностью

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[row, column])
При подобной реализации, у вас строчка матрицы из чисел 1, 23, 4, 56 будет добавлена в строку как 123456, и отдельные числа будет не различить

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            other is MatrixImpl<*> && height == other.height && width == other.width && list.equals(other.list)
Лучше `==` вместо `equals`

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            other is MatrixImpl<*> && height == other.height && width == other.width && list.equals(other.list)
Также, отсутствует функция `hashCode()`

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            result1 += (result[i] + 'a'.toInt()).toChar()
Вы здесь кое-что забыли. `result[i]` равное 10 должно превратиться в `'a'`, а у вас здесь получится `'a' + 10`

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    if ((notation.length == 2) && (notation[0] in 'a'..'h') || (notation[1] in '1'..'8' )) {
В этом условии напутано с логическими операциями, будьте внимательнее

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun myFun(coins: String, sum: Double): List<String> {
Пожалуйста, удалите эту функцию из проекта

2016-12-06 11:38 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun checkPlus(str: String): Boolean = str.any { str == "+" }
Эта функция возвращает `true`, если и только если `str == "+"`. Мне кажется, вы ожидали от неё другого поведения. Из-за этого, `bestHighJump` не проходит тесты

2016-12-14 12:45 UTC, mglukhikh commented
recheck all

2016-12-14 13:21 UTC, mglukhikh requested changes
Вы решили довольно много сложных задач, что хорошо, но стиль ваш не слишком хорош, что хуже. В принципе, замечаний осталось немного, вам осталось их исправить и решить что-нибудь из урока 7.2 (на четыре) и, также, из урока 8 (на пять).

2016-12-14 13:21 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        var indicator : Int = -2
Поехало форматирование

2016-12-14 13:21 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else indicator = 0
Переменная `indicator` не нужна в этой функции

2016-12-14 13:21 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        var rook2: Int = -2
По смыслу обе переменные `rookX` -- логические (есть ли угроза от ладьи? Да/Нет), значит, их и следует сделать таковыми

2016-12-14 13:21 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    n.toString().length
Зачем нужна эта операция?

2016-12-14 13:21 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        val ss = (numbers[i] * Math.pow(base.toDouble(), i.toDouble())).toInt()
Это замечание всё ещё в силе

2016-12-14 13:21 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        return -1
Поехало форматирование

2016-12-14 13:21 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +}
И опять поехало форматирование

2016-12-15 06:55 UTC, mglukhikh commented
recheck all

2016-12-15 07:04 UTC, mglukhikh reviewed
Замечания, пожалуйста, поправьте.

2016-12-15 07:04 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +fun edge(height: Int, width: Int, streamline: Direction): Cell {
Здесь лучше принимать `cell: Cell` как параметр, а не `height` и `width` отдельно. Посмотрите хотя бы на места, где вы вызываете эту функцию.

2016-12-15 07:04 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +    for (line in File(inputName).readLines())
Отсутствуют фигурные скобки

2016-12-15 07:04 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +        if (line.length <= 1) outputStream.write("$line\n") else {
`else` с новой строки, `outputStream.write` взять в фигурные скобки

2016-12-15 07:04 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +            for (char in 1..line.length - 1)
Опять отсутствуют фигурные скобки

2016-12-15 07:04 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +                else outputStream.write(line[char].toString())
`outputStream.write` с новой строки -- как в основной ветке `if`

2016-12-15 07:04 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +            outputStream.write("\n")
Здесь лучше использовать `newLine`, так как в разных ОС признаки перехода на новую строку разные

2016-12-15 07:27 UTC, mglukhikh commented
Обнаружены точные копии решений других студентов. Решение о выставлении оценки "Отлично" откладывается до выяснения обстоятельств.

2016-12-15 09:29 UTC, mglukhikh commented
Этот PR я закрываю, исправления меня более не интересуют. Увидимся на экзамене.

2016-12-15 09:29 UTC, closed without merging