Lesson 4. Task 1
Kotlin-Polytech/KotlinAsFirst2016 pull request #184
Opened 2016-10-24 06:21 UTC by Stupidman00

Использование глобальных переменных - это плохой стиль. Какие варианты решения данной проблемы есть в этом задании?

2016-10-24 08:45 UTC, Stupidman00 commented
Ошибку нашел. Понимаю как решить.

2016-10-25 12:27 UTC, mglukhikh commented
recheck all

2016-10-25 12:28 UTC, mglukhikh commented
Надеюсь, сегодня на лекции я ответил на ваш вопрос про глобальные переменные

2016-10-25 12:28 UTC, mglukhikh commented
Recheck all

2016-10-25 12:30 UTC, mglukhikh commented
recheck all

2016-10-25 12:47 UTC, mglukhikh requested changes
В целом, всё очень хорошо. Прошу исправить замечания по стилю.

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    else Math.sqrt(v.map { it * it }.sum())
Проверка на `isEmpty` здесь не нужна. Кроме этого, функцию можно было записать в виде expression body: `= Math.sqrt(v.map ...)`.

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        mutN/=base
Расставьте, пожалуйста, пробелы более аккуратно

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +                'u', 'v', 'w', 'x', 'y', 'z')
Вместо списков символов лучше использовать строки вроде `"01234..."`, тогда у вас будет поменьше одинарных кавычек.

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +val table: Map<Int,String> =
`Map<Int, String>`

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Здесь лучше писать так:

```
   for ((key, value) in table) {
        while (mutN >= key) {
            result += value
            mutN -= key
        }
    }
```

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var result: MutableList<String> = mutableListOf()
Дело вкуса, но мне `var result = mutableListOf<String>()` кажется короче

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        if (diclensionOfTripletWord.size == 3) {
Мне кажется, при наличии этой проверки проверка на `isNotEmpty()` избыточно

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +val table: Map<Int,String> =
И, кстати, явное указание типа здесь и для последующих `Map` вообще не требуется.

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun <T> List<T>.indexOf(value: T): Int {
Такая функция имеется в стандартной библиотеке

2016-10-25 12:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            newN = newN / minDivisor(newN)
Лучше использовать `+=` и `/=`

2016-10-27 08:39 UTC, mglukhikh commented
Спасибо за исправления, урок 4 принят.

2016-10-27 08:39 UTC, closed without merging