Sergeyprogramm
Kotlin-Polytech/KotlinAsFirst2016 pull request #186
Opened 2016-10-24 12:14 UTC by Sergeyprogramm

Lesson 4 (convert, convertToString, roman)

2016-10-24 14:56 UTC, mglukhikh commented
recheck all

2016-10-24 15:34 UTC, maximpetrov commented
recheck all

2016-10-24 16:03 UTC, maximpetrov requested changes

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if (((r>=a) && (s>=b)) ||
`if (x) return true else return false` эквивалентно `return x`.

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if (((r>=a) && (s>=b)) ||
Если сначала найти наименьшие стороны кирпича, то условие станет намного проще.

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun digitNumber(n: Int): Int {
Эта функция не работает, как видно из тестов.

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    num = square.toDouble() / Math.pow(10.0, (a).toDouble())
Нехорошо использовать `double` в целочисленных задачах, можете наткнуться на проблемы с точностью. Лучше напишите свою функцию `pow` для целых чисел.

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if (((r>=a) && (s>=b)) ||
Выравнивание

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var number = n
Выравнивание

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +     var result = listOf<Int>()
`List` - неизменяемый список, то есть в него нельзя добавлять элементы. Поэтому, когда Вы складываете два таких списка, создаётся новый. Гораздо эффективнее для постепенного заполнения списка использовать изменяемый список (`MutableList`).

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +              if (element > 9) result += ('a' + element - 10).toChar()
`toChar()` не нужен

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var number = n
Выравнивание

2016-10-24 16:03 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +      var result = ""
Выравнивание

2016-11-07 12:40 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun digitNumber(n: Int): Int {
В этой функции всё ещё бесконечный цикл, который не позволяет тестам пройти до конца

2016-11-07 12:40 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    fun pow(number: Int, degree: Double): Int {
Вынесите эту функцию из `squareSequenceDigit`, она Вам ещё может понадобиться.

2016-11-07 12:40 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    fun pow(number: Int, degree: Double): Int {
Почему у Вас показатель степени дробный?

2016-11-07 12:40 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +     var result = listOf<Int>()
Всё ещё в силе

2016-11-07 12:40 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +      var result = ""
Всё ещё в силе

2016-11-07 12:41 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +              if (element > 9) result += ('a' + element - 10).toChar()
Всё ещё в силе

2016-11-14 15:33 UTC, maximpetrov requested changes

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((c in a..b) && (b in c..d))
Выравнивание. Кроме того, здесь можно было бы воспользоваться `when`.

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        n > 2 -> fib(n - 2) + fib(n - 1)
Эта рекурсивная реализация слишком неэффективна. Посчитайте, сколько раз вызовется функция `fib` при вычислении fib(50) и сколько вызовов будут с одним и тем же аргументом.

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    fun pow(number: Int, degree: Double): Int {
Во-первых, вынесите эту функцию "наружу" (т.е. сделайте её на одном уровне с остальными функциями), т.к. она может понадобится Вам не только здесь. Во-вторых, почему у Вас показатель `double`? Разве Вы можете посчитать степень для нецелого показателя?

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    return (square / pow(10, count.toDouble()) % 10).toInt()
Зачем Вам здесь `toInt()`, если у Вас везде целые числа?

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +@file:Suppress("UNUSED_PARAMETER", "ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE", "UNUSED_VALUE", "UNUSED_VALUE")
Вместо того, чтобы игнорировать соответствующие подсказки, лучше прислушайтесь к ним.

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var result = listOf<Int>()
Ещё раз повторяю, используйте `MutableList`.

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var List : List<Int>
Зачем Вам эта переменная?

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +       for (element in convert) {
Выравнивание

2016-11-14 15:33 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var result = ""
StringBuilder

2016-11-21 15:05 UTC, maximpetrov requested changes

2016-11-21 15:05 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(Math.pow(f, i.toDouble())) / factorial(i) >= eps) {
Сохраняйте вычисленный член ряда в переменную, чтобы не вычислять его дважды. А ещё лучше вычисляйте его из предыдущего члена.

2016-11-21 15:05 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        val parse = map1.toSortedMap().entries.findLast { it.key <= number }.toString().split("=")
Зачем такое сложное получение элементов `map`?

2016-11-21 15:05 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        val parse = map1.toSortedMap().entries.findLast { it.key <= number }.toString().split("=")
Храните отсортированный `map` сразу, вместо того, чтобы сортировать его каждый раз

2016-11-21 15:05 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val matchResult = Regex("""[^-0-9+()\s]""").find(phone)
Если уж пользуетесь регулярными выражениями, то пользуйтесь ими как следует: здесь можно проверить формат выражения целиком, а не просто найти запрещённые символы.

2016-11-21 15:05 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val phoneList = phone.split(" ", "-", "(", ")")
Вместо разбиения и дальнейшего соединения можно воспользоваться функцией `filter`.

2016-11-21 15:05 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    return result.sorted()[result.size - 1]
Эффективнее воспользоваться функцией `max`.

2016-11-21 15:05 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            if ((j == '+') && (best < parts[part - 1].toInt())) best = parts[part - 1].toInt()
Можно использовать `'+' in parts[part]`

2016-12-05 17:49 UTC, maximpetrov commented
Перед тем как переходить к 7 уроку, исправьте замечания к предыдущим урокам.

2016-12-19 07:28 UTC, Sergeyprogramm commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(Math.pow(f, i.toDouble())) / factorial(i) >= eps) {
Я пытался отправить все исправления, но у меня вылезла ошибка "The requested URL retutned error: 403". Могу я на паре сегодня все исправить?

2016-12-19 07:30 UTC, mglukhikh commented
recheck all

2016-12-19 12:28 UTC, belyaev-mikhail commented
recheck all

2016-12-22 12:31 UTC, maximpetrov commented
Для получения зачёта Вам нужно решить несколько задач из 8 урока.

2016-12-22 12:36 UTC, Sergeyprogramm commented
до какого момента мне надо их сделать?


>Четверг, 22 декабря 2016, 15:31 +03:00 от Maxim Petrov <notifications@github.com>:
>
>Для получения зачёта Вам нужно решить несколько задач из 8 урока.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-12-22 12:39 UTC, maximpetrov commented
До экзамена

2016-12-22 12:44 UTC, Sergeyprogramm commented
А я могу прийти завтра или в понедельник в 309 аудиторию, либо в любой другой день, когда эта аудитория будет открыта, чтобы отправить задачи на гитхаб? В последний раз со своего компьютера у меня не получилось отправить. 


>Четверг, 22 декабря 2016, 15:39 +03:00 от Maxim Petrov <notifications@github.com>:
>
>До экзамена
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-12-22 12:56 UTC, maximpetrov commented
Приходите, если у Вас есть что оправлять

2017-01-14 20:02 UTC, maximpetrov requested changes
Для зачёта нужно минимум три задачи из 8 урока

2017-01-14 20:02 UTC, maximpetrov commented on src/lesson8/task1/Files.kt
> +        val document = File(inputName).readText().toLowerCase()
Зачем Вы для каждой подстроки считываете файл заново?

2017-01-14 20:02 UTC, maximpetrov commented on src/lesson8/task1/Files.kt
> +    var count = 0
Лучше объявление этой переменной перенести внутрь цикла.

2017-01-14 20:02 UTC, maximpetrov commented on src/lesson8/task1/Files.kt
> +        if (newRange == true) writer.newLine()
`if (x == true)` эквивалентно `if (x)`

2017-07-26 18:23 UTC, closed without merging