2 урок
Kotlin-Polytech/KotlinAsFirst2016 pull request #187
Opened 2016-10-24 12:16 UTC by Kir86russ

2016-10-24 15:01 UTC, maximpetrov requested changes

2016-10-24 15:01 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +        abs(((hoursDepart * 60) + minutesDepart) - ((hoursArrive * 60) + minutesArrive))
Вы вычитаете из времени отправления время прибытия, хотя должно быть наоборот. Не удивительно, что у Вас всегда получается отрицательное число, что Вы компенсируете ненужным модулем.

2016-10-24 15:01 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial + sqr(initial.toDouble()*percent/100)
Как видно из тестов, функция работает неправильно.

2016-10-24 15:01 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (age%10 == 1) return "$age год"
Во-первых, как видно из тестов, функция работает неправильно. Во-вторых, здесь лучше использовать конструкцию `when`.

2016-10-24 15:01 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +         if ((a in c..d) && (b in c..d)) return (b-a)
- Выравнивание
- Лучше использовать `when`
- Вместо `((a in c..d) && (b in c..d))` можно написать `(a..b in c..d)`
- Некоторые условия лишние

2016-10-25 10:59 UTC, mglukhikh commented
Кирилл, я вам поставил "3" за сентябрь потому, что на тот момент существовал только один ваш Pull Request с решённым первым уроком. По той же причине я написал о том, что вам следует начать делать уроки 2 и 3. Этот Pull Request вы создали ровно один день назад. До момента, пока Pull Request не создан, о наличии изменений в вашем репозитории никто из нас ничего не знает. В будущем, пожалуйста, не забывайте создавать Pull Request своевременно (а не через несколько недель после решения задач).

2016-10-25 12:42 UTC, maximpetrov requested changes
Кроме этих замечаний, есть замечание по стилю: пробелы не везде расставлены единообразно. Можете воспользоваться автоматическим форматированием кода (Ctrl+Alt+L)

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +     return a+b==c+d
Нарушено выравнивание

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        return n
Нарушено выравнивание

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Обязательно ли перебирать до `n`?

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +       return k
Нарушено выравнивание

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n-1) {
Почему при поиске наибольшего делителя Вы перебираете варианты от меньшего к большему?

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        return k
Нарушено выравнивание

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun countNumbers(n: Int): Int {  //подсчет кол-ва цифр в числе
Что Вам помешало реализовать функцию digitNumber из этого урока?

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +resalt = numberi * numberi
Нарушено выравнивание

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    return (resalt %10)
Скобки здесь лишние

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var resalt  :Int = 0
Так выравнивать не принято.

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (list.size == 0) return 0.0
У коллекций есть метод `isEmpty()`, который проверяет их на пустоту.

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (list.size == 0)
Во-первых, `if` без тела плохо сказывается на читаемости кода, лучше в таких случаях инвертировать условие и внутри `if` делать то, что было в `else`. Во-вторых, на пустоту стоило проверить ещё до вычисления среднего.

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +return list
Нарушено выравнивание

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var sumElements= 0.0
Подумайте, действительно ли Вам нужна эта временная переменная?

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    while (a % i ==0){
Нарушено выравнивание

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (i >= a) break
Это правильнее перенести в условие `while`.

2016-10-25 12:42 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        number = number + digits[i] * Math.pow(base.toDouble(), digits.size.toDouble() - i -1)
Нехорошо использовать `double` в целочисленных задачах. Лучше напишите свой целочисленный `pow` или попробуйте вообще обойтись без возведения в степень, с помощью математических преобразований.

2016-10-25 15:20 UTC, Kir86russ commented
понял, спасибо. Буду дорабатывать 
Почему я не могу "запулреквестить" это? Вы ведь будете выставлять оценку смотря на пул реквест, а не сюда

2016-10-26 11:44 UTC, maximpetrov requested changes

2016-10-26 11:44 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((a in c..d) && (b in c..d)) return (b - a)
Эти замечания ещё в силе:
- Лучше использовать `when`
- Вместо `((a in c..d) && (b in c..d))` можно написать `(a..b in c..d)`
- Некоторые условия лишние

2016-10-26 11:44 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n/2) {
Можно ограничить верхнюю границу ещё больше.

2016-10-26 11:44 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n - 1) {
Замечание про перебор от меньшего к большему ещё в силе.

2016-10-26 11:44 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
>  fun countNumbers(n: Int): Int {  //подсчет кол-ва цифр в числе
Замечание про реализацию `digitNumber`, что `countNumbers` делает тоже самое и оставить нужно только одну из них.

2016-10-26 11:44 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty() == true) return 0.0
Сравнивать на равенство `true` нет смысла, модно просто написать `if (list.isEmpty())`

2016-10-26 11:44 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (list.size > 1) {
Этот `if` не нужен: если размер списка будет меньше или равен 1, то ни одной итерации цикла выполнено не будет.

2016-10-26 11:44 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        if (i >= a) break
Замечание про перенос этого условия в условие `while` всё ещё в силе.

2016-10-26 11:44 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        number = number + digits[i] * Math.pow(base.toDouble(), digits.size.toDouble() - i - 1)
Замечание про неуместность `double` в целочисленных задачах всё ещё в силе.

2016-10-28 10:26 UTC, maximpetrov requested changes

2016-10-28 10:26 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        number = number + digits[i] * Math.pow(base.toDouble(), (digits.size - i - 1).toDouble()).toInt()
Принципиально Вы ничего не изменили, Вы всё также используете `double`.

2016-10-28 10:26 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n/2) {
Можно перебирать меньше, чем до `n/2`.

2016-10-28 10:26 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            for (i in n - 1 downTo 1)
Можно перебирать с числа меньшего, чем `n-1` и до числа меньшего, чем 1.

2016-10-28 10:26 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            for (i in n - 1 downTo 1)
Кроме того, поправьте выравнивание.

2016-11-23 10:38 UTC, mglukhikh commented
Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.

2016-11-23 11:23 UTC, Kir86russ commented
Здравствуйте. Я нечаянно что-то стер в IDEA и теперь тесты не работают. Как мне устранить это непаладку? Или можно я принесу на флешке задания в Блокноте Вам?

Среда, 23 ноября 2016, 13:38 +03:00 от Mikhail Glukhikh <notifications@github.com>:
>Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-11-23 11:39 UTC, Kir86russ commented
Я все починил, начинаю комитить. 


Среда, 23 ноября 2016, 14:23 +03:00 от патриарх патрик <zozozo24@mail.ru>:
>
>Здравствуйте. Я нечаянно что-то стер в IDEA и теперь тесты не работают. Как мне устранить это непаладку? Или можно я принесу на флешке задания в Блокноте Вам?
>
>Среда, 23 ноября 2016, 13:38 +03:00 от Mikhail Glukhikh < notifications@github.com >:
>>Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.
>>—
>>You are receiving this because you authored the thread.
>>Reply to this email directly,  view it on GitHub , or  mute the thread .
>

2016-11-25 08:37 UTC, maximpetrov requested changes
Пока Вы не исправите существующие замечания, новые уроки проверяться не будут

2016-11-25 08:37 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +         if (((kingX == rookX1) || (kingY == rookY1)) && ((kingX != rookX2) && (kingY != rookY2))) return 1
Во-первых, следует вынести условие угрозы от каждой ладьи в отдельную переменную. Во-вторых, можно изменить порядок проверки условий, чтобы упростить 2 из них. В-третьих, Здесь лучше использовать конструкцию `when`.

2016-11-25 08:37 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n/2) {
Всё ещё актуально

2016-11-25 08:37 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            for (i in n - 1 downTo 1)
Всё ещё актуально

2016-11-25 08:37 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            for (i in n - 1 downTo 1)
Всё ещё актуально

2016-11-25 08:37 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun countNumbers(n: Int): Int {  //подсчет кол-ва цифр в числе
Всё ещё актуально

2016-11-25 08:37 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        number = number + digits[i] * Math.pow(base.toDouble(), (digits.size - i - 1).toDouble()).toInt()
Всё ещё акутально

2016-11-25 12:11 UTC, maximpetrov requested changes

2016-11-25 12:11 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    var ladyaFirst = 0
Эта переменная должна быть логического типа и вычислить её можно без использования `if`.

2016-11-25 12:11 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else if ((kingX == rookX2) || (kingY == rookY2)) return 2
Мне кажется, Вы забыли удалить этот кусок.

2016-11-25 12:11 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (n % a != 0) {
Стало только хуже: `for` здесь лучше, чем `while`, кроме того Вы вместо того, чтобы уменьшить диапазон перебора вообще сняли ограничение.

2016-11-25 12:11 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n / 2 downTo 1)
С верхней границей согласен, а нижнюю можно сделать больше.

2016-11-26 07:56 UTC, maximpetrov requested changes

2016-11-26 07:56 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        number = number + digits[i] * Math.pow(base.toDouble(), (digits.size - i - 1).toDouble()).toInt()
Всё ещё акутально

2016-11-26 07:56 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun countNumbers(n: Int): Int {  //подсчет кол-ва цифр в числе
Всё ещё акутально

2016-11-26 07:56 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in (n / 2) downTo 1 )
Почему в `minDivisor` достаточно дойти до корня, я здесь нужно все числа перебирать?

2016-11-26 07:56 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        for (i in 2..(Math.sqrt(n.toDouble()).toInt())) {
Выравнивание поправьте

2016-11-26 07:56 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +        (kingX == rookX1 || kingY == rookY1) -> 1
Зачем Вам первые 3 строки в `when`?

2016-11-26 16:44 UTC, maximpetrov requested changes

2016-11-26 16:44 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in (n / 2) downTo 1 )
Он действительно будет выдавать ошибку, так как у Вас она есть в этой функции (помимо нижней границы)

2016-11-26 16:44 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        number += (digits[i] * Math.pow(base.toDouble(), (digits.size - i - 1).toDouble()).toInt()).toInt()
Это ещё хуже. Я хочу, чтобы Вы вообще не использовали `double`. Для этого можно либо написать свою функцию `pow` для целых чисел, либо с помощью арифметических преобразований вообще избавиться от возведения в степень.

2016-11-29 14:16 UTC, maximpetrov commented
recheck all

2016-11-29 15:33 UTC, maximpetrov requested changes

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    var builderString = ""
Если Вы хотите собирать строку по частям, то используйте `StringBuilder`.

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (parts.size == 3) {
Эту проверку лучше инвертировать, т.е. в случае ошибки вернуть пустую строку, а иначе обрабатывать дальше (но без `else`).

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if (day in 1..9) builderString = builderString + '0' + day.toString() + "."
Для этого в этом уроке есть функция `twoDigitStr`. А ещё лучше почитайте про функцию `String.format` и примените её для даты целиком.

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (parts.size == 1) return -1
Почему это отдельный случай?

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (count > 0) {
Зачем Вам `count`? Можно же просто `maxHeight` инициализировать -1.

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val filterString = Regex("""((\d+\ +(\+|\-)\ +)+)?\d+""")
Вместо + и ? можно использовать *.

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +                for (i in 0..parts.size - 3 step 2) {
Почему такой странный диапазон?

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    }catch (e: NumberFormatException){
Зачем Вы ловите это исключение, если уже проверили формат регулярным выражением? К тому же, почему Вы выбрасываете обратно исключение с тем же типом?

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +                val parts = expression.split(" ")
Что будет, если два элемента разделены более чем одним пробелом?

2016-11-29 15:33 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    var maxDistance = point1.distance(point2)
Лучше взять первые две точки.

2016-12-17 00:25 UTC, maximpetrov requested changes

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +            "Июля", "Августа", "Сентября", "Октября", "Ноября", "Декабря")
Зачем названия месяцев с большой буквы? Кроме того, сделайте этот список общим со следующей функцией.

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IllegalArgumentException) {
Зачем Вы кидаете исключение, ловите его и делаете `return`, вместо того, чтобы просто сделать `return`?

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        return String.format("%02d.%02d.%s", date, monthInt, year)
Почему для года `%s`?

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        val monthInt = month.toInt()
Зачем сначала Вы переводите в строку, а потом обратно?

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if (partsOfDate.size > 3) throw IllegalArgumentException()
А если меньше 3?

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IllegalArgumentException) {
Не нужно выбрасывать исключение только для того, чтобы поймать его и вернуть пустую строку, возвращайте пустую строку сразу.

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IndexOutOfBoundsException) {
Вы должны не ловить это исключение, а сделать так, чтобы оно не возникало.

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IllegalArgumentException) {
Зачем?

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        return jumpsInt.zip(jumpsSymb).filter { it.second.contains(Regex(".*[+].*")) }.toMap().toSortedMap(Comparator { o1, o2 -> o2 - o1 }).filter { it.value.matches(Regex(".*[+]+.*")) }.keys.firstO
- Вместо регулярного выражения, которое Вы используете можно просто проверить `'+' in it.second`
- Зачем Вы дважды фильтруете с одним и тем же условием?
- Зачем Вам вообще `SortedMap`, Вам хватит `maxBy`.

2016-12-17 00:25 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        when {
Используйте синтаксис `when` с аргументом.

2016-12-17 08:10 UTC, maximpetrov commented
recheck all

2016-12-18 20:20 UTC, Kir86russ commented
Error:Module 'KotlinAsFirst2016' production: java.lang.ClassCastException: org.jetbrains.jps.builders.java.dependencyView.TypeRepr$PrimitiveType cannot be cast to org.jetbrains.jps.builders.java.dependencyView.TypeRepr$ClassType 
_______________________________________________________________________
перестали работать тесты. выдает Айдиа этот текст при проверке любой задачи 
подскажите, пожалуйста в чем проблема
возможно это связано как то с "ловлей исключений"

2016-12-19 10:15 UTC, maximpetrov commented
recheck all

2017-07-26 18:23 UTC, closed without merging