Few problems in Task 1
Kotlin-Polytech/KotlinAsFirst2016 pull request #188
Opened 2016-10-24 12:43 UTC by zhao860161921

2016-10-24 13:49 UTC, mglukhikh commented
Сообщите, пожалуйста, своё полное имя и фамилию (в комментарии здесь, или в письме на адрес glukhikh@mail.ru).

2016-10-24 14:03 UTC, maximpetrov requested changes

2016-10-24 14:03 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +   val sum = (sagenes * 48 + arshins * 16 + vershoks) * 4.445 / 100
Здесь нет необходимости заводить переменную, чтобы сразу её вернуть, можно вернуть прямо результат выражения. А ещё лучше воспользоваться однострочной формой записи, как в прошлой функции.

2016-11-23 10:40 UTC, mglukhikh commented
У вас почти не сделано задач. Если вы не хотите быть отчисленным в конце семестра, вам следует начать очень активно работать над учебным проектом.

2016-12-19 09:11 UTC, mglukhikh commented
Ничего так и не сделано, так что "незачёт".

2017-07-26 18:23 UTC, closed without merging