Lesson 2
Kotlin-Polytech/KotlinAsFirst2016 pull request #189
Opened 2016-10-26 10:08 UTC by ehaidari77

2016-10-27 16:07 UTC, mglukhikh commented
Всё, в принципе, хорошо. Однако, в обоих файлах второго урока нужно поправить форматирование кода. Прочитать вот такое 
```
else if ((kingX ==rookX1||kingY==rookY1)&&(kingX!=rookX2&&kingY!=rookY2)) return 1
```
почти невозможно, для облегчения чтения программисты придумали пробелы. Например:
```
else if ((kingX == rookX1 | | kingY == rookY1) && (kingX != rookX2 && kingY != rookY2)) return 1
```

IDEA может автоматически отформатировать весь код в файле. Используйте комбинацию Ctrl+Alt+L.

2016-10-27 20:10 UTC, ehaidari77 commented
Lesson 3

2016-11-02 09:52 UTC, mglukhikh requested changes
Исправьте пожалуйста замечания по форматированию и стилю. Кроме этого, не проходят тесты для `center` из 4-го урока (см. замечания к ней).

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else return t1+t2+(s0-s1-s2)/v3
Повторно прошу поправить форматирование кода (можно использовать Ctrl+Alt+L в IDEA)

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else return 0
Форматирование кода

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else if (Math.abs(kingX-bishopX)==Math.abs(kingY-bishopY)&&(kingX!= rookX&&kingY!= rookY)) return 2
Форматирование кода

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else if(a*a>b*b+c*c||b*b>c*c+a*a||c*c>b*b+a*a) return 2
Форматирование кода

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean =((number/1000+number/100%10)==(number%10+number/10%10))
Форматирование кода

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = ((x1==x2)||(y1==y2)||(Math.abs(x1-x2)==Math.abs(y1-y2)))
Форматирование кода

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +                 x2: Double, y2: Double, r2: Double): Boolean = Math.sqrt(sqr(x1-x2)+sqr(y1-y2))+r1<=r2
Форматирование кода

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    val b1 = (a <= r && b <= s) || (b <= r && a <= s) || (a <= r && c <= s) || (a <= s && c <= r) || (b <= r && c <= s) || (c <= r && b <= s)
Такую строчку лучше разбить на несколько строчек, например

```
val b1 = (a <= r && b <= s) ||
        (b <= r && a <= s) ||
        (a <= r && c <= s) || ...
```

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +import com.sun.xml.internal.ws.runtime.config.TubelineFeatureReader
Этот импорт не нужен

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +import kotlin.concurrent.timer
Этот тоже (нужен только java.lang.Math.*)

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    x--
Такой трюк с `x++` и последующим `x--` некрасив и не нужен. Гораздо проще написать цикл for, перебирающий делители (в вашем коде -- x) и возвращать первый же найденный из них

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    val x = n1 == 1
Эта функция почти повторяет `lcm`. Создайте отдельную функцию `gcd` для расчёта наибольшего общего делителя и используйте её здесь и в `lcm`.

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var k = 0
Можно начать перебор не с нуля, а с корня из m - 1.

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
В этой функции вполне можно обойтись одним циклом while

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        nn = n / pow(10.0, (count * 1.0 - 1)).toInt() % 10 * pow(10.0, t * 1.0).toInt() + nn
Напишите свою функцию pow для возведения целого числа в целую степень

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    m = m / pow(10.0, l * 1.0).toInt() % 10
Здесь тоже нужна своя функция pow

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        val x=list.sum() / list.size
Здесь можно вызвать уже написанную функцию mean

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return mutableListOf()
Эта ветка не нужна. К тому же, она создаёт новый список, а нужно вернуть старый

2016-11-02 09:52 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        t++
Здесь лучше написать `else t++` и убрать `t--` двумя строчками выше

2016-11-25 20:43 UTC, mglukhikh requested changes
Прошу исправить все замечания на вкладке Files Changed: https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/189/files. Сделайте это ПЕРЕД тем, как решать новые задачи.

2016-11-25 20:43 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
1) Неудачное название переменной
2) Одинаковый список в двух функциях. Объявите его на верхнем уровне, ПЕРЕД `dateStrToDigit`, и используйте в обеих функциях

2016-11-25 20:43 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            "июля", "августа", "сентября", "октября", "ноября", "декабря")
Одинаковый список в двух функциях

2016-11-25 20:43 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (jumps.matches(Regex("[-% 0-9]"))) {
Поясните в комментарии, пожалуйста, что делает эта строчка

2016-12-19 21:45 UTC, mglukhikh commented
Вы за семестр не исправили ни одного замечания по коду. Смотрите вкладку Files Changed и исправляйте. Пока ваша оценка -- "незачёт". Постарайтесь, пожалуйста, до упражнений в среду исправить хотя бы часть имеющихся замечаний.

2016-12-19 21:46 UTC, mglukhikh commented
recheck all

2016-12-19 21:48 UTC, mglukhikh commented
recheck all

2017-01-16 11:39 UTC, ice-phoenix commented
recheck all

2017-01-23 07:22 UTC, ice-phoenix commented
recheck all

2017-07-26 18:23 UTC, closed without merging