Lesson5.task1 Hiraev Malik 13531/2
Kotlin-Polytech/KotlinAsFirst2016 pull request #192
Opened 2016-10-26 13:38 UTC by MalikPiter

2016-10-26 14:16 UTC, MalikPiter commented
Не понимаю в чем проблема

2016-11-01 10:22 UTC, mglukhikh requested changes
Незначительные замечания по стилю

2016-11-01 10:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        if (element > 9) elem = alphabet[element - 10].toString()
Здесь гораздо понятнее так: `val elem = if (element > 9) alphabet[...].toString() else "$element"`.

2016-11-01 10:22 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        else list += char.toInt() - 48
Магические константы 97, 122, 87, 48 следует убрать. Замените их на действия с соответствующими символами.

2016-11-01 10:22 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int) = hours*3600+minutes*60+seconds
Вы бы причесали форматирование кода в первых уроках. Ctrl+Alt+L вам в помощь

2016-11-01 10:22 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val bool = phoneWithoutSmbl.matches(Regex("""(\+\d+)?(\(\d+\))?\d+"""))
Лучше проверить условие сразу же и сделать return, если оно ложно

2016-11-01 10:22 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    }
Я бы просто поймал исключение из `toInt`. Впрочем, дело вкуса

2016-11-01 10:22 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val descriptionList = description.split(" ")
Таким решением вы сразу создаёте себе лишних проблем. Лучше вначале разбить по товарам, а потом отделить товар от цены

2016-11-01 10:22 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        } else if (descriptionList[i].matches(Regex("""\d*\.?\d*\;"""))) {
Эта ветка уйдёт, если сделать разбиение согласно структуре строки (см. выше)

2016-11-01 10:22 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return descriptionList[descriptionList.indexOf("$maxPrice$x") - 1]
Вы вполне можете сочетать поиск максимальной цены с сохранением соответствующего ей названия товара

2016-11-04 18:42 UTC, mglukhikh approved these changes
Согласен с исправлениями, 5-й урок принят. Но опрометчиво пойманный Exception всё-таки поправьте :)

2016-11-04 18:42 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    } catch (e: Exception) {
Никогда или почти никогда не нужно ловить "исключение вообще" (а именно это символизирует собой класс `Exception`). Данный блок catch поймает вам, в частности, `NullPointerException`, `IndexOutOfBoundsException` и многие другие исключения, то есть, когда вы пишете так, вы рискуете не узнать об ошибках в вашей программе -- при их возникновении ваша функция "молча" возвращает пустую строку. В данном случае вы знаете, что возникнуть "легально" может только `NumberFormatException` -- его и нужно здесь ловить

2016-11-04 18:42 UTC, closed without merging