3 урок
Kotlin-Polytech/KotlinAsFirst2016 pull request #193
Opened 2016-10-26 15:36 UTC by KatPierce

2016-10-27 12:45 UTC, belyaev-mikhail commented
recheck all

2016-10-27 13:24 UTC, belyaev-mikhail commented
recheck all

2016-10-27 14:00 UTC, belyaev-mikhail requested changes

2016-10-27 14:00 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = (hoursArrive * 60 + minutesArrive) - (hoursDepart * 60 + minutesDepart)
Длинные строки в коде лучше разбивать на более короткие

2016-10-27 14:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    val a = Math.max(m, n)
Эту функцию гораздо проще (и быстрее) можно реализовать на основе функций `gcd` или `lcm`, определённых выше.

2016-10-27 14:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    else for (i in 2..n - 1) {
Действительно ли для проверки делителей нужно проверять все числа до `n - 1`?
Как минимум, *половина* из них делителями `n` точно не является.

2016-10-27 14:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +fun square(m: Int): Boolean {
Что это за чушь? Эта программа ничего не проверяет.

2016-10-27 14:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        (m <= sqr(Math.sqrt(n.toDouble()).toInt().toDouble()) && sqr(Math.sqrt(n.toDouble()).toInt().toDouble()) <= n)
1. Вы считает одно и тоже сложное выражение дважды
1. Это некорректный способ проверки, является ли число квадратом. В том случае, если `n == m` и оно само по себе квадрат, может произойти ошибка округления и функция выдаст `false`. Либо используйте функции округления вместо `toInt()`, либо не используйте такой способ.
1. `sqr(Math.sqrt(n.toDouble()).toInt().toDouble()) <= n` является верным вообще всегда для любых `n`, кроме случаев с ошибками округления.

2016-10-27 14:00 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        nn= number
Пробелы

2016-10-27 18:16 UTC, belyaev-mikhail requested changes

2016-10-27 18:16 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        result+=v[i]*v[i]}
Пробелы

2016-10-27 18:16 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +   val sum= list.sum()
Отступы и пробелы

2016-10-27 18:16 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            list[i] = element-n
Некорректные отступы

2016-10-27 18:16 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        for (i in 0..n-1){
Форматирование

2016-10-27 18:16 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +         for (i in 0..n - 1) {
Форматирование

2016-10-27 18:16 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        number/=element
Форматирование

2016-10-27 18:16 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    var a =""
Почему `var`, если переменная не меняется?

2016-10-27 18:16 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    if (isPrime(n)==true ) return "$n" else return a
Что это значит и зачем это? `factorize` и так должен вернуть список из одного `n`, если `n` &mdash; простое.

2016-10-27 18:19 UTC, belyaev-mikhail requested changes

2016-10-27 18:19 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        m <= sqr(Math.sqrt(n.toDouble()).toInt())
Это по-прежнему некорректный код для вычисления ближайшего снизу квадрата.

2016-10-27 18:19 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        result = (nn / Math.pow(10.0, dif.toDouble()).toInt()) % 10
Так возводить в степень целые числа нельзя.

2016-11-23 10:24 UTC, mglukhikh commented
Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.

2016-11-24 18:33 UTC, KatPierce commented
У меня полетел компьютер, отправляю с ноутбука Константина Казаченко.

2016-11-25 12:46 UTC, belyaev-mikhail commented
recheck all

2016-11-25 13:03 UTC, belyaev-mikhail commented
recheck all

2016-11-25 13:12 UTC, belyaev-mikhail requested changes

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        if (sqrtResult % 1 == 0.0) {
И эта проверка по-прежнему некорректна.

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    if ((a.size == 0) && (b.size == 0)) return 0.0 else
Форматирование

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    if (p.isEmpty() == true) return 0.0 else
Форматирование

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty() == true) return list else
Форматирование

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        if (list[i] > 9) result += (87 + list[i]).toChar() else
Форматирование

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        if (str[i] in '0'..'9') list += ((str[i]).toInt() - 48) else
Форматирование

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +            (sqr(center.x-p.x)+sqr(center.y-p.y))<=sqr(radius)
Отступы

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        , radius = diameter.begin.distance(diameter.end) / 2.0)
Кривое форматирование

2016-11-25 13:12 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +fun lineBySegment(s: Segment): Line = Line(s.begin, Math.atan((s.end.y-s.begin.y)/(s.end.x-s.begin.x)))
Пробелы

2016-12-23 06:48 UTC, mglukhikh requested changes
Большая просьба не оставлять в репозитории решений задач с тестирования. А ещё лучше было бы туда их и вовсе не добавлять

2016-12-23 06:48 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun exam(examResults: List<String>, thresherhold: Double): List<String> {
Удалите эту функцию из репозитория, пожалуйста

2016-12-23 06:48 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun beststudents(examResults: List<String>, threshold: Double): List<String> {
Удалите эту функцию из репозитория, пожалуйста

2016-12-23 06:48 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun student(examResults: List<String>, threshold: Double): List<String> {
Удалите эту функцию из репозитория, пожалуйста

2016-12-23 06:48 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun birthdays(text: String): List<String> {
Удалите эту функцию из репозитория, пожалуйста

2016-12-23 06:54 UTC, KatPierce commented
Михаил Игоревич, я не понимаю. У меня получилось отправить пуллреквест или
нет? Вчера мы с Петровым Максимом Алексеевичем 2 часа пытались это сделать
,в итоге он отправился, но бот прислал вот это.

пт, 23 дек. 2016 г. в 9:48, Mikhail Glukhikh <notifications@github.com>:

> *@mglukhikh* requested changes on this pull request.
>
>
>
>
> Большая просьба не оставлять в репозитории решений задач с тестирования. А
> ещё лучше было бы туда их и вовсе не добавлять
> ------------------------------
>
>
>
>
> In src/lesson5/task1/Parse.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/193#pullrequestreview-14267560>
> :
>
>
> > \ No newline at end of file
>
> +fun computeDeviceCells(cells: Int, commands: String): List<Int> = TODO()
>
> +
>
> +fun main(args: Array<String>) {
>
> +    val f = "Он пошёл в в школу"
>
> +    val x = firstDuplicateIndex(f)
>
> +    println(x)
>
> +}
>
> +
>
> +
>
> +fun exam(examResults: List<String>, thresherhold: Double): List<String> {
>
>
>
> Удалите эту функцию из репозитория, пожалуйста
>
>
>
>
> ------------------------------
>
>
>
>
> In src/lesson5/task1/Parse.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/193#pullrequestreview-14267560>
> :
>
>
> > +            try {
>
> +                sr += stringLittleLittle[2].toString().toDouble()
>
> +            } catch (e: NumberFormatException) {
>
> +                throw IllegalArgumentException()
>
> +            }
>
> +
>
> +            number++
>
> +        }
>
> +        if (sr / number >= thresherhold) {
>
> +            resultList += (string[0].substring(0, string[0].length - 1))
>
> +        }
>
> +    }
>
> +    return resultList
>
> +}
>
> +
>
> +fun beststudents(examResults: List<String>, threshold: Double): List<String> {
>
>
>
> Удалите эту функцию из репозитория, пожалуйста
>
>
>
>
> ------------------------------
>
>
>
>
> In src/lesson5/task1/Parse.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/193#pullrequestreview-14267560>
> :
>
>
> > +        var mark = 0.0
>
> +        var marks = listOf<String>()
>
> +        for (j in 0..part.size - 1) {
>
> +            marks = part[j].split(" ")
>
> +            mark = marks[1].toDouble()
>
> +            if (mark < 2.0 || mark > 5.0)
>
> +                throw IllegalArgumentException()
>
> +            averagemark += mark
>
> +        }
>
> +        if (averagemark / part.size >= threshold)
>
> +            result.add(parse[0])
>
> +    }
>
> +    return result
>
> +}
>
> +
>
> +fun student(examResults: List<String>, threshold: Double): List<String> {
>
>
>
> Удалите эту функцию из репозитория, пожалуйста
>
>
>
>
> ------------------------------
>
>
>
>
> In src/lesson5/task1/Parse.kt
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/193#pullrequestreview-14267560>
> :
>
>
> > +        var mark = 0.0
>
> +        var marks = listOf<String>()
>
> +        for (j in 0..part.size - 1) {
>
> +            marks = part[j].split(" ")
>
> +            mark = marks[1].toDouble()
>
> +            if (mark < 2.0 || mark > 5.0)
>
> +                throw IllegalArgumentException()
>
> +            averagemark += mark
>
> +        }
>
> +        if (averagemark / part.size >= threshold)
>
> +            result.add(parse[0])
>
> +    }
>
> +    return result
>
> +}
>
> +
>
> +fun birthdays(text: String): List<String> {
>
>
>
> Удалите эту функцию из репозитория, пожалуйста
>
>
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/193#pullrequestreview-14267560>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVLQ_05MuwfLxgtloH1lUuhB_5MpEsjTks5rK26vgaJpZM4KhUzt>
> .
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>

2016-12-26 06:41 UTC, mglukhikh commented
Всё у вас получилось. Это не бот прислал, это мой комментарий. Потому что не нужно класть в репозиторий решения задач с тестирования, ещё раз вам повторяю. Вообще, комментарии и результаты смотреть лучше на страничке вашего PR: https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/193.

2017-07-26 18:23 UTC, closed without merging