Makarova 13531/3
Kotlin-Polytech/KotlinAsFirst2016 pull request #194
Opened 2016-10-26 15:46 UTC by JulyMak

2016-10-26 20:40 UTC, belyaev-mikhail commented
recheck all

2016-10-26 20:42 UTC, belyaev-mikhail commented
recheck all

2016-10-26 20:44 UTC, belyaev-mikhail commented
Читайте задание внимательно. В случае некорректного ввода функция `dateStrToDigit` должна возвращать пустую строку.

2016-10-27 12:04 UTC, JulyMak commented
Да вроде же так и есть

2016-10-27 12:22 UTC, belyaev-mikhail commented
Нет, не так. Ваша функция выбросила на некорректную строку исключение.

2016-10-27 14:02 UTC, belyaev-mikhail commented
recheck all

2016-10-31 15:01 UTC, belyaev-mikhail requested changes

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return timeInSeconds
Зачем заводить переменную, если её значение вы тут же возвращаете?

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val length = (sagenes * 48 + arshins * 16 + vershoks) * 0.04445
Аналогично

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val angle = (grad + min / 60.0 + sec / 3600.0) * (Math.PI / 180)
Аналогично

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val digit = (number / 100) % 10
Аналогично

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val allTime = (hoursArrive * 60 + minutesArrive) - (hoursDepart * 60 + minutesDepart)
Аналогично

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +fun segmentLength(a: Int, b: Int, c: Int, d: Int): Int {
Вместо цепочки `if`ов лучше использовать `when`.

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if ((number / 100) % 10 + (number / 1000) == (number / 10) % 10 + number % 10)
`if(X) return true else return false` не имеет смысла, т.к. это то же самое, что и просто `return X`.

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if (x1 == x2 || y1 == y2 || Math.abs(x1 - x2) == Math.abs(y1 - y2))
Аналогично

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    else return false
Аналогично

2016-10-31 15:01 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    else return true
Аналогично

2016-11-22 16:22 UTC, belyaev-mikhail requested changes

2016-11-22 16:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    var a1 = a
Зачем вам эти бессмысленные переменные, которые вы используете 1 раз?

2016-11-22 16:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    return !(NOD(m, n) != 1)
"Не не равно"? Вам это слух не режет?

2016-11-22 16:22 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    val revertNum = revert(n)
Зачем заводить переменную, которую вы используете 1 раз?

2016-11-22 16:22 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +            result = Math.max(result, resultNumbers[i].toInt())
Зачем вам эта переменная? Почему нельзя сразу вернуть результат?

2016-11-23 11:19 UTC, mglukhikh commented
recheck all

2016-11-24 12:39 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        angle = Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x))
А если сегмент параллелен оси X или оси Y?
В первом случае вы делите на 0, во втором берёте арктангенс от 0.

2016-11-24 12:48 UTC, belyaev-mikhail commented
recheck all

2016-11-24 13:05 UTC, belyaev-mikhail requested changes

2016-11-24 13:05 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        angle = Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x))
А что будет, если сегмент параллелен оси Y?

2016-12-11 15:54 UTC, JulyMak commented on src/lesson6/task1/Geometry.kt
> +        angle = Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x))
А разве арктангенс бесконечности не равен pi/2 ?

2016-12-12 20:34 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        angle = Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x))
1) 2/0 не обязано равняться бесконечности. Если вы забыли школьную математику, я напомню: на ноль делить нельзя. Конкретно в даблах может получиться и минус бесконечность, и плюс бесконечность, вам просто повезло.
2) Нет, он не обязан быть равным pi/2, потому что это нигде не написано в его документации. Для этого случая есть функция atan2, которая принимает отдельно y, отдельно x.

2016-12-12 20:39 UTC, ice-phoenix commented
Напоминаю, что я все еще хочу увидеть ваше решение тестового задания у себя на почте.

2016-12-12 20:43 UTC, belyaev-mikhail commented
Ваше решение для `circleByThreePoints` выглядит корректным, возможно, недостаёт точности в `crossPoint`.

2016-12-17 18:28 UTC, JulyMak commented
Как все-таки можно поправить точность crossPoint, чтобы circleByThreePoints работала?

2016-12-17 20:59 UTC, mglukhikh commented
Использование тангенса в `crossPoint` -- плохая идея, и проверки на пи пополам не спасают -- угол может быть очень близок к пи пополам, тангенс получится очень большим и это приведёт к снижению точности. Подумайте, как можно от этого избавиться

2016-12-17 22:22 UTC, belyaev-mikhail requested changes

2016-12-17 22:22 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +        if (maxSide == a) {
Такие длинные переборы на `if`ах следует заменять на `when`.

2016-12-17 22:22 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +            angle == Math.PI / 2 || angle == -Math.PI / 2 -> point.x
Так сравнивать значения типа `Double` на равенство нельзя.
Что, если угол равен не Пи/2, а, скажем, Пи/2 - (1/1000000000)?
Равенство уже не пройдёт, а ваш общий случай с тангенсом всё равно начнёт выдавать чушь, потому что это число очень близко к такому, для которого тангенс уже не посчитаешь.

2016-12-17 22:22 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +    val point = circleByDiameter(Segment(a, b)).center
Вам не кажется, что для нахождения центра между двумя точками строить окружность, а потом брать её центр &mdash; это, мягко говоря, не самое оптимальное решение?

2016-12-17 22:22 UTC, belyaev-mikhail commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?) = other is MatrixImpl<*> && height == other.height && width == other.width
`equals()` для сколько нибудь разумной реализации матрицы не может так работать.
Во-первых, вы должны поддерживать сравнение с другими реализациями интерфейса `Matrix`.
Во-вторых, вы тут вообще не сравниваете содержимое матрицы, только её размер.
Совершенно некорректное решение.

2016-12-18 14:31 UTC, belyaev-mikhail requested changes

2016-12-18 14:31 UTC, belyaev-mikhail commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?) = other is MatrixImpl<*> && height == other.height && width == other.width &&
Вы исправили только половину замечания. `equals()` должен работать с любыми реализациями интерфейса `Matrix`, а не только с вашей. Никаких препятствий этому нет, все методы в интерфейсе есть.

2016-12-18 14:31 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        val x = (Math.cos(angle) * (Math.sin(other.angle) * other.point.x - Math.cos(other.angle) * other.point.y) -
Хорошо, что у вас это заработало, но считать косинус и синус одних и тех же углов столько раз &mdash; крайне плохое решение.
Вы же писали реализацию `sin` и `cos` в другом уроке и должны понимать, насколько медленно они считаются.

2016-12-18 19:30 UTC, JulyMak commented on src/lesson6/task1/Geometry.kt
> +        val x = (Math.cos(angle) * (Math.sin(other.angle) * other.point.x - Math.cos(other.angle) * other.point.y) -
Я решила систему из двух уравнений для прямых, как и сказано в задании. Не знаю, каким еще способ это можно сделать

2016-12-18 20:05 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        val x = (Math.cos(angle) * (Math.sin(other.angle) * other.point.x - Math.cos(other.angle) * other.point.y) -
Речь не про способ решения, а про то, что вы кучу раз пересчитываете синусы и косинусы одних и тех же углов. Математика тут вообще ни при чем.

2016-12-18 20:07 UTC, belyaev-mikhail requested changes

2016-12-18 20:07 UTC, belyaev-mikhail commented on src/lesson7/task1/Matrix.kt
> +        if (other is MatrixImpl<*> && height == other.height && width == other.width)
Вы не решили описанную мной проблему. У вас по-прежнему есть проверка на `MatrixImpl`.

2016-12-18 21:21 UTC, belyaev-mikhail commented
recheck all

2016-12-18 21:27 UTC, belyaev-mikhail commented
Если вы хотите 5 за декабрь, вам нужно срочно найти и решить ещё одну Hard задачу.

2016-12-18 21:31 UTC, belyaev-mikhail commented
Впрочем, на 5 автоматом вам ещё нужно решить хоть что-то в 8 уроке и переписать тест.

2016-12-18 21:32 UTC, closed without merging