Lesson_3
Kotlin-Polytech/KotlinAsFirst2016 pull request #196
Opened 2016-10-26 19:35 UTC by fav77

Готово 15 из 18 заданий (без sin и cos)

2016-10-26 20:08 UTC, belyaev-mikhail commented
recheck all

2016-10-26 20:18 UTC, belyaev-mikhail commented
recheck all

2016-10-26 20:37 UTC, belyaev-mikhail requested changes

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +        hours*3600+minutes*60+seconds
Ваш стиль кодирования должен быть консистентным. Если вы используете пробелы до и после знаков операций, их следует использовать **везде**, если не используете &mdash; не используйте **нигде**.

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +        (sagenes * 48 + arshins * 16 + vershoks)* 4.445/100
См. комментарий про пробелы. Да ещё и в рамках одного выражения.

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +        (grad+min/60.0+sec/(60.0*60))/(180/PI)
Пробелы

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +        sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2))
Пробелы

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return (number/100)%10
Пробелы.

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return (number/100)%10
Однострочные функции лучше записывать через `=` и без `return`.

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val timeDe = hoursDepart*60+minutesDepart
Пробелы

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    val totalPer = (1.0 + percent * 0.01) * (1.0 + percent * 0.01) * (1.0 + percent * 0.01)
Зачем высчитывать одно и то же выражение трижды?

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return a*100+b*10+c
Пробелы

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean {
Эту функцию можно очень легко реализовать, используя функцию `lcm()`, которую вы определили выше.
И, в отличие от вашей версии, она будет работать быстро.

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        for (i in 0..Math.sqrt(n.toDouble()).toInt()) {
Это некорректный способ взятия целочисленного квадратного корня от числа, даже если тесты говорят вам обратное. Что, если `n` само является квадратом, а точности `Double` не хватит, чтобы получить корректный корень? Этот случай не всплыл в тестах, но код всё равно некорректный.
Нужно либо округлять, а не тупо делать `toInt()`, либо не использовать такой подход вовсе.

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    } else for (i in Math.sqrt(m.toDouble()).toInt()..Math.sqrt(n.toDouble()).toInt()) {
Аналогично

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        if ((n / (Math.pow(10.0, digitNumber(n) - i.toDouble())).toInt()) % 10 != (n / (Math.pow(10.0, i.toDouble() - 1)).toInt()) % 10)
Для того, чтобы возвести целое число в целую степень, использовать тип `Double` некорректно.
Функции возведения в целые степени в Kotlin нет, но это значит только то, что такую функцию следует написать.

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    var prevLenght = 0
Слово &laquo;Length&raquo; пишется не так.

2016-10-26 20:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        lines = fib(count).toString()
Вызывать каждый раз очень затратную функцию `fib()` крайне неэффективно. Попробуйте переформулировать решение так, чтобы этого не делать.

2016-11-07 11:52 UTC, belyaev-mikhail commented
Вы отправляете новые задания, не исправляя замечания к старым. Довожу до вашего сведения, что проверяться и засчитываться они до исправлений не будут.

2016-11-23 10:25 UTC, mglukhikh commented
Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.

2016-11-29 14:50 UTC, belyaev-mikhail commented
recheck assignment

2016-11-29 15:03 UTC, belyaev-mikhail commented
recheck assignment

2016-11-29 15:37 UTC, belyaev-mikhail commented
recheck assignment

2016-11-30 14:22 UTC, belyaev-mikhail commented
recheck all

2016-11-30 14:52 UTC, belyaev-mikhail commented
recheck all

2016-11-30 14:56 UTC, belyaev-mikhail commented
recheck all

2016-12-17 22:57 UTC, belyaev-mikhail requested changes

2016-12-17 22:57 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +Double = sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2))
Форматирование

2016-12-17 22:57 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if ((age in 5..20) || (age in 105..120)) return "$age лет"
Длинные цепочки `if` следует превращать в `when`.

2016-12-17 22:57 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if (((Math.sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2))) + r1) <= r2) return true
`if (X) return true else return false` не имеет никакого смысла, т.к. ничем не отличается от просто `return X`.

2016-12-17 22:57 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    if (s >= a && (r >= b || r >= c)) return true
См. комментарий про `when`

2016-12-17 22:57 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    for (k in Math.sqrt(m.toDouble()).toInt()..Math.sqrt(n.toDouble()).toInt()) {
Это неправильный промежуток. `sqr(sqrt(n.toDouble()).toInt()` может запросто оказаться меньше `n` из-за округлений.

2016-12-17 22:57 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +        if (center.distance(p) <= radius) return true
`if (X) return true else return false` не имеет смысла, т.к. ничем не отличается от просто `return X`

2016-12-17 22:57 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +    if (s.begin.x == s.end.x) {
Строго говоря, сравнивать значения типа `Double` на равенство таким образом нельзя.
Именно поэтому существует функция `Math.atan2`.

2016-12-20 10:24 UTC, mglukhikh commented
recheck all

2017-01-14 14:56 UTC, belyaev-mikhail commented
recheck all

2017-01-14 19:43 UTC, mglukhikh commented
Мы сообща решили, что решения всех задач из урока восемь верные, так что вам ставим зачёт и в понедельник Вы можете приходить на экзамен

2017-01-16 08:01 UTC, gagarski commented
recheck all

2017-07-26 18:23 UTC, closed without merging