lesson3 4 5
Kotlin-Polytech/KotlinAsFirst2016 pull request #197
Opened 2016-10-27 08:15 UTC by hehe134

2016-10-28 11:31 UTC, belyaev-mikhail commented
recheck all

2016-10-31 11:37 UTC, belyaev-mikhail requested changes

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = (sagenes * 48 * 0.04445 + arshins * 16 * 0.04445 + vershoks * 0.04445)
Длинные строки следует разбивать на более короткие. В случае однострочных функций лучше всего ставить перенос после `=`.

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad / 180.0 * PI + min / 60.0 / 180 * PI + sec / 3600.0 / 180 * PI)
Ditto

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    val s0 = (t1*v1+t2*v2+t3*v3)/2.0
Ваш стиль кодирования должен быть консистентным. Если вы ставите пробелы до и после знаков операций &mdash; ставьте их **везде**, если не ставите &mdash; не ставьте **нигде**.

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else if ((kingX ==rookX2||kingY==rookY2)&&(kingX!=rookX1&&kingY!=rookY1)) return 2
Ditto

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else if ((kingX ==rookX2||kingY==rookY2)&&(kingX!=rookX1&&kingY!=rookY1)) return 2
Длинные цепочки `if`-`else if`-`else if` следует заменять на `when`.

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else return 0
Пробелы, `when`

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else if(a*a>b*b+c*c||b*b>c*c+a*a||c*c>b*b+a*a) return 2
Ditto

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else if (a<=c&&b>=d) return d-c
Ditto

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean =((number/1000+number/100%10)==(number%10+number/10%10))
Пробелы

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean =((x1==x2)||(y1==y2)||(Math.abs(x1-x2)==Math.abs(y1-y2)))
Пробелы

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +                 x2: Double, y2: Double, r2: Double): Boolean =Math.sqrt(sqr(x1-x2)+sqr(y1-y2))+r1<=r2
Пробелы

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    val b1 = (a <= r && b <= s) || (b <= r && a <= s) || (a <= r && c <= s) || (a <= s && c <= r) || (b <= r && c <= s) || (c <= r && b <= s)
Зачем заводить переменную, если кроме неё в функции ничего нет?

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +import com.sun.xml.internal.ws.runtime.config.TubelineFeatureReader
Что это? Зачем это?

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    val x = n1 == 1
Заводить переменную и тут же её возвращать &mdash; зачем?

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    val x = n1 == 1
Алсо, данная функция прекрасно выражается через `lcm`.

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        nn = n / pow(10.0, (count * 1.0 - 1)).toInt() % 10 * pow(10.0, t * 1.0).toInt() + nn
Использовать `Math.pow` для целых чисел подобным образом некорректно.
Напишите свою реализацию `pow` для целых чисел, это несложно.

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    m = m / pow(10.0, l * 1.0).toInt() % 10
Аналогично

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    return t
Возврат переменной, объявленной выше + откуда вы взяли эту странную идиому `x * 1.0` вместо `x.toDouble()`??

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        return t
Аналогично

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String {
Эта функция в одну строчку выражается через `factorize()`

2016-10-31 11:37 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    return s
Не обязательно писать свою реализацию инверсии списка, есть функция `revert()`

2016-11-04 19:12 UTC, hehe134 commented on src/lesson4/task1/List.kt
> +    return s
Понятно, спасибо большое!

2016-11-07 11:48 UTC, belyaev-mikhail requested changes

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return x
Какой смысл заводить переменную, чтобы тут же её вернуть?

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +    return x
Какой смысл заводить переменную, чтобы тут же её вернуть?

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else return "$age лет"
Если я в конкретном задании пропустил одно из общих замечаний, это не значит, что его не следует исправлять. Длинные цепочки условий следует заменять на `when`.

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    else return t1 + t2 + (s0 - s1 - s2) / v3
Аналогично

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson2/task2/Logical.kt
> +    else return false
Конструкция `if(X) return true else return false` не имеет никакого смысла, т.к. ничем не отличается от просто `return X`

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    if (n1 == 1) return true
Аналогично

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        nn += n / Math.pow(10.0, (count * 1.0 - 1)).toInt() % 10 * Math.pow(10.0, t * 1.0).toInt()
Вы либо не поняли моего замечания, либо намеренно его проигнорировали.
Тем не менее, использовать `pow` таким образом &mdash; всё ещё некорректно.

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    m = m / Math.pow(10.0, l * 1.0).toInt() % 10
+1

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    m = m / pow(10.0, l * 1.0).toInt() % 10
+1

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        x +=Math.pow(element, 2.0)
Пробелы. Кроме того, возводить число в квадрат лучше как `element * element`

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    return t
Опять заводим переменную и тут же её возвращаем. Кто вас научил так делать? Вы даже имя ей нормальное не смогли придумать, до того она здесь не нужна.

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +        return t
+1

2016-11-07 11:48 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +    return p1 * 1.0
`p1 * 1.0`

2016-11-24 22:14 UTC, hehe134 commented on src/lesson3/task1/Loop.kt
> +        nn += n / Math.pow(10.0, (count * 1.0 - 1)).toInt() % 10 * Math.pow(10.0, t * 1.0).toInt()
Здравствуйте, я не понимаю вашего замечания, как исправить здесь?

2016-11-25 12:50 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +        nn += n / Math.pow(10.0, (count * 1.0 - 1)).toInt() % 10 * Math.pow(10.0, t * 1.0).toInt()
Я вам писал в предыдущем комментарии, что нельзя использовать `Math.pow` для того, чтобы возводить целые числа в целые степени. `Math.pow` работает с приближенными действительными числами типа `Double`. Использовать его для целых чисел, приводя результат к типу `Int`, нельзя, потому что результаты такого преобразования могут оказаться некорректными.

2016-12-17 22:58 UTC, belyaev-mikhail commented
recheck all

2016-12-20 19:00 UTC, belyaev-mikhail commented
recheck all

2016-12-21 20:44 UTC, belyaev-mikhail commented
recheck all

2017-07-26 18:23 UTC, closed without merging