Sidorina_Lesson6
Kotlin-Polytech/KotlinAsFirst2016 pull request #198
Opened 2016-10-27 18:36 UTC by ElenaLaufeyson

Решения 6 урока

2016-10-27 19:02 UTC, ElenaLaufeyson commented
Почему угол между равными точками не может быть равен 0? Почему бот просит только угол Math.PI/2 ???

2016-10-27 22:34 UTC, belyaev-mikhail commented
Угол между одинаковыми точками может быть равен чему угодно, это баг в проверке у бота.

2016-10-27 22:38 UTC, belyaev-mikhail commented
recheck assignment

2016-10-27 22:40 UTC, belyaev-mikhail commented
Починено.

2016-11-01 12:26 UTC, mglukhikh requested changes
Незначительные замечания по стилю

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return Line(Point(circ.center.x, circ.center.y), Math.atan(a1 / (b1 + Double.MIN_VALUE)))
Чтобы не возиться с нулевым знаменателем в `atan`, лучше применять `atan2`. См. https://docs.oracle.com/javase/7/docs/api/java/lang/Math.html#atan2(double,%20double)

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        angle = Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x))
Чтобы не возиться с нулевым знаменателем в atan, лучше применять atan2. См. https://docs.oracle.com/javase/7/docs/api/java/lang/Math.html#atan2(double,%20double)

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val C2 = -A2 * other.point.x - B2 * other.point.y
По code style, имена переменных должны называться с маленькой буквы. Не вижу причин делать в данном случае исключение

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            b.distance(c) > a.distance(b) + a.distance(c))
Здесь лучше создать переменные `ab`, `bc` и `ac` и использовать их, чтобы не считать длины всех сторон по три раза, это раз. И главное: а какой вообще смысл в этой проверке? Если вы считаете, что смысл в ней есть, напишите тест для случая, когда она срабатывает. Отдельно проверьте, как работает эта функция для трёх точек на одной прямой.

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        for (k in 1..points.size - 1) {
Если уж вы перебираете индексы, то здесь стоит начать не с 1, а с `i + 1`

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        val column1 = listOf('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
Здесь лучше `"abcdefgh"` вместо списка. К строке тоже можно обратиться по индексу

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (strings[i].equals(strings[i + 1])) return index
Лучше == вместо явного вызова `equals`

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            val exptoint = expressions[i + 1].toInt()
camelCase: expToInt

2016-11-01 12:26 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        val column1 = listOf('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
К тому же, список будет создаваться каждый раз, а строковый литерал будет просто константой, постоянно лежащей в памяти

2016-11-01 17:43 UTC, ElenaLaufeyson commented on src/lesson6/task1/Geometry.kt
> +            b.distance(c) > a.distance(b) + a.distance(c))
Эта проверка срабатывает как раз в том случае, когда три точки лежат на одной прямой, и построить по ним окружность нельзя.

2016-11-02 09:31 UTC, mglukhikh requested changes
Чуть-чуть не доделали

2016-11-02 09:31 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        throw IllegalArgumentException("Треугольник не существует")
Пожалуйста, напишите тест для случая с тремя точками на одной прямой (например, a = Point(0.0, 0.0), b = Point(1.0, 0.0), c = Point(2.0, 0.0)) и убедитесь, что в тесте действительно происходит это исключение (для этого в тесте его необходимо поймать).

2016-11-02 09:31 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        val column1 = listOf('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
Эти два замечания по-прежнему в силе

2016-11-04 18:35 UTC, mglukhikh approved these changes
В целом всё хорошо, остался один вопрос на подумать (соответствующий участок кода можете поправить в следующем PR). 6-й урок принят.

2016-11-04 18:35 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        throw IllegalArgumentException("Треугольник не существует")
Ага, отлично

2016-11-04 18:35 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +            else -> Square(curSquare.column, curSquare.row + 1)
Подумайте, можно ли эту последовательность условий записать короче.

2016-11-04 18:35 UTC, closed without merging