Две задачи из 5го урока
Kotlin-Polytech/KotlinAsFirst2016 pull request #199
Opened 2016-10-27 19:58 UTC by GlowBlood

В то время, пока я судорожно пытаюсь сделать самую сложную из 4го...

2016-10-29 10:10 UTC, GlowBlood commented
Случайно указала неправильную почту
Правильная - ipberezovskaya@yandex.ru

2016-10-31 07:29 UTC, mglukhikh requested changes
Не слишком существенные замечания по стилю

2016-10-31 07:29 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список следовало сделать глобальной переменной (вынести за функцию), так как он используется в двух функциях. Поскольку по факту это константа, лучше назвать её капсом: `MONTHS`.

2016-10-31 07:29 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    if (parts.size !== 3) return ""
Это сравнение ссылок, правильнее использовать обычное сравнение `!=`. Для сравнения ссылок вообще нет гарантии, что для списка размером 3 вы получите тут при сравнении `false` (хотя текущий компилятор, действительно, работает так).

2016-10-31 07:29 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if ((month !in months) || (days < 1) || (days > 31)) return ""
Лучше `month !in 1..12`, это работает быстрее

2016-10-31 07:29 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if ((days < 1) || (days > 31) || (month < 1) || (month > 12)) return ""
Красивее и короче `days !in 1..31`, `month !in 1..12`

2016-10-31 07:29 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            val days = parts[0].toInt()
Почему вдруг множественное число?

2016-11-02 10:40 UTC, GlowBlood commented
Я вообще ничего не понимаю
Почему сейчас у меня не проходит бота ничего, что проходило до этого?
чтооооо вообще происходит???
Т_Т 
Т_Т
Т_Т

2016-11-02 14:08 UTC, mglukhikh requested changes
См. замечания.

2016-11-02 14:08 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    }
Сместить всю функцию на 4 пробела назад (выделить + Shift+TAB)

2016-11-02 14:08 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            else return String.format("%02d %s %d", day, MONTHS[month - 1], year)
`%02d` --> `%d`. Здесь ожидается ответ вида "3 апреля", а не "03 апреля"

2016-11-02 14:08 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        else return String.format("%02d.%02d.%d", day, MONTHS.indexOf(month) + 1, year)
Вначале найти индекс, а уже потом пытаться его преобразовывать к целому. Иначе вы получаете исключение в `month.toInt()` для любых корректных входных данных

2016-11-16 17:32 UTC, mglukhikh commented
recheck all

2016-11-21 07:43 UTC, mglukhikh commented
Отлично, первые пять уроков у вас засчитаны, двигайтесь дальше (по вашему желанию, можете также решить ещё что-нибудь из 5-го урока)

2016-11-21 07:43 UTC, closed without merging