Lesson 4
Kotlin-Polytech/KotlinAsFirst2016 pull request #200
Opened 2016-10-28 11:16 UTC by SeveNChaK

2016-11-01 21:40 UTC, gagarski requested changes

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +fun isPrime(n: Int) = n >= 2 && (2..n / 2).all { n % it != 0 }
Можно ли ещё сократить диапазон перебора делителей?

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (v.isEmpty()) return absv
Нужно ли в данной задаче рассматривать пустой список как особый случай? Подумайте, что будет с циклом `for` по пустому списку.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +fun mean(list: List<Double>): Double = if (list.isEmpty()) 0.0 else list.sum() / list.size.toDouble()
`list.sum()` для списка из Double вернёт Double. `list.size` не обязательно приводить к Double.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty())
Нужно ли в данной задаче рассматривать пустой список как особый случай? Подумайте, что будет с циклом `for` по пустому списку.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (a.isEmpty()) return scalar
Нужно ли в данной задаче рассматривать пустой список как особый случай? Подумайте, что будет с циклом `for` по пустому списку.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (p.isEmpty()) return px
Нужно ли в данной задаче рассматривать пустой список как особый случай? Подумайте, что будет с циклом `for` по пустому списку.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty())
Нужно ли в данной задаче рассматривать пустой список как особый случай? Подумайте, что будет с циклом `for` по пустому списку.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            list[list.size - i] = list.subList(0, list.size - i + 1).sum()
`subList(...).sum()` будет на каждой итерации пересчитывать сумму частичного списка. Подумайте, можно ли сохранять промежуточный результат и использовать его при вычислениях. Попробуйте прикинуть, как изменится число обращения к элементам списка, число операций сложения.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        if (!isPrime(primeIndex)) primeIndex++
- Попробуйте в каждой итерации искать делитель не начиная с 2, а начиная с последнего найденного делителя. 
 - Проверка на простоту делителя тут не нужна. Если на предыдущих итерациях вы всё сделали правильно, то для составного числа остаток от деления не будет равен нулю. Попробуйте убедиться в этом
 - Сортировка в конце функции лишняя, вы и так добавляете делители по возрастанию.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    while (number > 1) {
Не похож ли данный код на код функции `factorize()`? Почему бы не использовать её?

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    while (number > 0) {
Также дублирование кода с `convert`. Постарайтесь использовать её в связке с `map` или циклом по результату `convert`.

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (char in str) {
- Используйте `decimal`
 - Вместо `String.indexOf` эффективнее будет использовать ассоциативный массив (`mapOf('0' to 0, '1' to 1, /* ... */, 'a' to 10)`), либо свойства кодировки ASCII (`'2' == '0' + 2`, 'd' == 'a' + 3)

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val numbers = listOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
Лучше объединить `numbers` и `romans` в ассоциативный массив

2016-11-01 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val numbers = listOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
Ассоциативный массив.

2016-11-06 21:27 UTC, SeveNChaK commented on src/lesson4/task1/List.kt
> +    for (char in str) {
Относительно моего времени эффективнее использовать String.indexOf, потому что заполнять ассоциативный массив намного дольше:)

2016-11-06 22:06 UTC, SeveNChaK commented on src/lesson4/task1/List.kt
> +    for (char in str) {
а как обратиться к элементу такого массива?

2016-11-08 15:01 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (char in str) {
Вроде разобрались?

2016-11-08 15:03 UTC, gagarski commented
recheck all

2016-11-08 15:03 UTC, gagarski approved these changes

2016-11-08 15:04 UTC, closed without merging

2016-11-09 03:32 UTC, SeveNChaK commented on src/lesson4/task1/List.kt
> +    for (char in str) {
Да, разобрался, все ок, спасибо