6th lesson
Kotlin-Polytech/KotlinAsFirst2016 pull request #201
Opened 2016-10-28 15:17 UTC by grafovdenis

2016-11-02 14:00 UTC, mglukhikh commented
recheck all

2016-11-02 14:29 UTC, ice-phoenix requested changes

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return hours * 3600 + minutes * 60 + seconds
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return 4.445 * (sagenes * 48 + arshins * 16 + vershoks) / 100
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return PI / 180 * (grad + (min + sec / 60.0) / 60.0)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return sqrt(pow(x2 - x1, 2.0) + pow(y2 - y1, 2.0))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (number / 100) % 10
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (hoursArrive * 60 + minutesArrive) - (hoursDepart * 60 + minutesDepart)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (((initial * (1 + percent / 100.0)) * (1 + percent / 100.0)) * (1 + percent / 100.0))
- Повторно используемые выражение следует вынести в отдельные переменные

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        age % 10 > 1 && age % 10 < 5 -> return "$age года"
Можно записать проще через `... in ...`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (threatFrom1) {
Данное выражение лучше оформить как `when`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (threatFromRook) {
Данное выражение лучше оформить как `when`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            if (sqr(a) + sqr(b) == sqr(c) || sqr(b) + sqr(c) == sqr(a) || sqr(a) + sqr(c) == sqr(b)) return 1
Данное выражение лучше оформить как `when`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        b == c || d == a -> return 0
Зачем этот случай отдельно?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        b in c..d && a in c..d -> return (b - a)
Зачем скобки?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = abs(x1 - x2) == abs(y1 - y2) || (x1 == x2) || (y1 == y2)
Длинные строчки лучше разбивать на несколько более коротких

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return sqrt(sqr(x2 - x1) + sqr(y2 - y1)) + r1 <= r2
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +            if (b <= c) {
Почему где-то `<=`,  а где-то `<`?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return m / gcd(m, n) * n
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var result = n - 1
Нет ли более точной верхней границы на возможные делители числа `n`?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = 0
Нет ли более точной границы для вашего перебора? Нельзя ли обойтись вообще без перебора?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        lastDigit = number % 10
Зачем вы меняете `lastDigit`?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += sum[i]
Почему нельзя считать эту переменную сразу? Зачем сперва перекладывать `a` в `sum`?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (isPrime(i)) {
Зачем проверять число на простоту, если вы проверяете делители от меньшего к большему?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.size == 0) list.add(0)
Такое ли условие должно быть для того, чтобы результат конвертации был `[0]`?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
Для подобных операций следует использовать не строку, а список строк или `StringBuilder`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in digits) {
`i` --- не очень удачное имя для этой переменной, так как это не та переменная, по которой мы что-то индексируем в этом цикле

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return result
Почему бы не воспользоваться функцией `decimal`?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list1 = mutableListOf(1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1)
Вместо двух списков лучше использовать список пар

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (digital.matches(Regex("""\d{2}\.\d{2}\.\d+"""))) {
Почему здесь вы не воспользовались идиомой `val parts = ... else return ""`?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (parts[1].toInt() in 1..12 && parts[0].toInt() in 1..31) {
Зачем это проверять здесь, а не после того, как вы получили переменные `day / monthNum`?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        val parts = phone.split(" ").joinToString()
Это можно сделать через `filter`

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return parts.split(Regex("""[^+\d]+""")).joinToString().filter { it != ' ' && it != ',' }
Откуда в строке может появиться запятая или пробел?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                Double.NaN
Что?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (parts[i].matches(Regex("""\d+""")) && parts[i + 1].matches(Regex("""\+"""))) {
Эти две проверки можно сделать и без regex'ов

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                i % 2 != 0 -> {
Этой проверки можно избежать, если задать шаг итерирования у цикла

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (list[i] == list[i + 1] && str != "") return result
Пустые строки лучше сперва отфильтровать

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val pricesList = mutableListOf<Double>()
Лучше список пар

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (element.matches(Regex("""(.+ \d+.\d+)|(.+ \d+)"""))) {
Этот регекс можно записать проще

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (pricesList[i] >= maxPrice) {
Если воспользоваться списком пар, этого цикла можно будет избежать

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        val listOfArabic = listOf(1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1)
Список пар

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (parts[i] == "C" && (parts[i + 1] == "M" || parts[i + 1] == "D")) {
Что будет, если вашей функции на вход подать строку "CC"?

2016-11-02 14:29 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    val centerX: Double = (diameter.begin.x + diameter.end.x) / 2
* Система типов Котлина выведет тип переменной автоматически

2016-11-08 16:46 UTC, grafovdenis commented on src/lesson4/task1/List.kt
> +        if (isPrime(i)) {
Я же проверяю возможный делитель на простоту, а не число

2016-11-10 10:13 UTC, grafovdenis commented
recheck assignment

2016-11-14 12:48 UTC, ice-phoenix requested changes

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (((initial * k) * k) * k)
Много лишних скобок вокруг законченных выражений

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`return when { ... }`

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when{
Форматирование кода

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        a + b > c && b + c > a && a + c > b ->
Проще сперва найти максимальную сторону, а потом все считать относительно нее

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`return when ...`

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`return when ...` -> one-liner

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    when {
Можно упростить через `min / max` или `list.sorted`

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return k in m..n
* Лучше `return k * k in ...`
* Нужно ли проверять квадрат `k` на то, что он больше `m`?

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += digit * pow(base, power)
Можно ли обойтись без постоянного повторного возведения `base` в степени, отличающиеся на 1?

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in str.length - 1 downTo 0) {
Зачем вам цикл по индексам, если сами индексы вы не используете?

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        } else i++
:+1:

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
Лучше `StringBuilder` или список строк

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return String.format("%d %s %d", day, month, year)
Почему в двух похожих функциях вы используете два разных стиля обработки ошибок? В одном случае проверяете каждое значения индивидуально, во втором --- проверяете все сразу в самом конце.

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return parts.filter { it != ' ' && it != '(' && it != ')' && it != '-' }
Можно `it !in ...`

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            continue
Разве это исключение не говорит об ошибке формата строки с прыжками?

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                continue
См. замечание выше

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                parts[i] == "+" -> result += parts[i + 1].toInt()
Как ваш код проверяет, что нет ситуации, когда в строке два числа / два знака операции подряд?

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val list = if (str != "") str.toLowerCase().split(" ") else return -1
Зачем проверка на пустоту строки?

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (part.isNotEmpty()) {
Лучше сперва сделать `list.filter`, чтобы избавиться от пустых строк

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                val price = if (values[1].toDouble() != 0.0) values[1].toDouble() else return "0.0"
Это не проверка на положительность цены

2016-11-14 12:48 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                    result += list[i].first
Лучше сканировать строку слева направо и проверять элементы вашего списка `list` на то, что их символьное представление входит в строку

2016-11-14 12:49 UTC, ice-phoenix commented
recheck all

2016-11-14 12:50 UTC, ice-phoenix commented
recheck all

2016-11-16 13:47 UTC, ice-phoenix commented
recheck all

2016-11-16 13:52 UTC, ice-phoenix requested changes

2016-11-16 13:52 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var point1 = Point(0.0,0.0)
Форматирование кода

2016-11-16 13:52 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            if (points[i].distance(points[j]) > maxDist) {
Повторно используемые выражения следует вынести в отдельные переменные

2016-11-16 13:52 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +val listOfLetters = listOf(1 to "a", 2 to "b", 3 to "c", 4 to "d", 5 to "e", 6 to "f", 7 to "g", 8 to "h")
Это все можно просто заменить строкой

2016-11-21 11:32 UTC, ice-phoenix requested changes

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((initial * k) * k) * k
Лишние скобки вокруг законченных выражений

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val list = listOf(a, b, c).sorted()
:+1:

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return list[0] <= s && list[1] <= r || list[0] <= r && list[1] <= s
:+1:

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return if (b == 0) a else gcd(b, a % b)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun squareBetweenExists(m: Int, n: Int): Boolean = pow(ceil(sqrt(m.toDouble())),2) <= n
Форматирование кода

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return parts.filter { it !in " ()-" }
Зачем вы два раза фильтруете пробелы?

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        when {
Можно как `val y = when { ... }`

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val parts = if (notation.matches(Regex("""\w\d"""))) notation.split("") else throw IllegalArgumentException()
Зачем `split`? Почему не просто `notation[0] / notation[1]`?

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +                xInt = i + 1
Почему не просто `indexOf`?

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if (x.matches(Regex("""[a-h]""")) && y.matches(Regex("""[1-8]"""))) {
Почему проверяем через регулярные выражения, а не через перевод строки в обычные типы `Char / Int`?

2016-11-21 11:32 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if (start.column in 1..8 && start.row in 1..8 && end.column in 1..8 && end.row in 1..8) {
Разве нет функции `Square.inside()`?

2016-11-23 10:59 UTC, ice-phoenix commented
recheck all

2016-11-23 10:59 UTC, ice-phoenix commented
recheck all

2016-11-23 11:00 UTC, ice-phoenix commented
recheck all

2016-11-25 14:18 UTC, ice-phoenix requested changes

2016-11-25 14:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
`when { return ... }` ==> `return when { ... }` + one-liner

2016-11-25 14:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var x = 1
Не очень удачные имена переменных

2016-11-25 14:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return String.format("%d %s %d", day, month, year)
Все еще актуально

2016-11-25 14:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                throw IllegalArgumentException()
Нельзя ли все это проверить без необходимости второго цикла?

2016-11-25 14:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +fun sameColor(first: Square, second: Square) = (first.column + first.row) % 2 == (second.column + second.row) % 2
:+1:

2016-11-25 14:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val y = if (notation[1] in '1'..'8') notation[1].toString().toInt() else throw IllegalArgumentException()
Может быть, обойдемся без `toString().toInt()`?

2016-11-25 14:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    }
Может быть, есть способ сделать из буквы цифру несколько проще, чем этот?

2016-11-25 14:18 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                if (column != width - 1) sb.append(",")
В таких случаях обычно запятую добавляют всегда, а лишнюю запятую в конце откусывают снаружи цикла

2016-11-26 20:00 UTC, ice-phoenix requested changes
Оставшиеся замечания следует исправить, с матрицами, насколько я вижу, все сделано довольно неплохо.

2016-12-05 09:49 UTC, ice-phoenix requested changes

2016-12-05 09:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-12-05 09:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return str[n - 1].toInt() - 48
Давайте мы сделаем, чтобы эти функции не собирали в строку все промежуточные и ненужные нам результаты?

2016-12-05 09:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return str[n - 1].toInt() - 48
Давайте мы сделаем, чтобы эти функции не собирали в строку все промежуточные и ненужные нам результаты?

2016-12-05 09:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list = mutableListOf(1000 to "M", 900 to "CM", 500 to "D", 400 to "CD", 100 to "C",
Зачем `mutableListOf`?

2016-12-05 09:49 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return parts.filter { it !in "()-" }
Почему сразу не сделать оба фильтра?

2016-12-05 09:49 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +            sb.deleteCharAt(height - 1)
Вот этот вызов, кажется, немножко не там, где надо

2016-12-12 10:01 UTC, ice-phoenix requested changes

2016-12-12 10:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += digit * pow(base, power)
Все еще актуально

2016-12-12 10:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return parts.filter { it !in "()- " }
Эту функцию можно сделать `one-liner`'ом

2016-12-12 10:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            continue
Все еще актуально

2016-12-12 10:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                continue
Все еще см. выше

2016-12-12 10:01 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +                            medium = Square(i, j)
Зачем продолжать искать дальше?

2016-12-12 10:01 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +                        if (abs(end.column - i) == abs(end.row - j) && abs(start.column - i) == abs(start.row - j)) {
Все это можно сделать намного проще

2016-12-18 21:59 UTC, grafovdenis commented
recheck assigned

2016-12-18 22:56 UTC, ice-phoenix commented
recheck all

2016-12-18 23:01 UTC, ice-phoenix commented
С учетом статистики и замечаний у вас все "Хорошо". Поздравляем!

2017-07-26 18:23 UTC, closed without merging