Задачи
Kotlin-Polytech/KotlinAsFirst2016 pull request #202
Opened 2016-10-31 09:35 UTC by oddishwolf

Все задачи

2016-10-31 09:54 UTC, mglukhikh commented
Старайтесь в будущем не забывать об этом, пожалуйста. Просматривать все 94 репозитория на предмет изменений у нас нет возможности, так что, пока вы на кнопку не нажали, мы вынуждены считать, что вы ничего не сделали.

2016-10-31 09:56 UTC, oddishwolf commented
Сейчас все загрузил, есть шанс на исправление оценки? 


>Понедельник, 31 октября 2016, 12:54 +03:00 от Mikhail Glukhikh <notifications@github.com>:
>
>Старайтесь в будущем не забывать об этом, пожалуйста. Просматривать все 94 репозитория на предмет изменений у нас нет возможности, так что, пока вы на кнопку не нажали, мы вынуждены считать, что вы ничего не сделали.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-10-31 10:54 UTC, mglukhikh commented
> Сейчас все загрузил, есть шанс на исправление оценки? 

Сейчас сообщать куратору, что вы злостный двоечник, я не буду. Но в конце семестра повторение подобной ситуации вполне может привести, например, к неполучению автомата или к снижению заслуженной оценки на балл.

2016-11-06 17:43 UTC, mglukhikh commented
recheck all

2016-11-06 17:57 UTC, mglukhikh requested changes
Пара задач решена с ошибкой (см. отчёт бота). Плюс замечания по стилю. Пожалуйста, исправьте замечания и ошибки, прежде чем решать другие задачию

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +             else t1 + t2 + ((h - s1 - s2)/v3)
1) Старайтесь расставлять пробелы консистентно (то есть всюду одинаково). А то у вас в одном месте `h/v1`, в другом `s1 +s2`, в третьем `v1 * t1`. Это можно исправить автоматически с помощью авто-форматирования кода: Ctrl+Alt+L.

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +             else t1 + t2 + ((h - s1 - s2)/v3)
2) В этом месте лучше использовать конструкцию `when`, код будет выглядеть аккуратнее

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else 3
Здесь и далее, лучше использовать `&&` вместо `and`, `||` вместо `or`.

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    val n2 = ((number/1000) + ((number/100)%10))
Пробелы

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +     else return false
`if (x) return true else return false` эквивалентно `return x`.

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    } else return -1
Подумайте, нельзя ли решить эту задачу короче

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
1) Пробелы 
2) `if (x) return true else return false`

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +
Пробелы, ненужные пустые строки

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        m = (m*10 + (num%10))
Пробелы

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    else return 0 // НЕ ДОДЕЛАНА !!!
Функция будет работать неверно с отрицательными `n`

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var abswithoutsqrt = 0.0
camelCase: `absWithoutSqrt`

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..(v.size - 1)) {
Используйте цикл по элементам: `for (elem in v) { ... }` (см. пример negativeList)

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    else return sum/k
В начале функции поехало форматирование. Пробелы в `sum/k`

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Эта проверка не нужна

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            list[i]=sum
Пробелы

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    result.sorted()
Этот вызов функции не нужен

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
В этой функции не нужно повторять код `factorize`, её следует просто вызвать

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        }
Для преобразования названия месяца в число создайте список названий (лучше на верхнем уровне, то есть перед функцией) и используйте `list.indexOf`.

2016-11-06 17:57 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        }
Здесь тоже можно использовать список названий месяцев (просто обратиться к нему по индексу).

2016-11-15 10:02 UTC, mglukhikh commented
Пожалуйста, исправьте замечания и ошибки в уроках 1-5, прежде чем решать задачи из следующих уроков. Задачи 6-го урока я проверю позже

2016-11-22 16:18 UTC, mglukhikh commented
recheck all

2016-11-22 16:23 UTC, mglukhikh commented
Замечания из последнего Review по-прежнему в силе. Также, две задачи по-прежнему решены неверно

2016-11-23 20:22 UTC, oddishwolf commented
Можете объяснить что не так с данной задачей? Уже перепробовал массу вариантов, но бот выводит ошибку. Я практически уверен, что ответ должен быть правильным:
/**
 * Сложная
 *
 * В строке представлено выражение вида "2 + 31 - 40 + 13",
 * использующее целые положительные числа, плюсы и минусы, разделённые пробелами.
 * Наличие двух знаков подряд "13 + + 10" или двух чисел подряд "1 2" не допускается.
 * Вернуть значение выражения (6 для примера).
 * Про нарушении формата входной строки бросить исключение IllegalArgumentException
 */
fun plusMinus(expression: String): Int {
    val members = expression.split(" ")
    var result = members[0].toInt()
    val LengthOfString = members.size
val RightNumber = Regex("""\d""")
    val RightSymbol = Regex("""[+-]""")
    val NotRightFormat = Regex("""[^\d+-]""")
    if ((LengthOfString == 1) && (members[0].contains(NotRightFormat)) || expression == "") throw IllegalArgumentException("Wrong")
    else {
        for (i in 0..LengthOfString - 2) {
            val TwoPluses = members[i].contains(RightSymbol) && members[i + 1].contains(RightSymbol)
            val TwoNumbers = members[i].contains(RightNumber) && members[i + 1].contains(RightNumber)
            val AllNotRightSymbols = members[i].contains(NotRightFormat) || members[i + 1].contains(NotRightFormat)
            val WrongString = TwoPluses || TwoNumbers || AllNotRightSymbols
            if (WrongString) throw IllegalArgumentException("Wrong")
            else {
                if (members[i] == "+") result += members[i + 1].toInt()
                if (members[i] == "-") result -= members[i + 1].toInt()
            }
        }
    }
    return result
}
 

2016-11-24 21:34 UTC, oddishwolf commented
Здравствуйте. Я там кажется "немного" перестарался и получил вот это. Если знаете как с этим бороться и что делать, напишите пожалуйста. Я не могу теперь пушить задачи и проверять их через бота, так как постоянно пишет "Failure: Check Ended". Иными словами, сейчас не в состоянии загрузить решенную задачу для вашей проверки. 

2016-11-25 07:16 UTC, mglukhikh commented
recheck all

2016-11-25 07:18 UTC, mglukhikh commented
Вроде бы тестирование успешно прошло. Возможно, это был временный эффект, связанный с проблемами сервера, на котором работает бот.

2016-11-25 21:32 UTC, mglukhikh requested changes
Пересмотрел уроки 2-5. Дал вам подсказку по поводу `plusMinus`. Осталось в силе много старых замечаний, так что к уроку 6 пока приступать рано.

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
`if (x) return true else return false` эквивалентно `return x`

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
См. выше

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    while ((num_m != 0) and (num_n != 0)) {
Лучше использовать ленивый `&&`

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Эта проверка по-прежнему не нужна

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    result.sorted()
Этот вызов функции по-прежнему не нужен

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    result.sorted()
Вы здесь дублируете код `factorize`, её нужно просто вызвать

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Замечание верное, но не на том месте

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        var Num = n
С маленькой буквы

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        }
Повторно! Для преобразования названия месяца в число создайте список названий (лучше на верхнем уровне, то есть перед функцией) и используйте `list.indexOf`.

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        }
Повторно! Здесь тоже можно использовать список названий месяцев (просто обратиться к нему по индексу).

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val RightNumber = Regex("""\d""")
Переменные должны называться с маленькой буквы

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..members.size - 1) {
Здесь лучше применить цикл по элементам: `for (member in members) { ... }`

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val NotRightFormat = Regex("""[^\d+-]""")
Переменные следует называть с маленькой буквы

2016-11-25 21:32 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var result = members[0].toInt()
Что будет, если `members[0]` окажется не числом? Например, для `expression = "BAD"`.

2016-11-27 21:46 UTC, oddishwolf commented on src/lesson5/task1/Parse.kt
> +    var result = members[0].toInt()
Так это у меня и есть основная проверка

2016-11-27 21:47 UTC, oddishwolf commented on src/lesson5/task1/Parse.kt
> +    var result = members[0].toInt()
val notRightFormat = Regex("""[^\d+-]""")
...
if ((lengthOfString == 1) &&#  ((members[0].contains(notRightFormat)) || expression == "")) throw IllegalArgumentException(" ")

2016-11-27 21:48 UTC, dmitrirazumov commented on src/lesson5/task1/Parse.kt
> +    var result = members[0].toInt()
val notRightFormat = Regex("""[^\d+-]""")
if ((lengthOfString == 1) && **_((members[0].contains(notRightFormat))_** || expression == "")) throw IllegalArgumentException(" ") #

2016-11-30 12:29 UTC, mglukhikh requested changes
Замечаний по коду почти не осталось. Не работают `digitNumber` и `plusMinus`. Исправьте их, и я закрою этот Pull Request.

2016-11-30 12:29 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Может исправите эту задачу наконец? Она работает неверно для отрицательных чисел

2016-11-30 12:29 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var C = 0.0
С маленькой буквы

2016-11-30 12:29 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Исправлено

2016-11-30 12:29 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var result = members[0].toInt()
Это замечательно, но вы до этой строчки просто не дойдёте. Так как словите исключение здесь.

2016-12-05 11:45 UTC, oddishwolf commented
Исправил все ошибки. Программы прошли проверку бота.

2016-12-05 15:34 UTC, mglukhikh commented
recheck all

2016-12-05 19:42 UTC, mglukhikh commented
Задача `mostExpensive` у вас не проходит тесты (причём даже локальные в учебном проекте). Доразбирайтесь уж с ней.

2016-12-10 10:26 UTC, mglukhikh requested changes
В целом всё в порядке, два незначительных замечания. Вы можете, по своему желанию, решать следующие задачи 5-го или 6-го урока или же перейти к 7-му. Судя по результатам тестирования, потратить ещё немножко времени на задачи уроков 5 и 6 было бы для вас полезно. Отмечу, например, что задача `plusMinus` решена хоть и правильно, но несколько сложновато, можно попроще.

2016-12-10 10:26 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun myFun(from: String, to: String, route: String): Int {
Пожалуйста, удалите эту функцию из проекта

2016-12-10 10:26 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            val WrongString = TwoPluses || TwoNumbers || AllNotRightSymbols
Напоминаю вам, что переменные следует называть в `camelCase`, например, `wrongString` (см. также ещё три переменные выше)

2016-12-10 10:27 UTC, mglukhikh commented
recheck all

2016-12-10 10:27 UTC, mglukhikh commented
recheck all

2016-12-17 20:16 UTC, oddishwolf commented
Программа "PlusMinus" почему-то проходит проверку бота через раз

2016-12-17 20:19 UTC, mglukhikh commented
Это потому, что бот делает случайные проверки, и вам то попадается тот случай, на котором ваша функция работает неправильно, то нет. По факту это значит, что задача решена с ошибкой

2016-12-17 20:25 UTC, oddishwolf commented
Надо ли мне еще что-то исправлять?

2016-12-17 20:31 UTC, mglukhikh requested changes
Посмотрел, написал замечаний. Текущая оценка за аттестацию получается 3.5. То есть зачёт у вас уже есть, для получения "3" автоматом нужно пройти тестирование, для получения "4" автоматом нужно также исправить все написанные замечания.

2016-12-17 20:31 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return true
Прошу проверить правильность работы функции `equals` тестами. Тесты добавить в тестовый файл урока 7.1.

2016-12-17 20:31 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    }
Отсутствует функция `hashCode()`.

2016-12-17 20:31 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +}
Функция не всегда проходит тесты. Возьмите один из контр-примеров бота и разберитесь, в чём дело.

2016-12-17 20:31 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun myFun(text: String): MutableList<String> {
Удалите, пожалуйста, эту функцию из репозитория

2016-12-17 20:31 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val c_length = (center.distance(other.center))
Названия `r_length` и `c_length` нарушают code style

2016-12-17 20:31 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    fun diameter(vararg points: Point): Segment {
Сдвиньте эту функцию на 4 пробела влево

2016-12-17 20:31 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    fun circleByDiameter(diameter: Segment): Circle {
И эту тоже

2016-12-17 20:31 UTC, mglukhikh commented on test/lesson5/task1/Tests.kt
> +    fun myFun() {
Тесты `myFun` также прошу удалить из репозитория

2016-12-17 20:31 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return list.toString()
Как будем в этом строковом представлении отличать колонки от рядов?

2016-12-17 21:09 UTC, oddishwolf commented
recheck all

2016-12-17 21:12 UTC, oddishwolf commented on src/lesson7/task1/Matrix.kt
> +    }
добавил

2016-12-17 21:15 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    }
Плохо добавили. Содержимое списка никак не учитывается.

2016-12-17 21:31 UTC, oddishwolf commented on src/lesson7/task1/Matrix.kt
> +    }
Надеюсь, что теперь правильно

2016-12-17 22:41 UTC, oddishwolf commented
Полностью переделал plusMinus, сделал через исключение. Думаю, так правильнее + короче. 
Бота прошел, судя по всему.

2016-12-17 23:39 UTC, oddishwolf commented
Если не секрет, почему вы поставили метку "mediocre"?

2016-12-18 16:46 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return true
Тестов функции `equals` пока так и не появилось

2016-12-18 16:47 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    }
Да, так верно

2016-12-18 16:48 UTC, mglukhikh commented
До good (4) осталось проверить `equals` тестами. А пока mediocre (3).

2016-12-18 20:12 UTC, oddishwolf commented on src/lesson7/task1/Matrix.kt
> +        return true
Написал тесты, запушил
@

2016-12-19 08:49 UTC, mglukhikh requested changes
Пока вашими тестами я не удовлетворён :(

2016-12-19 08:49 UTC, mglukhikh commented on test/lesson7/task1/Tests.kt
> +        assertEquals(false, createMatrix(2, 2, listOf(listOf(1, 1), listOf(2, 2))) != createMatrix(1, 1, listOf(listOf(1, 2), listOf(2, 2))))
Этот тест написан некорректно. Вы сравниваете матрицы разных размером, поэтому они должны быть НЕ РАВНЫ, а значит, `false` вначале нужно заменить на `true`. Сделайте это и проверьте, проходит ли тест на вашем компьютере.

2016-12-19 11:27 UTC, oddishwolf commented on test/lesson7/task1/Tests.kt
> +        assertEquals(false, createMatrix(2, 2, listOf(listOf(1, 1), listOf(2, 2))) != createMatrix(1, 1, listOf(listOf(1, 2), listOf(2, 2))))
Исправил

2016-12-19 20:51 UTC, mglukhikh commented
Дмитрий, ваша финальная оценка за семестр -- удовлетворительно, с моим мега-сложным заданием про функцию `equals` вы не справились даже со второй попытки. Тест по-прежнему написан неверно. Так что соглашайтесь на "3" автоматом или приходите 16 января на экзамен.

2016-12-19 20:51 UTC, closed without merging

2016-12-19 22:07 UTC, oddishwolf commented
Михаил Игоревич, хотел бы узнать, влияет ли оценка за финальное тестирование на экзаменационную оценку? За сегодняшнее тестирование я получил 5, а за аттестацию (в PR) тройку. 
Дмитрий Хорохорин, 13531/3

2016-12-20 11:18 UTC, mglukhikh commented
Да, правда, у вас до этого было два теста, написанных на 2. В среднем как раз получается 3.

2016-12-23 12:10 UTC, oddishwolf commented
Когда можно подойти с зачеткой и получить оценку за экзамен?



Отправлено из мобильной Почты Mail.Ru


вторник, 20 декабря 2016 г., 14:19 +0300 от Mikhail Glukhikh  <notifications@github.com>:
>Да, правда, у вас до этого было два теста, написанных на 2. В среднем как раз получается 3.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2016-12-23 17:04 UTC, mglukhikh commented
То есть вы согласны на "3". Хорошо, я поставлю эту оценку в ведомость. Если вы хотите получить запись в зачётке, то можно подойти на консультацию 13 января (10-00) или на экзамен 16 января (примерно с 10 до 19). Либо ищете одного из преподавателей, ведущих упражнения, они на кафедре чаще меня.