Programs by Prokhorovmax (Prokhorov Maxim, 13531/3)
Kotlin-Polytech/KotlinAsFirst2016 pull request #203
Opened 2016-10-31 11:54 UTC by Prokhorovmax

2016-11-06 17:35 UTC, mglukhikh requested changes
В целом всё нормально, незначительные замечания по стилю.

2016-11-06 17:35 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val matchResult3 = Regex("""[-+]""")
Старайтесь избегать подобных названий переменных: цифры 1, 2, 3 в данном случае ни о чём не говорят. В данном случае, например, подошли бы названия `matchDigitOrSign`, `matchDigit`, `matchSign`.

2016-11-06 17:35 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    if ((length == 1) && (parts[0].contains(matchResult1)) || expression == "") throw IllegalArgumentException("Wrong expression format")
Здесь лучше было бы поставить фигурные скобки после `if`: во-первых, потому, что строка длинновата, а во-вторых, потому, что у `else` фигурные скобки есть.

2016-11-06 17:35 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            val condition = (condition1 && condition2) || (condition3 && condition4) || condition5
Попробуйте подобрать более удачные названия для всех переменных `conditionX` и `condition`, И мне кажется, что проверка на `condition5` не нужна.

2016-11-06 17:35 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                    parts[i].matches(Regex("""[-]""")) -> result -= parts[i + 1].toInt()
Применение регэксов здесь кажется мне перебором. 

```
when (parts[i]) { 
    '+' -> ...
    '-' -> ...
}
```

2016-11-07 16:27 UTC, mglukhikh commented
recheck all

2016-11-07 16:32 UTC, mglukhikh commented
Не забудьте исправить замечания к 5-му уроку, пожалуйста. По 6-му, см. отчёт бота.

2016-11-11 12:09 UTC, Prokhorovmax commented on src/lesson5/task1/Parse.kt
> +            val condition = (condition1 && condition2) || (condition3 && condition4) || condition5
Исправил. Единственное, исходя из большинства тестов сайта (различные символы в качестве входной строки), могу сказать, что бывшее пятое условие (cond5) необходимо. Именно оно проверяет такие строчки. Возможно я что-то не понял или можно сделать по-другому, но я не придумал)

2016-11-15 10:37 UTC, mglukhikh requested changes
5-й урок принят. Что же касается шестого, то одна из задач в нём решена неверно, см. моё замечание.

2016-11-15 10:37 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val angle = Math.atan(Math.abs(s.begin.y - s.end.y) / Math.abs(s.begin.x - s.end.x))
Взятие здесь модуля кажется мне неверным, так как в результате вы можете получить угол только от 0 до пи пополам. Общее замечание: советую почитать про функцию `Math.atan2`.

2016-11-22 16:03 UTC, mglukhikh approved these changes
Хорошо, имеющиеся задачи из урока 6.1 тоже приняты. По своему выбору, вы можете порешать что-нибудь ещё из 6-го урока либо перейти к уроку 7.

2016-11-22 16:03 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val x = (this.point.x * Math.tan(this.angle) - other.point.x * Math.tan(other.angle) + other.point.y - this.point.y) / (Math.tan(this.angle) - Math.tan(other.angle))
Эту строку я бы разбил на две

2016-11-22 16:03 UTC, closed without merging