lesson 6
Kotlin-Polytech/KotlinAsFirst2016 pull request #204
Opened 2016-10-31 19:13 UTC by lixir

2016-11-01 18:06 UTC, gagarski requested changes

2016-11-01 18:06 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    if (diameter.begin.x < diameter.end.x) minX = diameter.begin.x
`Math.min()`

2016-11-01 18:06 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        if (Math.abs(Math.cos(angle)) <= 0.0000000000000001) {
Лучше вместо `Math.abs(Math.cos(angle)) <= 0.0000000000000001` делать  `Math.tan(angle).isInfinite()`. 

Красивее было бы найти прямую с минимальным наклоном и искать точку пересечения по её уравнению.

2016-11-01 18:06 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    if (abAngle * 2 >= Math.PI) abAngle -= Math.PI
Почитайте документацию, может ли быть возвращаемое значение `Math.atan()` больше или равно Math.PI?

2016-11-08 15:16 UTC, gagarski commented
recheck all

2016-11-08 15:17 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        if (Math.abs(Math.cos(angle)) <= 0.0000000000000001) {
актуально

2016-11-08 15:20 UTC, gagarski requested changes

2016-11-08 15:20 UTC, gagarski commented on tutorial/chapter05.adoc
> +                           В Котлине это делается так:
Настоятельно рекомендую вам откатить файлы tutorial'а в исходное состояние. Иначе у вас могут возникнуть проблемы с конфликтами изменений и с проверкой ботом.

2016-11-08 15:22 UTC, lixir commented on tutorial/chapter05.adoc
> +                           В Котлине это делается так:
как это сделать?

2016-11-09 22:38 UTC, lixir commented
Type check all in your request and control D

2016-11-09 22:39 UTC, lixir commented
recheck all

2016-11-09 22:43 UTC, lixir commented
Type recheck all in your request and control D

2016-11-09 22:43 UTC, lixir commented
Type check all in your request and control D

2016-11-09 22:48 UTC, lixir commented
Type check all in your request and control

2016-11-10 09:25 UTC, lixir commented on src/lesson6/task1/Geometry.kt
> +        if (Math.abs(Math.cos(angle)) <= 0.0000000000000001) {
не работает

2016-11-10 15:30 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        if (Math.abs(Math.cos(angle)) <= 0.0000000000000001) {
Что не работает?

2016-11-10 15:45 UTC, gagarski commented on tutorial/chapter05.adoc
> +                           В Котлине это делается так:
Почитайте документацию по git.

2016-11-10 15:46 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (m == n) return m
Если уж взялись переделывать уже сделанные задания, то почитайте про алгоритм Евклида. Он и эффективнее и реализация у вас получится короче.

2016-11-10 17:54 UTC, lixir commented on src/lesson6/task1/Geometry.kt
> +        if (Math.abs(Math.cos(angle)) <= 0.0000000000000001) {
тангенс не бесконечный

2016-11-15 20:18 UTC, mglukhikh commented
recheck all

2016-11-15 20:24 UTC, mglukhikh commented
Насколько я вижу, опровергающий пример к `minContainingCircle` вполне верен, так что следует исправить ошибку в решении.

2016-11-15 20:26 UTC, mglukhikh commented
Советую просто взять пример, как он дан ботом, и протестировать функцию на нём. Обязательно добавьте пример в список тестов.

2016-11-15 20:29 UTC, mglukhikh commented
Опровергающий пример с предпоследнего тестирования, кстати, тоже верен.

2016-11-20 00:08 UTC, lixir commented
recheck all

2016-11-21 13:14 UTC, gagarski requested changes
Пока не

2016-11-21 13:14 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +fun rookMoveNumber(start: Square, end: Square): Int {
[Здесь и далее] Не забывайте про однострочные функции (с `=`). Конеркетно эту можно записать в виде 
```kotlin
fun rookMoveNumber(start: Square, end: Square): Int = when {
    // ...
}

2016-11-21 13:14 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +            for (column in 0..width-1) sb.append(this[row,column])
Числа внутри строки в данной реализации ничем не разделены. Попробуйте вызвать ваш `toString` для какой-нибудь матрицы.

2016-11-21 13:14 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    for (i in 0..floor(min(height, width) / 2.0).toInt()) {
Целочисленное деление положительного числа на 2 округлит его вниз, не нужно переходить к числам с плпавающей точкой.

2016-11-21 13:14 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    for (i in 0..floor(min(height, width) / 2.0).toInt()) {
Целочисленное деление положительного числа на 2 округлит его вниз, не нужно переходить к числам с плпавающей точкой.

2016-11-21 13:14 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +        for (j in 0..result.width - 1) result[i, j] = transpose[i, result.width - 1 - j]
- Зачем вы транспонируете матрицу в `result` , если всё равно переписываете её целиком?
 - Зачем вообще здесь транспонировать матрицы? Это разве сильно упрощает жизнь?

2016-11-21 13:14 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +            if (true !in set) return Triple(true, row, column)
- Можно ли прервать два внутренних цикла при нахождении первого несовпадения ключа и замка?
 - Можно ли вместо множества обойтись одним булевским флагом?

2016-11-21 13:14 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    val nullMatrix = createMatrix(matrix.height + 2, matrix.width + 2, 0)
Иожно ли обойтись без копирования в `nullMatrix` (добавив проверку на корректность хода в цикл).

2016-11-21 13:14 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    val result = matrix
`val result = matrix` - бессмысленная операция, матрица при этом не копируется, просто создаётся новая ссылка на неё (можете проверить).

2016-11-21 13:14 UTC, gagarski commented on src/lesson8/task1/Files.kt
> +                    j += word.toLowerCase().split(string.toLowerCase()).size - 1
В `substrings` могут быть и строки с пробелами и строки с переносом строки.

2016-11-21 13:14 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +                    k = true
Почитайте, как делать `break` нескольких циклов сразу: https://kotlinlang.org/docs/reference/returns.html

2016-11-21 13:14 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +            if (end in list) break
Можно ли обойтись без переменной `list` и многократного перебора этого списка для поиска `end` в нём (например, проверяя на равенство `step` и `end`)?
См. также про `break` нескольких циклов сразу: https://kotlinlang.org/docs/reference/returns.html

2016-11-21 13:14 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +    val set = mutableSetOf<Square>()
Почитайте главу 6.5 tutorial'а и слайды, к лекции 6.5. Можно применить один из классических алгоритмов, описанных там.

2016-11-21 20:49 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[row,column])
А теперь вспомните функцию `joinToString` и подумайте, не делаете ли вы то же самое?

2016-11-21 20:49 UTC, gagarski approved these changes

2016-11-25 07:56 UTC, mglukhikh commented
recheck all

2016-11-25 08:00 UTC, mglukhikh commented
recheck all

2016-11-25 08:08 UTC, mglukhikh commented
recheck all

2016-11-25 08:17 UTC, mglukhikh commented
Рад вам сообщить, что вы выполнили программу этого семестра с оценкой "ОТЛИЧНО" (можете подойти ко мне с зачёткой, и я вам эту оценку поставлю). При желании, можно порешать ещё какие-нибудь задачи.

2016-11-25 08:20 UTC, mglukhikh commented
Должен вас также поблагодарить за помощь в тестировании нашей инфраструктуры

2016-12-03 21:01 UTC, lixir commented
разве в последнем тесте Expected не равен Actual, в IDEA прошли оба теста

2016-12-05 18:23 UTC, lixir commented
recheck all

2016-12-10 13:21 UTC, lixir commented
recheck all

2016-12-10 13:33 UTC, lixir commented
recheck all

2016-12-13 17:14 UTC, gagarski commented
recheck all

2016-12-13 23:59 UTC, lixir commented
recheck all

2016-12-14 09:30 UTC, gagarski commented
recheck all

2016-12-14 11:02 UTC, gagarski commented
recheck all

2017-01-27 07:08 UTC, lixir commented
recheck all

2017-07-26 18:23 UTC, closed without merging