lesson 3. Task 1 except the hard ones
Kotlin-Polytech/KotlinAsFirst2016 pull request #205
Opened 2016-11-01 11:10 UTC by Nikolay123456789

2016-11-01 17:55 UTC, gagarski requested changes

2016-11-01 17:55 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if (n in 1..2) 1 else fib(n - 2) + fib(n - 1)
- Рекурсивное решение напрашивается, исходя из определения чисел Фибоначчи, но попробуйте посчитать, к скольки вызовам функции `fib()` приведёт вызов `fib(10)`, `fib(40)`, `fib(55)`, сколько среди них вызовов с одинаковыми аргументами и решить задачу более оптимальным способом.

2016-11-01 17:55 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    do {
Почитайте про более эффективные чем полный перебор алгоритмы вычисления НОД и НОК

2016-11-01 17:55 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    do {
Можно решить эту задачу с использованием НОК (или НОД).

2016-11-01 17:55 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +     if (reverted == n) return true
- Вы используете довольно многословный способ вычисления булевского значения.
Постарайтесь озознать (в уме или на бумаге), что 
```kotlin
if (x) true else false
```
эквивалентно
```kotlin
x
```

Таким образом можно написать просто `return reverted == n`, а после этого можно записать функцию и ещё короче.

2016-11-01 19:55 UTC, Nikolay123456789 commented
Я не понимаю какие ощибки я сделал в digitNumber,isCoPrime,HasDIfferentDigits

2016-11-01 21:02 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (k in 1..m * n) {
Вы всё ещё перебираете все числа. Поищите, например, про алгоритм Евклида.

2016-11-01 21:07 UTC, gagarski commented
> Я не понимаю какие ощибки я сделал в digitNumber,isCoPrime,HasDIfferentDigits

> digitNumber

Вы не рассмотрели отрицательные числа

> isCoPrime

См. пример, приведённый ботом: 2 и 1 являются взаимно простыми числами, а ваша функция говорит, что нет.

> HasDIfferentDigits

 Протестируйте вашу функцию на числах из одной цифры: 1, 2, 3, 4 и т. д. Эти числа не содержат различающихся цифр, ваша функция должна возвращать `false`.

2016-11-08 15:13 UTC, gagarski requested changes

2016-11-08 15:13 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (k in 1..m * n) {
Вы всё ещё перебираете все числа. Поищите, например, про алгоритм Евклида.

2016-11-08 15:13 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (reverted == n) true else false
Теперь это выражение с `if` ничего не делает. Можно его просто убрать.

2016-11-08 15:13 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    } while (div <= n)
Можно ли, достигнув какого-то числа закончить перебор и вернуть `n`?

2016-11-08 15:13 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    } while (div >= 1)
Можно ли, достигнув какого-то числа закончить перебор и вернуть `1`?

2016-11-08 15:13 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean {
Можно использовать `lcm` или `gcd`.

2016-11-10 12:04 UTC, Nikolay123456789 commented on src/lesson3/task1/Loop.kt
> +    } while (div <= n)
Извините,я не понимаю что вы имеете виду про minDivisor и maxDivisor

2016-11-10 16:12 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    } while (div <= n)
Вы перебираете числа от 2 до n. Может ли, например 9999 быть минимальным делителем числа 10000? А 9997? А 200?

2016-11-10 16:13 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    } while (div <= n)
Посмотрите также примеры из данного урока.

2016-11-22 16:21 UTC, mglukhikh commented
recheck all

2016-11-27 13:12 UTC, gagarski requested changes

2016-11-27 13:12 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (NOD(m, n) != 1) return false
- Сначала можно заменить на `return NOD(m, n) == 1`, а потом записать в виде однострочной функции.

2016-11-27 13:12 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int {
Вы чуть ниже определили функцию для НОД. Можно ли вычислить НОК с помощью неё, а не с помощью полного перебора?

2016-11-27 13:12 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val letters = listOf("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y",
Старайтесь переносить такие длинные строки (например после запятых)

2016-11-27 13:13 UTC, gagarski commented
recheck all

2016-11-27 20:30 UTC, nikoscharits24 commented on src/lesson3/task1/Loop.kt
> +    if (NOD(m, n) != 1) return false
return NOD(m,n) == 1 просто это оставить?

2016-11-27 20:38 UTC, Nikolay123456789 commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int {
fun lcm(m: Int, n: Int): Int {
   return (m * n)/NOD(m,n)
} 
это правильно написано?

2016-12-05 16:24 UTC, gagarski commented
recheck all

2016-12-05 16:27 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int {
Лучше `m * NOD(m,n) / n`. Так вы измежите целочисленного переполнения при умножении для m = n = 1000000, например.

2016-12-05 16:27 UTC, gagarski approved these changes

2016-12-05 16:28 UTC, closed without merging