Sidorina_Lesson7
Kotlin-Polytech/KotlinAsFirst2016 pull request #207
Opened 2016-11-06 15:26 UTC by ElenaLaufeyson

Для решений заданий 7 урока.

2016-11-06 18:50 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    return MatrixImpl<E>(height, width, e)
Здесь явное указание `E` необязательно.

2016-11-06 18:50 UTC, mglukhikh commented
Пока всё правильно.

2016-11-15 09:58 UTC, mglukhikh requested changes
В целом всё хорошо, незначительные замечания по коду.

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        result = result * 10 + width
В качестве коэффициентов рекомендуется использовать простые числа (это улучшает равномерность распределения получающихся хэш-кодов).

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        var str: String = ""
Здесь лучше использовать `StringBuilder` (см. конец 7-го раздела учебного пособия). Когда вы оперируете со строками напрямую, создаётся слишком много объектов, которые потом Garbage Collector вынужден удалять.

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    var flag = false
Избегайте подобных названий переменных. Конкретно в этом случае можно вообще обойтись без неё.

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    val numb = (Math.min(height, width)+1)/2 //число "кругов"
Форматирование (нажмите Ctrl+Alt+L)

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    val matr = createMatrix<E>(matrix.height, matrix.width, matrix[0,0])
Явное указание `E` необязательно

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    val list = mutableListOf<Int>()
В этой функции эффективнее применить другой вид коллекции.

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    var sum = 0
Эту переменную лучше определить внутри циклов, тогда её не придётся каждый раз обнулять в конце тела циклов

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +            if (i-1 > -1) {
Мне кажется, `i > 0` выглядит гораздо понятнее

2016-11-15 09:58 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +            matr[i,j] = sum
Опционально: попробуйте придумать более короткое решение данной задачи. Не забывайте, что вы вправе определить для матрицы какие-либо новые функции -- для этого либо добавьте их в интерфейс, либо определите их как расширения -- см. например `Matrix<Int>.times` ниже в этом же файле.

2016-11-15 17:08 UTC, ElenaLaufeyson commented on src/lesson7/task2/Matrices.kt
> +    val list = mutableListOf<Int>()
А Вы не подскажете, какой именно вид коллекции здесь эффективнее применить?

2016-11-16 18:41 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    val list = mutableListOf<Int>()
Ну я вам напомню, что рассказывал я вам на лекциях про три вида коллекций: список (list), множество (set) и дек (Deque). В данной задаче всё, что вы делаете с этой коллекцией -- это `add` и `contains`. Осталось вспомнить, в каком из этих трёх видов коллекций эти операции реализованы эффективнее.

2016-11-28 17:24 UTC, ElenaLaufeyson commented on src/lesson7/task2/Matrices.kt
> +    val list = mutableListOf<Int>()
Да, я понимаю, что Вы хотите сказать, что эффективнее здесь воспользоваться коллекцией set, поскольку она исключает повторы при записи, но в моем случае мне, наоборот, нужно "отлавливать" эти повторы, поэтому мне подойдет и list, тем более, что он будет работать быстрее, поскольку, в отличие от set-а, он будет просто записывать в список, не проверяя каждый раз наличие в нем текущего элемента. Я проверяю contains не для того, чтобы добавлять или не добавлять элементы, а для того, чтобы отлавливать повторы, и, если есть повтор, сразу выходить из функции. 
Также не вижу смысла использовать тут дек, поскольку в данном случае он будет полностью равносилен списку.

2016-11-28 18:47 UTC, ElenaLaufeyson commented
Почему не работает функция sibilants, если то, что ожидалось ботом, и то, что получилось, абсолютно одинаковое?

2016-11-28 20:35 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    val list = mutableListOf<Int>()
Ваши рассуждения, к сожалению, неверны. Проблема в том, что `contains` у списка размером `N` работает примерно в `N` раз медленнее, чем у множества размером `N`. И это обстоятельство заведомо перекрывает всё остальное -- `add` у списка и множества работает с сопоставимой скоростью. Одно из преимуществ множества состоит как раз в том, что `add`, `contains` и `remove` в нём работают очень быстро.

2016-11-28 20:50 UTC, mglukhikh reviewed
В основном всё в порядке. Прочитайте этот Review и мой ответ на на ваше рассуждение про list и set.

2016-11-28 20:50 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +    for (line in File(inputName).readLines())
Блоки такой длины, как у этого цикла `for`, обычно заключают в фигурные скобки -- даже если формально этого можно не делать.

2016-11-28 20:50 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +            output.newLine()
Это как раз то место, в котором ваше решение, вероятно, отличается от опорного -- вы добавляете лишний `newLine` после последней строки текста. GitHub этот перевод строки, к сожалению, съедает, так что в отчёте бота этого незаметно. Но в данном случае я согласен, что разница несущественная -- обычно этот лишний перевод строки не учитывается при сравнении. Мы поправим соответствующим образом тесты.

2016-11-28 20:50 UTC, mglukhikh approved these changes

2016-11-28 20:52 UTC, mglukhikh commented
Думаю, что я уже сейчас могу вас поздравить с успешным завершением программы этого семестра с оценкой ОТЛИЧНО. Тестирование у вас пройдено, так что можете подойти ко мне с зачёткой, я поставлю вам оценку.

2016-11-28 20:52 UTC, closed without merging

2016-11-28 21:01 UTC, mglukhikh commented
Ну и как всегда, вы можете, если вам хочется, порешать ещё какие-либо задачи. Welcome.