Lesson 5
Kotlin-Polytech/KotlinAsFirst2016 pull request #208
Opened 2016-11-07 17:49 UTC by Pashnik

2016-11-07 17:59 UTC, Pashnik commented
Может ли быть ошибка в боте? У меня в Idea с такими же данными проходит.

2016-11-08 21:15 UTC, gagarski commented
> Может ли быть ошибка в боте? У меня в Idea с такими же данными проходит.

Протестируйте с несколькими пробелами подряд в разных местах, скорее всего GitHub в комментариях их съел.

2016-11-09 09:51 UTC, gagarski commented
recheck assignment

2016-11-15 12:27 UTC, mglukhikh requested changes
В целом всё хорошо, отдельные замечания по стилю

2016-11-15 12:27 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +import lesson7.task2.fifteenGameMoves
Лишний импорт

2016-11-15 12:27 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        for (i in 0..MONTH_LIST.size) {
Пожалуйста, обойдитесь без этого цикла. Он здесь совершенно лишний.

2016-11-15 12:27 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if (list[i] != '-'.toString() && list[i] != '%'.toString()) {
Используйте `"X"` вместо `'X'.toString()`

2016-11-15 12:27 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        for (i in 0..list.size - 1) {
Здесь лучше применить цикл по элементам списка, например: `for (jump in list) { ... }`

2016-11-15 12:27 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        }
Используйте функцию `list.max()`

2016-11-15 12:27 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if (myList[i] == '+'.toString()) {
Здесь и ниже обойдитесь без `toString()`

2016-11-15 12:27 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun firstDuplicateIndex(str: String): Int {
Отформатируйте код правильно

2016-11-15 12:27 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        index +=list[i-1].toString().length
Зачем здесь `toString()`?

2016-11-21 07:45 UTC, mglukhikh commented
recheck all

2016-11-21 07:47 UTC, mglukhikh approved these changes
Принято

2016-11-21 07:47 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun firstDuplicateIndex(str: String): Int {
Исправлено

2016-11-21 07:48 UTC, mglukhikh commented
Отлично, у вас засчитаны первые пять уроков, приступайте к шестому уроку, пожалуйста

2016-11-21 07:48 UTC, closed without merging