Moshkin - Lesson6
Kotlin-Polytech/KotlinAsFirst2016 pull request #210
Opened 2016-11-08 23:49 UTC by MoshkinAlexey

2016-11-09 09:08 UTC, mglukhikh commented
recheck all

2016-11-09 09:09 UTC, mglukhikh commented
recheck all

2016-11-09 09:51 UTC, mglukhikh requested changes
В принципе всё хорошо, хотя последняя задача из `lesson6.task1` решена неверно. Немногочисленные замечания см. ниже.

2016-11-09 09:51 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        circleByThreePoints(maxDiameter.begin, maxDiameter.end, thirdPoint)
А почему именно эти три точки? Верно ли, что эта окружность всегда будет содержать все остальные точки?

2016-11-09 09:51 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            radius = localeRad
Я бы сделал `radius` неизменяемым, а для "максимального расстояния от центра до точки из множества" объявил бы другую переменную. Тем более, что радиус в исходном смысле у вас используется ниже при проверке в `return`.

2016-11-09 09:51 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +fun knightMoveNumber(start: Square, end: Square): Int {
Я бы реализовал эту функцию через `knightTrajectory` и не повторял бы здесь тот же самый код

2016-11-09 09:51 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    class Pair(val x: Int, val y: Int)
Это не очень полезный класс. `Pair` уже есть в стандартной библиотеке Котлина и объявлять его ещё раз не надо.

2016-11-09 09:51 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +            for (i in 0..movesList.size - 1) {
Лучше так: `for (move in movesList) { ... }` или (возможно при использовании библиотечной пары) даже так: `for ((dx, dy) in movesList) { ... }`

2016-11-09 09:51 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    var log = true
Неудачное название переменной

2016-11-09 09:52 UTC, mglukhikh commented
recheck all

2016-11-09 09:59 UTC, mglukhikh commented
Обратите также внимание, что, судя по последнему отчёту бота, несколько задач из различных уроков не проходят тестирование. Посмотрите на примеры бота и исправьте ошибки.

2016-11-09 10:07 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    list.add(Square(start.column, start.row))
Просто `list.add(start)`

2016-11-09 10:09 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    if (start.column - start.row != end.column - end.row) {
Условие кажется неверным. Кроме этого, всю следующую конструкцию можно записать существенно проще

2016-11-09 10:11 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        } catch (e: IndexOutOfBoundsException) {
Ловить это исключение обычно не рекомендуется. Гораздо правильнее с самого начала проверить индекс на корректность

2016-11-09 10:47 UTC, mglukhikh commented
recheck all

2016-11-15 10:55 UTC, mglukhikh reviewed
По-прежнему остаются провалившиеся тесты

2016-11-15 10:55 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +fun knightMoveNumber(start: Square, end: Square): Int {
Сделано

2016-11-15 11:05 UTC, mglukhikh commented
По поводу последней задачи в уроке 6.1: похоже на то, что ваше решение верное, а ошибку выдаёт бот. Мы поисследуем ситуацию, но, кроме этой задачи, есть ещё несколько других, которые не проходят тесты.

2016-11-15 12:00 UTC, mglukhikh commented
recheck all

2016-11-15 12:04 UTC, belyaev-mikhail commented
recheck assignment

2016-11-15 12:09 UTC, belyaev-mikhail commented
recheck all

2016-11-15 12:14 UTC, mglukhikh commented
В общем остаются только `isPalindrome` и `bishopTrajectory`

2016-11-16 18:21 UTC, mglukhikh approved these changes

2016-11-16 18:21 UTC, mglukhikh commented
Отлично, первые шесть уроков у вас приняты в полном объёме

2016-11-16 18:21 UTC, closed without merging

2016-11-16 18:27 UTC, mglukhikh commented
Поскольку вы довольно редко появляетесь на занятиях, на всякий случай предупреждаю: если вы хотите получить оценку автоматом за экзамен, вам необходимо до конца семестра хотя бы раз появиться на упражнениях и пройти тестирование (я говорил об этом на лекциях, но не уверен, что вы это слышали).