Lesson 5
Kotlin-Polytech/KotlinAsFirst2016 pull request #211
Opened 2016-11-09 03:53 UTC by SeveNChaK

2016-11-16 10:25 UTC, mglukhikh requested changes
Замечания по стилю + одна неработающая задача. А в целом, довольно хорошо

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +import jdk.nashorn.internal.runtime.regexp.RegExp
Мне кажется, этот импорт не используется

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +import jdk.nashorn.internal.runtime.regexp.RegExp
И к тому же, в котлине есть свой класс `Regex`

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Лучше вынести этот список на верхний уровень, так как он повторяется в другой функции

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
См. выше (список на верхнем уровне достаточно объявить один раз)

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (list[1].toInt() % 100 - 1 !in 0..11) return ""
Зачем вдруг `% 100` ?

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        val month = months[list[1].toInt() % 100 - 1]
Выражение в `[]` уже встречалось строчкой выше, заведите отдельную переменную

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result.sorted()[result.size - 1]
Лучше просто `result.max()`, найти максимум быстрее, чем сделать сортировку, и пишется это короче

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result.map { it.toInt() }.sorted().last()
Здесь тоже лучше использовать `max()`

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        mostPrice = priceList.map { it.toInt() }.sorted().last().toString()
`it.toDouble()` отлично работает и со строками вроде `"62"`, так что этот блок кажется ненужным

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var mostPrice = priceList.map { it.toDouble() }.sorted().last().toString()
И опять-таки лучше `max()`

2016-11-16 10:25 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var mostPrice = priceList.map { it.toDouble() }.sorted().last().toString()
В целом, я вам рекомендую вначале разбить строку на список товаров с ценами, а потом разбираться с каждым товаром и его ценой отдельно, а не пытаться вначале найти максимальную цену, а потом соответствующий ей товар.

2016-11-20 15:03 UTC, SeveNChaK commented on src/lesson5/task1/Parse.kt
> +import jdk.nashorn.internal.runtime.regexp.RegExp
Не делал импортов еще сам, они сами там появляются

2016-11-20 15:05 UTC, SeveNChaK commented on src/lesson5/task1/Parse.kt
> +        mostPrice = priceList.map { it.toInt() }.sorted().last().toString()
Он сделает из "62" -> 62.0, а мне в конечном итоге надо просто 62 получить, потому что в строке есть 62, но нет 62.0

2016-11-20 16:16 UTC, SeveNChaK commented
Почему провалился тест [Hard] lesson5.task1/flattenPhoneNumber ??

2016-11-21 08:04 UTC, mglukhikh commented
recheck all

2016-11-21 08:11 UTC, mglukhikh approved these changes
Судя по всему, тест провалился случайно, во всяком случае, я не вижу в этой функции ошибок и повторное тестирование ошибок не выявило. Спасибо за исправления, первые пять уроков у вас засчитаны

2016-11-21 08:11 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result!!.value.toString()*/
Не нужно оставлять такие закомментированные фрагменты. Система контроля версий сохраняет для вас историю изменений

2016-11-21 08:11 UTC, closed without merging

2016-11-21 08:23 UTC, SeveNChaK commented
Хорошо, спасибо.Иногда забываю удалить старые закомментированные куски🙈11:11, 21 ноября 2016 г., Mikhail Glukhikh <notifications@github.com>:@mglukhikh approved this pull request.

Судя по всему, тест провалился случайно, во всяком случае, я не вижу в этой функции ошибок и повторное тестирование ошибок не выявило. Спасибо за исправления, первые пять уроков у вас засчитаны

In src/lesson5/task1/Parse.kt:
> +fun mostExpensive(description: String): String {
+    /*val check = Regex("""\s(\d+)+((\.(\d+)(;\s|$))|(;\s|$))""").find(description)
+    if (check == null) return ""
+    val price = Regex("""(\d)+((.\d)|(?=((;\s)|($))))""").findAll(description)
+    if (price == null) return ""
+    val priceList = mutableListOf<String>()
+    for (i in price) {
+        priceList.add(i.value)
+    }
+    var mostPrice = priceList.map { it.toDouble() }.max().toString()
+    var result = Regex("""([а-яА-Яa-zA-Z])+(?=\s$mostPrice)""").find(description)
+    if (result == null) {
+        mostPrice = priceList.map { it.toInt() }.max().toString()
+        result = Regex("""([а-яА-Яa-zA-Z])+(?=\s$mostPrice)""").find(description)
+    }
+    return result!!.value.toString()*/

Не нужно оставлять такие закомментированные фрагменты. Система контроля версий сохраняет для вас историю изменений

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты