Lesson6 Hiraev Malik
Kotlin-Polytech/KotlinAsFirst2016 pull request #214
Opened 2016-11-12 23:36 UTC by MalikPiter

Выполнил несколько задач, остальные сделаю позже.

2016-11-15 12:44 UTC, maximpetrov requested changes

2016-11-15 12:44 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +        val result = distanceCenter - radiusSum
Можно сначала рассчитать результат, а потом проверять его на отрицательность.

2016-11-15 12:44 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    var rad = 0.0
Можно здесь не инициализировать переменную, тогда можно будет сделать её `val`.

2016-11-15 12:44 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    if (s.begin.x == s.end.x) {
Рассмотрение этого отдельного случая не обязательно, так как арктангенс бесконечности всё равно будет равен `PI / 2`.

2016-11-15 19:59 UTC, MalikPiter commented on src/lesson6/task1/Geometry.kt
> +        val result = distanceCenter - radiusSum
А разве не лучше все проверки стараться выносить вперед, чтобы программа не выполняла лишних операций, если условие не пройдено?

2016-11-15 20:37 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +        val result = distanceCenter - radiusSum
В первую очередь проверки выносятся вперёд, чтобы программа не выполняла действий, которые приведут к ошибкам (например, обратится к элементу за границей массива). Ну и операции, которые не нужны в случае непрохождения проверки, тоже, конечно, стоит выполнять после проверок.
Но в данном случае, эта операция не будет лишней, а всего лишь частью проверки, тем более, что сравнение двух чисел, как правило, выполняется путём их вычитания и сравнения результата с нулём.

2016-11-16 07:52 UTC, maximpetrov requested changes

2016-11-16 07:52 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    for (pointOne in points) {
Здесь стоит сделать также, как Вы сделали в `findNearestCirclePair`, т.е. использовать циклы по индексам так, чтобы не сравнивать два раза одну и ту же пару точек.

2016-11-16 16:54 UTC, MalikPiter commented
Не понимаю, почему я не могу вызвать `diameter()`, передав в качестве аргумента `points`

2016-11-17 00:41 UTC, maximpetrov requested changes

2016-11-17 00:41 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +import kotlin.concurrent.thread
Этот импорт явно лишний

2016-11-17 00:41 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    if (distanceMax >= distanceSum - distanceMax) throw IllegalArgumentException()
Что Вы проверяете здесь?

2016-11-17 00:46 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    var result = Segment(points[0], points[1])
Функция `diameter` принимает `vararg`, т.е. некоторое количество элементов указанного типа (в данном случае `Point`). При этом внутри функции `vararg` представляется как `Array<Point>`, поэтому нельзя просто передать его как аргумент, для этого нужно использовать оператор раскрытия: `diameter(*points)`

2016-11-17 18:54 UTC, MalikPiter commented on src/lesson6/task1/Geometry.kt
> +    if (distanceMax >= distanceSum - distanceMax) throw IllegalArgumentException()
Существует ли такой треугольник

2016-11-17 20:35 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    if (distanceMax >= distanceSum - distanceMax) throw IllegalArgumentException()
Когда может треугольник, построенный по трём точкам, не существовать?

2016-11-17 20:37 UTC, MalikPiter commented on src/lesson6/task1/Geometry.kt
> +    if (distanceMax >= distanceSum - distanceMax) throw IllegalArgumentException()
Когда сумма двух меньших сторон меньше или равна большей стороне

2016-11-17 20:48 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    if (distanceMax >= distanceSum - distanceMax) throw IllegalArgumentException()
Возможно ли это, если длины сторон - это не абстрактные числа, а расстояния между тремя точками?

2016-11-18 05:23 UTC, MalikPiter commented on src/lesson6/task1/Geometry.kt
> +    if (distanceMax >= distanceSum - distanceMax) throw IllegalArgumentException()
Значит нет смысла в этой проверке?

2016-11-18 09:39 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    if (distanceMax >= distanceSum - distanceMax) throw IllegalArgumentException()
Именно в этой нет. Единственное, что стоит проверить, что точки не лежат на одной прямой.

2016-11-20 13:56 UTC, maximpetrov requested changes

2016-11-20 13:56 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    if ((a.x == b.x && b.x == c.x) || (a.y == b.y && b.y == c.y)) throw IllegalArgumentException()
Эта проверка сработает, только если точки лежат на одной горизонтали или вертикали, но не сработает, если они лежат на любой другой прямой.

2016-11-20 14:37 UTC, maximpetrov commented
Последняя функция не работает, потому что алгоритм, который Вы реализовали некорректен: Две наиболее удалённые точки могут быть диаметром искомой окружности, если все остальные точки попадут в неё. Иначе нельзя сказать наверняка, что они будут в числе тех трёх точек, по которым будет построена окружность. И уж точно нельзя строить окружность по первой же точке, более удалённой от предполагаемого центра.

2016-11-20 15:11 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +            if ((points[i].y - points[0].y) * cos(angle) != (points[i].x - points[0].x) * sin(angle)) return false
Не стоит просто так сравнивать `double`, лучше сравнивать разность с каким-нибудь порогом

2016-11-23 12:26 UTC, maximpetrov commented
recheck all

2016-11-23 12:28 UTC, closed without merging