5,6 lesson
Kotlin-Polytech/KotlinAsFirst2016 pull request #215
Opened 2016-11-13 18:42 UTC by mezd10

2016-11-16 13:44 UTC, ice-phoenix requested changes

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val a = hours * 3600 + minutes * 60 + seconds
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val a = sagenes * 48
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return e
Можно сразу `return a + b + c`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val s = sqrt(sqr(x1 - x2) + sqr(y1 - y2))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val a = number % 1000
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val a = (hoursArrive - hoursDepart) * 60
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return c
Этот код можно значительно упростить, если вынести повторно используемые выражения в отдельные переменные

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (s_sred <= s1) return s_sred / v1
Данное выражение лучше оформить как `when`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val s_sred = (s1 + s2 + s3) / 2
В Котлине принят `camelCase` для именования переменных

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX1) || (kingY == rookY1)) && ((kingX !== rookX2) && (kingY !== rookY2))) return 1
Повторно используемые выражения, отвечающие за какой-либо законченный факт (атака короля ладьей, например), следует вынести в отдельные переменные, а потом сделать `when` по их различным комбинациям

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    } else return 0
См. замечание выше

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((a == b) && (b == c) && (c == a)) return 0
Лучше сперва найти максимальную сторону, а потом все считать относительно нее

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +import lesson4.task1.sqRoots
Зачем?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((numb1 + numb2) == (numb3 + numb4)) return true
Выражение `if (cond) return true else return false` можно заменить на `return cond`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (x1 == x2) return true
Эту функцию можно записать значительно проще, если вспомнить, как комбинируются логические условия

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return ((sqr(x1 - x2) + sqr(y1 - y2) <= sqr(r2)) && (Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) + r1 <= r2))
Зачем проверять условие `a <= b && a^2 <= b^2`???

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n > 2) {
Зачем эта проверка?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return k / evc
Подсчет `gcd` следует вынести в отдельную функцию

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Можно ли указать более точную верхнюю границу на возможные делители числа, чем `n`?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in (n - 1) downTo 2) {
См. про верхнюю границу выше

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return a
Почему эту функцию не использовали в функции `lcm`???

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        quadr = k * k
Эту функцию можно решить без цикла, если воспользоваться правильными функциями для округления возможных границ для `k`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n % 2 == 1) summ += Math.pow(fir, i.toDouble()) / factorial(i)
Повторно используемые выражения следует вынести в отдельные переменные

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n % 2 == 1) summ += Math.pow(fir, i.toDouble()) / factorial(i)
См. выше

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (result == n)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (number % 10 != one) index = false
Почему сразу не вернуть результат?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun strok(n: Int): Int = n.toString().length
Зачем эта функция?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var result = 0
Почему эта переменная объявлена здесь?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    (n..number - 1).forEach { k -> result /= 10 }
Можно ли сделать то, что вы делаете здесь, без цикла?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (result % 10)
См. замечания выше

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val sp = list.sum()
Лучше без вспомогательных переменных

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Зачем эта проверка?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if ((a.isNotEmpty()) && (b.isNotEmpty())) {
Зачем эта проверка?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (p.isNotEmpty()) {
Зачем эта проверка?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list = p
Зачем вы завели эту переменную?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Зачем эта проверка?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return list.sorted()
Зачем сортировать результат, если вы добавляли делители от минимального к максимальному?

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
Для таких операций лучше использовать список строк или `StringBuilder`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun mpow(a: Int, b: Int): Int {
Эта функция должна называться `pow`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return digits.reversed().mapIndexed { i, d -> d * mpow(base, i) }.sum()
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun pow(a: Int, b: Int): Int {
Несколькими строчками выше вы реализовали точно такую же функцию. Зачем вы сделали эту???

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var i: Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return str.reversed().sumBy { char.indexOf(it) * pow(base, i++) }
Изменять внешнюю переменную из `sumBy` --- **очень плохой** стиль

2016-11-16 13:44 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        for (j in parts[i]) {
Вместо цикла можно `contains / in`

2016-11-16 13:44 UTC, ice-phoenix commented
recheck all

2016-11-16 13:45 UTC, ice-phoenix commented
recheck all

2016-11-26 18:52 UTC, ice-phoenix commented
Учитывая, что вы не исправили достаточно большое количество замечаний из более ранних уроков, новые задачи из урока 5 и урок 6 не будут вам зачтены.

2016-11-28 09:39 UTC, ice-phoenix commented
Очень много замечаний все еще не исправлено.

2016-12-04 21:28 UTC, ice-phoenix requested changes
Все не очень хорошо, советую на одном из занятий поговорить с преподавателем на тему того, как улучшить ваши навыки написания кода и сам этот код.

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val translate  = sagenes * 48
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val delete1 = number % 1000
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val tominutes = (hoursArrive - hoursDepart) * 60
Все еще не очень имена переменных

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val const = 0.01 * percent
И все еще плохо с именами переменных в датском королевстве

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return second + (second * const)
Все это можно записать намного проще

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    ((age % 10 in 2..4) && (age % 100 !in 12..14)) -> "$age года"
Лишние скобки вокруг законченных выражений

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val sSred = (s1 + s2 + s3) / 2
Называть переменные транслитом --- очень плохая идея

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return firstTime
Зачем вам эта переменная? Почему нельзя сразу вернуть то, что надо?

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((sSred > s1) && (sSred <= (s1 + s2))) -> t1 + ((sSred - s1) / v2)
Первую часть выражения можно не проверять

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val attack = when {
Поговорите с преподавателем на занятиях, как следует разносить условия по переменным

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val attack = when {
А нет, в функции ниже вы все правильно поняли. Почему здесь вы считаете все разом, а не каждую ладью отдельно???

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return attack
Можно сразу вернуть инициализатор этой переменной

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            ((c <= a) && (a <= d) && (d <= b)) -> d - a
Этот набор условий можно упростить

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return ((numb1 + numb2) == (numb3 + numb4))
Много лишних скобок

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val numb4 = (((number % 1000)) % 100) % 10
Подумайте, как все это посчитать проще

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return result
Можно сразу вернуть инициализатор этой переменной

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) + r1 <= r2
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return ((mini1 <= r) && (mini2 <= s)) || ((mini1 <= s) && (mini2 <= r))
И здесь очень много лишних скобок

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +import com.sun.org.apache.xerces.internal.impl.xpath.regex.Match
Зачем вам этот импорт?

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun nod(m: Int, n: Int): Int {
`gcd`

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var fact = factorial(i)
Зачем `var`?

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        n++
Зачем вам и `n`, и `i`?

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return summ
См. замечания выше

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        sec = str.toInt()
Перепишите вашу функцию так, чтобы вам не приходилось делать этого ужаса

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return digits.reversed().mapIndexed { i, d -> d * pow(base, i) }.sum()
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (str.matches(Regex("""[0-9]+\s[а-яА-Я]+\s[0-9]+"""))) {
Зачем принимать на вход заглавные буквы, если вы дальше с ними не работаете?

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (month != 0) return String.format("%d %s %d", day, month, year)
Вместо этой проверки здесь можно сделать `return ""` выше

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if ((parts[i] != "") && (parts[i].toInt() > max)) {
Вместо первой проверки лучше отфильтровать все пустые строки в самом начале

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if ((j == '+') && (maxHigh < parts[i - 1].toInt())) {
Проверку того, что в `parts[i]` есть плюс, можно сделать намного проще

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        throw IllegalArgumentException(expression)
Зачем?

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                result += (parts[j].length + 1)
Почему этот результат нельзя считать сразу, пока вы идете по словам?

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return -1
Этого исключения происходить не должно

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                maxindex = parts.indexOf(parts[i])
Может быть, мы можем найти индекс попроще???

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return ""
Этого исключения быть не должно

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +import lesson2.task2.pointInsideCircle
Зачем?

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            else -> ""
Это можно вычислить намного проще

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            else -> throw IllegalArgumentException()
Проще надо быть

2016-12-04 21:28 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        throw IllegalArgumentException()
Зачем?

2016-12-04 21:30 UTC, ice-phoenix commented
recheck all

2016-12-07 14:31 UTC, ice-phoenix commented
recheck all

2016-12-07 15:17 UTC, ice-phoenix requested changes

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val travelHourTominutes = (hoursArrive - hoursDepart) * 60
`camelCase`

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = ((initial * (1 + 0.01 * percent)) * (1 + 0.01 * percent)) * (1 + 0.01 * percent)
Это выражение можно упростить еще больше

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +
А зачем столько пустых строк?

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((average > (s1 + s2))) -> t1 + t2 + ((average - s1 - s2) / v3)
Много лишних скобок

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        else -> 0.0
Когда будет выполнен данный случай?

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    }
Все это можно записать намного проще, если вспомнить, как можно комбинировать логические переменные

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +                  x2: Double, y2: Double, r2: Double): Boolean = Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) + r1 <= r2
Форматирование кода

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (b <= a && b <= c) {
`if ... else if ... else if ...`

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    else {
Здесь можно обойтись без `else`, так как вы выходите из функции в ветке `then`

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        n++
Зачем вам переменная `i` и переменная `n` одновременно?

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var pow = Math.pow(fir, i.toDouble())
Почему `var`?

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (number % 10 != one) index = false
Все еще актуально

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (str[str.length - 1 - (i - n)]).toInt() - '0'.toInt()
Зачем два вызова `toInt()`?

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        sec = str.toInt()
Все еще актуально

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (str[str.length - 1 - (i - n)]).toInt() - '0'.toInt()
См. замечание выше

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    } else return 0.0
Форматирование кода и расстановка скобок должны быть одинаковыми

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val sred = mean(list)
Именовать переменные транслитом --- не очень хорошо

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if('+' in parts[i]) {
Форматирование кода

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            else throw  IllegalArgumentException(expression)
Лишний пробел

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: StringIndexOutOfBoundsException) {
Этого исключения быть не должно

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IndexOutOfBoundsException) {
Этого исключения быть не должно

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        while ((parts[i] != parts[i + 1]) && (i < parts.size)){
Лишние скобки

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IndexOutOfBoundsException) {
Этого исключения быть не должно

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        if(!inside()) return ""
Форматирование кода

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val columnNotation = listOf<Char>('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
Вместо списков `Char` можно просто завести соответствующие строки

2016-12-07 15:17 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val row = listOf<Char>('1', '2', '3', '4', '5', '6', '7', '8')
Почему не `rowNotation`?

2016-12-07 15:55 UTC, mezd10 commented on src/lesson4/task1/List.kt
> +    } else return 0.0
что здесь не так?

2016-12-07 16:04 UTC, mezd10 commented on src/lesson6/task2/Chess.kt
> +    val columnNotation = listOf<Char>('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
Почему не подходит список?

2016-12-09 08:55 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val columnNotation = listOf<Char>('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
Потому что его объявление занимает намного больше места, его сложнее модифицировать при необходимости поменять код, и он ничем не лучше строки (у которой нет предыдущих недостатков) в данном конкретном случае

2016-12-09 08:55 UTC, ice-phoenix commented
recheck all

2016-12-09 10:40 UTC, ice-phoenix requested changes

2016-12-09 10:40 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        initial * (1 + 0.01 * percent) * sqr(1 + 0.01 * percent)
Вы не поверите, но можно еще проще

2016-12-09 10:40 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return mini1 <= r && mini2 <= s || mini1 <= s && mini2 <= r
Это условие можно записать проще

2016-12-09 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return square % 10
Форматирование кода

2016-12-09 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        while(n<k) {
Зачем это делать внутри цикла, если данный `while` выполняется только когда мы хотим выйти из цикла?

2016-12-09 10:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return nfib % 10
См. замечания выше

2016-12-09 10:40 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        val month = when(parts[1]) {
Форматирование кода

2016-12-09 10:40 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return nameOfMaxCost ?: ""
Зачем здесь элвис-оператор?

2016-12-12 09:27 UTC, ice-phoenix requested changes

2016-12-12 09:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when{
Форматирование кода

2016-12-12 09:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val attackKing = (Math.abs(kingX - bishopX) == (Math.abs(kingY - bishopY)))
Лишние скобки вокруг законченных выражений

2016-12-12 09:29 UTC, ice-phoenix commented
В общем и целом, все неплохо. Закрываю PR для облегчения жизни GitHub. Когда будете решать следующие задачи, не забудьте создать новый PR.

2016-12-12 09:29 UTC, closed without merging