KotlinAsFirst2016/oxovu
Kotlin-Polytech/KotlinAsFirst2016 pull request #216
Opened 2016-11-16 10:30 UTC by oxovu

2016-11-21 14:20 UTC, gagarski requested changes

2016-11-21 14:20 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    return if (a.x != b.x) Line(Point((a.x + b.x) / 2, (a.y + b.y) / 2), Math.PI / 2 + Math.atan(Math.abs((a.y - b.y) / (a.x - b.x))))
Точная проверка `Double` на равенство - плохой стиль. Более того, она не нужна. `atan` нормально работает с бесконечными значениями.

2016-11-25 20:10 UTC, mglukhikh commented
recheck all

2016-11-27 13:49 UTC, gagarski requested changes

2016-11-27 13:49 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +            (Math.cos(angle) == Math.cos(Math.PI / 2)) -> point.x
Сравнение Double на точное равенство.

2016-11-27 13:49 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    return if (Math.abs(a.x - b.x) > Math.pow(10.0, -10.0)) Line(Point((a.x + b.x) / 2, (a.y + b.y) / 2), Math.PI / 2 + Math.atan(Math.abs((a.y - b.y) / (a.x - b.x))))
 Вместо `Math.pow(10.0, -10.0)` лучше просто `1e-10`

2016-12-05 12:14 UTC, gagarski requested changes

2016-12-05 12:14 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +            (Math.abs(Math.cos(angle)) == Math.cos(Math.PI / 2)) ->
Сравнение Double на точное равенство.

2016-12-17 21:03 UTC, mglukhikh commented
recheck all

2016-12-18 12:52 UTC, gagarski requested changes

2016-12-18 12:52 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +        if ((notation.length != 2) || (notation[0] !in 'a'..'h') || (notation[1] !in '1'..'8')) throw IllegalArgumentException()
Форматирование

2016-12-18 12:52 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        val sb = StringBuilder()
Ваша реализация `toString` работает неправильно:
```kotlin
    val x = MatrixImpl(5, 5, 10)
    println(x)
```
печатает
```
[[[1,0,1,0,1,0,1,0,1,0],[1,0,1,0,1,0,1,0,1,0],[1,0,1,0,1,0,1,0,1,0],[1,0,1,0,1,0,1,0,1,0],[1,0,1,0,1,0,1,0,1,0]]
```

- Определитесь, будете ли вы использовать списки или `StringBuilder` для построения строки
- В последней строке функции происходит какой-то кромешный ад.

-

2016-12-18 12:52 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +                matrix[i, j] = this[i, j] * (-1)
```matrix[i, j] = -this[i, j]```

2016-12-18 13:00 UTC, gagarski commented
По проваленному тесту в  `lesson6.task2/bishopTrajectory`

Посмотрите результат вашей функции для примера, сгенерированного ботом и проверьте (например, на бумаге), правильное ли он выдаёт решение.

По остальным проваленным тестам вроде всё должно быть понятно из вывода бота.

2016-12-19 13:20 UTC, gagarski commented
recheck all

2016-12-19 13:34 UTC, gagarski requested changes

2016-12-19 13:34 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        val sb = StringBuilder()
Пожалуйста перепишите `toString` так, чтобы он возвращал результат, из которого человек может понять, что содержится в матрице, а не непонятное месиво из цифр. Рекомендую самостоятельно проверить ваше решение перед отправкой.

2017-07-26 18:23 UTC, closed without merging