Lesson 5. Task 1
Kotlin-Polytech/KotlinAsFirst2016 pull request #220
Opened 2016-11-19 21:53 UTC by Stupidman00

2016-11-20 13:44 UTC, Stupidman00 commented
bestLongJump() - Не знаю в чем проблема. Я попробовал прогнать test case бота через assertEquals() и тесты проходят.
bestHighJump() - Ошибка переполнения стека может быть вызвана слишком большой последовательностью результатов поиска при помощи регулярного выражения, или нет?
computeDeviceCells() - Изначально пытался реализовать алгоритм, исходящий из того, что тело одного цикла не может пересекаться с телом другого. Похоже ошибка именно в этом. У меня есть мысли как это исправить.

2016-11-21 14:40 UTC, gagarski commented
> bestLongJump() - Не знаю в чем проблема. Я попробовал прогнать test case бота через assertEquals() и тесты проходят.

Скорее всего дело в последовательности из нескольких пробелов подряд, которую теряет GitHub в комментах.

>computeDeviceCells() - Изначально пытался реализовать алгоритм, исходящий из того, что тело одного цикла не может пересекаться с телом другого. Похоже ошибка именно в этом. У меня есть мысли как это исправить.

Разные циклы могут пересекаться, да. 

> bestHighJump()

Гляну попозже.

2016-11-26 03:38 UTC, Stupidman00 commented
lesson6\task1\diameter() - У меня test case бота проходит. А бот похоже нашел минимальный отрезок, в его test case. В чем проблема?

2016-11-27 15:41 UTC, gagarski commented
recheck all

2016-11-30 09:10 UTC, gagarski commented
recheck all

2016-11-30 09:11 UTC, gagarski commented
recheck all

2016-11-30 09:12 UTC, gagarski commented
recheck all

2016-11-30 10:42 UTC, Stupidman00 commented
recheck all

2016-12-05 12:33 UTC, gagarski commented
> [Example] lesson7.task2/plus
org.opentest4j.AssertionFailedError : expected: lesson7.task1.MatrixImpl@7b3feb2<[[[3]]]> but was: lesson7.task1.MatrixImpl@2e4ecdf<[[[3]]]>

У вас ошибка в реализации `equals`

2016-12-05 12:38 UTC, gagarski requested changes

2016-12-05 12:38 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        var result = height
Хорошая функция `hashCode` должна учитывать все значимые поля объекта (вспомните лекции/почитайте интернет чтобы понять зачем). Вы никак не учитываете содержимое матрицы. 

Попробуйте написать `hashCode`, учитывающий содержимое матрицы либо автоматически сгенерировать его с помощью IDE и понять.

2016-12-09 11:17 UTC, Stupidman00 commented
recheck all

2016-12-13 16:41 UTC, gagarski commented
recheck all

2016-12-13 16:46 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        val diameter: Segment = diameterByArray(points)
Varargи можно передавать далее в функцию с varargами:
```kotlin
fun b(vararg x: Int) {

}

fun a(vararg x: Int) {
    b(*x)
}
```

2016-12-18 11:10 UTC, gagarski commented
recheck all

2016-12-18 12:14 UTC, gagarski commented
recheck all

2016-12-18 12:24 UTC, gagarski commented
> lesson4.task1/polynom

Тут у вас багов нет.

>  lesson6.task2/bishopTrajectory

А тут у вас баг. См. результаты тестов, которые вам предоставлены.

> lesson6.task1/minContainingCircle

Изучите предоставленные ботом контрпримеры. Некоторые точки не содержатся в возвращённой вами окружности.

2016-12-18 12:26 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (p.isEmpty()) return result
Нужно ли рассматривать пустой список в данном случае как отдельную ветку?

2016-12-18 12:26 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty() || list.size == 1) return list
Нужно ли рассматривать пустой список (и список из одного элемента) в данном случае как отдельную ветку?

2016-12-18 12:26 UTC, gagarski approved these changes

2016-12-19 15:07 UTC, gagarski commented
recheck all

2016-12-19 16:02 UTC, gagarski commented
Предлагаю вам решить задания из уроков 7.2 и 8 до начала вашего занятия в среду. Помимо количества уроков, все показатели позволяют вам претендовать на оценку "отлично", а без этих двух уроков только "удовлетворительно".

2016-12-21 09:26 UTC, Stupidman00 commented
recheck all

2017-07-26 18:23 UTC, closed without merging