lesson 1,2,3,4
Kotlin-Polytech/KotlinAsFirst2016 pull request #221
Opened 2016-11-20 15:06 UTC by el-orabi

2016-11-21 08:47 UTC, mglukhikh requested changes
Много замечаний по стилю + одна задача решена неверно. В целом всё неплохо. Хотелось бы узнать, почему вы начали решать задачи только 20 ноября.

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = (hours*3600 + minutes*60 + seconds)
1) Внешние скобки здесь не нужны
2) Рядом со знаками операций следует ставить пробелы: `hours * 3600 + minutes * 60 + seconds`. Используйте Ctrl+Alt+L для автоматического форматирования кода в IDEA

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else return t1+t2+(s0-s1-s2)/v3
См. замечание выше про пробелы

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else if ((kingX ==rookX2||kingY==rookY2)&&(kingX!=rookX1&&kingY!=rookY1)) return 2
В этой функции вы несколько раз проверяете одни и те же условия. Следует добавить промежуточные переменные "угроза от 1-й ладьи" и "угроза от 2-й ладьи" и использовать их для определения результата

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else return 0
См. замечания к предыдущей функции

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else return 0
Расставьте правильно пробелы или используйте Ctrl+Alt+L

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else return -1
Расставьте правильно пробелы или используйте Ctrl+Alt+L

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean =((number/1000+number/100%10)==(number%10+number/10%10))
Расставьте правильно пробелы или используйте Ctrl+Alt+L. Внешние скобки не нужны

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = ((x1==x2)||(y1==y2)||(Math.abs(x1-x2)==Math.abs(y1-y2)))
Расставьте правильно пробелы или используйте Ctrl+Alt+L. Внешние скобки не нужны

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +                 x2: Double, y2: Double, r2: Double): Boolean = Math.sqrt(sqr(x1-x2)+sqr(y1-y2))+r1<=r2
Расставьте правильно пробелы или используйте Ctrl+Alt+L.

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    val b1 = (a <= r && b <= s) || (b <= r && a <= s) || (a <= r && c <= s) || (a <= s && c <= r) || (b <= r && c <= s) || (c <= r && b <= s)
Слишком длинная строка, пожалуйста, разбейте её на несколько

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +import com.sun.xml.internal.ws.runtime.config.TubelineFeatureReader
Лишний импорт

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +import kotlin.concurrent.timer
Лишний импорт

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    x--
Зачем вы вначале увеличиваете `x` на единицу, а затем уменьшаете? Можно ли обойтись без этого? Если можно, то как?

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    x++
См. вопрос к предыдущей функции

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return x
Текст этой функции почти повторяет текст `lcm`. Найдите в них общую часть (расчёт наибольшего общего делителя) и сделайте из неё отдельную функцию, а после этого используйте её в `lcm` и `isCoPrime`

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Можно ли решить эту задачу, не перебирая все возможные `k` начиная с 0?

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        nn = n / pow(10.0, (count * 1.0 - 1)).toInt() % 10 * pow(10.0, t * 1.0).toInt() + nn
Для возведения целого числа в целую степень лучше написать свою `fun pow(x: Int, y: Int): Int = TODO()`. В противном случае у вас могут возникнуть неточности при округлении

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Объясните, пожалуйста, в комментарии, что происходит в этих двух циклах `while`

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    m = m / pow(10.0, l * 1.0).toInt() % 10
Возведение целого числа в целую степень

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return mutableListOf()
В этой функции не следует создавать новых списков -- она должна изменить (или оставить без изменений) имеющийся список `list`

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        val x=list.sum() / list.size
Расставьте правильно пробелы или используйте Ctrl+Alt+L

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        p1 = (p1 + element * pow(x, x1))
Лучше использовать `+=`

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    return p1 * 1.0
Зачем умножать на 1.0?

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        list[i]=t
Расставьте правильно пробелы или используйте Ctrl+Alt+L.

2016-11-21 08:47 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        t++
Попробуйте обойтись без последовательного уменьшения, а затем увеличения `t`

2016-11-21 08:47 UTC, mglukhikh commented
Перед тем, как решать какие-либо новые задачи, следует исправить имеющиеся замечания

2016-11-24 05:15 UTC, el-orabi commented
Я не начинал в 20 я начинал раньше только у меня был проблема с компютором
сейчас я получил новый и я начинал отправить задачи,
Сегодня я буду отправить новый просто у меня вопрос где я могу вас найти,

2016-11-21 9:47 GMT+01:00 Mikhail Glukhikh <notifications@github.com>:

> Перед тем, как решать какие-либо новые задачи, следует исправить имеющиеся
> замечания
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/221#issuecomment-261877764>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVHzbNp3VjpFOVI-L7t9HQbPVv4iWBHCks5rAVqggaJpZM4K3j1i>
> .
>

2016-11-24 08:55 UTC, mglukhikh commented
Вы вполне могли работать в аудитории на упражнениях. Компьютеров там достаточно. Меня найти лично можно только на лекции или в среду с 12 до 14 в 9-305. Если у вас есть вопросы, вы можете задавать их здесь, в письме на e-mail или обратиться к моим коллегам в 9-301 (спросите там, кто может ответить на вопрос по обучающему Котлину проекту).

2016-12-16 07:55 UTC, mglukhikh commented
recheck all

2016-12-19 08:42 UTC, mglukhikh commented
Все ваши решения являются точными копиями решений другого студента. Ваше дальнейшее обучение мне лично кажется довольно бессмысленным делом.

2016-12-19 08:42 UTC, closed without merging