Lesson 6
Kotlin-Polytech/KotlinAsFirst2016 pull request #222
Opened 2016-11-21 12:27 UTC by SeveNChaK

2016-11-23 17:04 UTC, SeveNChaK commented
Commit называется не правильно(

2016-11-23 18:32 UTC, SeveNChaK commented on src/lesson6/task1/Geometry.kt
>          val resultY2 = ((resultX - point.x) * sin(angle) / cos(angle)) + point.y
По идеи же если я подставлю одну известную координату пересечения в любой из уравнений прямой, то я должен получить одинаковую вторую координату пересечения, но почему здесь не так??

2016-11-30 09:32 UTC, mglukhikh commented
recheck all

2016-11-30 09:47 UTC, mglukhikh commented
recheck all

2016-11-30 09:47 UTC, mglukhikh commented
recheck all

2016-11-30 10:13 UTC, mglukhikh requested changes
Довольно много замечаний по коду + неверно работает построение окружности по трём точкам.

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return result!!.value.toString()*/
Уберите закомментированный код, пожалуйста

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            }
Нельзя ли три последние ветки как-нибудь объединить?

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +import lesson3.task1.cos
Нужно ли это?

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        }
Либо 
```
if (...) return ...
else return ...
```

либо

```
if (...) {
    return ...
}
else {
    return ...
}
```

Смешивать два эти стиля не нужно, поскольку просто некрасиво выглядит

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +                ((sin(angle) * cos(other.angle) - cos(angle) * sin(other.angle)) / cos(angle) / cos(other.angle))
Очень длинная строка. Отформатируйте аккуратнее. Может быть, здесь следует использовать промежуточные переменные

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        else resultY=resultY1
Форматирование кода

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val resultY2 = ((resultX - point.x) * sin(angle) / cos(angle)) + point.y
`sin / cos = tan`

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return Line(a, angle)
Используйте `lineBySegment`

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    if (angle < 0) angle = PI + angle
Подобные операции с углом делаются несколько раз. Создайте для этой цели функцию

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    }
Оба этих `when` можно записать гораздо короче

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        val result = columnStr[column] + row.toString()
Преобразование `toString()` здесь лишнее

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        val columnStr = mapOf<Int, String>(1 to "a", 2 to "b", 3 to "c", 4 to "d", 5 to "e", 6 to "f", 7 to "g", 8 to "h")
Лучше было использовать просто строку `"abcdefgh"`

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    val e = IllegalArgumentException("Description")
Описания, строго говоря, должны быть разными в разных местах

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    val row = notation[1].toInt() - 48
Уберите магическую константу 48

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            height == other.height && width == other.width && listMatrix.equals(other.listMatrix)
Лучше `==` вместо `equals`

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +        for (j in height - turn - 1 downTo turn) if (matrix[j, turn - 1] == 0) matrix[j, turn - 1] = number++
Такие однострочные конструкции очень плохо читаются. Добавьте фигурные скобки ко всем циклам. Подумайте также, нельзя ли избавиться от проверки дополнительных условий.

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +        for (j in height - turn - 1 downTo turn) if (matrix[j, turn - 1] == 0) matrix[j, turn - 1] = number
См. замечания к предыдущей функции

2016-11-30 10:13 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return Circle(center, radius)
Эта функция не проходит тесты бота. Необходимо взять пример, предоставленный ботом, добавить его в список тестов и аккуратно проверить её в режиме отладки. Скорее всего, дают сбои `bisectorByPoints` или `crossPoint`.

2016-11-30 13:20 UTC, SeveNChaK commented
Михаил Игоревич, зачем ворошить прошло?:) У меня же уже были проверены 4-й и 5-й уроки?И извините за закомментированный код, вы мне уже говорили, я где-то убрал, а тут забыл🙁13:13, 30 ноября 2016 г., Mikhail Glukhikh <notifications@github.com>:@mglukhikh requested changes on this pull request.

Довольно много замечаний по коду + неверно работает построение окружности по трём точкам.

In src/lesson5/task1/Parse.kt:
> +fun mostExpensive(description: String): String {
+    /*val check = Regex("""\s(\d+)+((\.(\d+)(;\s|$))|(;\s|$))""").find(description)
+    if (check == null) return ""
+    val price = Regex("""(\d)+((.\d)|(?=((;\s)|($))))""").findAll(description)
+    if (price == null) return ""
+    val priceList = mutableListOf<String>()
+    for (i in price) {
+        priceList.add(i.value)
+    }
+    var mostPrice = priceList.map { it.toDouble() }.max().toString()
+    var result = Regex("""([а-яА-Яa-zA-Z])+(?=\s$mostPrice)""").find(description)
+    if (result == null) {
+        mostPrice = priceList.map { it.toInt() }.max().toString()
+        result = Regex("""([а-яА-Яa-zA-Z])+(?=\s$mostPrice)""").find(description)
+    }
+    return result!!.value.toString()*/

Уберите закомментированный код, пожалуйста



In src/lesson4/task1/List.kt:
> +            (nPart1 % 10 == 1) && (nPart1 % 100 != 11) -> {
+                resultPart1.removeAt(resultPart1.size - 1)
+                resultPart1.add("одна тысяча")
+            }
+            (nPart1 % 10 == 2) && (nPart1 % 100 != 12) -> {
+                resultPart1.removeAt(resultPart1.size - 1)
+                resultPart1.add("две тысячи")
+            }
+            (nPart1 % 10 == 3) && (nPart1 % 100 != 13) -> {
+                resultPart1.removeAt(resultPart1.size - 1)
+                resultPart1.add("три тысячи")
+            }
+            (nPart1 % 10 == 4) && (nPart1 % 100 != 14) -> {
+                resultPart1.removeAt(resultPart1.size - 1)
+                resultPart1.add("четыре тысячи")
+            }

Нельзя ли три последние ветки как-нибудь объединить?



In src/lesson6/task1/Geometry.kt:
>  package lesson6.task1
 
 import lesson1.task1.sqr
+import lesson3.task1.cos

Нужно ли это?



In src/lesson6/task1/Geometry.kt:
> @@ -55,14 +58,19 @@ data class Circle(val center: Point, val radius: Double) {
      * расстояние между их центрами минус сумма их радиусов.
      * Расстояние между пересекающимися окружностями считать равным 0.0.
      */
-    fun distance(other: Circle): Double = TODO()
+    fun distance(other: Circle): Double {
+        if (center.distance(other.center) <= radius + other.radius) return 0.0
+        else {
+            return center.distance(other.center) - radius - other.radius
+        }

Либо
if (...) return ...
else return ...

либо
if (...) {
    return ...
}
else {
    return ...
}

Смешивать два эти стиля не нужно, поскольку просто некрасиво выглядит



In src/lesson6/task1/Geometry.kt:
> @@ -97,29 +105,66 @@ data class Line(val point: Point, val angle: Double) {
      * Найти точку пересечения с другой линией.
      * Для этого необходимо составить и решить систему из двух уравнений (каждое для своей прямой)
      */
-    fun crossPoint(other: Line): Point = TODO()
+    fun crossPoint(other: Line): Point {
+        val resultX = (other.point.y - point.y + ((point.x * sin(angle) * cos(other.angle) - other.point.x * sin(other.angle) * cos(angle)) / cos(angle) / cos(other.angle))) /
+                ((sin(angle) * cos(other.angle) - cos(angle) * sin(other.angle)) / cos(angle) / cos(other.angle))

Очень длинная строка. Отформатируйте аккуратнее. Может быть, здесь следует использовать промежуточные переменные



In src/lesson6/task1/Geometry.kt:
> @@ -97,29 +105,66 @@ data class Line(val point: Point, val angle: Double) {
      * Найти точку пересечения с другой линией.
      * Для этого необходимо составить и решить систему из двух уравнений (каждое для своей прямой)
      */
-    fun crossPoint(other: Line): Point = TODO()
+    fun crossPoint(other: Line): Point {
+        val resultX = (other.point.y - point.y + ((point.x * sin(angle) * cos(other.angle) - other.point.x * sin(other.angle) * cos(angle)) / cos(angle) / cos(other.angle))) /
+                ((sin(angle) * cos(other.angle) - cos(angle) * sin(other.angle)) / cos(angle) / cos(other.angle))
+        val resultY1 = ((resultX - other.point.x) * sin(other.angle) / cos(other.angle)) + other.point.y
+        val resultY2 = ((resultX - point.x) * sin(angle) / cos(angle)) + point.y
+        var resultY = 0.0
+        if (abs(resultY1)> abs(resultY2)) resultY=resultY2
+        else resultY=resultY1

Форматирование кода



In src/lesson6/task1/Geometry.kt:
> @@ -97,29 +105,66 @@ data class Line(val point: Point, val angle: Double) {
      * Найти точку пересечения с другой линией.
      * Для этого необходимо составить и решить систему из двух уравнений (каждое для своей прямой)
      */
-    fun crossPoint(other: Line): Point = TODO()
+    fun crossPoint(other: Line): Point {
+        val resultX = (other.point.y - point.y + ((point.x * sin(angle) * cos(other.angle) - other.point.x * sin(other.angle) * cos(angle)) / cos(angle) / cos(other.angle))) /
+                ((sin(angle) * cos(other.angle) - cos(angle) * sin(other.angle)) / cos(angle) / cos(other.angle))
+        val resultY1 = ((resultX - other.point.x) * sin(other.angle) / cos(other.angle)) + other.point.y
+        val resultY2 = ((resultX - point.x) * sin(angle) / cos(angle)) + point.y

sin / cos = tan



In src/lesson6/task1/Geometry.kt:
>  
 /**
  * Средняя
  *
  * Построить прямую по двум точкам
  */
-fun lineByPoints(a: Point, b: Point): Line = TODO()
+fun lineByPoints(a: Point, b: Point): Line {
+    var angle = Math.atan2(a.y - b.y, a.x - b.x)
+    if (angle == PI || angle == -PI) angle = 0.0
+    if (angle < 0) angle += PI
+    return Line(a, angle)

Используйте lineBySegment



In src/lesson6/task1/Geometry.kt:
>  
 /**
  * Сложная
  *
  * Построить серединный перпендикуляр по отрезку или по двум точкам
  */
-fun bisectorByPoints(a: Point, b: Point): Line = TODO()
+fun bisectorByPoints(a: Point, b: Point): Line {
+    var angle = atan2(a.y - b.y, a.x - b.x)
+    if (angle == PI || angle == -PI) angle = 0.0
+    if (angle < 0) angle = PI + angle

Подобные операции с углом делаются несколько раз. Создайте для этой цели функцию



In src/lesson6/task1/Geometry.kt:
> +fun bisectorByPoints(a: Point, b: Point): Line {
+    var angle = atan2(a.y - b.y, a.x - b.x)
+    if (angle == PI || angle == -PI) angle = 0.0
+    if (angle < 0) angle = PI + angle
+    angle = PI / 2 + angle
+    if (angle == PI || angle == -PI) angle = 0.0
+    val distanceX: Double
+    val distanceY: Double
+    when {
+        a.x > b.x -> distanceX = a.x - abs(a.x - b.x) / 2
+        else -> distanceX = b.x - abs(a.x - b.x) / 2
+    }
+    when {
+        a.y > b.y -> distanceY = a.y - abs(a.y - b.y) / 2
+        else -> distanceY = b.y - abs(a.y - b.y) / 2
+    }

Оба этих when можно записать гораздо короче



In src/lesson6/task2/Chess.kt:
> @@ -23,7 +28,12 @@ data class Square(val column: Int, val row: Int) {
      * В нотации, колонки обозначаются латинскими буквами от a до h, а ряды -- цифрами от 1 до 8.
      * Для клетки не в пределах доски вернуть пустую строку
      */
-    fun notation(): String = TODO()
+    fun notation(): String {
+        val columnStr = mapOf<Int, String>(1 to "a", 2 to "b", 3 to "c", 4 to "d", 5 to "e", 6 to "f", 7 to "g", 8 to "h")
+        if (column !in 1..8 || row !in 1..8) return ""
+        val result = columnStr[column] + row.toString()

Преобразование toString() здесь лишнее



In src/lesson6/task2/Chess.kt:
> @@ -23,7 +28,12 @@ data class Square(val column: Int, val row: Int) {
      * В нотации, колонки обозначаются латинскими буквами от a до h, а ряды -- цифрами от 1 до 8.
      * Для клетки не в пределах доски вернуть пустую строку
      */
-    fun notation(): String = TODO()
+    fun notation(): String {
+        val colum [...]

2016-12-12 12:04 UTC, SeveNChaK commented on src/lesson6/task1/Geometry.kt
> +    return Circle(center, radius)
давно находил ошибку в crossPoint, но не знал как исправить. Вот постарался и с некоторой помощью переделал функцию.

2016-12-12 12:05 UTC, SeveNChaK commented on src/lesson6/task1/Geometry.kt
> +    }
Не смог придумать варианта короткой записи(

2016-12-12 12:06 UTC, SeveNChaK commented on src/lesson4/task1/List.kt
> +            }
Схожесь заметил, но не знаю как объединить, ведь первое слово в добавляемой строке различается.

2016-12-12 12:07 UTC, SeveNChaK commented on src/lesson6/task1/Geometry.kt
> +                ((sin(angle) * cos(other.angle) - cos(angle) * sin(other.angle)) / cos(angle) / cos(other.angle))
Переделал задачу полностью. Это одно уравнение и мне не пришло вариантов на какие отдельные переменные можно его разделить(

2016-12-12 12:08 UTC, SeveNChaK commented on src/lesson6/task1/Geometry.kt
> +        val resultY2 = ((resultX - point.x) * sin(angle) / cos(angle)) + point.y
Другие преподаватели советовали не использовать тангенс, так как в некоторых случаях может произойти некий конфуз, когда тангенса от такого числа не существует, вроде бы, или что-то другое

2016-12-12 12:10 UTC, SeveNChaK commented on src/lesson7/task2/Matrices.kt
> +        for (j in height - turn - 1 downTo turn) if (matrix[j, turn - 1] == 0) matrix[j, turn - 1] = number++
Мое мышление пока не может придумать вариантов, чтобы избавится от првоерки дополнительных условий. Буду рад подсказки как для этой задачи, так и для остальных, в которых не мог исправить до конца:)

2016-12-12 15:37 UTC, mglukhikh commented
recheck all

2016-12-12 15:42 UTC, mglukhikh commented
recheck all

2016-12-14 12:37 UTC, mglukhikh requested changes
В целом, замечания к вам минимальны, задач вы решили уже много. Для получения оценки "отлично" вам достаточно решить какую-либо задачу из урока номер 8.

2016-12-14 12:37 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            }
Ну я бы вынес в отдельные переменные `nPart1 % 10` и `nPart1 % 100`, которые встречаются по четыре раза. В этом случае первое слово можно брать из списка `"одна", "две", "три", "четыре"`. А второе слово `"тысяча"` для первой ветки и `"тысячи"` для остальных.

2016-12-14 12:37 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun moneyCounter(sum: Double, coins: String): String {
Пожалуйста, удалите эту задачу из репозитория

2016-12-14 12:37 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    }
Чем вам запись вида `(x + y) / 2.0` не угодила?

2016-12-14 12:37 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +                (Math.sin(other.angle) * Math.cos(angle) - Math.sin(angle) * Math.cos(other.angle))
Этот код можно упростить двумя способами:

1) Просто вынести в отдельные переменные постоянно встречающиеся значения, например, синусы и косинусы обоих углов
2) Написать отдельную маленькую функцию для решения системы из двух уравнений с двумя неизвестными и здесь вызвать её

2016-12-14 12:37 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return Circle(center, radius)
Ок

2016-12-19 08:39 UTC, mglukhikh commented
Ваше решение `countSubstrings` не учитывает, что строки могут накладываться друг на друга. Пока получается оценка "4".

2016-12-19 10:50 UTC, SeveNChaK commented
Исправил 8ой урок.Можно узнать, зачтена ли мне задача которую самостоятельно на паре решал?11:39, 19 декабря 2016 г., Mikhail Glukhikh <notifications@github.com>:Ваше решение countSubstrings не учитывает, что строки могут накладываться друг на друга. Пока получается оценка "4".

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

2016-12-19 21:40 UTC, mglukhikh commented
Простите, я не понял последний вопрос. Когда и что вы решали на паре? Вы про тестирование, может быть?

2016-12-19 21:41 UTC, mglukhikh commented
А исправление ваше верное.

2016-12-19 22:02 UTC, SeveNChaK commented
Да, про тестирование.0:40, 20 декабря 2016 г., Mikhail Glukhikh <notifications@github.com>:Простите, я не понял последний вопрос. Когда и что вы решали на паре? Вы про тестирование, может быть?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

2016-12-20 13:36 UTC, mglukhikh commented
За тестирование у вас стоит "4", мне казалось, что вы должны быть в курсе -- вы с Михаилом Анатольевичем это обсуждали. Ну а в целом, должен вас поздравить с успешным получением оценки "отлично" за семестр, задач вы решили много и качество высокое. В удобный момент подойдите к кому-нибудь из нас с зачёткой.

2016-12-20 13:36 UTC, closed without merging

2016-12-20 16:03 UTC, SeveNChaK commented
Спасибо, а где и когда и вообще до какого момента кого-нибудь из вас можно найти? Я просто пока болею и не знаю как вообще буду себя чувствовать в ближайшие дни, но надеюсь к концу недели поправлюсь.16:36, 20 декабря 2016 г., Mikhail Glukhikh <notifications@github.com>:За тестирование у вас стоит "4", мне казалось, что вы должны быть в курсе -- вы с Михаилом Анатольевичем это обсуждали. Ну а в целом, должен вас поздравить с успешным получением оценки "отлично" за семестр, задач вы решили много и качество высокое. В удобный момент подойдите к кому-нибудь из нас с зачёткой.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

2016-12-20 16:07 UTC, mglukhikh commented
В общем и целом, выставление оценок в зачётку процедура необязательная. Она лишь страхует вас от ситуации, когда что-то случается с ведомостями и / или мы забываем туда поставить оценку. Так что, в принципе, можно подождать до начала следующего семестра. А так, Марат Халимович и Михаил Анатольевич более-менее постоянно находятся в 9-301 (по будним дням после 12). Я сам буду в Политехе завтра с 10 до 14, в пятницу с 17 до 20, а после этого -- на консультации и на экзамене.

2016-12-20 16:13 UTC, SeveNChaK commented
а можно например во время экзамена прийти получить?19:07, 20 декабря 2016 г., Mikhail Glukhikh <notifications@github.com>:В общем и целом, выставление оценок в зачётку процедура необязательная. Она лишь страхует вас от ситуации, когда что-то случается с ведомостями и / или мы забываем туда поставить оценку. Так что, в принципе, можно подождать до начала следующего семестра. А так, Марат Халимович и Михаил Анатольевич более-менее постоянно находятся в 9-301 (по будним дням после 12). Я сам буду в Политехе завтра с 10 до 14, в пятницу с 17 до 20, а после этого -- на консультации и на экзамене.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

2016-12-20 17:21 UTC, mglukhikh commented
Да, если вам не лень ряди этого специально приходить

2016-12-20 17:42 UTC, SeveNChaK commented
Хорошо, спасибо20:21, 20 декабря 2016 г., Mikhail Glukhikh <notifications@github.com>:Да, если вам не лень ряди этого специально приходить

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

2016-12-23 11:02 UTC, SeveNChaK commented
Здравствуйте, а в какой аудитории вас сегодня можно найти?19:07, 20 декабря 2016 г., Mikhail Glukhikh <notifications@github.com>:В общем и целом, выставление оценок в зачётку процедура необязательная. Она лишь страхует вас от ситуации, когда что-то случается с ведомостями и / или мы забываем туда поставить оценку. Так что, в принципе, можно подождать до начала следующего семестра. А так, Марат Халимович и Михаил Анатольевич более-менее постоянно находятся в 9-301 (по будним дням после 12). Я сам буду в Политехе завтра с 10 до 14, в пятницу с 17 до 20, а после этого -- на консультации и на экзамене.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

2016-12-23 17:02 UTC, mglukhikh commented
Сейчас я в 9-306, но, наверное, уже поздно

2016-12-23 17:16 UTC, SeveNChaK commented
ну лаадно, на экзамене тогда.20:02, 23 декабря 2016 г., Mikhail Glukhikh <notifications@github.com>:Сейчас я в 9-306, но, наверное, уже поздно

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты