Еще из 5го
Kotlin-Polytech/KotlinAsFirst2016 pull request #225
Opened 2016-11-22 19:41 UTC by GlowBlood

2016-11-22 19:43 UTC, GlowBlood commented
То ничего не отправлялось, то все сразу отправилось ¯\_(ツ)_/¯
Еще и лажа какая-то происходит

2016-11-23 09:30 UTC, mglukhikh commented
См. файл `Parse.kt`. Директивы импорта должны идти сразу после директивы `package`, нельзя вставлять между ними какие-либо определения -- `val MONTHS` в вашем случае. Переставьте ваш список месяцев ниже, и всё будет в порядке. Напоминаю, кстати, что перед созданием коммита следует проверить, проходят ли тесты в учебном проекте локально -- в вашем случае проект даже не компилируется.

2016-11-24 13:29 UTC, mglukhikh commented
Я посмотрю код немного позже, но обратите внимание на падающий тест в отчёте бота

2016-11-25 20:30 UTC, mglukhikh requested changes
В принципе, всё довольно хорошо, замечания минимальны. Но `bestLongJump`, конечно, с ошибкой.

2016-11-25 20:30 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +val slist = listOf("0","1","2","3","4","5","6","7")
`"0123456789"`. По-моему, гораздо короче. А ещё можно добавлять к символу `'0'` цифру и получать соответствующий ей символ.

2016-11-25 20:30 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    center.distance(p) <= radius
Форматирование поехало. Да и лучше было написать всё в одной строке, она не длинная

2016-11-25 20:30 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val newJumps = jumps
Зачем эта переменная?

2016-11-25 20:30 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if (newNewJumps[i + 1].toInt() > newNewJumps[i].toInt()) max = newNewJumps[i + 1].toInt()
Эта методика определения максимума в списке неверна в корне. А ещё можно было преобразовать всё к `List<Int>` с помощью `map` и потом использовать `list.max()`.

2016-11-25 22:30 UTC, GlowBlood commented on src/lesson5/task1/Parse.kt
> +            if (newNewJumps[i + 1].toInt() > newNewJumps[i].toInt()) max = newNewJumps[i + 1].toInt()
Не получается так сделать
![image](https://cloud.githubusercontent.com/assets/22037087/20636110/e8725442-b377-11e6-8003-728b55935989.png)

2016-11-28 07:36 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if (newNewJumps[i + 1].toInt() > newNewJumps[i].toInt()) max = newNewJumps[i + 1].toInt()
А для кого я на лекции рассказывал про Nullability в Котлине и как с ней бороться? Функция `list.max()` возвращает `null`, если список пуст, поэтому тип её результата `Int?`. Вам необходимо этот `null` на что-то заменить (см. текст этой задачи). Сделать это можно, например, с помощью Элвис-оператора `?:`.

2016-12-01 21:08 UTC, GlowBlood commented
Извините, а можно получить какой-нибудь комментарий к моим изменениям?

2016-12-03 19:01 UTC, GlowBlood commented
А еще можно поинтересоваться, что Вы подразумеваете под словосочетанием "строковая нотация"??? Этого не написано нигде, видимо, нужно сообразить самостоятельно, но у меня не выходит.

2016-12-03 21:27 UTC, mglukhikh commented
"Возвращает строковую нотацию для клетки. В нотации, колонки обозначаются латинскими буквами от a до h, а ряды -- цифрами от 1 до 8.". 

```
a8 b8 c8 d8 e8 f8 g8 h8
...
a2 b2 c2 d2 e2 f2 g2 h2
a1 b1 c1 d1 e1 f1 g1 h1
```

2016-12-03 21:29 UTC, mglukhikh approved these changes
Я думаю, что ошибки вы исправили и PR можно закрыть. Так держать!

2016-12-03 21:29 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
>      if (s.begin.x == s.end.x) newAngle = Math.PI/2
По идее, эта проверка не нужна, `atan2` должен сделать всё сам.

2016-12-03 21:29 UTC, closed without merging

2016-12-04 14:44 UTC, GlowBlood commented
Понятно, спасибо

2016-12-07 09:20 UTC, mglukhikh commented
recheck all