Programs by Prokhorovmax (Prokhorov Maxim, 13531/3)
Kotlin-Polytech/KotlinAsFirst2016 pull request #228
Opened 2016-11-23 13:10 UTC by Prokhorovmax

Имеющиеся задачи из урока 6.1 приняты. По своему выбору, вы можете порешать что-нибудь ещё из 6-го урока либо перейти к уроку 7 (@mglukhikh)

2016-11-24 22:24 UTC, Prokhorovmax commented
Помогите, пожалуйста, с задачей из 6.1 circleByThreePoints, хотя бы укажите на некоторые ошибки. Вроде и на лекции про нее говорили, и вроде все правильно: алгоритм самый адекватный,  все используемые функции проходят тесты, но что-то не то :(

Помимо исправлений, которые, скорее всего и к сожалению, придется делать, хотел еще успеть сделать что-нибудь из 7.1 до вечера пятницы. Был бы признателен, если появится такая возможность.

2016-11-25 07:12 UTC, mglukhikh commented
Вы можете начать делать задачи из 7.1 в этом PR, я не возражаю (исправьте соответственно заголовок). Сегодня вечером посмотрю всё внимательно и помогу вам. Сейчас в связи с близкой аттестацией у нас очень много подобных запросов :)

2016-11-25 18:22 UTC, mglukhikh commented
recheck all

2016-11-25 18:31 UTC, mglukhikh commented
recheck all

2016-11-25 18:57 UTC, mglukhikh requested changes
Относительно небольшие замечания по коду + неработающее построение окружности по трём точкам (см. комментарии). А так вообще очень хорошо.

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            height == other.height && width == other.width && list.equals(other.list)
На Котлине лучше `list == other.list` вместо вызова `equals`

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    val kingTrajectory = mutableListOf<Square>(start)
Явное указание `<Square>` здесь не требуется, и так понятно, что список из `Square`

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +            else -> Square(currentSquare.column, currentSquare.row + 1)
Мне кажется, этот `when` можно значительно сократить

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        if (((columnChange % 2 == 1) && (rowChange % 2 == 1)) || ((columnChange % 2 != 1) && (rowChange % 2 != 1))) return 2
Это условие можно сократить примерно в четыре раза

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    val bishopTrajectory = mutableListOf<Square>()
Явное указание `Square` не требуется

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    val letterConversion = 96
Не нужно использовать магические константы, используйте сами символы и вычитайте их! Например, `notation[1] - '0'` даст вам цифру

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return Line(s.begin, angle)
Здесь и в `lineByPoints` можно обойтись без промежуточной переменной

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val y = (x - other.point.x) * Math.tan(other.angle) + other.point.y
Меня немножко смущают все эти тангенсы. Математически то, что вы написали, скорее всего верно, но не забывайте, что `tan(Math.PI / 2)` равен бесконечности. И в этом случае вряд ли ваши расчёты будут корректно работать.

2016-11-25 18:57 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return Circle(center, radius)
Математически всё верно. Я вам советую взять тест, предложенный ботом (достаточно очевидно, что ответ, указанный как Expected, в нём верен, а полученный вами Actual -- нет), и выполнить его в режиме отладки -- посмотрев, на какой стадии какой ответ вы получаете и где образуется ошибка. Я лично грешу на функцию `crossPoint`, но не исключено, что я ошибаюсь.

2016-11-30 12:22 UTC, mglukhikh approved these changes

2016-11-30 12:22 UTC, mglukhikh commented
Хорошо, содержимое уроков 6.1, 6.2, 7.1 принято

2016-11-30 12:22 UTC, closed without merging