Lesson6.task2 Hiraev Malik
Kotlin-Polytech/KotlinAsFirst2016 pull request #229
Opened 2016-11-23 14:27 UTC by MalikPiter

2016-11-30 09:23 UTC, mglukhikh requested changes
В целом всё хорошо, незначительные замечания по стилю. Обязательно поправьте реализацию `MatrixImpl.equals`, иначе вам будет нормально не проверить задачи из урока 7.2.

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    val alf = "abcdefgh"
Эту штуку лучше вынести на верхний уровень, иначе она будет храниться в каждом квадрате

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        if (column !in 1..8 || row !in 1..9) return ""
Почему вдруг до 9?

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        if (((square.column < 1) or (square.column > 8)) or ((square.row < 1) or (square.row > 8))) throw IllegalArgumentException()
Тут явный перебор с круглыми скобками, и лучше было бы использовать `!in` и `||` вместо `or`

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    } while (switch)
А можно ли решить эту задачу без цикла?

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        else -> columnDistance
Здесь как-то явный перебор условий. Можно значительно короче.

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    if ((symbolColumn == 0) and (symbolRow == 0)) return result
Лучше `&&`

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    }
Этот участок у вас дублируется, стоило бы вынести в отдельную функцию

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    centerSquare = Square(start.column, start.row)
Стоило бы объединить определение и инициализацию этой переменной

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    val distanceRow = abs(start.row - end.row)
Можно обойтись без второй части этой функции, если пересчитывать очередной шаг в цикле

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    //СОЕДИНЯЕМ ВСЕ КЛЕТКИ ШАХМАТНОЙ ДОСКИ С ВОЗМОЖНЫМИ ХОДАМИ КОНЯ
Эта часть сделана не очень изящно. Во-первых, перебирать всё-таки стоит номера рядов и колонок, а не их обозначения. Во-вторых, можно было бы заранее создать список из возможных перемещений коня (на сколько клеток он смещается по обеим координатам) и здесь его использовать

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    return chessGraph
Вы сумели здесь использовать готовый класс `Graph`. По-своему это хорошо, но обращаю внимание на то, что поиск траектории в этом классе не реализован. Так что для решения `knightTrajectory` -- если соберётесь -- вам придётся либо расширить класс `Graph`, либо реализовать уже свой вариант BFS-алгоритма

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?) = other is MatrixImpl<*> && height == other.height && width == other.width
Эта реализация ошибочна -- она считает равными любые матрицы одинакового размера.

2016-11-30 09:23 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        result = 31 * result + list.hashCode()
А вот эта реализация верная -- здесь вы учли и `height`, и `width`, и `list`.

2016-12-06 18:47 UTC, Hiraev commented
@mglukhikh , как мне это исправить?
Я не могу выгрузить измененный документ
<img width="1008" alt="2016-12-06 21 44 25" src="https://cloud.githubusercontent.com/assets/6796753/20938799/74f5ea4a-bbfd-11e6-9e9d-89d7a6849d9a.png">
<img width="1327" alt="2016-12-06 21 46 09" src="https://cloud.githubusercontent.com/assets/6796753/20938809/7d608de8-bbfd-11e6-8afb-2b671c7dfc23.png">

2016-12-06 19:55 UTC, Hiraev commented
recheck all

2016-12-06 20:40 UTC, Hiraev commented
recheck all

2016-12-06 20:44 UTC, closed without merging