Уроки до 6
Kotlin-Polytech/KotlinAsFirst2016 pull request #233
Opened 2016-11-24 23:34 UTC by feternal

Сделанные задачи из уроков 4, 5, 6

2016-11-25 22:02 UTC, belyaev-mikhail commented
recheck all

2016-11-25 22:23 UTC, belyaev-mikhail requested changes

2016-11-25 22:23 UTC, belyaev-mikhail commented on pom.xml
>      <version>0.0.1-SNAPSHOT</version>
Зачем вы меняете файл pom.xml? Если это сломает вам проверку ваших заданий, виноваты будете только вы.

2016-11-25 22:23 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = sagenes * 48 * 0.04445 + arshins * 16 * 0.04445 + vershoks * 0.04445
Длинные строки следует разбивать на более короткие

2016-11-25 22:23 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = (hoursArrive * 60 + minutesArrive) - (hoursDepart * 60 + minutesDepart)
См. комментарий про длинные строки

2016-11-25 22:23 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if ((castleAttack(rookX1, rookY1, kingX, kingY)) && (castleAttack(rookX2, rookY2, kingX, kingY))) return 3
Такие цепочки из `if`-ов следует заменять на `when`

2016-11-25 22:23 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if ((castleAttack(rookX, rookY, kingX, kingY)) && (!bishopAttack(bishopX, bishopY, kingX, kingY))) return 1
Аналогично

2016-11-25 22:23 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if ((a + b > c) && (a + c > b) && (b + c > a)) {
Аналогично

2016-11-25 22:23 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +import java.time.Month
Зачем? Вы же нигде это не используете.

2016-12-19 13:45 UTC, feternal commented
Изменения же прошли?

2016-12-19 22:18 UTC, mglukhikh commented
recheck all

2017-07-26 18:23 UTC, closed without merging