Lesson6.task1
Kotlin-Polytech/KotlinAsFirst2016 pull request #234
Opened 2016-11-24 23:47 UTC by avightclav

2016-11-25 11:13 UTC, mglukhikh commented
Решение `diameter` выглядит верным, это баг в тестах. Решение `circleByThreePoints` явно ошибочно.

2016-11-28 19:25 UTC, avightclav commented
А будут вообще какие-то замечания/предложения по коду? Хотя бы какой-нибудь фидбек?

2016-11-29 10:37 UTC, mglukhikh commented
Будут, будут. Сегодня или завтра посмотрим.

2016-11-30 11:48 UTC, mglukhikh requested changes
Много замечаний по коду + неработающие тесты в уроке 6.1

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    fun length(): Double = sqrt(sqr(begin.x - end.x) + sqr(begin.y - end.y))
У вас уже есть `Point.distance`, здесь её можно использовать

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        for (z in convexHull.withIndex()) { // можно ли начать итерацию не с самого начала листа, а с определёенного индекса (в данном случае с i индекса)?
Есть `subList`, который можно для этой цели использовать

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val convexHull = if (points.size >= 3) points.asList() else convexHull(points)
Я не понял всю эту конструкцию. Почему нельзя взять `points.asList()` всегда? Ответьте в комментарии, пожалуйста

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +fun convexHull(points: Array<out Point>): List<Point> {
Объясните, пожалуйста, что делает эта функция и зачем

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +fun polarAngle(p0: Point, p1: Point, p2: Point): Double {
Смысл этой функции мне тоже не очень понятен. Причём тут полярный угол, если это просто разница в длине двух отрезков?

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return angle
Прочитайте про `Math.atan2`

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val convexHull = if (points.size >= 3) points.asList() else convexHull(points)
Отмечу, кстати, что реализация не проходит тесты

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +                (1 / tan(angle) - 1 / tan(other.angle))
Я рекомендую вам для поиска пересечения использовать то уравнение прямой, которое приведено в комментарии к классу `Line`. С тангенсом здесь может быть всё непросто, так как он свободно может быть как очень маленьким, так и очень большим. Как результат, решение теряет устойчивость (небольшое изменение входных данных ведёт к большому изменению результата).

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        if (((ulpequals(abs(angle), PI / 2)) && ((ulpequals(abs(other.angle), 0.0)) || (ulpequals(abs(other.angle), PI))))) {
Весь код начиная отсюда очень подозрителен, рекомендую вам его убрать и вместо этого разобраться в причинах возникающих проблем.

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            val s = diameter2(points)
Зачем понадобилась ещё одна реализация `diameter`? Может быть, лучше поправить основную, так, чтобы она хотя бы проходила тесты?

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            return Circle(middle, radius)
Не во всех случаях данная окружность включает в себя все точки множества. См. комментарий к задаче.

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +val columns = listOf("", "a", "b", "c", "d", "e", "f", "g", "h")
Здесь лучше было использовать просто строку

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    fun equals(square: Square): Boolean {
Зачем это, если есть `==`? И настоящий `equals(other: Any?)` для `data class` переопределяется автоматически.

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    } catch (e: StringIndexOutOfBoundsException) {
Не нужно ловить это исключение, ситуация, когда оно возникает -- это ошибка программиста. Проверьте размер строки перед началом операций

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        if ((start.row == end.row) && (start.column == end.column)) return 0
`start == end`

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        get() = ((this.row <= height) && (this.column <= width))
Лучше `exists`. И непонятно, почему `<=`, а не `<`, и почему не проверяется нижняя граница (0)

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        if (Cell(row, column).exist)
Зачем эта проверка, если всё равно при отсутствии элемента в `map` кидается то же самое исключение?

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        else throw IllegalArgumentException()
Не нужно дважды писать одно и то же. Используйте из одной функции другую.

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        else throw IllegalArgumentException()
Форматируйте код консистентно. Если после `if` стоит ENTER и отступ, то сделайте то же самое и после `else`

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        else throw IllegalArgumentException()
См. выше

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?): Boolean = other is MatrixImpl<*> && height == other.height && width == other.width
Вы забыли сравнить на равенство элементы. Обязательно поправьте эту функцию, иначе вы не сможете нормально проверять задачи урока 7.2

2016-11-30 11:48 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        for (i in map)
Можно было просто взять хэш-код от `map` целиком

2016-11-30 23:38 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +    fun length(): Double = sqrt(sqr(begin.x - end.x) + sqr(begin.y - end.y))
Согласен. Исправлю.

2016-11-30 23:40 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +    val convexHull = if (points.size >= 3) points.asList() else convexHull(points)
Моя программа строит выпуклую оболочку множества и сравнивает только её элементы. Алгоритм мне подсказал Марат Халимович (уважаемый человек, между прочим!).

2016-11-30 23:40 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +        for (z in convexHull.withIndex()) { // можно ли начать итерацию не с самого начала листа, а с определёенного индекса (в данном случае с i индекса)?
Спасибо!

2016-11-30 23:41 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +fun convexHull(points: Array<out Point>): List<Point> {
Строит выпуклую оболочку множества по алгоритму "Graham Scan", для того, чтобы сравнивать меньшее количество отрезком.

2016-11-30 23:43 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +fun polarAngle(p0: Point, p1: Point, p2: Point): Double {
Потому что алгоритм позволяет отсортировать отрезки относительно одной точки в порядке возрастания полярного угла.

2016-11-30 23:48 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +                (1 / tan(angle) - 1 / tan(other.angle))
Я выразил один аргумент через систему уравнений, отталкиваясь исключительно от предложенного уравнения. Ничего другого я придумать не смог. Надеюсь на Ваш совет.

Михаил Беляев (тоже уважаемый в обществе человек) говорит наоборот, что не согласен с уравнением прямой, которое предложено. Поэтому прошу вас объяснить почему Вы рекомендуете использовать именно его.

2016-11-30 23:52 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +        if (((ulpequals(abs(angle), PI / 2)) && ((ulpequals(abs(other.angle), 0.0)) || (ulpequals(abs(other.angle), PI))))) {
Это единственное возможное решение предложенных уравнений, которое я смог придумать.

Михаил Беляев (напомню, уважаемый в обществе человек), сказал мне, что сравнивать оператором "==" два числа типа Double ни в коем случае нельзя, и мою задачу нельзя будет даже зачесть. К слову, иначе моя программа пытается поделить единицу на тангенс очень маленького угла (подробнее в результатах тестов), и получает бесконечность, хотя должна, как мне сказали (из-за ограничений типа Double) принять его за ноль (сам угол).

2016-12-01 00:18 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +    return angle
Спасибо. я знаю про эту функцию, но чем хуже эта?

2016-12-01 00:20 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +            val s = diameter2(points)
Согласен, что вторая реализация была лишней (но я торопился к зачёту).

Но я всё же не понимаю, то что моя программа выводит точки в другом порядке (в редких случаях) -- не единственная ошибка?

2016-12-01 00:21 UTC, avightclav commented on src/lesson6/task1/Geometry.kt
> +            return Circle(middle, radius)
Я это понял вчера. А как определить когда какой случай?

2016-12-01 00:21 UTC, avightclav commented on src/lesson6/task2/Chess.kt
> +val columns = listOf("", "a", "b", "c", "d", "e", "f", "g", "h")
Спасибо! Согласен!

2016-12-01 00:21 UTC, avightclav commented on src/lesson6/task2/Chess.kt
> +    fun equals(square: Square): Boolean {
Это было глупо! Но я уже получил ответ на Вашей лекции. Спасибо!

2016-12-01 00:22 UTC, avightclav commented on src/lesson6/task2/Chess.kt
> +    } catch (e: StringIndexOutOfBoundsException) {
Спасибо!

2016-12-01 00:23 UTC, avightclav commented on src/lesson7/task1/Matrix.kt
> +        get() = ((this.row <= height) && (this.column <= width))
Согласен! Это оплошность! Спасибо!

2016-12-01 00:23 UTC, avightclav commented on src/lesson7/task1/Matrix.kt
> +        if (Cell(row, column).exist)
Не знал, хотя, теперь уже понимаю, что это несколько логично. Спасибо!

2016-12-01 18:14 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            return Circle(middle, radius)
Банально проверить, включает эта окружность все точки или нет :)

2016-12-01 18:15 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    return angle
По сути дела, здесь вы пытаетесь на базе `atan` сделать `atan2`.

2016-12-01 18:18 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val convexHull = if (points.size >= 3) points.asList() else convexHull(points)
Эммм... Марат Халимович, конечно, очень уважаемый человек, но почему для трёх и более точек вы берёте исходный список, а вот если их две и менее -- начинаете строить выпуклую оболочку? По-моему, как раз в этом случае ничего строить уже точно не надо (для двух точек нужно просто построить отрезок из этих двух точек, для одной и менее бросить исключение).

2016-12-01 18:22 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +                (1 / tan(angle) - 1 / tan(other.angle))
Косинус и синус всегда лежат в пределах от -1 до 1. А когда вы имеете дело с тангенсом, вы свободно можете получить уравнение вида `INF * (x - p.x) = y - p.y`, где `INF` -- бесконечность. Или то же самое с очень большим числом вместо бесконечности. Вы можете предсказать, как будут работать ваши формулы с подобными коэффициентами? Мне, например, даже думать про это страшно :)

2016-12-01 18:26 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        if (((ulpequals(abs(angle), PI / 2)) && ((ulpequals(abs(other.angle), 0.0)) || (ulpequals(abs(other.angle), PI))))) {
А зачем вам вообще что-то сравнивать? У вас есть два линейных уравнения относительно `x` и `y`. Вы их решаете и находите значения `x` и `y`, строите из них точку и возвращаете её. А у вас после этого начинаются какие-то странные сравнения и проверки -- и всё потому, что в коэффициентах иногда фигурируют бесконечности и решение просто неверно считается. IMHO, конечно.

2016-12-01 18:29 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            val s = diameter2(points)
Да, это замечание похоже справедливо, здесь нам нужно чинить наши тесты. Странно, мне казалось, что сравнение отрезков независимо от порядка точек в них уже было сделано.

2016-12-01 18:31 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +            val s = diameter2(points)
Но это касается задачи `diameter`. В `minContainingCircle` ошибка ваша. Собственно, у вас не проходит один из локальных тестов (имеющихся в самом учебном проекте).

2016-12-01 18:32 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        if (Cell(row, column).exist)
Вы меня здесь не вполне поняли. Оно кидается в вашем собственном коде: 
```
return map[cell] ?: throw IllegalArgumentException()
```

Map возвращает `null`, если элемента нет, а ваш элвис-оператор вместо него бросает исключение

2016-12-18 21:44 UTC, mglukhikh commented
recheck all

2016-12-18 21:54 UTC, mglukhikh commented
recheck all

2016-12-18 21:55 UTC, mglukhikh commented
recheck all

2016-12-18 21:57 UTC, mglukhikh commented
recheck all

2016-12-18 21:59 UTC, mglukhikh requested changes
Хочу проверить, что у вас сейчас получается по тестам, но бот явно перегружен :(. Вот пока немножко замечаний по коду. Пока у вас получается что-то в районе "3.5", для четвёрки нужно, как минимум, решить что-нибудь из урока 7.2. Плюс у вас пока не пройдено тестирование. Замечания тоже надо исправлять.

2016-12-18 21:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            map[cell] = value
Примените Ctrl+Alt+L (автоформат) к этому файлу, а то тут не всё в порядке с форматированием

2016-12-18 21:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?): Boolean = other is MatrixImpl<*> && height == other.height && width == other.width && map == other.map
Здесь лучше после = вставить перенос строки, длинновато

2016-12-18 21:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        result += map.hashCode()
Лучше как раньше: `result = result * 31 + map.hashCode()`, так код получается качественнее

2016-12-18 21:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    */
Сотрите закомментированный код, пожалуйста

2016-12-18 21:59 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    else return MatrixImpl<E>(height, width, e)
Здесь нет необходимости указывать `<E>`

2016-12-18 22:27 UTC, mglukhikh requested changes
Написал ещё чуть-чуть замечаний про неработающие тесты.

2016-12-18 22:27 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    if ((notation.length == 2) && (notation[1].toString().toInt() in 1..8) && (columns.indexOf(notation[0].toString()) != -1)) {
В вашем решении не учитывается, что `toInt` может кинуть `NumberFormatException`. А в общем и целом рекомендую подумать, как то же самое записать короче.

2016-12-18 22:27 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        for (z in convexHull.withIndex()) { // можно ли начать итерацию не с самого начала листа, а с определёенного индекса (в данном случае с i индекса)?
Можно, нужно использовать `sublist`

2016-12-18 22:27 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val pointsList = points.sortedWith(Comparator { o1, o2 -> -(polarAngle(p0, o1, o2).toInt()) }).toMutableList()
Вот этот компаратор мне точно очень подозрителен. Компаратор будет считать точки равными, если лямбда выдала 0. А ваш `toInt()` может округлить до нуля совсем ненулевой угол. Скорее всего, из-за этого падает тест бота с ошибкой "Comparison method violates its general contract"

2016-12-18 22:27 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val p0 = points.minWith(Comparator { o1, o2 -> if (o1.y == o2.y) (o1.x - o2.x).toInt() else (o1.y - o2.y).toInt() })!!
Да и этот компаратор не лучше. Рассмотрим три точки: `(1, 0)`, `(1.5, 0)`, `(2, 0)`. С точки зрения вашего компаратора, первая из них равна второй, вторая равна третьей. Зато первая меньше третьей. Нарушено свойство транзитивности. Может быть, тест бота падает и из-за этого

2017-07-26 18:23 UTC, closed without merging