Lessons 5, 6
Kotlin-Polytech/KotlinAsFirst2016 pull request #238
Opened 2016-11-30 10:35 UTC by KhoroshkovKirill

2016-12-05 15:56 UTC, belyaev-mikhail commented
recheck all

2016-12-05 16:14 UTC, belyaev-mikhail requested changes

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = hours*3600+minutes*60+seconds;
Использование пробелов в коде должно быть консистентным.
Если вы ставите пробелы до и после знаков операций &mdash; ставьте их **везде**, если не ставите &mdash; их не следует ставить **нигде**.

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +        (sagenes*48 + arshins*16 + vershoks) * 0.04445
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad + min/60.0 + sec/3600.0)* Math.PI /180
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(sqr(x2-x1) + sqr(y2-y1))
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun thirdDigit(number: Int): Int = number/100%10
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +        hoursArrive * 60 + minutesArrive -hoursDepart*60 - minutesDepart
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +        ((initial.toDouble()*(percent/100.0+1))*(percent/100.0+1))*(percent/100.0+1)
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = number%10*100 + (number/10%10*10) + (number/100)
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if ((age %10 in 5..9)||(age %100 in 11..19)||(age %10==0)) {
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson2/task1/IfElse.kt
> +    if(s1>=half_s)
+1

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    for(d in 2..Math.sqrt(n.toDouble()).toInt()){
Это некорректный способ взятия корня от целого числа.
Может так получиться, что число, которое вернёт это выражение, будет меньше настоящего корня, и тогда вы его упустите.

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    for(i in n/2 downTo Math.sqrt(n.toDouble()).toInt()){
Аналогично

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +import javafx.scene.control.Separator
Что это и зачем?

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            rez.add((from_convert[i] + '0'.toInt()).toChar())
`(from_convert[i] + '0'.toInt()).toChar()` это зачем? Можно же просто написать `'0' + from_convert[i]`

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            rez.add((from_convert[i] + 'a'.toInt() - 10).toChar())
Аналогично

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            to_decimal.add(str[i].toInt() - '0'.toInt())
Аналогично

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson4/task1/List.kt
> +            to_decimal.add(str[i].toInt() - 'a'.toInt() + 10)
Аналогично

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson5/task1/Parse.kt
> +        if (words[i].equals(words[i+1])){
Зачем в явном виде тут вызывать `equals()`?

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +fun lineByPoints(a: Point, b: Point): Line = Line(a,Math.atan((a.y - b.y) / (a.x - b.x)))
А что будет, если сегмент параллелен оси Y?

2016-12-05 16:14 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +    else if (Math.atan2((a.y - b.y),(a.x - b.x)) > 0)
Кучу раз считать арктангенс &mdash; крайне неэффективно.

2016-12-07 09:16 UTC, mglukhikh commented
recheck all

2016-12-14 17:50 UTC, belyaev-mikhail requested changes

2016-12-14 17:50 UTC, belyaev-mikhail commented on src/lesson3/task1/Loop.kt
> +    for (i in n / 2 downTo Math.sqrt(n.toDouble()).toInt() - 1) {
Почему `- 1`?

2016-12-14 17:50 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +    Math.atan((a.y - b.y) / (a.x - b.x)))
Почему вы здесь не используете `Math.atan2`?

2016-12-14 17:50 UTC, belyaev-mikhail commented on src/lesson6/task1/Geometry.kt
> +    else if (Math.atan2((a.y - b.y), (a.x - b.x)) > 0)
Зачем кучу раз пересчитывать арктангенс?

2016-12-19 22:28 UTC, mglukhikh commented
recheck all

2016-12-19 22:31 UTC, mglukhikh commented
Решать 8-й урок, пропустив 7-й -- это, конечно, очень хитро.

2016-12-20 20:50 UTC, belyaev-mikhail commented
recheck all

2017-07-26 18:23 UTC, closed without merging