Lesson7.task2 Hiraev Malik 13531/2
Kotlin-Polytech/KotlinAsFirst2016 pull request #241
Opened 2016-12-07 15:01 UTC by Hiraev

2016-12-07 15:19 UTC, Hiraev commented
recheck last

2016-12-07 15:20 UTC, Hiraev commented
recheck c821aa0

2016-12-07 15:21 UTC, Hiraev commented
recheck lesson7.task2

2016-12-07 15:22 UTC, Hiraev commented
recheck Matrices.kt

2016-12-07 15:23 UTC, Hiraev commented
recheck src/lesson7/task2/Matrices.kt

2016-12-07 20:49 UTC, mglukhikh commented
recheck assignment

2016-12-07 20:55 UTC, mglukhikh requested changes
В общем всё хорошо, но две задачи, как вы видите, не работают :(

2016-12-07 20:55 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +            listColumns += matrix[j, i] //Добавляем очередную ячейку в столбец
Здесь вас ничто не гарантирует от выхода за границу матрицы

2016-12-07 20:55 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +        row += symbolRow
В этой функции я бы посмотрел просто по тесту от бота, что не так. Вообще, ситуация в этой задаче может слегка меняться в зависимости от чётности числа рядов и колонок. Кроме этого, могут возникать проблемы на последних шагах -- что у вас и происходит

2016-12-08 21:10 UTC, Hiraev commented on src/lesson7/task1/Matrix.kt
> +                sb.append("$elem [$row, $column] $tabulation")
@mglukhikh , почему у меня числа распределяются не равномерно? Я изменил строку `sb.append("$elem [$row, $column] $tabulation")` на `sb.append("$elem $tabulation")`, чтобы разобраться в функции generateSpiral()
<img width="470" alt="2016-12-09 0 06 01" src="https://cloud.githubusercontent.com/assets/6796753/21027862/be2829f6-bda3-11e6-9cec-db3aebe0304e.png">

2016-12-08 21:12 UTC, Hiraev commented on src/lesson7/task1/Matrix.kt
> +                sb.append("$elem [$row, $column] $tabulation")
под неравномерность я подразумеваю разное расстояние между числами, при их выводе на дисплей

2016-12-09 07:54 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +                sb.append("$elem [$row, $column] $tabulation")
Объясняю, как работает табуляция в консоли. Этот символ переводит вывод в следующую условную колонку, обычно колонка занимает 4 или 8 пробелов в зависимости от настроек консоли -- в вашем случае это 4 пробела. Поэтому, если в очередную колонку выведено три и менее символов, например, `"68 "`, то мы ещё находимся в предыдущей колонке и для того, чтобы попасть в следующую колонку, надо добавить один символ. А вот если выведено четыре символа, то мы уже попали в следующую колонку и добавление табуляции добавит ещё четыре пробела.

2016-12-09 13:20 UTC, Hiraev commented
recheck all

2016-12-09 13:22 UTC, Hiraev commented on src/lesson7/task1/Matrix.kt
> +    override fun maxLength(): Int { //Функция для нахждения самой длинной строки в матрице
Попытался добавить свою функцию, чтобы отобразить матрицу в более привлекательном виде, но что-то пошло не так. Однако у меня все работало хорошо.

2016-12-09 14:39 UTC, mglukhikh approved these changes

2016-12-09 14:39 UTC, mglukhikh commented
Спасибо. 7-й урок принят

2016-12-09 14:39 UTC, closed without merging