Lesson 7
Kotlin-Polytech/KotlinAsFirst2016 pull request #243
Opened 2016-12-08 21:40 UTC by Pashnik

and 4 Tasks from Lesson 6.2

2016-12-09 11:41 UTC, mglukhikh commented
recheck all

2016-12-09 11:43 UTC, mglukhikh commented
Название PR не соответствует содержанию -- пока не вижу здесь ни одной задачи из 7-го урока.

2016-12-09 11:44 UTC, mglukhikh commented
Обратите внимание на падающий тест в первом (!) уроке.

2016-12-09 11:47 UTC, mglukhikh commented
Прежде чем кто-нибудь из нас перечитает текст урока 6.2 внимательно, рекомендую вам сделать это самому. Многие вещи в нём можно написать короче. В падающем тесте вы, судя по всему, даёте траекторию движения слона, не соответствующую шахматным правилам.

2016-12-12 09:28 UTC, mglukhikh requested changes
Написал замечаний к уроку 6.2

2016-12-12 09:28 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    fun correctSquare(square: Square) : Boolean {
Такая функция уже есть и называется `inside()`, эта функция не нужна. Кроме этого, напомню вам, что у функций, определённых внутри класса, всегда есть один неявный параметр, так называемый "получатель". В этой функции вы игнорируете его существование. Сравните реализацию вашей функции и функции `inside()` и сделайте выводы

2016-12-12 09:28 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        return false
`if (...) return true else return false` эквивалентно ...?

2016-12-12 09:28 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    fun squareUnparity(column: Int, row: Int) : Boolean {
А здесь я бы просто использовал отрицание от `squareParity`

2016-12-12 09:28 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +            || (start.squareUnparity(start.column, start.row) && end.squareParity(end.column, end.row)))
Это условие можно записать значительно короче, используя операцию `!=` над `Boolean`

2016-12-12 09:28 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    if (!start.correctSquare(start) || !end.correctSquare(end)) throw IllegalArgumentException()
Используйте `inside()`

2016-12-12 09:28 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +    if (!start.correctSquare(start) || !end.correctSquare(end)) throw IllegalArgumentException()
Используйте `inside()`

2016-12-12 09:28 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +            || start.squareUnparity(start.column, start.row) && end.squareUnparity(end.column, end.row)) {
А в этом условии можно использовать `==` над `Boolean`

2016-12-12 09:28 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +                return listOf(start, intermediateSquare, end)
`return` здесь и ниже можно вынести из `if`, это несколько сократит код

2016-12-14 12:43 UTC, mglukhikh commented
recheck all

2016-12-14 13:10 UTC, mglukhikh approved these changes
Изменения приняты, первые шесть уроков и первая половина седьмого зачтены. На "четыре" вам осталось решить только что-нибудь из урока 7.2. Если же вы хотите "пять", то необходимо также решить одну задачу из урока 8 + одну задачу категории "Очень сложная" из любого урока на ваш выбор.

2016-12-14 13:10 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +fun myFun(examResults: List<String>, threshold: Double): MutableList<String> {
Уберите, пожалуйста, эту функцию из репозитория

2016-12-14 13:10 UTC, closed without merging

2016-12-14 13:11 UTC, Pashnik commented
Хорошо, спасибо большое

ср, 14 дек. 2016 г. в 16:10, Mikhail Glukhikh <notifications@github.com>:

> Closed #243
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/243>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/243#event-893590598>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AImjbY-XDTv_VP_bvkH5GfQzaHXwPJ4fks5rH-rGgaJpZM4LIUQK>
> .
>