lesson 7,8
Kotlin-Polytech/KotlinAsFirst2016 pull request #245
Opened 2016-12-12 15:04 UTC by mezd10

2016-12-12 17:22 UTC, mglukhikh commented
recheck all

2016-12-12 17:24 UTC, mglukhikh commented
recheck all

2016-12-14 20:24 UTC, mglukhikh requested changes
Пересмотрел ваш код с самого начала, он довольно хорош, замечания к вам незначительны (самые серьёзные -- замечания к equals и hashCode в 7-м уроке). Тем страннее проблемы, возникающие у вас при написании тестирования. Замечания исправьте, и желаю вам удачи в 3-й попытке.

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        else result.append(i)
Поехало форматирование

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            9 -> "девятьсот"
Подобную информацию лучше всё-таки хранить в списках, чем писать такие здоровенные `when`

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            "декабря" -> 12
Аналогичное предыдущему замечание. Создайте список месяцев (как глобальную переменную, то есть ПЕРЕД функцией) и пользуйтесь им. А иначе получается, что похожий `when` у вас имеется в двух разных функциях.

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            12 -> "декабря"
См. выше

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val k1 = Math.tan(this.angle)
Что будет, если угол равен пи пополам или же очень близок к нему?

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +fun lineBySegment(s: Segment): Line = Line(s.begin, Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x)))
Здесь лучше применить `atan2`, избегая тонкостей, возникающих при делении на ноль

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return true
Данная функция `equals` не соответствует контракту: она возвращает `true` для любых матриц неравного размера, проверьте. На всякий случай напомню, что списки тоже можно сравнивать на равенство

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +        return result
Данный вариант расчёта хэш-кода формально корректен, но нехорош, поскольку никак не учитывает элементы матрицы

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +    @file:Suppress("UNUSED_PARAMETER")
Зачем эти лишние пробелы?

2016-12-14 20:24 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +                if (quantityElement == lineLowerCase.length) quantity++
Нельзя ли всё это написать как-нибудь покороче?

2016-12-16 21:30 UTC, mglukhikh commented
recheck all

2016-12-16 21:35 UTC, mglukhikh approved these changes

2016-12-16 21:37 UTC, mglukhikh commented
Оставшиеся замечания незначительны, хотя ответы на заданные вопросы всё же хотелось бы получить.

2016-12-17 21:41 UTC, mezd10 commented on src/lesson6/task1/Geometry.kt
> +fun lineBySegment(s: Segment): Line = Line(s.begin, Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x)))
при использовании atan2 выдает ошибку при значении х

2016-12-17 21:42 UTC, mezd10 commented on src/lesson6/task1/Geometry.kt
> +        val k1 = Math.tan(this.angle)
тангенса пи пополам не существует же

2016-12-17 21:42 UTC, mezd10 commented on src/lesson8/task1/Files.kt
> +    @file:Suppress("UNUSED_PARAMETER")
убрал

2016-12-17 21:43 UTC, mezd10 commented on src/lesson8/task1/Files.kt
> +                if (quantityElement == lineLowerCase.length) quantity++
покороче именно цикл?

2016-12-18 16:35 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val k1 = Math.tan(this.angle)
Вот поэтому я и спрашиваю, как ваша функция будет работать в данном случае

2016-12-18 16:35 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +fun lineBySegment(s: Segment): Line = Line(s.begin, Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x)))
Не понял, о какой ошибке вы говорите. Приведите пример неработающего кода в комментарии

2016-12-18 16:36 UTC, mglukhikh commented on src/lesson8/task1/Files.kt
> +                if (quantityElement == lineLowerCase.length) quantity++
Нет, я о том, что, может быть, тут вообще можно сократить количество циклов

2016-12-18 17:14 UTC, mezd10 commented on src/lesson6/task1/Geometry.kt
> +fun lineBySegment(s: Segment): Line = Line(s.begin, Math.atan((s.end.y - s.begin.y) / (s.end.x - s.begin.x)))
извините, это моя ошибка, уже исправил

2016-12-18 17:58 UTC, mezd10 commented on src/lesson6/task1/Geometry.kt
> +        val k1 = Math.tan(this.angle)
просто выводит ошибку, но компиляция проходит

2016-12-18 17:59 UTC, mezd10 commented on src/lesson8/task1/Files.kt
> +                if (quantityElement == lineLowerCase.length) quantity++
сократил, чуть-чуть изменив код

2016-12-19 08:34 UTC, mglukhikh commented
Решение по поводу вашей окончательной оценки будет принято сегодня на упражнениях (с учётом результатов тестирования и некоторых других обстоятельств)

2016-12-19 21:23 UTC, closed without merging