tututu
Kotlin-Polytech/KotlinAsFirst2016 pull request #248
Opened 2016-12-14 18:10 UTC by onfound

2016-12-14 19:11 UTC, onfound commented
recheck all

2016-12-14 19:23 UTC, onfound commented
rechek all

2016-12-14 19:55 UTC, mglukhikh commented
recheck all

2016-12-14 20:04 UTC, mglukhikh commented
Подробнее мы посмотрим ваш PR чуть позже, а пока обратите внимание на неработающие тесты в 6-м уроке (особенно это касается части 6.2).

2016-12-16 10:32 UTC, maximpetrov commented
recheck all

2016-12-16 14:13 UTC, maximpetrov requested changes

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        result += digits[i] * pow(base, digits.size - 1 - i)
Зачем, идя от младших цифр к старшим, Вы всё равно используете `pow`?

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    val map1 = mapOf(4 to "IV", 1 to "I", 5 to "V", 9 to "IX", 10 to "X", 40 to "XL", 50 to "L", 90 to "XC", 100 to "C", 400 to "CD", 500 to "D", 900 to "CM", 1000 to "M").toSortedMap()
`sortedMapOf`

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val condition2 = b != c && d != a
Нужно ли рассматривать этот случай отдельно?

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        val parse = map1.entries.findLast { it.key <= number } ?: continue
Почему `continue`, если ничего не будет найдено? Если так действительно случится, то Вы попадёте в бесконечный цикл, ведь `number` меняться не будет. Если Вы уверены, что что-то должно найтись в любом случае, то используйте `!!` вместо `?:`.

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    for (i in 0..points.size - 2)
Зачем Вы здесь начинаете с 0, если уже рассмотрели пару (0, 1)?

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    for (i in 0..circles.size - 2) {
Аналогично, зачем перебор с 0, если пара (0, 1) уже рассмотрена

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson6/task2/Chess.kt
> +        val result = Square(notation[0] - '`', notation[1] - '0')
Почему ```'`'```?

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson7/task1/Matrix.kt
> +    override fun get(row: Int, column: Int): E = map[Cell(row, column)] ?: throw IllegalArgumentException()
Лучше наоборот, определить этот метод через `get(cell: Cell)`

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson7/task1/Matrix.kt
> +        map[Cell(row, column)] = value
Лучше наоборот, определить этот метод через `set(cell: Cell, value: E)`

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[Cell(row, column)])
Попробуйте вызвать `toString` на какой-нибудь матрице и разобраться в том, что он вернёт.

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson7/task2/Matrices.kt
> +import lesson7.task1.MatrixImpl
Зачем Вам этот импорт?

2016-12-16 14:13 UTC, maximpetrov commented on src/lesson8/task1/Files.kt
> +    for (element in substrings) result += Pair(element, text.split(element.toLowerCase()).size - 1)
Подстроки могут пересекаться, а Ваше решение этого не поддерживает.

2016-12-16 22:53 UTC, onfound commented on src/lesson6/task2/Chess.kt
> +        val result = Square(notation[0] - '`', notation[1] - '0')
![image](https://cloud.githubusercontent.com/assets/20609072/21281097/567d940e-c3fb-11e6-8d3d-45b7c331676b.png)

2016-12-16 23:20 UTC, maximpetrov commented on src/lesson6/task2/Chess.kt
> +        val result = Square(notation[0] - '`', notation[1] - '0')
Это не объясняет, почему вычитается именно ```'`'```

2016-12-17 09:45 UTC, onfound commented on src/lesson6/task2/Chess.kt
> +        val result = Square(notation[0] - '`', notation[1] - '0')
символ '`' имеет код 96 в кодировке ASCII, а следующие за ним символы a, b, c, d, e, f, g, h отличаются кодом соответственно: (96+1), (96+2), (96+3), (96+4), (96+5), (96+6), (96+7), (96+8). При вычитании двух элементов типа char, вычитаются их коды. Поэтому данным действием notation[0] - '`' мы получаем Int ответ для букв a, b, c, d, e, f, g, h  соответственно 1, 2, 3, 4, 5, 6, 7, 8

2016-12-17 10:05 UTC, maximpetrov commented on src/lesson6/task2/Chess.kt
> +        val result = Square(notation[0] - '`', notation[1] - '0')
Вы понимаете, что заменив 96 на ```'`'``` Вы не улучшили читаемость кода, а ухудшили? Символ ```'`'``` не имеет никакого логического отношения к символам букв, и чтобы понять, что произойдёт нужно залезть в ACSII кодировку. Используйте такой символ, чтобы это не требовалось.

2016-12-18 00:38 UTC, maximpetrov requested changes

2016-12-18 00:38 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    for (i in 0..digits.size - 1) {
Я не имел ввиду, что нужно идти от старших цифр к младшим. Я хотел сказать, что вместо вычисления множителя каждый раз с помощью `pow` можно его накапливать.

2016-12-18 00:38 UTC, maximpetrov commented on src/lesson8/task1/Files.kt
> +        result += Pair(element, count)
Всё-таки в map принято через `[]` класть элементы.

2016-12-18 00:38 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    val correct = phone.all { it in "+0123456789-() " } && phone != "" && phone.indexOf('+', 1) == -1 && ((phone.first() == '+' && phone.length > 1) || (phone.first() != '+' && phone.length > 0))
Это Ваше решение направлено на преодоление одного появившегося в тесте нарушения формата, причем даже этот случай Вы обрабатываете не совсем корректно: Вы не учитываете, что `' '` и `'-'` могут появляться в любом месте номера, поэтому Вы посчитаете номер неправильным, если эти символы появятся перед `'+'`.

2016-12-19 07:16 UTC, maximpetrov commented
recheck all

2016-12-19 07:20 UTC, maximpetrov approved these changes

2017-07-26 18:23 UTC, closed without merging