Lesson6.Task1/2 (and one from the 5th)
Kotlin-Polytech/KotlinAsFirst2016 pull request #249
Opened 2016-12-14 20:26 UTC by Nikolay123456789

https://github.com/Nikolay123456789
https://github.com/Nikolay123456789

2016-12-14 20:28 UTC, mglukhikh commented
recheck all

2016-12-14 20:36 UTC, mglukhikh commented
recheck all

2016-12-14 20:54 UTC, mglukhikh requested changes
В целом всё нормально, я вам советую завтра прийти на упражнения и попробовать пройти тестирование. Мои замечания см. ниже

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +   return (m * NOD(m,n)) / n
Использованная вами формула неверна

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Поправьте форматирование

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return false
`if (...) return true else return false` можно заменить на `return ...`. То же можно сделать и здесь.

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val letters = listOf("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y",
Здесь лучше использовать не список из кучи маленьких строк, а одну короткую строку: `"01234...abcd..."`.

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список у вас используется в двух функциях. Перенесите его определение так, чтобы оно было ПЕРЕД функцией `dateStrToDigit`, и вы получите возможность использовать его и там и там, не дублируя.

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        val List = parts.split(" ")
Переменные следует называть с маленькой буквы: `list`

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    } catch (e: Exception) {
Никогда не ловите просто `Exception` -- это вообще любая ошибка. Уточняйте, чего именно вы боитесь. В данном случае это `NumberFormatException` -- его и следует ловить.

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +                i == 0 -> result += results[i].toInt()
Здесь и ниже возможно возникновение `NumberFormatException`, которое вы не ловите. Например, для входной строки `"+"`.

2016-12-14 20:54 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +                (Math.tan(this.angle) - Math.tan(other.angle))
Как этот код будет работать, если один из углов равен пи пополам?

2016-12-14 21:28 UTC, Nikolay123456789 commented on src/lesson3/task1/Loop.kt
> +   return (m * NOD(m,n)) / n
![image](https://cloud.githubusercontent.com/assets/22072863/21201774/502e3a30-c25d-11e6-90eb-ed3d24ae0fe3.png)

вот я это использовал

2016-12-14 21:29 UTC, Nikolay123456789 commented on src/lesson3/task1/Loop.kt
> +   return (m * NOD(m,n)) / n
может быть скобки не правильны?

2016-12-14 23:53 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +   return (m * NOD(m,n)) / n
Я опечатался.

Имелось в виду конечно `(m / NOD(m, n)) * n`

2016-12-15 13:34 UTC, Nikolay123456789 commented on src/lesson4/task1/List.kt
> +    val letters = listOf("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y",
как примерно это сделать?

2016-12-15 14:13 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val letters = listOf("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y",
`val letters = "012...abcd..."`

2016-12-16 20:50 UTC, mglukhikh requested changes
Ещё осталось некоторое количество старых замечаний

2016-12-16 20:50 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val letters = listOf("01234...abcd...")
А подумать? Прежде чем механически копировать?

2016-12-16 20:50 UTC, mglukhikh commented
recheck all

2016-12-16 20:52 UTC, mglukhikh commented
recheck all

2016-12-16 20:55 UTC, mglukhikh commented
recheck all

2016-12-17 13:38 UTC, nikoscharits24 commented on src/lesson4/task1/List.kt
> +    val letters = listOf("01234...abcd...")
не понял,значит это не правильно?

2017-07-26 18:23 UTC, closed without merging