Задача 2 3
Kotlin-Polytech/KotlinAsFirst2016 pull request #25
Opened 2016-09-08 10:32 UTC by Ilya1998

2016-09-08 16:04 UTC, mglukhikh commented
Насколько могу видеть, этот код выдаст ошибку компиляции. И следите, пожалуйста, за выравниванием. Внутри фигурных скобок код должен быть с одинаковым отступом. Закрывающая фигурная скобка должна быть на отдельной строке, с тем же отступом, что и заголовок функции (или тот элемент кода, к которому она относится -- например, if).

2016-09-08 16:16 UTC, maximpetrov commented
recheck assignment

2016-09-15 18:52 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +
Здесь и далее: закрывающая фигурная скобка ставится на отдельной строчке, отступ у всех операторов функции должен быть одинаковым. Например:
```
fun foo(parameter: Int): Int {
    val intermediate = parameter + 1
    val result = 2 * intermediate
    return result
}
```

2016-09-27 16:56 UTC, mglukhikh commented
Две задачи во втором уроке решены с ошибкой (см. сообщения бота). Прошу также исправить замечания в первом уроке. Можете использовать комбинацию клавиш Ctrl+Alt+L для автоматического форматирования кода.

2016-09-27 16:57 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +fun ageDescription(age: Int): String
Фигурная скобка открывается на одной строчке с функцией:
```
fun foo(...): Type {
    // Function text
}
```

2016-09-27 16:58 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +                                                      }
Закрывающая фигурная скобка должна находиться на одном уровне с началом заголовка функции (в данном случае -- без отступа)

2016-09-27 16:58 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX==rookX2)||(kingY == rookY2)) danger2=2
Либо отделяйте знаки операций пробелами, либо нет. Смешивать и то, и другое в одном коде -- дурной тон

2016-09-27 16:59 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else if ((kingX == rookX1)||(kingY == rookY1)) return 1
Одни и те же условия в функции проверяются по несколько раз

2016-09-27 17:02 UTC, Ilya1998 commented
Там не может быть ошибки. Программа проходит тест полностью.

27 Сен 2016 г. 19:56 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:
>
> Две задачи во втором уроке решены с ошибкой (см. сообщения бота). Прошу
также исправить замечания в первом уроке. Можете использовать комбинацию
клавиш Ctrl+Alt+L для автоматического форматирования кода.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2016-09-27 20:15 UTC, mglukhikh commented
И даже несмотря на то, что программа проходит тест полностью, в ней есть ошибки, что и подтверждают более полные тесты бота. В частности, число 1001 определяется

2016-09-29 15:54 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    var danger1 = 0
Весь этот код у вас никогда не будет выполняться, поскольку перед ним обязательно выполниться return. Вероятно, вы забыли удалить первые четыре строчки функции

2016-09-29 15:54 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((((t1 * v1) + (t2 * v2) + (t3 * v3)) / 2) < (t1 * v1)) return ((((t1 * v1) + (t2 * v2) + (t3 * v3)) / 2) / v1)
Здесь следует ввести несколько промежуточных переменных, чтобы код выглядел менее страшно. Например, s1 = t1 * v1.

2016-09-29 15:56 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (c <= a && d >= b) q = (b - a) else
`else if` должны быть на одной строке. Для условий вроде `d>=a && d<=b` используйте лучше `d in a..b`. Кроме этого, советую вам применить здесь конструкцию `when`, с ней код будет читаться лучше.

2016-09-29 15:56 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if ((number % 10 + number / 10 % 10) == (number / 100 % 10 + number / 1000)) return true
`if (x) return true else return false` эквивалентно `return x`

2016-09-29 15:57 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if ((Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) + r1) <= r2) return true
`if (x) return true else return false` эквивалентно `return x`

2016-09-29 15:57 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var fibnach1:Int=1
Явное указания типа не нужно

2016-09-29 15:58 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        if (n == i * (n / i)) {
Для проверки делимости нацело используйте операцию взятия остатка от деления: `n % i == 0` в данном случае.

2016-09-29 15:59 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    for (i in 0..n){
Нельзя ли как-нибудь сократить проверяемый интервал чисел?

2016-09-29 15:59 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var sinus:Double=x
Явное указание типа не нужно

2016-09-29 16:01 UTC, mglukhikh commented
Как видно из сообщений бота, довольно большое количество задач решено неверно. Исправляйте ошибки, и я просмотрю ваше решение заново

2016-10-27 19:59 UTC, mglukhikh commented
recheck all

2016-10-27 20:08 UTC, mglukhikh requested changes
У вас по-прежнему довольно много фактических ошибок и, кроме того, к вам масса замечаний по стилю. Исправьте ошибки и замечания, пожалуйста. Сделайте это ДО того, как начнёте решать новые задачи.

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int {
Пожалуйста, приведите в порядок форматирование кода в этом файле. Можно для этого использовать Ctrl+Alt+L

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +
Это замечание по-прежнему в силе

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return "invalid input"
Подобный код выглядит гораздо более изящно, если использовать when вместо if

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((((t1 * v1) + (t2 * v2) + (t3 * v3)) / 2) < (t1 * v1)) return ((((t1 * v1) + (t2 * v2) + (t3 * v3)) / 2) / v1)
Это замечание по-прежнему в силе

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    var danger1 = 0
Нижняя часть функции сделана хорошо, вот только вы забыли удалить верхнюю часть

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else return 0
Эту функцию прошу переделать аналогично предыдущей

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +                if (c >= a && c <= b && d <= b) q = (d - c) else q = -1
Такое форматирование "лесенкой" недопустимо. Лучше всего здесь использовать конструкцию when.

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
Здесь и далее: `if (x) return true else return false` эквивалентно `return x`. А функцию `foo` из одного `return x` можно записать как `fun foo(...): Type = x`.

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if ((Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) + r1) <= r2) return true
Повторно

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    else return false
Это условие слишком длинное, чтобы адекватно восприниматься, к тому же, оно неверное -- тесты не проходят. Я бы разбил его на несколько if. Или использовал бы when из нескольких строчек. Вам самому так будет проще понять, где ошибка

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        var ns: Int = Math.abs(n)
Тип локальных переменных в Котлине почти никогда указывать не требуется

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var fibnach1:Int=1
Повторно

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        fibnach3=fibnach2+fibnach1
Бардак с пробелами. Нужно так: `fibnach3 = fibnach2 + fibnach1`.

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        if (n == i * (n / i)) {
Повторно

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun maxDivisor(n: Int): Int {
См. предыдущую функцию. К тому же, опять бардак с пробелами (для устранения можно использовать Ctrl+Alt+L)

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return true
Это далеко не самое эффективное решение (и к тому же неверное -- см. тесты бота). Почитайте, какие существуют алгоритмы для проверки на взаимную простоту, и реализуйте один из них

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    for (i in 0..n){
Повторно

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return false
Пожалуйста, не ленитесь ставить пробелы. Читать текст функции в таком виде невозможно

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun center(list: MutableList<Double>): MutableList<Double> = list.map { it - mean(list) }.toMutableList()
В этой функции необходимо изменить исходный список `list`, а не создавать новый

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var length = 0.0
Не слишком удачное название переменной

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    list = factorize(n)
Это правильно, только `factorize` не реализован

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    list = listOf()
Две последних строчки можно объединить в одну

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        if (list[i] > 9) string1 += (87 + list[i]).toChar()
Вместо магических констант вроде "87" следует использовать то, что они реально означают. Подозреваю, что здесь имеется в виду код какого-то символа. Вот этот символ и нужно здесь написать

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        result += (digits[i] * Math.pow(base.toDouble(), ((digits.size - 1) - i).toDouble())).toInt()
Для возведения целого числа в целую степень лучше написать свою функцию `pow`, иначе вы рискуете получить ошибки при округлении

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        else list += ((string1[i]).toInt() - 87)
Убрать магические константы. Кроме этого, здесь можно применить цикл по элементам: `for (char in string1) { ... }`. Кроме этого, не понял смысл переменной `string1` -- чем плоха `str`?

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(number)>eps) {
Подумайте, как ведёт себя это решение при больших `x` -- например, при `x = 100 * PI`. Напишите тест для этого случая -- синус должен равняться 0, точность возьмите `1e-10`. Подумайте, как добиться увеличения точности вычислений, используя известные вам свойства синуса. То же для функции косинус

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            output = fibnach3 / 10
Здесь явная ошибка -- результатом функции должна быть цифра, от 0 до 9.

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var fibnach3:Int=0
Не надо писать повсюду типы. Если переменная равна 0, её тип очевиден и для читателя, и для компилятора

2016-10-27 20:08 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return output
Реализация этой функции явно не закончена.

2016-11-21 08:01 UTC, mglukhikh requested changes
Нашёл два устаревших замечания. Однако, во вкладке Files Changed осталось большое количество неисправленных замечаний по урокам 2-4, прошу их исправить. До их исправлений задачи 5-го урока проверяться и засчитываться не будут.

2016-11-21 08:01 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int {
Исправлено

2016-11-21 08:01 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var length = 0.0
Исправлено

2016-11-21 08:02 UTC, mglukhikh commented
Обратите внимание также на фактические ошибки в уроках 2-5, которые выдаёт вам бот

2016-11-23 09:26 UTC, mglukhikh commented
Пожалуйста, посмотрите на вкладку Files Changed и исправьте имеющиеся там замечания. Кроме этого, обращаю внимание на то, что тесты некоторых задач из 3-го и 4-го уроков не проходят -- смотрите последний отчёт бота.

2016-11-24 16:20 UTC, Ilya1998 commented
Не могу найти папку files change, не подскажете где ее искать?

23 Ноя 2016 г. 12:26 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:

> Пожалуйста, посмотрите на вкладку Files Changed и исправьте имеющиеся там
> замечания. Кроме этого, обращаю внимание на то, что тесты некоторых задач
> из 3-го и 4-го уроков не проходят -- смотрите последний отчёт бота.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-262466355>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AchjQ7ee_u0L6OAj1WK5-C-NvTEyks5rBAa_gaJpZM4J32D3>
> .
>

2016-11-24 16:29 UTC, mglukhikh commented
Это не папка, это закладка вверху этой страницы (рядом с Conversation и Commits). https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25/files.

2016-12-18 16:44 UTC, Ilya1998 commented
Здравствуйте. Подскажите пожалуйста,  обязательно ли делать 8 лессон для
зачета? И хотел спросить какая оценка выходит у меня на данный момент,
интернсуюсь чттбы успеть что то поправить.
Это Шавкунов Илья из группы 13531/1
Заранее Спасибо

8 Сен 2016 г. 19:04 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:

> Насколько могу видеть, этот код выдаст ошибку компиляции. И следите,
> пожалуйста, за выравниванием. Внутри фигурных скобок код должен быть с
> одинаковым отступом. Закрывающая фигурная скобка должна быть на отдельной
> строке, с тем же отступом, что и заголовок функции (или тот элемент кода, к
> которому она относится -- например, if).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-245648331>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6ATG4C0h85SfsXW2co2C8YyWpFDRRks5qoDIXgaJpZM4J32D3>
> .
>

2016-12-18 17:50 UTC, mglukhikh commented
recheck all

2016-12-18 17:57 UTC, Ilya1998 commented
Ну у меня получается 7 уроков + 10 сложных заданий, и еще сейчас я пытаюсь
исправить ошибки из вкладки files change.
По идее здесь 4 выходит. Но с какого урока считаются сложные и средние
задачи?


2016-12-18 20:50 GMT+03:00 Mikhail Glukhikh <notifications@github.com>:

> recheck all
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-267835471>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AUpzGbOTMQPmoy8uEScm4xhjb4Ksks5rJXJWgaJpZM4J32D3>
> .
>

2016-12-18 18:12 UTC, mglukhikh commented
Нет, восьмой урок для зачёта делать не нужно.

2016-12-18 18:13 UTC, mglukhikh commented
Вы явно не запускали на своём компьютере тесты 7-го урока. Прошу вас написать минимум по одному тесту для каждой решённой вами задачи и убедиться в их работоспособности.

2016-12-18 18:16 UTC, Ilya1998 commented
Спасибо. А с какого урока идет отсчет сложных и средних задач?

18 декабря 2016 г., 21:13 пользователь Mikhail Glukhikh <
notifications@github.com> написал:

> Вы явно не запускали на своём компьютере тесты 7-го урока. Прошу вас
> написать минимум по одному тесту для каждой решённой вами задачи и
> убедиться в их работоспособности.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-267836752>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AfvG2HvbzhxU75SJFPpfZSaEIOzVks5rJXfbgaJpZM4J32D3>
> .
>

2016-12-18 18:17 UTC, mglukhikh commented
Так что пока получается максимум "3". Кроме этого, у вас масса неработающих тестов (см. отчёт бота), и соответствующие задачи следует исправить. Бот, кстати, насчитал у вас 8 сложных задач, а не 10.

2016-12-18 18:17 UTC, mglukhikh commented
Для контр-примеров бота прошу добавлять тесты к соответствующей задаче и проверять их прохождение на локальном компьютере.

2016-12-18 18:18 UTC, mglukhikh commented
Отсчёт задач идёт с начала

2016-12-18 19:15 UTC, Ilya1998 commented
А можно ли завтра вечером прислать еще задачи? А то не успеваю уже сегодня.


2016-12-18 21:18 GMT+03:00 Mikhail Glukhikh <notifications@github.com>:

> Отсчёт задач идёт с начала
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-267836992>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AfrOGOCvuy8hVG1aJmr2CyWqA_kNks5rJXjqgaJpZM4J32D3>
> .
>

2016-12-22 09:20 UTC, Ilya1998 commented
Подскажите пожалуйста, у меня же достаточно задач решено для зачета. Почему
тогда мне сказали решать 8 урок если вы говорили что для зачета 8 уроков
можно не решать?



8 сентября 2016 г., 19:04 пользователь Mikhail Glukhikh <
notifications@github.com> написал:

> Насколько могу видеть, этот код выдаст ошибку компиляции. И следите,
> пожалуйста, за выравниванием. Внутри фигурных скобок код должен быть с
> одинаковым отступом. Закрывающая фигурная скобка должна быть на отдельной
> строке, с тем же отступом, что и заголовок функции (или тот элемент кода, к
> которому она относится -- например, if).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-245648331>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6ATG4C0h85SfsXW2co2C8YyWpFDRRks5qoDIXgaJpZM4J32D3>
> .
>

2017-01-12 14:21 UTC, Ilya1998 commented
Подскажите пожалуйста. Что мне нужно донести 16 для того чтобы получить
зачет? Просто вы говорили что для зачета у меня все есть но на практике мне
сказали решать 8  урок.


22 декабря 2016 г., 12:20 пользователь Илья Шавкунов <
shavkunov1198@gmail.com> написал:

> Подскажите пожалуйста, у меня же достаточно задач решено для зачета.
> Почему тогда мне сказали решать 8 урок если вы говорили что для зачета 8
> уроков можно не решать?
>
>
>
> 8 сентября 2016 г., 19:04 пользователь Mikhail Glukhikh <
> notifications@github.com> написал:
>
>> Насколько могу видеть, этот код выдаст ошибку компиляции. И следите,
>> пожалуйста, за выравниванием. Внутри фигурных скобок код должен быть с
>> одинаковым отступом. Закрывающая фигурная скобка должна быть на отдельной
>> строке, с тем же отступом, что и заголовок функции (или тот элемент кода, к
>> которому она относится -- например, if).
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-245648331>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AVA6ATG4C0h85SfsXW2co2C8YyWpFDRRks5qoDIXgaJpZM4J32D3>
>> .
>>
>
>

2017-01-12 14:47 UTC, mglukhikh commented
Вам на практике всё прекрасно сказали. Раз непонятно, повторяю: ввиду того, что многие решения задач в вашем проекте являются точными копиями решений других студентов, для получения зачёта вам необходимо решить несколько дополнительных задач из 8-го урока. Минимальное количество задач: три. Решения должны быть выполнены САМОСТОЯТЕЛЬНО.

2017-01-12 14:49 UTC, mglukhikh commented
Если вы хотите получить зачёт 16-го, решить задачи надо не позднее 15-го.

2017-01-13 08:45 UTC, Ilya1998 commented
Подскажите пожалуйста, мне из 8 лессона решать таск 1 или таск 2?


2017-01-12 17:49 GMT+03:00 Mikhail Glukhikh <notifications@github.com>:

> Если вы хотите получить зачёт 16-го, решить задачи надо не позднее 15-го.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-272182040>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AWDi7yehcNbyoa7VBeMji0xrY_pHks5rRj1zgaJpZM4J32D3>
> .
>

2017-01-13 09:20 UTC, mglukhikh commented
В task2 решать нечего, он только из примеров. Так что task1

2017-01-14 16:27 UTC, Ilya1998 commented
Помогите пожалуйста. В IDEA у меня в восьмом лессоне показана
синтаксичечкая ошибка. Я ее никак найти не могу и не знаю откуда она, я там
ничего не менял. Из за этого не могу отправить вам задачи. Можно как нибудь
это исправить или вам просто решение задачи прислать не в программе


2017-01-13 12:20 GMT+03:00 Mikhail Glukhikh <notifications@github.com>:

> В task2 решать нечего, он только из примеров. Так что task1
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-272397243>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AUTtysmVc9LgYbLGv4ohS6-VQeExks5rR0HwgaJpZM4J32D3>
> .
>

2017-01-14 19:45 UTC, mglukhikh commented
Unresolved reference: maxLength, смотрите строку 146 урока 8

2017-01-15 17:10 UTC, mglukhikh commented
Программа по-прежнему не компилируется. Приходите завтра в 14-00 на зачёт и исправляйте свои ошибки.

2017-01-15 17:23 UTC, Ilya1998 commented
То есть у меня есть зачет?

15 Янв 2017 г. 20:10 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:

> Программа по-прежнему не компилируется. Приходите завтра в 14-00 на зачёт
> и исправляйте свои ошибки.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-272708701>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AR1Xn7qrwF-JHcAdfZIGCIi6vtKCks5rSlMBgaJpZM4J32D3>
> .
>

2017-01-15 18:37 UTC, Ilya1998 commented
И я могу в 16:00 экзамен писать?

15 Янв 2017 г. 20:23 пользователь "Илья Шавкунов" <shavkunov1198@gmail.com>
написал:

> То есть у меня есть зачет?
>
> 15 Янв 2017 г. 20:10 пользователь "Mikhail Glukhikh" <
> notifications@github.com> написал:
>
>> Программа по-прежнему не компилируется. Приходите завтра в 14-00 на зачёт
>> и исправляйте свои ошибки.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-272708701>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AVA6AR1Xn7qrwF-JHcAdfZIGCIi6vtKCks5rSlMBgaJpZM4J32D3>
>> .
>>
>

2017-01-18 07:57 UTC, Ilya1998 commented
Михаил Игоревич,  а где я могу найти почту Гагарского или Петрова, чтобы
спросить у них, могу ли я зачетную задачу писать уже?
Заранее спасибо.

8 Сен 2016 г. 19:04 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:

> Насколько могу видеть, этот код выдаст ошибку компиляции. И следите,
> пожалуйста, за выравниванием. Внутри фигурных скобок код должен быть с
> одинаковым отступом. Закрывающая фигурная скобка должна быть на отдельной
> строке, с тем же отступом, что и заголовок функции (или тот элемент кода, к
> которому она относится -- например, if).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-245648331>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6ATG4C0h85SfsXW2co2C8YyWpFDRRks5qoDIXgaJpZM4J32D3>
> .
>

2017-01-19 06:44 UTC, mglukhikh commented
У вас проект даже не собирается. Какая ещё зачётная задача? Налаживайте сборку проекта, добивайтесь, чтобы проходили тесты, а уже потом будем смотреть.

2017-01-19 08:33 UTC, Ilya1998 commented
Просто вы говорили что нужно минимум три задачи из 8 урока. Так три задачи
как раз у меня есть. Вот я и спрашиваю.

19 Янв 2017 г. 9:44 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:

> У вас проект даже не собирается. Какая ещё зачётная задача? Налаживайте
> сборку проекта, добивайтесь, чтобы проходили тесты, а уже потом будем
> смотреть.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-273694720>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6Ac9_Lp8RN0u6-h_tv4ykvJgK7Tdnks5rTwY2gaJpZM4J32D3>
> .
>

2017-01-19 10:01 UTC, mglukhikh commented
В настоящий момент у вас 0 задач из восьмого урока. Поскольку ваш код не компилируется.

2017-01-19 10:03 UTC, Ilya1998 commented
Но они проходят тесты. А то что присылает бот я не понимаю просто.

19 Янв 2017 г. 13:01 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:

> В настоящий момент у вас 0 задач из восьмого урока. Поскольку ваш код не
> компилируется.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-273730624>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AUOBKAMkj7gjqeQzl2FrDYLyqo9mks5rTzSKgaJpZM4J32D3>
> .
>

2017-01-19 10:07 UTC, mglukhikh commented
1) Не верю, что у вас chooseLongestChaoticWord проходит тесты, поскольку ваша реализация не делает вообще ничего.
2) Зачем вы удалили printMultiplicationProcess / printDivisionProcess? Верните их на место.

2017-01-19 10:09 UTC, Ilya1998 commented
Ну вот именно эта задача не проходит. Но перед ней еще три идут которые
проходят.

19 Янв 2017 г. 13:07 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:

>
>    1. Не верю, что у вас chooseLongestChaoticWord проходит тесты,
>    поскольку ваша реализация не делает вообще ничего.
>    2. Зачем вы удалили printMultiplicationProcess / printDivisionProcess?
>    Верните их на место.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-273731820>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6AbW4VKE-fugb4yqJSbKyhR-ILUePks5rTzXHgaJpZM4J32D3>
> .
>

2017-01-22 09:17 UTC, Ilya1998 commented
Ну вот, три задачи у меня есть. Что мне делать дальше?

8 Сен 2016 г. 19:04 пользователь "Mikhail Glukhikh" <
notifications@github.com> написал:

> Насколько могу видеть, этот код выдаст ошибку компиляции. И следите,
> пожалуйста, за выравниванием. Внутри фигурных скобок код должен быть с
> одинаковым отступом. Закрывающая фигурная скобка должна быть на отдельной
> строке, с тем же отступом, что и заголовок функции (или тот элемент кода, к
> которому она относится -- например, if).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/25#issuecomment-245648331>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA6ATG4C0h85SfsXW2co2C8YyWpFDRRks5qoDIXgaJpZM4J32D3>
> .
>

2017-07-26 18:24 UTC, closed without merging