Седьмой урок Первый таск
Kotlin-Polytech/KotlinAsFirst2016 pull request #250
Opened 2016-12-15 22:06 UTC by GlowBlood

А еще я случайно отправила какую-то дичь из 6го урока, но там у меня все зачтено, поэтому смотреть на него не нужно

2016-12-15 22:09 UTC, GlowBlood commented
о

2016-12-15 22:09 UTC, GlowBlood commented
recheck all

2016-12-15 22:11 UTC, GlowBlood commented
Почему-то как раз изменения 7го урока бот не проверил((

2016-12-16 06:44 UTC, mglukhikh commented
recheck all

2016-12-16 06:45 UTC, mglukhikh commented
Бот на автомате проверяет изменения только из последнего коммита

2016-12-16 06:45 UTC, mglukhikh commented
recheck all

2016-12-16 06:47 UTC, mglukhikh commented
В уроке 7.1 в целом всё в порядке, только полный бардак с форматированием и вы забыли определить функцию hashCode(). У JVM-программистов есть важное правило, постарайтесь его как можно быстрее запомнить: если определил в классе equals() -- определи и hashCode(). Подробности я рассказывал на лекциях, в 7-м разделе пособия они тоже есть. А дальше вы можете приступать к уроку 7.2.

2016-12-16 07:01 UTC, mglukhikh commented
Кстати, в функции `equals` вы использовали волшебную конструкцию `if (...) return true else return false` которую можно записать проще.

2016-12-16 07:02 UTC, mglukhikh commented
И тесты вашего проекта почему-то не завершились, надеюсь, это случайность. Попробуем ещё раз.

2016-12-16 07:02 UTC, mglukhikh commented
recheck all

2016-12-16 07:15 UTC, mglukhikh commented
recheck all

2016-12-16 07:39 UTC, mglukhikh requested changes
Пересмотрел перед зачётом весь проект, поскольку обнаружил заметные проблемы с оформлением кода. Впрочем, исправляется всё это быстро. Хуже то, что тесты вашего проекта, похоже, зависают, а значит, как минимум в одной из задач осталась серьёзная ошибка (бесконечное зацикливание или просто очень долгое выполнение). Я вас попрошу запустить локально на компьютере тесты всех семи первых уроков и посмотреть, завершаются они или нет. Если тесты какого-либо урока не завершаются, посмотрите, на какой задаче происходит зависание и исправьте её. Если локально все тесты у вас проходят -- напишите мне.

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    val ms = minutes*60
Примените к этому файлу авто-форматирование, пожалуйста (Ctrl+Alt+L). Отсутствуют пробелы вокруг знаков операций.

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return (initial*(1+0.01*percent))*(1+0.01*percent) + 0.01*percent*(initial*(1+0.01*percent))*(1+0.01*percent)
Это выражение нельзя как-нибудь упростить? Есть же элементарные правила алгебры, которые вы, надеюсь, знаете.

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((age % 10 in 2..4)&& (age%100 !in 10..19)) return "$age года"
К этому файлу тоже стоит применить Ctrl+Alt+L, пробелы, как видите, всюду стоят по-разному.

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val S_half =(s1+s2+s3)/2
Эта переменная названа не по Code Style, переименуйте её (Shift+F6 в IDEA). Напоминаю, что имена переменных в Kotlin / Java принято писать через `camelCase`.

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val worning1 = (rookX1 == kingX) || (rookY1 == kingY)
Если это предупреждение, то `warning`. А вообще, скорее угроза `threat`.

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val eq_rook =  ((rookX == kingX) || (rookY == kingY))
Тоже название не по Code Style

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val mid_cat = (a+b+c) - hypo - lit_cat
Опять-таки названия не по Code Style.

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +        (number/1000 + (number/100)%10)==(number%10 + (number%100)/10)
И здесь Ctrl+Alt+L вам поможет

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    val longth = max(max(a, b), c)
`length`

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    val deepth = min(min(a, b), c)
`depth`

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        result = result*x
И здесь примените Ctrl+Alt+L

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun intPow (a: Int, b:Int): Int {
Вы не поясните, в чём отличие этой функции от предыдущей? Возможно, одну из них стоит удалить?

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return false
Волшебное выражение `if (...) return true else return false` эквивалентно? В случае проблем загляните в лекцию Марата Халимовича о 50 оттенках ошибки :) Она есть в слайдах

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +if ((0 >= height) || (0 >= width)) throw er
И на этом файле стоит применить Ctrl+Alt+L, всё поехало

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    for (colomn in 0..width - 1) { matrix[row, colomn] = e}}
Такая запись в программах не используется, поскольку очень плохо читается. 

```
for (...) {
    for (...) {
        ...
    }
}
```

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    for (colomn in 0..width - 1) { matrix[row, colomn] = e}}
Кроме этого, инициализация элементов матрицы здесь в принципе не нужна, так как она уже сделана в блоке `init` в `MatrixImpl`.

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    {
`init {` и далее по тексту

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    override fun set(row: Int, column: Int, value: E) {  list[width*row + column]  = value }
Тело функции на отдельной строке, закрывающая фигурная скобка тоже

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    override fun set(cell: Cell, value: E) { list[cell.column + cell.row*width] = value }
Тело функции на отдельной строке, закрывающая фигурная скобка тоже

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            else return false
`if (...) return true else return false`

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    while (newN !== 0) {
`!=`. Применять сравнение ссылок очень опасно для чисел, поскольку для чисел ссылок может в принципе не быть и, строго говоря, нигде не сказано, как такое сравнение для них работает. Есть маленькая вероятность, что тесты зависают именно из-за этого (впрочем, скорее всего, это не так).

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
Здесь и в следующей функции лучше применить цикл по элементам, избегая индексации. Всё дело в том, что для некоторых видов списков индексация занимает много времени. Кроме этого, такой код проще в понимании

```
for (elem in v) {
    summa += elem * elem
}
```

2016-12-16 07:39 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    }
См. выше

2016-12-16 07:51 UTC, mglukhikh commented
Вообще, в целом, я вам советую ориентироваться на итоговую оценку "4". Чтобы её на зачётной неделе получить, вам следует:

1) Исправить замечания по оформлению
2) Разобраться, где у вас зависают тесты
3) Решить что-нибудь из урока 7.2
4) Убедиться, что у вас решено 4 сложных задачи (из всех уроков в совокупности), если это не так -- дорешать необходимое их число
5) Пройти тестирование на зачётной неделе

2016-12-16 16:40 UTC, GlowBlood commented
Ого
С тестами у меня действительно возникли проблемы, причем видимо дело в том, что я просто на что-то не то нажала. После того как отправила шестой урок и Вы мне его закрыли (все с тестами было ок), открыла второй таск, начала смотреть, еще сделать ничего не успела, а в файле (окне?) тестов каждая строчка подчеркивалась красной волнистой линией, некоторые слова - красным цветом. Попыталась что-то с этим сделать, спросить у одногруппников, помочь мне никто не смог, а принести компьютер не имела возможности, так что решила пока оставить 6ур таск2 и делать 7. С тестами седьмого урока все было норм, но проверка не запускалась, так как ошибка была в тестах 6го урока.

2016-12-16 16:43 UTC, GlowBlood commented
Я так понимаю, что мне нет смысла исправлять оформление, пока я не разберусь с тестами?

2016-12-16 17:16 UTC, GlowBlood commented
Еще происходит следующая история:
![image](https://cloud.githubusercontent.com/assets/22037087/21271533/6606c014-c3cc-11e6-868f-97461672aa53.png)
весь файл вроде в порядке, нигде ничем больше не подчеркивает, только название, а запускать тесты (ЛЮБЫЕ) отказывается

2016-12-16 17:17 UTC, GlowBlood commented
Таким образом, мне ни один тест не проверить, не свои исправления

2016-12-16 20:19 UTC, mglukhikh commented
Попробуйте заново скачать проект на свой компьютер (в другую директорию) и открыть его в IDEA. Действуйте по инструкции в учебном пособии. Может быть, это поможет. Вообще, я хотел бы посмотреть, как вам удалось такого результата добиться, но сейчас мало времени, так что важнее наладить возможность работать с проектом для вас.

2016-12-16 20:21 UTC, mglukhikh commented
Если самой будет никак не разобраться -- приходите в понедельник в 14-00 на занятия с 3-й группой и попросите преподавателей вам помочь.

2016-12-16 20:35 UTC, GlowBlood commented
Большое спасибо

2016-12-16 20:59 UTC, mglukhikh commented
recheck all

2016-12-16 21:09 UTC, mglukhikh commented
Могу вас поздравить, тесты прошли (похоже, это была временная проблема с ботом всё-таки). Кроме этого, четыре сложные задачи у вас уже есть. Так что пунктов остаётся не так уж много.

2016-12-18 16:41 UTC, mglukhikh requested changes
Всё нормально, за исключением одной ошибки. Жду её исправления и решения какой-либо задачи из урока 7.2 (в принципе, и то и другое может подождать до среды, когда мы встретимся на упражнениях). Совет: не выбирайте самую простую задачу, такой путь только кажется самым правильным.

2016-12-18 16:41 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return initial * pow((1 + percent / 100).toDouble(), 3.0)
`percent / 100` даст не тот результат, на который вы рассчитываете. Поэтому тесты функции перестали проходить

2016-12-18 16:42 UTC, mglukhikh commented
Пока ставлю mediocre (3), но позже оценка может быть повышена до good (4).

2016-12-18 16:43 UTC, mglukhikh commented
Не забывайте только, что в среду вам писать тест, поэтому с учебным проектом надо бы закончить до упражнений.

2016-12-19 16:24 UTC, GlowBlood commented
Спасибо, постараюсь исправить сегодня

2016-12-20 16:54 UTC, GlowBlood commented
Проверьте, пожалуйста ^_^
Дико извиняюсь, что так поздно

2016-12-20 17:19 UTC, mglukhikh commented
Ага. Ну что ж, удачи вам завтра на тестировании

2016-12-20 17:19 UTC, closed without merging

2016-12-20 17:43 UTC, GlowBlood commented
Спасибо!))