NanXiang Wang
Kotlin-Polytech/KotlinAsFirst2016 pull request #251
Opened 2016-12-16 08:00 UTC by NanXiang1998116

2016-12-16 08:05 UTC, mglukhikh commented
Это отлично, только ваша программа не компилируется. Исправляйте ошибку, и тогда будем смотреть. Убедитесь, что у вас на компьютере проходят тесты 5-го и 6-го уроков.

2016-12-16 08:29 UTC, mglukhikh commented
recheck all

2016-12-16 08:30 UTC, mglukhikh commented
recheck all

2016-12-16 08:36 UTC, mglukhikh commented
Обратите пока внимание на неработающие тесты. Попробуйте починить ошибочные решения самостоятельно.

2016-12-16 11:37 UTC, mglukhikh commented
recheck all

2016-12-16 12:01 UTC, mglukhikh commented
Поправьте ещё неработающий тест в первом уроке, пожалуйста

2016-12-16 12:14 UTC, NanXiang1998116 commented
Все 12 тестов работают.

2016-12-16 14:18 UTC, mglukhikh requested changes
Посмотрел, написал замечаний. Про ваш вопрос по поводу тестирования мы подумаем и решим что-нибудь, раз уж 6 уроков у вас более-менее сделано. Постараюсь написать вам в понедельник.

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val month = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Два одинаковых списка в этой и следующей функции. Такой список объявляется один раз на верхнем уровне, то есть до функции `dateStrToDigit`.

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (parts[0].toInt() > 31 || parts[0].toInt() <= 0) return ""
Вы в этой функции трижды вызываете `parts[0].toInt()`. Заведите под него переменную

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val Month = listOf<String>("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Про этот список см. выше

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val month = listOf("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
Попробуйте обойтись без этого списка вообще

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val phonenumber = phone.filter { it != ' ' && it != '-' }
`camelCase`: `phoneNumber`

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    if (phonenumber.matches(Regex("""(\(|\)|\d|\+)*"""))) return phonenumber.filter { it in '0'..'9' || it == '+' }
Несмотря на то, что тесты проходят, этот регэкс верен не для всех случаев. Добавьте тест для номера `"2 + 2"`

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +                val distance2 = Math.sqrt(sqr(points[i].x - points[j].x) + sqr(points[i].y - points[j].y))
У вас уже есть функция для расчёта расстояния между точками

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +    val y3 = Math.min(y1, y2) + (Math.max(y1, y2) - Math.min(y1, y2)) / 2.0
А с `x3` и `y3` точно нужно так сложно? Если да, то зачем?

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val c: Double = Math.tan(angle) - Math.tan(other.angle)/*k1-k2*/
Что будет, если какой-нибудь из углов равен пи пополам? И зачем вы вдруг повсюду стали писать тип?

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        val columnlist = listOf("a", "b", "c", "d", "e", "f", "g", "h")
Здесь лучше просто строку: `"abcdefgh"`

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        val rowlist = listOf<Int>(1, 2, 3, 4, 5, 6, 7, 8)
А этот список вообще не нужен

2016-12-16 14:18 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        (start.column % 2) != (end.column % 2) && (start.row % 2) == (end.row % 2) -> return -1
Подумайте, как записать эти два условия короче. Hint: на Boolean тоже можно использовать `==`

2016-12-18 16:57 UTC, mglukhikh requested changes
Оставшиеся замечания в принципе незначительны (хотя один тест не проходит). В принципе, на "3" вы в этом семестре наработали, но надо пройти тестирование, если вы хотите получить эту оценку без экзамена (на более высокую оценку надо решать задачи из следующих уроков). Поскольку вы сейчас не мобильны, могу предложить следующий вариант: я в четверг 22 декабря в 12:00 напишу вам на ваш e-mail задание на тестирование, вы не позднее 14:00 в тот же день пришлёте мне его решение, тоже на e-mail. Напишите мне, устраивает ли вас "3" и устраивает ли вас такой вариант с тестированием (напоминаю, что проходить его необязательно, но если без него, то надо будет 16 января сдавать экзамен).

2016-12-18 16:57 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        (!start.inside() || !end.inside() || start.column == 0 || start.row == 0 || end.column == 0 || end.row == 0) -> throw  IllegalArgumentException()
Добавьте тест, предложенный ботом `start = (8,0), end = (8,0)` и исправьте поведение функции для этого случая. Ожидаемый результат -- `IllegalArgumentException`, в тесте можно убедиться в том, что оно приходит, поймав его.

2016-12-18 16:57 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        (start == end) -> return 0
Вы уже написали `return` перед `when`, здесь не нужно его повторять. Просто 0.

2016-12-18 16:57 UTC, mglukhikh commented on src/lesson6/task2/Chess.kt
> +        val ColumnList = "abcdefgh"
С маленькой буквы

2016-12-18 16:57 UTC, mglukhikh commented on src/lesson6/task1/Geometry.kt
> +        val c: Double = Math.tan(angle) - Math.tan(other.angle)/*k1-k2*/
Этот вопрос и замечание пока в силе

2017-07-26 18:23 UTC, closed without merging