completed 1..8
Kotlin-Polytech/KotlinAsFirst2016 pull request #254
Opened 2016-12-18 18:41 UTC by gregismypepper

completed 1..8

2016-12-18 20:49 UTC, mglukhikh commented
Здравствуйте, мы очень рады вас видеть в конце семестра. Существуют ли какие-то причины, по которым вы весь семестр ничего не делали?

2016-12-18 23:51 UTC, gregismypepper commented
Я закончил теперь и у меня еще больше шести часов в запасе - пунктуально. Я извиняюсь за свое отсутствие посещения уроков и признаю, что уважительной причины у меня нет. Дома я работал, однако ошибочно пологал, что вложенные тесты считаются исчерпывающими. Я вас видел не часто, но ваши письменные лекции, сколько мало их небыло, мне честно понравились (кроме матрицы), благодарю.

2016-12-19 08:53 UTC, mglukhikh commented
recheck all

2016-12-19 08:55 UTC, mglukhikh commented
Рад, что вам понравились лекции. Однако, должен вас уведомить, что у вас стоят три двойки за сентябрь, октябрь, и ноябрь, так что вам придётся изрядно потрудиться теперь, чтобы получить хотя бы "зачёт". В четверг в 12-00 ждём вас на занятиях, проверять ваше творчество мы будем позже.

2016-12-28 10:34 UTC, mglukhikh requested changes
Написал вам разных замечаний по первым пяти урокам. Попробуйте их исправить до 13 января.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return secondsPassed
Здесь и в двух следующих функциях можно (и нужно) использовать синтаксис с expression body. Незачем вводить вспомогательные переменные просто ради их наличия:

```
fun foo(...): Type = ...
```

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    }
Поясните мне, пожалуйста, смысл всей этой сложной логики в комментарии

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return (((initial + (initial * percent / 100.0)) + (initial + (initial * percent / 100.0)) * percent / 100.0) + (((initial + (initial * percent / 100.0)) + (initial + (initial * percent / 100.0))
Попробуйте обойтись без повторения одного и того же выражения трижды

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    } else return "Error"
Функция не проходит тесты, например, для age = 1. Кроме этого, количество вариантов здесь можно значительно сократить, попробуйте над этим подумать. В частности (в качестве подсказки), возраст в интервале от 1 до 99 обрабатывается точно так же, как и от 101 до 199.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    }
Здесь лучше не увеличивать whichIsHypotenuse, а просто присваивать ему значение 1, 2 или 3.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((a == b) || (b == c) || (a == c)) return 0
Равнобедренный треугольник не обязан быть остроугольным. Пример: a = b = 2, c = 3.9.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (whichIsHypotenuse == 1) {
В подобных местах лучше использовать `when (whichIsHypotenuse)`

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return 2
Треугольник здесь свободно может оказаться остроугольным. Например: a = 2, b = 2.1, c = 2.2.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return -1
Функция не проходит тесты, см. пример бота

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return encompassed == 4
Так тоже можно, но я бы здесь использовал логическое И -- оператор `&&`.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +return false
Поехало форматирование

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if (n <= 9) return 1
Это условие работает неверно для отрицательных чисел

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        result = fib(n - 2) + fib(n - 1)
Рекурсивное определение напрашивается, но попробуйте подумать, сколько раз вызовет саму себя функция `fib` при, например, `n = 10` и к каким проблемам это может приводить. Из-за этих проблем у вас не проходит тесты `fibSequenceDigit`.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Подобный алгоритм вынужден перебрать массу бессмысленных вариантов. Почитайте про известные алгоритмы определения наименьшего общего кратного.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var N2 = n
По Java Code Style, который используется и в Котлине, переменные не следует называть с большой буквы. Подобные имена резервируются для типов.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        result += (N2 % 10 * pow(10.0, count.toDouble()))
Для целочисленных задач лучше не использовать вещественные функции, чтобы избежать возможных проблем с округлением. Напишите свою функцию `pow` с целыми параметрами и используйте её.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return result.toInt() / 10
Подобный трюк может привести к переполнению для десятизначных n, что он, судя по всему, и делает. Смотрите контр-пример бота.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return (result.toInt() / 10) == n
Незачем второй раз переписывать `revert`, её можно просто вызвать

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var N = n
Большая буква

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        result += printLastStringElement(N)
Здесь лучше использовать готовую функцию `last()` на строке

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        N = rmLastStringElement(N)
А здесь готовую функцию `dropLast()` на строке

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        result = printFirstStringElement(log)
`log,first()` или `log[0]`

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..v.size - 1) {
В случаях, когда `i` непосредственно вам не нужно, а нужно только `v[i]`, следует использовать перебор элементов, а не индексов:

```
for (elem in v) {
    result += elem * elem
}
```

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        result += a[i]*b[i]
Не хватает пробелов

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            if ((foo % i) == 0) {
Здесь не учтена возможность повторения множителя (см. контр-пример бота)

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (n % 10 == 9) ones = "IX"
Для таких целей программисты придумали списки

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if ((n % 100 >= 90) && (100 > n % 100)) tens = "XC"
И для таких тоже

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if ((n % 1000 >= 900) && (1000 > n % 1000)) hundreds = "CM"
И для таких -- тоже

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    if (n % 10 == 9) one = "девять"
И здесь тоже нужен список

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (parts[1] == "декабря") month = "12"
Здесь следует использовать список названий месяцев и `indexOf`

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    try {day += parts[0].toInt()} catch (e: Exception) {return ""}
Не нужно писать всё в одну строку, соблюдайте правила выравнивания. Кроме этого, никогда не ловите просто `Exception` -- нужно указывать конкретный тип исключения, которого вы боитесь, в данном случае -- `NumberFormatException`. В просто `Exception` входят и такие типичные ошибки программиста, как выход за границу массива, и, ловя его, вы рискуете их пропустить.

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if (parts[1].toInt() == 12) monthName = "декабря"
А здесь следует индексировать тот же список названий месяцев

2016-12-28 10:34 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    return day.toString() + ' ' + monthName + ' ' + year.toString()
Здесь лучше использовать строковые шаблоны: `return "$day $monthName $year"`. Это банально короче

2016-12-28 10:35 UTC, mglukhikh commented
Все имеющиеся замечания можно просмотреть на вкладке Files Changed.

2017-07-26 18:23 UTC, closed without merging