Lesson 7 t1, t2
Kotlin-Polytech/KotlinAsFirst2016 pull request #255
Opened 2016-12-18 22:55 UTC by elkaties

2016-12-19 08:56 UTC, mglukhikh commented
recheck all

2016-12-19 08:57 UTC, mglukhikh commented
recheck all

2016-12-19 09:05 UTC, mglukhikh commented
recheck all

2016-12-19 09:06 UTC, mglukhikh requested changes
7-й урок пока что не могу вам зачесть, так что оценка за семестр получается "3".

2016-12-19 09:06 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +            matrix[row, column] = e
Здесь заполнять матрицу не нужно -- это уже сделано в блоке `init` ниже

2016-12-19 09:06 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?) = other is MatrixImpl<*> && height == other.height && width == other.width
При таком сравнении у вас все матрицы одного размера будут равными. Необходимо сравнивать также элементы.

2016-12-19 09:06 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +
И где `toString()`?

2016-12-19 09:06 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +        while (true) {
Форматирование. Перед проверкой этой задачи необходимо исправить `equals`

2016-12-19 12:38 UTC, elkaties commented on src/lesson7/task1/Matrix.kt
> +            matrix[row, column] = e
Он все равно ругается, если выкинуть заполнение матрицы

2016-12-20 19:07 UTC, mglukhikh commented
Сейчас всё хорошо, разве что при таком `MatrixImpl.toString()` вы не отличите ряды от колонок. И я не понял, кто именно и в какой момент ругается, если выкинуть заполнение матрицы. Но это детали -- главное, у вас тестирование так и не написано, а значит, экзамен придётся сдавать.

2016-12-21 17:09 UTC, closed without merging