some lessons
Kotlin-Polytech/KotlinAsFirst2016 pull request #262
Opened 2016-12-22 09:04 UTC by DavitGrigoryan

2016-12-22 11:42 UTC, mglukhikh commented
recheck all

2016-12-22 11:43 UTC, mglukhikh commented
recheck all

2016-12-22 11:48 UTC, mglukhikh commented
PR ваш мы как-нибудь посмотрим, раз вы тест написали. Пока можете поисправлять ошибки, которые бот нашёл.

2017-01-06 19:28 UTC, mglukhikh requested changes
Посмотрел, написал вам замечаний. Большая их часть вызвана очень неряшливым форматированием кода. Постарайтесь исправить замечания к 13-му января.

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +         grad*(PI/180)+min*(PI/(60*180))+sec*(PI/(3600*180))
Знаки операций следует отделять от аргументов пробелами, чтобы облегчить чтение программы. IDEA может сделать эту операцию за вас, используйте Ctrl+Alt+L

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +        sqrt(sqr(x2-x1)+sqr(y2-y1))
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +        number/100%10
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +        hoursArrive*60+minutesArrive-(hoursDepart*60+minutesDepart)
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +val s=(t1*v1+t2*v2+t3*v3)/2
Форматирование: после открывающей { полагается отступ в четыре пробела.

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    (s < (v1 * t1 + v2 * t2)) -> (((s - v1 * t1) / v2) + t1)
Тесты этой задачи не проходят. Рассмотрите случай, когда одно из времён равно 0.

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if(kingX==rookX2 || kingY==rookY2)if(a==1) a=3 else a=2
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +return a
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if(a+b<=c||b+c<=a||a+c<=b) return p
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    var p = -1
Эта переменная не нужна

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    var cosy:Double = 0.0
Явное указание типа не нужно

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if(d==a) cosy = ((c * c + b * b - a * a) )
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (d == c) cosy = ((a * a + b * b - c * c))
Здесь и далее -- ненужные скобки

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if(a >= c && b <= d) p= (b - a)
Форматирование. Длинную цепочку if...else лучше представить как when

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return s1==s2
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return (x1==x2 || y1==y2 || x1+y1==x2+y2 || x1-y1==x2-y2)
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return( sqrt(sqr(x1 - x2) + sqr(y1 - y2)) <= r2 - r1)
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    return (a<=r&&b<=s)||(b<=r&&a<=s)||(a<=r&&c<=r)||(c<=r&&a<=r)||(b<=r&&c<=s)||(c<=r&&b<=s)
Тесты этой задачи не проходят -- см. контр-пример бота. + пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +var a=n
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    if(n<10&&n>-10) return 1
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    {
Форматирование -- открывающая скобка должна быть на одной строке с while

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +     count++
Форматирование: отступ в 4 пробела

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    result = (1 / sq * (pow((1 + sq) / 2, doubleN)))
Поясните в комментарии смысл этой и следующей формулы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +return round(result).toInt()
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Данный алгоритм на практике работает очень медленно. Почитайте про известные алгоритмы определения НОК

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        if(n%a==0) break
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        if(n%i==0) nok=i
Нельзя ли не перебирать все возможные делители начиная с 1?

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        val c=a%b
Пробелы, форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +       if((sqrt(i.toDouble()).toInt()*sqrt(i.toDouble()).toInt()) ==i)  return true else i++
Это ужас какой-то. Можно гораздо проще.

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            Math.abs(eps)) {
Условие можно в одну строку

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        {
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        {
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            else k /= 10
```
if (...)
    doSomething
else
    doAnother
```

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    return if(list.size == 0)0.0 else(list.sum()/list.size)
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        result +=a[i]*b[i]
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    {
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var b=n
Пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        {
Форматирование, пробелы

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +return result
ФОрматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    val ALPHABET = "abcdefghijklmnopqrstuvwxyz"
Такие переменные, как `ALPHABET`, лучше определять вне функций

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список у вас встречается два раза. Определите его вне функций один раз и используйте

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        if ((i.toInt() < 58) && (i.toInt() > 47) || (i.toInt() == 43)) result += i
Магические константы (43, 47, 58) следует заменить символами

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    if (result.first() == '+' && result.length == 1) return ""
Для пустой строки эта конструкция будет кидать исключение

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    var max = parts[0].toInt()
Здесь тоже возможно исключение

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    {if (max == parts[i].toInt()) return -1}
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +        }
Форматирование

2017-01-06 19:28 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +            if ((j == '+') && (max < parts[part - 1].toInt())) max = parts[part - 1].toInt()
И здесь возможны несанкционированные исключения

2017-01-13 09:44 UTC, mglukhikh commented
recheck all

2017-01-13 10:06 UTC, mglukhikh commented
Убедительная просьба просмотреть ВСЕ мои замечания (см. выше по тексту PR, используйте кнопку Show Outdated на замечаниях). Часть из них остались не поправленными, вы просто поменяли код рядом с ними. Кроме этого, в 5-м уроке по-прежнему не работают две задачи, о причинах этого я вам писал.

2017-01-15 14:44 UTC, DavitGrigoryan commented
у меня такая проблема после обновления компилятор не работает корректно и я эти тесты который бот проверял поставил в мои тести и в обоих задач мне не выдало ошибки. и у меня вечером не работало. я только сейчас сделал и до вечера скину все задачи

2017-01-16 07:52 UTC, mglukhikh commented
recheck all

2017-01-16 08:01 UTC, mglukhikh commented
В общем и целом сойдёт. На зачёт вы наработали, можете приходить сегодня на экзамен.

2017-01-16 08:01 UTC, closed without merging