lessons 1,2,3 solved, lesson 4 in progress
Kotlin-Polytech/KotlinAsFirst2016 pull request #40
Opened 2016-09-10 19:44 UTC by tiger31

Check out 1st, 2nd, 3rd lessons, 4th in progress

2016-09-11 14:07 UTC, ice-phoenix commented
recheck assignment

2016-09-11 14:09 UTC, ice-phoenix commented
recheck assignment

2016-09-11 14:14 UTC, ice-phoenix commented
recheck assignment

2016-09-11 14:24 UTC, ice-phoenix commented
recheck assignment

2016-09-11 14:40 UTC, ice-phoenix commented
recheck assignment

2016-09-12 11:39 UTC, ice-phoenix commented
recheck all

2016-09-12 11:43 UTC, ice-phoenix commented
recheck all

2016-09-13 10:50 UTC, ice-phoenix commented
recheck all

2016-09-13 10:57 UTC, gagarski commented
recheck all

2016-09-14 11:15 UTC, ice-phoenix commented
recheck all

2016-09-14 11:16 UTC, ice-phoenix commented
recheck all

2016-09-14 11:27 UTC, ice-phoenix commented
recheck all

2016-09-14 11:27 UTC, ice-phoenix commented
recheck all

2016-09-14 11:28 UTC, ice-phoenix commented
recheck all

2016-09-14 11:29 UTC, ice-phoenix commented
recheck all

2016-09-14 11:35 UTC, ice-phoenix commented
recheck all

2016-09-14 11:44 UTC, ice-phoenix commented
recheck all

2016-09-14 12:02 UTC, ice-phoenix commented
recheck all

2016-09-14 14:37 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    var value: Double = grad + min.toDouble()/60 + sec.toDouble()/3600;
* Данная переменная может быть объявлена как `val`
* Система типов Котлина выведет тип переменной автоматически

2016-09-14 14:38 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(abs(x2-x1) * abs(x2-x1) + abs(y2-y1) * abs(y2-y1));
`x * x` == `abs(x) * abs(x)`

2016-09-14 14:39 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    var sn: String = number.toString()
В данной задаче нельзя использовать строковые функции

2016-09-14 14:39 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = number.toString().reversed().toInt()
В данной задаче нельзя использовать строковые функции

2016-09-14 14:42 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (rookX1==kingX || rookY1==kingY)
Условия того, бьет ли та или иная ладья короля, лучше сохранить в отдельные переменные типа Boolean, и дальнейший анализ проводить над этими переменными (чтобы не загромождать код)

2016-09-14 14:42 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (kingX == rookX || kingY == rookY)
См. выше

2016-09-14 14:43 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (arr[2] >= arr[1] + arr[0])
Данное выражение лучше оформить как `when`

2016-09-14 14:43 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (c <= a && d >= a && d <= b)
Данное выражение лучше оформить как `when`

2016-09-14 14:45 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return str[0].toString().toInt() + str[1].toString().toInt() == str[2].toString().toInt() + str[3].toString().toInt()
Вместо `a.toString().toInt()` необходимо использовать свойства ASCII кодировки для цифр

2016-09-14 14:46 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if((a <= r && b <= s) || (a <= s && b <= r))
В данной задаче лучше найти две минимальные стороны кирпича, а затем проверить возможность их прохода через отверстие

2016-09-14 14:48 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var nok: Int = m*n
В данной задаче лучше воспользоваться известными алгоритмами нахождения LCM

2016-09-14 14:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (str.length < n){
Оцените длину строки в случае, если `n == 10^6`. Можно ли решить задачу без сохранения промежуточных квадратов в строку?

2016-09-14 14:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (str.length < n){
Оцените длину строки в случае, если n == 10^6. Можно ли решить задачу без сохранения промежуточных квадратов в строку?

2016-09-14 14:53 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if(list.isEmpty()) list else list.map {it-list.sum()/list.count()}.toMutableList()
Выражение `list.sum()/list.count()` следует посчитать один раз

2016-09-14 14:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun times(a: List<Double>, b: List<Double>): Double = a.sumByDouble { it*b[a.indexOf(it)] }
[Здесь и далее] Если вы хотите работать с последовательностью в функциональном стиле, но имея доступ к индексу текущего элемента, используйте `indexed...` семейство функций.

В данной задаче, кроме того, может помочь функция `zip`.

2016-09-14 15:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        list.map { it+list.subList(0,list.indexOf(it)-1).sum() }.toMutableList()
Необходимо реализовать алгортм без постоянного пересчета одних и тех же элементов.

2016-09-14 15:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun polynom(p: List<Double>, x: Double): Double = p.sumByDouble { it*pow(x,p.indexOf(it).toDouble()) }
`indexed...`

2016-09-14 15:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list = mutableListOf<Int>()
* Данная переменная может быть объявлена как `val`

2016-09-14 15:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var num: Int = n
* Система типов Котлина выведет тип переменной автоматически

2016-09-14 15:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    while(num%2 == 0) {
Почему делитель 2 обрабатывается отдельно?

2016-09-14 15:02 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String {
Данная функция может использовать функцию `factorize`

2016-09-14 15:06 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return digits.reversed().sumBy { it*Math.pow(base.toDouble(), i++.toDouble()).toInt() }
Изменять внешнюю переменную внутри лямбды внутри функционального вызова --- *очень плохой стиль*. Либо перепишите с использованием цикла `for`, либо поговорите с преподавателем о том, как можно решить данную задачу в функциональном стиле.

2016-09-14 16:42 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val chars: String = "abcdefghijklmnopqrstuywxyz"
Данная задача может быть решена с использованием реализованной вами функции `convert`.

2016-09-16 17:58 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (expression.matches(Regex("^([0-9]+)( [-+] [0-9]+)*"))) {
Использовать регексы для всего, не понимая до конца их выразительные способности, - не очень хорошая идея. Как ваше решение реагирует на несколько пробелов между элементами выражения?

2016-09-16 17:59 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (price.toDouble() > value) {
Повторно используемые выражения следует вынести в отдельные переменные

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +
Где решение?

2016-09-16 18:00 UTC, ice-phoenix requested changes

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val value: Double = grad + min.toDouble()/60 + sec.toDouble()/3600
- Система типов Котлина выведет тип переменной автоматически
- При необходимости деления с плавающей запятой обычно делают `min / 60.0`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun thirdDigit(number: Int): Int = (number%1000-number%100)/100
Форматирование должно быть единым по всему коду (отступы, пробелы между операторами и так далее)

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (hoursArrive*60 + minutesArrive) - (hoursDepart*60+minutesDepart)
Если тело вашей функции состоит из одного `return`, принято ее оформлять как `fun foo(): Int = 42`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val per: Double = 1 + percent.toDouble() / 100
- Система типов Котлина выведет тип переменной автоматически
- `percent / 100.0`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((age%100 in 5..20 ) || age%10 == 0 || age%10 > 4){
Данное выражение лучше оформить как `when`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val path: Double = t1*v1 + t2*v2 + t3*v3
- Система типов Котлина выведет тип переменной автоматически

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (t1*v1 >= path/2)
Несколько раз используемые выражения следует вынести в переменные с осмысленными именами

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (rook1 && rook2) 3 else if (rook2) 2 else if (rook1) 1 else 0
Данное выражение лучше оформить как `when`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (rook && bish) 3 else if (bish) 2 else if (rook) 1 else 0
Данное выражение лучше оформить как `when`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val arr: DoubleArray = doubleArrayOf(a,b,c)
- Система типов Котлина выведет тип переменной автоматически

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val str: String = number.toString()
- Система типов Котлина выведет тип переменной автоматически

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    var deltaCenter: Double = sqrt(sqr(x2-x1)+sqr(y2-y1));
- Система типов Котлина выведет тип переменной автоматически

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val values = intArrayOf(a,b,c); values.sort()
Лучше использовать метод `Iterable<T>.sorted()`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n == 1 || n == 2) return 1
Попробуйте оценить, какое количество вызовов функции `fib(3)` требуется в вашей реализации для вычисления `fib(42)`. Можно ли сделать так, чтобы количество вызовов было меньше?

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a: Int = m; var b: Int = n
- Система типов Котлина выведет тип переменной автоматически
- Объявления нескольких переменных следует размещать на нескольких строчках

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            d = i
В данном случае можно сразу сделать `return i`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var d: Int = n
- Система типов Котлина выведет тип переменной автоматически

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Подумайте, каким числом ограничен сверху максимальный возможный делитель числа `n`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var d: Int = 1
См. комментарии к `minDivisor`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val max: Int = if (m > n) m else n
Подумайте, можно ли эту функцию реализовать через другие функции данного модуля

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i: Int = 0
Нет ли какого-либо числа, большего 0, с которого можно начинать перебирать точные квадраты в диапазоне от `m` до `n`?

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var lastNum: Int = n%10
Как ведет себя операция `%` для отрицательных чисел?

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (pointer + digitNumber(i*i) >= n)
Постоянно используемые выражения следует вынести в отдельные переменные

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            num = (i*i).toString()[n-pointer-1].toInt()-48
Вместо `a.toInt() - 48` лучше сделать `a - '0'`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (pointer + digitNumber(fib(i)) >= n)
См. комментарии выше

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +import com.sun.xml.internal.fastinfoset.util.StringArray
Зачем вам этот импорт?

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return list.mapIndexed { i, d -> if (i>0) sub+=list[i-1]; d + sub  }.toMutableList()
- Изменять захваченную переменную из лямбды --- **очень плохой стиль**
- Лучше обсудите с преподавателем, как это сделать правильно

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    while(num%2 == 0) {
Почему 2 обрабатывается отдельно от остальных случаев???

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return digits.reversed().mapIndexed { i, d -> d*Math.pow(base.toDouble(), i.toDouble()).toInt() }.sum()
[Здесь и раньше] Реализуйте функцию `pow` для целочисленных типов

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val chars: String = "abcdefghijklmnopqrstuvwxyz"
Данную структуру данных лучше сделать как ассоциативный массив (`Map`)

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +import kotlin.reflect.jvm.internal.impl.serialization.ProtoBuf
Зачем вам этот импорт?

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return String.format("%02d.%02d.%d", parts[0].toInt(), month, parts[2].toInt())
`parts[0]` и `parts[2]` лучше вынести в отдельные переменные соответствующих их смыслу типов

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var isNum: Int = 1; parts.forEach {if (it.matches(Regex("[0-9]+"))) isNum*=1 else isNum*=0 }
`isNum` лучше сделать переменной типа `Boolean`

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (Regex("[0-9]+").findAll(jumps).count() > 0)
Повторно вычисляемые выражения следует вынести в отдельные переменные

2016-09-16 18:00 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return Regex("[0-9]+").findAll(jumps).map { it.value.toInt() }.max().toString().toInt()
Зачем `toString().toInt()`???

2016-10-06 13:18 UTC, ice-phoenix requested changes
Все очень неплохо + то, что вы решаете многие задачи в функциональном стиле, просто замечательно. По поводу ошибок в сложных задачах мы сперва посмотрим, есть ли баги в проверяющей системе. Спасибо!

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val value: Double = grad + min / 60.0 + sec / 3600.0
- Система типов Котлина выведет тип переменной автоматически

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return value * PI / 180
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun thirdDigit(number: Int): Int = (number%1000 - number%100) / 100
[Здесь и везде] Форматирование кода должно быть единообразным, если вы отделяете операторы от операндов пробелами, то делайте это для всех операторов

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        age%100 in 5..20 -> age.toString() + " лет"
Лучше воспользоваться string interpolation в виде "$age лет"

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val path = (first + sec + t3*v3)/2
"t3 \* v3" лучше тоже вынести в отдельную переменную

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (first >= path)
Данное выражение лучше оформить как `when`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when { (rook1 && rook2) -> 3; rook2 -> 2; rook1 -> 1; else -> 0 }
Отдельные ветки `when` принято оформлять на отдельных строках

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    arr.sort()
Лучше `doubleArrayOf(...).sorted()`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +import lesson2.task1.minBiRoot
Зачем вам здесь этот импорт?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val str: String = number.toString()
- Система типов Котлина выведет тип переменной автоматически

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (x1 == x2) || (y1 == y2) || (abs(y2-y1) == abs((x2-x1)))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = 1
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = m
`nod ==> gcd`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n/2) {
Вы уже использовали более точную границу для возможных делителей в одной из задач ранее, почему не воспользоваться ей здесь?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in n/2 downTo 1) {
Вы уже использовали более точную границу для возможных делителей в одной из задач ранее, почему не воспользоваться ей здесь?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val min = min(m,n)
По условию задачи `m <= n`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        val length = digitNumber(i*i)
Повторно используемые выражения лучше вынести в отдельные переменные

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        val length = digitNumber(fib(i))
Повторно используемые выражения лучше вынести в отдельные переменные

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return if (list.isEmpty()) list else list.map { it - c }.toMutableList()
По условию задачи вы должны менять оригинальный список (хотя ваше решение в функциональном стиле, безусловно, выглядит чище и лучше)

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list.forEachIndexed { i, d -> if (i != list.count()-1) list[i+1] += list[i] }
Чтобы не проверять предпоследний элемент так, как это делаете вы, можно сперва сделать `list.take` на требуемую глубину

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (num%2 == 0) {
Зачем обрабатывать 2 отдельным случаем?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return str.reversed().sumBy {(map[it] ?: 0) * pow(base, i++)}
Зачем вам `map`, если все то же самое лежит в оригинальной строке `chars`?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    num %= 1000
Форматирование кода

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var str: String = ""
Для сборки строки из составных частей лучше использовать `StringBuilder`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        in 20..29 -> str = "двадцать" + (if(n%10 > 0) " " else "") + points(n%10,female)
Здесь и далее, вместо постоянной проверки "вперед" на пустоту результата лучше сложить все отдельные результаты в список, убрать пустые и соединить итоговый список через пробелы

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var isNum = true; parts.forEach {if (it.matches(Regex("[0-9]+")) && isNum) isNum = true else isNum = false }
Если вы решили использовать регексы для валидации входной строки, то лучше написать один регекс, который сразу проверяет все

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } else throw java.lang.IllegalArgumentException(java.lang.NumberFormatException(expression))
Не следует вкладывать одно исключение в другое в данном случае

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return Regex("[-+]?[0-9]+").findAll(expression.replace(" ","")).sumBy { it.groupValues[0].toInt() }
- Почему `groupValues[0]`, а не просто `values`?
- Чем вам мешают пробелы, что вы их сперва убираете из строки?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (price.toDouble() > value) {
Можно `val price = values[1].toDouble()`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val map: MutableMap<Int,Int> = HashMap()
Лучше `mutableMapOf()`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (commands.count { it=='[' } == commands.count { it=='[' } &&
Данное условие не проверяет парность циклов + в нем ошибка

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun lineByPoints(a: Point, b: Point): Line = Line(a, Math.atan((b.y-a.y)/(b.x-a.x)))
Почему бы не решить данную задачу, используя уже реализованные функции из этого модуля?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var f: Circle = circles[0]
* Система типов Котлина выведет тип переменной автоматически

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +import lesson8.task1.markdownToHtml
Зачем здесь этот импорт?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            return circleByThreePoints(d.begin, d.end, p)
Почему мы сразу выходим из перебора?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        val chars = "abcdefgh"
Почему бы массив `chars` не вынести куда-нибудь наружу, раз вы его используете везде и всюду?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val map = (1..8).associateBy { it -> chars[it-1] }
Зачем вам `map`, если в `char` все и так содержится?

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        if (start.column != end.column && start.row != end.row)
Данное выражение лучше оформить как `when`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        if ((start.column * start.row) % 2 == (end.column * end.row) % 2) {
Данное выражение лучше оформить как `when`

2016-10-06 13:18 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        else -> TODO()
Отлично! Помечать себе штуки на будущее как `TODO()` --- очень хорошая привычка!

2016-10-06 13:51 UTC, ice-phoenix commented
recheck all

2016-10-13 21:28 UTC, tiger31 commented
recheck all

2016-10-13 21:31 UTC, tiger31 commented
В комментариях в коде я уже написал, что почему-то последний тест в задаче "bishopTrajectory" не проходит в любом случае, в чем вообще его смысл?

2016-10-13 21:46 UTC, tiger31 commented
recheck all

2016-10-13 21:48 UTC, tiger31 commented
Решения прошли все тесты. Ну, кроме того, о которо я говорил. Жду вашей проверки

2016-10-18 14:17 UTC, ice-phoenix commented
recheck all

2016-10-18 14:21 UTC, ice-phoenix commented
recheck all

2016-10-18 16:08 UTC, ice-phoenix requested changes
Задачи из 6 урока посмотрю завтра

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    (hoursArrive*60 + minutesArrive) - (hoursDepart*60+minutesDepart)
Форматирование внезапно слегка поехало =)

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    while (n> 0) {
Форматирование должно быть единообразным везде =)

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        age%100 in 5..20 -> "$age лет"
Опять форматирование --- почему некоторые операторы отделены пробелами от операндов, а некоторые нет?

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            count ++
Форматирование --- оператор инкремента обычно все же пишут слитно с его операндом

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int = n*m/nod(m,n)
Форматирование

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return i >= m && i <= n
Вот это хорошее решение =)

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var sinn = x
Попробуйте подумать, нельзя ли, используя определенные тригонометрические закономерности, ограничить значение `x`,  с которым мы работаем?

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var cos = 1.0
Попробуйте подумать, нельзя ли, используя определенные тригонометрические закономерности, ограничить значение `x`,  с которым мы работаем?

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (pow(x,(1+i*2.0)) / factorial(1+i*2) > eps) {
Повторно вычисляемое выражение (тем более, со степенью и факториалом) следует вынести в отдельную переменную

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (pow(x,(i*2.0)) / factorial(i*2) > eps) {
Повторно вычисляемое выражение (тем более, со степенью и факториалом) следует вынести в отдельную переменную

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var num = abs(n)
Как это будет работать в случае `Integer.MIN_VALUE`?

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            num = (iSqr).toString()[n-pointer-1] - '0'
Можно обойтись без переменной `num`, если сразу возвращать результат прямо тут

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            num = fib.toString()[n-pointer-1] - '0'
Можно обойтись без переменной `num`, если сразу возвращать результат прямо тут

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun pow (x: Int, n: Int): Int {
Вот это прямо вообще круто =) Так держать!

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return p.mapIndexed { i, d -> d*pow(x,i.toDouble()) }.sum()
[Здесь и много где еще] Форматирование кода!

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return a.zip(b, { R,T -> R*T }).sum()
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return list.sorted()
Зачем сортировать список, если вы и так добавляете делители от меньшего к большему?

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return convert(n,base).joinToString(separator="", transform = {chars[it].toString()})
Фор-ма-ти-ро-ва-ни-е!

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return digits.reversed().mapIndexed { i, d -> d*pow(base, i) }.sum()
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return str.reversed().sumBy {chars.indexOf(it) * pow(base, i++)}
Чтобы не нужна была отдельная переменная `i`, может быть, лучше сделать `mapIndexed`,  а потом уже сложить?

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list: MutableList<String> = mutableListOf()
- Система типов Котлина выведет тип переменной автоматически

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (thousands != 0) list.add(keyword(thousands))
Проверку на 0 можно утащить в `keyword` и возвращать пустую строку

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list.removeAll { it == "" }
Мне кажется, лучше через `filter`

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return phone.replace(Regex("[-() ]+"),"")
Форматирование

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if(jumps.matches(Regex("[-%[0-9] ]+"))){
Зачем character class внутри character class?

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    //Как вообще работает метод trim()? Почему, когда я применяю его к строке, ничего не происходит?
`trim()` убирает пробелы из начала и конца строки

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (expression.matches(Regex("""^([0-9]+)(\s+[-+]\s+[0-9]+)*"""))) {
Попробуйте здесь сделать незахватывающие группы, может быть, это поможет со `StackOverflowError`

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var found = false
Можно попробовать решить все это через regex =)

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (one in description.split("; ")) {
Попробуйте здесь сделать проверку на то, что перед `;` есть число

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var count: Int = roman.length-1
* Система типов Котлина выведет тип переменной автоматически

2016-10-18 16:08 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val openPointQueue = mutableListOf<Int>()
Можно почитать про такие структуры данных, как Queue и Stack, и как с ними можно работать в Java / Kotlin

2016-10-18 16:32 UTC, tiger31 commented
С форматирование, что-то действительно странное, так как должно было все быть нормально

2016-10-19 15:47 UTC, ice-phoenix requested changes
:+1:

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        return Segment(min,max)
Принято ставить пробел после запятой, которая разделяет аргументы функции

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    val center_x = diameter.begin.x + (diameter.end.x - diameter.begin.x) / 2
Разделять компоненты имени `_` принято в C++ =) в Kotlin обычно используется `CamelCase`

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        val y: Double
Это можно заменить на `val y = if (...) ...`

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        val y: Double
Данное выражение лучше оформить как `when`

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun lineBySegment(s: Segment): Line = Line(s.begin, Math.atan((s.end.y-s.begin.y)/(s.end.x-s.begin.x)))
Форматирование

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +fun lineByPoints(a: Point, b: Point): Line = lineBySegment(Segment(a,b))
👍

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    val angle = lineByPoints(a,b).angle + Math.PI / 2
Лучше было бы завести `Segment(a, b)` и все считать от него

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var f = circles[0]
Можно эти две переменные утащить внутрь `if`

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    val ma = (b.y - a.y) / (b.x - a.x)
Если у вас есть деление, то можно где-то поделить на ноль =) Посмотрите на результаты тестов и подумайте, как можно исправить ваше решение.

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            c = circleByThreePoints(d.begin, d.end, p)
Вы почему-то считаете, что круг обязательно будет проходить через диаметр. Разве это так всегда?

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        return if (inside()) "${chars[this.column-1]}$row" else ""
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        throw IllegalAccessException()
Посмотрите, какое исключение нужно кидать в случае ошибки

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        ((start.column * start.row) % 2 != (end.column * end.row) % 2) -> -1
Похоже, что ваше условие определения цвета поля под слоном не работает =) смотрите в тест и разбирайтесь, что не так =)

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    //В чем смысл последнего теста? И почему он не проходит всегда?
Из-за ошибки в `bishopMoveNumber` ваш код думает, что траектории нет. Хотя она есть.

Тест, к сожалению, плюется внутренней ошибкой, мы это поправим =)

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            var Sq: Square
Можно `val sq = when { ... }`

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    val steps = mutableListOf(start)
Можно унести внутрь `if`

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +            if (abs(horizontal) > abs(vertical))
В таких случаях (когда у вас `if` не зависит от итерации `for`) обычно их меняют местами

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    }
Нельзя ли весь второй цикл заменить какой-либо трансформацией элементов списка?

2016-10-19 15:47 UTC, ice-phoenix commented on src/lesson6/task3/Graph.kt
> +        val visited = mutableMapOf<Vertex,MutableList<String>>()
На практике алгоритмы поиска путей не сохраняют весь путь для какой-либо вершины, а просто сохраняют предыдущую, и восстанавливают итоговый путь в самом конце

2016-10-19 15:50 UTC, ice-phoenix commented
recheck all

2016-10-19 15:52 UTC, ice-phoenix commented
recheck all

2016-10-19 16:05 UTC, ice-phoenix commented
recheck all

2016-10-19 16:08 UTC, ice-phoenix commented
recheck all

2016-11-22 13:59 UTC, ice-phoenix commented
recheck all

2016-11-22 14:00 UTC, ice-phoenix commented
recheck all

2016-11-25 16:15 UTC, tiger31 commented
Ноутбук сел, не успел залить почти весь 7 lesson, через часик - два все будет

2016-11-25 19:36 UTC, tiger31 commented
Я не могу понять, что не так? Почему я не могу перегрузить метод родительского интерфейса? И почему в IDEA все работает, и даже собирается проект?

2016-11-25 19:42 UTC, ice-phoenix commented
Если бы вы внимательно прочитали текст ошибки, то поняли бы, что ошибка возникает в тестах, потому что мы не рассчитывали на то, что вы будете менять интерфейс `Matrix`. Если вы хотите добавить свои функции, реализуйте их при помощи extension-методов.

2016-11-25 20:04 UTC, tiger31 commented
То, что ошибка где-то в компиляции тестов - я понял. Но я не думал, что нельзя вносить изенения в интерфейс, я дуал, что ошибка где-то у меня в объявлении методов или их перегрузке. Поэтому на протяжение часа я перерыл кучу форумов. Зато нашел немного полезной информации по другой теме. Спасибо, что подсказали

2016-11-25 20:18 UTC, tiger31 commented
Хотел, значит, залить решения около девяти часов, еще два часа сидел и пытался разобраться, что не так. Ну, собственно, как обычно :)

2016-11-25 20:33 UTC, tiger31 commented
За ночь постараюсь остаток дорешать

2016-11-26 19:28 UTC, tiger31 commented
Как я понял последня задача седьмого урока решается графом + A*? Или есть другие пути её решения?

2016-11-28 09:45 UTC, ice-phoenix commented
Вы бы лучше сперва все замечания исправили, перед тем, как решать последнюю задачу седьмого урока. В целом, эту задачу можно решать поиском на неявно заданном графе, да. Вот только что у вас будет эвристикой для A*?

2016-11-28 09:58 UTC, tiger31 commented
Исправлениями я займусь, а эвристикой будет что-то вроде f(x)=(количество перестановок до текущего состояния + количество ячеек не на своём месте)

2016-12-01 09:43 UTC, tiger31 commented
recheck all

2016-12-01 15:05 UTC, tiger31 commented
Изменил эвристику и пуллинг новых вершин, но алгоритм все еще решает только простые задачи с небольшим количество ходов. Что не так в алгоритме?

2016-12-01 15:06 UTC, tiger31 commented
Я знаю, что он и не вернет список ходов, но он даже не может найти конечную вершину(решение)

2016-12-01 17:34 UTC, mglukhikh requested changes
Я взял на себя смелость поревьюить `fifteenGameSolution` (и только её), поскольку вы первый из студентов, кто пытается решить эту задачу. Ответ на ваш вопрос в ревью содержится. Дерзайте. Эта задача, по-видимому, самая сложная во всём проекте, так что не огорчайтесь, если не получится решить её быстро. Если у моих коллег есть дополнительные замечания к решению, они напишут их отдельно.

NB: не считайте, пожалуйста, что вначале надо заставить всё работать, а потом решение причёсывать и приводить в порядок стиль. В нормальном случае эти процессы идут параллельно, поскольку заставить работать аккуратно написанное решение проще. Многократно проверено.

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +fun h(matrix: Matrix<Int>): Int {
Старайтесь не называть так функции. Насколько я понимаю, эта функция возвращает некоторую оценку, насколько далеко данная позиция от исходной. В соответствии с этим придумайте название. Простой идеей может быть, например, `evaluation` (оценка)

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    for (i in 0..3)
В таких конструкциях лучше ставить фигурные скобки везде, иначе их тяжелее читать. Кроме этого, есть смысл назвать в данном случае переменные цикла `row` и `column` -- так понятнее.

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +            if (matrix[i,j] != 0)
Вот здесь я не уверен в разумности этой проверки. Интуиция подсказывает, что расстояние пустой ячейки от её оригинальной позиции тоже имеет некоторое значение. Но здесь, конечно, нужна проверка на практике.

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +                    n += abs(matrix[i, j] / 4 - i) + abs(matrix[i, j] % 4 - j - 1)
Насколько я понимаю, здесь вы пытаетесь посчитать сумму расстояний по горизонтали и вертикали от оригинальной позиции. Если это так, то использованная формула кажется мне неверной.

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +        } else N += 1 + i / 4
Вы уверены, что этот кусок формулы, касающийся пустой клетки, справедлив? (спрашиваю потому, что первую часть этого мини-алгоритма в математических книгах я видел, а вторую -- нет)

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    // Попытка A* + поиск в шиину
Всё начиная отсюда стоило бы вытащить в отдельную функцию. Кроме этого, `A*` пока не виден

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +        } else N += 1 + i / 4
Кроме этого, это определение чётности позиции стоило бы вынести в отдельную функцию

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    data class State(val m: Matrix<Int>, val priority: Int) : Comparable<State> {
`m` --> `matrix`. Такие короткие имена почти не используются для свойств

2016-12-01 17:34 UTC, mglukhikh commented on src/lesson7/task2/Matrices.kt
> +    while (queue.isNotEmpty()) {
Я боюсь, что с подобной идеей алгоритма исправление ошибок (например, не учитывается приоритет, не запоминаются ходы, может быть, я ещё чего-либо не вижу) не поможет. Дело в том, что у игры в 15 всего имеется `16!` позиций, чёт / нечёт уменьшает это число вдвое. Такой вот полный поиск в ширину будет вынужден обойти весьма существенную часть от этого количества, а оно измеряется триллионами. То есть шансов получить решение за обозримое время таким способом вроде как не имеется (IMHO).

Что можно рекомендовать:

* в данной задаче `DFS` должен быть лучше `BFS`, хотя бы за счёт того, что можно избежать постоянного копирования матриц
* независимо от того, используете вы `DFS` или `BFS`, поиск необходимо ограничивать, то есть не искать дальше, чем на какое-то ограниченное количество ходов вперёд; вы при этом не достигнете завершающей позиции, но сможете найти позицию с лучшей оценкой и ход, ведущий в неё; найденный ход следует запомнить в списке, сделать и повторить всю процедуру поиска уже с новой позиции для поиска лучшего второго хода; процедура повторяется до тех пор, пока сделанный ход не приведёт вас в `solution`.

2016-12-05 11:44 UTC, ice-phoenix commented
Очень много неисправленных ранее замечаний. Давайте вы сперва исправите их все (да, скучно, да, нудно, да, не приближает вас к получению зачета напрямую), а потом уже будем смотреть, что вы наделали дальше.

2016-12-07 19:59 UTC, ice-phoenix requested changes
Чего-то посмотрел и пописал в задачке про 15

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    object companion {
Вообще-то, companion object задается несколько не так

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +val NOT_EXISTS = Cell(-1, -1)
Вы не поверите, но можно сделать extension value у класса =)

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    if (this == other) throw IllegalArgumentException("Cells are the same")
Можно в виде one-liner

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        throw IllegalArgumentException("Sub Matrix is out of bounds of original")
Раз уж мы все проверяем, то я бы проверил границы и в другую сторону

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    if (this.height < height + heightShift || this.width < width + widthShift)
Тут у вас клэш по именам, лучше его избегать --- я бы переименовал аргументы функции как-нибудь по другому

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    val list: MutableList<Cell> = mutableListOf()
Можно без указания типа переменной

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    return m
Нельзя ли эту функцию выразить через функцию `subMatrix`?

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        if (this.contains(cell.row + it + 1, cell.column + it)) list.add(Cell(cell.row + it + 1, cell.column + it))
Неплохой трик, но слегка усложняет понимание кода =)

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    object companion {
companion object задается несколько по другому =)

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            SOLUTION = if (N % 2 == 0) solution1 else solution2
Лучше сделать эту функцию как `solution = detectSolution(matrix)`, так она и чистой будет, и попонятнее, и вообще

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                    if (list[i] > list[j] && list[j] != 0)
Почему бы здесь вторую проверку тоже не сделать через `if` + `continue`?

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            println("Solution found: $SOLUTION")
Никаких `println` в коде!

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        return moves
Форматирование кода

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            step.swap(zeroPos, move)
Можно сделать, чтобы все подобные методы возвращали матрицу, и тогда можно будет их чейнить как `matrix.a().b().c()`

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    fun getCellsMoves(): List<Cell> = this.matrix.findMoves(this.matrix.indexOf(0))
Возможная оптимизация --- учитывая, как часто вас интересует позиция нуля, ее имеет смысл хранить отдельно, как поле состояния решения, например

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        val ZERO_MATRIX = createMatrix(4,4,0)
Форматирование кода

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                val value = State.companion.SOLUTION.indexOf(matrix[row, column])
Возможная оптимизация --- эту штуку можно посчитать один раз в `Map`, и потом быстро доставать, вместо медленного ползания по всей матрице

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        return manhattan + linearConflict()
Вот этого места я слегка не понял. Вы берете две оценки количества ходов, каждая из которых по отдельности вам точно никогда не переоценивает числа ходов, требуемых для решения задачи, и складываете их. Есть ощущение, что тем самым вы можете нарушить требуемое для нормальной работы A* свойство эвристики.

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                    val TileKRow = K / 4 == row || (K / 4 == row + 1 && K % 4 == 0) //Goal-позиция тайла K в этом ряду?
`camelCase`, yo!

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                for (cell in 0..column - 1) {
Не очень удачные имена для переменных

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +var finished = 0
Почему это все внезапно на глобальном уровне, а не внутри какого-либо объекта/класса?

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        state.matrix.swap(zero, move)
Кажется, что во всем этом деле (см. выше) вы слишком много раз копируете матрицу там, где можно было бы обойтись и без этого

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        return listOf()
Вы уж разберитесь в коде, либо через `==`, либо через `solved`

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        moves.clear()
Зачем перезапускать поиск с нуля?

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    State.companion.START = matrix
По хорошему, вам надо завести класс `Solver`, который будет заниматься хранением всей нужной вам для решения одного экземпляра задачи информации, а не жонглировать статическими переменными налево и направо

2016-12-07 19:59 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +                if (state.estimate() + path + 1 > limit) {
Зачем вы вообще ограничиваете глубину поиска, чтобы потом (если не получилось) перезапускать все с нуля и снова проходить все те же самые позиции?

2016-12-18 22:28 UTC, ice-phoenix commented
recheck all

2016-12-18 22:39 UTC, ice-phoenix commented
Несмотря на большое количество замечаний и не очень чистый код, по совокупной статистике решения задач и результатам тестирования у вас "Отлично"! Так держать!

2016-12-18 22:40 UTC, ice-phoenix commented
PS: Но тесты все же лучше, чтобы завершались =)

2016-12-18 23:15 UTC, tiger31 commented
Я сейчас несколько исправлений еще добавляю. Очень хотелось бы увидеть правильное решение последней задачи в седьмом, потому что пока это единственная задача, которая меня "сломала" :)

2017-07-26 18:24 UTC, closed without merging