Тривиальная 1
Kotlin-Polytech/KotlinAsFirst2016 pull request #46
Opened 2016-09-12 11:32 UTC by Prokhorovmax

2016-09-12 11:45 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val a = hours*3600
Переменным лучше давать говорящие имена, например `hoursInSeconds`

2016-09-12 11:47 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val dlina = sqrt (sqr(x2-x1)+sqr(y2-y1))
Постарайтесь избегать использования транслитерации в именах переменных. Любите английский.

2016-09-12 13:03 UTC, ice-phoenix commented
recheck assignment

2016-09-12 13:07 UTC, ice-phoenix commented
recheck all

2016-09-12 13:07 UTC, ice-phoenix commented
recheck all

2016-09-12 14:11 UTC, gagarski commented
recheck assignment

2016-09-12 14:12 UTC, gagarski commented
recheck all

2016-09-19 11:36 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +       (age % 10 == 1)and(age != 11)and(age != 111) -> "$age год"
Попробуйте записать условия для 111, 112, 113 и 114 в более общем виде

2016-09-19 11:37 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +       (age % 10 == 1)and(age != 11)and(age != 111) -> "$age год"
Попробуйте записать условия для 111, 112, 113 и 114 в более общем виде.

2016-09-19 11:37 UTC, gagarski requested changes

2016-09-19 13:14 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    val res = if (half <= s1) half / v1 else
Множественные ветвления принято записывать в виде
```kotlin
if (half <= s1) half / v1
else if (half <= s1 + s2) t1 + (half - s1) / v2
else t1 + t2 + (half - s1 - s2) / v3
```
или с помощью конструкции `when`

2016-09-19 13:14 UTC, gagarski requested changes

2016-09-26 13:24 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX1)or(kingY == rookY1))and((kingX == rookX2)or(kingY == rookY2))) return 3 else
Множественные ветвления принято записывать в виде
```kotlin
if (half <= s1) half / v1
else if (half <= s1 + s2) t1 + (half - s1) / v2
else t1 + t2 + (half - s1 - s2) / v3
```
или с помощью конструкции `when`.

Пожалуйста исправьте это здесь и в остальных местах.

2016-09-26 13:24 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    return if ((c>=a) && (d<=b)) d-c else
`if...else if...else`

2016-09-26 13:25 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if ((Math.sqrt(sqr(x2-x1)+sqr(y2-y1))) <= (r2-r1)) return true else return false
- Вы используете довольно многословный способ вычисления булевского значения.
```kotlin
if (x) true else false
```
эквивалентно
```kotlin
x
```

2016-09-26 13:26 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if      (((r>=a) && (s>=b)) ||
- Вы используете довольно многословный способ вычисления булевского значения.
```kotlin
if (x) true else false
```
эквивалентно
```kotlin
x
```
 - попробуйте заранее найти наименьшие стороны кирпича, условие станет заметно проще.

2016-09-26 13:28 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +    return third
Вы создали переменную `third`и тут же её возвращаете. Можно было написать просто `return a/100` .

2016-09-26 13:28 UTC, gagarski requested changes

2016-09-29 09:33 UTC, gagarski approved these changes

2016-09-29 09:35 UTC, closed without merging