Lesson 2
Kotlin-Polytech/KotlinAsFirst2016 pull request #49
Opened 2016-09-12 12:18 UTC by SeveNChaK

2016-09-12 13:13 UTC, ice-phoenix commented
recheck all

2016-09-12 13:47 UTC, ice-phoenix commented
recheck all

2016-09-12 13:48 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val x1 = hours * 60 * 60
Переменным лучше давать осмысленные имена

2016-09-12 13:49 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double  = TODO()
В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков

2016-09-12 13:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val ps:Double = (t1*v1+t2*v2+t3*v3)/2
Значения постоянно используемых выражений лучше вынести в отдельные переменные

2016-09-12 13:50 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((c in a..b) && (d in a..b))
Данную цепочку `if`'ов лучше оформить в виде `when`

2016-09-12 13:50 UTC, ice-phoenix commented
recheck all

2016-09-12 18:47 UTC, SeveNChaK commented
Изначально что-то не прошло, а в сообщение позже уже все нормально. Как это понимать? Подскажите, пожалуйста.16:50, 12 сентября 2016 г., Marat Akhin <notifications@github.com>:recheck all —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

2016-09-13 09:00 UTC, ice-phoenix commented
Проверяющая система использует случайное тестирование, и на разных запусках может проверять ваш код на разных входных значениях. В вашем коде все еще есть ошибка, найденная при первом запуске.

2016-10-12 09:38 UTC, mglukhikh commented
Автору PR: вы отстаёте от графика. Вам следует исправить имеющиеся замечания, закончить с заданиями 2-го урока и перейти к решению задач 3-го урока.

2016-10-15 18:51 UTC, maximpetrov commented
recheck all

2016-10-17 12:54 UTC, ice-phoenix requested changes
Дальнейшие задачи будут проверяться только после исправления имеющихся замечаний

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val s=sagenes*48
Форматирование кода должно быть одинаковым везде --- если вы отделяете знаки операций от операндов пробелами, то делайте это везде. Попробуйте отформатировать ваш код при помощи IntelliJ IDEA и в дальнейшем придерживайтесь такого же стиля кодирования.

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return number%1000/100
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (t1*v1 < ps)
Форматирование кода

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var t:Double
Можно обойтись без этой переменной, если все возвращать сразу

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (t1*v1 < ps)
Данное выражение лучше оформить как `when`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val ps:Double = (t1*v1+t2*v2+t3*v3)/2
* Система типов Котлина выведет тип переменной автоматически

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val x4:Int = number%10
* Система типов Котлина выведет тип переменной автоматически

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((x1+x2)==(x3+x4))
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (y1==y2)
Всю эту функцию можно записать в одну строчку, если вспомнить, как комбинируются условия типа `Boolean`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (R>r2)
Выражение `if (cond) false else true` можно заменить на ` ! cond`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((a*b<=r*s) || (a*c<=r*s) || (b*c<=r*s))
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k: Int = Math.min(n, m)
* Система типов Котлина выведет тип переменной автоматически
* Значение `Math.min(n, m)` используется еще и в цикле, следует вынести его в отдельную переменную

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var res: Int = 2
* Система типов Котлина выведет тип переменной автоматически

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var res: Int = n - 1
* Система типов Котлина выведет тип переменной автоматически

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a: Int = m
Что делает данная функция по сути? Объясните своими словами в комментарии.

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        revertNumber = revertNumber + Math.pow(10.0, k.toDouble()).toInt() * (number % 10)
Напишите `pow`, который работает в `Int`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isPalindrome(n: Int): Boolean = if (revert(n) == n) true else false
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        number = square.toDouble() / Math.pow(10.0, count.toDouble())
`pow(Int, Int)`

2016-10-17 12:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        number = fibn.toDouble() / Math.pow(10.0, count.toDouble())
`pow(Int, Int)`

2016-10-24 12:32 UTC, ice-phoenix commented
Обратите внимание, что ваш код не проходит один из встроенных в проект тестов. В дальнейшем проверяйте ваш код на работоспособность локально, у себя на машине, при помощи запуска встроенных тестов в IDE.

2016-10-24 12:50 UTC, ice-phoenix requested changes

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val x1 = hours * 60 * 60
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val s = sagenes * 48
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val ps = (t1 * v1 + t2 * v2 + t3 * v3) / 2
Повторно вычисляемые подвыражения лучше вынести в отдельные переменные

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((c in a..b) && (d in a..b)) {
Данное выражение лучше оформить как `when`

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +import lesson4.task1.abs
Зачем вам здесь этот импорт?

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = if ((y1 == y2) && (x1 == x2) && (Math.abs(y1 - y2) == Math.abs(x1 - x2))) true else false
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return !(R > r2)
Подобное выражение лучше записать как `R <= r2`

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val R = Math.sqrt(sqr(Math.abs(y1 - y2)) + sqr(Math.abs(x1 - x2))) + r1
В Котлине не принято называть переменные с большой буквы

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return ((a * b <= r * s) || (a * c <= r * s) || (b * c <= r * s))
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`
* Данный набор условий не проверяет, проходит ли кирпич в отверстие

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val min = Math.min(m, n)
Зачем два раза вызывать `min(m, n)`?

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        else k = k + min
Почитайте про более быстрые алгоритмы поиска НОК

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var res = n - 1
Нет ли более точной верхней границы для возможных делителей, чем `n`?

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a: Int = m
* Объясните, что делает ваш новый код, в комментарии
* Нельзя ли вынести часть функциональности вашей функции в отдельную функцию, которая могла бы помочь при решении других задач?

2016-10-24 12:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        revertNumber = revertNumber + pow(10, k) * (number % 10)
Почему бы вместо переменной `k` и постоянного возведения в степень не начать с требуемой степени десятки и уменьшать ее на 10 каждый раз?

2016-10-24 13:25 UTC, SeveNChaK reviewed
Ничего не менял в той задаче, все также через алгоритм Евклида

2016-10-24 13:25 UTC, SeveNChaK commented on src/lesson3/task1/Loop.kt
> +    var a: Int = m
Через алгоритм Евклида находит НОД и если он единица, то числа взаимно простые.

2016-10-24 14:06 UTC, SeveNChaK commented on src/lesson2/task2/Logical.kt
> +import lesson4.task1.abs
Никогда не добавлял импорт ни в один урок,  он сам

2016-10-24 14:06 UTC, SeveNChaK commented on src/lesson3/task1/Loop.kt
> +    var a: Int = m
В коде ничего не поменялось в этой задаче, все также алгоритм Евклида

2016-10-24 14:06 UTC, SeveNChaK commented on src/lesson3/task1/Loop.kt
> +        revertNumber = revertNumber + pow(10, k) * (number % 10)
Хорошая идея:)

2016-10-24 14:06 UTC, SeveNChaK commented on src/lesson3/task1/Loop.kt
> +    var res = n - 1
Не понял вопроса

2016-10-25 09:51 UTC, ice-phoenix requested changes

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val hour = hours * 60 * 60
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде. Это не час, это количество секунд в заданном количестве часов.

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val sagene = sagenes * 48
См. замечание выше

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val sx = abs(x1 - x2)
Зачем брать модуль перед возведением в квадрат?

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
Вместо `when { ... return ... return ... return ... }` лучше сделать `return when { ... }`

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        else -> return -1
Обратите внимание, что тесты для данной функции не проходят

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val r = Math.sqrt(sqr(Math.abs(y1 - y2)) + sqr(Math.abs(x1 - x2))) + r1
Зачем модуль перед возведением в квадрат?

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun brickPasses(a: Int, b: Int, c: Int, r: Int, s: Int): Boolean = ((((a <= r) && (b <= s)) || ((a <= s) && (b <= r))) || (((a <= r) && (c <= s)) || ((a <= s) && (c <= r))) || (((b <= r) && (c <= s))
Такой код лучше форматировать как
```
a && b
|| c && d
|| e && f
|| ...
```

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun NOD(x: Int, y: Int): Int {
* Функции в Котлине принято называть `camelCase`
* Данную функцию лучше назвать `gcd`

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n < 3) return result
Сколько раз будет выполнено тело цикла ниже, если `n < 3`? Имеет ли смысл данная проверка?

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var res = n - 1
Если мы ищем делители числа `n`, не равные `n`, какое максимальное значение может принимать любой другой делитель?

2016-10-25 09:51 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (count != 0) {
Зачем эта проверка? Что сделает код ниже, если `count == 0`?

2016-10-26 11:30 UTC, SeveNChaK commented on src/lesson2/task1/IfElse.kt
> +        else -> return -1
Проходит, у меня нигде нет сообщения об ошибке. Там два коммита почти сразу было, в первом не правильно, во втором все прошло.

2016-10-26 11:46 UTC, SeveNChaK commented on src/lesson3/task1/Loop.kt
> +    if (count != 0) {
Если равно нулю, то код возвращает последнюю цифру, иначе он возвращает нужную по порядку(с конца) цифру

2016-10-26 11:54 UTC, SeveNChaK commented on src/lesson3/task1/Loop.kt
> +    if (count != 0) {
Ненужные действия - исправил. В последней задачи тоже надо исправить, но поздно сообразил (после того как уже запушил), не стал лишний раз коммит делать.

2016-10-27 10:59 UTC, ice-phoenix requested changes
Все хорошо, за исключением нескольких замечаний

2016-10-27 10:59 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        else -> return -1
Да, прошу прощения, не заметил второго коммита

2016-10-27 10:59 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (r <= r2)
Лишние скобки вокруг выражения

2016-10-27 10:59 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        ((((a <= r) && (b <= s))
Много лишних скобок, которые можно убрать, если вспомнить о приоритете операций в Котлине

2016-10-27 10:59 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = (gcd(m, n) == 1)
Лишние скобки

2016-10-27 10:59 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var revertNumber = 0
Лучше `revertedNumber`

2016-10-27 10:59 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (count != 0) {
Нужна ли эта проверка?

2016-10-27 11:38 UTC, SeveNChaK commented on src/lesson3/task1/Loop.kt
> +    if (count != 0) {
Да, я вчера заметил, исправлю

2016-10-27 15:39 UTC, SeveNChaK commented
Готов сдать полностью Lesson 4, как только мы закончим с этим пулл реквестом.27.10.2016, 17:59, "Marat Akhin" <notifications@github.com>:@ice-phoenix requested changes on this pull request.

Все хорошо, за исключением нескольких замечаний

In src/lesson2/task1/IfElse.kt:
> \ No newline at end of file
+fun segmentLength(a: Int, b: Int, c: Int, d: Int): Int {
+    when {
+        (c >= a) && (d <= b) -> return d - c
+        (a >= c) && (b <= d) -> return b - a
+        c in a..b -> return b - c
+        d in a..b -> return d - a
+        else -> return -1

Да, прошу прощения, не заметил второго коммита



In src/lesson2/task2/Logical.kt:
> @@ -35,7 +43,10 @@ fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = TODO()
  * Вернуть true, если утверждение верно
  */
 fun circleInside(x1: Double, y1: Double, r1: Double,
-                 x2: Double, y2: Double, r2: Double): Boolean = TODO()
+                 x2: Double, y2: Double, r2: Double): Boolean {
+    val r = Math.sqrt(sqr(y1 - y2) + sqr(x1 - x2)) + r1
+    return (r <= r2)

Лишние скобки вокруг выражения



In src/lesson2/task2/Logical.kt:
> @@ -46,4 +57,10 @@ fun circleInside(x1: Double, y1: Double, r1: Double,
  * кирпич 4 х 4 х 4 пройдёт через отверстие 4 х 4.
  * Вернуть true, если кирпич пройдёт
  */
-fun brickPasses(a: Int, b: Int, c: Int, r: Int, s: Int): Boolean = TODO()
+fun brickPasses(a: Int, b: Int, c: Int, r: Int, s: Int): Boolean =
+        ((((a <= r) && (b <= s))

Много лишних скобок, которые можно убрать, если вспомнить о приоритете операций в Котлине



In src/lesson3/task1/Loop.kt:
> @@ -96,7 +137,7 @@ fun maxDivisor(n: Int): Int = TODO()
  * Взаимно простые числа не имеют общих делителей, кроме 1.
  * Например, 25 и 49 взаимно простые, а 6 и 8 -- нет.
  */
-fun isCoPrime(m: Int, n: Int): Boolean = TODO()
+fun isCoPrime(m: Int, n: Int): Boolean = (gcd(m, n) == 1)

Лишние скобки



In src/lesson3/task1/Loop.kt:
> @@ -131,7 +172,17 @@ fun cos(x: Double, eps: Double): Double = TODO()
  * Поменять порядок цифр заданного числа n на обратный: 13478 -> 87431.
  * Не использовать строки при решении задачи.
  */
-fun revert(n: Int): Int = TODO()
+fun revert(n: Int): Int {
+    var k = pow(10, digitNumber(n) - 1)
+    var revertNumber = 0

Лучше revertedNumber



In src/lesson3/task1/Loop.kt:
> @@ -166,4 +233,19 @@ fun squareSequenceDigit(n: Int): Int = TODO()
  * 1123581321345589144...
  * Например, 2-я цифра равна 1, 9-я 2, 14-я 5.
  */
-fun fibSequenceDigit(n: Int): Int = TODO()
+fun fibSequenceDigit(n: Int): Int {
+    var fibn = 0
+    var sum = 0
+    var count = 1
+    var number = 0
+    while (sum < n) {
+        fibn = fib(count)
+        count++
+        sum = sum + digitNumber(fibn)
+    }
+    count = sum - n
+    if (count != 0) {

Нужна ли эта проверка?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

2016-10-28 08:39 UTC, ice-phoenix commented
Все отлично, можете заливать 4 урок. Этот PR я закрываю, чтобы GitHub'у было попроще =)

2016-10-28 08:39 UTC, closed without merging

2016-10-28 11:12 UTC, SeveNChaK commented
Ураа:)28.10.2016, 15:39, "Marat Akhin" <notifications@github.com>:Все отлично, можете заливать 4 урок. Этот PR я закрываю, чтобы GitHub'у было попроще =)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.