Konev
Kotlin-Polytech/KotlinAsFirst2016 pull request #55
Opened 2016-09-13 13:18 UTC by nolit1

2016-09-13 13:29 UTC, maximpetrov commented
recheck all

2016-09-13 19:12 UTC, gagarski commented
recheck all

2016-09-13 19:18 UTC, gagarski commented on .gitignore
> -# Created by .ignore support plugin (hsz.mobi)
Зачем вы удалили .gitignore?
Из-за этого в ваши коммиты попадают изменения конфигурации среды разработки, которые не имеют отношения к решению задач.

2016-09-13 19:19 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad+min/60.0+sec/3600.0)/57.2958
Ваша константа для деления задана недостаточно точно. Используйте константу  `PI` из класса `Math`.

2016-09-15 10:17 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +if (((kingX==rookX1)||(kingY==rookY1))&&(kingX==rookX2||(kingY==rookY2))) return(3)
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-15 10:18 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX) || (kingY == rookY)) && ((kingX - bishopX) == (kingY - bishopY))) return(3) else
`else` в цепочке ветвлений принято переносить на новую строку вместе со следующим `if`:
```kotlin
if (someCondition) someAction()
else if (someOtherCondition) someOtherAction()
else anotherAction()
```
или так:
```kotlin
if (someCondition) 
    someAction()
else if (someOtherCondition) 
    someOtherAction()
else 
    anotherAction()
```
В таком случае среда разработки будет сама правильно форматировать код и вам не придётся двигать "лесенку" влево руками.

2016-09-15 10:19 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +     * Средняя
- В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков.

2016-09-15 10:19 UTC, gagarski requested changes

2016-09-15 22:08 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> -    if (((kingX == rookX) || (kingY == rookY)) && ((kingX - bishopX) == (kingY - bishopY))) return(3) else
[Здесь и далее] `return` - это оператор, а не функция. Скобки вокруг возвращаемого значения не нужны:  `return 3`

2016-09-15 22:09 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX) || (kingY == rookY)) && ((Math.abs(kingX - bishopX)) == Math.abs(kingY - bishopY))) return(3) else
См. замечания к предыдущим коммитам про `else if` и форматирование.

2016-09-15 22:09 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        if ((a>b+c || b>a+c || c>a+b)) return(-1)
См. замечания к предыдущим коммитам про `else if` и форматирование.

2016-09-15 22:09 UTC, gagarski requested changes

2016-09-17 12:04 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    val put: Double = ((s1 + s2 + s3) / 2.0)
- Постарайтесь избегать использования транслитерации в именах переменных.

2016-09-17 12:05 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +     * Простая
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-17 12:06 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +if (((kingX==rookX1)||(kingY==rookY1))&&(kingX==rookX2||(kingY==rookY2))) return(3)
[Здесь и везде] `return` - это оператор, а не функция. Скобки вокруг возвращаемого значения не нужны: `return 3`

2016-09-17 12:06 UTC, gagarski requested changes

2016-09-17 12:07 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    return age.toString() + " лет"
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-18 14:42 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +        ((a<=r && b<=s) || (a<=s && b<=r))
Условие можно сильно упростить если заранее найти минимальные стороны кирпича.

2016-09-18 14:42 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +        ((x1 + r1 == x2 + r2) && (x1 - r1 == x2 - r2) && (y1 + r1 == y2 + r2) && (y1 - r1 == y2 - r2)) ||
Вспомните уравнение окружности, попробуйте сделать чертёж на бумаге, условие можно записать **гораздо** проще.

2016-09-18 14:43 UTC, gagarski requested changes

2016-09-22 11:29 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    do { count++
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-22 11:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (n > 2) k = ((fib(n - 1) + fib(n - 2))) else k = 1
- Рекурсивное решение напрашивается, исходя из определения чисел Фибоначчи, но попробуйте посчитать, к скольки вызовам функции `fib()` приведёт вызов `fib(10)`, `fib(40)`, `fib(55)`, сколько среди них вызовов с одинаковыми аргументами и решить задачу более оптимальным способом.

2016-09-22 11:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var own: Int = 1
Почитайте про алгоритмы поиска НОК. Есть более эффективные методы, чем полный перебор.

2016-09-22 11:31 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (k in 2..n) {if (n%k == 0) break
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-22 11:31 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (k in n-1 downTo 1) {if (n%max == 0) break
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-22 11:32 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (m < 2 || n < 2) return false
Эту задачу можно решить в одну строку, применив одну из функций, написанную вами выше.

2016-09-22 11:32 UTC, gagarski requested changes

2016-09-22 11:33 UTC, gagarski commented
Пройдитесь пожалуйста по замечаниям и исправьте их.

2016-09-28 22:35 UTC, gagarski requested changes

2016-09-28 22:35 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (n - k == 0) return true else return false
Здесь комбо из ненужных усложнений:
 - Зачем проверять на `n - k == 0`, если можно на`n == k`
 - `if` здесь не нужен. Можно написать просто `return n == k`

2016-09-28 22:35 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if ((m * n).toDouble() / nok == 1.0) return true
- Сравнивать результат операции в Double с другим числом типа Double - очень плохая идея
 - (даже если забыть про предыдущий пункт) Зачем делить их друг на друга?
 - Зачем вообще преобразовывать их в `Double`?

Предыдущее решение хоть и было менее эффективным, но хотя бы без проблем, связанных со сравнением Double.

2016-09-28 22:35 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if (Math.sqrt(k.toDouble()) * 10 % 10 == 0.0) break
- Зачем вы делаете `* 10 % 10`?
 - Точное сравнение Double на равенство - это плохая идея

2016-09-28 22:37 UTC, gagarski requested changes

2016-09-28 22:37 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var string1: String = ""
Для больших `n` вы генерируете строку огромной длины. Решите задание без использования строк или хотя бы без хранения всей последовательности цифр.

2016-09-29 06:44 UTC, nolit1 commented on src/lesson3/task1/Loop.kt
> +    var string1: String = ""
Постараюсь по-максимуму исправить

2016-09-29 07:11 UTC, nolit1 commented on src/lesson3/task1/Loop.kt
> +    if ((m * n).toDouble() / nok == 1.0) return true
fun isCoPrime(m: Int, n: Int): Boolean {
    val nok = lcm(m, n)
    if ((m * n) / nok == 1) return true
    else return false
}

Можно ли так сделать? Я по формуле делал (НОК(a, b)=a·b:НОД(a, b)), в IDEA это работает

2016-09-29 16:33 UTC, gagarski requested changes

2016-09-29 16:33 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if ((m * n) / nok == 1) return true
- Зачем вы делите? Из-за этого у вас ошибка (тут же целочисленное деление)
 - Снова `if (...) true else false`

2016-09-29 16:43 UTC, nolit1 commented on src/lesson3/task1/Loop.kt
> +    if ((m * n) / nok == 1) return true
Хорошо, сейчас посмотрю. Я просто хотел сейчас сдать сложную задачу ( И о, Господи, она работает), поэтому от этой задачи отошёл

2016-09-29 17:00 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if ((m * n).toDouble() / nok == 1.0) return true
> Я по формуле делал (НОК(a, b)=a·b:НОД(a, b)), в IDEA это работает

Лучше примените эту формулу при вычислении НОК (я там писал вам замечание про неэффективность). Посчитайте НОД более эффективным алгоритмом (Гугл в помощь), а из него НОК. Заодно у вас появится функция НОД, которую вы сможете использовать здесь.

2016-09-30 21:40 UTC, gagarski requested changes

2016-09-30 21:40 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        if (sqr(a) > sqr(b) + sqr(c)) return (2) else if (sqr(a) == sqr(b) + sqr(c)) return (1)
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-30 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in 0..v.size - 1) {
[Здесь и далее] Если в теле цикла индекс вам не нужен, то можно обойтись без него:
```kotlin
for (elem in v) {
    // elem - текущий элемент
}
```

2016-09-30 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        number += sqr(v[i].toString().toDouble())
Зачем `.toString().toDouble()`?!

2016-09-30 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in 0..list.size - 1) {
См. замечания к `abs()`

2016-09-30 21:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.size != 0) {
- См. замечания к `abs`
 - `list.size == 0` здесь нет необходимости рассматривать как особый случай (и в вашем цикле и в `for (elem in list)` вы просто не попадёте в тело цикла, если длина списка равна нулю)

2016-09-30 21:41 UTC, gagarski commented
Исправьте предыдыщие ошибки и замечания, прежде чем делать новые задания. Если будут вопросы и ответы по замечаниям - задавайте.

2016-10-01 05:20 UTC, nolit1 commented
Спасибо за замечания. Вчера вечером исправлял и оптимизировал задачи. Понял как делать все намного проще и короче

2016-10-02 17:24 UTC, nolit1 commented
Помогите пожалуйста, каким способом лучше решать эту задачу?
 fun accumulate(list: MutableList<Double>): MutableList<Double> (4 lesson)
Я просто много всего перепробовал, но либо получается слишком большой код, либо просто не работает

2016-10-03 06:54 UTC, nolit1 commented
Задачу из 2 урока случайно изменил, вечером исправлю и попробую оптимизировать , как писали ранее

2016-10-03 16:42 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var string1: String = ""
исправлено

2016-10-03 16:43 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if (Math.sqrt(k.toDouble()) * 10 % 10 == 0.0) break
актуально

2016-10-03 16:43 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var own: Int = 1
актуально

2016-10-03 16:43 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (n > 2) k = ((fib(n - 1) + fib(n - 2))) else k = 1
актуально

2016-10-03 16:43 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +        ((x1 + r1 == x2 + r2) && (x1 - r1 == x2 - r2) && (y1 + r1 == y2 + r2) && (y1 - r1 == y2 - r2)) ||
актуально

2016-10-03 16:52 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for ((index, elem) in list.withIndex()) {
Выглядит почти правильно, но подумайте о краевых условиях (посмотрите на исключение, которое бросается). Возможно тут как раз тот случай, когда есть смысл перебирать индексы списка в цикле.

2016-10-03 16:54 UTC, nolit1 commented on src/lesson4/task1/List.kt
> +    for ((index, elem) in list.withIndex()) {
Спасибо, посмотрю

2016-10-03 16:55 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    return Math.abs(Math.sqrt((v.map { it * it }).sum()))
Вспомните примеры однострочных функций из первого урока. Они не только позволяют вам сэкономить около десятка символов на скобки и `return`, но и позволяют не писать тип возвращаемого значения у функции:
```kotlin
fun abs(v: List<Double>) = Math.abs(Math.sqrt((v.map { it * it }).sum()))
```

2016-10-03 18:37 UTC, nolit1 commented
А можно как-то поменять порядок элементов в списке, то есть [1,4,5,6] -> [6,5,4,1]?

2016-10-05 19:30 UTC, nolit1 commented
Задача convertToString. Я уверен, что этот список, что я сделал, можно сократить в одну строчку, по типу для 10-35 заменить на a-z, как - не знаю. По крайней мере оно работает.  И, да, я не знаю, почему список назвал "dogs", сделал, потом хотел заменить на что-то нормальное, в итоге забыл. На работу не влияет, но всё же.

2016-10-06 09:19 UTC, gagarski requested changes

2016-10-06 09:19 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            dogs[i] == 10 -> string1 += "a"
- Можно воспользоваться тем, что в любой кодировке латинские символы хранятся друг за другом, а также тем, что к символу можно прибавлять число: `'a' + 1 == 'b' ` и т. д.
 - Конкатенация строк в цикле довольно неэффективна: при каждом `+=` предыдущая строка копируется. Эффективнее будет использовать список, а затем вызвать на нём метод `joinToString`.

2016-10-06 09:19 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val dogs = convert(n, base).toMutableList()
Зачем `toMutableList`?

2016-10-06 09:19 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    return polynom(a.reversed(), base.toDouble()).toInt()
- Старайтесь избегать операций с числами с плавающей точкой в целочисленных задачах, чтобы не столкнуться с ошибками округления.

2016-10-24 14:38 UTC, gagarski commented
recheck all

2016-10-24 14:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    return polynom(a.reversed(), base.toDouble()).toInt()
Актуально.

2016-10-24 14:43 UTC, gagarski commented
recheck all

2016-10-24 15:00 UTC, gagarski requested changes

2016-10-24 15:00 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        if (str[i].hashCode() > 57) {
- Что, по-вашему, вовзращает `hashCode()` от `Char`?
 - Что такое 57?

2016-10-24 15:00 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            list += 9 + str[i].hashCode() - 96
Что такое 96?

2016-10-24 15:00 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val listDigit = listOf(1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1)
Лучше список из пар или Map, чем два отведльных списка, неявно связанных индексом.

2016-10-24 15:00 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (number % 100 == 0) Double.NaN else {
Отформатируйте `if - else if - else` пожалуйста

2016-10-24 15:00 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +    if (phone.contains(Regex("""[^-+\d)(\s]"""))) return "" else {
- Отформатируйте `if - else if - else`
 - Вы используете Regex'ы для задач, которые можно решить проще и понятнее без них.

2016-10-26 10:08 UTC, gagarski requested changes

2016-10-26 10:08 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        divisor = minDivisor(number)
Вызывая `minDivisor`, вы в каждой итерации ищете минимальный делитель, начиная с 2. Можно искать его начиная с текущего делителя.

2016-10-29 21:18 UTC, nolit1 commented on src/lesson4/task1/List.kt
> +        divisor = minDivisor(number)
Я не понимаю.

2016-11-01 13:02 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        divisor = minDivisor(number)
`minDivisor` каждый раз ищет минимальный делитель перебором, начиная с 2. 
После того, как вы поделили, например, на 157, нет смысла перебирать числа с 2 до 156.

2016-11-08 12:28 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var own: Int = 1
актуально

2016-11-08 12:28 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if (Math.sqrt(k.toDouble()) * 10 % 10 == 0.0) break
актуально

2016-11-08 12:41 UTC, gagarski requested changes

2016-11-08 12:41 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (n > 2) {k = ((fib(n - 1) + fib(n - 2)))
А почему не просто `fib(n)`?!

2016-11-08 12:41 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val list = convert(n, base).toMutableList()
Зачем `toMutableList()`, если вы его потом не изменяете?

2016-11-08 12:41 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    return polynom(a.reversed(), base.toDouble()).toInt()
- Старайтесь избегать операций с числами с плавающей точкой в целочисленных задачах, чтобы не столкнуться с ошибками округления.

2016-11-08 12:41 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +import com.sun.javafx.binding.StringFormatter
- Зачем этот импорт?
 - Старайтесь не импортировать ничего из пакетов `com.sun.*` и `sun.*`: http://stackoverflow.com/questions/1834826/it-is-a-bad-practice-to-use-suns-proprietary-java-classes

2016-11-08 12:41 UTC, gagarski commented on test/lesson5/task1/Tests.kt
> +        assertEquals(2147483647, bestLongJump("1417255715 - - 819359384 - % - 1 2147483647 % - 813219160 2147483647 - 2147483647 0 % - 2147483647 - - 1026951656 % - % - 0 1291512751 - - 1 - - - - 214
Поэкспериментируйте с последовательностями из нескольких пробелов в разных местах. Скорее всего, Гитхаб потерял их из тестовой строки.

2016-11-08 12:42 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (n > 2) k = ((fib(n - 1) + fib(n - 2))) else k = 1
актуально

2016-11-08 12:45 UTC, gagarski reviewed
Просмотрите внимательно замечания к 3 уроку [тут](https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/55/files). Там ещё осталось кое-что.

2016-11-08 12:45 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (k in 2..n) {
Можно ли уменьшить верхнюю границу перебора? А ещё сильнее, чем `n / 2`?

2016-11-08 12:45 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var max: Int = n - 1
Можно ли уменьшить верхнюю границу перебора? А ещё сильнее, чем `n / 2`?

2016-11-08 12:45 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean {
После исправления НОД/НОК можно решить задачу с помощью них.

2016-11-27 13:23 UTC, gagarski commented
6 и 7 урок пока не смотрел потому что всё ещё есть неисправленные замечания к ранним урокам.

2016-11-27 14:00 UTC, nolit1 commented
Написал 6 и 7 чтобы получить зачет. Замечания буду исправлять, времени нет свободного просто.

2016-11-27 14:03 UTC, nolit1 commented
Все замечания, конечно, читаю и принимаю во внимание

2016-11-27 14:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    return polynom(a.reversed(), base.toDouble()).toInt()
Стоит отметить, что кроме указанной проблемы с Double, сам подход к решению очень хорош.

2016-11-27 14:55 UTC, nolit1 commented on src/lesson4/task1/List.kt
> +    return polynom(a.reversed(), base.toDouble()).toInt()
Функция polynom требует, чтобы число было типа double. Лишь поэтому в данной задаче я сначала преобразую в double

2016-11-27 15:16 UTC, nolit1 commented
А почему у меня написано это?:
Author: Nolit1 [kj2806@mail.ru]

Owner: nolit1 []

Total: 21 / 57

Example: 9 / 9
Trivial: 1 / 1
Easy: 3 / 8
Normal: 6 / 18
Hard: 2 / 17
Impossible: 0 / 4

У меня ведь засчитаны намного больше задач. Откуда эти цифры?

2016-11-27 15:29 UTC, gagarski commented
> У меня ведь засчитаны намного больше задач. Откуда эти цифры?

Это итог по задачам, упомянутым в том комментарии (уроки 5-7).

2016-11-27 15:29 UTC, gagarski commented
recheck all

2016-11-27 15:46 UTC, gagarski commented
Верните пример `isPrime` в исходное состояние пожалуйста. Из-за ваших изменений не перепроверить все задания из-за таймаута :(

2016-11-27 20:08 UTC, gagarski commented
`isPrime` всё ещё изменён вами: смотрите [изменённые файлы](https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/55/files)

2016-11-27 20:14 UTC, nolit1 commented
Я правильно понимаю, так должно быть?
fun isPrime(n: Int): Boolean {
      if (n < 2) return false
     for (m in 2..Math.sqrt(n.toDouble()).toInt()) {
          if (n % m == 0) return false
      }
      return true

2016-12-01 13:26 UTC, nolit1 commented
Я сейчас исправил баги и некоторые моменты изменил совсем. Теперь всё работает, проверял неоднократно. Можете ли посмотреть и, если правильно, то засчитать работу?

fun main(args: Array<String>){
    println(exam(7))
    println(exam(9))
    println(exam(35))
}

fun exam(n: Int): MutableList<Int> {
    val result2 = mutableListOf<Int>()
    val list = mutableListOf(1,1)
    while(list[list.size - 1] - 1 < n){
        list.add(list[list.size - 1] + list[list.size - 2])
    }
    for (i in  list.size - 1 downTo 0) {
        result2.add(list[i])
        if (result2.sum() > n)
            result2[ result2.size - 1] = 0
    }

    if (result2.sum() != n)
        throw IllegalArgumentException()
    for (i in 0..result2.size - 1) {
        if (result2[i] != 0)
            result2[i] = 1
    }
    return result2.reversed().toMutableList()
}

2016-12-05 13:14 UTC, gagarski commented
recheck all

2016-12-05 13:34 UTC, gagarski requested changes

2016-12-05 13:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var own: Int = 1
Вы уже реализовали вычисление НОД. Используйте его здесь.

2016-12-05 13:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if (Math.sqrt(k.toDouble()) * 10 % 10 == 0.0) break
- Зачем вы делаете `* 10 % 10`?
- Точное сравнение Double на равенство - это плохая идея

2016-12-05 13:34 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    return polynom(a.reversed(), base.toDouble()).toInt()
Думаю, что за элегантность решения я готов закрыть глаза на проблемы с Double в данной задаче, но исходное замечание следует иметь в виду.

2016-12-05 13:34 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +            for (i in 0..parts.size-1) {
Посмотрите в сторону функции `parts.removeAll {}` (ту, что принимает функцию-предикат как аргумент).

2016-12-05 13:34 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +fun bestLongJump(jumps: String): Int {
Фомратирование.

2016-12-05 13:43 UTC, gagarski requested changes

2016-12-05 13:43 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        val sb = StringBuilder()
Протестируйте ваш `toString`и сделайте так, чтобы вовзвращаемое им значение было читаемо человеком.

2016-12-13 16:18 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        val sb = StringBuilder()
done

2016-12-13 16:19 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +fun bestLongJump(jumps: String): Int {
fixed

2016-12-13 16:31 UTC, gagarski requested changes

2016-12-13 16:31 UTC, gagarski commented on src/lesson8/task1/Files.kt
> +    val result = mutableMapOf<String, Int>()
Форматирование

2016-12-13 16:31 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    if (matrix.height == 1 && matrix.width == 1) return M
Нужно ли рассмотрение данного особого случая?

2016-12-13 16:36 UTC, gagarski requested changes

2016-12-13 16:36 UTC, gagarski commented on src/lesson8/task1/Files.kt
> +                if (string.toLowerCase() in textResult.toLowerCase()) count += textResult.toLowerCase().split(string.toLowerCase()).size - 1
Вы вызываете `textResult.toLowerCase()` 2*substrings.size раз. Вызовите его вне цикла.

2016-12-13 20:39 UTC, nolit1 commented
У меня произошли проблемы с idea. В итоге я загрузил файл со своим проектом с git hub. Вроде бы всё стало хорошо, как минимум оно начало работать. Но пропали кнопки тестов (зелёные треугольники) и не подсвечиваются никакие ошибки (синтаксис и т.п.) Скажите, пожалуйста, что можно сделать?

2016-12-14 09:48 UTC, gagarski commented
После импорта Идея выдаёт сообщение "Non-managed pom.xml file found" (оно всплывает внизу после импорта, либо его можно найти в Event Log). Нужно нажать "Add as Maven Project".

После этого возможно появится сообщение "Project SDK is not defined", нужно выбрать SDK для проекта.

Если это не поможет, завтра посмотрим.

2016-12-18 12:27 UTC, gagarski commented
recheck all

2016-12-18 12:32 UTC, gagarski commented
Обратите внимание на падающий тест в  `lesson6.task2/square`.

Скорее всего вы не обрабатываете ошибки со слишком короткими строками.

2016-12-18 14:14 UTC, nolit1 commented
Хорошо, завтра исправлю эту программу, спасибо

2016-12-19 15:50 UTC, gagarski commented
Также, скорее всего, `countSubstrings` неправильно посчитает подстроки, если в файле есть пересекающиеся подстроки. Например, "бб" содержится в строке "ббб" два раза. Добавьте соответствующие тесты к данной функции и исправьте её, если она работает неправильно.

Исправьте `square` и `countSubstrings` до начала занятия и вы получите оценку "отлично".

2016-12-19 17:00 UTC, nolit1 commented
Понял, спасибо, сегодня сделаю

2016-12-20 11:49 UTC, gagarski commented
Хотелось бы чтобы вы всё-таки решили `countSubstrings`

2016-12-20 11:49 UTC, gagarski approved these changes

2016-12-20 12:13 UTC, nolit1 commented
Обязательно доработаю эту задачу, только с долгами сейчас разберусь...

2016-12-20 12:42 UTC, gagarski commented
Сделаете до конца занятия в четверг - получите "отлично" =)

2016-12-20 12:48 UTC, nolit1 commented
Хорошо. Скажите, а где нужно прописывать свой вариант для теста? Просто задача ведь берёт текст из файла. Или как лучше это сделать?

2016-12-20 12:51 UTC, gagarski commented
Вы можете создать новый входной файл в каталоге `input`. Дальше - смотрите примеры уже созданных тестов.

2017-07-26 18:24 UTC, closed without merging