Lesson2Task2
Kotlin-Polytech/KotlinAsFirst2016 pull request #56
Opened 2016-09-13 13:39 UTC by MoshkinAlexey

13.09.2016

2016-09-13 17:04 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    var Str = "$age"
Переменные принято называть с маленькой буквы.

2016-09-13 18:08 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        num = n%10 * Math.pow(10.0, count.toDouble()).toInt()
Старайтесь избегать операций с числами с плавающей точной в целочисленных задачах.
В Java и Kotlin нет функции для целочисленного возведения в степень, но вы можете произвести эту операцию в вашем цикле `while` вместо подсчёта количества цифр.

2016-09-13 18:09 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        return number == numLast && isPalindrome( (n-number*Math.pow(10.0, pow.toDouble()).toInt())/10 )
То же замечание про числа с плавающей точкой, что и в функции `revert()`.

2016-09-13 18:40 UTC, gagarski commented
recheck all

2016-09-14 11:47 UTC, ice-phoenix commented
recheck all

2016-09-14 12:02 UTC, ice-phoenix commented
recheck all

2016-09-14 13:18 UTC, gagarski commented
recheck all

2016-09-14 16:38 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        for (j in 0..i - 1) sum += list[j]
На каждой итерации вы пересчитываете сумму начала списка. Сделайте так, чтобы время решения линейно (а не квадратично) зависело от длины списка.

2016-09-14 16:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String {
Данная задача может быть решена с использованием реализованной вами функции `factorize`.

2016-09-14 16:41 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var string = ""
Данная задача может быть решена с использованием реализованной вами функции `convert`.

2016-09-14 16:43 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var sum = 0
Данная задача может быть решена с использованием реализованной вами функции `decimal`.

2016-09-14 16:44 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val listStr1 = listOf("сто", "двести", "триста", "четыреста", "пятьсот", "шестьсот", "семьсот", "восемьсот", "девятьсот")
- Переменным лучше давать говорящие имена.

2016-09-14 16:45 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val Thousands = listOf("тысяча", "тысячи", "тысяч")
Переменные принято называть с маленькой буквы.

2016-09-14 16:53 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val listDigs = listOf(1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000)
Почитайте про ассоциативные массивы (`Map`) и функции `mapOf()` и `linkedMapOf()`

2016-09-14 17:00 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (string.length > 0 && string[0] == ' ') string = string.substring(1, string.length)
Для этого у строки есть метод `trim()`

2016-09-14 17:08 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        number -= number / 100 * 100
Подумайте, какую базовую арифметическую операцию вы реализуете этой строкой.

2016-09-14 17:22 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (num%max != 0){
- Может ли НОК быть меньше чем максимальное число?
 - Почитайте про стандартные алгоритмы нахождения НОД/НОК

2016-09-14 17:26 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..Math.min(m, n)){
Подумайте про связь данной задачи с предыдущими и про свойства взаимно простых чисел.

2016-09-14 17:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var result = x
Протестируйте вашу реализацию синуса на больших числах (в районе десятков или сотен PI). Правильно ли ваше решение? Попробуйте понять почему и придумать, как это исправить.

2016-09-14 17:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var result = 1.0
См. коммент к синусу.

2016-09-14 17:53 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int = if (n < 3) 1 else fib(n-2) + fib(n-1)
Рекурсивное решение напрашивается, исходя из определения чисел Фибоначчи, но попробуйте посчитать, к скольки вызовам функции `fib()` приведёт вызов `fib(10)`, `fib(40)`, `fib(55)` и решить задачу более оптимальным способом.

2016-09-17 20:25 UTC, gagarski commented
Постарайтесь исправить текущие замечания и ошибки прежде чем приступать к следующим урокам.

2016-09-18 10:53 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(value) > 2*Math.PI) {
В Java и Kotlin есть операция взятия остатка от деления для Double.

2016-09-18 10:53 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(value) > 2*Math.PI) {
В Java и Kotlin есть операция взятия остатка от деления для Double.

2016-09-18 10:55 UTC, gagarski requested changes

2016-09-18 12:15 UTC, MoshkinAlexey commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(value) > 2*Math.PI) {
Не знал, спасибо. Сделал с её помощью

2016-09-18 14:30 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +import com.sun.org.apache.xpath.internal.operations.Bool
Избегайте ненужных импортов.

2016-09-18 14:31 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        num = n%10 * Math.pow(10.0, count.toDouble()).toInt()
Всё ещё актуально.

2016-09-18 15:54 UTC, MoshkinAlexey commented
Почему в последней задаче 5го урока можно прибавлять и вычитать значения из несуществующей ячейки?
Inputs:
    cells -> 0
    commands -> - --+

2016-09-19 12:05 UTC, gagarski commented
recheck all

2016-09-19 12:10 UTC, gagarski commented
>Почему в последней задаче 5го урока можно прибавлять и убавлять значение в несуществующей ячейке?
Inputs:
cells -> 0
commands -> - --+

Тесты исправлены, но и у вас тоже ошибка. Во-первых, в задании сказано, какое исключение нужно бросать в этом случае. Во-вторых, над пустой лентой можно запускать пустой список команд.

2016-09-19 13:15 UTC, gagarski commented
recheck all

2016-09-19 13:22 UTC, gagarski commented
recheck all

2016-09-21 16:25 UTC, gagarski commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String {
done

2016-09-21 16:25 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        return number == numLast && isPalindrome( (n-number*Math.pow(10.0, pow.toDouble()).toInt())/10 )
актуально

2016-09-21 16:27 UTC, gagarski commented
> [Hard] lesson5.task1/computeDeviceCells
Expected: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Actual: null
Inputs:
cells -> 310
commands ->
Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: 0

Тут ваш баг.

> [Hard] lesson5.task1/computeDeviceCells
Expected: java.lang.IllegalStateException: -1 is out-of-bounds for [0,310)
Actual: null
Inputs:
cells -> 310
commands -> <}-]<+[<>+}-<]-[-}+- ++-++ [ <<[<[]<{+>+< --<---}-<+]<<<-<<>+<< +<<--+<- +-+<{--}- -+--<+-+----}<+-]-----+<-+]-{-+[-<++-+----+-<- --}[}++<}- +-+->><+>< +---><+<-+--++----[--->-<[---<-{[+-}+<
Exception: java.lang.IllegalArgumentException

А тут наш.

2016-09-21 16:36 UTC, gagarski commented
recheck all

2016-09-22 09:58 UTC, MoshkinAlexey commented
[Hard] lesson5.task1/firstDuplicateIndex

    Expected: 7
    Actual: -1
    Inputs:
        str -> 1a ^ ^ m d9 ? eW x.H F W t 6 4 7rI 9
    Exception: null

А какое тут слово повторяется с 7 символа?

2016-09-22 10:00 UTC, MoshkinAlexey commented
[Hard] lesson5.task1/computeDeviceCells

    Expected: java.lang.IllegalStateException: -1 is out-of-bounds for [0,310)
    Actual: null
    Inputs:
        cells -> 310
        commands -> ++--}+--<- ---<<{+
    Exception: java.lang.IllegalArgumentException
"}" и "{" не имеют пары, кинуто исключение IllegalArgumentException, вроде всё как надо

2016-09-22 11:47 UTC, gagarski commented
> А какое тут слово повторяется с 7 индекса?
Тут дело было в повторяющихся пробелов. Скорее всего на входе было что-то вроде `1a     ^   ^ m d9 ? eW x.H F W t 6 4 7rI 9`, но ГитХаб убрал лишние пробелы. Поскольку по заданию повторяющихся пробелов быть не должно, исправлено.

2016-09-22 11:47 UTC, gagarski commented
recheck assignment

2016-09-22 11:48 UTC, gagarski commented
recheck assignment

2016-09-22 12:11 UTC, gagarski commented
> [Hard] lesson5.task1/computeDeviceCells
Expected: java.lang.IllegalArgumentException: No pair for bracket
Actual: null
Inputs:
cells -> 1
commands -> -{-+{<-[>->>]]-{->-
Exception: java.lang.IllegalStateException

А теперь у вас баг.

2016-09-22 12:13 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +    val mounths = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
`months`

2016-09-22 12:13 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +    val mounth: Int
`month`

2016-09-22 12:17 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +            if ((i in intChars || i in allowedChars) == false) return -1
Помимо оператора `in` есть оператор `!in`. Применив закон де Моргана можно упростить условие:
```kotlin
if (i !in intChars && i !in allowedChars) return -1
```

2016-09-22 12:19 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +            if ((i in intChars || i in allowedChars) == false) return -1
Далее то же самое в нескольких местах

2016-09-22 12:22 UTC, gagarski approved these changes

2016-09-22 12:22 UTC, gagarski commented
recheck all

2016-09-22 12:24 UTC, gagarski commented
recheck all

2016-09-30 22:46 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var string = ""
done

2016-09-30 22:50 UTC, gagarski requested changes
(не заметил ранее)

2016-09-30 22:50 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        sum += digits[i] * Math.pow(base.toDouble(), (digits.size - i - 1).toDouble()).toInt()
Это задача с целыми числами, не следует в таких переходить к Double без необходимости. Реализуйте `pow` для целых чисел, либо вычисляйте `base ^ n` в вашем цикле.

2016-09-30 22:52 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        sum += digits[i] * Math.pow(base.toDouble(), (digits.size - i - 1).toDouble()).toInt()
В `isPalindrome` пока висит такое же замечание

2016-10-03 14:14 UTC, gagarski commented
recheck all

2016-10-03 14:19 UTC, gagarski commented
Из старого:
Осталось замечание про `Double` в `isPalindrome`.
Также не проходят тесты для `computeDeviceCells`

2016-10-03 15:05 UTC, gagarski approved these changes

2016-10-03 16:34 UTC, gagarski requested changes

2016-10-03 16:34 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +    val signX = listOf(-2, -2, -1, -1, 1, 1, 2, 2)
В `signX` и `signY` хранятся возможные ходы коня. Связывать их только индексом в соседних списках - плохой стиль.
Лучше хранить их в одном списке:

``` kotlin
val moves = listOf(Pair(-2, -1), Pair(-2, 1) /* ... */)
```

2016-10-03 16:34 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +    val signX = listOf(-2, -2, -1, -1, 1, 1, 2, 2)
`listOf(Pair()...)`

2016-10-03 16:34 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +    while (curSq != start) {
Сможете ли вы объяснить, почему такой подход работает (сначала сложить ходы в формате "из X в Y" в список, а потом пройтись по этим парам и составить путь). Почему в результате получается **кратчайший** путь?

2016-10-05 12:55 UTC, MoshkinAlexey commented
А строку команд нужно сразу проверять на правильность или в процессе выполнения команд?
И ещё вопрос, в тестах есть такой: assertEquals(listOf(IllegalArgumentException()), computeDeviceCells(1, "-{-+{<-[>->>]]-{->-"))
Если сразу не проверять на правильность строку команд, то разве не должно бросить исключение IllegalStateException() ? Так как '{' и '[' по условию воспринимаются только если под датчиком 0, или я не прав?
Преобразования значения под датчиком:
0  >  -1  >  -2  >  -1  >  IllegalStateException()

2016-10-05 15:35 UTC, gagarski commented
recheck all

2016-10-05 15:40 UTC, gagarski commented
> А строку команд нужно сразу проверять на правильность или в процессе выполнения команд?

Возможно в задании это сформулировано недостаточно чётко. Убрал генерацию программ с непарными скобками. Но у вас всё равно баг.
>[Hard] lesson5.task1/computeDeviceCells
java.lang.IllegalArgumentException : null
[Hard] lesson5.task1/computeDeviceCells
Expected: java.lang.IllegalStateException: -1 is out-of-bounds for [0,649)
Actual:
Inputs:
cells -> 649
commands -> +<[-<]--+<<+>-<->++-+[+< <--<<+]<+[<+--+<+---+><<<+>-]+<{}-+<-{<>-<- >- <+-+<--<-[>-+<-+--+} +<-<----{-<+<-><+<+<-<}<- +->] <<-<-+[-+-]< >--{+ -++-----[<-<+ -<<-}><<+-<-<-++--<-<-<+< -]-+{<--+}
Exception: java.lang.IllegalArgumentException

2016-10-06 09:40 UTC, gagarski commented
> [Hard] lesson5.task1/plusMinus
Expected: java.lang.IllegalArgumentException: java.lang.NumberFormatException: For input string: "-"
Actual: 0
Inputs:
* expression ->

Здесь неправильный результат при вызове `plusMinus(" -")`

2016-10-06 09:48 UTC, gagarski requested changes

2016-10-06 09:48 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +    val signX = listOf(-2, -2, -1, -1, 1, 1, 2, 2)
`listOf(Pair()...)`

2016-10-06 09:48 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +        if (opList.indexOf(op) % 2 == 0) sign = -1 else sign = 1
`opList.indexOf(op) % 2 == 0` - излишне запутанный способ определения открывающей скобки. Лучше просто `op =='[' || op == '{'`.

2016-10-06 16:09 UTC, MoshkinAlexey commented
не работает фунцкия crossPoint

2016-10-27 00:51 UTC, MoshkinAlexey commented
recheck all

2016-10-27 00:56 UTC, MoshkinAlexey commented
recheck all

2016-10-27 20:41 UTC, MoshkinAlexey commented
Как решать последнюю задачу в 6-1?

Ищем самые удалённые точки. Из центра отрезка между этими точками ищем наиболее удалённую. Строим окружность по этим трём точкам.
Такое решение неправильное?

2016-11-01 14:01 UTC, gagarski requested changes

2016-11-01 14:01 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    val angle = if (xDist == 0.0 && yDist == 0.0) 0.0
Нужно ли это? `Math.atan()` нормально работает с нулём и бесконечностью. Случай, когда `xDist == 0.0 && yDist == 0.0` является некорректным (можно построить бесконечное число прямых), такие тесты у нас не генерируются.

2016-11-01 14:01 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +        addSquare()
Ваш `addSquare` излишне запутывает довольно простую функцию. По сути вы имитируете передачу в неё аргументов через локальные переменные. Если три раза сделать `list.add()`, то ваша функция станет понятнее.

2016-11-01 14:01 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +        var log = false
Почитайте [про метки циклов](https://kotlinlang.org/docs/reference/returns.html) и избавьтесь от переменной `log`.

2016-11-01 14:01 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +        addSquare()
См. `rookTrajectory` про `addSquare()`

2016-11-01 15:42 UTC, gagarski commented
> Такое решение неправильное?

Ваше решение, во-вервых, выдаёт окружность большего радиуса, чем ожидаемый, во-вторых, ваша окружность содержит не все точки из списка (можете проверить).

2016-11-08 14:27 UTC, gagarski commented
recheck all

2016-11-08 14:29 UTC, gagarski commented
recheck all

2016-11-08 14:29 UTC, gagarski commented
recheck all

2016-11-08 14:31 UTC, gagarski commented
recheck all

2016-11-08 14:31 UTC, gagarski approved these changes

2016-11-08 14:32 UTC, gagarski commented
recheck all

2016-11-08 14:32 UTC, gagarski commented
recheck all

2016-11-08 14:37 UTC, gagarski commented
recheck all

2016-11-08 14:57 UTC, gagarski commented
recheck all

2016-11-08 15:24 UTC, gagarski commented
recheck all

2016-11-08 15:35 UTC, gagarski commented
recheck assignment

2016-11-08 15:40 UTC, gagarski commented
recheck assignment

2016-11-08 16:45 UTC, gagarski commented
recheck all

2016-11-08 19:29 UTC, mglukhikh commented
recheck all

2016-11-08 19:30 UTC, mglukhikh commented
recheck all

2016-11-08 19:32 UTC, mglukhikh commented
recheck all

2016-11-08 19:35 UTC, mglukhikh commented
recheck all

2016-11-08 19:45 UTC, gagarski commented
Замечаний не осталось, но бот почему-то не хочет перепроверять этот PR. 
Предлагаю создать новый и `minContainingCircle` решать уже там.

2016-11-08 19:45 UTC, closed without merging