кек
Kotlin-Polytech/KotlinAsFirst2016 pull request #57
Opened 2016-09-13 17:47 UTC by RainbowDev

2016-09-14 08:59 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> + * Например, 100 рублей под 10% годовых превратятся в 133.1 рубл
В коммитах лучше избегать изменений, не относящихся к решаемой задаче.

2016-09-14 09:00 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial+(initial*percent/100.0)+(initial+(initial*percent/100.0))*percent/100.0+(initial+(initial*percent/100.0)+(initial+(initial*percen
Данное выражение лучше упростить при помощи вынесения выражений `percent / 100` и `initial * percent / 100` в отдельные переменные.

2016-09-14 09:03 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = ((number%10)*100)+(number/100-number%10)+(((number/10)%10)*10)+((number/100)-(number/100-number%10))
Для упрощения понимания кода вычисляемые цифры следует вынести в отдельные переменные.

2016-09-14 09:04 UTC, ice-phoenix commented
Название PR `кек` не соответствует его содержанию. В будущем настоятельно рекомендуется давать PR названия, позволяющие понять, что было сделано в данном PR.

2016-10-12 09:34 UTC, mglukhikh commented
Автору PR: вы уже довольно сильно отстаёте от графика. Вам следует исправить замечания в этом PR и перейти к решению задач из 2-го и 3-го урока, в противном случае вы рискуете получить неудовлетворительную оценку за октябрь.

2016-10-20 10:50 UTC, ice-phoenix commented
recheck all

2016-10-20 10:52 UTC, ice-phoenix commented
Название пулл реквеста все еще не соответствует его содержанию. Если вы его не поправите к концу октября, вместо зачета по предмету вы получите парочку мемосов и представление к отчислению.

2016-10-20 11:37 UTC, ice-phoenix requested changes
Ваши следующие задачи не будут проверяться до тех пор, пока вы не исправите все имеющиеся замечания к урокам 1-3.

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (age%100 in 10..20) sAge+=" лет"
Все это выражение лучше оформить как один плоский `when`

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var sAge = "$age"
Вместо отдельной переменной лучше возвращать результаты работы вашей функции прямо по месту в виде `"$age лет"`

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX == rookX1 && rookX2 == kingX) || (kingY == rookY1 && rookY2 == kingY) || (kingY == rookY1 && rookX2 == kingX) || (kingX == rookX1 && rookY2 == kingY)) threat = 3
Выражения, отвечающие за факт атаки короля той или иной ладьей, следует вынести в отдельные переменные

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((Math.abs(bishopX-kingX)==Math.abs(bishopY-kingY)) && (rookX==kingX || rookY==kingY))  threat=3
Выражения, отвечающие за факт атаки короля ладьей или слоном, следует вынести в отдельные переменные

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a+b<c || c+a<b || b+c<a) kind=-1
Лучше сперва найти максимальную сторону, а потом все один раз посчитать относительно нее

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while(nVar!=0) {
[Здесь и везде] Разберитесь с форматированием кода

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var fib1:Int = 1
* Система типов Котлина выведет тип переменной автоматически

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i%2==1) fib1 += fib2
Если ввести еще одну переменную, в которой хранить результат (а в старых переменных хранить значения -1 и -2 шагов), то можно упростить весь алгоритм работы этой функции

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var max:Int
Форматирование кода

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    max+=1
Почитайте про более быстрые алгоритмы поиска НОК

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var del:Int=2
* Система типов Котлина выведет тип переменной автоматически

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var del:Int=n-1
* Система типов Котлина выведет тип переменной автоматически

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((m%i==0) && (n%i==0)) return false
Форматирование кода + подумайте, можно ли эту функцию выразить через уже реализованные вами функции этого модуля

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +       val sqroot=Math.sqrt(m.toDouble()).toInt()
Вместо `toInt()` следует использовать специальные функции `floor / ceil / round`, которые позволят вам упростить условие строчкой ниже

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var result:Int=0
* Система типов Котлина выведет тип переменной автоматически

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var count=0
Нет ли у вас готовой функции, которая считает количество цифр в числе?

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        for (j in 1..i-1) {ext*=10}
Напишите функцию `fun pow(Int, Int): Int`

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +return result
Пожалуйста, форматируйте ваш код так, как будто его будет читать психопат-перфекционист с педантичной любовью к каждому пробелу и каждому переносу строки, у которого есть топор и который знает, где вы живете

2016-10-20 11:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (test==1) return false
В каком случае вы можете оказаться здесь, а переменная `test` не равна 1???

2016-10-20 17:35 UTC, RainbowDev commented
А можно мне просто мемосов без отчисления? :D
В ближайшее время постараюсь исправить все замечания

2016-10-23 15:36 UTC, RainbowDev commented
Второй "Исправленный Lesson 2 Task 1" - это "Исправленный Lesson 3", когда коммитил забыл переименовать

2016-10-25 08:04 UTC, ice-phoenix requested changes

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(sqr(abs(x1 - x2)) + sqr(abs(y1 - y2)))
Зачем брать модуль перед возведением числа в квадрат?

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = (minutesArrive - minutesDepart) + 60 * (hoursArrive - hoursDepart)
Длинные строки принято разбивать на несколько более коротких, в данном случае, например, после знака `=` в объявлении функции

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val perc = percent.toDouble() / 100
Вместо явного вызова `toDouble()` при floating-point операциях, включающих константы, обычно эти самые константы делают типа `Double` --- `percent / 100.0`

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return initial + inperc + (initial + inperc) * perc + (initial + inperc + (initial + inperc) * perc) * perc
Формулу можно упростить, если воспользоваться математическими правилами

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val n1:Int
Почему вы разделили определение и объявление переменной?

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (age % 100 in 10..20) return "$age лет"
Этот `if` лучше сделать частью следующего за ним `when`

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (r1Threat && r2Threat) return 3
Данное выражение лучше оформить как `when`

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +
Зачем эти пустые строки?

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((bThreat) && (rThreat)) return 3
Данное выражение лучше оформить как `when`

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a > b) {
Тут достаточно трех вариантов вида `a > b && a > c`, `b > a && b > c`, ...

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a + b < c || a + c < b || b + c < a) return -1
Зачем это проверять сейчас в трех разных вариантах, если можно это проверить один раз потом, когда вы уже нашли максимальную сторону?

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (side1 * side1 + side2 * side2 > max * max) return 0
Данное выражение лучше оформить как `when`

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean = number%10+number%100/10==number%1000/100+number/1000
Внезапно форматирование кода стало беспробельным. Пожалуйста, в дальнейшем относитесь к форматированию вашего кода так, будто его будет читать серийный убийца-психопат с трепетным отношением к каждому непоставленному пробелу или лишней пустой строке, который знает, где вы живете, и у которого есть топор.

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = x1==x2 || y1==y2 || Math.abs(x1-y1)==Math.abs(x2-y2)
Длинная строка + форматирование

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun brickPasses(a: Int, b: Int, c: Int, r: Int, s: Int): Boolean = a<=r && b<=s || a<=r && c<=s || b<=r && a<=s || b<=r && c<=s || c<=r && a<=s || c<=r && b<=s
Длинная строка + форматирование

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n == 0) count = 1
Это условие можно было проверить раньше и сразу вернуть 1

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var fib1: Int = 1
* Система типов Котлина выведет тип переменной автоматически

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i % 2 == 1) fib1 += fib2
Вместо этой проверки на каждом шаге можно просто менять переменные местами

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (m % nod != 0 && n % nod != 0) nod+=1
Почитайте про более быстрые алгоритмы поиска GCD

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var del: Int = 2
* Система типов Котлина выведет тип переменной автоматически

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var del: Int = n - 1
* Система типов Котлина выведет тип переменной автоматически
* Нет ли более точной границы для максимального возможного делителя числа, чем `n - 1`?

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((m % i == 0) && (n % i == 0)) return false
Нельзя ли данную задачу решить через другие функции данного модуля?

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (m < n) {
Почему не `Math.min`???

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqroot = Math.sqrt(m.toDouble()).toInt()
Для округления следует использовать специальные функции `floor / ceil / round`

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (sqroot * sqroot >= m && sqroot * sqroot <= n) || ((sqroot + 1) * (sqroot + 1) <= n)
Если вы примените правильную функцию округления, данную проверку можно будет упростить

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var result: Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var ext: Int
Почему эта переменная объявлена здесь, а не ниже прямо при использовании?

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        ext = pow(10, i - 1)
Можно ли перестроить ваш алгоритм так, чтобы не было необходимости на каждой итерации цикла возводить 10 в требуемую степень?

2016-10-25 08:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val samenum: Int = n % 10
* Переменным лучше давать осмысленные имена, соответствующие их назначению в коде
* Система типов Котлина выведет тип переменной автоматически

2016-10-27 18:33 UTC, ice-phoenix commented
4 урок будет проверен после того, как вы исправите замечания к предыдущим урокам

2016-11-18 14:50 UTC, ice-phoenix commented
recheck all

2016-11-18 14:51 UTC, ice-phoenix commented
recheck all

2016-11-18 14:51 UTC, ice-phoenix commented
recheck all

2016-11-18 14:56 UTC, ice-phoenix commented
recheck all

2016-11-23 11:17 UTC, mglukhikh commented
Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.

2016-11-25 11:46 UTC, ice-phoenix requested changes

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return initial + inperc + (initial + inperc) * perc + (initial + inperc + (initial + inperc) * perc) * perc
Данное выражение можно очень сильно упростить, если вспомнить о некоторых математических свойствах умножения и сложения

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val n1:Int
Все еще актуально

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (r1Threat && r2Threat) return 3
Все еще актуально

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((bThreat) && (rThreat)) return 3
Все еще актуально

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a > b && a>c) {
Форматирование кода

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        if (b > c) {
Лучше записывать подобные конструкции на одном уровне через `else if`

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        side1 + side2 < max -> return -1
`when { return ... }` ==> `return when { ... }`

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        a <= r && b <= s || a <= r && c <= s || b <= r && a <= s || b <= r && c <= s ||
Форматирование кода

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i % 2 == 1) fib1 += fib2
Вместо этой проверки лучше менять `fib1 / fib2` местами

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return m * n / nod
Почитайте про более быстрые алгоритмы поиска GCD

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return true
Если вы напишите нормальный алгоритм поиска GCD, то эта функция станет тривиально реализуемой

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val sqroot = Math.sqrt(m.toDouble()).toInt()
Все еще актуально

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (sqroot * sqroot >= m && sqroot * sqroot <= n) || ((sqroot + 1) * (sqroot + 1) <= n)
Все еще актуально

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun pow (a: Int, b: Int) : Int{
Форматирование кода

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val samedigit = n % 10
`camelCase`

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +import lesson3.task1.isPrime
Зачем вам все эти функции здесь?

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var j = 0
Зачем вам эта переменная, когда есть `list.size`???

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (j > 0) result /= j
Почему бы не воспользоваться уже написанной несколькими строчками выше функцией для подсчета среднего?

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var C: Double = 0.0
* Система типов Котлина выведет тип переменной автоматически

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var px: Double = 0.0
* Система типов Котлина выведет тип переменной автоматически

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        xpow = 1.0
Зачем каждый раз считать эту переменную с самого начала? Неужели нельзя получить ее значение на итерации `i + 1` через ее значение на итерации `i`?

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Зачем данная проверка?

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        }
Подумайте, нужен ли вообще этот цикл?

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return list
Лучше как `list.reversed()`

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result: String = ""
Во первых, можно не указывать тип. Во вторых, для подобных операций лучше использовать список строк или `StringBuilder`.

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (element > 9) result += ('a'.toInt() + element - 10).toChar()
Зачем `toInt()`?

2016-11-25 11:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in digits.size-1 downTo 0){
Форматирование кода

2016-11-25 11:48 UTC, ice-phoenix commented
recheck all

2016-12-14 15:19 UTC, ice-phoenix commented
recheck all

2016-12-14 15:20 UTC, ice-phoenix commented
Довольно много замечаний еще не исправлены. Новые уроки не будут проверены, пока вы не исправите предыдущие.

2016-12-18 22:28 UTC, ice-phoenix commented
recheck all

2016-12-18 22:33 UTC, ice-phoenix commented
Поздравляем, у вас зачет! До встречи на экзамене!

2017-07-26 18:24 UTC, closed without merging