Test 1
Kotlin-Polytech/KotlinAsFirst2016 pull request #59
Opened 2016-09-14 09:27 UTC by GlowBlood

Ляляля

2016-09-14 09:51 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double {
Вместо того, чтобы вычислять константы-множители вручную, лучше вычислить их в программе через константу `PI`.

2016-09-19 02:25 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (((age % 10 == 2) || (age % 10 == 3) || (age % 10 == 4)) && (age % 100 > 14))
Условие можно записать как через диапазон `age % 10 in 2..4`.

2016-09-19 02:27 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +        if ((S_half>s1) && (S_half<=s1+s2))
Первая половина условия лишняя. Кроме того цепочки `if ... else if ... else ...` принято записывать на одном уровне
```kotlin
if (...) ...
else if (...) ...
...
else ...
```

2016-09-19 02:28 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (((rookX1 == kingX) || (rookY1 == kingY)) && ((rookX2 == kingX) || (rookY2 == kingY))) return 3
Лучше завести отдельные переменные для условий угрозы от каждой из ладей.

2016-09-19 02:30 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((rookX2 == kingX) || (rookY2 == kingY)) return 2
Приведите условия к одному стилю: или сделайте одну цепочку `if ...else if ... else` (не забудьте про одинаковый отступ), или везде `else` уберите.

2016-09-19 02:31 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (((((bishopX + bishopY) == (kingX + kingY)) || ((bishopX - bishopY) == (kingX - kingY)))) && (((rookX == kingX) || (rookY == kingY))))
Замечания такие же, как и к предыдущей функции

2016-09-19 02:34 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val lit_cat = min(min(a,b),c)
Нет разницы, какой из катетов меньше.

2016-09-19 02:34 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((a+b < c) || (a+c<b) || (b+c<a))
Условие можно упростить с учетом того, что Вы нашли гипотенузу.

2016-09-19 02:36 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +        result = abs(min(b, d) - max(a, c))
Модуль здесь не нужен

2016-09-19 02:36 UTC, maximpetrov requested changes
Исправьте замечания и к предыдущему уроку тоже

2016-09-21 10:00 UTC, GlowBlood commented on src/lesson2/task1/IfElse.kt
> +    val lit_cat = min(min(a,b),c)
Согласна, разницы нет, я называю катеты "маленький" и "средний" просто для того, чтобы их различать. Чтобы второй катет не оказался гипотенузой.

2016-09-21 15:36 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((age % 10 in 2..4)&& (age !in 10..19) && (age !in 110..119)) return "$age года"
Почему Вы просто не проверяете последние две цифры на попадание в 10..19?

2016-09-21 15:42 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val diff_bish = ((bishopX - bishopY) == (kingX - kingY))
Зачем Вы завели переменные, которые по отдельности не нужны? Стоило завести одну переменную для слона.

2016-09-21 15:44 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else result = (min(b, d) - max(a, c))
Здесь можно сразу вернуть значение без записывания его в переменную.

2016-09-21 15:46 UTC, maximpetrov requested changes

2016-09-21 16:12 UTC, maximpetrov approved these changes

2016-09-21 16:14 UTC, closed without merging