1 урок
Kotlin-Polytech/KotlinAsFirst2016 pull request #62
Opened 2016-09-14 10:23 UTC by VladislavMikh

2016-09-14 10:39 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +    println ("Root product: $x1x2")
В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков.

2016-09-14 10:40 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = grad * PI / 180 + min / 60.0 * PI / 180 + sec / 3600.0 * PI / 180
Функцию можно упростить с помощью элементарных арифметических преобразований.

2016-09-14 10:42 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +    val change_x_sqr = ( x2 - x1 ) * ( x2 - x1 )
[Здесь и далее] Переменные в Kotlin принято называть т. н. lower camel case'ом. Например `changeXSqr`. `change_x_sqr` или `changexsqr` - неправильный стиль.

2016-09-14 22:04 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +    val starttime = hoursDepart * 60 + minutesDepart
Lower camel case

2016-09-29 09:54 UTC, gagarski requested changes

2016-09-29 09:54 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        else -> fib( n - 1 ) + fib( n - 2 )
- Рекурсивное решение напрашивается, исходя из определения чисел Фибоначчи, но попробуйте посчитать, к скольки вызовам функции `fib()` приведёт вызов `fib(10)`, `fib(40)`, `fib(55)`, сколько среди них вызовов с одинаковыми аргументами и решить задачу более оптимальным способом.

2016-09-29 09:54 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = grad * PI / 180 + min * PI / 10800.0 + sec * PI / 648000.0
Старайтесь избегать неочевидных констант, вычисленных вручную.
Человеку, читающему ваш код скорее всего будет понятно, что такое 60 и 180, а про 10800 и 648000 - уже не совсем очевидно.
Пишите прямо в коде `60 * 180` и `60 * 60 * 180`, или хотя бы поясняйте происхождение этих чисел в комментарии рядом.

2016-09-29 09:54 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    return when {
Тесты для этой функции не проходят. Не все случаи рассмотрены.

2016-09-29 14:17 UTC, mglukhikh commented
recheck all

2016-10-26 11:03 UTC, gagarski commented
recheck all

2016-10-26 11:10 UTC, gagarski requested changes

2016-10-26 11:10 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int {
Почитайте про более эффективные алгоритмы вычисления НОД/НОК.

2016-10-26 11:10 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean {
Решите эту задачу, используя НОД или НОК.

2016-10-26 11:10 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var currentExp = x % (2 * Math.PI) // текущее значение x^(какой-то степении) в членах ф-ции
Протестируйте ваши реализации синуса и косинуса на больших числах. Решите проблемы, используя свойства синуса и косинуса.

2016-10-26 11:10 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var revertedSquare: Int // квадрат, записанный в обратном порядке
Зачем нужно число, записанное в обратном порядке?

2016-10-26 11:10 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (v.isEmpty()) return 0.0
Пустой список можно не рассматривать, как особый случай. В случае пустого списка вы просто не попадёте в цикл.

2016-10-26 11:10 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Пустой список можно не рассматривать, как особый случай. В случае пустого списка вы просто не попадёте в цикл.

2016-10-26 11:10 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (a.isEmpty() && b.isEmpty()) return 0.0
Пустой список можно не рассматривать, как особый случай. В случае пустого списка вы просто не попадёте в цикл.

2016-10-26 11:10 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (p.isEmpty()) return 0.0
Пустой список можно не рассматривать, как особый случай. В случае пустого списка вы просто не попадёте в цикл.

2016-10-28 12:25 UTC, gagarski requested changes
Пожалуйста исправьте текущие ошибки и замечания, прежде чем приступать к следующим задачам.

2016-10-28 12:25 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    return c / mm
- Лучше вынести вычисление НОД в отдельную функцию
 - Лучше сделать `mm / НОД * nn` чтобы избежать переполнения например для НОК(1000000, 1000000)

2016-10-28 12:25 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var nn = n
- Как сказано выше, лучше вынести НОД в отдельную функцию и использовать её здесь.

2016-10-28 12:25 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int {
done

2016-10-28 12:25 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    //var k = Math.max(n, m)                   // - 1 вариант
Старайтесь не оставлять закомментированные части кода. Для версионирования ваших функций используйте git (который вы и так используете)

2016-10-28 12:25 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var i = n - 1
Можно ли ограничить верхнюю границу перебора?

2016-10-28 12:25 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (n % i != 0) {
Можно ли ограничить верхнюю границу перебора (и вернуть `n`, если мы её достигли).

2016-10-28 12:25 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var revertedFib: Int
Зачем нужно число, записанное в обратном порядке?

2016-10-28 12:25 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            divider--
Ваш `--` перед `++` -- пример паттерна "костыль". Почему просто не убрать инкремент в тех случаях, когда это не нужно.

2016-11-08 12:21 UTC, gagarski requested changes

2016-11-08 12:21 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun gkd(a: Int, b: Int): Int { //  доп. ф-ция для нахождения НОД, используется  в ф-ции lcm
Greatest Common Divisor - `gcd`

2016-11-08 12:21 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n / 2) { // n может нацело делиться либо на число, не больщее чем n/2, либо на самого себя (n / n = 1)
А можно ли ещё сильнее ограничить перебор (см. примеры к этому уроку). В `maxDivisor` тоже.

2016-11-08 12:21 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (Math.abs(x) > 2 * Math.PI) xx = x % (2 * Math.PI)
Нужна ли проверка условия перед взятием остатка от деления?

2016-11-08 12:21 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (Math.abs(x) > 2 * Math.PI) xx = x % (2 * Math.PI)
Нужна ли проверка условия перед взятием остатка от деления?

2016-11-08 12:21 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var revertedSquare: Int // квадрат, записанный в обратном порядке
актуально

2016-11-08 12:21 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var revertedFib: Int
актуально

2016-11-08 12:21 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            divider--
актуально

2016-11-08 12:22 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            divider--
(вспомните, что можно писать ветку `else` у `if`, например)

2016-11-09 14:50 UTC, gagarski requested changes

2016-11-09 14:50 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        revertedSquare = (revert(number * number)).toLong()
Поотлаживайте вашу программу на случаях, предоставленных ботом. Например, 361128-я цифра последовательности встречается в квадрате числа 40737. Его квадрат влезает в тип Int, а перевёрнутый квадрат вызывает переполнение. Попробуйте решить эту задачу без `revert`.

2016-11-09 14:50 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val result = mutableListOf<Double>()
См. сообщение бота. Предполагается, что вы будете изменять входной список, а не создавать его изменённую копию.

2016-11-16 09:49 UTC, VladislavMikh commented on src/lesson4/task1/List.kt
> +    val result = mutableListOf<Double>()
Возможно рассматривать в данном пулл реквесте только задачи уроков 1-3?
Мне бы хотелось закрыть его, а для проверки задач из уроков 4+ использовать другой пулл реквест.

2016-11-21 08:16 UTC, mglukhikh commented
recheck all

2016-11-21 08:19 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return when {
Исправлено

2016-11-21 08:21 UTC, mglukhikh commented
По просьбе автора, PR закрывается с принятием уроков 1-3. Урок 4 пока не засчитан. Просьба обратить внимание на сообщение бота для `accumulate`.

2016-11-21 08:21 UTC, closed without merging