lesson3.task1
Kotlin-Polytech/KotlinAsFirst2016 pull request #63
Opened 2016-09-14 17:37 UTC by MedAlexey

2016-09-14 18:22 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +                                       if ((age%10==1)&&(age%100!==11)) "$age год" else
Для сравнения объектов на равенство используется оператор `!=`. Оператор `!==` проверяют, являются ли левый и правый операнд одним и тем же объектом. Хотя для `Int` (как в вашем когде) это не создаст проблем, исправьте это и впредь имейте это в виду (или будете натыкаться на странные баги).

2016-09-14 19:46 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +if((kingX!==rookX)&&(kingY!==rookY)&&(Math.abs(kingX-bishopX)!==Math.abs(kingY-bishopY)))0 else
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-14 19:46 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if((c>a)&&(c>b)){
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-14 19:48 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int {
- Рекурсивное решение напрашивается, исходя из определения чисел Фибоначчи, но попробуйте посчитать, к скольки вызовам функции `fib()` приведёт вызов `fib(10)`, `fib(40)`, `fib(55)`, сколько среди них вызовов с одинаковыми аргументами и решить задачу более оптимальным способом.

2016-09-14 19:49 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> -fun fibSequenceDigit(n: Int): Int = TODO()
- В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков.

2016-09-14 19:50 UTC, gagarski commented
recheck assignment

2016-09-14 21:17 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +if((kingX!==rookX)&&(kingY!==rookY)&&(Math.abs(kingX-bishopX)!==Math.abs(kingY-bishopY)))0 else
UPD: Оказывается, IDEA не правит "лесенки" из `else if`. `else` принято переносить на новую строку вместе с последующим `if`, таким образом цепочка из нескольких `if`ов будет выглядеть примерно так:
```kotlin
if (a == 10) doSomething()
else if (a == 20) doSomethingElse()
else if (a == 30) doOneMoreThing()
else doCompletelyDifferentThing()
```

Таким образом, мы перебираем несколько вариантов условий и всё на одном уровне. Это гораздо легче читать.

Также для множественных ветвлений в Kotlin есть конструкция `when` (см. Tutorial)

2016-09-14 21:18 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if((c>a)&&(c>b)){
См. выше

2016-09-17 11:54 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        if(((b<c)&&(a<c))||((c<a)&&(d<a))) -1 else
См. комментарий про `else if`

2016-09-17 11:56 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if((x1==x2)||(y1==y2)||(Math.abs(x1-x2)==Math.abs(y1-y2))) return true else return false
Результат условия тоже булевская переменная.
Поэтому конструкции вида 
```kotlin
if (something) return true else return false
```
можно записать гораздо короче:
```kotlin
return something
```

2016-09-17 11:58 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +        if(((a<=r)&&(b<=s))||((b<=r)&&(a<=s))||((a<=r)&&(c<=s))||((a<=s)&&(c<=r))||((b<=r)&&(c<=s))||((b<=s)&&(c<=r))) true else false
- Условие можно сильно упростить, если заранее определить две наиболее короткие стороны кирпича.
 - См. комментарий про `if (...) return true else return false`

2016-09-17 11:59 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var M=m
Переменные в Kotlin принято называть с маленькой буквы.

2016-09-17 12:00 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var min=0
Подумайте как решить эту задачу с помощью других реализованных вами функций.

2016-09-17 12:01 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if((x*x>=m)&&(x*x<=n)) return true else return false
- См. комментарий про `if (...) return true else return false`
 - Можно ли начать перебор не с нуля?

2016-09-17 12:02 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> -fun cos(x: Double, eps: Double): Double = TODO()
- В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков.

2016-09-17 12:03 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if(x !=number%10) result=true
Выполнение функции можно завершить сразу при нахождении разных цифр.

2016-09-17 12:03 UTC, gagarski requested changes

2016-09-17 20:25 UTC, gagarski commented
Постарайтесь исправить текущие замечания прежде чем приступать к следующим урокам.

2016-09-18 13:16 UTC, MedAlexey commented
Исправить и загрузить на сайт? 18.09.2016, 02:25, "Kirill Gagarski" <notifications@github.com>:Постарайтесь исправить текущие замечания прежде чем приступать к следующим урокам.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. 

2016-09-18 14:21 UTC, gagarski commented
@MedAlexey да

2016-09-21 09:35 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if (S_half <= s1) return S_half / v1 else
```koltin
if (...) ...
else if (...) ...
else if (...) ...
else ...
```
или
```kotlin
when {
    // ...
}

2016-09-21 09:36 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        if (((kingX == rookX1) || (kingY == rookY1)) && ((kingX !== rookX2) && kingY !== rookY2)) 1 else
```koltin
if (...) ...
else if (...) ...
else if (...) ...
else ...
```
или
```kotlin
when {
    // ...
}

2016-09-21 09:36 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        if ((kingX !== rookX) && (kingY !== rookY) && (Math.abs(kingX - bishopX) !== Math.abs(kingY - bishopY))) 0 else
```koltin
if (...) ...
else if (...) ...
else if (...) ...
else ...
```
или
```kotlin
when {
    // ...
}

2016-09-21 09:36 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if ((a > b) && (a > c)) {
```koltin
if (...) ...
else if (...) ...
else if (...) ...
else ...
```
или
```kotlin
when {
    // ...
}

2016-09-21 09:38 UTC, gagarski requested changes

2016-09-21 09:48 UTC, gagarski commented
recheck all

2016-09-21 15:48 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var n = 1
Протестируйте вашу функцию на больших `x`? Правильно ли она работает? Попробуйте понять почему и придумать, как это исправить, используя свойства синуса.

2016-09-21 15:48 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var n = 2
См. коммент про синус.

2016-09-21 15:48 UTC, gagarski requested changes

2016-09-29 09:41 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +            break
`break` здесь не нужен. После `return true` цикл и так завершиться.

2016-09-29 09:42 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if (S_half <= s1) return S_half / v1 else
Исправьте пожалуйста "лесенки" из `else if` здесь и ниже

2016-09-29 09:47 UTC, gagarski requested changes

2016-09-29 09:47 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    ((age % 10 == 1) && (age % 100 != 11)) -> "$age год"
Число веток можно сократить используя оператор `in`: `((age % 10 in 2..4) && (age % 100 !in 12..14))`

2016-09-29 09:47 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    (age % 10 == 5) -> "$age лет"
`age % 10 in 5..9`

2016-09-29 09:47 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    (age % 10 == 5) -> "$age лет"
Вообще все ветки, где `"$age лет"` можно заменить на одну:
```kotlin
else -> "$age лет"
```

2016-09-30 20:49 UTC, gagarski commented on src/lesson4/task1/List.kt
> +fun russian(n: Int): String {
Постарайтесь избавиться от дублирования кола

2016-09-30 21:01 UTC, gagarski requested changes

2016-09-30 21:01 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in 0..list.size - 1) {
[Здесь и далее] Если вам не нужен сам индекс, то вы можете обходить список так:
```kotlin
for (elem in list) {
     result += elem
     // и так далее
}
```

2016-09-30 21:01 UTC, gagarski commented on src/lesson4/task1/List.kt
> +import kotlin.reflect.jvm.internal.impl.serialization.deserialization.AdditionalSupertypes
Зачем этот импорт?

2016-09-30 21:01 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        result += (digits[digits.size - 1 - i] * Math.pow(base.toDouble(), i.toDouble()))
Стоит по возможности избегать использования чисел с плавающей точкой в задачах с целыми числами. Реализуйте `pow` для целых чисел или модифицируйте множитель `base^n` в ходе цикла.

2016-09-30 21:01 UTC, gagarski requested changes

2016-09-30 21:01 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var a = when (n / 100000) {
Постарайтесь избавиться от дублирования кода.

2016-10-06 13:24 UTC, gagarski requested changes

2016-10-06 13:24 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var number = n
Используйте функцию `convert`, определённую вами ранее

2016-10-06 13:24 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            10 -> 'a'
Используйте факты, что латинские символы кодируются в ASCII подряд и то, что можно прибавлять число к символу:
`'b' == 'a' + 1` и. д.

2016-10-06 13:24 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            'a' -> 10.toChar()
- См. выше про свойства латинских символов
 - Зачем `toChar()`?

2016-10-06 13:24 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        result += (Math.pow(base.toDouble(), i.toDouble()) * number.toDouble())
- Старайтесь избегать операций с числами с плавающей точкой в целочисленных задачах. Реализуйте `pow` для целых чисел, это несложно.

2016-10-07 17:00 UTC, MedAlexey commented on src/lesson4/task1/List.kt
> +        result += (Math.pow(base.toDouble(), i.toDouble()) * number.toDouble())
pow(x,y), где X и Y , как я понимаю, могут быть только Double. Как реализовать pow для целых чисел?

2016-10-07 18:52 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        result += (Math.pow(base.toDouble(), i.toDouble()) * number.toDouble())
Вспомните, как возводятся числа в целую степень и реализуйте свою функцию. Либо воспользуйтесь тем, что вы циклом проходитесь по строке и обновляйте множитель `(Math.pow(base.toDouble(), i.toDouble())` в цикле.

2016-10-20 10:15 UTC, gagarski requested changes
Пожалуйста исправьте эти и предыдущие замечания и ошибки прежде чем приступать к следующим заданиям.

2016-10-20 10:15 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Можно не рассматривать пустой список как особый случай. Если список пустой, цикл  просто не совершит ни одной итерации

2016-10-20 10:15 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in 2..number) {
Можно ли уменьшить верхнюю границу перебора?

2016-10-20 10:15 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var number = n
Используйте функцию `factorize`, реализованнную вами.

2016-10-20 10:15 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in 0..digits.size - 1) {
Не следует переходить к числам с плавающей точкой в целочисленных задачах чтобы не сталкиваться с ошибками округления. Реализуйте `pow` для целых чисел или используйте имеющийся у вас цикл для вычисления множителя base^n

2016-10-20 10:15 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in 0..digits.size - 1) {
К тому же у вас есть функция вычисления степени для целых чисел ниже (которая почему-то называется `sqr`)

2016-10-20 10:15 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var result = 1
Старайтесь называть функции в соответствии с тем, что они делают. Эта функция возводит в степень, а не вычисляет квадрат числа, как можно подумать из её названия.

2016-10-20 10:15 UTC, gagarski commented on src/lesson4/task1/List.kt
> +            'a' -> (sqr(base, i) * 10)
Можно упростить этот `when`, если использовать свойства ASCII-кодировки.
`'a' + 1 == 'b'`
`'a' + 2 == 'c'`
и т. д.

2016-10-20 10:15 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    when (number % 10) {
- Здесь явно дублируется код для единиц, десятков и сотен. Попробуйте вынести дублирующийся `when` в отдельную функцию, принимающую символ для единиц, пятёрок и десятков (`romanHelper('I', 'V', 'X')`, `romanHelper('X', 'L', 'C')` и т. д.).

2016-10-20 10:15 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +            "01" -> "1"
Можно ли обойтись без ручного перебора все случаев от 01 до 09?

2016-10-20 10:15 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +        var result = expression[0].toInt() - 48
Вместо 48 лучше `'0'.toInt()`. Так происхождение магической константы 48 станет намного понятнее читателю.

2016-10-20 10:19 UTC, gagarski commented
recheck all

2016-10-24 14:16 UTC, gagarski commented
recheck all

2016-10-24 14:34 UTC, gagarski requested changes

2016-10-24 14:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while(str.length-1<n){
Решите эту задачу без использования строк или хотя бы без хранения **всей** строки в памяти.

2016-10-24 14:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while(str.length-1<n){
Решите эту задачу без использования строк или хотя бы без хранения **всей** строки в памяти.

2016-10-24 14:34 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    /*when (number % 10) {
Если вы будете оставлять старые версии кода в комментариях, то очень быстро их станет больше, чем актуального кода. Почитайте tutorial по git'у, чтобы узнать, как восстанавливать старые версии с помощью него.

2016-10-24 14:34 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +        if (isString(parts[0])) {
Разве `toInt` не бросит  `NumberFormatException` (который вы ловите ) в тех же случаях, когда ваш `isString` (почему, кстати, `isString`?) вернёт `false`?

2016-11-09 16:09 UTC, gagarski commented
recheck assignment

2016-11-09 16:32 UTC, gagarski commented
recheck assignment

2016-11-09 17:06 UTC, gagarski commented
recheck assignment

2016-11-09 17:14 UTC, gagarski commented
recheck assignemnt

2016-11-09 17:15 UTC, gagarski commented
recheck assignment

2016-11-09 17:16 UTC, gagarski commented
recheck assignment

2016-11-21 14:03 UTC, gagarski requested changes

2016-11-21 14:03 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +    while ((x in 1..8) && (y in 1..8)) {   //1 четверть
Избавьтесь от дублирования кода. Например, сделав цикл по возможным направлениям.

2016-11-21 14:04 UTC, gagarski commented
Из старого остались синус/косинус и замечание по `russian`

2016-11-25 20:16 UTC, mglukhikh commented
recheck all

2016-11-27 14:46 UTC, gagarski requested changes

2016-11-27 14:46 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        var result = 5
Ваша функция `hashCode` возвращает одинаковый результат для всех матриц одинакового размера. 
 - Попробуйте почитать и понять tutorial/лекции про `hashCode` (Обратите внимание на комментарии внутри функции в tutorial'е)
 - Попробуйте учесть содержиvое в своей реализации `hashCode` самостоятельно.
 - Попробуйте сгенерировать `hashCode` с помощью IDE, прочитать и понять его.

2016-11-27 14:46 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +            if (matrix[i, j] != 0) columnWithHoles = false
Вверху в похожем цикле есть `break`,  а тут нет.

2016-11-27 14:53 UTC, gagarski commented
recheck all

2016-11-27 15:02 UTC, gagarski commented
В `lesson6.task2.square` нужна обработка ошибки (см. описание задания).

2016-11-27 15:17 UTC, gagarski commented
recheck all

2016-11-27 15:19 UTC, gagarski commented
recheck all

2016-11-27 15:26 UTC, gagarski requested changes

2016-11-27 15:26 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +fun square(notation: String): Square {
Для пустой строки выпадает не то исключение (см. комментарий бота)

2016-11-27 15:26 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +fun kingTrajectory(start: Square, end: Square): List<Square> {
Тесты бота не проходят. Попробуйте протестировать/отладить локально с входными данными из комментариев бота.

2016-11-27 15:26 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +    if (start.kingOnLine(end)) {                                        // если на одной линии
Нужно ли всё, что внутри этого if'а? Казалось бы, если начало и конец на одной линии, мы не попадём в диагональный цикл, а затем начнём двигаться по горизонтали/вертикали. Разве нет?

2016-12-05 16:29 UTC, gagarski commented
recheck all

2016-12-05 16:32 UTC, gagarski commented on src/lesson6/task2/Chess.kt
> +fun square(notation: String): Square {
fixed

2016-12-05 16:54 UTC, gagarski requested changes

2016-12-05 16:54 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        if (other is MatrixImpl<*> &&
Приведите в порядок отступы в этой функции пожалуйста. Вокруг внешних `if`ов и `for`ов лучше поставить фигурные скобки для понятности.

2016-12-05 16:54 UTC, gagarski commented on src/lesson8/task1/Files.kt
> +    for(i in 1..numberOfSpaces){
- Вместо конкатенации строк в цикле лучше использовать `StringBuilder`
 - Вместо цикла для генерации пробелов лучше использовать `" ".repeat(number)`.

2016-12-05 16:54 UTC, gagarski commented on src/lesson8/task1/Files.kt
> +            result = " " + result
См. коммент к `centered`

2016-12-05 16:56 UTC, gagarski commented
По 8 уроку:
 - `chooseLongestChaoticWord` - похоже ошибка в тестах
 - остальное - сравните кол-во строк во входном и выходнм файле (в задачах с выравниванием, например, это требование явно прописано)

2016-12-05 17:07 UTC, gagarski commented
recheck all

2016-12-05 17:10 UTC, gagarski commented
По 8 уроку: сравните кол-во строк во входном и выходнм файле (в задачах с выравниванием, например, это требование явно прописано)

2016-12-13 15:40 UTC, gagarski commented on src/lesson8/task1/Files.kt
> +    for(i in 1..numberOfSpaces){
ап

2016-12-13 15:40 UTC, gagarski commented on src/lesson8/task1/Files.kt
> +            result = " " + result
ап

2016-12-13 16:00 UTC, gagarski commented
recheck all

2016-12-13 16:01 UTC, gagarski commented
recheck all

2016-12-13 16:18 UTC, gagarski commented
`sibilants` - у вас вылетает исключение: выход за границу строки
`alignFileByWidth` - обратите внимание, что слова во входном файле могут быть отделены одним или **несколькими** пробелами. Ситуация с несколькими пробелами у вас обрабатывается некорректно (см. третью строку из последнего запуска тестов, где перед словом "равваОЛххабвббЕбФбаб" стоят два пробела).

Осталась ошибка в `crossPoint` в 6 уроке и несколько замечаний в 7 и 8.

2016-12-13 16:31 UTC, mglukhikh commented
В целом, всё довольно близко к отличному итогу, но ошибки, конечно, нужно поправить. Обратите также внимание на два провалившихся теста в 5-м уроке при последнем запуске бота. Либо они мигают, либо вы что-то случайно сломали при последних изменениях.

2016-12-15 11:56 UTC, MedAlexey commented on src/lesson8/task1/Files.kt
> +    for(i in 1..numberOfSpaces){
Можно ли в StringBuilder добавлять символы в начало стоки? Если да, то как?

2016-12-15 12:12 UTC, mglukhikh commented
Отвечая на вопрос про StringBuilder: https://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html#insert(int,%20boolean). Хотя это используется достаточно редко.

2016-12-15 12:19 UTC, gagarski commented
К StringBuilderу.

Хоть и можно, но в вашем случае не очень нужно. Можно сначала добавить пробелы, а затем `result`. А ещё лучше использовать метод `repeat` на строке из пробела.

2016-12-16 21:32 UTC, MedAlexey commented
Почему 8ой урок выдаёт ошибку при проверке?

2016-12-16 21:39 UTC, mglukhikh commented
recheck all

2016-12-16 21:51 UTC, gagarski commented
recheck all

2016-12-16 21:52 UTC, gagarski commented
recheck all

2016-12-16 22:01 UTC, gagarski approved these changes

2017-07-26 18:24 UTC, closed without merging