1
Kotlin-Polytech/KotlinAsFirst2016 pull request #65
Opened 2016-09-14 18:45 UTC by xslavakarachev

2016-09-14 20:53 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    {
Здесь нарушены правила выравнивания исходного кода. Попробуйте в IDEA, находясь в этом файле, нажать Ctrl+Alt+L. Посмотрите, как выровняет ваш код IDEA, и постарайтесь придерживаться такого же стиля в будущем. В частности, открывающая фигурная скобка ставится на той же строке, что и конструкция, к которой она относится

2016-09-14 20:53 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +        return cifra
return должен находиться на одном уровне с val

2016-09-14 20:53 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int{
А здесь вообще лесенка получилась, хотя всё это должно быть на одном уровне

2016-09-14 20:54 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (((Math.abs(kingX - bishopX)) !== (Math.abs(kingY - bishopY)) &&((kingX !== rookX && kingY !== rookY)))) return 0 else
Здесь else лучше перенести, указав его перед if на следующей строке

2016-09-14 20:56 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
У вас здесь по нескольку раз проверяются одни и те же условия. Подумайте, как можно переписать текст функции, чтобы этого избежать

2016-09-14 20:57 UTC, mglukhikh commented
Написал замечаний по коду, см. Files changed

2016-09-16 15:07 UTC, xslavakarachev commented on src/lesson2/task1/IfElse.kt
Исправил вроде бы

2016-09-17 10:47 UTC, xslavakarachev commented
Cколько задач на каждую тему нужно решить для зачета?

2016-09-17 11:49 UTC, mglukhikh commented
Для зачёта нужно решить одну задачу на каждую тему. Сложность решённых задач влияет на итоговую оценку

2016-09-17 11:54 UTC, mglukhikh commented
Пожалуйста, пишите более содержательные комментарии к коммитам. Без них довольно трудно разобраться, где и что было вами поправлено.

2016-09-17 11:56 UTC, mglukhikh commented
По-прежнему неверно выравнивание кода в первом уроке

2016-09-17 11:57 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
См. выше

2016-09-17 11:58 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
Весь код в блоке должен быть на одном уровне

2016-09-17 11:58 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
См. выше

2016-09-17 12:00 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Код внутри обоих внешних if почти идентичен, подумайте, как этого избежать. То же касается условий во внешних if. Для сравнения на неравенство следует употреблять `!=`. Операция `!==` это немножко другое -- сравнение ссылок на неравенство, употребляется редко (о ней мы поговорим позже на лекциях). Последняя строка бессмысленна; подумайте, как переписать код так, чтобы этой строки не было.

2016-09-17 12:01 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Возведение в квадрат лучше делать либо умножением на себя, либо используя функцию `sqr` из первого урока (или аналогичную). `Math.pow` более медленная и менее точная.

2016-09-17 18:36 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +
В triangleKind имеется опечатка, из-за которой тесты не проходят.

2016-09-17 18:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Остаётся в силе часть прежнего замечания: оператор `return 0` в конце никогда не будет выполнен (и можно написать функцию так, чтобы он был не нужен); оба внешних `if` внутри содержат почти идентичный код, этого дублирования тоже можно избежать.

2016-09-17 18:40 UTC, mglukhikh commented
По итогам просмотра: первый урок засчитан полностью, замечаний нет; во втором уроке triangleKind решена с ошибкой, а rookOrBishopThreatens решена верно, но с замечаниями по стилю; остальные задачи второго урока засчитаны.

2016-09-19 16:40 UTC, mglukhikh commented
В задаче про две ладьи ваше решение "умнее" приведённого в тестах, поскольку учитывает возможность, когда одна ладья загораживает другую. Считаем, что решение верно.

2016-09-19 16:43 UTC, mglukhikh commented
Решение задачи про треугольник по-прежнему неверное. Учтите, что самой длинной может быть любая сторона треугольника.

2016-09-19 16:45 UTC, mglukhikh commented
И опечатка была не там :)

2016-09-27 10:25 UTC, mglukhikh commented
recheck all

2016-09-28 14:52 UTC, xslavakarachev commented
Сколько задач нужно сделать из 3 урока, чтобы получить "5"?

2016-09-29 09:17 UTC, mglukhikh commented
Чтобы получить "5", достаточно сделать одну из задач 3-го урока, отмеченных как "Сложная".

2016-09-29 18:03 UTC, mglukhikh commented
recheck all

2016-09-29 18:15 UTC, mglukhikh requested changes
Довольно много мелких замечаний по коду. Два урока у вас более-менее сделаны, но замечания надо исправлять.

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    val allTIME = (hours * 3600) + (minutes * 60) + seconds
Нарушение общепринятого стиля имён. Переменные из двух слов принято называть так: `allTime`. Кроме этого, функцию можно было записать короче, используя синтаксис `fun seconds(...) = ...`.

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
То же самое

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +}
То же самое

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    return finall
Трижды выполняете одно и то же действие. Можно было использовать `Math.pow` или, в крайнем случае, цикл.

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> + * Найти навименьший корень биквадратного уравнения ax^4 + bx^2 + c = 0
Избегайте таких "случайных" изменений, они лишь мешают чтению. IDEA позволяет просматривать изменения перед созданием коммитов.

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Эта задача у вас решена с ошибкой, см. пример бота

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    }
Здесь и ниже, `if...else if` записывается вот так:

```
if (...) return ...
else if (...) return ...
```

а не "лесенкой", как у вас

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +}
Подумайте, не существует ли более короткого решения

2016-09-29 18:15 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if (x1 == x2 || y1 == y2 || ((Math.abs(x1 - x2)) == (Math.abs(y1 - y2)))) return true
`if (x) return true else return false` эквивалентно `return x`

2016-09-29 18:15 UTC, mglukhikh commented on test/lesson2/task1/Tests.kt
> +        assertEquals(0, whichRookThreatens(8, 1, 2, 1, 1, 8))
Было бы лучше вместо изменения существующего теста добавить ещё один, нужный вам.

2016-09-30 11:06 UTC, xslavakarachev commented
Мне не сделать коммит в IDEA, пишет : Commit failed with error
			0 files committed, 4 files failed to commit: zadacha1
			cannot lock ref 'HEAD': unable to resolve reference 'refs/heads/master': reference broken
Что можно сделать?

2016-09-30 11:36 UTC, mglukhikh commented
Попробуйте для начала перезапустить IDEA, потом, может быть, 
перезапустить компьютер. Если ни то, ни другое не помогает, я бы 
аккуратно сохранил все изменённые файлы где-нибудь отдельно, удалил бы 
проект с компьютера полностью, затем заново загрузил бы его с GitHub и 
положил бы изменённые файлы на место.

С уважением, Михаил Глухих


9/30/2016 2:06 PM, xslavakarachev пишет:
>
> Мне не сделать коммит в IDEA, пишет : Commit failed with error
> 0 files committed, 4 files failed to commit: zadacha1
> cannot lock ref 'HEAD': unable to resolve reference 
> 'refs/heads/master': reference broken
> Что можно сделать?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/65#issuecomment-250718372>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABE0z6wTzcA6EZgnKlHqPfdIx3q1H5KLks5qvO0rgaJpZM4J9G4m>.
>

2016-09-30 16:14 UTC, xslavakarachev commented
Здравствуйте, я сделал коммит и теперь не могу отправлять задачи, выдаёт ошибку : 
0 files committed, 1 file failed to commit: Zada4ki On branch master Your branch is up-to-date with 'origin/master'. nothing to commit, working tree clean
Не подскажите, что это может быть?

2016-10-04 05:22 UTC, mglukhikh commented
Вообще такое сообщение выдаётся, когда нет изменений для коммита. Хорошо бы посмотреть на компьютере. Или хотя бы скриншот.

2016-10-04 05:23 UTC, mglukhikh commented
А фигурная скобка у вас действительно не закрыта, так что программа не компилируется.

2016-10-15 19:44 UTC, mglukhikh commented
recheck all

2016-10-15 19:46 UTC, mglukhikh commented
recheck all

2016-10-15 20:04 UTC, mglukhikh commented
В целом всё хорошо. Посмотрите, пожалуйста, вкладку Files Changed и поправьте код в соответствии с оставшимися там замечаниями, их немного. Прошу сделать это ДО того, как вы начнёте решать другие задачи. Ну и на будущее -- попробуйте решить хотя бы одну задачу, помеченную как "Сложная".

2016-10-26 14:35 UTC, xslavakarachev commented
Исправил все ваши замечания перед решением задач

2016-10-28 07:55 UTC, mglukhikh reviewed
В целом всё нормально, остались незначительные замечания. Я сейчас закрою PR, исправьте остаток замечаний в следующем, пожалуйста

2016-10-28 07:55 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            a = b
Здесь какая-то очень сложная логика. Первый же найденный делитель будет максимальным. Только начать надо с `n - 1`, а не с `n`, естественно.

2016-10-28 07:55 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        } else n1 -= m1
Фигурные скобки либо ставьте для обеих веток, либо не ставьте для обеих веток. А так выглядит очень странно

2016-10-28 07:55 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return true
Эту задачу можно решить гораздо более эффективно, используя идеи из `lcm`.

2016-10-28 07:55 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var PX = 0.0 //peremennaya P ot X (p(x) = p0 + p1*x + p2*x^2 + p3*x^3 + ... + pN*x^N.)
Лучше `px`, капсом принято называть только константы

2016-10-28 07:56 UTC, mglukhikh commented
recheck all

2016-10-28 07:59 UTC, mglukhikh commented
4 урока приняты с незначительными замечаниями

2016-10-28 07:59 UTC, closed without merging