Решенные задачи первого урока. Шумеева
Kotlin-Polytech/KotlinAsFirst2016 pull request #66
Opened 2016-09-14 19:38 UTC by Galentin

2016-09-14 20:45 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = ( sagenes* 48* 4.445  +arshins*16*4.445 + vershoks*4.445)/100
В будущем переносите такие длинные строки, пожалуйста. Обычно удобно поставить перенос сразу после знака равенства

2016-09-14 20:46 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial * (( 1.00 + (percent/100.00))*( 1.00 + (percent/100.00))*( 1.00 + (percent/100.00)))
Здесь следует использовать функцию Math.pow для вычисления куба числа, а не писать одно и то же выражение три раза. Поправьте это место, пожалуйста

2016-09-14 21:59 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +fun thirdDigit(number: Int): Int = TODO ()
- В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков.

2016-09-27 10:27 UTC, mglukhikh commented
В уроке 2, пожалуйста, поправьте ошибку в задаче ageDescription. И не забудьте про замечания к уроку 1

2016-09-27 10:28 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        return "$age лет"
else пишется на одном уровне с if:

```
if (...)
    return ...
else
    return ...
```

2016-09-27 10:29 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +            )
Внешние скобки вокруг if...else не нужны и только затрудняют восприятие кода

2016-09-27 10:30 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +
Лишние пустые строки портят код, особенно, когда находятся посередине между else и if.

2016-09-27 10:30 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    else
else if лучше писать вместе

2016-09-27 10:31 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        if   ( (a1 > b1 + c1) || (b1 > a1+ c1) || (c1 > a1 +b1))
Пробелы расставлены хаотично. Либо ставьте пробелы между аргументами и знаками операций, либо нет.

2016-10-03 16:19 UTC, mglukhikh requested changes
По-прежнему много замечаний по форматированию кода. Советую исправить его с помощью Ctrl+Alt+L в IDEA и в дальнейшем придерживаться такого же стиля. Ошибку в задаче, вижу, вы исправили. Пожалуйста, исправьте проблемы с форматированием, прежде чем начинать решать что-то ещё.

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int =  (hoursArrive *60 +  minutesArrive ) - ( hoursDepart * 60 + minutesDepart)
Слишком длинная строка

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = hours*3600 + minutes* 60 + seconds
Хаотично стоящие пробелы

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +        ( sagenes* 48* 4.445  +arshins*16*4.445 + vershoks*4.445)/100
Хаотично стоящие пробелы

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad+ (min + sec/60.00)/60.00)/180 *Math.PI
Хаотично стоящие пробелы

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial *  Math.pow((1.00 + (percent/100.00)),3.00)
После запятой, как и в текстах на русском языке, ставится пробел

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int =  (number /100) + ((number % 100)/ 10) * 10 + ( number % 10)*100
Хаотично стоящие пробелы

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +         if ((rookX2 == kingX) || (rookY2 == kingY)) return 2
Этот оператор следует сдвинуть назад, на один уровень с прочими операторами

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +         if ((rookX == kingX) || (rookY == kingY)) return 1
Этот оператор следует сдвинуть назад, на один уровень с прочими операторами

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if ((a> b+c ) || (b> c+a) || (c>b+a))
Хаотично стоящие пробелы

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if (number/1000 + (number%1000)/100 == (number%100)/10+ number%10 ){
Хаотично стоящие пробелы

2016-10-03 16:19 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            0){
Перенос строки в условии не нужен

```
    while (m != 0) {
        ...
    }
```

2016-10-08 14:30 UTC, mglukhikh reviewed
Остались незначительные замечания по выравниванию кода. Pull request я вам закрою, но в следующем pull request замечания просьба исправить

2016-10-08 14:30 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            while(number2 > 0){
Неверное выравнивание. While остается на одном уровне с var. А уже в блоке фигурных скобок добавляются четыре пробела

2016-10-08 14:30 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    }
Закрывающую скобку следует сдвинуть на 4 пробела влево. Добавить также пробелы вокруг %

2016-10-08 14:30 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var kolvo = 0
При открытии фигурной скобки следует добавлять 4 пробела выравнивания

2016-10-08 14:30 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if (number / 1000 + (number % 1000) / 100 == (number % 100) / 10 + number % 10){
If (x) return true else return false эквивалентно return x

2016-10-08 14:30 UTC, closed without merging