lesson 2
Kotlin-Polytech/KotlinAsFirst2016 pull request #68
Opened 2016-09-14 21:03 UTC by Kazachenko1998

test 1 (кроме 1 и 2)

2016-09-14 21:21 UTC, gagarski commented on src/lesson1/task1/Simple.kt
> +return hours *3600+ minutes*60 +seconds
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.
- [Здесь и далее] Функции, состоящие из одного `return` в Kotlin принято записывать в однострочной форме (см. пример `sqr` и `discriminant`)

2016-09-14 21:24 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +return ss
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.
- Переменным лучше давать говорящие имена.

2016-09-14 21:25 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    var rook:Int=0; var bishop:Int=0; var ss:Int=0
`rook` и `bishop` у вас принимают значения 0 и 1, т. е. используются как булевские флаги. Используйте переменную типа`Boolean`

2016-09-14 21:29 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if ((rook==0)&&(bishop==0)) ss=0 else
`else` в цепочке ветвлений принято переносить на новую строку вместе со следующим `if`:
```kotlin
if (someCondition) someAction()
else if (someOtherCondition) someOtherAction()
else anotherAction()
```
или так:
```
```kotlin
if (someCondition) 
    someAction()
else if (someOtherCondition) 
    someOtherAction()
else 
    anotherAction()
```
В таком случае среда разработки будет сама правильно форматировать код и вам не придётся двигать "лесенку" влево руками.

2016-09-14 21:29 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        if ((a * a + b * b < c * c) or (a * a + c * c < b * b) or (b * b + c * c < a * a)) ss = 2 else
См. выше про  `else if`

2016-09-14 21:29 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    var ss: Int = 0
- Переменным лучше давать говорящие имена.

2016-09-14 21:30 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +     if (c<=a && d>=b) s = (b - a)  else
`else if`...

2016-09-14 21:30 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +return s
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-14 21:55 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if ((rookX2==kingX)or(rookY2==kingY)) bishop = 1
В данной задаче нет никакого `bishop`'а.
Также см. комментарий из следующей задачи.

2016-09-14 21:56 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +return ss
- Переменная `ss` здесь не очень нужна. Вы можете делать `return` прямо из веток ветвления.

2016-09-14 21:57 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> + * Координаты точек a, b, c, d соответственно, a <= b, c <= d.
- В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков.

2016-09-14 21:58 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +return s
- См. комментарий про `else if`

2016-09-15 21:24 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun nok(x: Int, y: Int): Int = (x / nod(x, y)) * y
Вызов `lcm` состоит только из вызова `nok`. Нужен ли `nok`?

2016-09-15 21:24 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun nod(x: Int, y: Int): Int {
По-английски НОД называется greatest common divisor (gcd). Старайтесь избегать использваония транслита в названиях функций/переменных.

2016-09-15 21:26 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    val nn = Math.max(m, n)
Проверить числа на взаимную простоту можно в одну строчку с учётом того, что вы сделали ранее в этом уроке.

2016-09-15 21:29 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if ((n % i == 0) && (m % i == 0)) failed = true
[Будет неактуально, когда исправите замечание выше] Когда вы присвоили переменной `failed` значение `true`, можно завершить выполнение функции (сделав `return` прямо из тела цикла)

2016-09-15 21:33 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (failed == true) return false else return true
[Будет неактуально, когда исправите замечания выше] Оператор `==` тоже возвращает булевское значение. 
Это ветвление **чрезвычайно** многословно для того, что оно делает.
В вашем случае его можно записать как
`return failed != true`
или ещё проще:
`return failed == false`
или совсем просто
`return !failed`

2016-09-15 21:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (failed == true) return true else return false
То же самое, что и выше про ветвления и булеву алгебру.

2016-09-15 21:45 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if ((i * i >= m) && (i * i <= n)) failed = true
Так же, как и в предыдущей задаче, можно завершить выполнение, как только будет найдено подходящее значение. Тест падает из-за того, что вы перебираете все числа от 0 до `Integer.MAX_VALUE`, хотя можно завршить цикл на первой же итерации.

2016-09-15 21:51 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun sin(x: Double, eps: Double): Double = Math.sin(x)
Вызов стандартной функции - не то, что предполагалось в этом задании. 
Нужно рассчитать синус по формуле, указанной в тексте путём постепенного суммирования членов ряда (`x`, `-x^3 / 3!` и т. д.). Когда останавливать суммирование так же сказано в тексте задания.

За математическим обоснованием формулы обращайтесь к лекциям по высшей математике или к гуглу по запросу "ряд Тейлора".

2016-09-15 21:51 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun cos(x: Double, eps: Double): Double = Math.cos(x)
См. комментарий про синус.

2016-09-15 21:52 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var nn: Int = n
- Переменным лучше давать говорящие имена.

2016-09-15 21:53 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var nn: Int = n
- Переменным лучше давать говорящие имена.

2016-09-15 21:54 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (answer == n) return true else return false
См. замечания выше про ветвления и булевские функции.

2016-09-15 21:54 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (failed == false) return true else return false
См. замечания выше про ветвления и булевские функции.

2016-09-15 21:54 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if (nn % 10 != memory) failed = false
См. замечания выше про досрочное завершение цикла.

2016-09-15 21:56 UTC, gagarski requested changes

2016-09-17 20:18 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if ((k * k <= n) && (k * k >= m)) return true else return false
`return (k * k <= n) && (k * k >= m)`

2016-09-17 20:19 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var resalt=0
`result`

2016-09-17 20:19 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var resalt=0
`result`

2016-09-17 20:19 UTC, gagarski requested changes

2016-09-17 20:22 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun sin(x: Double, eps: Double): Double {
Попробуйте протестировать вашу функцию на больших `x`: 10, 100, 1000. Правильный ли результат она выдаёт? Попробуйте подумать, почему и какое свойство синуса можно использовать чтобы это исправить.

2016-09-17 20:23 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun cos(x: Double, eps: Double): Double {
См. комментарий про синус.

2016-09-17 20:23 UTC, gagarski requested changes

2016-09-17 20:26 UTC, gagarski commented
Постарайтесь исправить текущие замечания и ошибки прежде чем приступать к следующим урокам.

2016-09-18 14:44 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if ((number % 10 + number / 10 % 10) == (number / 100 % 10 + number / 1000)) return true else return false
Здесь и далее вы используете довольно многословный способ вовзращения булевского значения.
```kotlin
if (x) return true else return false
```
эквивалентно
```kotlin
return x
```

2016-09-18 14:45 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if (((a <= r) && (b <= s)) || ((a <= s) && (b <= r)) || ((a <= r) && (c <= s)) || ((a <= s) && (a <= r)) || ((c <= r) && (b <= s)) || ((c <= s) && (b <= r))) return true else return false
Условие можно сильно упростить если заранее найти минимальные стороны кирпича.

2016-09-18 14:45 UTC, gagarski requested changes

2016-09-21 09:13 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var resalt=0
`result`

2016-09-21 09:13 UTC, gagarski commented on src/lesson4/task1/List.kt
> +
- В коммитах лучше избегать ненужных изменений, так как они усложняют объединение наборов изменений от разных разработчиков.

2016-09-21 09:18 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in (digits.size - 1) downTo 0) result = result + (digits[i] * Math.pow(base.toDouble(), ((digits.size - 1) - i).toDouble())).toInt()
Старайтесь избегать таких длинных строк. IDEA рисует вертикальную линию на 120 символах. Старайтесь придерживаться хотя бы этого ограничения и переносить строки.

2016-09-21 09:20 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..phone.length - 1) if ((phone[i] != '(') && (phone[i] != ')') && (phone[i] != '-') && (phone[i] != ' ') && (phone[i] != '+') && (phone[i]!in '0'..'9')) return ""
См. комментарий про длинные строки.

2016-09-21 09:20 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..jumps.length - 1) if ((jumps == "") || ((jumps[i] != '%') && (jumps[i] != '-') && (jumps[i] != ' ') && (jumps[i]!in '0'..'9'))) return -1
Длинные строки.

2016-09-21 09:20 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +fun chekPlus(str: String): Boolean {
`checkPlus`

2016-09-21 09:21 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..expression.length - 1) if ((expression == "") || ((expression[i] != '+') && (expression[i] != '-') && (expression[i] != ' ') && (expression[i]!in '0'..'9'))) return throw IllegalArgu
Длинные строки.

2016-09-21 09:24 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +        throw IllegalArgumentException("Description")
Вы ловите исключение `IllegalArgumentException` и тут же кидаете такое же, но с другим (бессмысленным) сообщением. Можно убрать этот `try`/`catch`.

2016-09-21 09:25 UTC, gagarski requested changes

2016-09-21 09:29 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +            result = when {
Можно использовать оператор `+=`. Также можно использовать конструкцию `when` с аргументом (для проверки на равенство).

```kotlin
result += when (parts[1]) {
    "01" -> "января"
   // и т. д.
```

2016-09-21 09:30 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +            result = when {
См. про `+=` и `when(...)` ниже.

2016-09-21 09:30 UTC, gagarski requested changes

2016-09-27 20:44 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        if (i != list.size - 1) s = s + (list[i]).toString() + "*"
Есть метод `joinToString`

2016-09-27 20:44 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +@file:Suppress("UNUSED_PARAMETER", "UNREACHABLE_CODE", "VARIABLE_WITH_REDUNDANT_INITIALIZER")
Старайтесь исправлять код с warning'ами, а не отключать их. Если вам действительно нужно их отключить (а это не такой случай), то старайтесь делать это более локально (например, для функции)

2016-09-27 20:45 UTC, gagarski approved these changes

2016-09-27 20:47 UTC, gagarski commented
Остались ошибки при вычислении синуса/косинуса (см. комментарий) и замечание по `isCoPrime`.

2016-09-27 20:47 UTC, gagarski commented
recheck all

2016-09-27 21:01 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +            return throw IllegalArgumentException("Description")
Чтобы бросить исключение нужно написать `throw IllegalArgumentException("Description")`

2016-09-27 21:02 UTC, gagarski commented
> как можно бросить исключение если мы его не ловили и не известно есть ли оно вообще?

Не понял вашего вопроса.

2016-09-27 21:10 UTC, gagarski commented
recheck all

2016-09-27 21:16 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(number) * 1000 > eps) {
Вы таким способом неявно повышаете заданную точность. Вспомните свойства синуса.

2016-09-27 21:18 UTC, gagarski commented
> Остались ошибки при вычислении синуса/косинуса (см. комментарий) и замечание по isCoPrime.

Также остались замечания по 1-2 урокам

2016-09-27 21:19 UTC, gagarski requested changes
`sin`, `cos`, `isCoPrime`, замечания по 1-2 урокам.

2016-09-27 21:22 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (Math.abs(number) * 1000 > eps) {
Вызовите `sin(Math.PI / 2, 0.01)` и `sin(2000 * Math.PI + Math.PI / 2, 0.01)`. Правильные ли результаты возвращает функция?

2016-09-27 21:44 UTC, gagarski requested changes

2016-09-27 21:44 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +            if ((sqr(center.x - p.x) + sqr(center.y - p.y)) <= sqr(radius)) true
Снова `if (...) true else false`.

2016-09-27 21:44 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    fun distance(first : Point, second : Point): Double = Math.sqrt(sqr(first.x - second.x) + sqr(first.y - second.y))
Расстояние между точками уже реализовано в классе `Point`.

2016-09-27 21:44 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        var jj = 0
Можно хранить не индексы, а сами точки. Операция присваивания не будет более медленной, поскольку при присваивании будут присваиваться ссылки на лочки.

2016-09-27 21:44 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        for (i in 0..points.size-1)
Когда внутри `for` только одно выражение, можно записывать его без фигурных скобок. Но если это выражение неоднострочное (как другой `for` или `if`), то запись без скобок немного затрудняет понимание участка кода.

2016-09-27 21:57 UTC, Kazachenko1998 commented
есть еще какие-то замечания по 1-3 урокам?

2016-09-27 22:11 UTC, gagarski commented
> есть еще какие-то замечания по 1-3 урокам?


 - Обратите внимание, что не проходят тесты для `ageDescription`  и `brickPasses`
 - Когда будете чинить `brickPasses`, попробуйте таки найти две минимальные стороны кирпича заранее и посмотреть, насколько условие станет проще.
 - Постарайтесь осознать, что когда вы пишете `if (x) true else false` или `if (x) return true else return false` это полностью эквивалентно `x` или `return x` соответственно (попробуйте убедиться в этом в уме или на бумаге для `x == true` и `x == false`). Вы везде пишете код вроде
```kotlin
 fun circleInside(x1: Double, y1: Double, r1: Double,
                  x2: Double, y2: Double, r2: Double): Boolean = TODO()
                  x2: Double, y2: Double, r2: Double): Boolean =
         if ((Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) + r1) <= r2) true else false
```
когда можно написать
```kotlin
 fun circleInside(x1: Double, y1: Double, r1: Double,
                  x2: Double, y2: Double, r2: Double): Boolean = TODO()
                  x2: Double, y2: Double, r2: Double): Boolean =
         Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) + r1) <= r2
```
(результат операции `<=` **уже** булевское значение). Исправлять это везде сейчас не нужно, но в будущем постарайтесь вспомниать об этом, если будете писать такие конструкции.
 - Синус и косинус всё ещё сломаны

2016-09-27 22:15 UTC, gagarski approved these changes

2016-09-28 22:55 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun sin(x: Double, eps: Double): Double {
Исправлено

2016-09-28 23:08 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +        throw NumberFormatException("IllegalArgumentException")
Опечатка: видимо вы имели в виду `throw IllegalArgumentException("IllegalArgumentException")`

2016-09-28 23:08 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +@Suppress("VARIABLE_WITH_REDUNDANT_INITIALIZER")
Лучше чем для всего файла, но всё же попробуйте понять, почему этот warning появляется.
Скорее всего он возникает из-за того, что вы объявляете переменную `string`, инициализируя её пустым списком: 
```kotlin
var string = listOf<String>()
```
а затем, не используя это значение, меняете значение переменной:
```kotlin
string = description.split("; ")
```

Следуя сообщению из warning'а, можно убрать инициализирующее значение, но тогда компилятор не сможет вывести тип переменной, поэтому нужно указать его вручную:
```kotlin
var string: List<String>
```

После этого и warning'а не будет и область видимости переменной будет такая, как вам нужна.

2016-09-28 23:08 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        if (string1[i] in '0'..'9') list += ((string1[i]).toInt() - 48)
Лучше написать не 48, а `'0'.toInt()`, так будет понятно, что это за число.

2016-09-28 23:09 UTC, gagarski commented
> [Normal] lesson4.task1/center
org.opentest4j.AssertionFailedError : You should mutate an input list, not create a copy
[Normal] lesson4.task1/center
org.opentest4j.AssertionFailedError : You should mutate an input list, not create a copy

Это сообщение говорит о том, что список поданный на вход функции должен быть изменён после её вызова

2016-09-28 23:15 UTC, gagarski commented
Есть ошибки (`plusMinus` и `center`, см. тесты)
По 1-5 уроку замечаний по коду, которые надо исправить нет. 
По 6 уроку есть замечание про `distance` и про индексы в `diameter`

2016-09-29 16:35 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = (nod(m, n) > Math.min(m, n)) || (nod(m, n) == 1)
Зачем первое условие в ИЛИ (`nod(m, n) > Math.min(m, n))`). Разве НОД двух чисел может быть больше какого-то из них?

2016-09-29 21:14 UTC, Kazachenko1998 commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = (nod(m, n) > Math.min(m, n)) || (nod(m, n) == 1)
а разве НОД 5 и 10 не равен 5?
![image](https://cloud.githubusercontent.com/assets/22072948/18972690/d7ffea18-86a2-11e6-8a45-80b7cc81ff91.png)

2016-09-29 21:32 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = (nod(m, n) > Math.min(m, n)) || (nod(m, n) == 1)
Во-первых, 5 разве больше пяти?
Во-вторых, 5 и 10 не взаимно простые числа

2016-09-29 21:42 UTC, Kazachenko1998 commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = (nod(m, n) > Math.min(m, n)) || (nod(m, n) == 1)
да, это было глупо... я забыл что мне нужно верное условие а не ложное...

2016-09-30 18:29 UTC, belyaev-mikhail commented
recheck assignment

2016-09-30 18:56 UTC, belyaev-mikhail commented
recheck assignment

2016-09-30 19:02 UTC, belyaev-mikhail commented
recheck assignment

2016-10-01 15:39 UTC, belyaev-mikhail commented
recheck assignment

2016-10-01 17:58 UTC, Kazachenko1998 commented
Expected:
x=-632.0, y=-999.4227867839951, radius=0.5766311693979751         
x=-632.0, y=-999.9849946518009, radius=0.4792190693119849
S ==             0.562207868, и она пересекается
Actual:
x=-632.0, y=-999.9849946518009, radius=0.4792190693119849
x=-632.0, y=-1000.0                     , radius=0.3337186732548538
S ==             0.0150053482, и она пересекается
Разве действительный результат не верный?

2016-10-03 17:23 UTC, gagarski commented
recheck all

2016-10-04 11:47 UTC, gagarski requested changes

2016-10-04 11:47 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +            if ((circles[i].distancee(circles[j]) <= min) && (circles[i].center != circles[j].center)) {
В данной задаче предполагается, что вы будете использовать функцию расстояния, которую вы определили в классе `Circle`. Ваше доопределённое для пересекающихся окружностей расстояние противоречит `distance`. Просто используйте `distance`.

2016-10-04 11:47 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    fun distancee(other: Circle): Double =
Если уж определяете новые методы, то придумывайте им названия, отражающие их суть (а не лишь бы отличалось от другого метода). (Кстати, этот метод не нужен, см. комментарий к `findNearestCirclePair`).

2016-10-04 11:47 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    var maxPoint = PointInt(0, 0)
Никогда не храните в объектах класса то, для чего они не предназначены или не соответствует их названию. Класс `PointInt` представляет точку на плоскости с целочисленными координатами (судя по вашему же названию). Если вы хотите хранить произвольную пару чисел, используйте стандартный класс `Pair` или определите свой класс с соответствующим названием

2016-10-04 11:47 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        if (Math.abs(Math.cos(angle)) <= 0.00000000001) {
Лучше записывать такие числа в экспоненциальной форме: `1e-11`

2016-10-04 11:47 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        } else if (Math.cos(other.angle) == 0.0) {
Почему выше сравнение с дельтой, а тут - строгое?

2016-10-04 11:47 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        } else if (Math.cos(other.angle) == 0.0) {
Можно ли обойтись одним особым случаем, когда прямые параллельны?

2016-10-04 11:47 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    var point = PointInt(0, 1)
`Pair`

2016-10-04 13:23 UTC, Kazachenko1998 commented on src/lesson6/task1/Geometry.kt
> +        } else if (Math.cos(other.angle) == 0.0) {
если прямые параллельны то точки пересечения нет, а что делать в этом случае не сказано=> такого случая быть не должно!хотя конечно можно бросить исключение, но ведь это не просят... зачем делать лишнюю работу?

2016-10-04 18:41 UTC, Kazachenko1998 commented
а в чем ошибка?
ожидаемый результат - (пусто)
действительный результат- (пусто)
Ошибка- список пуст

2016-10-05 13:25 UTC, gagarski commented
recheck all

2016-10-05 13:28 UTC, gagarski commented
recheck all

2016-10-05 13:32 UTC, gagarski commented
> а в чем ошибка?
ожидаемый результат - (пусто)
действительный результат- (пусто)
Ошибка- список пуст

Тесты для слона починил, `circleByThreePoints` пока не смотрел.

2016-10-06 10:14 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +        } else if (Math.cos(other.angle) == 0.0) {
Справедливо, но, во-первых, замечание про дельту всё ещё актуально, а во-вторых, я писал скорее о том, что применив формулы тригонометрии можно обойтись без кода вроде `if (Math.abs(Math.cos(angle)) <= 0.00000000001)`

2016-10-06 15:40 UTC, gagarski commented
recheck assignment

2016-10-06 15:43 UTC, gagarski commented
recheck all

2016-10-06 15:44 UTC, gagarski commented
recheck all

2016-10-06 16:02 UTC, belyaev-mikhail commented
recheck all

2016-10-06 16:13 UTC, belyaev-mikhail commented
recheck all

2016-10-06 16:30 UTC, belyaev-mikhail commented
recheck all

2016-10-06 16:37 UTC, belyaev-mikhail commented
recheck all

2016-10-06 17:48 UTC, gagarski requested changes

2016-10-06 17:48 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +    if ((x == Double.NaN) || (y == Double.NaN) || (r == Double.NaN) ||
Зачем всё это?

Во-первых, как ни странно, `Double.NaN != Double.NaN` (можете проверить). Нужно проверять на NaN методом `isNan()`. Также есть метод `isInfinite()`.
Во-вторых, в задании не сказано, что делать при невозможности построить окружность, так что можно оставить всё как есть (вроде сейчас мы не должны подавать на вход такие данные).

2016-10-24 11:06 UTC, gagarski commented
recheck all

2016-10-24 11:16 UTC, gagarski requested changes

2016-10-24 11:16 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +            (Math.abs(Math.cos(angle)) == Math.cos(Math.PI / 2)) -> point.x
Лучше `Math.tan(angle).isInfinite()`

2016-10-24 11:16 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?) =
Разве этих условий достаточно для сравнения матриц на равенство?

2016-10-24 11:16 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +    override fun equals(other: Any?) =
Скорее всего вы сгенерировали `equals` и `hashCode` автоматически до того, как добавили `list`. Попробуйте сгенерировать их заново или исправить вручную чтобы они выполняли корректное сравнение.

2016-10-24 12:22 UTC, gagarski commented
recheck all

2016-10-24 12:25 UTC, gagarski commented
recheck all

2016-10-24 12:49 UTC, gagarski commented
recheck all

2016-10-24 12:52 UTC, gagarski commented
recheck all

2016-10-24 12:57 UTC, gagarski commented
recheck all

2016-10-24 12:59 UTC, gagarski commented
recheck all

2016-10-24 13:26 UTC, gagarski commented
recheck all

2016-10-24 13:26 UTC, gagarski commented
recheck all

2016-10-24 13:29 UTC, gagarski commented
recheck all

2016-10-24 13:33 UTC, gagarski requested changes

2016-10-24 13:33 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +        6 -> 2
Если вы хотите представить направления (вверх/вниз/влево/вправо) в программе, то используйте пречисления: https://kotlinlang.org/docs/reference/enum-classes.html

2016-10-25 17:20 UTC, Kazachenko1998 commented on src/lesson6/task1/Geometry.kt
> +            (Math.abs(Math.cos(angle)) == Math.cos(Math.PI / 2)) -> point.x
При замене (Math.abs(Math.cos(angle)) == Math.cos(Math.PI / 2)) на Math.tan(angle).isInfinite() программа ломается и не выводит ничего.

2016-10-25 21:25 UTC, Kazachenko1998 commented
может я конечно ошибаюсь, но программа должна работать верно в отличии от бота? ибо я не понимаю почему в последней посылке ожидается такой ответ, а не мой.

2016-10-27 09:58 UTC, gagarski commented
recheck all

2016-10-27 12:23 UTC, gagarski commented
recheck all

2016-10-28 22:05 UTC, Kazachenko1998 commented
Почините, пожалуйста, бота в lesson7.task2/canOpenLock
И какие замечания нужно устранить по прошлым урокам?

2016-11-01 13:07 UTC, gagarski commented on src/lesson6/task1/Geometry.kt
> +            (Math.abs(Math.cos(angle)) == Math.cos(Math.PI / 2)) -> point.x
Что значит "не выводит ничего"? При каких входных данных?

2016-11-01 13:07 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +fun cos(x: Double, eps: Double): Double {
Исправлено

2016-11-01 13:10 UTC, gagarski commented
> И какие замечания нужно устранить по прошлым урокам?
Можно посмотреть комментарии [тут](https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/68/files)

2016-11-08 13:40 UTC, gagarski requested changes

2016-11-08 13:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        if (isPrime(i) == true)
Можно обойтись без проверки на простоту. Вы перебираете числа по возрастанию и делите число на все встречающиеся делители. После этого число просто не будет делиться на составные числа (поскольку они являются произведением простых меньше него). Например, вы нашли делители 2, 2, 3, 5 и поделили `number` на них. После этого число уже не будет делиться на 4, 6, 8, 12, 15, 16 и т. д.

`isPrime`, кстати уже был в третьем уроке в примерах.

2016-11-08 13:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        result += (digits[i] * Math.pow(base.toDouble(), ((digits.size - 1) - i).toDouble())).toInt()
Не стоит переходить к числам с плавающей точкой в целочисленных задачах чтобы не столкнуться с ошибками округления. реализуйте `pow` для целых чисел, либо считайте множитель внутри цикла.

2016-11-08 13:40 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    val rom = listOf("I", "IV", "V", "IX", "X", "XL", "L", "XC", "C", "CD", "D", "CM", "M")
Лучше список из пар, чем два списка, связанных общим индексом.

2016-11-08 13:40 UTC, gagarski commented on src/lesson5/task1/Parse.kt
> +    } catch (e: IllegalArgumentException) {
Вы ловите `IllegalArgumentException` и тут же бросаете исключение такого же класса, но без сообщения. Нужен ли этот try/catch вообще?

2016-11-08 13:40 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        val sb = StringBuilder()
Ваша реализация `toString` записывает все числа из стоки матрицы подряд, без пробелов, запятых и пр. Хотя требований в задании к её реализации нет, лусшу бы это исправить.

2016-11-08 13:40 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        var result = 5
Хорошая функция `hashCode()` должна учитывать все значимые поля класса. 
Если вы её сгенерировали с помощью IDE автоматически, то, как минимум, сгенерируйте её заново, а лучше погуглите и почитайте, зачем он нужен и как его лучше реализовывать.

2016-11-08 13:40 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    while (i < moves.size - 1) {
Для простого цикла по списку лучше `for`

2016-11-08 13:40 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    for (n in 0..15) {
Перечитайте эту проверку на корректность ходов. Во-первых, это не работает (вы проверяете, что есть **хотя бы один** корректный ход), во-вторых, это кромешный ад. Нужно просто пройтись по матрице и проверить каждый из элементов на то, что они лежат в диапазоне 1..15. Если какой-либо элемент не лежит, можно сразу бросить исключение.

2016-11-08 13:40 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    for (n in 0..15) {
Снизу, кстати, есть нормальная проверка.

2016-11-08 13:40 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    var matrix2 = createMatrix(matrix.height + 2, matrix.width + 2, 0)
Попробуйте обойтись без копирования матрицы в матрицу расширенного размера. Это не сильно упрощает логику.

В `matrix[0,0]` вы временно кладёте `Cell` перед обменом.

Ветки `when` лучше оформить как
```kotlin
when {
    isInside(cell.row + 1, cell.column) && moves[i] == matrix2[Cell(cell.row + 1, cell.column)] -> {}
   // ...
}
```

`isInside` реализуйте отдельно.

2016-11-08 14:00 UTC, gagarski commented
recheck all

2016-11-08 14:16 UTC, gagarski commented
recheck all

2016-11-21 14:21 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        val sb = StringBuilder()
актуально

2016-11-21 14:21 UTC, gagarski commented on src/lesson7/task1/Matrix.kt
> +        var result = 5
актуально

2016-11-21 14:23 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    for (n in 0..15) {
Неактуально

2016-11-21 14:24 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    var matrix2 = createMatrix(matrix.height + 2, matrix.width + 2, 0)
Вроде же исправляли на занятии? А в репозитории нет.

2016-11-24 10:26 UTC, gagarski commented on src/lesson7/task2/Matrices.kt
> +    var list2 = listOf<Int>()
`list2` лучше сделать локальной переменной внутри циклов, и инициализировать пустым списком при создании

2016-11-25 07:56 UTC, mglukhikh commented
recheck all

2016-11-25 08:13 UTC, mglukhikh commented
recheck all

2016-11-25 08:18 UTC, mglukhikh commented
Рад вам сообщить, что вы выполнили программу этого семестра с оценкой "ОТЛИЧНО" (можете подойти ко мне с зачёткой, и я вам эту оценку поставлю). При желании, можно порешать ещё какие-нибудь задачи.

2016-11-25 08:20 UTC, mglukhikh commented
Должен вас также поблагодарить за помощь в тестировании нашей инфраструктуры

2016-11-28 19:33 UTC, Kazachenko1998 commented
recheck all

2016-11-28 20:16 UTC, gagarski commented
Проблема в том что вы (не без моего участия) добавили метод в интерфейс `Matrix`. При тестировании используется другая реализация этого интерфейса, в которой этого метода нет.

Вывод: изменения в интерфейсе могут привести к боли.

Можно добавить дефолтную реализацию метода `toList` в интерфейсе `Matrix` (она может использовать только методы этого интерфейса). Можно вообще убрать этот метод, поскольку вы его не используете.

2016-11-28 21:04 UTC, Kazachenko1998 commented
Возникли небольшие трудности с IDEA(сильно сбились настройки) из-за чего столько посылок

2016-11-29 06:22 UTC, gagarski commented
recheck all

2016-11-29 14:53 UTC, gagarski commented
recheck all

2016-12-05 13:04 UTC, gagarski commented
recheck all

2016-12-05 13:13 UTC, gagarski commented
По проваленным тестам в 8 уроке:

`countSubstrings` - исправил референсное решение, стал проходить.
`centerFile` - проверьте выполнение требования про число строк
`sibilants` - то же самое.

2016-12-05 13:35 UTC, gagarski commented on src/lesson8/task1/Files.kt
> +    for (line in File(inputName).readLines())
`File().readText()`

2017-07-26 18:24 UTC, closed without merging