Решён первый урок
Kotlin-Polytech/KotlinAsFirst2016 pull request #73
Opened 2016-09-15 10:31 UTC by CrazyJen

2016-09-15 11:09 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    }
Отформатируйте код при помощи IntelliJ IDEA и в будущем постарайтесь придерживаться данного стиля форматирования

2016-09-15 11:10 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val num = number/100
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-09-15 11:12 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val perc = percent + 100
Вместо деления на 1,000,000 лучше перевести проценты в соответствующую им математическую величину

2016-09-15 11:13 UTC, ice-phoenix requested changes

2016-09-21 19:41 UTC, mglukhikh commented
Автору Pull Request: пожалуйста, напишите своё имя, фамилию и номер группы либо здесь в комментарии, либо мне на e-mail (glukhikh@mail.ru)

2016-09-23 10:46 UTC, ice-phoenix commented
Все выглядит правильно.

2016-09-23 10:47 UTC, closed without merging