lesson2/task1. Первая задача
Kotlin-Polytech/KotlinAsFirst2016 pull request #75
Opened 2016-09-15 10:38 UTC by Gukavina

2016-09-15 12:21 UTC, ice-phoenix commented
Просьба проверить соответствие имени в репозитории и имени на GitHub.

2016-09-15 12:22 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int) = initial*(percent/100.0+1)*(percent/100.0+1)*(percent/100.0+1)
Общее выражение лучше вынести в отдельную переменную

2016-09-15 12:22 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int) = number%10*100+number/10%10*10+number/100%10
Отдельные подвыражения лучше вынести в переменные с осмысленными именами

2016-09-15 12:24 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (age % 10 == 1) {
Подумайте над тем, как записать данную цепочку `if`'ов в виде `when`

2016-09-15 12:24 UTC, ice-phoenix requested changes

2016-09-19 10:06 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    } else {
`else { if ... }` лучше оформлять как `else if ...`

2016-09-19 10:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((rookX1 == kingX)or(rookY1 == kingY)or(rookX2 == kingX)or(rookY2 == kingY)){
Факт того, что какая-то фигура бьет короля, лучше вынести в отдельные переменные

2016-09-19 10:07 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if(((kingX-kingY) == (bishopX-bishopY))or(bishopX-kingX == bishopY-kingY)or(bishopX-kingX == -(bishopY-kingY))){
Факт того, что какая-то фигура бьет короля, лучше вынести в отдельные переменные

2016-09-19 10:08 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((a+b>c)and(b+c>a)and(a+c>b)){
Удобнее сперва найти максимальную сторону треугольника, а потом все считать относительно нее

2016-09-19 10:09 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a > d) return (-1)
Данное выражение лучше оформить как `when`

2016-09-19 10:09 UTC, ice-phoenix requested changes

2016-09-21 09:33 UTC, ice-phoenix commented
Разберитесь с тем, что ваш код для `timeForHalfWay` должен возвращать в случае, если итоговая пройденная дистанция равна 0.

2016-09-22 10:19 UTC, ice-phoenix commented
Просьба исправить **все** приведенные к задачам замечания перед подачей следующих PR

2016-09-22 10:20 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (sum34 == sum12) {
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-22 10:21 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((x1 == x2) or (y1 == y2) or (x1-x2 == y1-y2) or (x1-x2 == y2-y1))
* Выражение `(x1-x2 == y1-y2) or (x1-x2 == y2-y1)` можно посчитать проще, если вспомнить о такой функции, как модуль числа
* Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-22 10:22 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((sAB<=sHole)or(sCB<=sHole)or(sAC<=sHole)) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-22 10:22 UTC, ice-phoenix requested changes

2016-09-29 08:52 UTC, ice-phoenix requested changes
Просьба исправлять замечания перед подачей следующих PR

2016-09-29 08:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((age % 100 < 15) and (age % 100 > 11)) -> "$age лет"
Подумайте, нельзя ли упростить некоторые из данных условий, например, объединив их вместе?

2016-09-29 08:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val sAll = (t1*v1+t2*v2+t3*v3)/2
Повторно используемые выражения лучше вынести в отдельные переменные

2016-09-29 08:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if(((kingX-kingY) == (bishopX-bishopY))or((bishopX-kingX) == (bishopY-kingY))or(bishopX-kingX == -(bishopY-kingY))){
Факт того, что какая-то фигура бьет короля, лучше вынести в отдельные переменные

2016-09-29 08:52 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) + r1) <= r2) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-29 08:52 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((((s>=a)and(r>=c))or((r>=a)and(s>=c)))or(((s>=b)and(r>=a))or((r>=b)and(s>=a)))or(((s>=b)and(r>=c))or((r>=b)and(s>=c)))) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-29 08:52 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((((s>=a)and(r>=c))or((r>=a)and(s>=c)))or(((s>=b)and(r>=a))or((r>=b)and(s>=a)))or(((s>=b)and(r>=c))or((r>=b)and(s>=c)))) return true
Лучше сперва найти две минимальные стороны кирпича, а потом все считать относительно них

2016-09-29 18:20 UTC, ice-phoenix commented
Ваши PR не будут проверяться до тех пор, пока вы не исправите замечания к предыдущим PR.

2016-09-30 08:24 UTC, ice-phoenix commented
Если мы с вами посмотрим во вкладку `Files changed`, то увидим там достаточно большое количество комментариев, которые вы пропустили при исправлении. Убедительная просьба
* пользоваться страницей `Files changed` для просмотра замечаний преподавателя
* использовать систему комментариев к PR для общения с преподавателем, а не писать вопросы в коммит-сообщение (задача коммит-сообщения --- кратко описывать то, что было сделано в данном коммите)
* исправить те замечания, которые были вами пропущены

2016-10-06 11:53 UTC, ice-phoenix requested changes
Исправьте замечания перед продолжением работы над следующими задачами

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (ten == 1) -> when { (oneHundred == 11) -> "$age лет"
Вложенный `when` лучше унести на новую строку

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (sAll > 0) {
Данное выражение лучше оформить как `when`

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val rook1Danger: Boolean = (rookX1 == kingX) or (rookY1 == kingY)
* Система типов Котлина выведет тип переменной автоматически

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((rook1Danger == true) or (rook2Danger == true)) {
Данное выражение лучше оформить как `when`

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val bishopDanger: Boolean = ((kingX - kingY) == (bishopX - bishopY)) or ((bishopX - kingX) == (bishopY - kingY)) or (bishopX - kingX == -(bishopY - kingY))
* Система типов Котлина выведет тип переменной автоматически

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (bishopDanger == true) {
Данное выражение лучше оформить как `when`

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (a >= b) {
Все это лучше сделать как `if (a >= b && a >= c) ... else if (b >= a && b >= c) ... else ...`

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return (result)
Можно сразу `return when ...`

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val result = when {
Все вложенные `when` можно записать условиями `when` на первом уровне

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (sum34 == sum12)
Лишние скобки

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun brickPasses(a: Int, b: Int, c: Int, r: Int, s: Int): Boolean = ((((s >= a) and (r >= c)) or ((r >= a) and (s >= c))) or (((s >= b) and (r >= a)) or ((r >= b) and (s >= a))) or (((s >= b) and (r >
Данное условие лучше перенести на следующую строчку + хорошо было бы разнести отдельные подусловия на отдельные строчки

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val nn=n-1
Форматирование кода

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        return (result)
Лишние скобки

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun nod(x:Int, y: Int): Int = if (x!= 0) nod(y%x,x) else y
`nod ==> gcd` + форматирование кода

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return(result)
Можно все сделать one-liner'ом через `fun foo() = ...` синтаксис

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return(i)
Форматирование + скобки

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return(i)
Форматирование + скобки

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var result = 0
Можно ли решить эту задачу через уже реализованные вами функции?

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun squareBetweenExists(m: Int, n: Int): Boolean = ((sqr(Math.sqrt(n.toDouble()).toInt())>=m)and(sqr(Math.sqrt(n.toDouble()).toInt())<=n))
Форматирование + для округления лучше использовать специальные функции `round / floor / ceil`

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var mark=1
Форматирование + скобки

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun cos(x: Double, eps: Double): Double = sin(x+Math.PI/2,eps)
Браво! Хоть кто-то вспомнил про тригонометрию!

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return(result)
Форматирование + скобки

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +return (n==n2)
Форматирование + скобки

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +var n1=n
Можно ли данную задачу решить через уже реализованные вами ранее функции?

2016-10-06 11:53 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    (n..number - 1).forEach { i -> result /= 10 }
Менять внешнюю переменную внутри лямбды --- **очень плохой** стиль, лучше воспользоваться старым добрым циклом `for`

2016-10-27 11:48 UTC, ice-phoenix commented
recheck all

2016-10-27 12:49 UTC, ice-phoenix requested changes
Довольно много замечаний, исправьте их, пожалуйста, перед продолжением работы над следующими уроками

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int) = (hoursArrive * 60 + minutesArrive) - (hoursDepart * 60 + minutesDepart)
Длинные строчки обычно разбивают на несколько более коротких, в данном случае, можно перенести строку после знака `=`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val numberConversely = number % 10 * 100 + number / 10 % 10 * 10 + number / 100 % 10
Можно обойтись без промежуточной переменной и записать функцию как one-liner

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (ten == 1) ->
Лучше записать плоско как
```
when {
    ten == 1 && oneHundred == 11 -> ...
    ten == 1 -> ...
    ...
}
```

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val sAll = (t1 * v1 + t2 * v2 + t3 * v3) / 2
Лучше посчитать `sAll` из отдельных составных частей, которые вы и так считаете ниже

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (sAll > 0) ->
Вот эту проверку лучше, наоборот, вытащить наружу (так как она проверяет входные данные на допустимость) в виде отдельного `if` с `return`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (sAll > 0) ->
Но, в принципе, так тоже неплохо

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {((rook1Danger == true) or (rook2Danger == true)) ->
* Весь этот `when` можно записать плоско и проще, если вспомнить, что невыполнение какой-либо ветки из `when` означает, что ее условие точно **не** выполняется
* Вместо проверки переменных типа `Boolean` на равенство `true / false` лучше просто оставить `rook1Danger / !rook1Danger`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {(bishopDanger == true) and (rookDanger == true) -> 3
См. замечание к `whichRookThreatens`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    } else {
`else if (...)`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        if (cosMax >= 0.0) {
Данное выражение лучше оформить как `when`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        else ->
`else -> when ...` можно заменить, вытащив все условия вложенного `when` во внешний

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (a > d) or ((a < d) and (c > b)) -> -1
[Здесь и много где] Лучше использовать `&& / ||` вместо `and / or`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +                else -> 0
Если вы внимательно посмотрите на условия, то сможете увидеть, как можно упростить вычисление точек, которые участвуют в вычислении длины пересечения

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return ((x1 == x2) or (y1 == y2) or (Math.abs(x1 - x2) == Math.abs(y1 - y2)))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        ((((s >= a) and (r >= c)) or ((r >= a) and (s >= c)))
Лишние скобки вокруг выражений

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var nn: Int = n
* Система типов Котлина выведет тип переменной автоматически

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        return result
Можно сразу `return row[nn]`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int = m * n / gcd(m, n)
:+1:

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i = n - 1
Нет ли более точной верхней границы для возможных делителей числа `n`, чем `n - 1`?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (gcdMN == 1) return true
Выражение `if (cond) return true else return false` можно заменить на `return cond`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +//  var result = 0
Устаревшие комментарии лучше удалять

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun squareBetweenExists(m: Int, n: Int): Boolean = sqr(Math.floor(Math.sqrt(n.toDouble()))) >= m && sqr(Math.floor(Math.sqrt(n.toDouble()))) <= n
Повторно вычисляемое выражение лучше вынести в отдельную переменную

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        mark = 0 - mark
Лучше `mark = -mark`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        newElement = Math.pow(x % (Math.PI * 2), ind.toDouble()) / factorial(ind)
Зачем постоянно вычислять `x % (2 * PI)`?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun cos(x: Double, eps: Double): Double = sin(x + Math.PI / 2, eps)
:+1:

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (nn % x != n) x *= 10
Может быть, это можно выразить через возведение в степень?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return n == nn
Можно сразу `... = revert(n) == n`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number = 0
Нет ли у вас уже функции с точно такой же функциональностью?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    (n..number - 1).forEach { i -> result /= 10 }
Это лучше записать через старый добрый цикл `for`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    /**
Устаревший комментарий

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun squareList(list: List<Double>) = list.map { it * it }
Данная функция является излишней, намного понятнее везде, где нужен ее вызов, просто писать `list.map{ it * it }`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Лучше записать это как
```
if (...) return list.sum() / list.size
else return 0.0
```

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val average = list.sum() / list.size
Если записать `average` через `mean(...)`, то можно обойтись без проверки `list.isNotEmpty()`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (p.isEmpty()) return 0.0
Зачем нужна эта проверка? Что вернет код ниже, если список пуст?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            sum += forElemtnt
Зачем вам переменная `sum`, если ее значение всегда имеет элемент `list[i - 1]`?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var minDivisor = 0
Почему эта переменная объявлена здесь, а не по месту использования?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return result.joinToString(separator = "*")
Можно оформить данную функцию как one-liner

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    } else result.add(0, 0)
Почему не просто `add(0)`?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            result.add(0, nn % base)
Вместо добавления в начало списка лучше добавлять в конец, а потом развернуть итоговый список при помощи `reversed()`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else result += "${number[i]}"
Лучше `toString()`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result: String = ""
* Система типов Котлина выведет тип переменной автоматически
* Для сборки строки из составных частей лучше использовать список строк или `StringBuilder`

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (number[i] >= 10) result += (number[i] + 87).toChar()
Что такое 87? Почему не 42?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += digits[i] * Math.pow(base.toDouble(), (digits.size - 1 - i).toDouble()).toInt()
Напишите функцию `pow(Int, Int): Int`, работающую в целых числах, и воспользуйтесь ей везде, где вы не совсем корректно используете работу в числах с плавающей запятой для возведения в степень

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list = listOf()
Почему разделено определение и объявление переменной?

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else list += ((string[i]).toInt() - 87)
Магические константы

2016-10-27 12:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val string = str
Зачем вам эта переменная?

2016-11-18 13:32 UTC, ice-phoenix commented
Ваш код для `russian()` не завершается. Просьба проверить его локально на различных входных данных.

2016-11-18 14:11 UTC, ice-phoenix requested changes

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +import lesson4.task1.abs
Зачем?

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (sAll > 0) {
Это условие можно сделать частью `when`

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {(rook1Danger || rook2Danger) ->
Этот `when` очень сильно переусложнен. Подумайте еще раз, какие простые логические условия соответствуют возврату из функции 1, 2 и 3.

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        else -> 0
Зачем?

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {((a >= b) && (a >= c)) -> {
Форматирование кода

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when { (min1 + min2 > max) ->
Эти два `when` можно объединить в один

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var nn: Int = n
* Система типов Котлина выведет тип переменной автоматически

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var count: Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun maxDivisor(n: Int): Int = n / minDivisor(n)
:+1:

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (gcdMN == 1)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return sqr(sqrN) >= m && sqr(sqrN) <= n
Зачем проверять вторую часть условия?

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (nn % x != n) x *= 10
Ап

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    (n..number - 1).forEach { i -> result /= 10 }
Нельзя ли заменить этот цикл на возведение в степень и деление?

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun squareList(list: List<Double>) = list.map { it * it }
Ап

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        var forElement: Double
Почему эта переменная объявлена здесь, а не в теле цикла?

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var minDivisor: Int
Почему эта переменная объявлена здесь, а не в теле цикла?

2016-11-18 14:11 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (part in parts) {
Если вам необходимо сделать разные вещи с разными элементами списка, зачем цикл???

2016-11-21 11:17 UTC, ice-phoenix requested changes

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (ten == 1) && (oneHundred != 11) -> "$age год"
Когда это условие может выполниться?

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val bishopDanger = ((kingX - kingY) == (bishopX - bishopY)) or ((bishopX - kingX) == (bishopY - kingY)) or (bishopX - kingX == -(bishopY - kingY))
`or -> ||`

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (a > d) || ((a < d) && (c > b)) -> -1
Это условие можно упростить

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = ((x1 == x2) or (y1 == y2) or (Math.abs(x1 - x2) == Math.abs(y1 - y2)))
`or -> ||`

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = (gcd(m, n) == 1)
Лишние скобки вокруг законченных выражений

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 0..n) {
Почему бы не оформить этот цикл как `while`?

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +import kotlin.comparisons.reverseOrder
Зачем?

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Зачем данная проверка?

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        var minDivisor: Int
Почему вы разделили определение и объявление переменной?

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> + * И если поменять toChar на toString, то всё сломается :'(
Вообще-то, переменные типа `Char` тоже можно вычитать и складывать, например `'a' - 10 + i`

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if ((base != 0) && (n != 0)) {
`0^0 == 1`???

2016-11-21 11:17 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (str[i] in '0'..'9') list += ((str[i]).toInt() - 48)
См. замечание выше про работу с `Char`

2016-11-23 10:50 UTC, mglukhikh commented
recheck all

2016-11-25 10:19 UTC, ice-phoenix commented
recheck all

2016-11-25 11:23 UTC, ice-phoenix requested changes
Поговорите с преподавателем на занятиях о тех замечаниях, которые я указал. Плюс, обратите внимание, что не исправлены некоторые замечания из более ранних уроков.

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            (sAll > s1) and (sAll <= s12) -> (t1 + (sAll - s1) / v2)
* Первую часть этой проверки можно не делать, вы ее уже проверили строчкой выше
* `and` ==> `&&`

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (min1 + min2 > max) && (cosMax > 0.0) -> 0
Первую часть лучше проверить один раз в самом начале `when`, чем проверять ее снова и снова

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (n % i != 0) i--
Ненужный более код надо не комментировать, а удалять

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val piX = x % (Math.PI * 2)
Зачем два раза считать одно и то же?

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (number < n) {
Почему бы это не сделать более подходящим циклом `while`?

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +//import lesson3.task1.minDivisor
Зачем?

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val newList = v.map { it * it }
Можно обойтись без этой вспомогательной переменной, а если уж с ней, то имя у нее должно быть нормальное, а не ничего не говорящее `newList`

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        var result = 0.0
Подобные конструкции (когда в ветке then вы выходите из функции из-за неправильных входных данных или прочей ошибки) обычно оформляют как
```
if (cond) return ...
var result = 0.0
...
```
Выносить вторую часть в ветку else не имеет особого смысла и только усложняет понимание кода.

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val minDivisor = lesson3.task1.minDivisor(nn)
Зачем указывать путь полностью?

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0..number.size - 1) {
Если вам не нужен индекс в явном виде, лучше использовать цикл в foreach-стиле

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else result += "${number[i]}"
Лучше через `toString()`

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    } else if (n != 0) return result + 1
Зачем здесь возвращать через `result + 1`, если можно сразу вернуть 1?

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    else return result
А здесь можно сразу вернуть 0

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result++
Эту переменную можно просто завести здесь и проинициализировать единицей

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += digits[i] * pow((digits.size - 1 - i), base)
Лишние скобки вокруг законченных выражений

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0..str.length - 1)
Цикл в foreach-стиле

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else list += ((str[i]).toInt() - 87)
Лучше сделать эти преобразования через операции над `Char`, а не через `toInt()` и магические константы

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +else -> "десять"
Старый код нужно удалять, а не комментировать. Он все равно сохраняется в системе контроля версий, и вы сможете его вернуть при необходимости.

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (n == 3) n += 100
Если вам нужно сделать разные действия над разными элементами списка, зачем цикл???

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (formatStringToDateStrToDigit(str)) {
Зачем делать два набора практически одинаковых действий в двух функциях, при этом никак не переиспользуя результаты, я не понимаю. Пожалуйста, поговорите с вашим преподавателем на занятиях о том, как следует переделать эти функции.

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (formatStringToDateDigitToStr(digital)) {
См. замечания выше и поговорите с преподавателем и про эти функции тоже

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +}
Вместо всей этой функции можно просто сделать `phone.any / phone.all` с правильным условием

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var f = 0
Какой смысл несет эта переменная?

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return result
Весь цикл выше можно заменить на `phone.map / phone.filter` (смотря что вы пытаетесь здесь сделать)

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +}
Всю эту функцию можно заменить либо на проверку на основе регулярного выражения, либо (опять же), на `phone.all / phone.any`

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +}
Можно вообще обойтись без этой функции, так как строки и так можно сравнивать

2016-11-25 11:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } else return -1
Поговорите, пожалуйста, с преподавателем на занятиях о том, как следует правильно сделать эту функцию

2016-12-18 20:42 UTC, ice-phoenix commented
recheck all

2016-12-18 22:50 UTC, ice-phoenix commented
С учетом замечаний и статистики решения задач у вас "Удовлетворительно" автоматом.

2016-12-19 08:46 UTC, ice-phoenix commented
recheck all

2016-12-19 08:51 UTC, ice-phoenix commented
Даже с учетом дополнительно решенных задач все равно получается только "Удовлетворительно" автоматом.

2016-12-19 22:14 UTC, Gukavina commented
У меня есть ещё возможность исправить ошибки на этой неделе и получить оценку выше? Или уже не выйдет?

2016-12-20 07:59 UTC, ice-phoenix commented
На итоговое "Хорошо" необходимо было решить хотя бы одну задачку из 7.2. Кроме того, у нас есть некоторые вопросы к тому, как вы решили другие задачи. Попробуйте поговорить с преподавателем на упражнениях, но скорее всего ничего выше "Удовлетворительно" автоматом у вас не получится. Зато всегда можно прийти на экзамен и сдать на "Отлично"!

2017-07-26 18:24 UTC, closed without merging