Исправлен lesson1.task1 номер thirdDigit; Полностью решен lesson2
Kotlin-Polytech/KotlinAsFirst2016 pull request #77
Opened 2016-09-17 02:51 UTC by AllTimeLow

2016-09-17 11:26 UTC, mglukhikh commented
recheck all

2016-09-17 11:43 UTC, mglukhikh commented
recheck assignment

2016-09-17 11:53 UTC, mglukhikh commented
Код не компилируется. Пожалуйста, запускайте тесты на локальном компьютере перед отправкой PR.

2016-09-18 11:09 UTC, mglukhikh commented
recheck all

2016-09-19 01:49 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = number.toString().reversed().toInt()
Эту задачу тоже правильнее было бы решить без использования строк.

2016-09-19 01:50 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (age%10==1) return age.toString()+" год"
В этой ситуации для формирования строки удобнее воспользоваться конструкцией `"$age год"`.

2016-09-19 01:52 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +            val road: Double=(t1*v1+t2*v2+t3*v3)/2
Для улучшения читаемости кода лучше было бы завести переменные для длины каждого участка.

2016-09-19 01:53 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX==rookX1 || kingY==rookY1) && (kingX==rookX2 || kingY==rookY2)) return 3
Для повышения читаемости кода лучше вынести условия угрозы каждой из ладей королю в отдельные переменные.

2016-09-19 01:54 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((kingX==rookX || kingY==rookY) && (abs(bishopX-kingX)==abs(bishopY-kingY))) return 3
Для повышения читаемости кода лучше вынести условия угрозы ладьи и слона королю в отдельные переменные.

2016-09-19 01:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +        val cosinus: Double= (sqr(abc[0])+ sqr(abc[1])- sqr(abc[2]))/(2*abc[0]*abc[1])
Делить на `2ab` не обязательно, так как знак от этого не поменяется.

2016-09-19 01:58 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    else return false
Конструкция вида `if (x) return true else return false` эквивалентна `return x`, поскольку `x` уже логическое выражение. Кроме того, с учётом этого замечания, функция легко может быть реализована как однострочная.
Эти замечания справедливы для всех функций в этом файле.

2016-09-19 01:59 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if ((a<=r && b<=s) || (b<=r && a<=s) || (a<=r && c<=s) || (c<=r && a<=s) || (b<=r && c<=s) || (c<=r && b<=s)) return true
Условие было бы проще, если сначала найти две наибольшие стороны кирпича.

2016-09-19 02:01 UTC, maximpetrov requested changes
Три функции не проходят тесты + замечания по стилю.

2016-09-19 02:03 UTC, maximpetrov commented
Вернее тесты не проходят две функции

2016-10-12 09:28 UTC, mglukhikh commented
Напоминаю автору PR, что следует исправить написанные здесь замечания -- и продолжить работу над задачами 3-го урока.

2016-10-27 15:55 UTC, maximpetrov requested changes
Кроме этих замечаний, некоторые тесты не проходят.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +@file:Suppress("UNUSED_PARAMETER", "UNREACHABLE_CODE")
Не нужно отключать предупреждение `"UNREACHABLE_CODE"`, лучше исправьте те места, где оно показывается.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((a && b)) return 3
Зачем этот `if`?

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val a=((kingX==rookX1)||(kingY==rookY1))
Дайте переменным осмысленные имена

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val a = (kingX == rookX || kingY == rookY)
Дайте переменным осмысленные имена

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    else return fib(n-2) + fib(n-1)
Такая рекурсивная реализация ведёт к экспоненциальному росту числа вызовов функции `fib` (посчитайте, сколько раз вызовется эта фукнция для `n` равного 50). Переделайте так, чтобы этого не было.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if (NOD>number) {
В реализации алгоритма ошибка, что видно по тестам, которые не проходят.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n/2)
Можно установить верхнюю границу перебора меньше, чем `n/2`.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n/2 downTo 1)
Можно установить нижнюю границу перебора больше, чем `1`.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean {
Эта функция почти полностью дублирует код функции `lcm`. Вынесите нахождение НОД в отдельную функцию.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var i=ceil(sqrt(min.toDouble()))
`ceil` возвращает `double`, переведите его в `int`.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    val min=min(m,n)
По заданию `m <= n`

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (pow(x,(1+i*2.0)) / factorial(1+i*2) > eps) {
Очередной член последовательности лучше вычислить один раз, а не вычислять два раза на каждой итерации. А ещё лучше не считать его каждый раз заново, а вычислять из предыдущего.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (pow(x,(i*2.0)) / factorial(i*2) > eps) {
См. замечание для `sin`.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var abc = 0
Дайте переменной осмысленное название

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    return n.toString() == n.toString().reversed()
Решите без использования строк.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var last = num%10
Можно здесь сразу отрезать от числа последнюю цифру.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var qwe = 0
Дайте переменной осмысленное имя

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var qwe = 0
Дайте переменной осмысленное имя

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        val currentLength = qwe + digitNumber(a)
Зачем Вам эта переменная?

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        val currentLength = qwe + digitNumber(fib)
Зачем Вам эта переменная?

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    list.forEachIndexed { i, d -> list[i] -= c }
Здесь можно было бы обойтись и обычным `for`.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        val min = lesson3.task1.minDivisor(num)
Находить минимальный делитель таким образом не оптимально: Вы каждый раз будете проходить по всем уже рассмотренным ранее делителям.

2016-10-27 15:55 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    return list.sorted()
Зачем сортировать, если и так вы и итак ищете от минимального к максимальному?

2016-11-23 10:37 UTC, mglukhikh commented
Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.

2016-12-19 15:35 UTC, maximpetrov commented
recheck all

2016-12-20 10:06 UTC, maximpetrov commented
recheck all

2016-12-20 16:36 UTC, closed without merging