Did the second lesson
Kotlin-Polytech/KotlinAsFirst2016 pull request #79
Opened 2016-09-17 15:22 UTC by grafovdenis

2016-09-17 18:51 UTC, mglukhikh commented
Две задачи из второго урока решены неверно, смотрите комментарии бота

2016-09-17 18:53 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return result
Здесь и в следующей задаче можно избежать повторной проверки одних и тех же условий. Подумайте, как это можно сделать

2016-09-17 18:54 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (s <= s1){
Перед фигурной скобкой обычно ставится пробел. Вы обычно это делаете, но в некоторых местах забываете. На всякий случай: в IDEA есть автоформатирование. Выделить код и нажать Ctrl+Alt+L

2016-09-17 18:56 UTC, mglukhikh commented on test/lesson1/task1/Tests.kt
> +class   Tests {
Старайтесь избегать подобных случайных изменений. Перед выполнением коммита, в окне Local Changes можно просмотреть все сделанные вами изменения и откатить (отменить) подобные случайности.

2016-09-17 18:57 UTC, mglukhikh commented on test/lesson2/task1/Tests.kt
> +        assertEquals("121 год", ageDescription(121))
Очень правильно, что вы дополняете имеющиеся тесты своими случаями.

2016-09-17 18:58 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        else if ((c > a && c > b && sqr(c) > sqr (a) + sqr (b)) || (a > c && a > b && sqr(a) > sqr (c) + sqr (b)) || (b > a && b > c && sqr(b) > sqr (a) + sqr (c))){
Это условие можно немного упростить

2016-09-17 19:01 UTC, mglukhikh commented
Также посмотрите на решения whichRookThreatens, rookOrBishopThreatens и triangleKind, их можно несколько упростить. Всё остальное верно.

2016-09-18 12:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    if (condition1) {
Я бы использовал более говорящие названия, например, `threatFrom1`, `threatFrom2`.

2016-09-18 12:39 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +        } else if ((c > a && c > b && sqr(c) > sqr(a) + sqr(b)) || (a > c && a > b && sqr(a) > sqr(c) + sqr(b)) || (b > a && b > c && sqr(b) > sqr(a) + sqr(c))) {
Это условие по-прежнему можно упростить, если сообразите как -- буду рад.

2016-09-18 12:42 UTC, mglukhikh commented
И остаётся неработающий `brickPasses`.

2016-09-26 16:15 UTC, grafovdenis commented
Михаил Игоревич, тесты вроде как проходят, ошибки исправлены, с этим уроком всё?

2016-09-27 10:42 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    //sorting
На будущее: не называйте переменные с большой буквы. С сортировкой идея была правильная, но реализовать её можно проще. Тоже оставлю вам на подумать.

2016-09-27 10:43 UTC, mglukhikh commented
Да, второй урок считаем закрытым. Посмотрите, однако, замечания к triangleKind -- для саморазвития.

2016-09-27 10:44 UTC, mglukhikh commented on src/lesson2/task2/Logical.kt
> +    if (a + b == c + d) return true
Лучше просто: `return a + b == c + d`.

2016-09-27 10:49 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        val doubleK = k + 0.0
Здесь лучше написать аккуратнее. Во-первых, знак слагаемого (плюс или минус) можно определить вообще без возведения в степень. Во-вторых, для возведения в целую степень лучше написать свою функцию pow(x: Double, y: Int), это точнее. И главное: подумайте, как ведёт себя ваше решение, если `x` достаточно велик (20, 100, 1000, 10000). Как меняется необходимое для расчёта число слагаемых? Что происходит с погрешностью вычислений? Можно ли что-нибудь сделать с этими проблемами? Поправьте своё решение и добавьте тест для большого значения `x`, сравнивая результат работы вашей функции с результатом `Math.sin(x)`. Для косинуса -- те же замечания (достаточно поправить одну из функций, в общем).

2016-09-27 10:50 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +}
Вы забыли про случай с k = 0 (см. результат работы бота).

2016-09-27 10:52 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..max) {
А почему именно до максимума? Нельзя ли как-нибудь уменьшить эту границу?

2016-09-27 10:53 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        else k++
Решить эту задачу можно гораздо более эффективно. Почитайте про известные алгоритмы расчёта наибольшего общего делителя и наименьшего общего кратного.

2016-09-27 10:55 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int {
Здесь такой вопрос. Пусть n = 10. Сколько раз вызовется функция fib в ходе расчёта числа Фибоначчи? Что будет, если n = 15 или n = 20?

2016-09-27 10:55 UTC, mglukhikh commented
Написал замечаний по третьему уроку

2016-09-27 12:11 UTC, grafovdenis commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int {
Понятное дело, что количество вызовов будет большим, и быстродействие при больших n будет даже медленнее, чем при создании массива a и с последующим вызовом a[n].
Но вы сказали, что можно придумать рекурсивное решение хотя бы одной задачи :)

2016-09-27 12:20 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun fib(n: Int): Int {
Уговорили :). Хорошо, что вы это понимаете. Могу задать сложный вопрос на подумать -- а можно ли предложить усовершенствование рекурсивного решения, которое не имело бы этого недостатка?

2016-10-03 19:59 UTC, mglukhikh requested changes
Остались проблемы с точностью расчётов для синуса и избыточная верхняя граница в `squareBetweenExists`. В остальном всё хорошо.

2016-10-03 19:59 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    } else return -1
Ага, так в достаточной степени кратко.

2016-10-03 19:59 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +     * Не подскажете, с чем это связано?
Это очень странно, должно бы работать. Надо смотреть. Напишите мне в комментарии, как в точности выглядел неработающий код

2016-10-03 19:59 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    for (k in 0..n) {
Да, насчёт нуля вы правы. Но всё же, так как n * n существенно больше n, верхняя граница интервала явно избыточна. Подумайте, как тут можно сэкономить

2016-10-03 19:59 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +            result += pow(x, (2 * i + 1)) / factorial(2 * i + 1)
Рефакторинг в целом правильный, но вы не решили основной проблемы -- с точностью вычислений. Подумайте про это ещё раз, вспомните про известные свойства синуса.

2016-10-04 12:24 UTC, grafovdenis commented on src/lesson3/task1/Loop.kt
> +     * Не подскажете, с чем это связано?
```
fun sin(x: Double, eps: Double): Double {
    var i = 1
    var result = x
    var memberOfSequence = pow(x, (2 * i + 1)) / factorial(i * 2 + 1)
    while (memberOfSequence > eps) {
        if (i % 2 == 1)
            result -= memberOfSequence
        else
            result += memberOfSequence
        i++
    }
    return result
}
```

2016-10-04 13:58 UTC, grafovdenis commented on src/lesson3/task1/Loop.kt
> +     * Не подскажете, с чем это связано?
Пробовал ещё так, лучше не стало

```
fun fact(n: Int): Int {
    var result = 1
    for (i in 1..n) {
        result *= i
    }
    return result
}
```

```
fun sin(x: Double, eps: Double): Double {
    var i = 1
    var result = x
    var numerator = pow(x, (2 * i + 1))
    var divider = fact(i * 2 + 1)
    while (numerator / divider > eps) {
        if (i % 2 == 1)
            result -= numerator / divider
        else
            result += numerator / divider
        i++
    }
    return result
}
```

2016-10-04 20:03 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +     * Не подскажете, с чем это связано?
У вас `memberOfSequence`, `numerator`, `divider` зависят от `i`, а `i` меняется внутри цикла. Поэтому, и переменные эти нужно определять внутри цикла (лучше всего первым оператором тела) -- иначе вы их посчитаете один раз при `i = 1`, и больше они не изменятся.

2016-10-05 12:55 UTC, grafovdenis commented on src/lesson3/task1/Loop.kt
> +     * Не подскажете, с чем это связано?
Понял, спасибо.

2016-10-07 07:42 UTC, mglukhikh requested changes
Просмотрел последние четыре коммита, написал замечаний по ним. Напоминаю также нерешённые предыдущие проблемы: точность расчётов для синуса; более эффективное решение задачи про наименьшее общее кратное (забыл про неё в прошлом ревью). Пожалуйста, исправьте имеющиеся замечания, прежде чем решать следующие задачи (иначе мы рискуем в замечаниях утонуть).

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    while (k * k <= n) {
Да, согласен. Можно было ещё в качестве начального значения взять корень из m.

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +import org.jetbrains.annotations.Mutable
Зачем вам эта аннотация Mutable? Старайтесь просматривать список изменений перед коммитом (окно Version Control > вкладка Local Changes > Ctrl+D на изменённом файле) и "вычищать" такие случайные изменения.

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..v.size - 1) {
Лучше напрямую перебирать элементы списка, а не индексы: `for (element in v) { ... }`. Всё дело в том, что (как справедливо упоминал Марат Халимович на лекции), получение элемента списка по индексу может не всегда работать быстро. Для линейного списка эта операция требует **ещё раз** перебрать весь список с начала и до этого индекса. Ну и кроме того, прямой перебор элементов списка банально короче.

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    var sum = 0.0
Здесь можно просто `= list.sum()`.

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun center(list: MutableList<Double>): MutableList<Double> =
Условие этой задачи предполагает изменение переданного вам списка `list`, а не создание нового. Именно поэтому параметр имеет тип `MutableList`, а не просто `List`. Об этом же говорит вам бот в своём сообщении

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..b.size - 1) {
Лучше написать всё в одном цикле, и не вводя промежуточный список `sum`.

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +            k = 2
Не слишком эффективно, найдя очередной делитель, опять возвращаться к началу. Подумайте, как это сделать лучше.

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    //костыль :(
А зачем он? Что мешает сразу посчитать `mean(list)`, запомнить его и использовать?

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String {
У вас уже есть функция `factorize`, не нужно её здесь переписывать. Всё, что нужно -- это превратить полученный из неё список чисел в строку в нужном формате.

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        power -= 1
Лучше `power--`.

2016-10-07 07:42 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +    for (i in 0..list.size - 1) {
Подумайте, нельзя ли изменить исходный список за один проход, не создавая вспомогательный список и не считая каждый раз сумму предыдущих элементов.

2016-10-10 19:55 UTC, mglukhikh reviewed
Хорошо, большую часть замечаний вы поправили, остались замечания к эффективности реализации `factorize` и несколько костыльной реализации `accumulate`. Я закрою этот PR, оставшиеся замечания поправьте, пожалуйста, в следующем.

2016-10-10 19:55 UTC, mglukhikh commented on src/lesson4/task1/List.kt
> +        val el = element
Эта промежуточная переменная не нужна

2016-10-10 19:56 UTC, mglukhikh commented
Рекомендую вам также попробовать решить последнюю задачу из 4-го урока, думаю, вы в состоянии справиться с ней.

2016-10-10 19:56 UTC, closed without merging