a few more tasks solve
Kotlin-Polytech/KotlinAsFirst2016 pull request #82
Opened 2016-09-18 17:16 UTC by JakeIlan

2016-09-18 17:59 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    return false
- Выражение в условии `if` уже имеет тип `Boolean`, поэтому `if` в этом случае можно опустить. Т.е. `if (x) return true else return false` то же самое, что `return x`
- С учётом вышесказанного функцию легко сделать однострочной.
- Вокруг арифметических и логических операторов принято ставить пробелы. Используйте автоматическое форматирование кода IntelliJ IDEA.

2016-09-18 18:00 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +}
См. замечания к `isNumberHappy`.

2016-09-18 18:03 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    return false
См. замечания к `isNumberHappy`.

2016-09-18 18:04 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +}
- Условие могло бы выглядеть проще, если сначала определить две наибольшие стороны кирпича.
- См. замечания к `isNumberHappy`.

2016-09-18 18:04 UTC, maximpetrov requested changes

2016-09-29 17:32 UTC, maximpetrov requested changes
Не забудьте исправить предыдущие замечания.

2016-09-29 17:32 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (cond) {
Есть более оптимальный алгоритм нахождения НОК.

2016-09-29 17:32 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Не обязательно перебирать до `n`.

2016-09-29 17:32 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var minDiv = 2
Зачем Вы завели переменную `minDiv`, чем Вас не устроило `i`?

2016-09-29 17:32 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var maxDiv = n-1
Зачем Вы завели переменную maxDiv, чем Вас не устроило i?

2016-09-29 17:32 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n downTo 1) {
Не обязательно перебирать до 1.

2016-11-10 23:27 UTC, maximpetrov requested changes

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (cond) {
Замечание всё ещё в силе

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var result:Int
Эту переменную можно внести внутрь цикла и сделать `val`.

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var maxDiv = n-1
Замечание ещё в силе

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n downTo 1) {
Замечание ещё в силе

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    if (b > 0) for (i in 1..b) basement *= a
Зачем здесь этот `if`? Если `b` будет отрицательным, тело цикла просто не выполнится ни одного раза.

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    while (number > 0) {
Можно обойтись без подсчёта числа цифр в числе

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        number += "$fibNumber"
Во-первых, собирать `String` из кусков не эффективно, потому что это неизменяемый тип и при каждом при добавлении строки создаётся новая строка. Во-вторых, зачем Вам хранить всю строку в памяти?

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +fun intPower(a: Int, b: Int): Int {
Зачем Вы скопировали сюда эту функцию из третьего урока? Можно её просто оттуда импортировать и использовать в этом уроке.

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (a.size != 0) {
Эта проверка лишняя, если размер будет равен 0, то ни одной итерации цикла не будет выполнено.

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        k ++
Здесь эффективнее было бы не пересчитывать каждый раз `pow(x, k)`, а накапливать этот множитель.

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var prevSum = 0.0
Здесь можно обойтись без промежуточных переменных

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        result += intPower(base, digits.size - (i + 1)) * digits[i]
Здесь, с помощью арифметических преобразований вычисляемого выражения, можно избежать необходимости вычислять вес очередного разряда.

2016-11-10 23:27 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +fun russian(n: Int): String {
Во-первых, в большинстве Ваших цепочек `if` в этой функции лучше использовать `if ... else if ...`, а ещё лучше использовать вместо них `when`. Во-вторых, Вы можете использовать List или Map для хранения строк, тогда Ваш код будет немного компактнее.

2016-11-20 13:45 UTC, maximpetrov requested changes

2016-11-20 13:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +            minDiv = i
Можно возвращать делитель сразу при его нахождении

2016-11-20 13:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n - 1 downTo Math.sqrt(n.toDouble()).toInt()) {
Во-первых, см. замечание с `minDivisor`, во-вторых, с нижней границей перебора согласен, а верхнюю (`n - 1`) можно ещё уменьшить

2016-11-20 13:45 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
>          number += "$fibNumber"
Замечание про собирание строки всё ещё в силе

2016-11-20 13:45 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        for (j in i - 1 downTo 0) {
Подумайте ещё, Вы из решения с линейной сложностью сделали решение с квадратичной сложностью.

2016-11-20 13:45 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        val digit = digitsOfn % 10
Если эту переменную сделать локальной, то она не будет сохраняться между итерациями.

2016-11-23 08:17 UTC, maximpetrov requested changes

2016-11-23 08:17 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    return 2
Почему 2?

2016-11-23 08:17 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    return n - 1
Почему `n - 1`

2016-11-23 08:17 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in n - Math.sqrt(n.toDouble()).toInt() downTo Math.sqrt(n.toDouble()).toInt()) {
Верхняя граница всё равно неправильная.

2016-11-23 11:10 UTC, maximpetrov requested changes

2016-11-23 11:10 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    else resPhone.filter { it in "+()0123456789" }
Эта строка не имеет смысла, потому что `filter` не меняет исходную строку и не выбросит никакого исключения, если найдёт другие символы.

2016-11-23 11:10 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (phone.contains(Regex("""(\+\d\)?(\(\d+\)?(\d+)))"""))) return resPhone
Вы запутались в скобках в этом регулярном выражении. Если Вы их поправите, то только это выражение нужно будет для проверки формата. Единственное, о чём Вы забыли: убрать предварительно пробелы и тире.

2016-11-23 11:33 UTC, mglukhikh commented
recheck all

2016-11-25 09:23 UTC, maximpetrov requested changes

2016-11-25 09:23 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    else phone.filter { it in "+0123456789" }
Эта строка всё также ничего не делает

2016-11-25 09:23 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (phone.contains(Regex("""(\+\d\)?(\(\d+\)?(\d+)))"""))) return phone
Здесь всё ещё ошибка с расстановкой скобок.

2016-11-25 09:23 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +val months = listOf("января", "ферваля", "марта", "апреля", "мая", "июня",
Исправьте уже здесь все опечатки

2016-11-25 09:23 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +            if (points[i].distance(points[j]) > max){
Сохраните вычисленное расстояние в переменную, чтобы два раза не пересчитывать его

2016-11-25 09:23 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +                result = Segment(begin, end)
Нет большого смысла заводить эти две переменные

2016-11-25 09:23 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    if (points.size < 2) throw IllegalArgumentException()
Это стоило бы проверить в самом начале

2016-11-25 09:23 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +    val center = Point(Math.abs((diameter.begin.x - diameter.end.x) / 2),
Неправильно вычисляете центр, поэтому и тесты не проходят.

2016-11-26 07:49 UTC, maximpetrov requested changes

2016-11-26 07:49 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (phone.contains(Regex("""(\+\d)?(\(\d+\))?(\d+)"""))) return phone
Количество цифр в префиксе не фиксировано и может быть больше 1. Кроме того, Вам нужно проверить строку на полное совпадение (`match`).

2016-11-26 07:49 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (phone.contains(Regex("""[^0-9-+()\s]"""))) return ""
Эта проверка Вам не нужна, Вы же проверяете весь формат целиком в следующей строке. Вместо этой проверки нужно убрать из строки пробелы и тире, так как они могут быть в любом месте и Вы не учитываете их в регулярном выражении.

2016-12-07 15:23 UTC, maximpetrov commented
recheck all

2016-12-07 16:31 UTC, maximpetrov requested changes
Обратите внимание, что у Вас много функций не проходят тесты.

2016-12-07 16:31 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +    if (phone1.matches(Regex("""(^(\+)\d+)?(\d+)"""))) return phone1
Вам всего лишь нужно было исправить одно место в регулярном выражении. Зачем Вы всё переписали так, что формат теперь проверяется лишь отчасти?

2016-12-07 16:31 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +import lesson4.task1.abs
Зачем этот импорт?

2016-12-07 16:31 UTC, maximpetrov commented on src/lesson6/task1/Geometry.kt
> +fun lineBySegment(s: Segment): Line {
Одну из двух функций (`lineBySegment` и `lineByPoints`) можно реализовать через другую.

2016-12-19 14:38 UTC, maximpetrov commented
recheck all

2017-07-26 18:24 UTC, closed without merging