Hiraev Malik 13531/2 Lesson3
Kotlin-Polytech/KotlinAsFirst2016 pull request #83
Opened 2016-09-19 10:07 UTC by MalikPiter

2016-09-19 10:09 UTC, MalikPiter commented
recheck all

2016-09-19 10:10 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    var a: Double =initial.toDouble()
* Система типов Котлина выведет тип переменной автоматически

2016-09-19 10:11 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return a}
Это не является принятым способом форматирования кода на Kotlin

2016-09-19 10:11 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return number%10*100+number%100/10*10+number/100
Выражения, соответствующие отдельным цифрам, лучше вынести в переменные

2016-09-19 10:12 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val firstCondition = kingX==rookX1||kingY==rookY1
Переменным лучше давать осмысленные имена, соответствующие их значению в коде. В данном случае, например, переменную можно назвать как `firstRookThreatens`.

2016-09-19 10:13 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val firstCondition = abs(kingX-bishopX) == abs(bishopY-kingY)
См. выше

2016-09-19 10:13 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val a1 = max(max(a, b), c)
Все это проще сделать, отсортировав список из сторон треугольника

2016-09-19 10:14 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val newA = min(min(a,b),c)
См. выше про сортировку

2016-09-19 10:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for(i in 2..n) {
Нет ли какого-нибудь более сильного ограничения сверху на максимальный размер минимального делителя, не равного `n`, чем `n`?

2016-09-19 10:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for(i in 1..newN+1){
Нельзя ли найти более строгие границы для интервала перебора, чем `1 ... sqrt(n)`

2016-09-19 10:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(newN%10!==(newN/10)%10) return true
`!=` и `!==` --- это разные операторы, использующиеся в разных случаях; несмотря на то, что в данном конкретном случае особой разницы между ними нет, здесь (и много где еще по вашему коду) лучше использовать `!=`

2016-09-19 10:22 UTC, ice-phoenix requested changes
Просьба отформатировать код при помощи IntelliJ IDEA и в дальнейшем стараться придерживаться такого же стиля

2016-09-19 10:59 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    val a1 = max(max(a, b), c)
Строго говоря, на данный момент студенты ещё не знают, что такое список, это четвёртый урок.

2016-09-21 11:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for(i in n-1 downTo 1){
Почему в `minDivisor` и `maxDivisor` проверяются разные диапазоны делителей?

2016-09-21 11:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int) = if(nod(m,n)==1) true else false
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-21 11:34 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Может ли `sqrI` выйти из диапазона `[m..n]`?

2016-09-21 11:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isPalindrome(n: Int) = if(revert(n)==n) true else false
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-21 11:36 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (newN/10==0) break
Зачем проверять `newN/10 == 0` два раза?

2016-09-21 11:36 UTC, ice-phoenix requested changes

2016-09-21 13:05 UTC, MalikPiter commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Не может. Я же указал это в условии
`if(m<=sqrI && n>=sqrI) return true`

2016-09-21 13:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Вопрос несколько в другом. Если `i in (sqrt(m), sqrt(n))`, то может ли `i^2 ∉ (m,n)`?

2016-09-21 14:02 UTC, MalikPiter commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Нет. `i^2` всегда будет лежать на интервале `(m,n)`

2016-09-21 14:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
В таком случае, вы видите, в чем проблема в вашем коде?

2016-09-21 14:08 UTC, MalikPiter commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Нужно так? `if(m<sqrI && n>sqrI) return true`

2016-09-21 14:10 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Давайте по другому, в каком случае данное условие не будет выполнено?

2016-09-21 14:14 UTC, MalikPiter commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Если i^2 меньше m или больше n

2016-09-21 14:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
> Нет. i^2 всегда будет лежать на интервале (m,n)
> Если i^2 меньше m или больше n
Вывод?

2016-09-21 15:13 UTC, Hiraev commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Я понял к чему вы, но я пока не нашел способ решить эту задачу иначе.

2016-09-21 15:22 UTC, MalikPiter commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Я пришел к такому варианту, но он не работает 
`fun squareBetweenExists(m: Int, n: Int): Boolean {`
    `for(i in m..n){`
`        if(sqrt(i.toDouble()%10)==0.0) return true`
`    }`
`return false`
`}`

2016-09-21 19:51 UTC, MalikPiter commented on src/lesson3/task1/Loop.kt
> +        if(m<=sqrI && n>=sqrI) return true
Исправил

2016-09-23 10:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(newM==newM*10/10) return true
Для чисел типа `Double` данная проверка не имеет смысла

2016-09-23 10:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val difference = newN.toInt()-newM.toInt()
Подумайте о том, как именно происходит округление `Double` при вызове `toInt()` и как это может повлиять на правильность работы вашего решения

2016-09-23 10:43 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var z = newX
Подумайте, при помощи каких тригонометрических формул можно привести входное значения в ограниченный диапазон

2016-09-23 10:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(newN%10!=(newN/10)%10) return true
Форматирование кода

2016-09-23 10:44 UTC, ice-phoenix requested changes

2016-09-28 09:58 UTC, MalikPiter commented on src/lesson3/task1/Loop.kt
> +    val difference = newN.toInt()-newM.toInt()
При вызове toInt() число всегда округляется в меньшую сторону, так как дробная часть просто отбрасывается

2016-09-28 17:10 UTC, MalikPiter commented
Что мне нужно справить?

2016-09-29 08:44 UTC, ice-phoenix commented
recheck all

2016-09-29 08:48 UTC, ice-phoenix commented
Прошу прощения, забыл вам отписаться. Все хорошо, все принимаем =)

2016-09-29 08:48 UTC, closed without merging