Lesson 2 tast 1
Kotlin-Polytech/KotlinAsFirst2016 pull request #87
Opened 2016-09-19 12:39 UTC by egor-abak

2016-09-19 15:04 UTC, ice-phoenix commented
Обратите внимание, что ваш код даже не собирается. Убедительная просьба проверять, что встроенные в проект тесты проходят, перед отправкой PR.

2016-09-29 18:16 UTC, ice-phoenix commented
Ваш код все еще не собирается

2016-10-12 09:36 UTC, mglukhikh commented
Автору PR: вы сильно отстаёте от графика. Вам следует исправить ошибку компиляции и перейти к решению задач 2-го и 3-го урока, в противном случае вы рискуете получить неудовлетворительную оценку за октябрь месяц.

2016-10-17 17:46 UTC, mglukhikh commented
recheck all

2016-10-17 17:48 UTC, mglukhikh commented
recheck all

2016-10-20 10:18 UTC, ice-phoenix requested changes
Исправляйте замечания

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = (hours * 3600 + minutes * 60 + seconds)
Скобки вокруг выражения здесь излишни

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun angleInRadian(grad: Int, min: Int, sec: Int): Double = (grad + min/60.0 + sec/3600.0)*Math.PI/180
Форматирование кода должно быть одинаковым везде. Либо отделяете штуки друг от друга пробелами, либо не отделяете. Попробуйте отформатировать код при помощи IntelliJ IDEA и в дальнейшем придерживайтесь такого же стиля.

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = sqrt(((x1-x2)*(x1-x2))+((y1-y2)*(y1-y2)))
Лишние скобки

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        (((initial+initial*percent/100.0)+(initial+initial*percent/100.0)*percent/100.0)+((initial+initial*percent/100.0)+(initial+initial*percent/100.0)*percent/100.0)*percent/100.0)
Все это выражение можно записать намного проще, если воспользоваться алгебраическими свойствами

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            (age % 10) == (1) -> ("$age год")
Очень много лишних скобок

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            (kingX == rookX2 && kingY == rookY1)-> 3
Лучше сперва посчитать в отдельные переменные, атакует ли какая-либо ладья короля, а потом уже делать по этим переменным `when`

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        if (b<c || d<a) -1 else
Данное выражение лучше оформить как `when`

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((((number % 100) / 10) + (number % 10)) == (number / 1000) + ((number) / 100) % 10)
* Выражение `if (cond) true else false` можно заменить на `cond`
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var numb = n
`number`

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        k++
Почему не просто `Math.min(...)` или `if`???

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        k++
Почитайте про более быстрые алгоритмы поиска НОК

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty() == true) return 0.0
* `return` можно вытащить перед `if`
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`
* `if (cond == true) ==> if (cond)`

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val averageEqual = list.sum() / list.size
Что будет, если список пустой?

2016-10-20 10:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        list[i] = secondList-averageEqual
Можно `list[i] = list[i] - average`

2016-10-28 09:47 UTC, ice-phoenix requested changes
4 урок вам **не будет засчитан**, так как вы не исправили достаточно серьезные замечания к предыдущим урокам

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        (((initial + initial * percent / 100.0) + (initial + initial * percent / 100.0) * percent / 100.0) + ((initial + initial * percent / 100.0) + (initial + initial * percent / 100.0) * percent /
Данное выражение можно очень сильно упростить, если воспользоваться тривиальными математическими законами

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var treatFromFirst = 0
* Почему эта переменная имеет тип `Int`,  а не `Boolean`?
* `threatFromFirst`

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
Этот `when` не будет работать так, как вы хотите. Вы должны сперва в переменные `threatFrom*` записать то, атакует ли та или иная ладья короля, а потом уже присваивать соответствующее значение результату в `when`.

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +when {
Форматирование кода

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((((number % 100) / 10) + (number % 10)) == (number / 1000) + ((number) / 100) % 10)
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var numb = n
Ап

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        k++
Ап

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        k++
Ап

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (list.isEmpty() == true) 0.0
Зачем `... == true` для переменной типа `Boolean`?

2016-10-28 09:47 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val averageEqual = list.sum() / list.size
Можно было просто воспользоваться функцией `mean(...)`

2016-11-22 18:15 UTC, ice-phoenix commented
recheck all

2016-11-22 18:16 UTC, ice-phoenix commented
recheck all

2016-11-23 11:22 UTC, mglukhikh commented
Вы довольно сильно отстаёте от графика. Вам следует продолжать решать задачи учебного проекта.

2016-12-18 21:46 UTC, ice-phoenix commented
recheck all

2016-12-18 22:00 UTC, ice-phoenix commented
В настоящее время у вас нет даже зачета по нашему курсу.

2016-12-19 10:44 UTC, ice-phoenix commented
Вы можете расслабиться до дополнительной сессии, Егор. Дедлайн уже прошел.

2017-02-10 15:39 UTC, ice-phoenix commented
recheck all

2017-07-26 18:24 UTC, closed without merging