Some tasks solved
Kotlin-Polytech/KotlinAsFirst2016 pull request #9
Opened 2016-09-07 10:33 UTC by DDRDmakar

2016-09-07 10:42 UTC, ice-phoenix commented
recheck assignment

2016-09-07 11:50 UTC, mglukhikh commented
recheck assignment

2016-09-07 11:53 UTC, mglukhikh commented
У вас файл Simple.kt содержит какой-то кусок кода на Java, который, естественно, не компилируется и проверить его из-за этого нельзя. Прошу исправить проблему

2016-09-07 18:07 UTC, DDRDmakar commented
Спасибо, попробую исправить.

2016-09-08 09:55 UTC, mglukhikh commented
Обратите внимание, что задача ageDescription решена с ошибками, некоторые тесты не проходят. Остальное, насколько я понимаю, правильно.

2016-09-09 22:50 UTC, maximpetrov commented
recheck assignment

2016-09-09 22:52 UTC, maximpetrov commented
recheck assignment

2016-09-11 22:52 UTC, gagarski commented
Тесты для `angleInRadian` проваливаются из-за недостаточной точности числа π. Вы можете использовать константу из класса `java.lang.Math` (см. часть 1 учебного пособия).

2016-09-12 11:07 UTC, mglukhikh commented
Задача ageDescription не всегда выдаёт верный ответ

2016-09-12 11:08 UTC, mglukhikh commented
Остальные (кроме angleInRadian и ageDescription) решения верные

2016-09-14 09:08 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +        package lesson1.task1
Отформатируйте код при помощи встроенной функции форматирования IntelliJ IDEA и в будущем постарайтесь придерживаться такого стиля кодирования.

2016-09-14 09:09 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        package lesson2.task1
Форматирование кода.

2016-09-14 09:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun squareSequenceDigit(n: Int): Int
Оцените, строку какого размера придется создать вашему коду в случае, если `n == 10^6`. Какой объем памяти потребуется для ее хранения, если считать, что хранение одного символа требует 1 байта?

Можно ли изменить ваш код так, чтобы не требовалось сохранять все элементы последовательности квадратов чисел в одну строку?

2016-09-14 11:02 UTC, ice-phoenix commented
recheck all

2016-09-14 14:32 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +	while ( i % m != 0 || i % n != 0 ) i ++
Для решения этой задачи рекомендуется воспользоваться известными алгоритмами нахождения LCM (см. интернет)

2016-09-14 14:34 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +	var current_number_line : String = "$n"
* Данная переменная может быть объявлена как `val`
* Тип переменной можно не указывать, система типов Котлина сама выведет нужный тип

2016-09-21 11:13 UTC, ice-phoenix commented
Просьба исправить все указанные выше замечания к форматированию кода.

2016-09-21 11:15 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        if ( last_digit == 0 || last_digit > 4 || ( age >= 10 && age <= 20 ) ) return "$age лет"
Данное выражение лучше оформить как `when`

2016-09-21 11:21 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (       ( kingX == rookX1 || kingY == rookY1 ) &&
Выражения, соответствующие фактам атаки короля той или иной фигурой, следует вынести в отдельные переменные.

2016-09-21 11:21 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        else if ( a <= c && c <= b && b <= d ) R = b - c
Данное выражение лучше оформить как `when`

2016-09-21 11:21 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ( s1 == s2 ) return true
Данное выражение лучше оформить как `return s1 == s2`

2016-09-21 11:22 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    (
Данное выражение лучше оформить как `return [if condition]`

2016-09-21 11:22 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ( Math.sqrt ( ( x2 - x1 ) * ( x2 - x1 ) + ( y2 - y1 ) * ( y2 - y1 ) ) + r1 <= r2 ) return true
Данное выражение лучше оформить как `return [if condition]`

2016-09-21 11:23 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +		( a <= r && b <= s ) || ( b <= r && a <= s ) ||
Данное выражение лучше оформить как `return [if condition]`

2016-09-21 11:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +	for (m in 2..n-1) {
Нет ли более точной оценки сверху для максимального возможного делителя `n`?

2016-09-21 11:25 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +	for (m in 2..n-1) {
Например, как в вашем предыдущем решении

2016-09-21 11:26 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +	while (i % m != 0 || i % n != 0) i++
Нет ли более быстрых алгоритмов поиска LCM?

2016-09-21 11:27 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +	for (i in 2..n) {
Каким числом ограничен максимально возможный делитель числа `n`, не равный `n`?

2016-09-21 11:28 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +	for (i in 0..current_number_line.length - 1) {
Можно ли данную задачу решить с помощью других функций данного раздела?

2016-09-21 11:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +	var stopka: String = ""
Не следует называть переменные транслитом

2016-09-21 11:29 UTC, ice-phoenix requested changes

2016-09-21 23:06 UTC, DDRDmakar commented
Сделал изменения, как вы просили, но бот вылетает по времени. Похоже, что при проверке isPrime() Эх

2016-09-21 23:21 UTC, gagarski commented
@DDRDmakar про `isPrime()` вы догадались верно, но непонятно, зачем вы вообще его изначально правили (это был пример). Теперь он работает дольше (да ещё и с ошибкой).

2016-09-22 19:44 UTC, DDRDmakar commented
Похоже, при проверке функции digitNumber() происходит переход чисел из signed в unsigned.
Функция digitNumber(-2147483647) находит 10 разрядов, как и требуется
А digitNumber(-2147483648) находит один разряд ( то есть, это число преобразуется в ноль ).

2016-09-22 20:01 UTC, DDRDmakar commented
А, всё, понял. Простите. Я его в положительное переводил.

2016-09-23 08:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if ( ( a.size != b.size ) || a.isEmpty() ) return 0.0
Проверка `a.isEmpty()` здесь излишняя

2016-09-23 08:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    else return ( list.sum().toDouble() / list.size.toDouble() )
Вызывать `toDouble()` здесь необязательно

2016-09-23 08:47 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for( i in 2..Math.abs( n/2 )) if ( n % i == 0 ) return false
Зачем `Math.abs(n / 2)`?

2016-09-23 08:48 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var prime_divisors_storage: MutableList <Int> = mutableListOf()
Лучше `var prime_divisors_storage = mutableListOf<Int>()`

2016-09-23 08:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            if (number_is_prime(i) && current_number % i == 0) {
Подумайте, как можно реализовать перебор делимости числа на различные `простые` делители более эффективным образом

2016-09-23 08:49 UTC, ice-phoenix requested changes

2016-09-23 19:13 UTC, DDRDmakar commented on src/lesson4/task1/List.kt
> +    for( i in 2..Math.abs( n/2 )) if ( n % i == 0 ) return false
Чтобы цикл запускался, когда аргумент отрицательный.

2016-09-26 09:07 UTC, ice-phoenix commented
recheck all

2016-09-26 10:16 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial * (1.0 + (percent / 100.0)) * (1.0 + (percent / 100.0)) * (1.0 + (percent / 100.0)) * 1.0
Повторяющиеся подвыражения лучше вынести в отдельные переменные

2016-09-26 10:17 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val last_digit = age % 10
Почему в отдельную переменную вынесли только `age % 10`, а `age % 100` оставили как есть?

2016-09-26 10:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val r1: Boolean = (kingX == rookX1 || kingY == rookY1)
* Система типов Котлина выведет тип переменной автоматически

2016-09-26 10:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val s1: Int = ((number - number % 1000) / 1000) + ((number % 1000 - number % 100) / 100)
* Система типов Котлина выведет тип переменной автоматически

2016-09-26 10:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        (a <= r && b <= s) || (b <= r && a <= s) ||
Лучше найти две минимальные стороны кирпича и все считать относительно них

2016-09-26 10:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val i_step: Int = i
Все это можно записать как `val i_step = if (m > n) m else n`

2016-09-26 10:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    while (i % m != 0 || i % n != 0) i += i_step
Можно ли найти НОК более эффективным способом?

2016-09-26 10:22 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    total = x
Можно ли, используя какие-либо тригонометрические соотношения, ограничить величину `x`, которую мы используем в разложении?

2016-09-26 10:22 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    total = 1.0
Можно ли, используя какие-либо тригонометрические соотношения, ограничить величину `x`, которую мы используем в разложении?

2016-09-26 10:22 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var reverted: Int
[Здесь и ранее] Лучше совмещать объявление и определение переменной

2016-09-26 10:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val current_number_line: String = Integer.toString ( n )
* Система типов Котлина выведет тип переменной автоматически

2016-09-26 10:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 0..current_number_line.length - 1) {
Можно ли проверять меньше элементов в строке для проверки на палиндром?

2016-09-26 10:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val ariphmetical_average : Double = list.sum() / list.size
Что будет, если список пуст?

2016-09-26 10:25 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String = factorize ( n ).toMutableList().joinToString ( "*", "", "", -1, "..." )
Зачем `toMutableList()`?

2016-09-26 10:25 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var digit_storage = mutableListOf <Int> ()
* Данная переменная может быть объявлена как `val`

2016-09-26 10:26 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return digit_storage
Лучше `digit_storage.reversed()`

2016-09-26 10:26 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val digit_storage = convert ( n, base )
Можно ли эту функцию реализовать с использование `convert`?

2016-09-26 10:26 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var target : Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-09-26 10:28 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var target : Int = 0
Можно ли эту функцию реализовать при помощи функции `decimal`?

2016-09-26 10:28 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val digit_1 : List <String>    = listOf ( "", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX" ) // 1 2 3 4 5 6 7 8 9
* Система типов Котлина выведет тип переменной автоматически

2016-09-26 10:28 UTC, ice-phoenix requested changes

2016-09-28 15:22 UTC, ice-phoenix requested changes

2016-09-28 15:22 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial.toDouble() * Math.pow ((1.0 + (percent / 100.0)), 3.0 )
Можно обойтись без вызова `toDouble` в выражении `initial.toDouble()`

2016-09-28 15:22 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for ( i in s_step .. m*n step s_step ) if ( i%m == 0 && i%n == 0 ) return i
Можно ли найти НОК без перебора?

2016-09-28 15:22 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +	if ( list.isEmpty() ) return list
Форматирование кода

2016-09-28 15:22 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val ariphmetical_average = list.sum() / list.size.toDouble()
Можно обойтись без вызова `toDouble()`

2016-09-28 15:41 UTC, ice-phoenix requested changes

2016-09-28 15:41 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        part = Math.pow(x, i.toDouble()) / factorial(i)
Подумайте, не будет ли для данной реализации проблемой работа с большими входными значениями

2016-09-28 15:41 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +	for ( element in str ) digit_storage.add ( element.toInt() )
Посмотрите, что делает метод `Char.toInt()`

2016-09-30 08:53 UTC, ice-phoenix commented
recheck all

2016-09-30 09:01 UTC, ice-phoenix requested changes

2016-09-30 09:01 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (Math.sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1)) + r1 <= r2)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-30 09:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun factorizeToString(n: Int): String = factorize(n).joinToString("*", "", "", -1, "...")
Параметры функции, которые вы не меняете по сравнению с параметрами по умолчанию, можно не указывать

2016-09-30 09:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (element in str) digit_storage.add((element - if ('0' <= element && element <= '9') '0' else 'a' - 10).toInt())
Операцию приведения символа к его цифровому представлению лучше вынести в отдельную локальную функцию

2016-10-06 13:38 UTC, ice-phoenix requested changes

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (half <= s1) return half / v1
Данное выражение лучше оформить как `when`

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in s_step..m * n step s_step) if (i % m == 0 && i % n == 0) return i
Нет ли более быстрых алгоритмов поиска НОК?

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        for (i in current_number / 2 downTo 2) {
Как себя будет вести ваш код в случае, если `n == 1`?

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (element in digit_storage) digit_line += if (element < 10) "$element" else "${('a' + element - 10).toChar()}"
Для сборки строки по частям лучше использовать `StringBuilder`

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    numeric_date += if(date_part_storage[0].length < 2 ) '0' + date_part_storage[0] else date_part_storage[0]
`StringBuilder`

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if(('0' > target[index] || target[index] > '9') && target[index] != ' ' && target[index] != '-' && target[index] != '+' && target[index] != '(' && target[index] != ')') return ""
* Лучше завести множество (`Set`) допустимых элементов строки и проверять очередной символ на вхождение / невхождение в это множество, чем делать это через кучу проверок `char != smth`
* `return ""` должен быть на новой строке

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            target = target.replace( target[index].toString(), "")
Лучше все делать в два отдельных этапа. Сперва проверить строку на валидность, а потом (если она валидная) убрать из нее все ненужные символы разом.

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    catch(e: NumberFormatException) {return -1}
Форматирование кода

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if(jumps.any{ ('0' > it || it > '9') && it != ' ' && it != '+' && it != '-' && it != '%'  } ) return -1
См. замечание к `flattenPhoneNumber`

2016-10-06 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        attempt_storage.add( jump_storage[i] + ' ' + jump_storage[i+1] )
Лучше завести `Map` из высоты в описание попыток. Это значительно упростит и дальнейший код.

2016-10-27 15:04 UTC, ice-phoenix requested changes

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = ((number % 10) * 100) + (((number % 100) - (number % 10))) + ((number - number % 100) / 100)
Лишние скобки лучше убрать для облегчения понимания выражения

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val last_digit = age % 10
Переменные в Котлине принято называть `camelCase`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    // String answer
Что означает этот комментарий?

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (last_digit == 0 || last_digit > 4 || (last_two >= 10 && last_two <= 20)) -> "$age лет"
Можно проще как `last_two in 10..20`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    // Double answer; s1; s2; s3; half
Устаревшие комментарии лучше удалять

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun queenThreatens(x1: Int, y1: Int, x2: Int, y2: Int): Boolean = (
Лишние скобки

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun circleInside(x1: Double, y1: Double, r1: Double, x2: Double, y2: Double, r2: Double): Boolean = (Math.sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1)) + r1 <= r2)
Длинные строчки принято разбивать на несколько более коротких

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +// 	return (
Устаревший комментарий

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var digits_amount = 0
`camelCase`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var f_prev = 1
`camelCase`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun gcb(m: Int, n: Int): Int = if(n == 0) m else gcb(n, m % n)
`gcd`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int = m / gcb(m, n) *  n
Лучше записать как `m * n / gcd(m, n)`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var parameter_n = n
`camelCase`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val current_number_line = Integer.toString(n)
Можно просто `n.toString()`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (current_number_line [i] != current_number_line [current_number_line.length - 1 - i]) return false
Форматирование кода

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +//	if (n == 0) return 0
Устаревший комментарий

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var last_sequence_element = ""
`camelCase`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    // val v1 : List <Double> = v.map {it * it}
?

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return Math.sqrt((v.map { it * it }).sum())
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val ariphmetical_average = list.sum() / list.size
Можно было воспользоваться функцией `mean`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        for (i in current_number / 2 downTo 2) {
Почему бы не перебирать делители от минимального к максимальному, убрав необходимость проверки на простоту?

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        "$this"
Лучше вернуть из `with` просто `this`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        for (element in digit_storage) append(if (element < 10) "$element" else "${('a' + element - 10).toChar()}")
Код, который делает из числа символ, лучше сделать отдельной функцией

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        current_digit = (element - if ('0' <= element && element <= '9') '0' else 'a' - 10).toInt()
Код, который делает из символа число, лучше сделать отдельной функцией

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        append(if (date_part_storage[0].length < 2) '0' + date_part_storage[0] else date_part_storage[0])
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/pad-start.html

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (1 > month_num || month_num > 12) return ""
`month_num !in 1..12`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    }
Вместо всего этого можно воспользоваться функцией `any{ ... } / all{ ... }`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        for (element in jump_storage) if (element != "-" && element != "%") lucky_jump_storage.add(element.toInt())
Все это можно выразить через `filter{ ... } + map { ... }`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return lucky_jump_storage.sortedDescending()[0]
Можно просто `lucky_jump_storage.max()`

2016-10-27 15:04 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (jumps.any { !allowed_symbols.contains(it) }) return -1
Можно `it !in allowed_symbols`

2016-10-27 20:51 UTC, DDRDmakar commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int = m / gcb(m, n) *  n
Этот пример я нашёл в интернете, тоже думал поменять действия местами. Но если сначала умножать, а потом делить, то быстрее произойдёт переполнение переменной.

2016-10-28 12:01 UTC, ice-phoenix requested changes

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = Math.sqrt(((x1 - x2) * (x1 - x2)) + ((y1 - y2) * (y1 - y2)))
Лишние скобки вокруг законченных выражений

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun numberRevert(number: Int): Int = number%10 * 100 + number%100 - number%10 + (number - number%100) / 100
Форматирование кода

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    // V T
Излишний комментарий

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    val s1 = ((number - number % 1000) / 1000) + ((number % 1000 - number % 100) / 100)
Излишние скобки

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +	else {
`} else {`

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +	val min_1 : Int
`camelCase`

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun gcd(m: Int, n: Int): Int = if(n == 0) m else gcd(n, m % n)
Форматирование кода

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int = m / gcd(m, n) *  n
Лучше `m * n / gcd(m, n)`

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val xMin = x % (2 * Math.PI)
Почему в одной функции данная переменная названа `angle`, а в другой `xMin`?

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return list.map { it - ariphmeticalАverage }.toMutableList()
Вы должны изменять список, переданный на вход

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Зачем эта проверка? Разве код ниже не будет работать для пустого списка?

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 2..Math.abs(n / 2)) if (n % i == 0) return false
Эту функцию можно написать проще, если вспомнить о других функциях, которые вы уже писали

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        }
Может быть, весь этот цикл можно заменить на какую-то уже написанную вами функцию?

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        for (element in digitStorage) append(numToSymbol(element))
Совсем круто было бы, если бы вы разобрались, как это написать через функцию `fold`

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var currentDigit: Int
Почему эта переменная объявлена здесь, а не в цикле?

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        currentDigit = (element - if ('0' <= element && element <= '9') '0' else 'a' - 10).toInt()
Лучше сделать отдельную функцию, которая переводит символ в число

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        append(if (datePartStorage[0].length < 2) '0' + datePartStorage[0] else datePartStorage[0])
> Почитайте про функцию `String.padStart()`

Вы же ее и так используете ниже, почему вы не используете ее здесь???

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if(target.any { !allowedSymbols.contains(it) }) return ""
* Форматирование кода
* `a !in b`

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        luckyJumpStorage = (jumpStorage.filter { it != "-" && it != "%" }).map { it.toInt() }
Лишние скобки

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val attemptStorage = mutableListOf <Int>()
Форматирование кода

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (jumpStorage[i + 1].any { '0' <= it && it <= '9' })
`it in ...`

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return target
[Здесь и везде] Внутри `try` можно писать, в том числе, и `return`

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                target -= expressionStorage[i+1].toInt()
Форматирование кода

2016-10-28 12:01 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                name = element.dropLast(element.length - separator)
Можно `take(separator)`

2016-11-16 09:56 UTC, ice-phoenix requested changes

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var digits_amount = 0
Ап

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var fTemp: Int
Почему не проинициализировать эту переменную каким-либо значением?

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        fTemp = f
Почему не объявить эту переменную прямо тут?

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if(Math.abs(eps) > Math.abs(part)) break
Форматирование кода

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for((index, element) in list.withIndex())
Форматирование кода

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    while (!numberIsPrime(currentNumber)) {
Нельзя ли обойтись без функции `numberIsPrime`?

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val digitStorage = mutableListOf <Int>()
Форматирование кода

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (n < 0 || base < 2) return listOf()
Почему вы проверяете вход на ошибки после того, как обработали один отдельный, но корректный случай?

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return decimal(digitStorage, base)
:+1:

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return ""
Эту проверку лучше делать до того, как вы начинаете собирать строку в `StringBuilder`

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return luckyJumpStorage.max()
Можно все это выразить проще через `?:`

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val attemptStorage = mutableListOf <Int>()
Форматирование кода

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return attemptStorage.max()
См. выше

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var target: Int
Почему эта переменная объявлена здесь?

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var separator: Int
Почему эта переменная объявлена здесь?

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var currentPrice: Double
Почему эта переменная объявлена здесь?

2016-11-16 09:56 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    fun length(): Double = begin.distance(end)
Если вам необходимо расширить сторонний класс, в Котлине для этого используются `extension methods`, а не `я забрался в код и поменял все как мне надо`

2016-11-16 09:56 UTC, ice-phoenix commented
recheck all

2016-11-24 12:18 UTC, ice-phoenix requested changes

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = hoursArrive * 60 + minutesArrive - hoursDepart * 60 - minutesDepart
Длинные строки

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (half > s1 && half <= s1 + s2) -> t1 + ((half - s1) / v2)
Первую часть можно не проверять, вы ее уже проверили строчкой выше

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (c <= a && a <= b && b <= d) -> b - a
Данный набор условий можно записать намного короче, если подумать, как связаны уменьшаемое и вычитаемое с границами отрезков и функциями `min / max`

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +	}
Форматирование кода

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +
Зачем эта пустая строка?

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +
Многовато пустых строк

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (sequenceLen + lastSequenceElement.length >= n) return (lastSequenceElement[n - sequenceLen - 1] - '0').toInt()
Длинная строка

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return (lastSequenceElement [n - 1] - '0').toInt()
Форматирование кода

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun numberIsPrime(n: Int): Boolean {
Зачем вам эта функция?

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val digitStorage = mutableListOf <Int>()
Форматирование кода

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val digit_1 = listOf("", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX") // 1 2 3 4 5 6 7 8 9
`camelCase`

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        return this.toString()
:+1:

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return if (luckyJumpStorage.isEmpty()) -1 else luckyJumpStorage?.max() ?: -1
Зачем первая проверка?

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        luckyJumpStorage = jumpStorage.filter { it !in "-%" }.map { it.toInt() }
Почему вы разделили определение и объявление переменной?

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val attemptStorage = mutableListOf <Int>()
Форматирование кода

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return if (attemptStorage.isEmpty()) -1 else attemptStorage.max()
Лучше через элвис-оператор

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            } else throw IllegalArgumentException("null")
Зачем `"null"`?

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    fun length(): Double = begin.distance(end)
Все еще актуально

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    return longestSegment
Как ваш код проверяет, что в множестве менее двух точек?

2016-11-24 12:18 UTC, ice-phoenix commented
recheck all

2016-11-24 20:34 UTC, DDRDmakar commented on src/lesson6/task1/Geometry.kt
> +    return longestSegment
Я исправил не всё, так и написал в названрии коммита.

2016-11-24 20:36 UTC, DDRDmakar commented on src/lesson5/task1/Parse.kt
> +            } else throw IllegalArgumentException("null")
Конструктор требует строку. Что нужно ему передавать? Я не знаю, поэтому передаю "null"

2016-12-05 12:02 UTC, ice-phoenix commented
recheck all

2016-12-05 12:23 UTC, ice-phoenix requested changes

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = hoursArrive * 60 + minutesArrive - hoursDepart * 60 - minutesDepart
Все еще актуально

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (c <= a && a <= b && b <= d) -> b - a
Все еще актуально

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return primeDivisorsStorage.sorted()
Зачем сортировать?

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return luckyJumpStorage?.max() ?: -1
Зачем тут safe call в `list?.max()`?

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    return longestSegment
Все еще актуально

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    val ang = Math.atan((b.y - a.y) / (b.x - a.x)) + Math.PI / 2
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        return if(inside()) ('a' + column - 1).toString() + row.toString() else ""
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        return if(inside()) ('a' + column - 1).toString() + row.toString() else ""
Форматирование кода

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if(!notation.matches(Regex("""[a-h][1-8]"""))) throw IllegalArgumentException()
Форматирование кода

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +fun Square.similarWith(other: Square): Boolean = column == other.column && row == other.row
Как мне кажется, это просто операция равенства для клеток

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +fun Square.onLineWith(other: Square): Boolean = column == other.column || row == other.row
:+1:

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +    private fun createRow(length: Int, e: E) = Array<Any?>(length) { j -> e }
Почему `Any?`?

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (row !in 0..height - 1 || column !in 0..width - 1) return
Почему здесь вы проверяете границы, а в `get` --- нет?

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                if (j != width - 1) stringStorage.append(",")
Чтобы избежать дорогой проверки внутри цикла, обычно разделитель добавляют всегда, а снаружи цикла откусывают лишний

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    while (matrixMin(field) == 0) {
Может быть, условие завершения можно сделать попроще, чем каждый раз обходить ВСЮ матрицу и искать в ней нули?

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        println(row)
Это еще что такое?

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        for(j in 0..D - 1) {
Форматирование кода

2016-12-05 12:23 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            row.size != D
Это все можно проверить просто через равенство ваших множеств какому-то эталонному

2016-12-07 09:38 UTC, mglukhikh commented
recheck all

2016-12-07 10:23 UTC, DDRDmakar commented on src/lesson5/task1/Parse.kt
> +        return luckyJumpStorage?.max() ?: -1
Потому что max() возвращает Int?

2016-12-07 10:33 UTC, DDRDmakar commented on src/lesson7/task1/Matrix.kt
> +    private fun createRow(length: Int, e: E) = Array<Any?>(length) { j -> e }
Потому что компилятор не принимает массив шаблонов. 
" Cannot use 'T' as refied type parameter. Use a class instead."

2016-12-09 08:51 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return luckyJumpStorage?.max() ?: -1
Это прекрасно, но зачем делать safe call на том, что вполне себе не является nullable типом?

2016-12-09 08:52 UTC, ice-phoenix commented
recheck all

2016-12-10 14:00 UTC, DDRDmakar commented on src/lesson5/task1/Parse.kt
> +        return luckyJumpStorage?.max() ?: -1
Иначе отказывается компилироваться

2016-12-12 10:24 UTC, ice-phoenix requested changes

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val min_coordinate = listOf<Int>(a, b, c, d).min()
`camelCase`

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val max_coordinate = listOf<Int>(a, b, c, d).max()
Это совсем не упрощает набор условий

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +	return (min1 <= r && min2 <= s) || (min1 <= s && min2 <= r)
Форматирование кода

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        return luckyJumpStorage?.max() ?: -1
Не верю (с) Обсудите с преподавателем на занятиях, чтобы он объяснил, что и как

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +    if(height <= 0 || width <= 0) throw IllegalArgumentException()
Форматирование кода

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +    private fun createRow(length: Int, e: E) = Array<Any?>(length) { j -> e }
Тип у массива можно указать точнее, чем `Any?`

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (row !in 0..height - 1 || column !in 0..width - 1) return
Почему при чтении элемента выход за границу --- это исключение, а при записи --- нет?

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +            res = res * 23 + elem.hashCode()
Почему хэш код не учитывает размеры матрицы?

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        cellNumber += 4
Зачем вам эта переменная?

2016-12-12 10:24 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    val etalon = mutableSetOf<Int>()
Называть переменные транслитом --- не очень хорошо

2016-12-13 10:18 UTC, mglukhikh commented on src/lesson7/task1/Matrix.kt
> +    private fun createRow(length: Int, e: E) = Array<Any?>(length) { j -> e }
Просто для информации (возможно, в вопросе речь не об этом): попытка создать `Array<E>` приведёт к ошибке компиляции, так как массивы в JVM имеют reified type parameters.

2016-12-18 21:37 UTC, ice-phoenix commented
recheck all

2016-12-18 21:46 UTC, ice-phoenix commented
recheck all

2016-12-18 21:56 UTC, ice-phoenix requested changes

2016-12-18 21:56 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var sumLen = setOf(b, d)?.min() ?: 0
Почему бы не воспользоваться просто функциями `Math.min / Math.max`?

2016-12-18 21:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val primeDivisorsStorage = mutableListOf <Int>()
Форматирование кода

2016-12-18 21:56 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (cell.row !in 0..height - 1 || cell.column !in 0..width - 1) throw IllegalArgumentException()
Почему просто не вызвать метод выше?

2016-12-18 21:56 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (cell.row !in 0..height - 1 || cell.column !in 0..width - 1) throw IllegalArgumentException()
Почему просто не вызвать метод выше?

2016-12-18 21:56 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +               if (storage[i][j] != other.storage[i][j]) return false
Весь этот цикл можно заменить на `==`

2016-12-18 21:56 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            if (i > 0) field[i, j] += matrix[i-1, j]
Все это можно записать много проще, если расщепить один цикл на несколько --- по циклу на границу матрицы, плюс еще один по внутренним элементам

2016-12-18 22:00 UTC, ice-phoenix commented
С учетом статистики решений у вас все очень "Хорошо". Поздравляем!

2017-07-26 18:24 UTC, closed without merging