Решение simple.kt
Kotlin-Polytech/KotlinAsFirst2016 pull request #90
Opened 2016-09-20 16:44 UTC by TripleMan29

2016-09-20 17:19 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (age % 100 == age % 10 + 10) return ("$age лет")
Не совсем очевидная строка, лучше заменить на более понятную проверку на попадание в диапазон 10..19.

2016-09-20 17:20 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else if ((age % 10 < 5) and (age % 10 >= 2)) return ("$age года")
Здесь можно проверять на попадание в диапазон: `age % 10 in 2..4`

2016-09-20 17:21 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else return ("$age лет")
Возвращаемое значение не обязательно заключать в скобки

2016-09-20 17:26 UTC, maximpetrov commented
recheck all

2016-09-20 17:54 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial*(1+percent*0.01)*(1+percent*0.01)*(1+percent*0.01)
Здесь лучше использовать функцию `pow` для возведения в степень.

2016-09-25 01:10 UTC, maximpetrov commented
recheck all

2016-09-25 01:15 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX1) || (kingY == rookY1)) and ((kingX != rookX2) and (kingY != rookY2))) return 1
Заведите переменные для условий нападения каждой из ладей, чтобы не вычислять одно и то же условие несколько раз.

2016-09-25 01:16 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX) || (kingY == rookY)) and ((kingX/kingY != bishopX/bishopY))) return 1
То же, что и в задаче про 2 ладьи + где-то ошибка, тест этой функции не проходит.

2016-09-25 01:17 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((sqr(a) + sqr(b) == sqr(c)) || (sqr(a) + sqr(c) == sqr(b)) || (sqr(c) + sqr(b) == sqr(a))) return 1
Сначала вычислите наибольшую сторону, чтобы упростить все условия.

2016-09-25 01:19 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((b >= c) and (b <= d) and (a <= c)) return b - c
Здесь ровно половина условий - лишние.

2016-09-25 01:20 UTC, maximpetrov requested changes
Не забудьте исправить прошлые замечания.

2016-09-26 18:24 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if (number/1000 + number/100%10 == number/10%10 + number%10) return true
[Здесь и далее] Выражение `if (x) return true else return false` эквивалентно `return x`

2016-09-26 18:31 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    val min1: Int = Math.min(Math.min(a,b),c)
Лучше использовать более говорящие имена, чем `min1`, `min2` и т.д.

2016-09-26 18:32 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if (min1 <= min2) { if (middle <= max3) return true
Здесь можно объединить два условия в одно.

2016-09-26 18:32 UTC, maximpetrov requested changes
Все предыдущие замечания остаются в силе

2016-09-29 12:26 UTC, maximpetrov requested changes

2016-09-29 12:26 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val NotAttackRockX1: Boolean = (kingX != rookX1) and (kingY != rookY1)
Вместо этой переменной можно использовать `!AttackRockX1`.

2016-09-29 12:26 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((AttackRockX1) and (NotAttackRockX2)) return 1
Если выбрать правильный порядок проверки условий, то `NotAttackRockX1` и `NotAttackRockX2` вообще не нужно будет проверять.

2016-09-29 12:26 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val a: Int = (kingX - bishopX)*(kingX - bishopX)
Следовало завести переменные, в которых хранились бы условия угрозы слоном и ладьёй, как Вы сделали в предыдущей задаче.

2016-09-29 12:26 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +    if ((r >= a) and ((s >= b) || (s >= c))) return true
Лучше всё-таки было оставить нахождение наименьших сторон кирпича

2016-09-29 17:33 UTC, maximpetrov requested changes

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var k: Int
Можно инициализировать переменные прямо при объявлении, тогда, к тому же, можно тип не указывать.

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in  1..m*n) {
Есть более оптимальный алгоритм вычисления НОК.

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if ((n%i == 0) and (i < d)) d = i
Вместо введения дополнительной переменной, можно возвращать множитель сразу при нахождении.

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Не обязательно перебирать до `n`.

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..(n-1)) {
Можно пойти перебирать с конца, тогда тоже можно будет вернуть результат сразу при нахождении.

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..(m*n)) {
Используйте более оптимальный алгоритм.

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..m*n) {
Зачем Вы перебираете до `m*n`?

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    number = k.toDouble() / Math.pow(10.0, (i).toDouble())
Не стоит здесь связываться с Double, у Вас могут возникнуть проблемы с точностью.

2016-09-29 17:33 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    number = k.toDouble() / Math.pow(10.0, (i).toDouble())
Не стоит здесь связываться с Double, у Вас могут возникнуть проблемы с точностью.

2016-10-12 11:40 UTC, mglukhikh commented
Автору PR: пожалуйста, удалите из вашего репозитория лишние файлы. Лишними являются папки _windows и inspection, а также все файлы с расширением xml, кроме файла pom.xml. Их хранение в репозитории бессмысленно; кроме этого, из-за них у вас появляется много ничего не значащих изменений, которые читать ваши PR.

2016-10-25 21:13 UTC, maximpetrov commented
recheck all

2016-10-25 21:20 UTC, maximpetrov commented
Новые задания не будет проверяться, пока Вы не исправите замечания к предыдущим

2016-10-26 11:47 UTC, maximpetrov commented
recheck all

2016-10-28 14:16 UTC, maximpetrov requested changes

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    val s1: Double = v1 * t1
Лучше перенести объявление `s1` и `s2` перед объявлением `s` и использовать их.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((AttackRockX1) and (!AttackRockX2)) return 1
Поменяйте порядок проверки условий таким образом, чтобы условия немного упростились.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((AttackRock) and (a != b)) return 1
Заведите переменную для угрозы от слона + поменяйте порядок поверки условий, чтобы упростить эти условия.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    if ((a + b <= c) || (a + c <= b) || (c + b <= a)) return -1
Найдите наибольшую сторону треугольника вместо того, чтобы проверять все стороны.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson2/task2/Logical.kt
> +   val pass = ((r >= a) and ((s >= b) || (s >= c))) || ((r >= b) and ((s >= c) || (s >= a))) || ((r >= c) and ((s >= b) || (s >= a)))
Что помешало записать эту функцию в виде однострочной?

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in  1..k) {
От замены `m*n` на `k` алгоритм поиска НОК не стал оптимальнее.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Можно ограничить перебор числом меньшим, чем `n`.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if ((n%i == 0) and (i < n)) return i
Зачем проверяется, что `i < n`?

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in (n-1) downTo 1) {
Можно начинать перебор не `n-1` и заканчивать не 1.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..m) {
Алгоритм всё ещё не оптимальный

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..n) {
Это немного логичнее, чем перебирать до `m*n`, но можно значительно сократить диапазон перебора.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    if ((k > 0) and (m!=0) and (n!=0)) return true
Нельзя ли упростить две эти странные проверки?

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    number = k.toDouble() / Math.pow(10.0, (i).toDouble())
Здесь также не стоит использовать `double`.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +fun powInt(number: Int, degree: Int): Int {
Функцию Вы написали, а воспользоваться забыли?

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    val abs = Math.sqrt(sqr)
Можно не заводить временную переменную

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    for (i in 0..v.size-1) {
Здесь лучше воспользоваться циклом `for` прямо по списку, а не по его индексам.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var list = listOf<Int>()
Используйте `MutableList`, `List` нельзя изменять.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +            list += minDivisor(N)
`minDivisor` каждый раз проходит по всем делителям, которые Вы уже проверили.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    return list.sorted()
Зачем сортировать список, если Вы итак помещаете элементы в него в порядке возрастания?

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    var list = listOf<Int>()
Используйте `MutableList`

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +        list = listOf(N % base) + list
Лучше класть элементы в конец, а потом перевернуть список.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список лучше сделать глобальным и использовать в следующей задаче тоже.

2016-10-28 14:16 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        if ((day !in 1..31) or (month !in months)) return ""
Сразу найдите индекс месяца с помощью `indexOf`, чтобы не искать его два раза.

2016-10-28 14:17 UTC, maximpetrov commented
recheck all

2016-11-18 09:40 UTC, maximpetrov commented
recheck all

2016-11-18 09:42 UTC, maximpetrov commented
recheck all

2016-11-18 13:36 UTC, maximpetrov requested changes

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double = initial*(1+percent*0.01)*(1+percent*0.01)*(1+percent*0.01)
Замечание ещё в силе

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else if ((AttackRockX1) and (!AttackRockX2)) return 1
Здесь можно не проверять на `!AttackRockX2`, потому что это уже проверяется в предыдущем условии

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson2/task1/IfElse.kt
> +    else if ((AttackRock) and (!AttackBishop)) return 1
Здесь можно не проверять на `!AttackBishop`, потому что это уже проверяется в предыдущем условии

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    var count = n*m
Этот вариант чуть лучше, но не намного

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n-1) {
Диапазон перебора можно сильнее ограничить сверху

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in (n-2) downTo 2) {
Диапазон перебора можно сильнее ограничить сверху и снизу

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if ((n%i == 0) and (i > 1)) return i
Зачем проверка на > 1? Во-первых, у Вас диапазон перебора до 2, в во-вторых, если бы Вы и добрались до 1 в переборе, то почему она не подошла бы?

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +        if ((m <= k * k) and (k * k <= n)) return true
`k * k` стоит вынести в переменную.

2016-11-18 13:36 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in 1..number) {
Вместо этого неэффективного цикла воспользуйтесь одной из функций `round`, `floor` или `ceil`.

2016-11-24 15:31 UTC, maximpetrov commented
recheck all

2016-12-09 23:28 UTC, maximpetrov commented
recheck all

2016-12-09 23:40 UTC, maximpetrov requested changes
Кроме этих замечаний, у Вас ещё несколько так и не исправлено, а также несколько тестов не проходят

2016-12-09 23:40 UTC, maximpetrov commented on src/lesson3/task1/Loop.kt
> +    for (i in max..m * n) {
От того, что Вы начали с одного из чисел, а не с 1, алгоритм не стал намного оптимальнее.

2016-12-09 23:40 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +import org.jetbrains.annotations.Mutable
Зачем этот импорт?

2016-12-09 23:40 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +            pforx = pforx + p[i] * Math.pow(x, i.toDouble())
Здесь лучше накапливать множитель x в степени по ходу цикла

2016-12-09 23:40 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Почему эта проверка происходит уже после того, здесь, а не в самом начале?

2016-12-09 23:40 UTC, maximpetrov commented on src/lesson4/task1/List.kt
> +            list += minDivisor(N)
Вы всё ещё используете функцию `minDivisor`, которая будет каждый раз перебирать множители с 2, независимо от того, что Вы их уже рассматривали. Кроме того, Вы два раза вызываете её вместо того, чтобы сохранить результат в переменную.

2016-12-09 23:40 UTC, maximpetrov commented on src/lesson5/task1/Parse.kt
> +        val months = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Сделайте этот список глобальным и общим с предыдущей функцией

2016-12-17 20:53 UTC, mglukhikh commented
Предупреждаю вас, что без исправления замечаний к первым пяти урокам уроки 6 и 7 не будут вам зачтены.

2016-12-18 11:09 UTC, maximpetrov commented
recheck all

2016-12-19 09:12 UTC, mglukhikh commented
recheck all

2016-12-19 09:15 UTC, mglukhikh commented
recheck all

2016-12-19 09:24 UTC, mglukhikh commented
recheck all

2016-12-19 10:51 UTC, maximpetrov commented
recheck all

2016-12-19 10:51 UTC, maximpetrov commented
recheck all

2016-12-19 10:52 UTC, maximpetrov commented
recheck all

2017-03-06 15:07 UTC, closed without merging