Lesson 2 Task 1 DONE
Kotlin-Polytech/KotlinAsFirst2016 pull request #91
Opened 2016-09-20 19:36 UTC by IgorLo

2016-09-21 15:53 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +    if (age%100 in 5..20) return "$age лет"
[Здесь и далее]
Цепочку из проверки нескольких взаимоисключающих условий лучше оформить в виде:
```kotlin
if (age%100 in 5..20) return "$age лет"
else if (age%10 == 1) return "$age год"
else if (age%10 in 2..4) return "$age года"
else return "$age лет"
```
А ещё лучше в виде конструкции `when`

2016-09-21 15:55 UTC, gagarski commented on src/lesson2/task1/IfElse.kt
> +        else -> when {
Вложенный в `else` `when` не нужен. Если вы запишете условия из внутреннего `when` во внешний, то результат не изменится (в них вы будете попадать, только если предыдущие условия не верны).

2016-09-21 15:58 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if (number/1000 + ((number/100)%10) == (number%10 + (number/100)%10)) return true
- См. выше про взаимоисключающие условия
 - Вы используете довольно многословный способ вовзращения булевского значения.
```kotlin
if (x) return true else return false
```
эквивалентно
```kotlin
return x
```

2016-09-21 15:59 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    x1 == x2 -> return true
- Попробуйте применить автоматическое форматирование  в Intellij IDEA к данному участку кода (выделите этот участок и нажмите `Code -> Reformat Code` в меню). Посмотрите на результат и постарайтесь придерживаться такого стиля форматирования.

2016-09-21 15:59 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if (((Math.sqrt((x1-x2) * (x1-x2) + (y1-y2) * (y1-y2))) + r1) <= r2) return true
- См. выше про взаимоисключающие условия
 - Вы используете довольно многословный способ вовзращения булевского значения.
```kotlin
if (x) return true else return false
```
эквивалентно
```kotlin
return x
```

2016-09-21 16:00 UTC, gagarski commented on src/lesson2/task2/Logical.kt
> +    if (s>=a && (r>=b || r>=c)) return true
Попробуйте заранее вычислить минимальные стороны кирпича. Условия станут заметно проще.

2016-09-21 16:01 UTC, gagarski requested changes

2016-09-27 22:59 UTC, gagarski requested changes

2016-09-27 22:59 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    if (m > n) {
Есть функции `Math.min()` и `Math.max()`.

2016-09-27 22:59 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    for (i in 0..n) {
Можно ли сузить интервал перебора?

2016-09-27 22:59 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var N = Math.abs(n)
Переменные в Котлине принято называть с маленькой буквы.

2016-09-27 22:59 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var N = Math.abs(n)
Переменные в Котлине принято называть с маленькой буквы.

2016-09-27 22:59 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var N = n
Переменные в Котлине принято называть с маленькой буквы.

2016-09-27 22:59 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    count = line[n - 1].toInt()
`Char.toInt()` делает вовсе не то, что вы думаете.

2016-09-27 22:59 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var line = "1"
Постарайтесь решить эту задачу без сохранения всей строки в памяти.

2016-09-27 23:00 UTC, gagarski commented
recheck all

2016-09-27 23:06 UTC, gagarski commented
Обратите внимание, что у вас есть ошибки в 1 и 2 уроке. Пройдитесь также по замечаниям и исправьте их.

2016-09-30 21:19 UTC, gagarski commented
Ваш код не компилируется. Запускайте пожалуйста локальные тесты перед коммитом.

2016-10-06 10:34 UTC, gagarski requested changes

2016-10-06 10:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var a = x
- Протестируйте синус и косинус на больших числах (10π, 100π, 1000π) и заставьте его работать, используя свойства синуса и косинуса.
  - Переменным лучше давать осмысленные имена, соответствующие их назначению в коде.

2016-10-06 10:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    var line = "1"
done

2016-10-06 10:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +        if ((n / (Math.pow(10.0, digitNumber(n) - i.toDouble())).toInt()) % 10 != (n / (Math.pow(10.0, i.toDouble() - 1)).toInt()) % 10) return false
- Старайтесь избегать операций с числами с плавающей точкой в целочисленных задачах, реализуйте `pow` для целых чисел, это несложно.

2016-10-06 10:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    while (a % b > 0) {
Лучше вынести вычисление НОД в отдельную функцию.

2016-10-06 10:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    val min: Int
Попробуйте решить данную задачу с использованием реализованных вами ранее функций (это можно сделать в одну строку).

2016-10-06 10:34 UTC, gagarski commented on src/lesson3/task1/Loop.kt
> +    return (n * m) / b
Лучше сначала поделить на `b`, а потом умножить на `m`. Так вы избежите переполнения в некоторых случаях для больших чисел. (Например `nok(1000000, 1000000)`)

2016-10-24 10:49 UTC, gagarski requested changes
Исправьте пожалуйста имеющиеся замечания и ошибки прежде чем приступать к новым задачам.

2016-10-24 10:49 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    for (i in 0..revResult.size - 1) {
Используйте функцию `reverse` у списка.

2016-10-24 10:49 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var count = 2
Область видимости `count` можно уменьшить до тела цикла.

2016-10-24 10:49 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Нет необходимости рассматривать пустой список как особый случай. Если список пуст, ваша функция просто не попадёт внутрь цикла и вернёт неизменённый список последним `return`.

2016-10-24 10:49 UTC, gagarski commented on src/lesson4/task1/List.kt
> +fun center(list: MutableList<Double>): MutableList<Double> {
В задании предполагается то, что вы будете изменять входной список, а не создавать новый.

2016-10-28 12:12 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var count = 2
Вы каждый раз начинаете перебор с 2. Можно начинать с текущего делителя.

2016-10-28 12:12 UTC, gagarski commented on src/lesson4/task1/List.kt
> +fun center(list: MutableList<Double>): MutableList<Double> {
fixed

2016-11-21 13:21 UTC, gagarski requested changes

2016-11-21 13:21 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    var count = 2
Всё ещё актуально. Если вы обнаружили, что число делится на count, то нет смысла перебирать делители меньше `count`, поскольку вы уже поделили `n` на них.

2016-11-21 13:21 UTC, gagarski commented on src/lesson4/task1/List.kt
> +    return result.sorted()
Сортировать список не имеет смысла, он у вас отсортирован по результатам того, как вы его формируете.

2016-11-21 13:21 UTC, gagarski commented on src/lesson4/task1/List.kt
> +        result += digits[i] * (Math.pow(base.toDouble(), (digits.size - 1 - i).toDouble())).toInt()
Переход к числам, с плавающей точкой в целочисленных задачах может привести к проблемам с точностью. Реализуйте `pow` для целых чисел, это несложно.

2016-12-07 09:43 UTC, mglukhikh commented
recheck all

2016-12-14 20:02 UTC, mglukhikh requested changes
См. замечание

2016-12-14 20:02 UTC, mglukhikh commented on src/lesson5/task1/Parse.kt
> +    val matchResult = Regex("""[^-0-9+()\s]""").find(phone)
Отвечая на ваш сегодняшний вопрос: эта функция (кажется) может работать некорректно с входом вида: `phone = "\t"` (табуляция).

2016-12-19 15:38 UTC, gagarski commented
recheck all

2016-12-21 09:33 UTC, mglukhikh commented
recheck all

2017-07-26 18:24 UTC, closed without merging