lesson 1, 2, 3
Kotlin-Polytech/KotlinAsFirst2016 pull request #93
Opened 2016-09-21 09:38 UTC by VirusVoid

2016-09-21 11:54 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val r = seconds+(minutes*60)+(hours*60*60)
Данное выражение лучше оформить как `return seconds + ...`

2016-09-21 11:55 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val q = ((vershoks*4.445)+(arshins*16*4.445)+(sagenes*48*4.445))/100
См. замечание к `seconds`

2016-09-21 11:55 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val y = (sec/3600.0+min/60.0+grad)*PI/180
См. замечание к `seconds`

2016-09-21 11:55 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val l = sqrt(sqr(abs(x2-x1))+sqr(abs(y2-y1)))
* См. замечание к `seconds`
* Зачем брать модуль перед возведением в квадрат?

2016-09-21 11:55 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val c = (number/100)%10
См. замечание к `seconds`

2016-09-21 11:56 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val t = (hoursArrive*60+minutesArrive)-(hoursDepart*60+minutesDepart)
См. замечание к `seconds`

2016-09-21 11:58 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val m = (initial*(1+percent/100.toDouble())*(1+percent/100.toDouble())*(1+percent/100.toDouble()))
* Повторно используемые выражения следует вынести в переменные
* См. замечание к `seconds`

2016-09-21 11:58 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val p = (number%10)*100+((number/10)%10)*10+(number/100)
См. замечание к `seconds`

2016-09-21 11:58 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (s1 > s12) s12 / v1
Данное выражение лучше оформить как `when`

2016-09-21 11:59 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val s12 = (v1*t1+v2*t2+v3*t3)/2.0
Это можно выразить через `s1`, `s2`, `s3`

2016-09-21 11:59 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (((kingY == rookY1)||(kingX == rookX1))&&((kingY == rookY2)||(kingX == rookX2))) 3
Выражения, соответствующие фактам атаки короля той или иной фигурой, лучше вынести в отдельные переменные с говорящими именами

2016-09-21 12:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (((kingY == rookY) || (kingX == rookX)) && (abs(bishopX - kingX)) != (abs(bishopY - kingY))) 1
Выражения, соответствующие фактам атаки короля той или иной фигурой, лучше вынести в отдельные переменные с говорящими именами

2016-09-21 12:00 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> -
Постарайтесь избегать внесения изменений, не относящихся к решению задач

2016-09-21 12:00 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return if (s1==s2) true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-21 12:01 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    do {c=c/10
Отформатируйте код при помощи IntelliJ IDEA и в дальнейшем постарайтесь придерживаться такого же стиля

2016-09-21 12:01 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i=0;
Переменным лучше давать говорящие имена

2016-09-21 12:02 UTC, ice-phoenix requested changes

2016-09-30 08:33 UTC, ice-phoenix commented
Обращаю ваше внимание, что код, отправленный вами, даже не компилируется. Убедительная просьба проверять работоспособность вашего кода локально, путем запуска встроенных тестов, перед отправкой PR.

Исправляйте вашу функцию `timeForHalfWay`, в которой есть определенная проблема с типом возвращаемого значения.

2016-10-06 11:31 UTC, ice-phoenix requested changes
Исправьте имеющиеся замечания перед тем, как продолжать работу над следующими уроками

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +   return seconds+(minutes*60)+(hours*60*60)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((vershoks*4.445)+(arshins*16*4.445)+(sagenes*48*4.445))/100
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (sec/3600.0+min/60.0+grad)*PI/180
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return sqrt(sqr(x2-x1)+sqr(y2-y1))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (number/100)%10
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (hoursArrive*60+minutesArrive)-(hoursDepart*60+minutesDepart)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val k = 1+percent/100.toDouble()
Вместо `100.toDouble()` можно просто `100.0`

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +import lesson4.task1.abs
Почему не воспользоваться стандартным методом `abs`?

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    (age%10==1)&&(age!=111)&&(age!=11) ->"$age год"
[Здесь и везде] Просьба форматировать код правильно (в данном случае, например, весь блок `return when { ... }` должен быть смещен на 4 пробела вправо). Попробуйте отформатировать код при помощи IntelliJ IDEA и в дальнейшем придерживаться такого же стиля кодирования.

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    (age!=12)&&(age!=112)&&(age%10==2) ->"$age года"
Все эти условия можно выразить проще

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val s1 = v1 * t1
Форматирование кода --- здесь внезапно вы решаете отделять операторы пробелами от их операндов, хотя раньше все было без единого пробела. Просьба привести **весь** код к единому стилю.

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +
Какую роль несет этот перенос строки?

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        if ((c>=a)&&(c<=b)&&(d>=b)) return Math.abs(b-c)
Данное выражение лучше оформить как `when`

2016-10-06 11:31 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i=0
Переменным лучше давать говорящие имена

2016-10-11 15:23 UTC, ice-phoenix commented
Перед тем, как будет проверено ваше решение урока номер 4, вам необходимо исправить замечания к предыдущим урокам.

2016-10-12 10:53 UTC, VirusVoid commented
recheck all

2016-10-12 11:31 UTC, mglukhikh commented
recheck all

2016-10-13 12:59 UTC, ice-phoenix requested changes
Исправляйте замечания к коду (вкладка `Files changed`)

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        if (s1 >= s123) return s123 / v1
Данное выражение лучше оформить как `when`

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (((kingY == rookY1) || (kingX == rookX1)) && ((kingY == rookY2) || (kingX == rookX2))) 3
* Подвыражения, отвечающие за условия атаки короля той или иной фигурой, лучше вынести в отдельные переменнные
* Данное выражение лучше оформить как `when`

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (((kingY == rookY) || (kingX == rookX)) && (abs((bishopX - kingX)) != (abs(bishopY - kingY)))) 1
* Подвыражения, отвечающие за условия атаки короля той или иной фигурой, лучше вынести в отдельные переменнные
* Данное выражение лучше оформить как `when`

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when{
Попробуйте отформатировать ваш код при помощи IntelliJ IDEA и в дальнейшем придерживаться такого же стиля

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return if (s1 == s2) true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i = 0;
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i = 0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (ost == 0) cur = kv % 10
Данная проверка не нужна, так как тело цикла `for (j in 1..0) ...` будет выполнено ноль раз, т.е. ветка `else` делает то, что вам надо, и так

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (v.size != 0) return Math.sqrt(s)
Зачем эта проверка?

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0..v.size - 1) {
Если вам явно не нужен индекс, лучше воспользоваться циклом в `foreach` стиле
```
for (element in list) {
    foo(element)
}
```

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0..list.size - 1) {
Если вам явно не нужен индекс, лучше воспользоваться циклом в `foreach` стиле
```
for (element in list) {
    foo(element)
}
```

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        list[i] = el
Можно сразу как `list[i] = list[i] - sr`

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    sr = mean(list)
Почему вы разделили объявление и определение переменной?

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (sumpr != 0.0) return sumpr
Проверка не нужна

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (znach != 0.0) return znach
Проверка не нужна

2016-10-13 12:59 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var znach = 0.0
Переменные транслитом лучше не называть

2016-10-20 10:50 UTC, ice-phoenix commented
recheck all

2016-10-20 11:21 UTC, ice-phoenix commented
Ваши решения последних задач не будут проверены до тех пор, пока вы не исправите замечания к предыдущим.

2016-10-25 08:07 UTC, ice-phoenix commented
Вы изменили файл `pom.xml`, что привело к невозможности корректной компиляции вашего проекта на тестовом сервере. Пожалуйста, верните файл `pom.xml` к исходному виду, чтобы мы могли проверить ваши решения.

2016-10-25 14:32 UTC, ice-phoenix commented
А зачем вы вернули `pom.xml` в правильное состояние, а потом опять все сломали?

2016-10-25 15:15 UTC, ice-phoenix commented
recheck all

2016-10-27 18:27 UTC, ice-phoenix requested changes

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (age % 10 == 4) && (age % 100 != 14) -> "$age года"
Эти три условия можно объединить через `a in b..c`

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (s123 != 0.0) {
Этот `if` можно сделать частью вложенного `when`

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            ((s1 < 123) && (s1 != 0.0)) -> t1 + (s123 - s1) / v2
Что такое 123?

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val l12 = (((kingY == rookY1) || (kingX == rookX1)) && ((kingY == rookY2) || (kingX == rookX2)))
Почему бы не вытащить в отдельные переменные факт атаки королем одной или второй ладьей, а потом тривиальным образом их скомбинировать в ответ?

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val l = (((kingY == rookY) || (kingX == rookX)) && (abs((bishopX - kingX)) != (abs(bishopY - kingY))))
* См. комментарий выше
* Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((c >= a) && (c <= b) && (d >= b)) -> abs(b - c)
Зачем модуль?

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var a = 0;
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var el = 0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        s = s + kv.toString().length
`digitNumber`?

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var el1 = 0
См. замечание выше

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +           list[i]=sum
Форматирование кода

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()){
Если убрать эту проверку, сколько раз будет выполнено тело цикла ниже?

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        con = (Math.pow(base.toDouble(), l.toDouble())).toInt()
Напишите функцию `pow(Int, Int)`, работающую в целых числах

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            res += ((q.toInt() - 'a'.toInt()) + 10) * con
Переменные типа `Char` можно складывать и вычитать

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var d = 0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (part in parts) {
Зачем использовать цикл, когда вам нужно делать разные вещи с разными элементами списка?

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                when (part) {
Весь этот код и проверки можно упростить, если сразу работать с `parts[i]`

2016-10-27 18:27 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +fun dateDigitToStr(digital: String): String {
См. замечания выше

2016-10-27 18:30 UTC, ice-phoenix commented
recheck all

2016-10-28 12:24 UTC, ice-phoenix requested changes
Еще остались неисправленные замечания, можно их доделывать в рабочем порядке

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((age % 10 == 1) && (age % 100 != 11)) -> "$age год"
Лишние скобки вокруг законченных выражений

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        l && sl -> 3
Почему в двух похожих функциях вы перебираете варианты в разном порядке?

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (s1 >= half) -> half / v1
Это аналогично следующей конструкции
```
if (half != 0.0 == s1 >= half)
else if (half != 0.0 == ...)
...
```
Мне кажется, это совсем не соответствует тому, что вам надо.

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var kv = 0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return cur
Можно обойтись без этой переменной, если сразу возвращать результат

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var el1 = 0
Все еще в силе замечания выше и к этой функции

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +import kotlin.comparisons.reverseOrder
Зачем?

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        s += sqr(i)
Если вам в явном виде не нужен индекс, лучше делать
```
for (e in list) {
    foo(e)
}
```

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var sumpr = 0.0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun power(a: Int, b: Int): Int {
`pow`

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var con = 0
Почему эта переменная объявлена здесь, а не в цикле?

2016-10-28 12:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        con = power(base, l)
Можно ли обойтись без постоянного пересчета степени? Во сколько раз отличаются значения `con` между двумя соседними итерациями цикла?

2016-11-14 11:38 UTC, ice-phoenix commented
Обратите внимание, что ваш код даже не компилируется, что говорит о том, что вы даже не пробовали запускать у себя на компьютере локальные тесты. Если данная ситуация повторится в будущем, мы будем рассматривать возможность ограничения вашей оценки на экзамене "хорошо" или "удовлетворительно".

2016-11-14 11:56 UTC, ice-phoenix requested changes
Все дальнейшие решения не будут проверятся до тех пор, пока вы не исправите уже имеющиеся замечания и не объясните преподавателю на лабораторных, почему вы 1) игнорируете замечания 2) коммитите код, который даже не собирается

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((age % 10 == 1) && (age % 100 != 11)) -> "$age год"
up

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (s1 >= half) -> half / v1
Это замечание все еще в силе

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val l = (((kingY == rookY) || (kingX == rookX)))
Много лишних скобок

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        l && sl -> 3
Это замечание все еще в силе

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (s1 == s2)
Лишние скобки вокруг законченного выражения

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        if ((x1 + r1 <= x2 + r2) && (y1 + r1 <= y2 + r2)) return true
Ненужный вам код вы либо удаляете, либо исправляете

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return cur
Ап

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    ost = s - n
Почему вы разделили определение и объявление этой переменной?

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var el1 = 0
Все еще, да

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +import kotlin.comparisons.reverseOrder
В чем смысл?

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        s += sqr(i)
Это значит, что код следует переписать

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        con = pow(base, l)
Можно ли обойтись без постоянного повторного возведения `base` в степени, отличающиеся на 1?

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var a = n.toString()
Именование переменных должно говорить о том, для чего они предназначены

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var s = ""
Для сборки строки лучше использовать список строк или `StringBuilder`

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var k=0
Форматирование кода

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +return s1
А где мы с тысячами разбираемся?

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        return p.distance(center) <= radius
Функцию с одним `return` можно оформить как `fun contains(...): Boolean = p.distance(...) ...`

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var segmentpoint2 = Point(0.0,0.0)
Форматирование кода и именование переменных

2016-11-14 11:56 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var center = Point((diameter.begin.distance(diameter.end))/2)
Зачем второй раз считать радиус?

2016-11-17 14:18 UTC, ice-phoenix requested changes

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        ((s1 < half)) && (s1 + s2 >= half) -> t1 + (half - s1) / v2
Лишние скобки вокруг законченных выражений

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val sl = ((abs(bishopX - kingX)) == (abs(bishopY - kingY)))
Лишние скобки вокруг законченных выражений

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (r2 - r1) >= (distance(x1, y1, x2, y2))
* Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`
* Лишние скобки

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var l = n.toString().length
Ненужные более комментарии следует удалять

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var scalarproduct = 0.0
`camelCase`

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in 0..2) {
Если вам необходимо сделать три разных набора действий, делать их в цикле --- совсем неправильно

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var s1 = ""
Зачем вам все эти переменные?

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +
Что делает этот код?

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                when (part) {
Это замечание все еще в силе

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (part in parts) {
Это замечание все еще в силе

2016-11-17 14:18 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var segmentpoint1 = Point(0.0, 0.0)
`camelCase`

2016-11-21 08:27 UTC, mglukhikh commented
recheck all

2016-11-22 15:55 UTC, ice-phoenix requested changes

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            ((c >= a) && (c <= b) && (d >= b)) -> b - c
Лишние скобки вокруг законченных выражений

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((a*b<=holeSquare)||(b*c<=holeSquare)||(a*c<=holeSquare))return true
* Форматирование кода
* Выражение `if (cond) true else false` можно заменить на `cond`
* Данное условие не проверяет возможность прохода кирпича в отверстие

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var q=n
Форматирование кода

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (sum!=(n%10* digitNumber(n)))return true
* Повторно используемое выражение следует вынести в отдельную переменную
* Выражение `if (cond) true else false` можно заменить на `cond`

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        scalarProduct += (a[i] * b[i])
Лишние скобки

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var l = mutableListOf<Int>()
Почему `var`, а не `val`?

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var l = mutableListOf<Int>()
Не очень хорошее название переменной

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return l.joinToString(separator = "*")
Почему не вызвать функцию `factorize`?

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var c = pow(10, 0)
Зачем возводить в нулевую степень?

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var a = 0
Почему эта переменная объявлена здесь?

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var s = ""
`StringBuilder` или список строк

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            s += ('a'.toInt() + el - 10).toChar()
Зачем `toInt()`? Зачем `toChar()`?

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        } else s += el.toString()
Форматирование кода

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var d1 = 0
Почему эти переменные объявлены здесь, а не ниже?

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var d = 0
Почему эти переменные объявлены здесь?

2016-11-22 15:55 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            if (i.distance(j) > max) {
Можно сократить количество перебираемых пар в два раза

2016-11-24 14:34 UTC, ice-phoenix requested changes

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        s1 < half && s1 + s2 >= half -> t1 + (half - s1) / v2
Первую часть можно не проверять, вы проверили это условие строчкой выше

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        ((a<=r)||(b<=r)||(c<=r))&&((a<=s)||(b<=s)||(c<=s))
Форматирование кода

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return sum != n % 10 * digitNumber(n)
Если вы все равно проходитесь по числу, почему бы сразу не посмотреть, есть ли в нем отличающиеся цифры?

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        l.add(0, n)
Лучше добавлять в конец, а потом сделать `reversed()`

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
Список строк или `StringBuilder`

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result = n.toString()
Что такое представить число в нульичной системе счисления?

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var z = n
Старый код лучше удалять, он все равно сохраняется в истории репозитория

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var r1 = ""
Если во все эти переменные вы собираете результат, то лучше вместо всех них завести список строк или `StringBuilder`

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        when (unit1) {
Вы два раза делаете одно и то же (добавляя или нет "тысяч" в том или ином случае), подумайте над тем, как это упростить

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        9 -> s1 = "девяносто " + s
Может быть, вместо всех этих штук можно завести списки, в которые просто индексироваться текущей цифрой числа?

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val m = listOf("января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря")
Этот список можно вынести на верхний уровень и переиспользовать в функции ниже

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        when (parts[1]) {
См. замечание выше

2016-11-24 14:34 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    for (i in 0..points.size-1) {
Форматирование кода

2016-11-25 15:12 UTC, ice-phoenix commented
Буду проверять уроки дальше, когда вы исправите все предыдущие замечания

2016-11-27 13:25 UTC, ice-phoenix requested changes

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        else -> Double.NaN
В каких случаях выполняется данная ветка?

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k = 0;
Почему здесь очень много где прорезались точки с запятой в конце строк???

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return digitCountInNumber(q,q%10)!= digitNumber(n)
Что стало с форматированием?

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var q = n
Зачем все это?

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var ost = s - n
Почему `var`?

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var ost = s - n
См. замечания выше

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var q = n
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            } else result.append(el.toString())
Форматирование кода

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (base >= 1) {
Что такое число в одноичной системе счисления?

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val a = n.toString()
Старый код нужно удалять, он все равно остается в системе контроля версий

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var r1 = ""
Это замечание все еще актуально, данная задача не будет зачтена до тех пор, пока вы не поправите ее реализацию

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            "02" -> m1 = m[parts[1].toInt() - 1]
Нельзя ли вместо всего этого воспользоваться уже имеющимся списком месяцев? И записать преобразование в одну строчку?

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (part in "0".."9") {
Это не проверяет то, что `part` --- любое допустимое число

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (part == "-") z = -1
Обсудите с преподавателем на занятии, как следовало бы реализовать эту функцию

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +import lesson7.task2.canOpenLock
Зачем?

2016-11-27 13:25 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (row>=0&&column>=0&&row<=height&&column<=width) return cellMeaning else throw IllegalArgumentException()
Что стало с форматированием? Почему мы сперва посмотрели в список, а потом проверили, что не выходим за его границы?

2016-12-04 20:26 UTC, ice-phoenix requested changes

2016-12-04 20:26 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (n < base) {
Зачем этот случай обрабатывать отдельно?

2016-12-04 20:26 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return "$result"
`result.toString()`

2016-12-04 20:26 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            } else result.append(el.toString())
Форматирование кода должно быть единообразным

2016-12-04 20:26 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        else throw NumberFormatException()
Зачем кидать исключение, если вы сразу знаете, что здесь нужно вернуть?

2016-12-04 20:26 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        = Circle(Point((diameter.begin.x + diameter.end.x) / 2, (diameter.begin.y + diameter.end.y) / 2), (diameter.begin.distance(diameter.end)) / 2)
Длинные строки лучше разбивать на более короткие

2016-12-04 20:26 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (row >= 0 && column >= 0 && row <= height && column <= width) return cellMeaning else throw IllegalArgumentException()
Почему вы сперва сходили за элементом в список, а только потом проверили, что индексы не выходят за его границы???

2016-12-14 15:37 UTC, ice-phoenix requested changes

2016-12-14 15:37 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (parts[1].toInt() in 1..12) m1 = m[parts[1].toInt() - 1]
Можно как `val m1 = if (...) ...`

2016-12-14 15:37 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch(e: NumberFormatException) {
Форматирование кода

2016-12-14 15:37 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        (diameter.begin.distance(diameter.end)) / 2)
Форматирование кода

2016-12-14 15:37 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (row >= 0 && column >= 0 && row <= height && column <= width) {
Мне кажется, условия выхода за границы матрицы немножко неправильные

2016-12-14 15:37 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +            val cellMeaning = list[row * width + column]
Зачем это выносить в отдельную переменную?

2016-12-14 15:37 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        list[row * width + column] = value
Почему вы здесь не проверяете выход за границы матрицы?

2016-12-14 15:37 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                    width == other.width
Почему не учитывается содержимое матрицы?

2016-12-14 15:37 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                sb.append("\t"+this[row, column])
Почему табуляции?

2016-12-18 20:51 UTC, ice-phoenix commented
recheck all

2016-12-18 20:58 UTC, ice-phoenix requested changes

2016-12-18 20:58 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                    list.equals(other.list)
Можно просто `list == other.list`

2016-12-18 20:58 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                sb.append("\t" + this[row, column])
Почему табуляции?

2016-12-18 20:58 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +import lesson7.task1.MatrixImpl
Зачем?

2016-12-18 20:58 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        }
Данную функцию лучше было бы реализовать через четыре цикла, рисующие по одной стороне витка спирали

2016-12-18 20:59 UTC, ice-phoenix commented
recheck all

2016-12-18 21:02 UTC, ice-phoenix commented
С учетом многочисленных замечаний и статистики выполненных заданий у вас "Хорошо". Поздравляем!

2017-07-26 18:24 UTC, closed without merging