Lesson 2. Task 1 and 2.
Kotlin-Polytech/KotlinAsFirst2016 pull request #94
Opened 2016-09-21 09:53 UTC by Stupidman00

Тесты работают на JUnit4. Решение данной проблемы сейчас считаю второстепенным, решение задач - первостепенно.

2016-09-21 10:21 UTC, mglukhikh commented
Не проходит тест isNumberHappy (число 1295 ошибочно считается счастливым)

2016-09-21 10:21 UTC, mglukhikh commented
Не проходит тест ageDescription -- ошибочно выводится 111 год вместо лет.

2016-09-21 10:22 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    do{
Перед фигурной скобкой следует ставить пробел

2016-09-21 10:23 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +    }while(mutableNumber!=0)
Между фигурной скобкой и while, и между while и условием следует ставить пробелы

2016-09-21 10:24 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return "$age "+when{
Между when и фигурной скобкой следует ставить пробел. + в данном контексте тоже лучше отделять пробелами от операндов

2016-09-21 10:36 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +{
Открывающая фигурная скобка ставится на одной строчка с типом результата:
```
fun timeForHalfWay(...): Double {
    ...
}
```

2016-09-21 10:40 UTC, mglukhikh commented
Также общие замечания по стилю. Советую посмотреть, как выравнивает код автоформатирование в IDEA (Ctrl+Alt+L) и в дальнейшем придерживаться такого же стиля. Что касается JUnit, то нам в принципе всё равно, какую версию вы используете, так как бот всё равно использует свою.

2016-09-27 20:29 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun takeDigit(number: Int, digit: Int = 1): Int {
Вы переименовали функцию, а она используется в тестах бота. Делать этого нельзя :(. В принципе, идея была хорошей, исправить её можно так:

```
fun thirdDigit(number: Int) = takeDigit(number, 3)

fun takeDigit(number: Int, digit: Int = 1): Int {
    // Ваша функция как есть
}
```

2016-09-27 20:29 UTC, mglukhikh commented on src/lesson1/task1/Simple.kt
> +fun takeDigit(number: Int, digit: Int = 1): Int {
Исправьте этот момент, и бот сможет проверить ваше решение

2016-09-28 22:08 UTC, gagarski commented
> Тесты работают на JUnit4. Решение данной проблемы сейчас считаю второстепенным, решение задач - первостепенно.

Попробуйте следующее:
 - Проверьте, что у вас свежая версия IDEA (2016.2.x)
 - Импортируйте проект заново как написано в Tutorial'е. Если IDEA будет спрашивать что-то про добавление `pom.xml` - соглашайтесь.

После этого Maven добавит в ваш проект нужные версии библиотек. 
Если это не поможет, обратитесь на занятии к преподавателю, будем смотреть.

2016-09-29 18:01 UTC, mglukhikh requested changes
Незначительные замечания по оформлению кода -- хотя в целом он довольно хорош. Плюс, проблемы с точностью в функциях `sin` и `cos`.

2016-09-29 18:01 UTC, mglukhikh commented on src/lesson2/task1/IfElse.kt
> +    return if ((rookX == figureX) || (rookY == figureY)) true
`return if (x) true else false` строго эквивалентно `return x`.

2016-09-29 18:01 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    var count: Int = 0
В Котлине можно (почти всегда) не указывать явно типы переменных

2016-09-29 18:01 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +        temp = sqr(number.toDouble()).toInt()
Здесь проще (и надёжнее!) было бы написать `number * number`. Эти преобразования типов могут привести к случайному округлению не в ту сторону

2016-09-29 18:01 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    return result
Подумайте, как поведёт себя такое решение при больших `x`: например, 20, или 100, или 10000. Много ли итераций цикла потребуется для расчёта? Как будет вести себя точность вычислений? Можно ли что-то с этим сделать? Попробуйте написать тест для подобных случаев с `Math.sin` в качестве ожидаемого ответа и точностью `1e-10`, вы увидите, что он не проходит. Попробуйте придумать, что можно сделать с большими `x`. Вспомните об известных свойствах функций `sin` и `cos`, это вам поможет.

2016-10-01 20:11 UTC, Stupidman00 commented
Хотя sin() и cos() теперь проходят, зависимость точности от первоначального параметра x всё равно осталась.

2016-10-03 19:46 UTC, mglukhikh approved these changes
Дальнейшие фокусы с точностью -- это уже совсем из области вычислительной математики. С ходу я мог бы предложить свести параметр `x` к интервалу от `- PI / 2` до `PI / 2`, чтобы ряд сходился ещё быстрее. Ну и, строго говоря, есть более удачные для расчёта формулы, чем эти классические ряды Фурье. Если вам интересно, погуглите что-нибудь типа "формулы для расчёта синуса". А этот PR я закрываю, всё принято.

2016-10-03 19:46 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +    val newX: Double = x.mod(2.0 * Math.PI)
Да, фикс правильный. Ещё лучше просто `x % (2.0 * Math.PI)`.

2016-10-03 19:46 UTC, mglukhikh commented on src/lesson3/task1/Loop.kt
> +fun squareSequenceDigit(n: Int): Int = sequenceDigit(n, {it*it})
Красивое решение. Более изящный синтаксис здесь такой: 
```
fun squareSequenceDigit(n: Int) = sequenceDigit(n) { it * it }
```
Это так называемый лямбда-аргумент, завтра на лекции о них будем говорить

2016-10-03 19:46 UTC, closed without merging