Lesson1,2 are done
Kotlin-Polytech/KotlinAsFirst2016 pull request #98
Opened 2016-09-22 09:10 UTC by AlexanderKuptsov

2016-09-22 10:05 UTC, ice-phoenix commented on IntelliLang.xml
> +  <component name="LanguageInjectionConfiguration">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:05 UTC, ice-phoenix commented on _windows/git.xml
> +  <component name="Git.Application.Settings">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on _windows/keymap.xml
> +  <component name="KeymapManager">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on _windows/laf.xml
> +  <component name="LafManager">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on _windows/path.macros.xml
> +  <component name="PathMacrosImpl">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on colors.scheme.xml
> +  <component name="EditorColorsManagerImpl">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on debugger.xml
> +  <component name="DebuggerSettings">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on diff.xml
> +  <component name="DiffSettings">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on gradle.run.settings.xml
> +  <component name="GradleSystemRunningSettings">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on inspection/Default.xml
> +  <option name="myName" value="Default" />
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:06 UTC, ice-phoenix commented on mavenVersion.xml
> +  <component name="MavenVersion" mavenHome="Bundled (Maven 3)" />
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:08 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((sagenes*48+arshins*16+vershoks)*0.04445)
Данную функцию лучше оформить как `fun lengthInMeters(...) = ...`

2016-09-22 10:08 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return((grad+(min+sec/60.0)/60.0)*Math.PI/180.0)
Данную функцию лучше оформить как `fun angleInRadian(...) = ...`

2016-09-22 10:11 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return sqrt(sqr(x1-x2)+ sqr(y1-y2))
Данную функцию лучше оформить как `fun trackLength(...) = ...`

2016-09-22 10:12 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((number/100)%10)
Данную функцию лучше оформить как `fun thirdDigit(...) = ...`

2016-09-22 10:12 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return((hoursArrive-hoursDepart)*60+minutesArrive-minutesDepart)
Данную функцию лучше оформить как `fun travelMinutes(...) = ...`

2016-09-22 10:12 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (initial*(percent/100.0+1)*(percent/100.0+1)*(percent/100.0+1))
Повторяющиеся выражения следует вынести в отдельные переменные

2016-09-22 10:13 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return(number%10*100+(number/10%10)*10+number/100)
См. замечания выше

2016-09-22 10:13 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (age % 10 == 1 && age % 100 != 11) return "$age год"
Данное выражение лучше оформить как `when`

2016-09-22 10:14 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    var danger1=0
Переменным лучше давать чуть более осмысленные имена

2016-09-22 10:14 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((a + b <= c) || (a + c <= b) || (c + b <= a)) return -1
Для упрощения логики лучше сперва найти максимальную сторону треугольника, и все считать относительно нее

2016-09-22 10:15 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if(c<=b&&c>=a&&d>=b) return (b-c)
Отформатируйте код при помощи IntelliJ IDEA и в дальнейшем постарайтесь придерживаться такого же стиля кодирования

2016-09-22 10:16 UTC, ice-phoenix commented on web-browsers.xml
> +  <component name="WebBrowsersConfiguration">
Файлы настроек IDE не должны храниться в системе контроля версий

2016-09-22 10:16 UTC, ice-phoenix requested changes

2016-09-28 16:24 UTC, ice-phoenix requested changes
Просьба исправлять предыдущие замечания перед отправкой следующих PR. В противном случае ваш PR не будет проверяться.

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +  val p=percent/100.0 +1
Форматирование кода

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if(c<=b&&c>=a&&d>=b) return (b-c)
Данное выражение лучше оформить как `when`

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n>2) k=(fib(n-1)+ fib(n-2)) else k=1
Подумайте, сколько вызовов функции `fib(5)` необходимо для того, чтобы посчитать `fib(40)`. Можно ли уменьшить число вызовов?

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in m*n downTo 2) {
Есть ли более точная граница для минимально возможного НОК двух чисел чем 2?

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ( i%m == 0 && i%n == 0) k = i
Посмотрите более быстрые алгоритмы поиска НОК

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in n/2 downTo 2)
Зачем при поиске минимального делителя полным перебором идти от максимально возможного делителя?

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n%i==0) k=i
Зачем при поиске максимального делителя полным перебором идти от минимально возможного делителя?

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        for (i in (if (m<=n) m else n) downTo 2)
Можно ли выразить данную функцию через другие, уже реализованные вами функции этого модуля?

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +          check=true
Форматирование кода

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i*i>=m&&i*i<=n){
Подумайте, в каком случае данное условие может не выполниться?

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        newNumber+=(number%10)
Форматирование кода

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n==number) return true else return false
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        k += (i * i).toString()
Подумайте, строка какой длины потребуется для того, чтобы посчитать `squareSequenceDigit(1000000)`? Можно ли обойтись без сохранения промежуточных строк?

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (max>side1+side2 ) return -1
Данное выражение лучше оформить как `when`

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (a>=b&&a>=c) max1=c
Форматирование кода

2016-09-28 16:24 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    do {n/10
Форматирование кода

2016-09-28 16:33 UTC, ice-phoenix commented
Кроме того, реализация вашей функции `digitNumber` зависает. Постарайтесь найти в ней ошибку при помощи написания и запуска дополнительных юнит-тестов.

2016-09-28 21:16 UTC, AlexanderKuptsov commented on src/lesson2/task1/IfElse.kt
> +    if (max>side1+side2 ) return -1
А почему лучше через when?

2016-09-29 23:24 UTC, AlexanderKuptsov commented on IntelliLang.xml
> +  <component name="LanguageInjectionConfiguration">
я не знаю, как их убрать

2016-09-29 23:25 UTC, AlexanderKuptsov commented on src/lesson1/task1/Simple.kt
> +    return(number%10*100+(number/10%10)*10+number/100)
Здесь вроде нет повторений

2016-09-29 23:27 UTC, AlexanderKuptsov commented on src/lesson2/task1/IfElse.kt
> +    if(c<=b&&c>=a&&d>=b) return (b-c)
Почему when лучше if? Просто интересно

2016-09-30 08:34 UTC, ice-phoenix commented
recheck all

2016-09-30 08:36 UTC, ice-phoenix commented on IntelliLang.xml
> +  <component name="LanguageInjectionConfiguration">
Вы проходили какой-либо туториал по Git?

2016-09-30 08:52 UTC, ice-phoenix requested changes

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (c <= b && c >= a && d >= b) return (b - c)
Данное выражение лучше оформить как `when`

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (max > side1 + side2) return -1
Данное выражение лучше оформить как `when`

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (number / 1000) + ((number / 100) % 10) == (number % 10 + (number % 100) / 10)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return x1 == x2 || y1 == y2 || Math.abs(x1 - x2) == Math.abs(y1 - y2)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return (Math.sqrt(sqr(x1 - x2) + sqr(y1 - y2)) + r1) <= r2
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    var max1 = a
Вы ищите максимальные или минимальные стороны кирпича?

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n > 2) k = (fib(n - 1) + fib(n - 2)) else k = 1
Переменная `k` здесь избыточна, можно сразу использовать `return` на требуемое значение

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n/2) {
[Здесь и везде] Постарайтесь придерживаться единого стиля форматирования по всему коду. Если вы отделяете операторы пробелами, то делайте это везде. Если вы не отделяете операторы пробелами, то не делайте это никогда.

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (m!=n) return lcm(m, n).toLong() == m.toLong() * n.toLong()
Подумайте, если вы используете `Long` здесь, то нет ли смысла его использовать в других связанных с данной задачей функциях?

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val number: Int = revert(n)
Данная переменная избыточна

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var check: Boolean = false
* Система типов Котлина выведет тип переменной автоматически

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (number % 10 == (number / 10) % 10) check = false
Ветка `then` для данного `if` избыточна, лучше развернуть условие и перенести ветку `else` в ветку `then`
```
if (cond) foo    =>    if ( ! cond) { bar }
else { bar }
```

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        number += sqr(v[i].toString().toDouble())
Зачем вызов `toString().toDouble()`?

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            list[i] = list[i].toString().toDouble() - sum
Зачем вызов toString().toDouble()?

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.size != 0) {
Старайтесь быть последовательным. Если для проверки списка на пустоту вы используете `isEmpty / isNotEmpty`, то используйте их везде.

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var simple: String = ""
* Система типов Котлина выведет тип переменной автоматически

2016-09-30 08:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        simple += minDivisor(number).toString()
Если вы много раз используете `minDivisor(number)`, то почему не вынести это выражение в отдельную переменную?

2016-10-02 18:02 UTC, AlexanderKuptsov commented on IntelliLang.xml
> +  <component name="LanguageInjectionConfiguration">
Немного

2016-10-07 08:54 UTC, ice-phoenix requested changes

2016-10-07 08:54 UTC, ice-phoenix commented on IntelliLang.xml
> +  <component name="LanguageInjectionConfiguration">
Если вы не дошли в туториале до места, где рассказывают, как удалить файлы из системы контроля версий, настоятельно рекомендую таки дойти и почитать, как это сделать

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (s <= s1) return (s / v1)
Данное выражение лучше оформить как `return when ...`

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Long {
Менять тип возвращаемого значения функции в данном случае не стоило

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return k.toLong()
Зачем здесь возвращать `Long`, если вы все считаете в `Int`?

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Если при поиске максимального делителя вы идете от `n / 2` к `1`, то почему здесь нельзя идти от `2` к `n / 2`?

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (m != n) return lcm(m, n).toLong() == m.toLong() * n.toLong()
Зачем `toLong()`?

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val mSqrt = (Math.sqrt(m.toDouble())).toInt()
Для округления лучше использовать специальные функции `round / floor / ceil`

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var check: Boolean = false
* Система типов Котлина выведет тип переменной автоматически
* Результат работы функции можно возвращать сразу, без введения дополнительной переменной

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i >= m && i * i <= n) {
В каком случае данное условие не выполнится, если учесть то, как вы считаете `mSqrt` и `nSqrt`?

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return k[k.length - 1 - count + n].toString().toInt()
Данное преобразование можно сделать проще, если почитать, как представляются цифры в виде `Char`

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            list[i] = list[i].toString().toDouble() - sum
Зачем вы делаете `toString().toDouble()`???

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return if (res.isNotEmpty()) res.reversed()
На ноль лучше проверить отдельно в самом начале

2016-10-07 08:54 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        polynom(digits.map { it.toDouble() }.toList().reversed(), base.toDouble()).toInt()
Вызов `toList()` излишний

2016-10-07 08:56 UTC, ice-phoenix commented
По поводу, чем `when` лучше, чем `if`. `when` сразу говорит читающему ваш код программисту, что сейчас будут идти много равноправных вариантов развития дальнейших событий / условий / проверок. Все это, конечно же, можно выразить и через `if`, но это будет занимать больше места и несколько сложнее для понимания.

2016-10-10 10:52 UTC, ice-phoenix requested changes
Исправьте оставшиеся замечания перед продолжением работы

2016-10-10 10:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list = convert(n, base).toMutableList()
Зачем `toMutableList()`?

2016-10-10 10:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (str[i].toInt() <= '9'.hashCode()) {
Что такое `'9'.hashCode()`, зачем оно здесь и почему нельзя все сделать прямо в типе `Char`?

2016-10-10 10:52 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val listArab = listOf(1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000)
Лучше всего (если хотите так) сделать список пар и потом искать в нем нужные элементы при помощи `list.find(...)`, например

2016-10-10 10:53 UTC, ice-phoenix commented
check all

2016-10-10 19:14 UTC, ice-phoenix commented
check all

2016-10-11 15:20 UTC, ice-phoenix requested changes

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            k = i
Можно обойтись без переменной `k`

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (m % i == 0 && n % i == 0) return false
Нельзя ли эту функцию выразить через другие разработанные вами функции данного модуля?

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i >= m && i * i <= n) {
В каком случае данное условие не будет выполняться?

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var k: String = ""
* Система типов Котлина выведет тип переменной автоматически

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isNotEmpty()) {
Зачем эта проверка? Будет ли выполнено тело цикла `for` в случае, если список пуст?

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (p.isNotEmpty()) {
См. замечание к `center`

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val list = convert(n, base).toList()
Зачем `toList()`?

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            listRes += 'a' + (list[i] - 10)
Функциональность по переводу числа в соответствующий символ лучше вынести в отдельную функцию

2016-10-11 15:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val listArab = listOf(1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000)
Лучше всего (если хотите так) сделать список пар и потом искать в нем нужные элементы при помощи list.find(...), например

2016-10-11 15:21 UTC, ice-phoenix commented
recheck all

2016-10-11 15:21 UTC, ice-phoenix commented
Идем во вкладку `Files changed` и исправляем все замечания

2016-10-11 16:11 UTC, AlexanderKuptsov commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Может же быть,что число простое, тогда минимальный делить будет этим числом(+ в последующей программе мне нужно это)

2016-10-11 16:17 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Подумайте, что вернет ваша программа в случае, если просто поменять в цикле границы итерации на `2..n / 2` и число является простым

2016-10-12 10:50 UTC, ice-phoenix requested changes
Огромный совет на будущее. Если вы меняете свой код, то меняйте его в соответствии с рекомендацией преподавателя или не меняйте никак. Менять код "абы как", чтобы пропал комментарий в коде, --- **очень плохо**.

2016-10-12 10:50 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    when {
Вместо `when { ... -> return ... }` лучше `return when { ... -> ... }`

2016-10-12 10:50 UTC, ice-phoenix commented on IntelliLang.xml
> +  <component name="LanguageInjectionConfiguration">
Let me google it for you: http://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste

2016-10-12 10:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            return i
Есть ли более быстрые алгоритмы поиска НОК?

2016-10-12 10:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    //if (m != n) return lcm(m, n)==m * n
Почему вы закомментировали этот код?

2016-10-12 10:50 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i >= m && i * i <= n) {
Что исправили ваши последние изменения в этом коде?

2016-10-12 10:50 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            listRes += 'a' + (list[i] - 10)
Функциональность по переводу числа в соответствующий символ лучше вынести в отдельную функцию

2016-10-12 17:30 UTC, AlexanderKuptsov commented on src/lesson3/task1/Loop.kt
> +    //if (m != n) return lcm(m, n)==m * n
Он полостью правильно не работал, поэтому я пока оставил работающую часть

2016-10-12 17:36 UTC, AlexanderKuptsov commented on src/lesson3/task1/Loop.kt
> +        if (i * i >= m && i * i <= n) {
Ничего особо не меняют. Я пока ничего не придумал."-1" просто пробовал. Я стараюсь все исправлять(все ваши замечания), не "абы как" и не ради исчезновения комментария, но не всегда получается сразу придумать решение.

2016-10-13 12:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i >= m && i * i <= n) {
Во первых, я хочу извиниться, если вы действительно пытались исправить замечание таким странным способом. Во вторых, если вы не исправили все замечания, то не следует называть свой коммит как `Fixed all except roman`. В третьих, если вы хотите посмотреть, как ваш код ведет себя на каком-то интересном случае, этот самый интересный случай лучше добавить как еще один тест.

2016-10-13 12:40 UTC, ice-phoenix requested changes

2016-10-13 12:40 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return m * n / min
Штуку, которая считает НОД, можно было вынести в отдельную функцию

2016-10-13 12:40 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return res
Ваш код будет понятнее и чище, если вы соберете отдельные компоненты итоговой строки в список строк, а потом сделаете `joinToString` с нужным разделителем, вместо того, чтобы сразу собирать все в итоговую строку

2016-10-13 12:40 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return res
Ваш код будет понятнее и чище, если вы соберете отдельные компоненты итоговой строки в список строк, а потом сделаете joinToString с нужным разделителем, вместо того, чтобы сразу собирать все в итоговую строку

2016-10-13 12:40 UTC, ice-phoenix commented
Исправляйте оставшиеся замечания к старому коду в рабочем режиме

2016-10-17 12:29 UTC, ice-phoenix requested changes
Исправляйте, пожалуйста, предыдущие замечания перед работой над следующими уроками

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return number % 10 * 100 + (number / 10 % 10) * 10 + number / 100
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    /*  if (((kingX==rookX1)||(kingY==rookY1)) && ((kingX==rookX2)||(kingY==rookY2))) return 3
Уберите по коду ненужные более комментарии

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    /* if (c <= b && c >= a && d >= b) return (b - c)
Ненужные комментарии

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    /*for (i in Math.max(m, n)..m * n) {
Ненужный более комментарий

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +/* for (i in 2..Math.min(m, n)) {
Ненужный более комментарий

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    //return k[k.length - 1 - count + n].toString().toInt()
Ненужный более комментарий

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            listRes += 'a' + (list[i] - 10)
Я имел в виду вынести в отдельную функцию перевод **одного** символа в число и наоборот, и потом просто применить ее ко всем элементам списка через `map`

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    fun add(n: Int, letter: String): String {
Ненужный более комментарий

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +import java.util.zip.DataFormatException
Зачем вам это исключение?

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    /* val parts = str.split(" ")
Ненужный более комментарий

2016-10-17 12:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    /*  val parts = digital.split(".")
Ненужный более комментарий

2016-10-24 16:28 UTC, ice-phoenix commented
recheck all

2016-10-24 16:29 UTC, ice-phoenix requested changes

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean = (number / 1000) + ((number / 100) % 10) == (number % 10 + (number % 100) / 10)
Такие длинные строки лучше разбивать на несколько, в данном случае, например, после знака `=` в объявлении функции

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun nod(n: Int, m: Int): Int {
`nod ==> gcd`

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i >= m && i * i <= n) {
Если вы подумаете, какие функции следует применить вместо `round`, чтобы округлить границы вашего поиска в правильную сторону, можно будет обойтись вообще без цикла

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            check = true
Можно обойтись без переменной `check`, если сразу возвращать результат

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var count: Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (n >= 10) {
Лучше отформатировать как
```
if (n >= 10) ...
else ...
```

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        convert(n, base).map { numberToSymbol(it) }.joinToString(separator = "")
:+1:

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun symbolToNumber(str: String): List<Int> {
Эта штука должна выглядеть так же, как `numberToSymbol`

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val listArab = listOf(1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000)
Либо список пар, либо `Map` из одного в другое. Одновременная индексация по нескольким связанным спискам --- очень плохая идея в 99 случаях из 100.

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return String.format("%02d.%02d.%d", resDay, resMonth, resYear)
Здесь можно воспользоваться string interpolation `"$resDay.$resMonth.$resYear"`

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            count++
* Зачем считать до конца, если при любом плюсе после первого мы возвращаем пустую строку?
* Можно записать все это в функциональном стиле

2016-10-24 16:29 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (parts[i].toInt() >= max) max = parts[i].toInt()
Как данный код учитывает успешность или неуспешность попытки?

2016-10-26 20:57 UTC, AlexanderKuptsov commented on src/lesson4/task1/List.kt
> +    val listArab = listOf(1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000)
Я не очень понял, как это сделать.

2016-10-28 09:18 UTC, ice-phoenix requested changes

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun travelMinutes(hoursDepart: Int, minutesDepart: Int, hoursArrive: Int, minutesArrive: Int): Int = (hoursArrive - hoursDepart) * 60 + minutesArrive - minutesDepart
Длинные строки в Котлине принято разбивать на несколько более коротких, в данном случае, например, после знака `=` в определении функции

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return m * n / qcd(n, m)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = lcm(m, n) == m * n
Раз у вас есть функция `gcd`, может быть, было бы проще воспользоваться ей для определения взаимной простоты?

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val nSqrt = Math.ceil(Math.sqrt(n.toDouble()))
Почему вы решили нижнюю границу округлить **вниз**, а вернхнюю --- **наверх**?

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (nSqrt - mSqrt > 1 || m == 0 || n == 0 || m == 1 || n == 1) return true
Если округлить числа в правильную сторону, то это условие можно упростить

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        } else k = "1"
Почему, вместо того, чтобы исправить вашу реализацию функции `fib` и сделать ее быстрее, вы перереализовали ее здесь?

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun decimalFromString(str: String, base: Int): Int = decimal(str.map { symbolToNumber(it) }, base)
:+1: :+1: :+1:

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (str <= '9') str - '9' + 9
Можно было просто вычесть `'0'` и обойтись без `... + 9`

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            for (i in listAll.size - 1 downTo 0) {
Весь этот цикл можно заменить на `list.find{ ... }`

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var res = ""
Для подобной работы со строками лучше использовать `StringBuilder` или список строк

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val listAll = listOf(Pair("I", 1), Pair("IV", 4), Pair("V", 5), Pair("IX", 9), Pair("X", 10), Pair("XL", 40), Pair("L", 50),
Можно проще как `listOf("I" to 1, "IV" to 4, ...)`

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (phone.contains(Regex("""[^()\d\s+-]""")) || (phone.length == 1 && phone.first() == '+')) return ""
Второе условие можно записать намного проще

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (i in 1..phone.length - 1) {
Весь этот `for` можно заменить на `any / all`

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            Double.NaN
Почему так? Что возвращает ваш код в случае, если в строке встретилось неправильное число? Что он должен делать по заданию?

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    newJumps = Regex("""[\s]""").replace(newJumps, "")
Ваши регексы очень хрупкие --- если уж вы решили для фильтрации удачных попыток использовать регексы, то извольте написать регекс, который находит именно удачную попытку (число, за которым следует признак удачной попытки), а не убирать все неудачные попытки, искать числа, за которыми следуют **два пробельных символа** друг за другом, убирать их, и так далее...

Кроме такого способа можно взять и собрать список пар из попыток и их результатов, а потом уже искать нужную попытку в этом списке.

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val symbols: String
Почему вы разделили определение и объявление переменной?

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (symbols[i - 1] == '+') res += parts[i].toInt() else res -= parts[i].toInt()
Как ваше решение отреагирует, если в строке встретились два числа подряд, без знака операции между ними?

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return res
Более правильным решением этой задачи было бы идти по строке слева направо, читая по одному набору символов без пробелов (токену), и, в зависимости от значения токена, выполнять то или иное действие

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var resStr = ""
Зачем вы собираете всю строку, если в итоге используете только ее длину???

2016-10-28 09:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            Double.NaN
Почему так?

2016-10-28 09:19 UTC, ice-phoenix commented
recheck all

2016-10-28 09:34 UTC, AlexanderKuptsov commented on src/lesson3/task1/Loop.kt
> +        } else k = "1"
Я её исправил

2016-10-28 09:38 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        } else k = "1"
Ваша текущая реализация `fib` является экспоненциальной от `n`. Реализация, которую вы используете тут (из-за того, что ваш тест `fibSequenceDigit` не проходил по таймауту), является линейной. Почему вы решили влепить линейную реализацию прямо тут, а не исправить корень проблемы и не поправить функцию `fib`?

2016-10-28 14:32 UTC, AlexanderKuptsov commented on src/lesson4/task1/List.kt
> +            for (i in listAll.size - 1 downTo 0) {
Я не понимаю, что нужно здесь  сделать

2016-10-31 12:44 UTC, ice-phoenix requested changes

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i > 2) {
Зачем данная проверка? Можно ли обойтись без нее, если изменить, например, диапазон итерирования цикла?

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun qcd(n: Int, m: Int): Int {
`gcd`

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun lcm(m: Int, n: Int): Int = m * n / qcd(n, m)
:+1:

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val nSqrt = Math.floor(Math.sqrt(n.toDouble()))
Браво! :+1:

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (nSqrt - mSqrt >= 0) return true
Выражение `if (cond) return true else return false` можно заменить на `return cond`

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        convert(n, base).map { numberToSymbol(it) }.joinToString(separator = "")
:+1:

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun decimalFromString(str: String, base: Int): Int = decimal(str.map { symbolToNumber(it) }, base)
:+1:

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var res = ""
Это замечание все еще в силе

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            for (i in listAll.size - 1 downTo 0) {
Весь этот цикл можно заменить на `list.find{ ... }`

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (i in 1..phone.length - 1) {
Это можно заменить на `phone.drop(...).any{ ... }`

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (parts[i].toInt() >= max) max = parts[i].toInt()
Повторно используемые подвыражения лучше вынести в отдельные переменные

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (parts[i] != "") return -1
Почему сперва не отфильтровать все пустые строки?

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            Double.NaN
Что это делает?

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (pairs[1].contains(Regex("""[^\d.]""")) || pairs[1].toDouble() < 0) return ""
Если внезапно `pairs` --- это список с одним элементом?

2016-10-31 12:44 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (pairs[1].toDouble() >= max) {
Повторно вычисляемые выражения

2016-11-07 11:38 UTC, AlexanderKuptsov commented on src/lesson5/task1/Parse.kt
> +    for (i in 1..phone.length - 1) {
Я не понимаю, как работает .drop(...).any{ ... }. Можете пожалуйста дать подсказку?

2016-11-07 12:17 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (i in 1..phone.length - 1) {
У вас есть занятия в лабораториях и преподаватели на этих самых занятиях, у которых можно спросить все, что вас интересует

2016-11-07 12:25 UTC, AlexanderKuptsov commented on src/lesson5/task1/Parse.kt
> +    for (i in 1..phone.length - 1) {
Спасибо. Обязательно спрошу.

2016-11-07 12:35 UTC, ice-phoenix requested changes

2016-11-07 12:35 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            (c <= b && c >= a && d >= b) -> (b - c)
Можно упростить при помощи записи `c in a..b`

2016-11-07 12:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +
Пустые строки

2016-11-07 12:35 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +fun findMax(list: List<String>): Int {
Вместо этой функции можно сделать `list.filter{ it.isNotEmpty() }.map{ it.toInt() }.max()`

2016-11-15 13:38 UTC, ice-phoenix requested changes
Исправляйте замечания к предыдущим урокам перед решением следующих + исправляйте неработающие тесты

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var res = ""
Ап

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            for (i in listAll.size - 1 downTo 0) {
Ап

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    newJumps = Regex("""[\s]""").replace(newJumps, "")
Ап

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return res
Ап

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (pairs[1].contains(Regex("""[^\d.]""")) || pairs[1].toDouble() < 0) return ""
Что будет, если цена задана в формате, которые не совпадает с форматом `Double`?

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (pairs[1].toDouble() >= max) {
Повторно используемые выражения следует вынести в отдельные переменные

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            if (center.distance(other.center) > radius + other.radius) center.distance(other.center) - (radius + other.radius)
Это выражение можно упростить

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    if (points.size < 2) throw IllegalArgumentException()
Почему вы проверяете размер входа после того, как уже используете этот самый вход?

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +                max = points[i].distance(points[k])
Повторно используемые выражения следует вынести в отдельные переменные

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        val letters = listOf("a", "b", "c", "d", "e", "f", "g", "h")
Вместо этого можно просто использовать строку `"abcdefgh"`

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if (notation.isBlank() || notation[0] !in 'a'..'h' || notation[1].toInt() in 1..8) throw IllegalArgumentException()
Что будет, если `notation == "a"`?

2016-11-15 13:38 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    return Square(notation[0] - 'a' + 1, notation[1].toInt() - '0'.toInt())
Зачем `toInt()`?

2016-11-22 17:46 UTC, ice-phoenix requested changes

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun lengthInMeters(sagenes: Int, arshins: Int, vershoks: Int): Double = (sagenes * 48 + arshins * 16 + vershoks) * 0.04445
Длинные строки

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            (b in c..d && a in c..d) -> (b - a)
Подумайте над тем, как можно упростить данный набор условий через функции `max / min`

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +
Лишние пустые строки

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> + * например: n = 100, basre = 4 -> (1, 2, 1, 0) или n = 250, base = 14 -> (1, 3, 12)
???

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var res = ""
И все еще в силе

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            for (i in listAll.size - 1 downTo 0) {
Ап-ап-ап

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var number = n
Ненужный более код лучше удалить

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (parts[i + 1].contains(Regex("""[+]""")) && parts[i].toInt() > max) max = parts[i].toInt()
Форматирование кода

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..parts.size - 2) {
Может быть, стоит перебирать `i` с каким-либо шагом?

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return res
Ап-ап

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (description == "") return ""
Зачем данная проверка?

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (pairs[1].contains(Regex("""[^\d.]""")) || el < 0) return ""
Зачем первая проверка?

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        if (dist > 0.0) return dist else return 0.0
`if ... return` ==> `return if ...`

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +                diameter.begin.distance(other = diameter.end) / 2.0)
```
Circle(
    Point(
        (diameter.begin.x + diameter.end.x) / 2.0,
        (diameter.begin.y + diameter.end.y) / 2.0
    ),
    diameter.begin.distance(other = diameter.end) / 2.0
)
```

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        Line(Point((a.x + b.x) / 2.0, (a.y + b.y) / 2.0),
Форматирование (см. пример выше)

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        if (column !in 1..8 || row !in 1..8) return ""
`if ... return` ==> `return if ...`

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    if (notation.length !=2 || notation[0] !in 'a'..'h' || notation[1].toInt() in 1..8) throw IllegalArgumentException()
Форматирование кода

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +    private val listMap = mutableMapOf<Cell, E>()
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-22 17:46 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        var res = "["
`StringBuilder`

2016-11-22 17:47 UTC, ice-phoenix commented
recheck all

2016-11-22 17:48 UTC, ice-phoenix commented
recheck all

2016-11-22 17:48 UTC, ice-phoenix commented
recheck all

2016-11-23 11:49 UTC, ice-phoenix requested changes

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return if (res >= 0) res else -1
:+1:

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (count >= n) break
Почему бы не оформить этот цикл как `while`?

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (count >= n) break
См. замечание выше

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var listRes = ""
Список строк или `StringBuilder`

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (number / 100 % 10 == 0) Double.NaN
Зачем?

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val last = if (number % 10 !in 1..4) listUnits[number % 10] + " тысяч" else listThousands[number % 10]
Зачем делать так? Почему не занести варианты для 5000-9000 в `listThousands`?

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (number % 100 == 0) listRes += " тысяч"
Данное выражение лучше оформить как `when`

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (number % 100 == 0) Double.NaN
Данное выражение лучше оформить как `when`

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +
?

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +    notation.length != 2 ||
Если форматируем так, то лучше это выровнять вместе с остальными условиями ниже

2016-11-23 11:49 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        if (res == null) throw  IllegalArgumentException()
Лишние пробелы

2016-11-23 20:43 UTC, AlexanderKuptsov commented on src/lesson5/task1/Parse.kt
> +
if (el >= max) max = el  - для поиска самой высокой цены, а  mostExpensive = pairs[0] для сохранения названия продукта, соответствующего этой цене.

2016-11-25 12:43 UTC, ice-phoenix commented
recheck all

2016-11-25 13:00 UTC, ice-phoenix requested changes
:+1:

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            }
Этот цикл можно заменить на `list.find / list.findLast`

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    val listRes = StringBuilder()
Не очень хорошее название переменной

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    }
Если сможете избавиться от дублирования кода здесь, будете совсем большим молодцом =)

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +     val parts = expression.trim().split(" ")
Ненужный более код лучше удалять, он все равно сохраняется в системе контроля версий

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +
Меня тут внезапная пустая строка заинтересовала =)

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                if (col != width - 1) res.append(",")
В подобных случаях, чтобы избежать тяжелой проверки внутри цикла, обычно запятую добавляют всегда, а потом откусывают последнюю запятую из `StringBuilder`

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    if (matrix.width != matrix.height) throw  IllegalArgumentException()
Форматирование кода

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    M[0, 0] = 0
Зачем? Почему при создании матрицы не заинициализировать все нулями?

2016-11-25 13:00 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +            if (k < matrix.width - 1 && i > 0) sum += matrix[i - 1, k + 1]
Чтобы избежать всех этих проверок, обычно делают сперва отдельные циклы по сторонам матрицы (там, где может не быть каких-либо соседей), а потом уже основной цикл там, где все соседи точно есть

2016-11-28 10:32 UTC, ice-phoenix requested changes

2016-11-28 10:32 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            number -= listAll.find { number - it.second >= 0 }!!.second
Зачем два раза искать одно и то же? Почему вы используете небезопасную операцию `!!`? Можно ли обойтись без нее?

2016-11-28 10:32 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            in 10..19 -> res.append(" " + listUnits[number % 100] + " тысяч")
`StringBuilder.append(a + b + c)` лучше сделать как `append(a); append(b); append(c);`

2016-11-28 10:32 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val parts = expression.split(" ")
Как вы думаете, выполняется ли этот код?

2016-11-28 10:32 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        res.append("\n")
Зачем начинать вывод с новой строки???

2016-11-28 10:32 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                if (row != width - 1) res.append(" ")
Чтобы избежать проверки, разделители обычно добавляют всегда, а снаружи цикла последний ненужный разделитель откусывают

2016-11-28 10:32 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +        for (k in count..height - count - 2) {
Почему здесь `-2`, а в цикле выше `-1`?

2016-11-28 10:32 UTC, ice-phoenix commented on src/lesson7/task2/Matrices.kt
> +    val M = createMatrix(height, width, 1)
`camelCase`

2016-11-28 10:33 UTC, ice-phoenix commented
recheck all

2016-11-28 10:56 UTC, alv commented
Hi there,

For some reason I’ve been getting notifications from your Github project, seems that I have been mentioned by mistake, or at least Github thinks so.

Is there a way to remove me from these notifications?

Thank you!


> El 28 nov 2016, a las 11:35, kotlin-polytech-bot <notifications@github.com> escribió:
> 
> author
> 
> AlexanderKuptsov [shon55398@gmail.com]
> 
> lesson1.task1
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 12 / 12
> 
> Example: 4 / 4
> Trivial: 4 / 4
> Easy: 4 / 4
> 
> Succeeded:
> 
> [Trivial] lesson1.task1/seconds
> [Example] lesson1.task1/discriminant
> [Example] lesson1.task1/sqRoot
> [Example] lesson1.task1/sqr
> [Trivial] lesson1.task1/trackLength
> [Trivial] lesson1.task1/lengthInMeters
> [Trivial] lesson1.task1/angleInRadian
> [Easy] lesson1.task1/thirdDigit
> [Easy] lesson1.task1/travelMinutes
> [Example] lesson1.task1/quadraticRootProduct
> [Easy] lesson1.task1/accountInThreeYears
> [Easy] lesson1.task1/numberRevert
> Seed: -5092252395349062980
> 
> lesson2.task1
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 7 / 7
> 
> Example: 1 / 1
> Easy: 5 / 5
> Normal: 1 / 1
> 
> Succeeded:
> 
> [Example] lesson2.task1/minBiRoot
> [Easy] lesson2.task1/ageDescription
> [Easy] lesson2.task1/timeForHalfWay
> [Easy] lesson2.task1/whichRookThreatens
> [Easy] lesson2.task1/rookOrBishopThreatens
> [Easy] lesson2.task1/triangleKind
> [Normal] lesson2.task1/segmentLength
> Seed: -5092252395349062980
> 
> lesson2.task2
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 5 / 5
> 
> Example: 1 / 1
> Easy: 2 / 2
> Normal: 2 / 2
> 
> Succeeded:
> 
> [Example] lesson2.task2/pointInsideCircle
> [Easy] lesson2.task2/isNumberHappy
> [Easy] lesson2.task2/queenThreatens
> [Normal] lesson2.task2/circleInside
> [Normal] lesson2.task2/brickPasses
> Seed: -5092252395349062980
> 
> lesson3.task1
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 16 / 18
> 
> Example: 4 / 4
> Trivial: 1 / 1
> Easy: 6 / 8
> Normal: 3 / 3
> Hard: 2 / 2
> 
> Succeeded:
> 
> [Example] lesson3.task1/factorial
> [Easy] lesson3.task1/lcm
> [Easy] lesson3.task1/minDivisor
> [Easy] lesson3.task1/maxDivisor
> [Example] lesson3.task1/isPrime
> [Example] lesson3.task1/isPerfect
> [Example] lesson3.task1/digitCountInNumber
> [Trivial] lesson3.task1/digitNumber
> [Easy] lesson3.task1/fib
> [Easy] lesson3.task1/isCoPrime
> [Easy] lesson3.task1/squareBetweenExists
> [Normal] lesson3.task1/revert
> [Normal] lesson3.task1/isPalindrome
> [Normal] lesson3.task1/hasDifferentDigits
> [Hard] lesson3.task1/squareSequenceDigit
> [Hard] lesson3.task1/fibSequenceDigit
> Seed: -5092252395349062980
> 
> lesson4.task1
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 21 / 21
> 
> Example: 7 / 7
> Easy: 2 / 2
> Normal: 7 / 7
> Hard: 4 / 4
> Impossible: 1 / 1
> 
> Succeeded:
> 
> [Normal] lesson4.task1/convert
> [Example] lesson4.task1/buildSumExample
> [Example] lesson4.task1/invertPositives
> [Example] lesson4.task1/sqRoots
> [Example] lesson4.task1/negativeList
> [Example] lesson4.task1/biRoots
> [Example] lesson4.task1/squares
> [Easy] lesson4.task1/mean
> [Normal] lesson4.task1/factorize
> [Normal] lesson4.task1/polynom
> [Normal] lesson4.task1/times
> [Normal] lesson4.task1/center
> [Example] lesson4.task1/isPalindrome
> [Normal] lesson4.task1/accumulate
> [Hard] lesson4.task1/decimalFromString
> [Hard] lesson4.task1/roman
> [Impossible] lesson4.task1/russian
> [Hard] lesson4.task1/factorizeToString
> [Hard] lesson4.task1/convertToString
> [Normal] lesson4.task1/decimal
> [Easy] lesson4.task1/abs
> Seed: -5092252395349062980
> 
> lesson5.task1
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 10 / 12
> 
> Example: 2 / 2
> Normal: 3 / 3
> Hard: 5 / 7
> 
> Succeeded:
> 
> [Example] lesson5.task1/timeSecondsToStr
> [Normal] lesson5.task1/dateStrToDigit
> [Normal] lesson5.task1/dateDigitToStr
> [Hard] lesson5.task1/flattenPhoneNumber
> [Normal] lesson5.task1/bestLongJump
> [Hard] lesson5.task1/bestHighJump
> [Hard] lesson5.task1/plusMinus
> [Hard] lesson5.task1/firstDuplicateIndex
> [Hard] lesson5.task1/mostExpensive
> [Example] lesson5.task1/timeStrToSeconds
> Seed: -5092252395349062980
> 
> lesson6.task1
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 13 / 16
> 
> Example: 4 / 4
> Trivial: 1 / 1
> Easy: 2 / 2
> Normal: 5 / 6
> Hard: 1 / 1
> Impossible: 0 / 2
> 
> Succeeded:
> 
> [Example] lesson6.task1/halfPerimeter
> [Normal] lesson6.task1/diameter
> [Easy] lesson6.task1/circleByDiameter
> [Normal] lesson6.task1/lineBySegment
> [Hard] lesson6.task1/bisectorByPoints
> [Normal] lesson6.task1/findNearestCirclePair
> [Easy] lesson6.task1/circleDistance
> [Example] lesson6.task1/pointDistance
> [Trivial] lesson6.task1/circleContains
> [Example] lesson6.task1/triangleArea
> [Example] lesson6.task1/triangleContains
> [Normal] lesson6.task1/lineByPoint
> [Normal] lesson6.task1/lineByPoints
> Seed: -5092252395349062980
> 
> lesson6.task2
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 5 / 11
> 
> Example: 1 / 1
> Easy: 4 / 4
> Normal: 0 / 2
> Hard: 0 / 3
> Impossible: 0 / 1
> 
> Succeeded:
> 
> [Easy] lesson6.task2/bishopMoveNumber
> [Easy] lesson6.task2/square
> [Easy] lesson6.task2/notation
> [Easy] lesson6.task2/rookMoveNumber
> [Example] lesson6.task2/inside
> Seed: -5092252395349062980
> 
> lesson7.task1
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 3 / 3
> 
> Easy: 1 / 1
> Normal: 2 / 2
> 
> Succeeded:
> 
> [Easy] lesson7.task1/createMatrix
> [Normal] lesson7.task1/getSetString
> [Normal] lesson7.task1/getSetInt
> Seed: -5092252395349062980
> 
> lesson7.task2
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 5 / 15
> 
> Example: 2 / 2
> Easy: 0 / 1
> Normal: 2 / 5
> Hard: 1 / 6
> Impossible: 0 / 1
> 
> Succeeded:
> 
> [Example] lesson7.task2/plus
> [Example] lesson7.task2/transpose
> [Hard] lesson7.task2/generateRectangles
> [Normal] lesson7.task2/sumNeighbours
> [Normal] lesson7.task2/rotate
> Seed: -5092252395349062980
> 
> owner
> 
> AlexanderKuptsov []
> 
> total
> 
> Author: AlexanderKuptsov [shon55398@gmail.com]
> 
> Owner: AlexanderKuptsov []
> 
> Total: 101 / 136
> 
> Example: 30 / 30
> Trivial: 6 / 6
> Easy: 26 / 29
> Normal: 25 / 38
> Hard: 13 / 26
> Impossible: 1 / 7
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/98#issuecomment-263237617>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAEJfy46pnlaDBgw8hg4l3X8wXkRHDmsks5rCq5vgaJpZM4KDrNh>.
>

2016-11-28 11:48 UTC, mglukhikh commented
@alv Hi! I think we cannot do it ourselves. But you, in turn, should be able to control notifications. May be this link will help you: https://help.github.com/articles/managing-notifications/#unsubscribe-from-a-notification-in-a-repository.

2016-11-28 11:52 UTC, alv commented
Thanks, done! Good luck with your project!

> El 28 nov 2016, a las 12:48, Mikhail Glukhikh <notifications@github.com> escribió:
> 
> @alv <https://github.com/alv> Hi! I think we cannot do it ourselves. But you, in turn, should be able to control notifications. May be this link will help you: https://help.github.com/articles/managing-notifications/#unsubscribe-from-a-notification-in-a-repository <https://help.github.com/articles/managing-notifications/#unsubscribe-from-a-notification-in-a-repository>.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Kotlin-Polytech/KotlinAsFirst2016/pull/98#issuecomment-263251651>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAEJf7EPc66kCbQO-d_OGuCvNP2m9KDIks5rCr-NgaJpZM4KDrNh>.
>

2016-11-28 15:04 UTC, AlexanderKuptsov commented on src/lesson7/task1/Matrix.kt
> +        res.append("\n")
Так, мне кажется,  выглядит лучше. Могу убрать

2016-11-28 20:20 UTC, AlexanderKuptsov commented on src/lesson7/task2/Matrices.kt
> +        for (k in count..height - count - 2) {
Это для того, чтобы лишний раз не перебирать угловые эл-ты.

2016-12-01 12:01 UTC, AlexanderKuptsov commented on src/lesson5/task1/Parse.kt
> +    val parts = expression.split(" ")
Должен.
Если нет "+" или "-" и нет пробелов, то выводится результат(входная строка)
Если нет "+" или "-", но есть пробел(ы), то будет исключение 
Или лучше изменить данный код?

2016-12-05 11:25 UTC, ice-phoenix commented
recheck all

2016-12-05 11:42 UTC, ice-phoenix requested changes

2016-12-05 11:42 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            res += search?.first
Почему здесь не указали значение для `null`? Если мы не нашли соответствующее значение в нашем списке, что это значит? Может быть, имеет смысл сделать что-то для случая, когда `search == null`?

2016-12-05 11:42 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val parts = expression.split(" ")
Его лучше изменить, потому что я (как и сторонний программист сделал бы) совсем не заметил одинокого `Double.NaN` в первом `if`. Так никогда не делают. Вам надо подумать, что именно является признаками ошибки формата, и явно записать именно их.

2016-12-05 11:42 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var res: Int
Объявление этой переменной и `return` можно убрать внутрь блока `try`

2016-12-05 11:42 UTC, ice-phoenix commented on src/lesson6/task2/Chess.kt
> +        else letters[column - 1] + row.toString()
Этот блок `else` лучше слегка оттабулировать вправо

2016-12-07 15:59 UTC, ice-phoenix commented
recheck all

2016-12-07 16:24 UTC, ice-phoenix requested changes

2016-12-07 16:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    else {
Тут можно без блока `else`, потому что мы выходим из функции в `then`

2016-12-07 16:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            if (search == null) search = "" to 0
Вообще, данная ситуация говорит о том, что что-то пошло совсем не так

2016-12-07 16:24 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else -> res.append(" " + (if (number % 100 in 20..99) listDes[(number % 100) / 10] + " " else "") + unit)
Все отдельные компоненты результирующей строки лучше выносить в отдельные переменные с нормальными именами

2016-12-07 16:24 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (parts[i + 1].contains(Regex("""[+]""")) && parts[i].toInt() > max) max = parts[i].toInt()
Узнать, есть ли `+` в строке, можно чуть попроще без использования регексов

2016-12-07 16:24 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (expression.contains(Regex("""[\s]""")) && !expression.contains(Regex("""[-+]"""))) throw IllegalArgumentException()
Что проверяет эта проверка?

2016-12-07 16:24 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        res = parts[0].toInt()
Зачем вы разделили определение и объявление этой переменной?

2016-12-07 16:24 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (pairs.size <= 1) return ""
А если там три части?

2016-12-08 12:50 UTC, mglukhikh commented
recheck assignment

2016-12-08 12:53 UTC, mglukhikh commented
8 урок: решение sibilants по факту отсутствует. countSubstrings иногда проходит тесты, иногда нет -- как повезёт.

2016-12-13 13:03 UTC, mglukhikh commented
recheck all

2016-12-13 13:19 UTC, mglukhikh commented
Не проходит единственный тест, разница -- в лишнем переводе строки в конце файла

2016-12-13 14:42 UTC, mglukhikh commented
Уберите, пожалуйста, закомментированный код в `sibilants`

2016-12-13 15:02 UTC, mglukhikh commented
Тест `centerFile` мигает (судя по всему, проходит на большей части случайных примеров, но не на всех). Посмотрите ещё на замечания, оставшиеся в Files Changed (и либо исправьте их, либо объясните, почему не хотите исправлять).

2016-12-20 07:33 UTC, AlexanderKuptsov commented
Здравствуйте, что мне нужно ещё сделать или исправить, чтобы получить автомат. Или просто можно подойти?

2016-12-20 07:51 UTC, ice-phoenix commented
Можно просто подойти к преподавателю на зачетной неделе =)

2016-12-20 07:53 UTC, AlexanderKuptsov commented
Круто! А сегодня можно?

2016-12-20 07:56 UTC, ice-phoenix commented
Если сегодня есть занятие, то можно.

2016-12-20 08:00 UTC, AlexanderKuptsov commented
Ну по расписанию сегодня есть занятие, только аудитория закрыта.

2016-12-20 08:12 UTC, ice-phoenix commented
Упражнения, вестимо. Лекции на зачетной неделе обычно не читаются.

2016-12-20 08:13 UTC, AlexanderKuptsov commented
Понял, спасибо!

2017-07-26 18:24 UTC, closed without merging