123
Kotlin-Polytech/KotlinAsFirst2016 pull request #99
Opened 2016-09-22 09:11 UTC by Gast9ra

2016-09-22 10:02 UTC, ice-phoenix commented
Просьба давать PR осмысленное имя, соответствующее его содержанию

2016-09-22 10:25 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (hours * 3600 + minutes * 60 + seconds)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-22 10:25 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((vershoks * 4.445 + arshins * 16 * 4.445 + sagenes * 48 * 4.445) / 100)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-22 10:25 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((grad + ((min + sec / 60.0) / 60.0)) * Math.PI / 180)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-22 10:25 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (sqrt(sqr(x2 - x1) + sqr(y2 - y1)))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-22 10:26 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val number = number / 100
Называть локальную переменную так же, как аргумент функции, --- **очень плохой** стиль

2016-09-22 10:27 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return ((hoursArrive - hoursDepart) * 60 + (minutesArrive - minutesDepart))
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-22 10:27 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val initial = initial * (percent / 100.0 + 1) * (percent / 100.0 + 1) * (percent / 100.0 + 1)
Повторно вычисляемые выражения лучше вынести в отдельные переменные

2016-09-22 10:28 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    return (number % 10 * 100 + (number / 10 % 10) * 10 + number / 100)
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-09-22 10:28 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((age % 10 >= 5) && (age % 10 <= 9)) || (age % 10 == 0) || ((age >= 10) && (age <= 12))) return ("$age лет")
Данное выражение лучше оформить как `when`

2016-09-22 10:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((((t1 * v1) + (t2 * v2) + (t3 * v3)) / 2) < (t1 * v1)) return ((((t1 * v1) + (t2 * v2) + (t3 * v3)) / 2) / v1)
Отдельные осмысленные подвыражения следует вынести в переменные с говорящими именами. Разобраться в таком частоколе скобочек совсем непросто.

2016-09-22 10:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((((kingX == rookX1) || (kingY == rookY1)) && ((kingX == rookX2) || (kingY == rookY2)))) return 3
Подвыражения, отвечающие за факт атаки короля той или иной фигурой, следует вынести в отдельные переменные

2016-09-22 10:29 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((kingX == rookX) || (kingY == rookY)) && (((Math.abs(kingX - bishopX)) == (Math.abs(kingY - bishopY))))) return 3
Подвыражения, отвечающие за факт атаки короля той или иной фигурой, следует вынести в отдельные переменные

2016-09-22 10:30 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((a + b > c) && (a + c > b) && (c + b > a)) {
Логика данной функции будет проще, если сперва найти максимальную сторону треугольника, а потом все считать относительно нее

2016-09-22 10:30 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (c <= a && d >= b) q = (b - a) else
Данное выражение лучше оформить как `when`

2016-09-22 10:30 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((number % 10 + number / 10 % 10) == (number / 100 % 10 + number / 1000)) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-22 10:30 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) + r1) <= r2) return true
Выражение `if (cond) true else false` можно заменить на `cond`

2016-09-22 10:31 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if (((a <= r) && (b <= s)) || ((a <= s) && (b <= r)) || ((a <= r) && (c <= s)) || ((a <= s) && (a <= r)) || ((c <= r) && (b <= s)) || ((c <= s) && (b <= r))) return true
Лучше сперва найти две минимальные стороны кирпича, а потом все проверять относительно них

2016-09-22 10:31 UTC, ice-phoenix requested changes

2016-09-22 11:17 UTC, mglukhikh commented
recheck all

2016-09-23 08:29 UTC, ice-phoenix commented
Название PR `123` никак не говорит о том, что было сделано

2016-09-23 08:33 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n==i*(n/i))  {
* В Kotlin есть более хороший способ проверить, делится ли число на другое число без остатка
* Нет ли более точной границы сверху для максимально возможного делителя `n`, чем `n`?

2016-09-23 08:34 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n==i*(n/i)){
См. замечание к `minDivisor`

2016-09-23 08:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((m%i==0)&&(n%i==0)) return(false)
Нельзя ли эту функцию выразить через другие функции этого модуля?

2016-09-23 08:35 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i*i in m..n) return true
Подумайте над тем, как можно реализовать это более быстрым алгоритмом

2016-09-23 08:36 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var sinus:Double=x
* Система типов Котлина выведет тип переменной автоматически

2016-09-23 08:36 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return t.toString().toInt()
Зачем у строки вызывать `toString()`?

2016-09-23 08:37 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun hasDifferentDigits(n: Int): Boolean = if ((n.toString().filter {it == n.toString()[0] })!=(n.toString())) true else false
Повторно вычисляемые выражения лучше вынести в отдельную переменную

2016-09-23 08:38 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        result = result + (num * num).toString()
Оцените размер строки `result` для `n = 1000000`. Как вы думаете, такая строка поместится в оперативную память вашего компьютера?

2016-09-23 08:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number=0
Форматирование кода должно быть единообразным

2016-09-23 08:40 UTC, ice-phoenix requested changes

2016-09-23 08:40 UTC, ice-phoenix commented
Просьба исправить все замечания перед следующими PR

2016-09-29 09:39 UTC, ice-phoenix requested changes
Убедительная просьба перед отправкой нового PR исправлять **все** замечания к предыдущим

2016-09-29 09:39 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int=(hours * 3600 + minutes * 60 + seconds)
[Здесь и далее] Отформатируйте код при помощи IntelliJ IDEA и в дальнейшем старайтесь придерживаться такого же стиля кодирования

2016-09-29 09:39 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun accountInThreeYears(initial: Int, percent: Int): Double= initial * (percent / 100.0 + 1) * (percent / 100.0 + 1) * (percent / 100.0 + 1)
Повторно используемые выражения лучше вынести в отдельные переменные

2016-09-29 09:39 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (((age % 10 >= 5) && (age % 10 <= 9)) || (age % 10 == 0) || ((age%100 >= 10) && (age%100 <= 19))) return ("$age лет")
Данное выражение лучше оформить как `when`

2016-09-29 09:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((m%i==0)&&(n%i==0)) return(false)
Можно ли реализовать проверку на взаимную простоту при помощи других функций, реализованных вами в данном модуле?

2016-09-29 09:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i*i in m..n) return true
Можно ли найти более точные границы для перебора возможных значений точного квадрата между `m` и `n`?

2016-09-29 09:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var t:String=""
* Система типов Котлина выведет тип переменной автоматически
* Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-09-29 09:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n/10==0) return true
Можно ли реализовать эту функцию через другие функции данного модуля?

2016-09-29 09:39 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var resalt=0
`result`

2016-09-29 18:17 UTC, ice-phoenix commented
Ваши задачи не будут проверятся (и учитываться как решенные) до тех пор, пока вы не исправите замечания к предыдущим.

2016-10-13 13:20 UTC, ice-phoenix requested changes
Идем на вкладку `Files changed`, изучаем замечания и исправляем их перед продолжением работы

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int=(hours * 3600 + minutes * 60 + seconds)
[Здесь и далее] Форматирование кода

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +            return initial * persentforyea*persentforyea*persentforyea
Почему `return` решил пойти направо?

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val persentforyea =percent / 100.0 + 1
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде; желательно без ошибок

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val FirstPartWay=t1*v1
Переменные в Котлине принято называть с маленькой буквы

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val halfallway=(t1*v1+t2*v2+t3*v3)/2
Почему внезапно вы решили форматировать код без пробелов между операторами и их операндами? Форматирование должно быть единообразным **везде**.

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (halfallway < (FirstPartWay)) return ((halfallway) / v1)  //есди первый отрезок
Данное выражение лучше оформить как `when`

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val firstrook:Boolean=(kingX==rookX1)|| (kingY==rookY1)
* Система типов Котлина выведет тип переменной автоматически

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((firstrook) && (Secondrook)) return 3 //от 2
Данное выражение лучше оформить как `when`

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val rook:Boolean=(kingX==rookX)|| (kingY==rookY)
* Система типов Котлина выведет тип переменной автоматически

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if (rook && bishop) return 3
Данное выражение лучше оформить как `when`

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +fun isNumberHappy(number: Int): Boolean=if ((number % 10 + number / 10 % 10) == (number / 100 % 10 + number / 1000)) true else  false
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((x1 == x2) || (y2 == y1)) return true
Данное выражение лучше оформить как `when`

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    if ((Math.sqrt(sqr(x2 - x1) + sqr(y2 - y1)) + r1) <= r2)  true else false
Выражение `if (cond) true else false` можно заменить на `cond`

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +    return when{
Все это можно заменить на выражение, состоящее из условий вашего `when`, соединенных через логическое ИЛИ

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        var counter: Int = 0
* Система типов Котлина выведет тип переменной автоматически

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var fibnach1:Int=1
* Система типов Котлина выведет тип переменной автоматически

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun nod(a: Int,b: Int): Int{
`nod ==> gcd`

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean=(nod(m,n)>Math.min(m,n))||(nod(m,n)==1)
Убедительная просьба здесь и везде внимательно относиться к форматированию кода. Вы в первую очередь пишете код для того, чтобы его потом **читали другие разработчики**.

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun quantity(n: Int): Int {
Нет ли уже реализованной вами функции, которая делает именно это?

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result:Double=0.0
* Система типов Котлина выведет тип переменной автоматически

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        return all/len.toDouble()
Зачем `toDouble()`?

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val len: Int = list.size
* Система типов Котлина выведет тип переменной автоматически

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +return list
Почему `return` внезапно решил сходить налево?

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            else->{
Неужели нет других простых чисел, кроме перечисленных вами здесь?

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result:String=""
Эту функцию можно намного проще выразить через `factorize`

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list = listOf()
Зачем вы разделили определение и объявление переменной?

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (list[i] > 9) string1+=(87 + list[i]).toChar()
Вместо 87 лучше использовать соответствующий символ

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (n==0) string1=""
Форматирование кода везде и всегда должно быть единообразным

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in (digits.size-1) downTo 0) result+=(digits[i]*Math.pow(base.toDouble(),((digits.size-1)-i).toDouble())).toInt()
В данном случае тело цикла лучше вынести на отдельную строку

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (string1[i] in '0'..'9') list+=((string1[i]).toInt()-48)
Вместо 48 лучше использовать соответствующий символ

2016-10-13 13:20 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val num:Int=n1%10
* Система типов Котлина выведет тип переменной автоматически

2016-10-24 12:05 UTC, ice-phoenix requested changes
Исправляем замечания и продолжаем работать

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val persentforyear = percent / 100.0 + 1
Переменные в Kotlin принято называть `camelCase`'ом

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (age % 10 >= 2) && (age % 10 <= 4) -> "$age года"
Условия лучше перечислять в порядке, имеющем какой-то смысл, --- в данном случае, например, в порядке увеличения последней цифры рассматриваемого возраста

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val halfallway = (t1 * v1 + t2 * v2 + t3 * v3) / 2
`camelCase`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    val firstrook = (kingX == rookX1) || (kingY == rookY1)
`camelCase`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        rook && bishop->3
Пожалуйста, относитесь к форматированию вашего кода таким образом, будто его будет читать психопат-маньяк-убийца с обсессивно-компульсивным расстройством по поводу правильной расстановки пробелов и форматирования, который знает, где вы живете, и имеет доступ к широкому арсеналу пыточных и других инструментов, способных принести вам много страданий или окончить вашу жизнь предварительно.

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((a + b > c) && (a + c > b) && (c + b > a)) {
Это замечание все еще в силе

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +            (x1 == x2) || (y2 == y1) -> true
Это можно записать проще, если вспомнить, каким образом можно комбинировать логические условия в Котлине

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +            (a <= r && b <= s) -> true
Это можно записать проще, если вспомнить, как комбинируются логические условия в Котлине

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (a != 0) return (nod(b % a, a))
[Здесь и много где] Лишние скобки вокруг законченного выражения

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return ((m / (nod(m, n))) * n)
Лучше `m * n / gcd(m, n)`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun nod(a: Int, b: Int): Int {
`nod ==> gcd`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n == i * (n / i)) {
Для проверки того, делится ли число нацело на другое или нет, в Котлин существует специальная операция

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Нет ли более точной границы сверху для максимально возможного делителя числа, чем `n`?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in n - 1 downTo 1) {
См. замечания к `minDivisor`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isCoPrime(m: Int, n: Int): Boolean = (nod(m, n) > Math.min(m, n)) || (nod(m, n) == 1)
Зачем первое условие?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +/**
Устаревшие комментарии не следует оставлять в коде

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (i * i in m..n) return true
Нет ли более простого способа найти число, **квадрат** которого лежит между двумя другими числами, чем перебирать все от 0 до `n`?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (counter % 2 == 1) sinus = sinus - number
`sinus -= number`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var sinus: Double = x
- Система типов Котлина выведет тип переменной автоматически

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var t: String = ""
- Система типов Котлина выведет тип переменной автоматически

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return t.toString().toInt()
Зачем `String.toString()`?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var number: Double = x
- Система типов Котлина выведет тип переменной автоматически

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if (n / 10 == 0) return true
Есть более простой способ проверить то, что вы хотите здесь проверить

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val firstnumber: Int = n % 10
`camelCase`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val firstnumber: Int = n % 10
- Система типов Котлина выведет тип переменной автоматически

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    nforwhile = 1
Нет ли у вас уже написанной функции, которая может посчитать вам значение `counter`?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    if ((firstnumber == revertnumfirst) && (secondnumber == revertnumsecond)) return true
Неужели этого достаточно для проверки того, является ли число палиндромом?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun hasDifferentDigits(n: Int): Boolean = if ((n.toString().filter { it == n.toString()[0] }) != (n.toString())) true else false
Эту задачу следует решить линейным проходом по строке без создания промежуточных строк

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var r = 0
Нет ли у вас уже написанной функции, которая делает то же, что делает ваша функция `quantity`?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var resalt = 0
`result`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var resalt = 0
`result`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        result += v[i] * v[i]
В случае, если вам не нужно явное значение индекса, лучше воспользоваться циклом в `foreach` стиле

```
for (element in list) {
    foo(element)
}
```

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            all += list[i]
См. замечание выше

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        list[i] -= midlelist
См. замечание выше

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Зачем эта проверка? Сколько раз будет выполнено тело цикла `for` в случае, если список пустой?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +                scalar += a[i] * b[i]
См. замечание выше про `foreach`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (p.isEmpty()) 0.0
Зачем эта проверка?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (list.isEmpty()) list
Зачем эта проверка?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var delitet: Int = 1
Использовать транслит в именах переменных --- **очень плохой** стиль

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var n1: Int = n
- Система типов Котлина выведет тип переменной автоматически

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list = listOf()
Почему вы разделили объявление и определение переменной?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: List<Int>
Почему вы где-то используете `MutableList`, а где-то `List`???

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var string1: String = ""
- Система типов Котлина выведет тип переменной автоматически

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (list[i] > 9) string1 += (87 + list[i]).toChar()
Вместо 87 лучше воспользоваться соответствующим символом

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var string1: String = ""
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in (digits.size - 1) downTo 0) result += (digits[i] * Math.pow(base.toDouble(), ((digits.size - 1) - i).toDouble())).toInt()
Напишите функцию `pow`, работающую в целых числах

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return decimal(list, base)
См. замечания к `decimal`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result: String = ""
- Система типов Котлина выведет тип переменной автоматически
- Для соединения строк друг с другом следует воспользоваться `StringBuilder`

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        when {   //translate number
Почему не `when (counter) { ... }`?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            else -> {
Мы не поддерживаем перевод пятизначных чисел в римскую систему счисления?

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var result: String = ""
* Система типов Котлина выведет тип переменной автоматически

2016-10-24 12:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (parse[0].toInt() in 1..9) result += "0" + parse[0].toInt().toString() + "."
Результаты сплита лучше сразу вытащить в отдельные переменные с правильными типами

2016-10-27 19:21 UTC, ice-phoenix requested changes

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +        (age % 10 >= 2) && (age % 10 <= 4) -> "$age года"
Можно упростить через `a in b..c`

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            ||(kingY==rookY)
Почему внезапно новая строка?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
Это замечание все еще в силе

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in n - 1 downTo 1) {
Это замечание все еще в силе

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (sqrtResult % 1 == 0.0) {
Проверять числа с плавающей запятой на целочисленность - очень плохая идея. Переделайте ваш алгоритм так, чтобы он искал целое число, квадрат которого попадает в нужные границы.

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val x1=x % (2 * Math.PI)
Форматирование кода

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var t = ""
В условии задачи сказано, что строки использовать нельзя

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val x1=x % (2 * Math.PI)
Форматирование кода

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if ((n.toString().filter { it == n.toString()[0] }) != (n.toString())) true else false
Перепишите функцию так, чтобы она выполнялась за один проход по строке

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (list.isEmpty()) return list
Это замечание все еще в силе

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (p.isEmpty()) 0.0
Ап

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            var gap: Double = 0.0
- Система типов Котлина выведет тип переменной автоматически

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result: List<Int>
Зачем вы разделили определение и объявление переменной?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            while ((n1!=0)&&(n1 % divider) == 0) {
Форматирование кода

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in (digits.size - 1) downTo 0) result += (digits[i] * Math.pow(base.toDouble(), ((digits.size - 1) - i).toDouble())).toInt()
Это замечание все еще в силе

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list = convert(n, base)
Зачем вы разделили определение и объявление переменной?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (n == 0) str1 = ""
Зачем?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (list[i] > 9) str1 += (87 + list[i]).toChar()
Что такое 87?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    return str1
Для таких задач вместо строки лучше использовать список строк или `StringBuilder`

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    list = listOf()
Зачем вы разделили определение и объявление переменной?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var str1= str
Зачем???

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +                println("error")
Об ошибке необходимо сигнализировать либо возвращаемым значением, либо исключением, но никак не выводом в консоль

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (counter===4) return result.reversed()
Почему так?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var result = ""
`StringBuilder`

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    }
Все это можно заменить на `any / all`

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (result[0] != '+') {
Почему так?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    }
`any / all`

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            if (max < text[i].toInt()) max = text[i].toInt()
Повторно вычисляемые выражения следует вынести в переменные

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            null
Почему `null`?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        var string = jumps.split(" ")
Очень неудачное название для переменной, которое совершенно не отражает ее суть

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    for (i in 0..str.length - 1) if (str[i] == '+') return true
`any`

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (maxI == -1) return -1 else return string[maxI].toInt()
Зачем вам две переменные, указывающие на максимальную высоту?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return throw IllegalArgumentException("IllegalArgumentException")
`any / all`

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var resultExpression = expression
Зачем?

2016-10-27 19:21 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                else result += parts[i].toInt()
Если в строке два числа подряд, что вернет ваш код?

2016-10-27 19:47 UTC, gagarski commented
recheck assignment

2016-11-18 14:13 UTC, ice-phoenix commented
Жду исправления остальных замечаний

2016-11-22 18:14 UTC, ice-phoenix requested changes
Очень много неисправленных ранее замечаний

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun seconds(hours: Int, minutes: Int, seconds: Int): Int = (hours * 3600 + minutes * 60 + seconds)
Здесь и много где --- лишние скобки вокруг законченных выражений

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val persentForYear = percent / 100.0 + 1
`percentPerYear`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    //(age % 100 >= 10) && (age % 100 <= 19) -> "$age лет"
Ненужный более код нужно удалять

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            || (kingY == rookY)
Почему внезапно решили на новой строке это написать вы?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    if ((a + b > c) && (a + c > b) && (c + b > a)) {
+

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +    return when {
Функцию с телом в виде одного `return expr` можно записать как `fun foo(...) = expr`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        (a <= r && b <= s) ||
Проще сперва найти две минимальные стороны, а потом все считать относительно них

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in 2..n) {
+

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    for (i in n - 1 downTo 1) {
+

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (sqrtResult % 1 == 0.0) {
+

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var sinus = x1
`sine`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +var t = ""
Старый код

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var cosus = 1.0
`cosine`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return cosus % (2 * Math.PI)
Зачем? Что это вообще делает???

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +fun isPalindrome(n: Int): Boolean = revert(n)==n
Форматирование кода

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    val firstNumber = n % 10
Старый код

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +  ((n.toString().filter { it == n.toString()[0] }) != (n.toString()))
Эта задача должна быть решена через старый добрый цикл `for`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var resalt = 0
Почему данная переменная объявлена здесь?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    result = fib(i)
См. замечания выше

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    } catch (e: Exception) {
Зачем???

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val midllelist = mean(list)
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        } catch (e: Exception) {
Зачем???

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (list.isEmpty()) list
+

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            var gap: Double = 0.0
* Система типов Котлина выведет тип переменной автоматически

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result: List<Int> = listOf()
* Система типов Котлина выведет тип переменной автоматически

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        while ((n1 != 0) && (n1 % divider) == 0) {
Зачем первая часть проверки?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        //if (list[i] > 9) str1 += (87 + list[i]).toChar()
Магические константы

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: List<Int>
Почему вы разделили определение и объявление переменной?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    if (n == 0) return str1.toString()
Зачем эта проверка?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in (digits.size - 1) downTo 0) result += (digits[i] * Math.pow(base.toDouble(), ((digits.size - 1) - i).toDouble())).toInt()
+

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +fun powInt(num: Int, b: Int): Int {//функция степени ,не готова
Эта функция должна называться `pow`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var list: List<Int> = listOf()
* Система типов Котлина выведет тип переменной автоматически

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var str1 = str
Зачем???

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else list += ((str1[i]).toInt() - 87)
Магические константы

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var result = ""
`StringBuilder`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        val num: Int = n1 % 10
* Система типов Котлина выведет тип переменной автоматически

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +                    (num > 5) && (num < 9) -> {
Можно проще через `in a..b`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +                    (num >= 1) && (num <= 3) -> {
Можно проще через `in a..b`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (counter == 4) return result.reversed() //revers из-за прохода с конца
Зачем?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            else result += parse[0].toString() + "."
`String.padStart(...)`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var result = ""
См. замечания выше

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (phone.isEmpty()) return "" //проверка условий
Зачем эта проверка?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if ((parts[0] == "-") || (parts[0] == "+"))
Зачем данная проверка?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if ((littleReg[i] == littleReg[i + 1]) && (littleReg[i] != "")) return summ
Лучше сперва отфильтровать пустые строки

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var result =""
Форматирование кода

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val maxNum = Regex("[0-9.]+").findAll(description).map { it.value.toDouble() }.max() // нахождение макс числа
Если описание товара содержит число, как будет работать ваш код?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        var string = description.split("; ") //split по покупкам
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: Exception) {
Необходимо ловить наиболее специфичный тип исключения, а не все подряд

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val font_rom = listOf("I", "IV", "V", "IX", "X", "XL", "L", "XC", "C", "CD", "D", "CM", "M")
`camelCase`

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val font_ar = listOf(1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000)
Список пар, а не два списка

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (roman.isEmpty()) return 0
Является ли пустая строка валидным римским числом?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var posit = 0
Переменным лучше давать осмысленные имена, соответствующие их назначению в коде

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (roman.length == 1) { //когда один символ
Зачем данный случай обрабатывать отдельно?

2016-11-22 18:14 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (roman.substring(posit, font_rom[n].length + posit) == font_rom[n]) {
Лучше через `String.startsWith(...)`

2016-11-22 18:14 UTC, ice-phoenix commented on tutorial/chapter04.adoc
> +http://[.line-through]#``и мы вынуждены записать вызов функции более подробно -- `listOf<Double>()`, указывая __типовой аргумент__ `<Double>`
???

2016-11-22 20:18 UTC, Gast9ra commented on src/lesson2/task1/IfElse.kt
> +            || (kingY == rookY)
так выглядит лучше

2016-11-23 10:19 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +            || (kingY == rookY)
Почему вы тогда не используете этот лучший стиль везде в своем коде?

2016-11-23 16:59 UTC, Gast9ra commented on src/lesson3/task1/Loop.kt
> +    return cosus % (2 * Math.PI)
Иначе не заходит по тестам

2016-11-24 09:40 UTC, Gast9ra commented on src/lesson4/task1/List.kt
> +        if (counter == 4) return result.reversed() //revers из-за прохода с конца
Это решение стоит чтобы при большом количестве 'M' выводило правильно .

2016-11-24 10:11 UTC, Gast9ra commented on src/lesson5/task1/Parse.kt
> +    if (phone.isEmpty()) return "" //проверка условий
Если строка пустая ,то это не верный формат

2016-11-24 12:18 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (phone.isEmpty()) return "" //проверка условий
Что сделает код ниже, если строка пустая? Что он вернет?

2016-11-24 12:19 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (counter == 4) return result.reversed() //revers из-за прохода с конца
Ваш код должен естественным образом обеспечивать возврат нормального значения (например, через правильное условие остановки внешнего цикла)

2016-11-24 12:20 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    return cosus % (2 * Math.PI)
Подумайте над первопричиной того, что у вас не `заходит по тестам`. Может быть, вы где-то не совсем правильно считаете?

2016-12-04 20:04 UTC, ice-phoenix commented
Идем во вкладку `Files changed` и исправляем все оставшиеся замечания. Когда все их исправим, тогда будем говорить дальше.

2016-12-09 12:44 UTC, ice-phoenix commented
recheck all

2016-12-09 14:05 UTC, ice-phoenix requested changes

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +fun trackLength(x1: Double, y1: Double, x2: Double, y2: Double): Double = (sqrt(sqr(x2 - x1) + sqr(y2 - y1)))
[Здесь и много где] Лишние скобки вокруг законченных выражений

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson1/task1/Simple.kt
> +    val persentPerYear = percent / 100.0 + 1
Все же `percentPerYear`

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson2/task1/IfElse.kt
> +                <= max * max) -> 2
Можно просто `<`

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson2/task2/Logical.kt
> +        ((x1 == x2)
Можно без скобок вокруг первого `||`

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i: Int = 2
* Система типов Котлина выведет тип переменной автоматически

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i: Int = n - 1
* Система типов Котлина выведет тип переменной автоматически
* Нельзя ли уточнить верхнюю границу на возможные делители числа `n`?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        m <= pow(sqrt(n.toDouble()).toInt(),2)
Форматирование кода + для округления следует использовать специальные функции `floor / ceil / round`

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +            if (sqrtResult * sqrtResult in m..n) return true
Старый код следует удалять, так как он все равно будет сохранен в системе контроля версий

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var decade = tenNumbers(digitNumber(n))
Зачем вызывать `tenNumbers`? Почему бы (повторюсь еще раз) не написать нормальную функцию `pow`, которую вы тут и сделали, только для одного частного случая?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        if (n1 % 10 == number) count++
Может быть, можно сразу получить результат, если цифры не сошлись?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var result: Int
Зачем вы разделили определение и объявление переменной?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    } catch (e: NumberFormatException) {
Зачем???

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +            0.0
Зачем???

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        if (list[i] > 9) str1.append((87 + list[i]).toChar())
Почему 87, а не 394?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else str1.append((list[i]).toString())
Лишние скобки

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    var str1 = StringBuilder()
Зачем `var`?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    for (i in (digits.size - 1) downTo 0) result += (digits[i] * pow(base, ((digits.size - 1) - i)))
Очень много лишних скобок

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +    }
* Форматирование кода
* Объясните в комментарии, пожалуйста, как именно работает этот код

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        else list += ((str[i]).toInt() - 87)
Может быть, 88?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +                result.append(rom[i])
Вместо двух списков --- список пар

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson4/task1/List.kt
> +        var i = 12
Почему 12?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            result.append(parse[0].padStart(2, '0') + ".")
Вместо `StringBuilder.append(a + b)` лучше `append(a); append(b)`

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            result.append("." + parse[2].toInt().toString())
Почему мы проверяем год на то, что он число, но не проверяем число?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            else result.append(parse[0].toInt().toString() + " ")
Может быть, это можно записать проще?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            && (it !in '0'..'9'))})
Это можно записать проще через `it !in "..."`

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (result[0] != '+') {
Почему?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: StringIndexOutOfBoundsException) {
Этого исключения быть не должно

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +            return throw IllegalArgumentException("IllegalArgumentException")
См. замечание выше

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: StringIndexOutOfBoundsException) {
Этого исключения быть не должно

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    return result
Форматирование кода

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var resultExpression = expression
Зачем???

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if ((littleReg[i] == littleReg[i + 1]) && (littleReg[i] != "")) return sum
Вместо второй проверки пустые строки следует отфильтровать предварительно

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val maxNum = Regex("[0-9.]+").findAll(description).map { it.value.toDouble() }.max() // нахождение макс числа
Что будет, если название товара содержит точку или цифру?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    var result = ""
Зачем вам эта переменная?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val font_Rom = listOf("I", "IV", "V", "IX", "X", "XL", "L", "XC", "C", "CD", "D", "CM", "M")
`camelCase`

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    val font_Ar = listOf(1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000)
Список пар вместо двух списков, связанных индексом

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (roman.substring(posit, font_Rom[n].length + posit) == font_Rom[n]) {
Это лучше сделать через `regionMatches`

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    if (roman.length == 1) { //когда один символ
Зачем отдельно обрабатывать этот случай?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +            if (points[i].distance(points[j]) > max) {
Фигурные скобки

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +                , radius = diameter.begin.distance(diameter.end) / 2.0)
Форматирование кода

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        var y:Double
Зачем вы разделили определение и объявление переменных?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    var anglee:Double
Зачем вы разделили определение и объявление переменной?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +        return (Line(s.begin, Math.abs(anglee))) else return (Line(s.begin, -Math.abs(anglee)))
Зачем эта проверка?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +                (lineBySegment(Segment(a, b)).angle + (Math.PI / 2)) % (Math.PI))
Форматирование кода

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson6/task1/Geometry.kt
> +    val x12 = a.x - b.x
Лучше не `x12`, а `xab` здесь и далее

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        for (column in 0..width - 1) matrix[row, column] = e
Форматирование кода

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                    width == other.width
Почему содержимое матрицы никак не участвует в равенстве?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +                sb.append(this[row, column])
Как будем разделять элементы?

2016-12-09 14:05 UTC, ice-phoenix commented on src/lesson7/task1/Matrix.kt
> +        result = result * 31 + width
См. замечание выше

2016-12-09 14:06 UTC, ice-phoenix commented
recheck all

2016-12-14 21:00 UTC, mglukhikh commented
recheck all

2016-12-18 21:01 UTC, ice-phoenix commented
recheck all

2016-12-18 21:23 UTC, ice-phoenix requested changes
Я бы посмотрел задачки и дальше, но с учетом вашего "подхода" к исправлению замечаний, не хочу тратить на это ни свое, ни ваше время

2016-12-18 21:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +    var i = n - 1
Может быть, есть граница поточнее для делителей?

2016-12-18 21:23 UTC, ice-phoenix commented on src/lesson3/task1/Loop.kt
> +        m <= pow(sqrt(n.toDouble()).toInt(), 2)
Для округления следует использовать специальные функции `floor / ceil / round`

2016-12-18 21:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +                result.append(" ")
Вместо того, чтобы продолжать мучать один и тот же кусок кода, может быть, стоило действительно сесть и действительно подумать? Или хотя бы спросить у преподавателя на занятии, что не так?

2016-12-18 21:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +    } catch (e: StringIndexOutOfBoundsException) {
Этого исключения быть не должно

2016-12-18 21:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        })
Это можно записать через `it in "..."`

2016-12-18 21:23 UTC, ice-phoenix commented on src/lesson5/task1/Parse.kt
> +        if (result[0] != '+') {
Почему?

2016-12-18 21:27 UTC, ice-phoenix commented
Учитывая все замечания, ваш подход к их исправлению в частности и ко всему курсу в целом, ничего выше "Удовлетворительно" я вам предложить не могу. Если вы не согласны с этим решением, с удовольствием встретимся с вами на экзамене!

2017-07-26 18:24 UTC, closed without merging